### ISSUE TITLE
Coredump uploading isn't working

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1082]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: 3.1.0.rc2-0.20190624.433cb93f7.el7.x86_64

### Logs
* test_id: fed493bf-339e-41ab-ab78-f710fb322385
* jenkins job: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-200gb-48h/4/
* job log: 

### Description
There was a coredump and it wasn't sct didn't found it and upload it to s3

**Comment by fruch** [comment]
I think I've found the issue that in our AMI the 
`ulimit -c` is 0
hence no core dump files

**Comment by bentsi** [comment]
@fruch is this fixed?

**Comment by bentsi** [comment]
@fruch why did you close it? Is it fixed?
