### ISSUE TITLE
Not all logs are uploaded to s3

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1090]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: latest master

### Logs
* test_id: 0a61ddd3-583e-484e-9fdc-8d87fea93b85

### Description

Original Jenkins archive saved all files in latest/ directory. It has a web view by jenkins webpage, and jenkins provides zip links for sub-directory, it's easy to share.

Currently we upload log files to s3, but not all.

![image](https://user-images.githubusercontent.com/309708/60319588-74d2b700-99a9-11e9-9efa-30533d7a4b2d.png)

Split db logs are useful even we can find everything in job.log.

@fruch

**Comment by bentsi** [comment]
done in #1073
