### ISSUE TITLE
Debug and fix write-counter stress being stuck

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#1112]
it has been observed repeatedly on longevities 3 and 4 hours jobs for 3.1 ([3h](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-10gb-3h/) and [4h](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-100gb-4h/))

it has been observed that the job stops reporting, and it gets stuck very often.
also, as there is an issue with the timeout, the stress job is being killed much after the test times out

**Comment by amoskong** [comment]
I also touched the counter_write stuck in longevity-50gb-4days jobs.
Just reported an issue: https://github.com/scylladb/scylla-tools-java/issues/101
cassandra-stress: counter_write workload will stuck after write all population[ #101](https://github.com/scylladb/scylla-tools-java/issues/101)

**Comment by bentsi** [comment]
this is a known issue: https://github.com/scylladb/scylla-tools-java/issues/54
