### ISSUE TITLE
Missing lines in sct.log from one of the nodes

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1133]
### Prerequisites

* [x] Are you rebased to master ?
* [] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1-staging
* **scylla**: 3.0.8-0.20190627.23da53c4f

### Logs
* test_id: 150b6c8e-4586-45fd-8a84-26f8718e5a7b
* job log: https://s3.console.aws.amazon.com/s3/object/cloudius-jenkins-test/150b6c8e-4586-45fd-8a84-26f8718e5a7b/job_log.zip?region=eu-west-1&tab=overview
* the relevant journalctl from the node can be found here:
gs://scratch.scylladb.com/balalis/journalctl_t_scylla.txt (google cloud)

### Description

Some of the lines from the jounalctl of one of the nodes (10.0.39.222) is missing from the sct.log, namely the backtrace the node experienced. (TimeStamp - Jul 08 11:47:52)

**Comment by fruch** [comment]
addressed by #1153
