### ISSUE TITLE
The test result (for example, assertion) or code failure is not printed in the sct.log

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1181]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Description

If the test failed/not passed because of code failure or assertion (test is not passed), we can't find the error (traceback or assertion result) in the sct.log. Just after the tearDown will be completed, the error/result will be printed to the console and out.log (not in the sct.log)

Actually, any test result is not appeared in the sct.log

**Expected behavior:** 
- The error traceback is printed immediately when it happened to the console and into sct.log 
- Test result is printed in the sct.log

**Comment by bentsi** [comment]
@juliayakovlev thanks for reporting, we have a task for that in our Queue
