### ISSUE TITLE
SCT doesn't support monitoring master branch

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#1189]
Running a test with the following configuration fails:
`monitor_branch: 'master'`

At first it failed on lack of python3, so I have added the following lines to install_scylla_monitoring_preqs in the rehl section:
```
yum install -y python36
yum install -y python36-pip
python3 -m pip install --upgrade pip
python3 -m pip install pyyaml
```
This advanced but fails on the actual start script.
The log says:

```
Command: 'bash -ce \'\ncd /home/centos/scylla-monitoring-master\nmkdir -p /home/centos/scylla-monitoring-data\n./start-all.sh             -s /home/centos/scylla-monitoring-master/config/scylla_servers.yml             -n /home/centos/scylla-monitoring-master/config/node_exporter_servers.yml             -d /home/centos/scylla-monitoring-data -l -v master,master -b "-web.enable-admin-api"\n\''
< t:2019-07-23 07:11:32,999 f:cluster.py      l:2211 c:sdcm.cluster         p:ERROR > 
< t:2019-07-23 07:11:32,999 f:cluster.py      l:2211 c:sdcm.cluster         p:ERROR > Exit code: 1
```

It is important in order for SCT to serve as a metrics testing tool in addition to Scylla testing tool that we support this.

**Comment by fruch** [comment]
is the failure cause of master is pass twice ?

I.e. you didn't attached the stdout and stderr of the failed command.

when did scylla-monitoring moved to python3 ?

**Comment by eliransin** [comment]
>is the failure cause of master is pass twice ?

I don't understand the question

>I.e. you didn't attached the stdout and stderr of the failed command.

Yes I did:
> Command: 'bash -ce \'\ncd /home/centos/scylla-monitoring-master\nmkdir -p /home/centos/scylla-monitoring-data\n./start-all.sh             -s /home/centos/scylla-monitoring-master/config/scylla_servers.yml             -n /home/centos/scylla-monitoring-master/config/node_exporter_servers.yml             -d /home/centos/scylla-monitoring-data -l -v master,master -b "-web.enable-admin-api"\n\''
< t:2019-07-23 07:11:32,999 f:cluster.py      l:2211 c:sdcm.cluster         p:ERROR > 
< t:2019-07-23 07:11:32,999 f:cluster.py      l:2211 c:sdcm.cluster         p:ERROR > Exit code: 1

>when did scylla-monitoring moved to python3 ?

gitblame output (from the scylla monitoring branch): 
`12e3b41c (Amnon Heiman  2019-06-20 10:41:00 +0300  1) #!/usr/bin/python3`

/cc @amnonh

**Comment by fruch** [comment]
@eliransin 

I think I've found the issue, seem like now the monitoring expect a list of mangers address, even that we don't use manager

I think call in this before ./start-all.sh should fix the problem, for now:
`cp prometheus/scylla_manager_servers.example.yml prometheus/scylla_manager_servers.yml`

we should later support patching a real monitor if we install it (I think we install it only after installing the monitor)

**Comment by roydahan** [comment]
@eliransin does it work for you with branch-3.0 of monitoring?

**Comment by eliransin** [comment]
I didn't try since branch-3.0 didn't exist when I opened this issue. But after consulting with Amnon, I understand that the master branch I worked on is what now became branch-3.0 so if it works for you the issue.
* I think it will only work if you have added support for python3 and the python3 dependancies.
