### ISSUE TITLE
support aggregating the results of multiple c-s (also in the plot)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-cluster-tests#121]
we support running multiple loaders

we need to support aggregation of the results at the end and also aggregation durring execution to plot the aggregated load in the system.

how should we plot the latency (we should not aggregate them) - maybe we should have a bar at each point showing the difference between the loaders - if the bar is small the difference is small if the bar is large the difference is large.

**Comment by slivne** [comment]
sample

```
^[[Ashlomi@localhost~/urchin-ccm (support_for_prometheus)$ ccm node1 stress write n=100000 -rate threads=4
INFO  12:58:32 Found Netty's native epoll transport in the classpath, using it
INFO  12:58:32 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  12:58:32 New Cassandra host /127.0.0.1:9042 added
Connected to cluster: scylla-1
Datatacenter: datacenter1; Host: /127.0.0.1; Rack: rack1
Created keyspaces. Sleeping 1s for propagation.
Sleeping 2s...
Warming up WRITE with 50000 iterations...
Running WRITE with 4 threads for 100000 iteration
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
total,         10648,   10647,   10647,   10647,     0.4,     0.2,     0.4,     2.2,    24.4,   110.3,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
total,         27705,   16977,   16977,   16977,     0.2,     0.2,     0.4,     0.5,     4.1,    11.2,    2.0,  0.12254,      0,      0,       0,       0,       0,       0
total,         38310,   10536,   10536,   10536,     0.4,     0.2,     0.5,     2.7,    15.5,   129.1,    3.0,  0.09865,      0,      0,       0,       0,       0,       0
total,         55022,   16648,   16648,   16648,     0.2,     0.2,     0.4,     0.6,     4.9,    11.4,    4.0,  0.08318,      0,      0,       0,       0,       0,       0
total,         67111,   11936,   11936,   11936,     0.3,     0.2,     0.5,     4.0,    11.5,    16.4,    5.0,  0.07594,      0,      0,       0,       0,       0,       0
total,         76134,    8745,    8745,    8745,     0.4,     0.2,     2.0,     5.0,    10.1,    22.5,    6.1,  0.08947,      0,      0,       0,       0,       0,       0
total,         89624,   13401,   13401,   13401,     0.3,     0.2,     0.5,     1.9,     8.3,    14.1,    7.1,  0.07644,      0,      0,       0,       0,       0,       0
total,        100000,   15033,   15033,   15033,     0.3,     0.2,     0.4,     1.0,     3.7,     9.1,    7.8,  0.06773,      0,      0,       0,       0,       0,       0


Results:
op rate                   : 12892 [WRITE:12892]
partition rate            : 12892 [WRITE:12892]
row rate                  : 12892 [WRITE:12892]
latency mean              : 0.3 [WRITE:0.3]
latency median            : 0.2 [WRITE:0.2]
latency 95th percentile   : 0.4 [WRITE:0.4]
latency 99th percentile   : 1.8 [WRITE:1.8]
latency 99.9th percentile : 8.4 [WRITE:8.4]
latency max               : 129.1 [WRITE:129.1]
Total partitions          : 100000 [WRITE:100000]
Total errors              : 0 [WRITE:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:00:07
END
```

So lets start from the RESULTS parts given that we want to produce the aggregation of two c-s running in parallel 

op rate                   : X{op rate} + Y{op rate}
partition rate            : X{partition rate} + Y{partition rate}
row rate                  : X{row rate} + Y{row rate}  [WRITE:X{row rate}{WRITE} + Y{row rate}{WRITE}]
latency mean              : (X{latency mean}*X{op rate} + Y{latency mean}*Y{op rate})/(X{op rate} + Y{op rate} [WRITE: (X{latency mean}{WRITE}*X{row rate}{WRITE} + Y{latency mean}{WRITE}*Y{row rate}{WRITE})/(X{row rate}{WRITE} + Y{row rate}{WRITE}]
latency median            : 0.2 [WRITE:0.2]
latency 95th percentile   : (X{latency 95th percentile}*X{op rate} + Y{latency 95th percentile}*Y{op rate})/(X{op rate} + Y{op rate} [WRITE: (X{latency 95th percentile}{WRITE}*X{row rate}{WRITE} + Y{latency 95th percentile}{WRITE}*Y{row rate}{WRITE})/(X{row rate}{WRITE} + Y{row rate}{WRITE}]
latency 99th percentile   : (X{latency 99th percentile}*X{op rate} + Y{latency 99th percentile}*Y{op rate})/(X{op rate} + Y{op rate} [WRITE: (X{latency 99th percentile}{WRITE}*X{row rate}{WRITE} + Y{latency 99th percentile}{WRITE}*Y{row rate}{WRITE})/(X{row rate}{WRITE} + Y{row rate}{WRITE}]
latency 99.9th percentile : (X{latency 99.9th percentile}*X{op rate} + Y{latency 99.9th percentile}*Y{op rate})/(X{op rate} + Y{op rate} [WRITE: (X{latency 99.9th percentile}{WRITE}*X{row rate}{WRITE} + Y{latency 99.9th percentile}{WRITE}*Y{row rate}{WRITE})/(X{row rate}{WRITE} + Y{row rate}{WRITE}]
latency max               : (X{latency max}*X{op rate} + Y{latency max}*Y{op rate})/(X{op rate} + Y{op rate} [WRITE: (X{latency max}{WRITE}*X{row rate}{WRITE} + Y{latency max}{WRITE}*Y{row rate}{WRITE})/(X{row rate}{WRITE} + Y{row rate}{WRITE}]
Total partitions          :  X{total partitions} + Y{total partitions}  [WRITE:X{total partitions}{WRITE} + Y{total partitions}{WRITE}]
Total errors                : X{total errors} + Y{total errors}  [WRITE:X{total errors}{WRITE} + Y{total errors}{WRITE}]
.
.

the same should be applied to the execution in each line where we should do aggregation on line bases based on time stamp (but lets do it step 2)

**Comment by penberg** [comment]
@slivne Can't you use ``cassandra-stress`` daemon mode for this?

**Comment by slivne** [comment]
good question lets test it out and see if it provides what we need

**Comment by kongove** [comment]
@penberg c-stress daemon accepts commands from multiple clients, but the results are displayed in output of each client, it's not aggregated.

**Comment by amoskong** [comment]
We already aggregated the results before reported to ES.
