### ISSUE TITLE
event: Backtrace content are repeated

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1228]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: branch-3.1

### Logs
* test_id: 6183c9a8-a99f-4e77-bc8e-f8143e1c4ce7 
* events log: https://cloudius-jenkins-test.s3.amazonaws.com/6183c9a8-a99f-4e77-bc8e-f8143e1c4ce7/events_log.zip
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/6183c9a8-a99f-4e77-bc8e-f8143e1c4ce7/job_log.zip

### Description

event: Backtrace content are repeated in sct.log & events.log

**Actual behavior:** 

```
2019-08-15T09:21:17+00:00  rolling-upgrade-3-1-centos-db-node-6183c9a8-0-3 !INFO    | scylla: Backtrace:

0x00000000006aa6e2
0x00000000006aa6e2
0x00000000005c1e0c
0x00000000005c1e0c
0x00000000005c22c6
0x00000000005c22c6
/lib64/libpthread.so.0+0x000000000000f5cf
/lib64/libpthread.so.0+0x000000000000f5cf
/lib64/libc.so.6+0x00000000000c4fac
/lib64/libc.so.6+0x00000000000c4fac
/lib64/libc.so.6+0x00000000000c4e43
/lib64/libc.so.6+0x00000000000c4e43
/lib64/libfreebl3.so+0x0000000000000e21
/lib64/libfreebl3.so+0x0000000000000e21
/lib64/libfreebl3.so+0x0000000000000f30
/lib64/libfreebl3.so+0x0000000000000f30
/lib64/libcrypt.so.1+0x0000000000002ff9
/lib64/libcrypt.so.1+0x0000000000002ff9
/lib64/libcrypt.so.1+0x0000000000000fcf
/lib64/libcrypt.so.1+0x0000000000000fcf
0x0000000003ac7dd3
0x0000000003ac7dd3
```

**Comment by fruch** [comment]
seen this a few more times in:
https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/rolling-upgrade/job/rolling-upgrade-centos7/82/execution/node/40/log/
