### ISSUE TITLE
Connect the cluster into a prometheus backend that will collect the metrics and download the data at the end 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-cluster-tests#123]
We are collecting the c-s
We are not collecting the metrics of scylla
It will be helpfull if we can download the metrics from scylla so that it will help initial analysis 

The direction is to setup https://github.com/scylladb/scylla-grafana-monitoring and have it point to the scylla nodes

We will work toward having promethus on the AMI / scylla_setup so this part should be done in the near future. 

The real work is to start the prmoethues/graphana up
Download the db
Check that we can later reuse the download db in another instance run locally

How large are the artifacts 

We may want later to save everything in git or some other db.

**Comment by lmr** [comment]
Solved by https://github.com/scylladb/scylla-cluster-tests/commit/dbca350c295d635f0171673c08c8c50a405d41a2
