### ISSUE TITLE
seed node hangs when /usr/sbin/raid-check is run (01:00 at Sunday)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1243]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: branch-3.1

### Logs
* test_id: bef4a568-feba-41df-bf15-e88eee6955c0
* job log:: 
https://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-100gb-4h/51
https://cloudius-jenkins-test.s3.amazonaws.com/bef4a568-feba-41df-bf15-e88eee6955c0/job_log.zip

### Description

Running a longevity of 4 hours during early Sunday, the seed node seem to get stuck when getting to the time 
```
153431:< t:2019-08-25 01:00:15,810 f:cluster.py      l:1212 c:sdcm.cluster         p:DEBUG > 2019-08-25T01:00:01+00:00  ip-172-30-0-49 !INFO    | CROND[33491]: (root) CMD (/usr/sbin/raid-check)
```

**Comment by roydahan** [comment]
@fruch isn't it a scylla issue?
What is the recommendation to do here?

**Comment by fruch** [comment]
I didn't had enough information suggesting it's a Scylla issue. That was the only thing I've found, but didn't had much more data.

Open it here until we'll see it again

**Comment by fruch** [comment]
never seen this again
