### ISSUE TITLE
unable to get grafana annotations

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1270]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: 3.1.rc4

### Logs
* test_id:  4586343b-185e-42f1-8272-6b3708c5977f
* test job: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/75/execution/node/40/log/
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/4586343b-185e-42f1-8272-6b3708c5977f/job_log.zip

### Description

`< t:2019-08-28 21:51:08,286 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.142.0.182:3000`

`p:WARNING > unable to get grafana annotations [HTTPConnectionPool(host='10.142.0.182', port=3000): Max retries exceeded with url: /api/annotations (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe95c691a10>: Failed to establish a new connection: [Errno 111] Connection refused',))]`

### Steps to Reproduce

I see this issue multiple times in upgrade_test of 3.1

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

```
05:57:33  ERROR [678.654s]: test_rolling_upgrade (upgrade_test.UpgradeTest)
05:57:33  ----------------------------------------------------------------------
05:57:33  Traceback (most recent call last):
05:57:33    File "/sct/sdcm/tester.py", line 133, in wrapper
05:57:33      args[0].tearDown()
05:57:33    File "/sct/sdcm/tester.py", line 1380, in tearDown
05:57:33      self.finalize_test()
05:57:33    File "/sct/sdcm/tester.py", line 1290, in finalize_test
05:57:33      self.collect_logs()
05:57:33    File "/sct/sdcm/tester.py", line 1586, in collect_logs
05:57:33      logs_dict["monitoring_stack"] = self.monitors.download_monitoring_data_stack()
05:57:33    File "/sct/sdcm/cluster.py", line 3831, in download_monitoring_data_stack
05:57:33      local_path_to_monitor_stack = self.get_monitoring_data_stack(node)
05:57:33    File "/sct/sdcm/cluster.py", line 3818, in get_monitoring_data_stack
05:57:33      f.write(annotations_json)
05:57:33  TypeError: must be unicode, not None
05:57:33  
05:57:33  ----------------------------------------------------------------------
05:57:33  Ran 1 test in 678.655s
05:57:33  
05:57:33  FAILED (errors=1)
```

/CC @fruch

**Comment by fruch** [comment]
FYI, 
the read issue was a failure to create db nodes:
```
< t:2019-08-28 21:50:19,792 f:cluster.py      l:2351 c:sdcm.cluster         p:ERROR > E: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages.xz  Hash Sum mismatch
< t:2019-08-28 21:50:19,792 f:cluster.py      l:2351 c:sdcm.cluster         p:ERROR > E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by amoskong** [comment]
Yes. After my fix, it can still collect logs for us, not fail the job in
get_monitoring_data_stack().
