### ISSUE TITLE
Issue with uploading prometheus data

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1286]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: 3.1.0.rc4
* **scylla-monitoring**: branch 3.0

### Logs
* test_id: 3d5f9865-42b2-460e-8a41-cf6392bc1034
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/3d5f9865-42b2-460e-8a41-cf6392bc1034/job_log.zip

### Description

At the end of large partition longevity, the prometheus snapshot failed to be created:
```
11:43:31  < t:2019-09-02 08:43:28,524 f:common.py       l:198  c:utils                p:INFO  > Create prometheus snapshot [try #0]
11:43:31  < t:2019-09-02 08:43:28,635 f:db_stats.py     l:148  c:sdcm.db_stats        p:ERROR > Prometheus returned error: {u'status': u'error', u'errorType': u'internal', u'error': u'create snapshot: snapshot head block: write compaction: found chunk with minTime: 1567413603582 maxTime: 1567413808582 outside of compacted minTime: 1567404000000 maxTime: 1567413808383'}
11:43:31  < t:2019-09-02 08:43:28,636 f:cluster.py      l:3651 c:sdcm.cluster         p:ERROR > Cluster longevity-large-partitions-4d-3-1-monitor-set-3d5f9865 (AMI: ['ami-0ff760d16d9497662'] Type: t3.large): Error downloading prometheus data dir: 'NoneType' object has no attribute '__getitem__'
```

**Comment by fruch** [comment]
@aleksbykov have you seen this failures before ?

**Comment by aleksbykov** [comment]
@fruch sorry for long delay. Saw it before, but it can't catch it. Now i found the problem, why it happened. problem  in PrometheusDBStats.request. If request finished with error, it returns None.
Prepare the fix.

**Comment by fruch** [comment]
@aleksbykov fixing the None, isn't enough. we still don't have the snapshot, not even in very short duration jobs:
https://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-10gb-3h/71/console
https://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-100gb-4h/66/console

we need it working, can we stop the Prometheus before taking the snapshot ?
