### ISSUE TITLE
sct.log size becomes zero during test and test fails

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1291]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 
78d48b4 - (HEAD -> longevity_50gb, origin/longevity_50gb) append_scylla_args: '--reactor-backend epoll' (3 days ago) <Yaron Gilor>
eb21a50 - (upstream/master, master) Minor updates to 1000 keyspaces use case (4 days ago) <Israel Fruchter>

* **scylla**: 3.1 rc 5

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description
run a longevity 50gb job in jenkins.
cluster gets up and running with load.
after few hours sct.log file size becomes zero and no test log report is available.
the jenkins job had an error of no space left on device.

job dir content is:
```
$ ssh -l jenkins -p 22 -i /home/yarongilor/.ssh/scylla-qa-ec2 eu_builder2 ls -ralth /jenkins/slave/workspace/scylla-staging/Longevity_yaron/longevity-50-gb/scylla-cluster-tests/20190905-152134-434932
total 3.5M
-rw-r--r--  1 jenkins docker    36 Sep  5 15:21 test_id
drwxr-xr-x  2 jenkins docker    66 Sep  5 15:21 events_log
drwxr-xr-x  8 jenkins docker  4.0K Sep  5 15:22 longevity-tls-50gb-4d-longevit-db-cluster-1d3188f1
drwxr-xr-x  5 jenkins docker   226 Sep  5 15:22 longevity-tls-50gb-4d-longevit-loader-set-1d3188f1
drwxr-xr-x  3 jenkins docker   105 Sep  5 15:22 longevity-tls-50gb-4d-longevit-monitor-set-1d3188f1
drwx------ 12 jenkins root     229 Sep  5 15:23 hosts
drwxr-xr-x  8 jenkins docker   282 Sep  5 19:01 .
drwxr-xr-x  3 jenkins docker    64 Sep  5 19:01 collected_logs
drwxrwxr-x 22 jenkins jenkins 4.0K Sep  5 19:01 ..
-rw-r--r--  1 jenkins docker     0 Sep  5 19:51 sct.log
-rw-r--r--  1 jenkins docker  3.5M Sep  5 19:51 output.log
yarongilor@yaron-pc:~/git/scylla-cluster-tests(longevity_50gb)$
```
jenkins job log is:
```
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Longevity_yaron/job/longevity-50-gb/3/execution/node/39/log/?consoleFull
```

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by juliayakovlev** [comment]
I received same issue in the same longevity, just master branch
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-50gb-4days/3/consoleFull
