### ISSUE TITLE
Timeout while running 'wait_until_running' method on AWS instance

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1299]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: 3.1.rc6

### Logs
* test_id: e15330fe-0fcc-4c2c-8837-3c212ab9c198
* jenkins job: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-multi-keyspaces-60h/16
* job log: 

### Description

Restart of node via AWS, failed with Launch Error, and in SCT it look like that:
```
(DisruptionEvent Severity.ERROR): type=end name=RestartThenRepairNode node=Node longevity-1000-keyspaces-3-1-db-node-e15330fe-4 [18.202.236.165 | 10.0.7.58] (seed: False) duration=7071 error=Timeout while running 'wait_until_running' method on AWS instance 'i-05adfaa5a50e55983'
Traceback (most recent call last):
File "/sct/sdcm/nemesis.py", line 1078, in wrapper
result = method(*args, **kwargs)
File "/sct/sdcm/nemesis.py", line 1287, in disrupt
self.call_random_disrupt_method()
File "/sct/sdcm/nemesis.py", line 581, in call_random_disrupt_method
disrupt_method()
File "/sct/sdcm/nemesis.py", line 210, in disrupt_restart_then_repair_node
self.target_node.restart()
File "/sct/sdcm/cluster_aws.py", line 427, in restart
self._instance_wait_safe(self._instance.wait_until_running)
File "/sct/sdcm/cluster_aws.py", line 390, in _instance_wait_safe
raise cluster.NodeError(msg)
NodeError: Timeout while running 'wait_until_running' method on AWS instance 'i-05adfaa5a50e55983'
``

I think we need some retries if it's starting to happen more often,
this why I've raise the issue, to collect more information

**Comment by fruch** [comment]
After I've started the node again two times manually it came up.
I thinking exponential back-offs, cause those is really confusing if the test keep running

**Comment by fruch** [comment]
Happens again on a few jobs at the same time:

https://jenkins.scylladb.com/job/manager-2.6/job/centos-sanity-test/30

**Comment by fruch** [comment]
Sounds to me like an issue with spot creation in AWS, that we aren't dealing very good.

**Comment by fruch** [comment]
happened again today:
this is the error on the ec2 console:
`Server.InternalError: Internal error on launch`

**Comment by roydahan** [comment]
@fruch are you on this or to assign?

**Comment by fruch** [comment]
> > @fruch are you on this or to assign?
> 
> I'm not sure we have what assign, it's clearly a fault on ec2 in those cases.
> 
> What do we want ? more information ? event with "Server.InternalError: Internal error on launch" ?

notice this issue is from 2019...
