### ISSUE TITLE
Can't open monitoring data using SCT latest versions

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#1351]
https://github.com/scylladb/scylla/issues/4999 has some monitoring that needs to be inspected.
The command offered there (https://github.com/scylladb/scylla/issues/4999#issuecomment-533105613) is:
`hydra investigate show-monitor 6cbbc65c-755f-43b9-a879-e7b281d8c5d0`
The command didn't work out of the box:
First the command had to be adapted to use the branche's hydra script:
`docker/env/hydra.sh investigate show-monitor 6cbbc65c-755f-43b9-a879-e7b281d8c5d0`
And second only a specific commit (c9abcb7) which is from master worked , while the issue 
was run using sct branch-3.1 AFAIK.
So eventually we ended up with:
```
git checkout c9abcb7
docker/env/hydra.sh investigate show-monitor 6cbbc65c-755f-43b9-a879-e7b281d8c5d0
```

Some more details:
branch-3.1(4402494d203ce02f493fbe51800d92ef87596a38) doesn't support reading this monitoring and get stuck with the following line:
`docker/env/hydra.sh investigate show-monitor 6cbbc65c-755f-43b9-a879-e7b281d8c5d0`
master (782ce11b07cb544e942d6d6932b85569adf5e669) doesn't support the reading also, it 
just ends without any docker in place:
```
[eliransin@localhost sct]$ docker/env/hydra.sh investigate show-monitor 6cbbc65c-755f-43b9-a879-e7b281d8c5d0
Docker version 19.03.2, build 6a30dfca03
Image up-to-date
Obtaining QA SSH keys...
QA private key '/home/eliransin/.ssh/scylla-qa-ec2' exists. Nothing to update.
QA private key '/home/eliransin/.ssh/scylla-test' exists. Nothing to update.
QA private key '/home/eliransin/.ssh/support' exists. Nothing to update.
QA SSH keys obtained.
Making sure the ownerships of results directories are of the user
Search monitor stack archive files for test id 6cbbc65c-755f-43b9-a879-e7b281d8c5d0 and restoring...
Checking that docker is available...
Docker is available
Download file https://cloudius-jenkins-test.s3.amazonaws.com/6cbbc65c-755f-43b9-a879-e7b281d8c5d0/monitoring_data_stack_branch-2.4_3.1.tar.gz to directory /tmp/tmptMPNTu
Extracting data from archive 6cbbc65c-755f-43b9-a879-e7b281d8c5d0/monitoring_data_stack_branch-2.4_3.1.tar.gz
LocalCmdRunner [eliransin@SCT-CONTAINER]: Command "
cd /tmp/tmptMPNTu/6cbbc65c-755f-43b9-a879-e7b281d8c5d0
tar -xvf monitoring_data_stack_branch-2.4_3.1.tar.gz
" finished with status 0
Extracting data finished
Monitoring stack restored
+-------------------------------------------------------+
|                Grafana monitoring stack               |
+-------------------+-----------+-----------------------+
| Name              | container | Link                  |
+-------------------+-----------+-----------------------+
| Prometheus server | aprom     | http://localhost:9090 |
| Grafana server    | agraf     | http://localhost:3000 |
+-------------------+-----------+-----------------------+
[eliransin@localhost sct]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
We have found a working commit from master with an older docker image version (0.45), this is:
c9abcb7
There might be newer commits that also supports it but the branches themselves doesn't.

**Comment by fruch** [comment]
@eliransin funny thing is I've just noticed this issue a few minutes ago..., thanks for reporting it.

**Comment by eliransin** [comment]
10x @fruch , that was super fast :+1:
