### ISSUE TITLE
c:sdcm.sct_events p:ERROR > failed to format timestamp:[-61543785157]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cluster-tests#1362]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 97e371328c598d254b854523c91bee4fbb13afa1
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/bentsi-staging/job/bentsi-byo-longevity-sstable-corrupt-repr/6/consoleFull

### Description

See https://github.com/scylladb/scylla/issues/4971#issuecomment-538604292
> [2019-10-03T16:07:40.008Z] < t:2019-10-03 16:07:38,345 f:sct_events.py l:147 c:sdcm.sct_events p:ERROR > failed to format timestamp:[-61543785157] < t:2019-10-03 16:07:38,345 f:sct_events.py l:147 c:sdcm.sct_events p:ERROR > failed to format timestamp:[-61543785157]

**Comment by fruch** [comment]
@bhalevy FYI, we are aware of this issue, and it's a minor one related on to the SCT events, i.e. this is no what cause the failure in scylladb/scylla#4971 reproductions

**Comment by bhalevy** [comment]
Yes, I didn't think it was the cause of scylladb/scylla#4971. Regardless, it better be taken care of :)

**Comment by fruch** [comment]
we don't have this parsing code anymore
