### ISSUE TITLE
sdcm/cluster.py: Fail to parse downloaded scylla.yaml

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#137]
scylla.yaml was downloaded to localhost, but avocado failed to parse it to get seeds ip address.
The output content is blank.

#### Avocado Code: sdcm/cluster.py

    class BaseScyllaCluster(object):

        def get_seed_nodes_private_ips(self):
            if self.seed_nodes_private_ips is None:
                node = self.nodes[0]
                yaml_dst_path = os.path.join(tempfile.mkdtemp(
                    prefix='scylla-longevity'), 'scylla.yaml')
                node.remoter.receive_files(src='/etc/scylla/scylla.yaml',
                                           dst=yaml_dst_path)
                with open(yaml_dst_path, 'r') as yaml_stream:
                    conf_dict = yaml.load(yaml_stream)
                    try:
                        self.seed_nodes_private_ips = conf_dict['seed_provider'][
                            0]['parameters'][0]['seeds'].split(',')
                    except:
                        raise ValueError('Unexpected scylla.yaml '
                                         'contents:\n%s' % yaml_stream.read())
            return self.seed_nodes_private_ips

#### The downloaded scylla.yaml is fine:

    $ grep seed  /var/tmp/scylla-longevityLPTTxz/scylla.yaml
    # seed_provider class_name is saved for future use.
    # seeds address are mandatory!
    seed_provider:
              # seeds is actually a comma-delimited list of addresses.
              - seeds: "172.31.31.137"
    #    connectivity.  (Thus, you should set seed addresses to the public

#### Avocado logs:

    Cluster amostation-jks-scylla-loader-set-2c40a9c2 (AMI: ami-e2246382 Type: c3.large): Setup duration -> 115 s
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): (1/3) DB nodes ready. Time elapsed: 95 s
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): (2/3) DB nodes ready. Time elapsed: 95 s
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): (3/3) DB nodes ready. Time elapsed: 96 s
    PARAMS (key=update_db_binary, path=*, default=None) => ''
    Remote [centos@54.183.174.176]: Receive files (src) /etc/scylla/scylla.yaml -> (dst) /var/tmp/scylla-longevityLPTTxz/scylla.yaml
    Cleaning up resources used in the test
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): Stop nemesis begin
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): Stop nemesis end
    Cluster amostation-jks-scylla-db-cluster-5e5389cb (AMI: ami-e2246382 Type: c3.large): Destroy nodes
    Node amostation-jks-scylla-db-node-5e5389cb-1 [54.183.174.176 | 172.31.31.138] (seed: None): Destroyed
    Node amostation-jks-scylla-db-node-5e5389cb-2 [52.53.173.157 | 172.31.31.139] (seed: None): Destroyed
    [54.183.179.46] [stdout] Jul 20 00:42:10 ip-172-31-31-137 scylla[2158]:  [shard 0] gossip - InetAddress 172.31.31.138 is now DOWN
    [52.53.173.157] [stderr] Connection to 52.53.173.157 closed by remote host.
    Node amostation-jks-scylla-db-node-5e5389cb-3 [54.183.179.46 | 172.31.31.137] (seed: None): Destroyed
    Cluster amostation-jks-scylla-loader-set-2c40a9c2 (AMI: ami-e2246382 Type: c3.large): Destroy nodes
    Node amostation-jks-scylla-loader-node-2c40a9c2-1 [54.67.57.26 | 172.31.30.7] (seed: None): Destroyed
    [54.67.57.26] [stderr] Connection to 54.67.57.26 closed by remote host.
    Key Pair amostation-jks-longevity-test-3b494cb6 -> /var/tmp/amostation-jks-longevity-test-3b494cb6.pem: Destroyed
 
    Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado-37.0-py2.7.egg/avocado/core/test.py:435
    Traceback (most recent call last):
      File "/home/amos/scylladb.com/scylla-cluster-tests/sdcm/tester.py", line 110, in wrapper
        return method(*args, **kwargs)
      File "/home/amos/scylladb.com/scylla-cluster-tests/sdcm/tester.py", line 141, in setUp
        self.db_cluster.wait_for_init()
      File "/home/amos/scylladb.com/scylla-cluster-tests/sdcm/cluster.py", line 1344, in wait_for_init
        self.get_seed_nodes()
      File "/home/amos/scylladb.com/scylla-cluster-tests/sdcm/cluster.py", line 673, in get_seed_nodes
        seed_nodes_private_ips = self.get_seed_nodes_private_ips()
      File "/home/amos/scylladb.com/scylla-cluster-tests/sdcm/cluster.py", line 669, in get_seed_nodes_private_ips
        'contents:\n%s' % yaml_stream.read())
    ValueError: Unexpected scylla.yaml contents:
 
 
    ERROR 1-simple_regression_test.py:SimpleRegressionTest.test_simple_regression -> TestSetupFail: Unexpected scylla.yaml contents:
 
 
    Not logging /proc/slabinfo (lack of permissions)

**Comment by kongove** [comment]
yaml.load(yaml_stream) returns:

    [('cluster_name', 'amostation-jks-scylla-db-cluster-bcade8d4'), ('num_tokens', 256), ('data_file_directories', ['/var/lib/scylla/data']), ('commitlog_directory', '/var/lib/scylla/commitlog'), ('commitlog_sync', 'periodic'), ('commitlog_sync_period_in_ms', 10000), ('commitlog_segment_size_in_mb', 32), ('seed_provider', [[('class_name', 'org.apache.cassandra.locator.SimpleSeedProvider'), ('parameters', [[('seeds', '172.31.18.66')]])]]), ('listen_address', '172.31.18.68'), ('native_transport_port', 9042), ('read_request_timeout_in_ms', 5000), ('write_request_timeout_in_ms', 2000), ('endpoint_snitch', 'SimpleSnitch'), ('rpc_address', '0.0.0.0'), ('rpc_port', 9160), ('api_port', 10000), ('api_address', '127.0.0.1'), ('batch_size_warn_threshold_in_kb', 5), ('partitioner', 'org.apache.cassandra.dht.Murmur3Partitioner'), ('commitlog_total_space_in_mb', -1), ('broadcast_rpc_address', '172.31.18.68'), ('api_ui_dir', '/usr/lib/scylla/swagger-ui/dist/'), ('api_doc_dir', '/usr/lib/scylla/api/api-doc/'), ('auto_bootstrap', False)]

**Comment by lmr** [comment]
I can't reproduce this as per latest master, e027fb6fe57ff0ea979faba529a8e10f2a0fe7c3. Are you still seeing this problem, @kongove ?

**Comment by kongove** [comment]
As we talked in gtalk, the yaml.load() strangely returns list of tuple, parse failed.
And yaml.load() returns regular dict if we write a simple script with same logical in same environment.

yaml.safe_load() works well, we should replace yaml.load() by it when we know the root reason.
