### ISSUE TITLE
In case the c-s that tries to create the keyspace fails, truncate will fail

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#1390]
There is an issue on master, longevity-4h job.
The TruncateMonkey false alarm on InvalidRequest issue when trying to truncate a keyspace named ks_truncate.
The keysapce doesn't exist because the c-s we ran failed.

https://github.com/scylladb/scylla-cluster-tests/blob/546c850c75b23e9010761418f654afbb5822d1f9/sdcm/nemesis.py#L665

First, we need to better handle it and not proceeding to the truncate in case the c-s failed.
This will remove false alarms.

Second, we need to check why the c-s failed and how to solve it.
(maybe to run it from the loader?)
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-100gb-4h/24/

**Comment by fruch** [comment]
@roydahan fixed it
