### ISSUE TITLE
ClusterHealthValidator error "Node(s) 10.0..... exists in the gossip, but doesn't exist in the cluster" explanation

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1421]
disrupt_terminate_and_replace_node nemesis
 
ClusterHealthValidator error ```Node(s) 10.0..... exists in the gossip, but doesn't exist in the cluster``` may be received.
It happens because of terminated node stays a few minutes in the gossip with status ```shutdown```.
Terminated node will be removed by FatClient. 
It may happened that ClusterHealthValidator will run before removing, so the error will be reported.
The message below reporting that the node is removing
```
gossip - FatClient 10.0.... has been silent for 30000ms, removing from gossip
```

Next time the ClusterHealthValidator running, the error won't be reported

**Comment by bentsi** [comment]
fixed in #2074
