### ISSUE TITLE
Please include rpm packages alongside core file

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla-cluster-tests#1502]
A core file by itself is not useful. Every time we have to look at a scylla core the first think to do is try to find the the binaries that produced that core, which is not trivial and gets harder as old jenkins builds are deleted.

Could SCT produce a .tar.(gz,gst,xz, whatever) with, in addition to the core, the rpms:

scylla
scylla-conf
scylla-debuginfo
scylla-kernel-conf
scylla-python3
scylla-server

That would mean that there would be a single file to download before one can start debugging.

**Comment by fruch** [comment]
In some case we might be able to supply them, when we are installing them directly, 

In most cases it's an AMI, and we could supply their versions. but backtracking into the specific ones in our S3 is a bit more complex, and we'll need more order during the creating of the AMI, to get that information.
maybe @hagitsegev or  @penberg have an idea how we turn an AMI into the location of the RPM installed in it.

**Comment by avikivity** [comment]
It's a lot harder for developers who aren't familiar with our artifact repository structure.

**Comment by fruch** [comment]
@avikivity I agree It's also hard for me to find things like that, 
I think I've suggested tagging the AMIs with the paths in S3, but suggestion seem to have gone to /dev/null

I see the talk in scylladb/scylla-pkg#589, might be also usual and we could use the that method.  

I first need some order and breadcrumbs to work with, right now they are not there.

**Comment by espindola** [comment]
I would be equally happy if the bug reports included a link to, for example,
http://download.scylla.com/packages/build-id/

**Comment by fruch** [comment]
@espindola would be easy to add, but first the build need to be arranged in that fashion. i.e. once  scylladb/scylla-pkg#589 comes to a conclusion. we'll be able to build ontop of it.

**Comment by espindola** [comment]
Sounds good to me!
