### ISSUE TITLE
Request to add jenkins job info to gce/aws instances

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1528]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master

### Description

We can find the jenkins Job by checking the instance name prefix, if there many instances, and many jobs, it's difficult to match them.

IN the past, we added current work directory path of sct builder to gce/aws instance as a Tag. It's helpful. But now this tag had been removed in refactor. I request to add the tag back, or add other similar function.

- prompt jobs will trigger upgrade jobs
- private repo testing will trigger upgrade jobs
- artifact-test jobs will trigger upgrade jobs
- we also have some staging upgrade jobs, executed manually
- we have upgrade jobs of master/3.2/3.1/3.0 & 2019.1/2018.1
- we have more than 4 distros (centos7/ubuntu16/ubuntu18/ubuntu14/debian8/debian9)

We have 71 upgrade jobs: https://jenkins.scylladb.com/search/?q=upgrade

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

We can easy to know which jenkins job created the instance.

**Actual behavior:** [What actually happened]

We have to check the jobs log to match the test id with instance name.

**Comment by fruch** [comment]
@amoskong were using the GCE metadata, and putting there the output of `create_common_tags()`
I do agree it's not really visible in the gcloud console.

But we usually using the `hydra list-resources` I guess we could some of the tags to be visible in `list-resources`

thing is GCE labels are only strings and not a dictionary, that's the main reason why we moved to use metadata instead.
If you want to put it in both, for more usability in the console, I don't mind.

**Comment by amoskong** [comment]
I found the problem, we have the `JenkinsJobTag` (eg value: jenkins-scylla-3.2-rolling-upgrade-rolling-upgrade-centos7-31), this tag is enough for me although it doesn't contain the full path with parent directories. But the tags were lost in the end, related issue: https://github.com/scylladb/scylla-cluster-tests/issues/1539

![image](https://user-images.githubusercontent.com/309708/70629591-2ff3c180-1c65-11ea-97f3-32ba4f7bd8ae.png)
