### ISSUE TITLE
gce & aws: keep-on-failure doesn't work

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1545]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master / branch-3.2

### Logs
* test_id: 8e00086b-09dd-4657-8050-2b643ac78e3f
* test job:  https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/31/ 

### Description

![image](https://user-images.githubusercontent.com/309708/70667048-e6c66080-1caa-11ea-895e-15cb6b8ffb67.png)

When I use default 'keep-on-failure' to submit the job, the 'keep-alive' tag isn't added to instances correctly. Then the instance will be stopped or killed unexpectedly.

### Steps to Reproduce

1. run any job with default 'keep-on-failure'

**Expected behavior:** [What you expected to happen]

The instances won't be stopped or killed

**Actual behavior:** [What actually happened]

 the 'keep-alive' tag isn't added to instances correctly. Then the instance will be stopped or killed unexpectedly.

**Comment by aleksbykov** [comment]
@amos, Issue in misconfiguration and missing appropriate stages in upgrade pipeline. Trello task is added.
As a quick fix, could be enabled for upgrade pipeline the clean-resources by sct. What do you think?

**Comment by amoskong** [comment]
Hi @aleksbykov The problem still exists.

SCT_EXECUTE_POST_BEHAVIOR had been set to true.

- sct branch: branch-2019.1  (based on branch-3.2)
- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-2019.1/job/rolling-upgrade-centos7/12/consoleFull
- job failed, and instances were destroyed unexpectedly

![image](https://user-images.githubusercontent.com/309708/71142214-b013bb80-2251-11ea-9e06-8d88ce55ba8f.png)

**Comment by aleksbykov** [comment]
@amos. it is work as expected. This happened, because critical.log is empty.The error why the test failed, is not put to critical.log. That why, clean resources take decision to clean resources.
