### ISSUE TITLE
SCT should always run with --abort_on_internal_error

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla-cluster-tests#1579]
We try to avoid aborting when an internal error is found. This makes bugs harder to debug.

There is a compromise in the form of --abort_on_internal_error, which can be used to make aborts optional.

We should always run SCT with --abort_on_internal_error as that should find more bugs and make them easier to debug.

**Comment by amoskong** [comment]
@roydahan had enabled it by default by https://github.com/scylladb/scylla-cluster-tests/commit/6c79e966bef08eec5a8e65a1fd36aef0cd43b013

But it's not backported to sct branch-3.2, and some tests have their own append_scylla_args, the --abort-on-internal-error isn't enabled by them.

```
$ git grep append_scylla_args: test-cases/
test-cases/longevity/longevity-5000-tables.yaml:append_scylla_args: '--blocked-reactor-notify-ms 500'
test-cases/longevity/longevity-in-memory-36GB-4days.yaml:append_scylla_args: '--blocked-reactor-notify-ms 500  --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --in-memory-storage-size-mb 80000'
test-cases/longevity/longevity-multi-keyspaces.yaml:append_scylla_args: '--blocked-reactor-notify-ms 500'
test-cases/performance/perf-regression-latency-1TB.yaml:append_scylla_args: '--blocked-reactor-notify-ms 4'
test-cases/performance/perf-regression-latency-500gb-30min.yaml:append_scylla_args: '--blocked-reactor-notify-ms 4'
test-cases/performance/perf-regression-latency-in-memory.yaml:append_scylla_args: "--in-memory-storage-size-mb 80000 --blocked-reactor-notify-ms 4"
test-cases/performance/perf-regression-user-profiles.yaml:append_scylla_args: '--blocked-reactor-notify-ms 4'
```

**Comment by amoskong** [comment]
I'm wrong, Roy's patch had been backported to 3.2 and 2019.1
https://github.com/scylladb/scylla-cluster-tests/commit/a23b4ebd7f87653071dd2fb48f83ee5d43ae7267

**Comment by espindola** [comment]
@bhalevy

**Comment by roydahan** [comment]
already done.
