### ISSUE TITLE
hydra failed to clean resource of longevity with multiple configure files

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1589]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1

### Logs
* test_id: e8686cd2-18ed-474f-9dee-588dde2ca20a
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/e8686cd2-18ed-474f-9dee-588dde2ca20a/20191218_164333/sct-runner-e8686cd2.zip
* Jenkins job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/EaR-longevity-kmip-200gb-6h-clone/3/console

### Description

hydra failed to clean resource of longevity with multiple configure files.
I also see this problem in ics-longevity of Alex.

### Steps to Reproduce

1. run longevity with multiple config files

**Expected behavior:** 

**Actual behavior:** 

```
00:46:49  + ./docker/env/hydra.sh clean-resources --config-file '["test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml",' '"configurations/hytrust-kmip-ear.yaml"]' --logdir /sct
00:46:49  Running on Build Server...
00:46:49  Docker version 18.09.8, build 0dd43dd87f
00:46:49  Image up-to-date
00:46:49  Obtaining QA SSH keys...
00:46:49  QA private key '/home/jenkins/.ssh/scylla-qa-ec2' exists. Nothing to update.
00:46:49  QA private key '/home/jenkins/.ssh/scylla-test' exists. Nothing to update.
00:46:49  QA private key '/home/jenkins/.ssh/support' exists. Nothing to update.
00:46:49  QA SSH keys obtained.
00:46:49  Making sure the ownerships of results directories are of the user
00:46:50  Usage: sct.py clean-resources [OPTIONS]
00:46:50  Try "sct.py clean-resources --help" for help.
00:46:50  
00:46:50  Error: Got unexpected extra argument (configurations/hytrust-kmip-ear.yaml])
```

**Comment by fruch** [comment]
sounds an escaping issue, why isn't this command uses the environment variable ?

**Comment by aleksbykov** [comment]
@fruch as i remembered, we talked that it is better pass date to command via parameter. 
Change to use env variable
