### ISSUE TITLE
RFC: Find ways to explicitly test slow disks and limited bandwidth

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla-cluster-tests#159]
Some bugs might show up on slow disks or limited bandwidth. We need to think about a consistent way to reproduce such conditions in our testing setup.

**Comment by amoskong** [comment]
We limit the network speed by tc (https://en.wikipedia.org/wiki/Tc_(Linux))


GCE: standard persistent disk - 100G

Operation Type | Read | Write
-- | -- | --
Sustained random IOPS limit | 75.00 | 150.00
Sustained throughput limit (MB/s) | 12.00 | 12.00

**Comment by roydahan** [comment]
https://github.com/scylladb/scylla-cluster-tests/discussions/6299#discussion-5340808
