### ISSUE TITLE
test_lib/compaction.py: AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1590]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1

### Logs
* test_id: fabcd06d-3361-44d4-8eac-2d54b90bcec5
* job: https://jenkins.scylladb.com/job/enterprise-2019.1/view/enterprise-2019.1-test/job/longevity/job/longevity-mv-si-4days/5/

### Description

I see this backtrace when repair failed. the current nemesis is restart_then_repair_node.

### Steps to Reproduce

1.  run https://jenkins.scylladb.com/job/enterprise-2019.1/view/enterprise-2019.1-test/job/longevity/job/longevity-mv-si-4days/5/ws/

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

```
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1115, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1330, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 624, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 875, in disrupt_toggle_table_ics
    self.toggle_table_ics()
  File "/sct/sdcm/nemesis.py", line 741, in toggle_table_ics
    table=table)
  File "/sct/test_lib/compaction.py", line 44, in get_compaction_strategy
    LOGGER.debug("Query result for {}.{} compaction is: {}".format(keyspace, table, compaction.value))
AttributeError: 'str' object has no attribute 'value'

Command: 'nodetool  repair '

Exit code: -1
```

**Comment by amoskong** [comment]
hi @yarongilor is it a sct issue?

**Comment by fruch** [comment]
What mentioned in the title, is an SCT bug.
The repair failure might be the root cause of it

**Comment by amoskong** [comment]
> What mentioned in the title, is an SCT bug.
> The repair failure might be the root cause of it

This issue opened in scylla-cluster-tests project, so it's only about test code issue (the AttributeError).
Here we don't need to care why the repair fail.

(We have scylla issue to track the repair fail)

**Comment by yarongilor** [comment]
That's an interesting scenario bug. i have a simple fix for it but didn't send a PR yet.
the scenario is that a table is selected in order to modify compaction-strategy. but then, on querying all tables, this table is not found. the bug is that "compaction_strategy" variable left as str with the initial value of "N/A" and no updated as a CompactionStrategy enum value.
im still not sure how the test got to this scenario.

**Comment by fruch** [comment]
@yarongilor, can you confirm that  is address already ?

**Comment by yarongilor** [comment]
yes, addressed and fixed.
