### ISSUE TITLE
debian9/ubuntu: ValueError: repo for scylla version 2019.1 wasn't found

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1599]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1 / master

### Logs

- Debian 9: https://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-debian9/21/execution/node/46/log/
- Ubuntu 16: https://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/23/execution/node/58/log/
- Ubuntu 18: https://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04/17/execution/node/58/log/

I didn't find test id in the log of above jobs.

### Description

We switched to private repo from 2019.1, sdcm/utils/common.py:get_s3_scylla_repos_mapping() failed to find valid apt source file of 2019.1 for debian9 / ubuntu16/ ubuntu 18.

### Steps to Reproduce

1. Run upgrade test job from 2019.1

**Expected behavior:** [What you expected to happen]

Valid repo can be found.

**Actual behavior:** [What actually happened]

```
p:ERROR > Traceback (most recent call last):
p:ERROR >   File "./sct.py", line 486, in <module>
p:ERROR >     cli()
p:ERROR >   File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
p:ERROR >     return self.main(*args, **kwargs)
p:ERROR >   File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
p:ERROR >     rv = self.invoke(ctx)
p:ERROR >   File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
p:ERROR >     return _process_result(sub_ctx.command.invoke(sub_ctx))
p:ERROR >   File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
p:ERROR >     return ctx.invoke(self.callback, **ctx.params)
p:ERROR >   File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
p:ERROR >     return callback(*args, **kwargs)
p:ERROR >   File "./sct.py", line 412, in run_test
p:ERROR >     failfast=False, buffer=False, catchbreak=True)
p:ERROR >   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
p:ERROR >     self.parseArgs(argv)
p:ERROR >   File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
p:ERROR >     self.createTests()
p:ERROR >   File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
p:ERROR >     self.module)
p:ERROR >   File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
p:ERROR >   File "/usr/lib64/python2.7/unittest/loader.py", line 109, in loadTestsFromName
p:ERROR >     return self.suiteClass([parent(obj.__name__)])
p:ERROR >   File "/sct/sdcm/tester.py", line 149, in __init__
p:ERROR >     self.params = SCTConfiguration()
p:ERROR >   File "/sct/sdcm/sct_config.py", line 1011, in __init__
p:ERROR >     raise ValueError("repo for scylla version {} wasn't found".format(scylla_version))
p:ERROR > ValueError: repo for scylla version 2019.1 wasn't found
```

/CC @fruch

**Comment by amoskong** [comment]
- https://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04/17/execution/node/57/log/

- p:ERROR > ValueError: repo for scylla version 2018.1 wasn't found
- Ubuntu 18.08


Sent a PR to disable the upgrade test from 2018.1 to 2019.1 on ubuntu 18.04:
- https://github.com/scylladb/scylla-cluster-tests/pull/1601

**Comment by roydahan** [comment]
I  don't understand this issue.
Why is it SCT issue and not scylla?

**Comment by fruch** [comment]
I'm guessing we were trying to upgrade from 2018.1 on Ubuntu 18.08, 
we don't have a version for 2018.1 for Ubuntu 18.08.

**Comment by amoskong** [comment]
SCT failed to find a valid apt source url from http://downloads.scylladb.com.

```
# Background

Currently SCT try to find official release repo of scylla from downloads.scylladb.com, it works well in the past.
We switched to private repo from 2019.1, some repo files of 2019.1 doesn't exist, they are replaced by template of private repo.

http://downloads.scylladb.com/rpm/centos/scylla-2019.1.repo  (exists)
debian9: http://downloads.scylladb.com/deb/debian/scylla-2019.1-stretch.list (doesn't exist)
ubuntu16: http://downloads.scylladb.com/deb/ubuntu/scylla-2019-xenial.list (doesn't exist)
ubuntu18: http://downloads.scylladb.com/deb/ubuntu/scylla-2019.1-bionic.list (doesn't exist)

SCT code: https://github.com/scylladb/scylla-cluster-tests/blob/f0f28ce3141c778215160287b712b7f628502e37/sdcm/utils/common.py#L732
        get_s3_scylla_repos_mapping()

Currently SCT try to download repo by a valid url of scylla repo, if we want to change get_s3_scylla_repos_mapping() to support to identify new template file, and generate real repo in instance. It requires many changes.

## CentOS

http://downloads.scylladb.com/rpm/centos/scylla-$VERSION.repo

## Debian 

debian9: http://downloads.scylladb.com/deb/debian/scylla-$VERSION-stretch.list
debian8: http://downloads.scylladb.com/deb/debian/scylla-$VERSION-jessie.list

## Ubuntu

ubuntu14: http://downloads.scylladb.com/deb/ubuntu/scylla-$VERSION-trusty.list
ubuntu16: http://downloads.scylladb.com/deb/ubuntu/scylla-$VERSION-xenial.list
ubuntu18: http://downloads.scylladb.com/deb/ubuntu/scylla-$VERSION-bionic.list
```

**Comment by roydahan** [comment]
Again, not sure I understand.
Is there a repository for this version and platform or not?
If not, not an issue, just mark it as unsupported.
If Yes, and SCT can't reach it, does your PR fix it?

**Comment by amoskong** [comment]
On Mon, Dec 23, 2019 at 7:53 PM Roy Dahan <notifications@github.com> wrote:

> Again, not sure I understand.
> Is there a repository for this version and platform or not?
>
We have repo (the apt source directories), but there is no apt source file
(scylla*.list) there.

> If not, not an issue, just mark it as unsupported.
> If Yes, and SCT can't reach it, does your PR fix it?
>
I have no PR to fix this issue.

**Comment by roydahan** [comment]
The issue is that " scylla-2019.1.rc1-stretch.list" have rc1 in its name instead of 2019.1-strech.
Open a bug for it in scylla-pkg or somewhere to fix it urgently.

**Comment by amoskong** [comment]
On Mon, Dec 23, 2019 at 8:20 PM Roy Dahan <notifications@github.com> wrote:

> The issue is that " scylla-2019.1.rc1-stretch.list" have rc1 in its name
> instead of 2019.1-strech.
> Open a bug for it in scylla-pkg or somewhere to fix it urgently.
>
We need Release engineer or Amnon to answer if it's expected.

If it's expected, we need to change SCT.
If it's unexpected, release engineer needs to fix their job or code. The
apt source files need to be added manually.
