### ISSUE TITLE
hydra: test failed but job status is PASSed (blue)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1616]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Test job:

https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-centos7-test/10/console

### Description

The upgrade test actually failed, bug jenkins job is blue.
I love this 'feature' or 'bug', but we need to fix it ;-)

### Versions
* **SCT**: master

### Logs
* test_id: fc0151a3-f6b5-418e-86a2-0831f7c9f7ee
* job log: 
```
10:52:41  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/fc0151a3-f6b5-418e-86a2-0831f7c9f7ee/20191225_024959/db-cluster-fc0151a3.zip  |
10:52:41  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/fc0151a3-f6b5-418e-86a2-0831f7c9f7ee/20191225_024959/monitor-set-fc0151a3.zip |
10:52:41  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/fc0151a3-f6b5-418e-86a2-0831f7c9f7ee/20191225_024959/loader-set-fc0151a3.zip  |
10:52:41  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/fc0151a3-f6b5-418e-86a2-0831f7c9f7ee/20191225_024959/sct-runner-fc0151a3.zip  |
```

### Steps to Reproduce

1. run an upgraded job  (job would failed for scylla issue, or you can break the test manually)

**Expected behavior:**

Job result / status is failed  (red)

**Actual behavior:** 

Job result / status is passed  (blue)

/CC @bentsi

**Comment by fruch** [comment]
@aleksbykov can you take a look at this, I'm guessing it has todo with recent new steps added to this pipeline

**Comment by amoskong** [comment]
And this one:  https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-centos7-test/12/console

The test was stopped from builder

```
14:10:05  [Pipeline] echo
14:10:05  FAILED
14:10:05  [Pipeline] sh
14:10:08  + echo hudson.AbortException: script returned exit code 137
14:10:08  hudson.AbortException: script returned exit code 137
14:10:08  [Pipeline] }
14:10:08  [Pipeline] // dir
14:10:08  [Pipeline] }
14:10:08  [Pipeline] // wrap
14:10:08  [Pipeline] }
14:10:08  [Pipeline] // stage
14:10:08  [Pipeline] stage
14:10:08  [Pipeline] { (Collect logs for Upgrade from 3.1)
14:10:08  [Pipeline] wrap
14:10:09  [Pipeline] {
....
14:13:23  Finished: SUCCESS
```

**Comment by aleksbykov** [comment]
Will find new solution.
The recommended and implemented doesn't work for us.  
This print by pipeline, and means that stage failed.

**Comment by aleksbykov** [comment]
Fixed.

**Comment by aleksbykov** [comment]
example: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/longevity-abykov-staging/job/rolling-upgrade-staging-abykov/job/rolling-upgrade-centos7/
