### ISSUE TITLE
AddDropColumn nemesis shouldn't run on scylla-bench tablespace

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1651]
AddDropColumn nemesis shouldn't run on scylla-bench tablespace.

Scylla-bench has "validate data" mode and expect exactly 3 columns in the table. So this nemesis cause to failure

**Comment by juliayakovlev** [comment]
@bentsi  Roy asked to assign it to Dmitry

**Comment by dkropachev** [comment]
Fix is ready: https://github.com/scylladb/scylla-cluster-tests/pull/1661

**Comment by dkropachev** [comment]
If -validate-data is provided scylla-bench tries to validate data on each request, as result of AddDropColumn it generates following line each second:
p:INFO  > RemoteCmdRunner [centos@10.0.29.91]: 2019/12/31 13:41:19 gocql: not enough columns to scan into: have 3 want 9 

Outcomes:
scylla-bench unable to perform data validation
scylla-bench results are not affected
sct.log grows to >1gb

**Comment by bentsi** [comment]
fixed in #1661
