### ISSUE TITLE
failed to decode back trace 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1657]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.2

### Logs
* test_id: 5618f8c5-d3e4-4118-84f1-ac64330075b9

### Description

I've found this docker instance stuck for 3 days, and print those over and over
```
< t:2020-01-02 09:13:15,133 f:cluster.py      l:1311 c:sdcm.cluster         p:ERROR > Node longevity-10gb-3h-master-monitor-node-5618f8c5-1 [34.249.25.71 | 10.0.187.44] (seed: False): failed to decode back
trace 'NoneType' object has no attribute 'get'
``
[Description of the bug or feature]

**Comment by aleksbykov** [comment]
@fruch  i think this fixed by #1638
