### ISSUE TITLE
RFC: Additional new nemesis

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-cluster-tests#166]
Hi,

We need additional nemesis for testing:
- snapshot
- flush
- remove node
- add node
- cross DC repair
- major compaction
- cleanup 
- refresh

Thanks,
Noam.

**Comment by kongove** [comment]
It'a single test with multiple steps, or multiple single tests?
What's the execute order?

**Comment by noamha** [comment]
It's multiple single tests, each as a separate nemesis

**Comment by slivne** [comment]
there is a grow cluster test - lets synch before we do anything.
