### ISSUE TITLE
"Copy AMI to Testing Region" failed and "Stage Logs" doesn't show anything

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1763]
in https://jenkins.scylladb.com/job/scylla-3.3/job/ami/ - 
the copy to region failed and no reason can be seen.

![Screenshot from 2020-02-02 11-12-16](https://user-images.githubusercontent.com/9427929/73605916-232c8380-45ad-11ea-95ce-03c391a26bb1.png)

**Comment by yarongilor** [comment]
found problem in previous state of ami-test. so the issue is about wrong marking of next step (of copy ami) as the failed one.

**Comment by fruch** [comment]
@yarongilor why this is on SCT ?

This should go under scylla-pkg if still relevant

**Comment by yarongilor** [comment]
apparently resolved.
