### ISSUE TITLE
keep-on-failure: instances will only be kept if critical events raised

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1825]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: upgrade-3.1 / master

### Logs
* test_id: 0fd7e080-c7c3-4313-a5fb-467d69647dba
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/0fd7e080-c7c3-4313-a5fb-467d69647dba/20200214_074910/sct-runner-0fd7e080.zip
* Job console log: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/208/console

### Description

In sdcm/tester.py: clean_resources(), it processed the 'keep-on-failure' by referencing if critical events occur.  If the test failed and no critical event raises, the instances will also be destroyed.

```
def get_testrun_status(test_id=None, logdir=None):

    testrun_dir = get_testrun_dir(logdir, test_id)
    status = None
    if testrun_dir:
        with open(os.path.join(testrun_dir, 'events_log/critical.log')) as f:  # pylint: disable=invalid-name
            status = f.readlines()

    return status
```

### Steps to Reproduce

1. run upgrade job, with default post_behavior_db_nodes: keep-on-failure, post_behavior_monitor_nodes: keep-on-failure

**Expected behavior:** [What you expected to happen]

instances won't be destroyed if the job fails

**Actual behavior:** [What actually happened]

instances will be destroyed if the job fails.

The upgrade test failed, it uses subTest, some subTest failed, but there is not critical events raised.

```
15:48:56  ======================================================================
15:48:56  FAIL: test_rolling_upgrade (upgrade_test.UpgradeTest) [Step5 - Upgrade rest of the Nodes ]
15:48:56  ----------------------------------------------------------------------
15:48:56  Traceback (most recent call last):
15:48:56    File "/sct/upgrade_test.py", line 553, in test_rolling_upgrade
15:48:56      self.fill_and_verify_db_data('after upgraded %s' % self.db_cluster.node_to_upgrade.name)
15:48:56    File "/sct/upgrade_test.py", line 420, in fill_and_verify_db_data
15:48:56      self.verify_db_data()
15:48:56    File "/sct/sdcm/fill_db_data.py", line 3008, in verify_db_data
15:48:56      self.run_db_queries(session, session.default_fetch_size)
15:48:56    File "/sct/sdcm/fill_db_data.py", line 2954, in run_db_queries
15:48:56      raise ex
15:48:56    File "/sct/sdcm/fill_db_data.py", line 2951, in run_db_queries
15:48:56      self.assertEqual([list(row) for row in res], item['results'][i])
15:48:56  AssertionError: Lists differ: [] != [['192.168.0.1', 80, 42], ['192.168.0.2', 80, 24], ['192.168.0.2', 90, 42]]
15:48:56  
15:48:56  Second list contains 3 additional elements.
15:48:56  First extra element 0:
15:48:56  ['192.168.0.1', 80, 42]
15:48:56  
15:48:56  - []
15:48:56  + [['192.168.0.1', 80, 42], ['192.168.0.2', 80, 24], ['192.168.0.2', 90, 42]]
15:48:56  
15:48:56  ----------------------------------------------------------------------
15:48:56  Ran 1 test in 16050.855s
15:48:56  
15:48:56  FAILED (failures=2)
15:48:56  < t:2020-02-14 07:48:56,694 f:sct_events.py   l:746  c:sdcm.sct_events      p:INFO  > Stopping Events consumers...
15:48:56  < t:2020-02-14 07:48:56,694 f:sct_events.py   l:756  c:sdcm.sct_events      p:INFO  > All Events consumers stopped.
15:49:01  [Pipeline] }
15:49:01  [Pipeline] // dir
15:49:01  [Pipeline] }
15:49:02  [Pipeline] // wrap
15:49:02  [Pipeline] }
15:49:02  ERROR: script returned exit code 1
15:49:02  [Pipeline] // catchError
15:49:02  [Pipeline] }
15:49:02  [Pipeline] // stage
15:49:02  [Pipeline] stage
15:49:02  [Pipeline] { (Collect logs for Upgrade from 3.0)
```

**Comment by roydahan** [comment]
@amoskong this is how we defined it.
We want to keep only on critical for now, critical is something that is hard to catch and worth keeping the cluster for.
If you need the cluster just to investigate what happens, it means that we don't log enough details and we need to print more things to log.
If you think you hit a critical issue that is hard to catch, raise a critical event.
