### ISSUE TITLE
sct-running logs weren't collected for the new longevity test

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1828]
### Versions
* **SCT**: [branch or hash tag you are working on] master
* **scylla**: [branch or commit hash] master:latest

### Logs
* test_id: 10e4b4e1-62fe-4099-bb41-47241fca4128
* Jenkins job: https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-lwt-3h/1/console

This is the new longevity test, was run first time.
Test didn't collect sct-running logs - see console

I tried to upload the logs using hydra from my laptop:
```
./docker/env/hydra.sh collect-logs --test-id 10e4b4e1-62fe-4099-bb41-47241fca4128
```

This is the result (loaders were terminated in this time, but db nodes exist):
![Screenshot from 2020-02-16 15-41-59](https://user-images.githubusercontent.com/34435448/74605677-e3988800-50d2-11ea-93fa-8f8a5e7761e5.png)

**Comment by fruch** [comment]
logs collection need to run from where the test was running for sct logs to be collected
