### ISSUE TITLE
rolling upgrade tests should be reasonably reproducible and debug-able

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#1878]
Today, when the test fails it is very hard to determine what the problem is. After doing some analysis
rpms must be created and then being sent to QA to validation. A developer has no reasonable way to
debug the problem (with a reproducer) nor validating his rpms. This makes the debug process of
upgrade bugs, ridiculously slow and hard.
My request are:
1. make a "stop on failure" switch so a developer can debug it (preferably localy)
2. add option for rolling upgrade tests (whenever possible) to run locally (sct with dockers - I heard it's a thing :) )
3. expose some of the procedures as local procedures - meaning that a developer can use some building blocks from the test for debugging. Examples are: start stress, upgrade node n
4. Make an option for update from binaries/local repo (meaning that given an rpm a repo will be set up on the devs local machine and the upgrade will be pointed there)
According to MHO order of importance.
/cc @amoskong @roydahan @fruch

**Comment by roydahan** [comment]
1. Having the Step context manager will allow it more easily.
2. Maybe already supported?
3. They are all functions in the code, how would you want to use them?
4l The request is basically for rolling-upgrade with BYO rpms.

**Comment by fruch** [comment]
4 is available already for a long time

1 as well, we don't use steps anymore
And the test is by default stop on the first sign of failure

2 is maybe doable, but needs to be tested, also we have upgrade tests in dtest that can be aligned a bit with SCT but with less stress commands.

**Comment by roydahan** [comment]
upgrade dtest should provide whatever is missing here.
I'm closing this one.
