### ISSUE TITLE
Artifacts test missing a coredump happing during install

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1879]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master 

### Logs
* test_id: 4bb52f7c-f026-41bd-bc85-aa3d0d4171e2
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-centos8/3/

### Description

Seems like the Artifact test finish too fast, and doesn't wait for the coredump to finish uploading.

**Comment by enaydanov** [comment]
Nope. There are two coredumps of bash process and they was uploaded successfully (you can find links in `sct.log`.)

The problem in updating events logs. I found a race condition between events threads:



```
sct.log:
...
< t:2020-02-27 12:49:47,002 f:tester.py       l:169  c:sdcm.tester          p:DEBUG > Post behavior for loader nodes destroy
< t:2020-02-27 12:49:47,028 f:sct_events.py   l:84   c:sdcm.sct_events      p:INFO  > subscribe to server with port 0
< t:2020-02-27 12:49:47,030 f:sct_events.py   l:736  c:sdcm.sct_events      p:INFO  > writing to /sct/20200227-124945-458080/events_log/events.log
< t:2020-02-27 12:49:47,036 f:sct_events.py   l:84   c:sdcm.sct_events      p:INFO  > subscribe to server with port 0
< t:2020-02-27 12:49:47,048 f:sct_events.py   l:48   c:sdcm.sct_events      p:INFO  > EventDevice Listen on pub_port=35628, sub_port=39875
...
```

You can see that it tries to subscribe port 0 instead of 39875. In result we have empty `summary.log` (and all other events logs) and `JSONDecodeError` on attempt to parse empty file.

I fixed it in #1881. Please, review and merge it.

**Comment by fruch** [comment]
see
https://github.com/scylladb/scylla/issues/5916

I think we should also check explicitly for coredumps, like the artifacts are doing today, just to make sure we don't miss it.

**Comment by enaydanov** [comment]
> see
> [scylladb/scylla#5916](https://github.com/scylladb/scylla/issues/5916)
> 
> I think we should also check explicitly for coredumps, like the artifacts are doing today, just to make sure we don't miss it.

I thought that cores handled by SCT already, isn't it?

**Comment by fruch** [comment]
> > see
> > [scylladb/scylla#5916](https://github.com/scylladb/scylla/issues/5916)
> > I think we should also check explicitly for coredumps, like the artifacts are doing today, just to make sure we don't miss it.
> 
> I thought that cores handled by SCT already, isn't it?

Yes, but it would be raise as an event only when it finish to upload the coredump, we've seen cases we can reach the end of the tests before that finishes (if it's scylla coredump, it can be quite big)

Also the old tests were failing right after the install, and doesn't continue forward to next steps, we should consider doing the same.

**Comment by enaydanov** [comment]
> > I thought that cores handled by SCT already, isn't it?
> 
> Yes, but it would be raise as an event only when it finish to upload the coredump, we've seen cases we can reach the end of the tests before that finishes (if it's scylla coredump, it can be quite big)
> 
> Also the old tests were failing right after the install, and doesn't continue forward to next steps, we should consider doing the same.

Ok, I've added this thing to https://trello.com/c/aUOFfMAF/1713-artifact-test-leftovers
