### ISSUE TITLE
Rolling upgrade test: it was reported "all nodes were upgraded" despite the upgrade wasn't started at all.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1893]
### Prerequisites

* [x] Are you rebased to master ? 
* [ ] ~~Is it reproducible ?~~
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] master
* **scylla**: [branch or commit hash]

### Logs
* test_id: 10feb0f7-157b-42b8-adbf-92b8baec25e2
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/staging-rolling-upgrade-centos7/9/console

I am adding the validation that connected to SI problem during upgrade between 3.1 to 3.2 and faced out with some problem of the rolling upgrade test.
I start staging job on my private branch. 
The upgrade wasn't started because of CQL problem. 
But In the end of test I found the message: ```all nodes were upgraded, and last workaround is verified.``` 
But actually, the upgrade wasn't started at all.

**Comment by amoskong** [comment]
We always output `all nodes were upgraded, and last workaround is verified.`, even some subsTest failed, but error was suppressed. I will fix it.

**Comment by fruch** [comment]
We are not using subtests anymore
