### ISSUE TITLE
grafana serving on ipv6 on the monitor

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla-cluster-tests#190]
Upgraded fedora23
latest pip
SCT git commit: 92ff3adf485ba7ad60c6b976a787389659a267ce
avocado lts.

command: avocado run grow_cluster_test.py:GrowClusterTest.test_grow_3_to_5 --multiplex data_dir/scylla.yaml  --filter-only /run/backends/aws/us_east_1 /run/databases/scylla --filter-out /run/backends/libvirt

[scylla.yaml.txt](https://github.com/scylladb/scylla-cluster-tests/files/589744/scylla.yaml.txt)
[job.log.txt](https://github.com/scylladb/scylla-cluster-tests/files/589743/job.log.txt)
[rpm.list.mine.txt](https://github.com/scylladb/scylla-cluster-tests/files/589746/rpm.list.mine.txt)
[pip.list.mine.txt](https://github.com/scylladb/scylla-cluster-tests/files/589747/pip.list.mine.txt)
[netstat.txt](https://github.com/scylladb/scylla-cluster-tests/files/589734/netstat.txt)

Port 3000, 9000 and 9090 are server on tcpv6 on the resulting monitor hence preventing curl
to access them since ipv6 does not exist on ec2.

**Comment by benoit-canet** [comment]
I am closing this bug.

I just forgot my gateway was filtering traffic in a very strict way on output.

I removed the pesky filtering and it's work a lot better know.

Thanks to Shlomi and Lucas to make me remember this fact.

**Comment by slivne** [comment]
I used the same commit

commit 92ff3adf485ba7ad60c6b976a787389659a267ce
Merge: 4c1c34f b4ee512
Author: Lucas Meneghel Rodrigues <lmr@scylladb.com>
Date:   Thu Nov 10 17:22:40 2016 -0200

    Merge pull request #189 from scylladb/wait_jmx_up
    
    sdcm.nemesis: Wait until JMX service is back after nemesis killed scylla

and ran the same test and have grafana started


[job.log.txt](https://github.com/scylladb/scylla-cluster-tests/files/589830/job.log.txt)
