### ISSUE TITLE
BYO Test fail starting Scylla

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-cluster-tests#1915]
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/byo-longevity-test/53/
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/byo-longevity-test/52/

**Comment by amnonh** [comment]
@scylladb/qa-team Trying to test the new monitoring

**Comment by bentsi** [comment]
@amnonh Is there any specific reason for using Scylla 3.1? SCT master doesn't support it

**Comment by amnonh** [comment]
any version would do, I tried both 3.1 and 3.2

**Comment by bentsi** [comment]
try `3.3.rc1`

**Comment by bentsi** [comment]
The issue is that SCT master is not backward compatible so if you want to run with Scylla 3.2 you need to use branch-3.2 for SCT

**Comment by fruch** [comment]
Nowdays our backward compatibility is a bit better
