### ISSUE TITLE
an expected coredump in scylla_setup causes artifact-test fails

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#2015]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
    - only found once.
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch master
* **scylla**:  666.development-0.20200407.16246d1c99e
* Cluster size: 1
* OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d6a24fe35fdf5dc4 (eu-west-1)

### Logs
* test_id: 4c259718-60ce-4621-ba4a-c99f4369a314
* job log: sct log: https://cloudius-jenkins-test.s3.amazonaws.com/4c259718-60ce-4621-ba4a-c99f4369a314/20200408_001125/sct-runner-4c259718.zip
* db log: https://cloudius-jenkins-test.s3.amazonaws.com/4c259718-60ce-4621-ba4a-c99f4369a314/20200408_001125/db-cluster-4c259718.zip

### Description

This test failed for a coredump in scylla_setup (coredump setup), the coredump is generated for 'bash' process as expected.We need to ignore the special coredump in SCT.

### Steps to Reproduce

1. run artifact-test with oel

**Expected behavior:** [What you expected to happen]

The coredump should be ignored by SCT, because it's expected.

**Actual behavior:** [What actually happened]

Coredump occurred during scylla_setup, it's generated for 'bash' process.

coredump file: https://storage.cloud.google.com/upload.scylladb.com/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000.gz

```
2020-04-08 00:01:37.505: (CoreDumpEvent Severity.ERROR): node=Node artifacts-oel76-jenkins-db-node-4c259718-1 [54.194.6.193 | 10.0.3.227] (seed: True)
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000.gz
backtrace=           PID: 12356 (bash)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-04-08 01:01:26 BST (5s ago)
  Command Line: /bin/bash /tmp/tmpekbbc8hl
    Executable: /usr/bin/bash
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (clckwrk)
       Boot ID: f0b1893e3c264f899ee31dee60608402
    Machine ID: 677cfa1df55d442ea4279d4877a617e3
      Hostname: artifacts-oel76-jenkins-db-node-4c259718-1
      Coredump: /var/lib/systemd/coredump/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000
       Message: Process 12356 (bash) of user 0 dumped core.
                
                Stack trace of thread 12356:
                #0  0x00007fe5b08c7597 kill (libc.so.6)
                #1  0x0000000000440686 kill_pid (bash)
                #2  0x0000000000472dfe kill_builtin (bash)
                #3  0x000000000042f23f execute_builtin.isra.2 (bash)
                #4  0x0000000000431329 execute_simple_command (bash)
                #5  0x0000000000432233 execute_command_internal (bash)
                #6  0x0000000000433c1e execute_command (bash)
                #7  0x000000000041e255 reader_loop (bash)
                #8  0x000000000041c8be main (bash)
                #9  0x00007fe5b08b3495 __libc_start_main (libc.so.6)
                #10 0x000000000041d35a _start (bash)

download_instructions=
gsutil cp gs://upload.scylladb.com/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000.gz .
gunzip /var/lib/systemd/coredump/core.bash.0.f0b1893e3c264f899ee31dee60608402.12356.1586304086000000.gz
```

**Comment by fruch** [comment]
@amoskong shouldn't it happen on all artifact tests now ?

Why it failed only in this one ?
Maybe we could use the Filter from #2011

**Comment by bentsi** [comment]
@fruch good idea.

**Comment by bentsi** [comment]
In addition, we need to prevent the process from uploading it
