### ISSUE TITLE
Can't restore monitor set

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#2054]
Not possible to recover monitoring set for any recent longevity runs, as example 748ade92-9b96-466c-bc58-edff6d8aaecf: 

https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h/21/execution/node/64/log/
https://cloudius-jenkins-test.s3.amazonaws.com/748ade92-9b96-466c-bc58-edff6d8aaecf/20200419_205122/monitor-set-748ade92.zip

No snapshots there.

### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

sct: master

**Comment by enaydanov** [comment]
I'm not sure I touched something related to snapshots, but maybe it was affected by my changes indirectly.
