### ISSUE TITLE
DecommissionStreamingErr failing with CRITICAL

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#2059]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: enterprise

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: https://jenkins.scylladb.com/view/enterprise/job/scylla-enterprise/job/longevity-tests/job/longevity-100gb-4h/9/artifact/scylla-cluster-tests/latest/events_log/events.log/*view*/

DecommissionStreamingErr failing while looking for DECOMMISSION  string, failing as CRITICAL, and stop secenrio

**Comment by fruch** [comment]
Seen again on master with Scylla 4.0 rc1

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity/job/longevity-200gb-48h/27/

**Comment by amoskong** [comment]
In node.search_database_log(), an CRITICAL event is raised when the 'DECOMMISSION: done' log is matched.

We can disable the event by `publish_events=False`.
