### ISSUE TITLE
Clean resources stage getting wrong status from SCT Test stage

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2098]
i'm running on branch-4.0.

this message i see inside the "Clean Resources" stage:
```
Post behavior keep-on-failure for db_nodes. Test run Successful. Clean resources
```
but the result is:
```
Shell Script | script returned exit code -1
```

so, my instances were destroyed, although they were supposed to be kept on failure:
```
post_behavior_db_nodes: keep-on-failure
post_behavior_loader_nodes: destroy
post_behavior_monitor_nodes: keep-on-failure
```

**Comment by fruch** [comment]
this isn't working base on the exit status,
it is working base on the critical events, and if you didn't had critical events resources aren't kept

**Comment by fgelcer** [comment]
> this isn't working base on the exit status,
> it is working base on the critical events, and if you didn't had critical events resources aren't kept

but i did have at least 1 critical event.
see an example [here](https://jenkins.scylladb.com/view/scylla-4.0/job/scylla-4.0/job/longevity/job/longevity-large-partition-4days/6/artifact/scylla-cluster-tests/latest/events_log/critical.log)

**Comment by aleksbykov** [comment]
Not sure how this could happened, but looks like critical.log file was updated after the clean-resources stage was running
![Screenshot from 2020-04-29 14-40-46](https://user-images.githubusercontent.com/44991177/80572165-fd860d80-8a27-11ea-9eb7-158c954adf2a.png)

After I had donwloaded the https://cloudius-jenkins-test.s3.amazonaws.com/38462a33-88d9-447e-8b75-6e062ccea769/20200426_132410/sct-runner-38462a33.zip, the critical.log is empty.
Looks like that sct stage was failed, docker continued to run. and on moment the stage collect logs and clear resources, the critical.log was empty.
May be it could some how related to this message from jenkins:
```
20:23:49  wrapper script does not seem to be touching the log file in /home/jenkins/slave/workspace/scylla-4.0/longevity/longevity-large-partition-4days/scylla-cluster-tests@tmp/durable-44ded388
20:23:49  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by aleksbykov** [comment]
@fgelcer @fruch what do you think?

**Comment by fgelcer** [comment]
yes, the `critical.log` file was modified after the `Clean Resources` stage ran (and it was almost done when the `critical.log` was lastly modified.
we need to understand why... it could be related to overloaded systems, including Jenkins builder or the db or loader nodes.

**Comment by bentsi** [comment]
we are making improvements in the test status stage (#2334). Let's close and revisit if this happens again.
