### ISSUE TITLE
statistics monitor from the loaders(c-s clients) isn't enabled for perf_regression_test

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#211]
In PR [1], The loaders are added to monitor targets only in part of tests, the general Loader init isn't changed. So in perf_regression_test, prometheus won't get data from Loaders.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/192

**Comment by slivne** [comment]
I would like you to also change the way we add them so they will not be monitored as regular scylla nodes

we should probably add them as an additional line in the yaml and not to the list of scylla servers.

**Comment by slivne** [comment]
can be done in two steps

**Comment by amoskong** [comment]
fixed by 7e1c0b2d
