### ISSUE TITLE
master debian9 artifact test fails

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#2114]
### Prerequisites

* [Y] Are you rebased to master ?
* [Y] Is it reproducible ?
* [Y] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] master
* **scylla**: [branch or commit hash] master

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian9/64/console

### Description
Job fails since April 27th. I don't understand why.

23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > ERROR:
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > 
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 131, in wrapper
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     return method(*args, **kwargs)
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/utils/decorators.py", line 167, in inner
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     res = func(*args, **kwargs)
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 276, in setUp
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     self.init_nodes(db_cluster=self.db_cluster)
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 247, in init_nodes
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     db_cluster.wait_for_init(node_list=db_cluster.seed_nodes)
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 2824, in wrapper
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     raise NodeSetupFailed(f"{node}:{node_status}")
23:28:01  < t:2020-05-04 20:27:53,474 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > sdcm.cluster.NodeSetupFailed: Node artifacts-debian9-jenkins-db-node-ac04bb08-0-1 [35.196.88.42 | 10.142.0.94] (seed: True):False

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by bentsi** [comment]
@hagitsegev this is unrelated to SCT.
```
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > backtrace=           PID: 15268 (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >            UID: 108 (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >            GID: 112 (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >         Signal: 6 (ABRT)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >      Timestamp: Mon 2020-05-04 20:26:56 UTC (57s ago)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --lock-memory=1
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     Executable: /opt/scylladb/libexec/scylla
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >  Control Group: /
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >          Slice: -.slice
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >        Boot ID: aaac4e4ee04e484094a4e1e4c41e3ada
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     Machine ID: f3589799b2791a38e0e0bd216d6a612b
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >       Hostname: artifacts-debian9-jenkins-db-node-ac04bb08-0-1
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >        Storage: /var/lib/systemd/coredump/core.scylla.108.aaac4e4ee04e484094a4e1e4c41e3ada.15268.1588624016000000000000
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >        Message: Process 15268 (scylla) of user 108 dumped core.
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 Stack trace of thread 15270:
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #0  0x00007f1332763625 raise (libc.so.6)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #1  0x00007f133274c9ae abort (libc.so.6)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #2  0x00007f133274c7a9 n/a (libc.so.6)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #3  0x00007f133275ba66 __assert_fail (libc.so.6)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #4  0x0000000003050c0b n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #5  0x0000000002e01a37 n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #6  0x0000000002da2f2a n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #7  0x0000000002dd7ced n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #8  0x0000000002de5efd n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #9  0x0000000002d7507e n/a (scylla)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #10 0x00007f13331954e2 n/a (libpthread.so.0)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 #11 0x00007f13328286a3 __clone (libc.so.6)
23:28:01  < t:2020-05-04 20:27:54,854 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >                 
```
there is an issue in Scylla that is open:
https://github.com/scylladb/scylla/issues/6346

**Comment by hagitsegev** [comment]
OK, thanks.
It is just very hard to understand that.
