### ISSUE TITLE
c-s-exporter: data of multiple c-s clients mixed into same metric

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#212]
Prometheus page only displayed 8 metrics (same loader IP), but we have multiple c-s clients in each loader. So prometheus feels data from multiple c-s-exporters (one c-s client has one cs-exporter) is one client.

We should find a way to sum the values from different c-s clients and exported to prometheus.

![fireshot capture 26 - prometheus time series collection and _ - http___54 152 39 71_9090_graph 5b](https://cloud.githubusercontent.com/assets/309708/21426321/4534cd06-c889-11e6-8304-204646a6230b.png)

@benoit-canet

**Comment by slivne** [comment]
no you shouldn't you should find a way that each client info is written
aggregations can be done in prometheus like we do aggregations for scylla
server.

So the correct thing is to make sure that each client will send the info
and have a uniqueid to make sure they do not overwrite one another (we have
the ip - yet we may have multiple c-s on the same ip)

**Comment by amoskong** [comment]
Fixed by https://github.com/scylladb/scylla-cluster-tests/pull/400
