### ISSUE TITLE
scale test (200 nodes) fails with authentication error

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2154]
### Versions
* **SCT**: branch-4.0
* **scylla**: branch-4.0

it is possible that it affects also SCT branch-3.3.
at the time, @yarongilor moved SCT to run with branch-3.2 and then the test worked (for the last known time).

### Logs
* test_id: 80d637e6-f9a9-4bdc-b914-c970f6038a48
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/80d637e6-f9a9-4bdc-b914-c970f6038a48/20200513_051353/sct-runner-80d637e6.zip

errors in log:
```
Authentication timeout.: sleeping 30 seconds before next retry
```
also:
```
< t:2020-05-12 07:44:54,882 f:remote.py       l:354  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.145.82]: No existing session
```

during the execution i connected to couple of the nodes, and i saw, for example, that the scylla-service was up and running (2 different nodes listed here, but they are not connected to each other for some reason):
```
Nodetool:
nodetool help
CQL Shell:
cqlsh
More documentation available at:
http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

   ScyllaDB is active.

$ nodetool status

Datacenter: eu-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.0.145.82  537.16 KB  256          ?       4101f676-0411-4a63-8887-eff51a8aff55  1a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
This EC2 instance is optimized for Scylla.
Nodetool:
nodetool help
CQL Shell:
cqlsh
More documentation available at:
http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

   ScyllaDB is active.

$ nodetool status

Datacenter: eu-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  10.0.173.219  537.21 KB  256          ?       25218e78-58cb-42a3-8aae-9758185a9261  1a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
This EC2 instance is optimized for Scylla.
```

When running the scale test (200 nodes) on branch-4.0, test fails during setup phase. Important to mention that there are no logs from any of the nodes, meaning that probably rsync failed.

**Comment by fgelcer** [comment]
FYI @roydahan / @bentsi

**Comment by fruch** [comment]
looks like we are overloading the CPU of the builder, lots of print like those, are suggest the `ssh_ping_thread` is failing/timeouts
```
< t:2020-05-18 13:20:20,611 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > '_get_core_pids': failed with 'SSHConnectTimeoutError("Unable to run 'sudo coredumpctl --no-pager --no-legend 2>&1': f
ailed connecting to '10.0.172.210' during 60s",)', retrying [#1]  
```

seem like the 5sec in the

**Comment by fruch** [comment]
I've also seen exception like `No existing session`
https://github.com/paramiko/paramiko/issues/1097
@enaydanov seem like in #1930 you added `No existing session` to the retry list.

**Comment by dkropachev** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/2267
