### ISSUE TITLE
move to use the predefined dashboards of scylla-graphite-monitoring and not use the hardcoded ones

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-cluster-tests#220]
SCT is using a copy of the dashboards.

We are working to change the metrics in scylla and as such the dashboards will not be aligned with scylla metrics.

Need to move and use the dashboards (and probably the docker container) from scylla-graphite-monitoring to make sure we have the correct dashboards used for each version

Need a way to associate each test with a scylla version to know which branch/tage should be pulled out and used.

**Comment by kongove** [comment]
Currently we just add multiple dashboard with many versions (old, 1.5, 1.6, master) together, use can open right one according to the version.

TODO:
* get dashboards from scylla-grafana-monitoring project

![screen shot 2017-03-10 at 3 12 41 pm](https://cloud.githubusercontent.com/assets/309708/23785723/0ba40496-05a4-11e7-857c-30b71e3589f3.png)

**Comment by kongove** [comment]
Solved by PR #273
