### ISSUE TITLE
Node with state LEAVING was selected as target for the nemesis

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2204]
### Prerequisites

* [x] Are you rebased to master ? 
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: juliayakovlev:healthchecker_revision_multidc
* **scylla**: 666.development-0.20200521.c29ccdea7

### Logs
* test_id: 00751e96-45b8-418d-b238-40e5e4e1cf87
* job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-counters-multidc/22

Node was decommissioned during ShrinkCLuster nemesis.
But because of the issue [#6564](https://github.com/scylladb/scylla/issues/6564) the node was stuck with UL status ( UP and LEAVING).
Despite the node is not in the NORMAL status, it was selected for future nemesises.
Seems we don't need to select such nodes as target for the nemesis

**Comment by roydahan** [comment]
will be handled by cluster health validator
