### ISSUE TITLE
SCT stuck for 1 hour while restarting Docker

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2217]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch master - hash fff72776c2aac38bf8f6749e5a4131d3bc6b39c3

### Logs
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: 50cfc5a2-8872-4fc1-9455-d2ae2e2fb696                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/db-cluster-50cfc5a2.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/monitor-set-50cfc5a2.zip |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/loader-set-50cfc5a2.zip  |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/sct-runner-50cfc5a2.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

### Description

while executing pre-test routine, my execution got stuck on running `sudo rm -vf /var/lib/systemd/coredump/core.bash.*` for 1 hour, until eventually it timed out

here 1st and last prints:
```
< t:2020-06-04 10:48:38,160 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.245.28.222]: Running command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*"...
< t:2020-06-04 10:48:38,388 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.245.28.222]: Command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*" finished with sta
tus 0
< t:2020-06-04 11:48:26,053 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.245.28.222]: Running command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*"...
< t:2020-06-04 11:48:26,279 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.245.28.222]: Command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*" finished with status 0
< t:2020-06-04 11:48:30,280 f:remote.py       l:323  c:sdcm.remote          p:ERROR > Timeout opening channel.
< t:2020-06-04 11:48:30,280 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > 'run': failed with 'RetriableNetworkException('Timeout opening channel.')', retrying [#0]
```

**Comment by fruch** [comment]
have you seen this more then once ?

**Comment by fgelcer** [comment]
i'm running it locally on my pc, and for every run it happens

**Comment by amoskong** [comment]
> ### Prerequisites
> * [x]  Are you rebased to master ?
> * [ ]  Is it reproducible ?
> * [x]  Did you perform a cursory search if this issue isn't opened ?
> 
> ### Versions
> * **SCT**: branch master - hash [fff7277](https://github.com/scylladb/scylla-cluster-tests/commit/fff72776c2aac38bf8f6749e5a4131d3bc6b39c3)
> 
> ### Logs
> ```
> +--------------------------------------------------------------------------------------------------------------------------------------------+
> |                                      Collected logs by test-id: 50cfc5a2-8872-4fc1-9455-d2ae2e2fb696                                       |
> +-------------+------------------------------------------------------------------------------------------------------------------------------+
> | Cluster set | Link                                                                                                                         |
> +-------------+------------------------------------------------------------------------------------------------------------------------------+
> | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/db-cluster-50cfc5a2.zip  |
> | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/monitor-set-50cfc5a2.zip |
> | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/loader-set-50cfc5a2.zip  |
> | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/50cfc5a2-8872-4fc1-9455-d2ae2e2fb696/20200604_090439/sct-runner-50cfc5a2.zip  |
> +-------------+------------------------------------------------------------------------------------------------------------------------------+
> ```
> 
> ### Description

I didn't see the rm cmd stuck.
We repeatedly run the clean cmd in get_backtraces() loop.

> while executing pre-test routine, my execution got stuck on running `sudo rm -vf /var/lib/systemd/coredump/core.bash.*` for 1 hour, until eventually it timed out
> 
> here 1st and last prints:
> 
> ```
> < t:2020-06-04 10:48:38,160 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.245.28.222]: Running command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*"...

Start to run 
> < t:2020-06-04 10:48:38,388 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.245.28.222]: Command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*" finished with sta
> tus 0

Finished.

> < t:2020-06-04 11:48:26,053 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.245.28.222]: Running command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*"...

Started to run another 
> < t:2020-06-04 11:48:26,279 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.245.28.222]: Command "sudo rm -vf /var/lib/systemd/coredump/core.bash.*" finished with status 0

the another Finished.

> < t:2020-06-04 11:48:30,280 f:remote.py       l:323  c:sdcm.remote          p:ERROR > Timeout opening channel.
> < t:2020-06-04 11:48:30,280 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > 'run': failed with 'RetriableNetworkException('Timeout opening channel.')', retrying [#0]
> ```

This retry is for install_scylla_monitoring()

< t:2020-06-04 10:47:36,061 f:decorators.py   l:170  c:sdcm.utils.decorators p:DEBUG > BEGIN: install_scylla_monitoring <MonitorSetAWS>
< t:2020-06-04 11:48:30,280 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > 'run': failed with 'RetriableNetworkException('Timeout opening channel.')', retrying [#0]
< t:2020-06-04 11:48:46,031 f:decorators.py   l:173  c:sdcm.utils.decorators p:DEBUG > END: install_scylla_monitoring <MonitorSetAWS> (ran 3669.970031s)

There is something stuck inside install_scylla_monitoring.

**Comment by amoskong** [comment]
After filtered out the 'rm cmd' log, we saw restart docker cmd stuck for 1 hour, the second retry succeeded.

```
[amos@amos-centos8 50cfc5a2-8872-4fc1-9455-d2ae2e2fb696]$ less sct.log |grep -v 'rm -vf'|less

....
< t:2020-06-04 10:48:28,921 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo usermod -aG docker $USER"...
< t:2020-06-04 10:48:29,245 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.253.222.222]: Command "sudo usermod -aG docker $USER" finished with status 0
< t:2020-06-04 10:48:29,245 f:remote.py       l:279  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Reconnecting to '34.253.222.222'
< t:2020-06-04 10:48:30,005 f:remote.py       l:282  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Connected!
< t:2020-06-04 10:48:30,005 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo systemctl restart docker"...
< t:2020-06-04 11:48:30,280 f:remote.py       l:323  c:sdcm.remote          p:ERROR > Timeout opening channel.
< t:2020-06-04 11:48:30,280 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > 'run': failed with 'RetriableNetworkException('Timeout opening channel.')', retrying [#0]
< t:2020-06-04 11:48:35,285 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo systemctl restart docker"...
< t:2020-06-04 11:48:35,954 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.253.222.222]: Command "sudo systemctl restart docker" finished with status 0
```

**Comment by amoskong** [comment]
> After filtered out the 'rm cmd' log, we saw restart docker cmd stuck for 1 hour, the second retry succeeded.
> 
> ```
> [amos@amos-centos8 50cfc5a2-8872-4fc1-9455-d2ae2e2fb696]$ less sct.log |grep -v 'rm -vf'|less
> 
> ....
> < t:2020-06-04 10:48:28,921 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo usermod -aG docker $USER"...
> < t:2020-06-04 10:48:29,245 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.253.222.222]: Command "sudo usermod -aG docker $USER" finished with status 0
> < t:2020-06-04 10:48:29,245 f:remote.py       l:279  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Reconnecting to '34.253.222.222'
> < t:2020-06-04 10:48:30,005 f:remote.py       l:282  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Connected!
> < t:2020-06-04 10:48:30,005 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo systemctl restart docker"...
> < t:2020-06-04 11:48:30,280 f:remote.py       l:323  c:sdcm.remote          p:ERROR > Timeout opening channel.
> < t:2020-06-04 11:48:30,280 f:decorators.py   l:125  c:sdcm.utils.decorators p:DEBUG > 'run': failed with 'RetriableNetworkException('Timeout opening channel.')', retrying [#0]
> < t:2020-06-04 11:48:35,285 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@34.253.222.222]: Running command "sudo systemctl restart docker"...
> < t:2020-06-04 11:48:35,954 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@34.253.222.222]: Command "sudo systemctl restart docker" finished with status 0
> ```

The collecting system log for monitor and loader hasn't been merged, so we don't know what's happened around this stage (1 hour).
- https://github.com/scylladb/scylla-cluster-tests/pull/2197

**Comment by bentsi** [comment]
this is not related to "removing core.bash.*", changing the subject.
The output the you see is coming from the `sdcm.cluster.BaseNode.backtrace_thread`.
As Amos suggested we need to logs from the monitor in order to understand what happened. Let's keep the issue open and add new information here whenever it will reproduce

**Comment by bentsi** [comment]
I will add a timeout of 60 secs to the docker restart command
