### ISSUE TITLE
longevity on 1.6 is not using duration limit in SCT 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-cluster-tests#222]
commit 838cff4805df0eee47268b74780d1918c7277c63 (head i s broken #219)

http://jenkins.cloudius-systems.com:8080/job/scylla-1.6-longevity/4/label=master/console

the test was killed by jenkins timeout - it should have ended after 3 hours (I think) and provided a feedback if it was successful or not.

**Comment by roydahan** [comment]
Somehow (maybe my typo), the c-s command was:
stress_cmd: cassandra-stress write cl=QUORUM duration=1800m

I changed it back to 180m.

**Comment by kongove** [comment]
configure issue, close the issue.

If we want to increase the test time, we should also adjust the `test_duration` in config.
