### ISSUE TITLE
Performance tests are broken - stress command params aren't stored in test_details since Februray!!

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#2222]
If you'll look closer on performance results emails you'll see that the results are compared only to versions from February and below.
(master and release)

The reason for this is that our query for results is taking into account all parameters of the stress command that are part of tests_details.

I think that this commit broke it, but I don't understand the changes in order to fix it:
7a6b2f6ffb0268796d211411d89811172caad050

**Comment by fruch** [comment]
I've found the issue
The test name has changed by mistake 😒
from 
`performance_regression_test.py:PerformanceRegressionTest.test_mixed`
to
`performance_regression_test.PerformanceRegressionTest.test_mixed`

Cause I've used `seld.id()`

I'll create a script to change the names back, and a PR to fix it

**Comment by fruch** [comment]
After a closer look, seems like we are seeing only results created from `branch-perf-v6` the move to using `self.id()` was long time ago...

I think this is broken much longer then you thought.

**Comment by roydahan** [comment]
I see results till February 2020...
I see the missing results, but they aren't part of the query because the miss the "stress" command details.

**Comment by fruch** [comment]
@roydahan I think I've found the root cause and #2231 should fix it

**Comment by roydahan** [comment]
This is not enough to fix it...
