### ISSUE TITLE
scylla-manager-agent installation on deb-like distros failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#2234]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:  branch-4.1
* **scylla**: 4.1.rc1

### Logs
* test_id: f2503109-d21b-494a-8a6d-0b42358e5c68 

### Description

SCT sdcm/cluster.py: install_manager_agent() only works on CentOS/RHEL system.
This patch (https://github.com/scylladb/scylla-cluster-tests/commit/7ae31e20678b3892685539425cdb553fd62cb53d) enabled scylla-manager-agent installation for artifact-test instances.
So the scyllla-manager-agent installation on deb like distros will fail.

```
+ yum install -y scylla-manager-agent
> bash: line 1: yum: command not found
```

### Steps to Reproduce

1. scylla-manager-agent install

**Expected behavior:**
install failed

**Actual behavior:**
install succeed

**Comment by amoskong** [comment]
It seems this problem only occurred with branch-4.1 repo.

The artifact-centos8-test of scylla master looks good.
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-test/

**Comment by roydahan** [comment]
@bentsi FYI
