### ISSUE TITLE
libcloud failed: 'NoneType' object has no attribute 'makefile'

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#224]
Fail to call list_nodes() before cleanup resource. If it's a python or libcloud issue we should workaround it insider SCT.

```
Node longevity-1-6-scylla-db-node-04f7ec6a-2 [104.196.185.46 | 10.240.0.27] (seed: None):
Call to method <bound method GCENodeDriver.list_nodes of
<libcloud.compute.drivers.gce.GCENodeDriver object at 0x7f3b8bc91dd0>>
failed: 'NoneType' object has no attribute 'makefile'
Cleaning up resources used in the test
```

[(private) job/scylla-1.6-longevity-gce/label=master/22/console](http://jenkins.cloudius-systems.com/job/scylla-1.6-longevity-gce/label=master/22/console)
Python Issue (no update): [http://bugs.python.org/issue8728](http://bugs.python.org/issue8728)

**Comment by kongove** [comment]
```
:libcloud amoskong$ git grep makefile
libcloud/common/base.py:            def makefile(self, *args, **kwargs):
libcloud/compute/ssh.py:        stdin = chan.makefile('wb', bufsize)
libcloud/compute/ssh.py:        # Note #1: This is used instead of chan.makefile approach to prevent
libcloud/test/common/test_retry_limit.py:                        sock.makefile = Mock(return_value=f)
```
makefile() is only used in SSH connection.

libcloud/common/base.py
```
        # this is evil. laugh with me. ha arharhrhahahaha
        class fakesock(object):

            def __init__(self, s):
                self.s = s

            def makefile(self, *args, **kwargs):
                if PY3:
                    from io import BytesIO
                    cls = BytesIO
                else:
                    cls = StringIO

                return cls(b(self.s))
```

libcloud/compute/ssh.py
```
        transport = self.client.get_transport()
        chan = transport.open_session()

        start_time = time.time()
        chan.exec_command(cmd)

        stdout = StringIO()
        stderr = StringIO()

        # Create a stdin file and immediately close it to prevent any
        # interactive script from hanging the process.
        stdin = chan.makefile('wb', bufsize)
        stdin.close()
```

libcloud prefers to use 'ParamikoSSHClient'. There is also another client -> ShellOutSSHClient, I will also try this client.

**Comment by Kami** [comment]
I haven't seen this error before. Can you please provide more context and details when this happens:

- Which Python version
- Which OS
- Which version of paramiko (pip show paramiko)
- Which code causes this to happen

There is indeed another SSH client, but it's less secure so the Paramiko one is preferred and used by default.

I'm also a bit confused since you said it happens on `list_nodes` and list_nodes doesn't use and has nothing to do with the SSH client.

**Comment by Kami** [comment]
Edit: I just noticed this issue is opened against scylla-cluster-tests repo and not libcloud one. It would be good if you can also open a PR on our Github repo or issue on our JIRA tracker.

**Comment by lmr** [comment]
@kongove the errors you saw are not related to the SSH tracker, it's a failure calling a libcloud/GCE method. I wrote an exponential backoff retry method, see 601d9d7afbc72e0cbe10305b7872cd16357b0347

**Comment by lmr** [comment]
def _instance_wait_safe(self, instance_method):
        """
        Wrapper around GCE instance methods that is safer to use.

        Let's try a method, and if it fails, let's retry using an exponential
        backoff algorithm, similar to what Amazon recommends for it's own
        service [1].

        :see: [1] http://docs.aws.amazon.com/general/latest/gr/api-retries.html
        """
        threshold = 300
        ok = False
        retries = 0
        max_retries = 9
        while not ok and retries <= max_retries:
            try:
                return instance_method()
            except Exception, details:
                self.log.error('Call to method %s failed: %s',
                               instance_method, details)
                time.sleep(max((2 ** retries) * 2, threshold))
                retries += 1

        if not ok:
            raise NodeError('GCE instance %s method call error after '
                            'exponencial backoff wait' % self._instance.id)

**Comment by lmr** [comment]
@Kami the SSH client has nothing to do with the actual issue. @kongove just has to start to wrap more method calls with `_instance_wait_safe`. I even thought about writing a proxy object o the libvirt driver instance that would wrap all library calls with this module, or a decorator to do something similar, but I didn't think it was necessary, so I restricted it to list_nodes and a few other methods inside the GCE wrapper class.

**Comment by kongove** [comment]
@lmr why do you set threshold to 300, is it too long?
It almost 100% to retry list_nodes in gce scylla_setup, it wastes about 10 mins (retry twice).

We call list_nodes in multiple threads, and the calling time is very near.

list_nodes() returns info of all nodes, so we don't need to call list_nodes for all nodes repeatedly.

Can you just fresh instance state only at the beginning stage and after reboot? this will reduce the calling for list_nodes(). The following patch reduced the test time of perf-regression about 19 mins.

```
+++ b/sdcm/cluster.py
@@ -1004,8 +1004,11 @@ class GCENode(BaseNode):
 
     def _refresh_instance_state(self):
         node_name = self._instance.name
-        instance = [n for n in self._instance_wait_safe(self._gce_service.list_nodes) if n.name == node_name][0]
-        self._instance = instance
+        if self._instance:
+            instance = self._instance
+        else:
+            instance = [n for n in self._instance_wait_safe(self._gce_service.list_nodes) if n.name == node_name][0]
+            self._instance = instance
         ip_tuple = (instance.public_ips, instance.private_ips)
         return ip_tuple
 ```

**Comment by kongove** [comment]
@lmr  Why do we use similar retry policy as the example?
* `threshold` is the max wait time.
*  (2 ** retries) * 100ms == (2 ** retries) * 10s

```
+++ b/sdcm/cluster.py
@@ -967,7 +967,7 @@ class GCENode(BaseNode):
             except Exception, details:
                 self.log.error('Call to method %s (retries: %s) failed: %s',
                                instance_method, retries, details)
-                time.sleep(max((2 ** retries) * 2, threshold))
+                time.sleep(min((2 ** retries) * 10, threshold))
                 retries += 1
 
         if not ok:
```

**Comment by lmr** [comment]
@kongove, some answers:

1) 300 seconds comes frpm a discussion I found on AWS documentation. If it gives better results, the times could be adjusted.
2) list_nodes was used because there is no .refresh() method for libcloud GCE instances, meaning that once you create the instance, it doesn't have an IP, there's no easy way to determine the current instance IP address unless you keep calling the node list over and over until the ip appears. There might be a better way to do that, but keep in mind that I had a couple of days to implement the whole GCE support
3) The code you mentioned will probably fail to get an IP address, try it out. The reason is mentioned on 2), once you create an instance, there's no obvious way to refresh the internal state of the resource, as in AWS. AWS has a .refresh() method that allows you to keep checking the instance state until IP addresses appear.

**Comment by lmr** [comment]
And the retry should be 2**retries*0.1, since 100 ms = 0.1 s. So the 0.1 should have been added to the code but wasn't.

**Comment by lmr** [comment]
Anyway, the retry was supposed to not be very frequent, such as in the AWS case. But GCE API calls seem to fail more often anyway.

**Comment by kongove** [comment]
@lmr @Kami In the second comment, I parsed two parts of libcloud code. open_session() returns a `facksock` object, makefile() is called after executing ssh cmd. So the fail is related to SSH client. If we switch to other SSHClient (such as ShellOutSSHClient) makefile() won't be called, I wish to workaround the issue.

**Comment by kongove** [comment]
@Kami

We are calling list_nodes() in parallel (3 or more threads), I also try to replace it by ex_get_node(), the problem also exists.

```
CentOS Linux release 7.3.1611 (Core) 
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
paramiko Version: 1.18.1
```

**Comment by lmr** [comment]
@kongove I see. I haven't realized the implementation of some of the API commands use an SSHClient implementation behind the scenes. How do you do that?

Anyway, I understand your point now.

**Comment by kongove** [comment]
In my recent test, the max retries time is 3, so it's acceptable. Let's close this issue.
