### ISSUE TITLE
`ClusterTester.cql_connection` and friends connect to the wrong node/cluster

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2248]
```
        with self.cql_connection_patient(node=n) as sess:
```
one would expect that this connets to node `n`. But it doesn't!

```
    def cql_connection_patient(self, node, keyspace=None,  # pylint: disable=too-many-arguments
                               user=None, password=None,
                               compression=True, protocol_version=None,
                               port=None, ssl_opts=None, connect_timeout=100, verbose=True):
        """
        Returns a connection after it stops throwing NoHostAvailables.

        If the timeout is exceeded, the exception is raised.
        """
        # pylint: disable=unused-argument
        kwargs = locals()
        del kwargs["self"]
        return self.cql_connection(**kwargs)
```

goes into
```
    def cql_connection(self, node, keyspace=None, user=None,  # pylint: disable=too-many-arguments
                       password=None, compression=True, protocol_version=None,
                       port=None, ssl_opts=None, connect_timeout=100, verbose=True):
        # TODO: ask Bentsi why it was reverted (PR #1236)
        node_ips = self.db_cluster.get_node_external_ips()
        wlrr = WhiteListRoundRobinPolicy(node_ips)
        return self._create_session(node, keyspace, user, password,
                                    compression, protocol_version, wlrr,
                                    port=port, ssl_opts=ssl_opts, node_ips=node_ips,
                                    connect_timeout=connect_timeout, verbose=verbose)
```

goes into
```
    def _create_session(self, node, keyspace, user, password, compression,  # pylint: disable=too-many-arguments, too-many-locals
                        protocol_version, load_balancing_policy=None,
                        port=None, ssl_opts=None, node_ips=None, connect_timeout=None,
                        verbose=True):
        if not port:
            port = node.CQL_PORT

        if protocol_version is None:
            protocol_version = 3

        authenticator = self.params.get('authenticator')
        if user is None and password is None and (authenticator and authenticator == 'PasswordAuthenticator'):
            user = self.params.get('authenticator_user', default='cassandra')
            password = self.params.get('authenticator_password', default='cassandra')

        if user is not None:
            auth_provider = self.get_auth_provider(user=user,
                                                   password=password)
        else:
            auth_provider = None

        if ssl_opts is None and self.params.get('client_encrypt', default=None):
            ssl_opts = {'ca_certs': './data_dir/ssl_conf/client/catest.pem'}
        self.log.debug(str(ssl_opts))
        cluster_driver = ClusterDriver(node_ips, auth_provider=auth_provider,
                                       compression=compression,
                                       protocol_version=protocol_version,
                                       load_balancing_policy=load_balancing_policy,
                                       default_retry_policy=FlakyRetryPolicy(),
                                       port=port, ssl_options=ssl_opts,
                                       connect_timeout=connect_timeout)
        session = cluster_driver.connect()
...
```

notice that `_create_session` doesn't use the `node` parameter to create the session. For some reason, it uses `node_ips`, which is defines as ` self.db_cluster.get_node_external_ips()`.

---

This issue is an instance of more general problem with SCT codebase: **globals everywhere** (in this case, `self.db_cluster`). What if we didn't want to access a `db_cluster` node, but `cs_db_cluster` node? It won't work, we'll connect to the wrong cluster.

**Comment by bentsi** [comment]
In SCT we have to types of the connections to DB
- cql_connection - CQL connection that driver will get all the nodes as an endpoint, basically it means we need a connection to DB and it's not important which node will be connected first
- cql_connection_exclusive - a CQL connection  that will connect to one specific node 

We ensure this by using `WhiteListRoundRobinPolicy`:
- cql_connection  - `WhiteListRoundRobinPolicy([<all nodes in cluster>])`
- cql_connection_exclusive  - `WhiteListRoundRobinPolicy([<specific node>])`
Regarding SCT codebase, it was poorly designed at the beginning of the days and we have a lot legacy, so we all have to  leave with it and fix step-by-step

**Comment by bentsi** [comment]
So if you want to connect to specific node use `cql_connection_exclusive` or `cql_connection_patient_exclusive` ( same as the first but retries if host not available).
If you don't care to which node to connect use `cql_connection` or `cql_connection_patient` (one with retries).
@kbr- does this answer you question?

**Comment by kbr-** [comment]
@bentsi 
Yeah, I'm using `cql_connection_exclusive` now.
However:
1. `cql_connection` should connect to the correct cluster. Currently if you have two clusters `db_cluster` and `cs_db_cluster`, it will always connect to `db_cluster`. But I see that @aleksbykov has already posted a PR. https://github.com/scylladb/scylla-cluster-tests/pull/2253
2. Since `cql_connection` apparently ignores the node argument, it should not take a node argument.
Okay, I see that it uses the node to retrieve the port to connect to - but nothing else. Then a better interface would be to take just the port argument. The current interface causes confusion.
