### ISSUE TITLE
Nemesis disrupt_decommission_streaming_err failed with runtime error: Operation decommission is in progress, try again

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2271]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2020.1
* **scylla**: 2020.1.rc0-0.20200615.255af15e51b

### Logs
* test_id: 9c6a823c-f7fe-4099-b725-660b87769bab
* job log: https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/longevity/job/longevity-100gb-4h-test/4/

Nemesis: disrupt_decommission_streaming_err

Decommissioning was interrupted by storage_service/force_terminate_repair API:
```
< t:2020-06-16 00:38:10,282 f:nemesis.py      l:1803 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Stop background repair task by storage_service/force_terminate_repair API
< t:2020-06-16 00:38:10,293 f:remote.py       l:160  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@10.0.155.181]: Error executing command: "nodetool  decommission "; Exit status: -1
```

Reported that decommissioning is stopped:
```
< t:2020-06-16 00:38:10,294 f:nemesis.py      l:1774 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: decommission is stopped
```

But it continue to unbootstrap:
```
< t:2020-06-16 00:38:22,351 f:cluster.py      l:1409 c:sdcm.cluster         p:DEBUG > 2020-06-16T00:38:07+00:00  longevity-100gb-4h-2020-1-db-node-9c6a823c-2 !INFO    | scylla: [shard 0] range_streamer - Unbootstrap with 10.0.130.171 for keyspace=keyspace1, streaming [112, 128) out of 164 ranges
< t:2020-06-16 00:38:22,356 f:cluster.py      l:1409 c:sdcm.cluster         p:DEBUG > 2020-06-16T00:38:08+00:00  longevity-100gb-4h-2020-1-db-node-9c6a823c-2 !INFO    | scylla: [shard 0] range_streamer - Unbootstrap with 10.0.99.116 for keyspace=keyspace1, streaming [126, 140) out of 143 ranges
```

Recover the target node by a final rebuild failed:
```
< t:2020-06-16 00:38:23,913 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.155.181]: Running command "nodetool  rebuild "...
< t:2020-06-16 00:38:24,863 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.155.181]: nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation decommission is in progress, try again)
```

Nemesis failed. Target node was removed from gossip, but stays in STC cluster nodelist

The issue similar to https://github.com/scylladb/scylla-cluster-tests/issues/2004

**Comment by roydahan** [comment]
@juliayakovlev when you say “stay in the cluster” you mean in the cluster node list of SCT?
It would better to specify the exact object.

In any case, the issue is that we try to kill the decommission but we do it incorrectly.

**Comment by juliayakovlev** [comment]
> @juliayakovlev when you say “stay in the cluster” you mean in the cluster node list of SCT?
> It would better to specify the exact object.

Changed in description

> 
> In any case, the issue is that we try to kill the decommission but we do it incorrectly.
Right. Because of this I mentioned issue #2004

**Comment by roydahan** [comment]
The fix is very simple, remove the termination by API which doesn't really work

**Comment by roydahan** [comment]
@amoskong didn’t you fix it already?

**Comment by amoskong** [comment]
> @amoskong didn’t you fix it already?

Yes.

It's fixed by https://github.com/scylladb/scylla-cluster-tests/commit/1914385572d37f5f9b8721eef8cdbca80d6b6376
Which hasn't been backported to 4.2 / 4.1

**Comment by roydahan** [comment]
@juliayakovlev was the 1tb job ran with the old 2020.1 or the new one?

**Comment by juliayakovlev** [comment]
> @juliayakovlev was the 1tb job running with the old 2020.1 or the new one?

It always should run from latest SCT version. The 1914385 commit was merged before 20 days. Should be in

**Comment by amoskong** [comment]
I just checked https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-1tb-7days-test/2/
It uses branch-2020.1, the fix https://github.com/scylladb/scylla-cluster-tests/commit/1914385572d37f5f9b8721eef8cdbca80d6b6376 isn't backported

**Comment by roydahan** [comment]
@juliayakovlev when you started it it was before we changed branch-2020.1-new to be branch-2020.1, that's why it was missing.

**Comment by amoskong** [comment]
Fixed by https://github.com/scylladb/scylla-cluster-tests/commit/1914385572d37f5f9b8721eef8cdbca80d6b6376

**Comment by juliayakovlev** [comment]
@roydahan @bentsi 
It happened again on the master during disrupt_rebuild_streaming_err

*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220303.0544973b15dd with build-id 3b69cb8b4d61d8190175613119fcc982a0b5eddb`
Cluster size: 3 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   gemini-1tb-10h-master-db-node-dfd0facd-1 (52.215.207.192 | 10.0.1.29): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-5 (54.246.227.25 | 10.0.3.173): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-6 (34.241.254.50 | 10.0.2.172): 14 shards
Scylla running with shards number (terminated nodes):
   gemini-1tb-10h-master-db-node-dfd0facd-3 (54.74.33.231 | 10.0.2.208): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-4 (54.78.3.38 | 10.0.2.12): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-2 (34.244.27.104 | 10.0.2.230): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-050e5a4fbd1175aa3` (aws: eu-west-1)

Gemini command:
`/$HOME/gemini -d --duration 8h --warmup 2h -c 50 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.0.1.29,10.0.2.230,10.0.2.208 --outfile /home/centos/gemini_result_972a80f3-7b38-4c35-9cbe-9811563ddd43.log --seed 32 --oracle-cluster=10.0.1.67 `
Gemini version: `1.7.5`

Test: `gemini-1tb-10h`
Test name: `gemini_test.GeminiTest.test_load_random_with_nemesis`
Test config file(s):
- [gemini-1tb-10h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/c739275ca255f2fc2902a6496d3fbaae38b10012/test-cases/gemini/gemini-1tb-10h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/c739275ca255f2fc2902a6496d3fbaae38b10012/test-cases/gemini/gemini-1tb-10h.yaml&source=gmail-html&ust=1647419196287000&usg=AOvVaw17byBvcyBSNzY5NNQNLmV7))


**Issue description**

```
< t:2022-03-11 14:09:12,795 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
< t:2022-03-11 14:09:12,796 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-11 14:09:12.794: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=2cda4304-2be2-4a5a-97d0-13ee07dbd2
24: nodetool_command=rebuild node=gemini-1tb-10h-master-db-node-dfd0facd-5

< t:2022-03-11 14:12:49,427 f:cluster.py      l:1041 c:sdcm.cluster_aws     p:DEBUG > Node gemini-1tb-10h-master-db-node-dfd0facd-5 [54.246.227.25 | 10.0.3.173] (seed: False): Hardly rebooting node

< t:2022-03-11 14:12:51,374 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-03-11T14:12:50+00:00 gemini-1tb-10h-master-db-node-dfd0facd-1 !    INFO |  [shard 0] gossip - InetAddress 10.0.3.173 is now DOWN, status = shutdown

2022-03-11 14:15:17.620: (PrometheusAlertManagerEvent Severity.NORMAL) period_type=end event_id=304b7e5d-d2e2-4560-9805-2b2635fd7945 duration=1m3s: alert_name=InstanceDown node=10.0.3.173 start=2022-03-11T14:14:04.791Z end=2022-03-11T14:18:04.791Z description=10.0.3.173 has been down for more than 30 seconds. updated=2022-03-11T14:14:11.146Z state=active fingerprint=5221f5ac5d01d602 labels={'alertname': 'InstanceDown', 'instance': '10.0.3.173', 'job': 'scylla', 'monitor': 'scylla-monitor', 'severity': '2'}


< t:2022-03-11 14:15:37,963 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-03-11T14:15:37+00:00 gemini-1tb-10h-master-db-node-dfd0facd-5 !    INFO |  [shard 0] init - Scylla version 5.1.dev-0.20220303.0544973b15dd initialization completed.

< t:2022-03-11 14:16:03,909 f:nemesis.py      l:2801 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.GeminiChaosMonkey: Recover the target node by a final rebuild
< t:2022-03-11 14:16:05,013 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
< t:2022-03-11 14:16:05,014 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-11 14:16:05.013: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=3f659b26-9291-4eea-ac22-b24ede8468f9: nodetool_command=rebuild node=gemini-1tb-10h-master-db-node-dfd0facd-5

< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2618, in run_nodetool
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = _run()
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = connection.run(**command_kwargs)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise UnexpectedExit(result)
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Command: '/usr/bin/nodetool  rebuild '
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Exit code: 1
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stdout:
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-03-11 14:16:07,158 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation rebuild is in progress, try again)
```






Restore Monitor Stack command: `$ hydra investigate show-monitor dfd0facd-6f45-41fb-b5fb-c289529348e7`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=dfd0facd-6f45-41fb-b5fb-c289529348e7](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3Ddfd0facd-6f45-41fb-b5fb-c289529348e7&source=gmail-html&ust=1647419196287000&usg=AOvVaw19Nd_gFHvDeu-V6Nfb61ue))
Show all stored logs command: `$ hydra investigate show-logs dfd0facd-6f45-41fb-b5fb-c289529348e7`

Test id: `dfd0facd-6f45-41fb-b5fb-c289529348e7`


Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_145626/grafana-screenshot-gemini-1tb-10h-scylla-per-server-metrics-nemesis-20220311_145626-gemini-1tb-10h-master-monitor-node-dfd0facd-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_145626/grafana-screenshot-gemini-1tb-10h-scylla-per-server-metrics-nemesis-20220311_145626-gemini-1tb-10h-master-monitor-node-dfd0facd-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_145626/grafana-screenshot-gemini-1tb-10h-scylla-per-server-metrics-nemesis-20220311_145626-gemini-1tb-10h-master-monitor-node-dfd0facd-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_145626/grafana-screenshot-gemini-1tb-10h-scylla-per-server-metrics-nemesis-20220311_145626-gemini-1tb-10h-master-monitor-node-dfd0facd-1.png)&source=gmail-html&ust=1647419196287000&usg=AOvVaw0F6-HYoK5atLmc9QZ_2vDm)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw12MtVjwT4bRqWlPUNPWWh_)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/loader-set-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/loader-set-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/loader-set-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/loader-set-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw1jJjnYgKxX_naS560PFCtq)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/monitor-set-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/monitor-set-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/monitor-set-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/monitor-set-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw3FT80Z59ksiTyo2mHs-M85)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw0uwgeMMnnVAxP6oDvRkxm3)


[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/148/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/148/&source=gmail-html&ust=1647419196288000&usg=AOvVaw1zjSZfWoi6a0qFK3oObbZI))

**Comment by roydahan** [comment]
I don't  think reopening  this is the correct approach.
The solution here is probably different, we need first to understand why the previous rebuild didn't failed with error and the code should also check the state of the rebuild before running the next rebuild.

**Comment by bentsi** [comment]
let's open a new issue
@juliayakovlev

**Comment by juliayakovlev** [comment]
New issue:
https://github.com/scylladb/scylla-cluster-tests/issues/4534
