### ISSUE TITLE
CassandraAWSCluster inherits ScyllaAWSCluster, not AWSCluster + BaseScyllaCluster

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#230]
@lmr any hint?

diff --git a/sdcm/cluster.py b/sdcm/cluster.py
index 70bbec3..96a29fb 100644
--- a/sdcm/cluster.py
+++ b/sdcm/cluster.py
@@ -2859,7 +2859,7 @@ class ScyllaAWSCluster(AWSCluster, BaseScyllaCluster):
         super(ScyllaAWSCluster, self).destroy()
 
 
-class CassandraAWSCluster(ScyllaAWSCluster):
+class CassandraAWSCluster(AWSCluster, BaseScyllaCluster):
 
     def __init__(self, ec2_ami_id, ec2_subnet_id, ec2_security_group_ids,
                  service, credentials, ec2_instance_type='c4.xlarge',

**Comment by lmr** [comment]
Basically because it uses a few methods defined in `ScyllaAWSCluster`, so it saves up code lines.
