### ISSUE TITLE
Reactor stall event is reported as "BACKTRACE"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2312]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2020.1
* **scylla**: 2020.1.rc1-0.20200621.0659b8e6599

### Logs
* test_id: 08a066b6-21c5-45ac-a26c-4995035779b5 (the test still running)
* job log: https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/longevity/job/longevity-1tb-7days/2/

### Description

Reactor stall event is reported as "BACKTRACE"
test_id: 08a066b6-21c5-45ac-a26c-4995035779b5 (the test still running)
job: https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/longevity/job/longevity-1tb-7days/2/

Example:
```
2020-06-23 15:55:41.000: (DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=344467 node=Node longevity-tls-1tb-7d-2020-1-db-node-08a066b6-1 [54.75.15.116 | 10.0.135.18] (seed: True)
```

**Comment by fgelcer** [comment]
issue was already fixed
