### ISSUE TITLE
Jenkins job fails, even though test was successful

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2335]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 
    - e77d7c3d-4c0b-46a0-a33a-d233f00361e9
    - d42a557c-1725-42cd-a63c-de8b38374dbf
    - 17bb29cb-b26e-4c00-89ae-6f8fb8fb6266
    - 6d0d8a43-5450-49bc-9a9a-358376288419
    - 61ec003e-629a-4f55-87e9-396b4db52702
    - 3c4bbe6e-f868-4dec-952a-b78da217e113
* job log: 
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos7-test/145/
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-test/137/
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu1604-test/119/
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu1804-test/119/
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian9-test/123/
    - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian10-test/120/

### Description

In all of the aforementioned jobs the tests passed with no issue, since no error occurred during their run. Even the summery email marked the runs as successful.
Yet, the jobs were marked as failures, and they did not run their attached triggers.

**Comment by roydahan** [comment]
This is not true:
```
======================================================================
02:00:36  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
02:00:36  ----------------------------------------------------------------------
02:00:36  sdcm.sct_events.TestResultEvent: 
02:00:36  ------------------------------------------------------------------------------
02:00:36  PASSED :)
02:00:36  
02:00:36  
02:00:36  ----------------------------------------------------------------------
02:00:36  Ran 1 test in 984.623s
02:00:36  
02:00:36  FAILED (errors=1)
02:00:39  [Pipeline] }
02:00:39  [Pipeline] // dir
02:00:39  [Pipeline] }
02:00:39  [Pipeline] // wrap
02:00:39  [Pipeline] }
02:00:39  ERROR: script returned exit code 1
02:00:39  [Pipeline] // catchError
02:00:39  [Pipeline] }
02:00:39  [Pipeline] // stage
02:00:39  [Pipeline] stage
02:00:39  [Pipeline] { (Collect log data ())
02:00:39  [Pipeline] catchError
```

**Comment by roydahan** [comment]
Now the real question is why we write there PASSES and even worse, why we send the PASSED email.

**Comment by roydahan** [comment]
@dkropachev is this something you're aware of?
It's blocking master...

**Comment by ShlomiBalalis** [comment]
The only thing I was able to find was an error when executing `sudo yum makecache` where yum could not find mirror for epel, so it was retried twice more, but it succeeded eventually, and that doesn't explain the rest of the artifacts

**Comment by dkropachev** [comment]
Fixed in https://github.com/scylladb/scylla-cluster-tests/pull/2334
