### ISSUE TITLE
"Aborting on shard" wasn't recognized in test

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2390]
### Prerequisites

* [ ] Are you rebased to master ? 
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2020.1
* **scylla**: 2020.1.rc1 (ami-0319b8d6938e962aa)

### Logs
* test_id: fc2b3559-3595-4921-973a-19392af2a1f6
* job log: https://jenkins.scylladb.com/job/enterprise-2020.1/job/longevity/job/longevity-2tb-4days-1Dis-2NonDis-Nemesises/3/

### Description

Got "Aborting on shard" - full description of the issue see [here](https://github.com/scylladb/scylla-enterprise/issues/1440).
But we didn't found it. There is no event for that and no this failure in the email.

**Comment by fruch** [comment]
It was found by SCT:
```
2020-07-14 18:10:44.000: (DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=90391 node=Node longevity-tls-2tb-4d-1dis-2nondis-2-db-node-fc2b3559-3 [54.154.250.82 | 10.0.143.79] (seed: False)
2020-07-14T18:10:44+00:00  longevity-tls-2tb-4d-1dis-2nondis-2-db-node-fc2b3559-3 !INFO    | scylla: Backtrace:

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:755
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigabrt_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3429
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3425
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
seastar::sharded<service::migration_manager>::local() at /usr/include/fmt/format.h:1158
 (inlined by) service::get_local_migration_manager() at ././service/migration_manager.hh:179
 (inlined by) operator() at ./service/migration_manager.cc:1090
 (inlined by) _M_invoke at /usr/include/c++/9/bits/std_function.h:286
std::function<seastar::future<> ()>::operator()() const at /usr/include/fmt/format.h:1158
 (inlined by) operator()<std::function<seastar::future<>()> > at ./schema_registry.cc:212
 (inlined by) do_with<std::function<seastar::future<>()>, schema_registry_entry::maybe_sync(std::function<seastar::future<>()>)::<lambda(auto:118&)> > at ././seastar/include/seastar/core/do_with.hh:94
 (inlined by) schema_registry_entry::maybe_sync(std::function<seastar::future<> ()>) at ./schema_registry.cc:213
operator() at /usr/include/fmt/format.h:1158
 (inlined by) apply<service::maybe_sync(const schema_ptr&, netw::messaging_service::msg_addr)::<lambda()>::<lambda()>&> at ././seastar/include/seastar/core/future.hh:1674
 (inlined by) run_and_dispose at ././seastar/include/seastar/core/smp.hh:215
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2695
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
main at ./main.cc:477
?? ??:0
_start at ??:?
```

we might want to catch something from the actual error:
```
2020-07-14T18:10:44+00:00  longevity-tls-2tb-4d-1dis-2nondis-2-db-node-fc2b3559-3 !INFO    | scylla: scylla: ./seastar/include/seastar/core/sharded.hh:718: Service& seastar::sharded<T>::local() [with Service = service::migration_manager]: Assertion `local_is_initialized()' failed.
```
in most error the word `exception` was what we were looking for

**Comment by juliayakovlev** [comment]
It doesn't exist in the email, see email with subject:
 FAILED: enterprise-2020.1/longevity/longevity-2tb-4days-1Dis-2NonDis-Nemesises: 2020-07-14 09:36:54

**Comment by juliayakovlev** [comment]
Maybe create event "AbortingOnShard" or something like this and not just backtrace. Backtrace it's not so clear what we got

**Comment by fruch** [comment]
> enterprise-2020.1/longevity/longevity-2tb-4days-1Dis-2NonDis-Nemesises: 2020-07-14 09:36:54

there was 33 error events, the email doesn't show all of them, 
the attachment so a bit more, but it can fit so many errors, you have logs for that.

**Comment by bentsi** [comment]
@juliayakovlev as Israel said, we don't show all the events in the email because of the size limitations. I am closing this.

**Comment by juliayakovlev** [comment]
@bentsi  On my opinion aborting on shard is not regular backtrace. We need let to it more accent

**Comment by roydahan** [comment]
There are several things here:
1. Let's add event detection on "aborting on" it's a coredump that we may miss while looking for the "BACKTRACE" which is too common.

2. I asked for it several times, we need to show ALL critical and error events in the attachment.
The limit size of attachment is 25 MB, in this case it was 126 kb.
first let's change it, if we find in the future that we hit this limit, we will do it smarter by checking the size before sending.

**Comment by roydahan** [comment]
@juliayakovlev first one is really easy and short, please send a PR to add such event.

**Comment by fruch** [comment]
we already have an event for abort, a whole mechanize for backtrace decoding
