### ISSUE TITLE
Enabling encryption at-rest for table keyspace1.standard1 cause test EaR-longevity-replicated-50gb-4d failure

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2391]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2020.1
* **scylla**: 2020.1.rc1

### Logs
* test_id: 2a0a0235-589c-40af-b031-f5d5cbeb96bc
* job log: https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/SCT_Enterprise_Features/job/EncryptionAtRest/job/EaR-longevity-replicated-50gb-4d-test/3/

### Description

Test EaR-longevity-replicated-50gb-4d-test

All c-s threads failed:
enable encryption at-rest for table keyspace1.standard1, query:
```
ALTER TABLE keyspace1.standard1 WITH scylla_encryption_options = { 'cipher_algorithm' : 'AES/ECB/PKCS5Padding', 'secret_key_strength' : 128, 'key_provider': 'ReplicatedKeyProviderFactory'};
Executing CQL 'ALTER TABLE keyspace1.standard1 WITH scylla_encryption_options = { 'cipher_algorithm' : 'AES/ECB/PKCS5Padding', 'secret_key_strength' : 
128, 'key_provider': 'ReplicatedKeyProviderFactory'};'...
Host 10.0.87.29:9042 error: Server error.
Host 10.0.165.83:9042 error: Server error.
Finished initializing connection for host 10.0.250.233:9042
Added pool for host 10.0.250.233:9042 to session
Host 10.0.21.120:9042 error: Server error.
Host 10.0.181.123:9042 error: Server error.
Host 10.0.92.47:9042 error: Server error.
Host 10.0.250.233:9042 error: Server error.
```

Run this query manually:
```
ALTER TABLE keyspace1.standard1 WITH scylla_encryption_options = { 'cipher_algorithm' : 'AES/ECB/PKCS5Padding', 'secret_key_strength' : 128, 'key_provider': 'ReplicatedKeyProviderFactory'};
```

Got error, that from some reason doesn't printed in any log:
```
ServerError: Could not validate system key: /resources/system_keys/system_key (std::_Nested_exception<std::invalid_argument> (Could not read '/resources/system_keys/system_key'): std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/resources/system_keys/system_key]))
```

**Comment by roydahan** [comment]
@juliayakovlev do we have the key on all nodes?

@amoskong are you familiar with the issue?
Does it happen in 2019.1?

**Comment by amoskong** [comment]
I didn't see this problem in 2019.1.

In this job, replicated encryption-at-rest is used. But the error is about the system key.
At least, the replicated encryption-at-rest worked in the past (2019.1) without preparing system key.

If it's expected, we only need to append 'system_key_directory: /etc/encrypt_conf/' parameter to `configurations/replicated-ear.yaml`

**Comment by amoskong** [comment]
The problem doesn't exist in old job (2019.1.3-0.20191024.afe4cf5b0)
- job: https://jenkins.scylladb.com/job/enterprise-2019.1/job/SCT_Enterprise_Feature/job/EncryptionAtRest/job/EaR-longevity-replicated-50gb-4d/2/consoleFull
- 6 db nodes

But I can reproduce this problem with the following versions by docker: (only one db node)
- 2019.1.3-0.20191028.afe4cf5b0
- 2019.1.9-0.20200610.ac769cb75

**Comment by amoskong** [comment]
In the old job, we only enable encryption-at-reset in pre-create schema stage.  (pre_create_schema should be enabled in configure file).
In latest SCT, encryption-at-rest of all test tables will be enabled by ALTER after write workloads are started.

I just posted a PR https://github.com/scylladb/scylla-cluster-tests/pull/2394 to fix this issue.
