### ISSUE TITLE
sct run didn't terminate for 2 days even though we had a Spot Termination in the beginning 

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2392]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id:  3694a5e1-cf51-401f-a2b0-61701c816853
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

| 20200719_060938 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/3694a5e1-cf51-401f-a2b0-61701c816853/20200719_060938/monitor-set-3694a5e1.zip |
| 20200719_060938 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/3694a5e1-cf51-401f-a2b0-61701c816853/20200719_060938/sct-runner-3694a5e1.zip  |

### Description

Longevity-200gb-48h was running for more than two days even though a sport termination event has been detected 30 minutes after the test started.

link:
https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/52/

**Expected behavior:** Terminate the run in 30-60 minutes

**Actual behavior:** The test was running for more than 2 days

**Comment by roydahan** [comment]
@nizarh11 Is spot termination event defined as critical event?
If not, please send a PR to fix.

**Comment by nizarh11** [comment]
Yes 

> @nizarh11 Is spot termination event defined as critical event?
> If not, please send a PR to fix.
