### ISSUE TITLE
SDCM version utils prevents use of custom repository

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#2430]
commit e14191bc4c2e45ee90f3bc77940d51700a8725a6 introduced a check on the repository url, this check validates that
`scylla.com` is present on the url. This is not the case when using a developers custom repository for example.

The problematic check is:
`SCYLLA_URL_REGEX = re.compile(".*(?P<url>http.*scylladb.com.*).*")`

**Comment by Orenef11** [comment]
> commit [e14191b](https://github.com/scylladb/scylla-cluster-tests/commit/e14191bc4c2e45ee90f3bc77940d51700a8725a6) introduced a check on the repository url, this check validates that
> `scylla.com` is present on the url. This is not the case when using a developers custom repository for example.
> 
> The problematic check is:
> `SCYLLA_URL_REGEX = re.compile(".*(?P<url>http.*scylladb.com.*).*")`


Can you add the repository URL where the validation fails?
I can add a special flag to ignore this validation, but I do not think that is a good thing there a repository URL without scylladb as hostname ..

**Comment by Orenef11** [comment]
@ShlomiBalalis
The purpose of this validation is to check within the file only links from Scylla and not links from other directories.
Therefore, to support this option as well, the validation will check that URL is an IP address (as in your case) or a Scylla address.
Will the solution to solve your problem?

@fruch
 what do you think?

**Comment by fruch** [comment]
> @ShlomiBalalis
> The purpose of this validation is to check within the file only links from Scylla and not links from other directories.
> Therefore, to support this option as well, the validation will check that URL is an IP address (as in your case) or a Scylla address.
> Will the solution to solve your problem?
> 
> @fruch
> what do you think?

That I don't agree, and we should block private repo addresses, our validations is for checking this repo is working as expected, i.e. that it has scylla package in it, nothing else. cause of cases releng team we building broken repos by mistake.

if @eliransin want to use a private repo host on his computer, we should enable it.

**Comment by Orenef11** [comment]
> > @eliransin
> > The purpose of this validation is to check within the file only links from Scylla and not links from other directories.
> > Therefore, to support this option as well, the validation will check that URL is an IP address (as in your case) or a Scylla address.
> > Will the solution to solve your problem?
> > @fruch
> > what do you think?
> 
> That I don't agree, and we should block private repo addresses, our validations is for checking this repo is working as expected, i.e. that it has scylla package in it, nothing else. cause of cases releng team we building broken repos by mistake.
> 
> if @eliransin want to use a private repo host on his computer, we should enable it.

For this solution, I need another variable to know that it is a private repo (or does it already exist?)
