### ISSUE TITLE
Logs are not being collected due to job timeout 

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2515]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master 

3a6d0343-fad0-4a30-834f-f33cbb9b74e4

### Logs
* test_id: 3a6d0343-fad0-4a30-834f-f33cbb9b74e4
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/61/

### Description

When SCT test fails on timeout, the rest of the steps are being aborted [Collect log data | Clean resources | Send email with result | Declarative: Post Actions]

**In case the instance is terminated we can not get any logs for the run.****

To solve the issue I recommend:
(-) use Jenkins artifacts to save logs (since it was removed on the new runner)
(-) add timeout on the step level, this will only affect the step instead of the main job

**Comment by nizarh11** [comment]
@roydahan @bentsi @fruch what do you think ?

**Comment by roydahan** [comment]
@bentsi, why did you remove the copy of the artifacts to jenkins?
Can we add this back?

**Comment by enaydanov** [comment]
Each step wrapped with catching errors in our pipelines already and it doesn't look as a good idea to run a code not covered by any timeout in `post` section. I think that it's better to add some default timeout to each step and use `timeout` parameter for SCT test step only.

Something like following:

Checkout: 60s
Create SCT runner: 150s
SCT test: use pipeline parameter
Collecting logs: 20m
Cleanup: 5m
Send email: 120s

**Comment by fruch** [comment]
I think ##2494 should be doing just that...

**Comment by bentsi** [comment]
As Israel, mentioned, this is handled in https://github.com/scylladb/scylla-cluster-tests/pull/2494
