### ISSUE TITLE
SCT runner is using Jenkins master as an executor 

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2520]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master

### Logs
* job log:https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput/35/consoleFull

### Description

After changing the AWS region to "eu-north-1" , I see SCT is running/exceuting on master(Jenkins) instead of choosing a different builder.

```
17:32:43  Running on Jenkins in /var/lib/jenkins/jobs/scylla-master/jobs/scylla-master-perf-regression-aws-test-throughput/workspace

```

link: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput/35/consoleFull

**Comment by roydahan** [comment]
@bentsi ?
not sure it's a real issue.

**Comment by nizarh11** [comment]
> @bentsi ?
> not sure it's a real issue.

The job is failing because docker is not installed,  And I don't think its a good idea to install docker on master
```17:33:00  Docker not installed!!! Please run 'install-hydra.sh'!```

**Comment by bentsi** [comment]
@nizarh11 you are using `branch-perf-v8` that doesn't have a new code for `vars/getJenkinsLabels.groovy` that prevents running on Jenkins master and fails with a relevant error message. This had been already fixed in master when SCT Runner was introduced. So closing this.

**Comment by nizarh11** [comment]
@roydahan Do you know why are we using branch "branch-perf-v8"? Who is responsible for this job?

**Comment by fruch** [comment]
@nizarh11 @fgelcer is working on a PR to fix this branch
https://github.com/scylladb/scylla-cluster-tests/pull/2530

seems like it still need some work
