### ISSUE TITLE
nodetool disableautocompaction failed on new node due to missing keyspace during adding new node to cluster

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#2528]
### Prerequisites

* [x] Are you rebased to master ? branch-4.2
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master/branch-4.2
* **scylla**: branch-4.2

### Logs
* test_id: 35fb970f-857d-4d75-82b2-c8ae325166ea
* job log: https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-200gb-48h-test/7
https://cloudius-jenkins-test.s3.amazonaws.com/35fb970f-857d-4d75-82b2-c8ae325166ea/20200816_135352/sct-runner-35fb970f.zip

### Description

on latest job: https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/longevity/job/longevity-200gb-48h-test/7, nemesis 
Decommission failed with error:
```
Command: 'nodetool -u cassandra -pw cassandra  enableautocompaction keyspace1'

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/auto_compaction/keyspace1' failed: std::runtime_error (Too early: storage service not initialized yet)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```

this happened during adding new node to cluster with Nemesis._add_and_init_new_cluster_node method execution.
if disable_autocompaction is true, then the next  code is executed.
```
                for keyspace in keyspaces:
                    new_node.run_nodetool(sub_cmd='disableautocompaction', args=keyspace, ignore_status=True)
```

but this command failed 
```
< t:2020-08-14 15:49:15,546 f:nemesis.py      l:476  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: During bootstrap, autocompaction will be disabled for keyspaces ['keyspace1']
< t:2020-08-14 15:49:15,547 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "nodetool -u cassandra -pw cassandra  disableautocompaction keyspace1"...
< t:2020-08-14 15:49:16,461 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > nodetool: Keyspace [keyspace1] does not exist.
< t:2020-08-14 15:49:16,461 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > See 'nodetool help' or 'nodetool help <command>'.
```
because the new node don't sync schemas yet. And this could be related to sct code:
```
self.cluster.wait_for_init(node_list=[new_node], timeout=timeout, wait_db_up=False, check_node_health=False)
```
in this case `wait_db_up=False, check_node_health=False` the sct don't wait that scylla is ready

so when new node is up and we try to enable autocompaction on keyspace, we got an error, because the compaction is running at this moment for that keyspace.

also `new_node.run_nodetool(sub_cmd='disableautocompaction', args=keyspace, ignore_status=True)` has ignore status.

**Expected behavior:**
autocompaction should be properly disabled on new node
May be we should have another logic to properly disableautocompaction: detect that schemas are synced by validating the shema version on new node or 
may we have some scylla api command,  

**Actual behavior:** [What actually happened]
autocompaction is not disabled

**Comment by fgelcer** [comment]
on it

**Comment by roydahan** [comment]
let's remove this code.

**Comment by fgelcer** [comment]
> let's remove this code.

PR sent #2536
