### ISSUE TITLE
make it configurable to use public or private ip in ssh connections

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#253]
@abvgedeika just found a problem, currently we use private ip for ssh connections, which was changed by https://github.com/scylladb/scylla-cluster-tests/commit/1ac5d0b61cf549d62fa257f82ff5ee35ca973b19

But if we execute SCT in localhost, then it failed to connect remote instances. Let's add a parameter in configure file to control it, and use private ip by default.

**Comment by roydahan** [comment]
@kongove, that's what I commented on the original PR.
Not everyone uses SCT machine in the same place as their deployment.
I think the default should be public.

**Comment by kongove** [comment]
I just revert a patch to make the ssh connections still use public ip.

https://github.com/scylladb/scylla-cluster-tests/pull/255

**Comment by roydahan** [comment]
Can this one be closed now?

**Comment by lmr** [comment]
@roydahan I took a look and there's no configurability in the code just yet:

https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L974

And other places. So this issue can't be closed just yet.

**Comment by roydahan** [comment]
Oh my bad, the PR was just to revert the code to use public.

**Comment by lmr** [comment]
@roydahan I suggested a possible implementation to solve this ticket in #264.

**Comment by kongove** [comment]
@lmr  PR #264 looks good, I will test it, thanks.

**Comment by kongove** [comment]
Solved by https://github.com/scylladb/scylla-cluster-tests/commit/0a10b9f87858d9ebe689e198087706df48a682b2
