### ISSUE TITLE
failed to get price for c4.2xlarge in eu-north-1

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2555]
Versions
* **SCT**: Master
* **scylla**: [branch or commit hash]

### Logs

Log links for testrun with test id 9e669d36-d4d8-4f5c-93a5-e9215b993c8a                                           |
| 20200821_032151 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/9e669d36-d4d8-4f5c-93a5-e9215b993c8a/20200821_032151/db-cluster-9e669d36.zip |
| 20200821_032151 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/9e669d36-d4d8-4f5c-93a5-e9215b993c8a/20200821_032151/sct-runner-9e669d36.zip |

### Description

**2020-08-21 03:21:25.996: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp() 
exception=failed to get price for c4.2xlarge in eu-north-1**

https://jenkins.scylladb.com/job/scylla-master/view/master-test/job/longevity/job/longevity-50gb-4days/

**Comment by nizarh11** [comment]
@roydahan i see "eu-north-1" doesn't have "c4.2xlarge", what instance type should i use instead? [longevity-50gb-4days]

**Comment by roydahan** [comment]
Check if it has c5.
@ShlomiBalalis has a task to change all places we use c4 to c5.
Feel free to do it yourself and take his Trello task.

**Comment by fruch** [comment]
fixed by #2566
