### ISSUE TITLE
When investigating old issues, Prometheus metrics disappear some time after restoring them

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-cluster-tests#2558]
Prometheus metrics for old issues restored by `hydra investigate show-monitor` disappear some time (2-3h) after being restored.

This seems to be caused by Prometheus having default time retention (15 days). This is the first line from `docker logs <prometheus-container>`:

```
level=info ts=2020-08-26T10:08:05.500Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
```

This can be a little annoying during long debugging sessions, as it forces the user to manually save/restore all custom Grafana panels created by them.

**Comment by piodul** [comment]
Correction: it's actually possible to stop old Grafana instance, run `hydra investigate show-monitor` again and reuse opened Grafana browser tabs. This probably requires Grafana to be accessed through exactly the same address and port. `show-monitor` assigns a random port for Grafana, so I opened a ssh tunnel with the same local port as previous Grafana instance.

Nevertheless, if it is not much hassle to increase the retantion, it might be worth doing it to avoid needing such workarounds.

**Comment by fruch** [comment]
https://www.robustperception.io/configuring-prometheus-storage-retention

I think we should just do that by size, like 1TB, would be enough.

**Comment by fruch** [comment]
@aleksbykov I think you fixed that, right ?

**Comment by aleksbykov** [comment]
Yes, I think it was changed to 3 months
