### ISSUE TITLE
GrowShrinkCluster nemesis should correctly add/del nodes in multidc tests

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#2561]
### Prerequisites

* [x] Are you rebased to master ? branch-4.2
* [x] Is it reproducible ? for multidc tests
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.2
* **scylla**: branch-4.2

### Logs
* test_id: c4563a17-0912-4945-9e5b-0cb2c97050f7
* job : https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-alternator-3h-multidc-test/6
* sct logs: https://cloudius-jenkins-test.s3.amazonaws.com/c4563a17-0912-4945-9e5b-0cb2c97050f7/20200826_110016/sct-runner-c4563a17.zip

### Description

Nemesis GrowShrinkCluster adds  and in nemesis_interval removes number of node(s) set in config parameter:  nemesis_add_node_cnt: 1
There is no problem if test run in single DC.
But in multi dc tests, this nemesis could add new node(s) to one DC, and remove node(s) in another.
In this case we can get next:
```
< t:2020-08-26 09:42:30,371 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > Datacenter: eu-westscylla_node_west
< t:2020-08-26 09:42:30,372 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > ===================================
< t:2020-08-26 09:42:30,373 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > Status=Up/Down
< t:2020-08-26 09:42:30,373 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2020-08-26 09:42:30,374 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > --  Address        Load       Tokens       Owns    Host ID                               Rack
< t:2020-08-26 09:42:30,382 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  54.75.35.170   92.48 GB   256          ?       e218e0fb-76b0-4cf9-9ef2-39f3778561bb  1a
< t:2020-08-26 09:42:30,386 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  52.18.161.38   55.96 GB   256          ?       3f479370-bda4-451f-ac91-e49157439461  1a
< t:2020-08-26 09:42:30,389 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  34.255.205.1   100.88 GB  256          ?       370f8052-338a-43e0-b6f7-e9db1fdd7149  1a
< t:2020-08-26 09:42:30,394 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  34.252.127.35  82.43 GB   256          ?       0b291738-6c5e-4303-a0c8-da173c5c12a0  1a
< t:2020-08-26 09:42:30,394 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > Datacenter: us-eastscylla_node_east
< t:2020-08-26 09:42:30,401 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > ===================================
< t:2020-08-26 09:42:30,402 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > Status=Up/Down
< t:2020-08-26 09:42:30,402 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2020-08-26 09:42:30,404 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > --  Address        Load       Tokens       Owns    Host ID                               Rack
< t:2020-08-26 09:42:30,404 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  3.236.154.89   127.84 GB  256          ?       6780f3b0-3e44-4627-a7c9-a87f859313d4  1a
< t:2020-08-26 09:42:30,407 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > UN  3.227.20.232   123.7 GB   256          ?       6cc08cc0-de8f-42b5-944a-9c3782b6ff3f  1a
< t:2020-08-26 09:42:30,407 f:base.py         l:187  c:RemoteCmdRunner      p:DEBUG > 
```
and if next nemesis choose target node in DC where only 2 nodes and this nemesis will be Disruptive, then stress-commands could fail and fail all jobs.

### Steps to Reproduce

1. Run test with Multidc
2. Set only sequence: GrowShrinkCluster, {AnyDisruptiveNemesis}
3. Stress commands and job will fail.

**Expected behavior:** [What you expected to happen]
Nemesis should add and remove nodes in same Datacenter
**Actual behavior:** [What actually happened]
Add/remove nodes in different DCes.

**Comment by fruch** [comment]
@aleksbykov it's actually a more general issue, across all nemesis that replaces nodes, like Decommision and RemoveNode.

**Comment by roydahan** [comment]
Are the stress commands in this test runs with LOCAL_QUORUM or QUORUM?
if QUORUM it shouldn't matter to them.

Anyway, let's fix the nemesis.

**Comment by fruch** [comment]
Alternator defaults to LOCAL_QUORUM, when multidc.
No way to configure it via dynamodb api, only via CQL

**Comment by fruch** [comment]
Alternator defaults to LOCAL_QUORUM, when multidc.
No way to configure it via dynamodb api, only via CQL

**Comment by roydahan** [comment]
Does someone work on this issue?

**Comment by aleksbykov** [comment]
@roydahan i don't started yet
