### ISSUE TITLE
pipeline:scylla-4.2:gemini-3h-test: Failed on send mail with result stage

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#2637]
During scylla-4.2.rc4 release process gemini-3h-test failed on `send mail with result` stage , 

https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/gemini-/job/gemini-3h-test/49/console

**Comment by yaronkaikov** [comment]
@fruch

**Comment by fruch** [comment]
job of that failure are long gone (as well as scylla 4.2)
