### ISSUE TITLE
Critical event does not stop the test, when it occurs in a subtest

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2697]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: b5f1e9a3-ed7d-4a6c-a394-7f554153903d
* job log: https://jenkins.scylladb.com/job/mermaid-master/job/centos-upgrade-test/19/

### Description

When a critical event occurs during a subtest, the event is silence, and it will not rise and the test will not fail.
The event:
```
< t:2020-09-15 02:35:34,505 f:cluster.py      l:2392 c:sdcm.cluster_aws     p:CRITICAL > Node manager-upgrade-master-db-node-b5f1e9a3-2 [3.236.161.110 | 10.0.2.38] (seed: False): Command 'nodetool  info ' error: Critical Error has failed the test
```
But, afterwards the test continues on, to the next subtest.

### Steps to Reproduce

1. create an sct run with subtest
2. make a critical event occur during the subtest

**Expected behavior:** the event will rise normally, even during subtest

**Actual behavior:** the event is silenced

**Comment by fruch** [comment]
this is a confusion between critical event and critical log print
the first would stop the test, the latter would not.
