### ISSUE TITLE
Restarting a nemesis after stopping it

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2724]
Some tests would like to stop a nemesis perhaps to perform some checks on the cluster without it being disrupted in the meantime, and then restart it to continue the test.

I thought that
```
            self.db_cluster.stop_nemesis()
```
followed by
```
            self.db_cluster.start_nemesis()
```
would do that, but it seems the second call doesn't restart the nemesis fully: something prevents it from running any more disruptions. See e.g.
https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/feature-cdc-replication-longevity/12/console
where in the logs we can see
```
15:33:01  < t:2020-09-23 13:33:00,903 f:cdc_replication_test.py l:157  c:CDCReplicationTest   p:INFO  > Starting round 1
15:33:01  < t:2020-09-23 13:33:00,905 f:cdc_replication_test.py l:159  c:CDCReplicationTest   p:INFO  > Starting nemesis
15:33:01  < t:2020-09-23 13:33:00,905 f:nemesis.py      l:196  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Interval: 300 s
```

but no disruptions occur.

@fruch said in an email
> Seems like there an termination_event kept on the cluster object, it's need to be initialized again (gets initialized only on cluster constructor)
So I guess the second round it stop immediately, since this event is already set.

It sounds like the feature should be easy to implement by simply removing this event on `start_nemesis`?

**Comment by fruch** [comment]
We can't remove it, since this the way we communicate to the thread running the nemesis to stop.

We just need to initialize it again.
