### ISSUE TITLE
enable append_scylla_args on kubernetes backend

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#2747]
### Description
Currently there is no way to pass scylla-operator options to add into command that is used to spin up containers.
 Once ~~https://github.com/scylladb/scylla-operator/issues/192~~ https://github.com/scylladb/scylla-operator/issues/177 is fixed we can have sct code that will enable it for kubernetes.

**Comment by vponomaryov** [comment]
https://github.com/scylladb/scylla-operator/issues/177 is implemented long time ago.
SCT support is also added, it is here: https://github.com/scylladb/scylla-cluster-tests/pull/4905
Closing it as `fixed`
