### ISSUE TITLE
Failed to get spot instances: capacity-not-available on multiple master jobs

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#2798]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

many master jobs failed on this error ( 3h/4h/alternator etc.):
02:28:12  < t:2020-10-15 23:28:10,871 f:tester.py       l:118  c:sdcm.tester          p:ERROR > sdcm.ec2_client.CreateSpotInstancesError: Failed to get spot instances: capacity-not-available

### Versions
* **SCT**: master
* **scylla**: ami-0fc29826ba4f062e3

### Logs

example job log:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/242/execution/node/113/log/

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by roydahan** [comment]
This is not an issue, trigger the job in a different region or AZ.
