### ISSUE TITLE
`sct.py run-test` killed - test run `TearDown()` and there is no mention to `TEST_END`

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2851]
### Versions
* **SCT**: branch-4.3 4a3b004111c2c31d96d1a0dcf6538d1d7cdf0418
* **scylla**: 4.3.rc0

`sct.py run-test` killed - test run `TearDown()` and there is no mention to `TEST_END`
it is not clear though why the test was killed like this (it doesn't seem to be due to ENOSP as logs were collected to S3)
the test timeout is 3000 minutes (and the pipeline is 3100) but the test was killed after ~2700 minutes
full logs can be found here:

[db-cluster](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/db-cluster-4bf96148.zip)
[loader-set](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/loader-set-4bf96148.zip)
[monitor-set](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/monitor-set-4bf96148.zip)
[sct-runner](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/sct-runner-4bf96148.zip)

the email report came without the test_results, but logs were stored in S3
```
Failed to read test results for 4bf96148-9fe5-4633-b130-b2701213a876
```

**Comment by roydahan** [comment]
@dkropachev I know you found some issues with timeouts and durations when worked on master, can you help with this one?
Does it look the same?
From how it looks to me, it ends due to one of the timeouts.

**Comment by roydahan** [comment]
```
08:28:44  /bin/bash: line 1:    30 Killed                  ./sct.py run-test longevity_test.LongevityTest.test_custom_time --backend aws
08:28:44  Cleaning SSH agent
08:28:44  Agent pid 3658750 killed
```

**Comment by bentsi** [comment]
Highly likely it was killed by OOM

**Comment by fgelcer** [comment]
@bentsi said that it could be related to the runner being killed due to OOM

in my scenario the test is the one with parallel nemesis, and it have almost 15k ERROR events

**Comment by fruch** [comment]
I guess we don't have the logs from the SCT runner, we'll need it's logs to be certain...

We don't have logs collect for the SCT runner at least not yet

**Comment by fgelcer** [comment]
> I guess we don't have the logs from the SCT runner, we'll need it's logs to be certain...
> 
> We don't have logs collect for the SCT runner at least not yet

link to sct runner logs [here](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/sct-runner-4bf96148.zip)

**Comment by fruch** [comment]
> > I guess we don't have the logs from the SCT runner, we'll need it's logs to be certain...
> > We don't have logs collect for the SCT runner at least not yet
> 
> link to sct runner logs [here](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/sct-runner-4bf96148.zip)

this is the sct log, I was talking about the system logs, of the SCT runner machine. we don't have that uploaded

**Comment by fgelcer** [comment]
> > > I guess we don't have the logs from the SCT runner, we'll need it's logs to be certain...
> > > We don't have logs collect for the SCT runner at least not yet
> > 
> > 
> > link to sct runner logs [here](https://cloudius-jenkins-test.s3.amazonaws.com/4bf96148-9fe5-4633-b130-b2701213a876/20201106_062853/sct-runner-4bf96148.zip)
> 
> this is the sct log, I was talking about the system logs, of the SCT runner machine. we don't have that uploaded

we don't actually upload SCT runner syslogs (and maybe we should), and that SCT runner was already terminated, so, no, we don't have access to it

**Comment by Orenef11** [comment]
Happened for `rolling-upgrade` JOB:
https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-debian10-test/25/console

```
03:03:05  Failed to read test results for 44bc1972-a2e9-47ce-9774-089ea8cb64cd
03:03:17  Prepare result to send in email
03:03:17  Rendering results to html using 'results_aborted.html' template...
03:03:17  Results has been rendered to html
03:03:17  Rendering results to html using 'results_aborted.html' template...
03:03:17  Results has been rendered to html
03:03:17  HTML report saved to '/jenkins/slave/workspace/scylla-4.3/rolling-upgrade/rolling-upgrade-debian10-test/scylla-cluster-tests/20210110-212635-896242/email_report.html'.
03:03:17  Rendering results to html using 'results_issue_template.html' template...
03:03:17  Results has been rendered to html
03:03:17  HTML report saved to '/jenkins/slave/workspace/scylla-4.3/rolling-upgrade/rolling-upgrade-debian10-test/scylla-cluster-tests/20210110-212635-896242/issue_template.html'.
03:03:18  Send email with results to ['qa@scylladb.com']
03:03:19  + echo 'Email sent'
03:03:19  Email sent
03:03:19  [Pipeline] }
03:03:19  [Pipeline] // dir
03:03:19  [Pipeline] }
03:03:20  [Pipeline] // wrap
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // catchError
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // stage
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // withEnv
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // node
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // parallel
03:03:20  [Pipeline] }
03:03:20  [Pipeline] // script
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // stage
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // timeout
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // timestamps
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // withCredentials
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // withEnv
03:03:21  [Pipeline] }
03:03:21  [Pipeline] // node
03:03:21  [Pipeline] End of Pipeline
03:03:22  Finished: FAILURE
```

**Comment by fgelcer** [comment]
> Happened for `rolling-upgrade` JOB:
> https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-debian10-test/25/console
> 

@Orenef11 , if you had opened the `sct.log` from your job, you would see that the event is in there:
```
< t:2021-01-11 00:44:59,839 f:sct_events.py   l:976  c:sdcm.sct_events      p:INFO  > 2021-01-11 00:44:59.827: (InfoEvent Severity.NORMAL): message=TEST_END
```
