### ISSUE TITLE
Scylla is started when scylla-machine-image didn't finish setup

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#2855]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?

### Versions
* **SCT**: latest master (0cde646c)

### Description

In the artifact test, when starting Scylla service we don't wait until `scylla-machine-image` finishes.

**Expected behavior:** 
Artifact test succeeds, Scylla is started after the scylla-machine-image finished.

**Comment by fruch** [comment]
don't we start without user-data ?, and scylla-server starts on it's own ?

**Comment by fruch** [comment]
is this for GCE test  ? 

for AWS we have `_wait_for_preinstalled_scylla(node)` implemented, in all other cluster is empty function...

**Comment by bentsi** [comment]
For AWS it doesn't work correctly. For GCE cluster it is not implemented.

**Comment by fruch** [comment]
Now I'm feeling ashamed,

Cause I've noticed that the AWS is broken for a while (and wasting lots of time at creating a cluster)
had a fix, but forgot to put it on a PR:
83129f6c1066b8f5b6ed961125e172f93f2a4450
