### ISSUE TITLE
Scylla fails to be installed on OEL76

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#2858]
@ShlomiBalalis commented on [Tue Nov 03 2020](https://github.com/scylladb/scylla/issues/7536)

*Installation details*
Scylla version (or git commit hash): scylla-666.development-0.20201101.6be9f4938.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d6a24fe35fdf5dc4 (eu-west-1)

In the artifact test or oel76 the installation of scylla fails due to a conflict with the kernel:
```
Command: 'sudo yum install -y scylla'

Exit code: 1

Stdout:

Installed size: 341 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               39 MB/s | 127 MB  00:03     
Running transaction check
ERROR with transaction check vs depsolve:
kernel < 3.10.0-514 conflicts with scylla-server-666.development-0.20201101.6be9f4938.x86_64
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2020-11-01.23-25.DruJI0.yumtx

Stderr:

```

Logs:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 4632c7fd-f283-43c0-997e-3cdef6d569e9                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20201101_232552 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/4632c7fd-f283-43c0-997e-3cdef6d569e9/20201101_232552/db-cluster-4632c7fd.zip |
| 20201101_232552 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/4632c7fd-f283-43c0-997e-3cdef6d569e9/20201101_232552/sct-runner-4632c7fd.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```

---

@roydahan commented on [Tue Nov 03 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721022716)

@syuu1228 / @penberg 

---

@avikivity commented on [Tue Nov 03 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721043489)

Not a bug. That installation has a old kernel that scylla doesn't like.

---

@roydahan commented on [Wed Nov 04 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721616691)

@tzach please update support matrix, what we need to support.
If we're stop supporting OEL 7.6 and move to support later version 7.7 - 8.2? (I have no idea what is their kernel versions).
We used OEL7.6 AMI from AWS and with the kernel version it comes with.

---

@tzach commented on [Wed Nov 04 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721618563)

Good point
Look like https://docs.scylladb.com/getting-started/os-support/ is out of date
@avikivity can you please clarify what is supported (and from which Scylla version)

---

@avikivity commented on [Wed Nov 04 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721621652)

OEL 7.6 is supported. See https://blogs.oracle.com/linux/announcing-the-release-of-oracle-linux-7-update-6.

>Oracle Linux 7 Update 6 ships with the following kernel packages:
>
>Unbreakable Enterprise Kernel (UEK) Release 5 (4.14.35-1818.3.3) for x86-64 and Arm
>Red Hat Compatible Kernel (3.10.0-957) for x86-64 only

957 is greater than 514. That AMI had some old kernel installed, not a 7.6 kernel.

---

@roydahan commented on [Wed Nov 04 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721781712)

Ok, we need to document somewhere what is the minimum kernel supported.
Until last week this kernel was just fine for us.

Also, do we need to support the UEK?

---

@avikivity commented on [Wed Nov 04 2020](https://github.com/scylladb/scylla/issues/7536#issuecomment-721912718)

We support 3.10.0-514 or later. Yes, we support UEK.

**Comment by roydahan** [comment]
We have two options here:
1. run kernel update to latest every time we run the test.
2. Switch to a newer AMI, with 8.x release hopefully it uses newer kernel.

**Comment by roydahan** [comment]
@amoskong as our kernels expert, can you please take care of it?

**Comment by fruch** [comment]
I'm trying out option #2 
https://github.com/scylladb/scylla-cluster-tests/pull/2915

**Comment by amoskong** [comment]
On OEL, `kernel-uek` (Unbreakable Enterprise Kernel) is used, all installed kernel and kernel-uek are >= 3.10.0-514
But the installation failed.

I just reported a new issue: https://github.com/scylladb/scylla/issues/7675

The default kernel on OEL7.6 is :
```
[clckwrk@ip-172-31-14-204 ~]$ uname -a
Linux ip-172-31-14-204 4.14.35-1902.5.2.2.el7uek.x86_64 #2 SMP Fri Sep 20 00:39:39 GMT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by amoskong** [comment]
The kernel check of rpm had been removed by https://github.com/scylladb/scylla/commit/6238d105d9eaf30d50fd9a20fc9d1bbfcdcf458b

This install issue won't happen.

@roydahan Let's close this issue?

Meanwhile, we need to merge the new PR of oel8.1 (https://github.com/scylladb/scylla-cluster-tests/pull/2915)
