### ISSUE TITLE
The "longevity-cdc-100gb-4h-test" JOB failed because "reached timeout"

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla-cluster-tests#2885]
The stress command takes 240mins (4 hours) and the total time of JOB is 260MINS (4 hours and 20 minutes).

 
![image](https://user-images.githubusercontent.com/11705430/99275332-0a3b4900-2834-11eb-85ad-c2e2256d47b3.png)

**Comment by roydahan** [comment]
Why not just sending PR to fix it?

**Comment by Orenef11** [comment]
> Why not just sending PR to fix it?

Ill do it :-)

**Comment by Orenef11** [comment]
The issue is fixed
