### ISSUE TITLE
Do not reuqire root to install hydra

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-cluster-tests#2947]
- If the Docker or Podman or Pip are not installed, promote the suggested commands to install them.
- Do not link to /usr/local/bin

With the above, we can install and use hydra as plain user.

**Comment by fruch** [comment]
just a comment, I don't think it's working with podman (at least not yet)

**Comment by asias** [comment]
> just a comment, I don't think it's working with podman (at least not yet)

It does not. I tried multiple times in the past.
