### ISSUE TITLE
NonRoot offline install: fetch scylla-server log from ~/scylladb/scylla-server.log

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#3066]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: scylla master & 4.3

### Logs

test id: fb649268-6c3a-4f5b-9fe0-34c3cfc76890
version: scylla-unified-package-4.4.dev.0.20201225.72c2482f7.tar.gz

### Description

Scylla-server log was redirected to ~/scylladb/scylla-server.log after https://github.com/scylladb/scylla/commit/0f786f05fed41be94b09e33aa34a767074a14ec1

So current 'journalctl' cmdline can't fetch the scylla-server log, the log file in test result is empty.

```
[amos@amos-centos7 fb649268-6c3a-4f5b-9fe0-34c3cfc76890]$ cat db-cluster-fb649268.zip/artifacts-centos8-jenkins-db-node-fb649268-0-1/system.log 
No journal files were found.
[amos@amos-centos7 fb649268-6c3a-4f5b-9fe0-34c3cfc76890]$ 
```

### Steps to Reproduce

1. run any nonroot artifact test

**Expected behavior:** [What you expected to happen]
scylla-server log in ~/scylladb/scylla-server.log is fetched and archived.

**Actual behavior:** [What actually happened]
No scylla-server log archived

/Cc @aleksbykov

**Comment by aleksbykov** [comment]
@amos, logcollecter have to collect scylla-server.log during log collecting?
or even sct doesn't write any output frin scylla-server.log to sct logs?

**Comment by amoskong** [comment]
> @Amos, logcollecter have to collect scylla-server.log during log collecting?

Currently the logcollecter try to fetch log by journalctl cmd

> or even sct doesn't write any output frin scylla-server.log to sct logs?

It's not problem of writing, but the log source.

I have sent a fix:
