### ISSUE TITLE
private_repo_test is failing to connect to SQL server

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#3069]
It's failes with the following error:
```
mysql.connector.errors.InterfaceError: 2055: Lost connection to MySQL server at 'scylla-downloads-v2.cluster-cmibwi2oeyz8.us-west-2.rds.amazonaws.com:3306', system error: 1 [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)
```

Seem like since we move to debian based docker image this happend

this sounds like a fix:
https://stackoverflow.com/a/62158260

**Comment by juliayakovlev** [comment]
@bentsi FYI

@fruch We have very old MySQL version and this issue connected to old version. We tried this code against new MYSQL version and it works. So we need to upgrade

**Comment by fruch** [comment]
It was fixed long long time ago
