### ISSUE TITLE
Need to add rsyslog support for Scylla Monitoring 3.6

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-cluster-tests#3089]
The monitoring stack now listen to incoming rsyslog traffic on port: 1514

We need to add an rsyslog file: a file to /etc/rsyslog.d/

something like:
$ cat  /etc/rsyslog.d/scylla.conf
if $programname == 'scylla' then @@$IP:1514;RSYSLOG_SyslogProtocol23Format

 Where $IP is the IP address of the monitoring serve

**Comment by roydahan** [comment]
Opened a task in trello
