### ISSUE TITLE
Upgrade tests doesn't test encryption at rest

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#3114]
Scylla upgrade test doesn't contain encryption at rest tables.

**Comment by eliransin** [comment]
@roydahan / @fruch does anyone looking into it?

**Comment by roydahan** [comment]
We have a task for it, but no one is working on it at the moment.

**Comment by fruch** [comment]
We do want to get to it as part of some work we are doing for KMS...

**Comment by roydahan** [comment]
There is a separate task in QA tasks for it (assigned to @ShlomiBalalis). 
For KMS you can create a new task not in SCT or put it in the test plan.
