### ISSUE TITLE
1Tb use case can't finish the prepare stage

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#3121]
See scylladb/scylla#7748,

# Summary 
in 4.3 testing we starting seeing issue with getting the 1tb case finishing prepare stage
after multiple runs it was identified that SCT branch 4.2 is working and passing.

we should identify what are the change that are causing it

My guesses:
* Enabling shared awareness - if so, we'll open it on java-driver repo, and continue investigation of 7748 in that context
* the extra logging we now enable in default for c-s - if so we should consider to make them optional, and add a way to disable them by default.

**Comment by roydahan** [comment]
Did we do the opposite test to use the old loader and see that it works with it?
If not, let's do it.
It should be fairly east, just change the loader ami and run.
@ShlomiBalalis can you please do it?
(make sure that if it passes the prepare this way, kill the cluster immediately and no need to wait with it).
