### ISSUE TITLE
After the hostname change script has been applied on the loader, rsyslog.service failed after restart.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#3147]
*Installation details*
Scylla version (or git commit hash): ``
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f6a2c84c3cbfbf2b` (aws: eu-north-1)

Test: `longevity-cdc-100gb-4h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-cdc-100gb-4h.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/ca8a02961c8a045df4e2ea49d1cc2fde06d11620/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

**Issue description**

After the hostname change script has been applied on the loader 1, rsyslog.service failed after restart.
There is no error:
```
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 sudo[1732]:   centos : TTY=unknown ; PWD=/home/centos ; USER=root ; COMMAND=/bin/bash -cxe
                                                                                 if ! grep "\$LocalHostname longevity-cdc-100gb-4h-master-loader-node-05799dd2-1" /etc/rsyslog.conf; then
                                                                                     echo "" >> /etc/rsyslog.conf
                                                                                     echo "\$LocalHostname longevity-cdc-100gb-4h-master-loader-node-05799dd2-1" >> /etc/rsyslog.conf
                                                                                 fi
                                                                                 grep -P "127.0.0.1[^\\n]+longevity-cdc-100gb-4h-master-loader-node-05799dd2-1" /etc/hosts || sed -ri "s/(127.0.0.1[ \t]+localhost[^\n]*)$/\1\tlongevity-cdc-
100gb-4h-master-loader-node-05799dd2-1/" /etc/hosts
                                                                                 grep "preserve_hostname: true" /etc/cloud/cloud.cfg 1>/dev/null 2>&1 || echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
                                                                                 systemctl restart rsyslog
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 sudo[1732]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Stopping System Logging Service...
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 rsyslogd[1525]:  [origin software="rsyslogd" swVersion="8.24.0-52.el7_8.2" x-pid="1525" x-info="http://www.rsyslog.com"] exiting on signal 15.
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Stopped System Logging Service.
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Starting System Logging Service...
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Failed to start System Logging Service.
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Unit rsyslog.service entered failed state.
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: rsyslog.service failed.
Jan 14 12:28:54 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 sudo[1732]: pam_unix(sudo:session): session closed for user root
```

But after second  restart it succeeded to up:
```
Jan 14 12:28:55 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Stopped System Logging Service.
Jan 14 12:28:55 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Starting System Logging Service...
Jan 14 12:28:55 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 rsyslogd[1752]:  [origin software="rsyslogd" swVersion="8.24.0-52.el7_8.2" x-pid="1752" x-info="http://www.rsyslog.com"] start
Jan 14 12:28:55 longevity-cdc-100gb-4h-master-loader-node-05799dd2-1 systemd[1]: Started System Logging Service.
```

Maybe we need to retry restarting of  rsyslog.service and validate that all changes were done

Restore Monitor Stack command: `$ hydra investigate show-monitor 05799dd2-1d43-43f3-af65-7f9ba2811f26`
Show all stored logs command: `$ hydra investigate show-logs 05799dd2-1d43-43f3-af65-7f9ba2811f26`

Test id: `05799dd2-1d43-43f3-af65-7f9ba2811f26`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/db-cluster-05799dd2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/db-cluster-05799dd2.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/loader-set-05799dd2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/loader-set-05799dd2.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/sct-runner-05799dd2.zip](https://cloudius-jenkins-test.s3.amazonaws.com/05799dd2-1d43-43f3-af65-7f9ba2811f26/20210114_122930/sct-runner-05799dd2.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/170/)

**Comment by fruch** [comment]
the hostname change is a problematic part, I think we should reconsider if we still want to do that.

**Comment by roydahan** [comment]
Is this still relevant?
I don't think we bumped into it since...
