### ISSUE TITLE
First run new pipelines when creating a new release

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#3154]
When you create new pipelines for a new release:
There is a need to first run each pipeline, so it will read the properties from code.
After creating the new pipelines, when you try to run them, you only have "build now" and not "build with parameters".
This run will fail, as you can't give the relevant parameters.

Another option is to copy the pipelines from older branch, so you have the parameters.

The work around, is to manually run all new pipelines.

**Comment by hagitsegev** [comment]
Nice idea.

**Comment by fruch** [comment]
> Nice idea.

sound like a bit like `dry-run` in scylla-pkg, which I think we don't have in SCT pipelines

**Comment by hagitsegev** [comment]
This is not exactly like our dry-run.
This one just say: "OK, didn't get parameters, so I quit, I guess someone ran me to re-read parameters". This will give an "OK" status on the first run.
While our dry-run do some process verification. It will give "error" status on the first run.
I think I'll add this ability too.

Adding some dry-run parameter will be useful for me too, so when I debug - I'll call your tests in dry-run, when I need to debug the calling chain.

**Comment by fruch** [comment]
we already doing this
