### ISSUE TITLE
Jespen run cmd failed with Exit code: 255

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3164]
```
14:47:51  2021-01-20 12:30:54.361: (TestFrameworkEvent Severity.ERROR), source=JepsenTest.test_jepsen (jepsen_test.JepsenTest)() message=Traceback (most recent call last):
14:47:51  File "/jenkins/slave/workspace/scylla-master/jepsen/jespen_all_private_debug/scylla-cluster-tests/jepsen_test.py", line 58, in test_jepsen
14:47:51  self.jepsen_node.remoter.run(jepsen_cmd)
14:47:51  File "/jenkins/slave/workspace/scylla-master/jepsen/jespen_all_private_debug/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
14:47:51  result = _run()
14:47:51  File "/jenkins/slave/workspace/scylla-master/jepsen/jespen_all_private_debug/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
14:47:51  return func(*args, **kwargs)
14:47:51  File "/jenkins/slave/workspace/scylla-master/jepsen/jespen_all_private_debug/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
14:47:51  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
14:47:51  File "/jenkins/slave/workspace/scylla-master/jepsen/jespen_all_private_debug/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
14:47:51  result = connection.run(**command_kwargs)
14:47:51  File "<decorator-gen-3>", line 2, in run
14:47:51  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
14:47:51  return method(self, *args, **kwargs)
14:47:51  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
14:47:51  return self._run(self._remote_runner(), command, **kwargs)
14:47:51  File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
14:47:51  return runner.run(command, **kwargs)
14:47:51  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
14:47:51  return self._run_body(command, **kwargs)
14:47:51  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
14:47:51  raise UnexpectedExit(result)
14:47:51  invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
14:47:51  Command: 'cd ~/jepsen-scylla && ~/lein run test-all --node 10.142.15.210 --node 10.142.15.211 --node 10.142.15.216 --node 10.142.15.217 --node 10.142.15.218 --username sct --ssh-private-key ~/db_node_ssh_key --no-install-scylla'
14:47:51  Exit code: 255
14:47:51  Stdout:
14:47:51  cset lwt pause,kill,partition,clock,membership
14:47:51  mv lwt pause,kill,partition,clock,membership
14:47:51  write-isolation lwt pause,kill,partition,clock,membership
14:47:51  list-append lwt pause,kill,partition,clock,membership
14:47:51  wr-register lwt pause,kill,partition,clock,membership
14:47:51  0 successes
14:47:51  0 unknown
14:47:51  48 crashed
14:47:51  0 failures
14:47:51  Stderr:
14:47:51  WARNING: group-by already refers to: #'clojure.core/group-by in namespace: scylla.counter, being replaced by: #'qbits.hayt/group-by
14:47:51  WARNING: update already refers to: #'clojure.core/update in namespace: scylla.counter, being replaced by: #'qbits.hayt/update
14:47:51  WARNING: group-by already refers to: #'clojure.core/group-by in namespace: scylla.mv, being replaced by: #'qbits.hayt/group-by
14:47:51  WARNING: update already refers to: #'clojure.core/update in namespace: scylla.mv, being replaced by: #'qbits.hayt/update
14:47:51  Warning: protocol #'jepsen.nemesis.membership.state/State is overwriting function resolve
14:47:51  WARNING: resolve already refers to: #'clojure.core/resolve in namespace: jepsen.nemesis.membership.state, being replaced by: #'jepsen.nemesis.membership.state/resolve
14:47:51  WARNING: group-by already refers to: #'clojure.core/group-by in namespace: scylla.collections.map, being replaced by: #'qbits.hayt/group-by
14:47:51  WARNING: update already refers to: #'clojure.core/update in namespace: scylla.collections.map, being replaced by: #'qbits.hayt/update
14:47:51  WARNING: group-by already refers to: #'clojure.core/group-by in namespace: scylla.collections.set, being replaced by: #'qbits.hayt/group-by
14:47:51  WARNING: update already refers to: #'clojure.core/update in namespace: scylla.collections.set, being replaced by: #'qbits.hayt/update
```
Test details
Test: jepsen_test.JepsenTest.test_jepsen
Build number: 1
Backend: gce: us-east1
Test-id: 8df64503-2891-42cf-a544-8bfbf70d6dea
Start time: 2021-01-20 12:25:01
End time: 2021-01-20 12:39:48
Started by user: yarongilor
Private repo: http://downloads.scylladb.com.s3.amazonaws.com/deb/unstable/unified/master/2020-12-08T19:40:17Z/scylladb-master/scylla.list
Test result
FAILED
Jepsen parameters
Jepsen repo: https://github.com/scylladb/jepsen.git
Jepsen test command: test-all
System under test
ScyllaDB version: 4.4.dev-0.20201208.f802356572
ScyllaDB repo: http://downloads.scylladb.com.s3.amazonaws.com/deb/unstable/unified/master/2020-12-08T19:40:17Z/scylladb-master/scylla.list
Instance type: n1-standard-4
Number of ScyllaDB nodes: 5

Hydra commands:
Restore Monitor Stack command: $ hydra investigate show-monitor 8df64503-2891-42cf-a544-8bfbf70d6dea
Show all stored logs command: $ hydra investigate show-logs 8df64503-2891-42cf-a544-8bfbf70d6dea
Logs:
prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/prometheus_snapshot_20210120_123941.tar.gz
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_123054/grafana-screenshot-jespen_all_private_debug-scylla-per-server-metrics-nemesis-20210120_123516-jepsen-jenkins-monitor-node-8df64503-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_123054/grafana-screenshot-overview-20210120_123054-jepsen-jenkins-monitor-node-8df64503-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_123948/grafana-screenshot-jespen_all_private_debug-scylla-per-server-metrics-nemesis-20210120_124308-jepsen-jenkins-monitor-node-8df64503-0-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_123948/grafana-screenshot-overview-20210120_123948-jepsen-jenkins-monitor-node-8df64503-0-1.png
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_124810/db-cluster-8df64503.zip
jepsen-data - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_124810/jepsen-data.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_124810/loader-set-8df64503.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_124810/monitor-set-8df64503.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/8df64503-2891-42cf-a544-8bfbf70d6dea/20210120_124810/sct-runner-8df64503.zip

**Comment by enaydanov** [comment]
Looks like something wrong with my patch to scylladb/jepsen:

```
clojure.lang.ArityException: Wrong number of args (1) passed to: scylla.db/install!
```

Need to improve my Clojure.

**Comment by enaydanov** [comment]
Due to https://stackoverflow.com/a/55737594 need to replace `when` with `cond->`
