### ISSUE TITLE
If nodetool removenode command failed, the nemesis TerminateAndREmoveNode leave in cluster DN node

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#3173]
### Versions
* **SCT**: master/branch-4.4
* **scylla**: branch-4.4

### Logs
* test_id: a92a84b6-e2e9-4d07-8aa6-a85bf96363f8
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/a92a84b6-e2e9-4d07-8aa6-a85bf96363f8/20210125_232251/sct-runner-a92a84b6.zip

### Description

During the mentioned test-id: a92a84b6-e2e9-4d07-8aa6-a85bf96363f8 job with longevity-cdc-4h

nemesis TerminateAndREmoveNode was failed twice: during the repair command on each node and during nodetool  removenode.
This code:
```

        def remove_node():
            # nodetool removenode 'host_id'
            rnd_node = random.choice([n for n in self.cluster.nodes if n is not self.target_node])
            self.log.info("Running removenode command on {}, Removing node with the following host_id: {}"
                          .format(rnd_node.ip_address, host_id))
            res = rnd_node.run_nodetool("removenode {}".format(host_id), ignore_status=True, verbose=True)
            return res.exit_status

        exit_status = remove_node()
        assert exit_status == 0, "nodetool removenode command exited with status {}".format(exit_status)

```

if command failed, then the disrupt method also failed, and target node will stay in DN, it will not be removed from cluster, and will continue to in DN till end of test

**Expected behavior:** [What you expected to happen]
if command failed, then scylla on target node should be restarted or target node should be terminated and replaced with new one.

**Actual behavior:** [What actually happened]

**Comment by roydahan** [comment]
The cluster health validator should have caught it when the nemesis completed (or the new one started) and raise a critical event that would have stop the test.
If that's not what happened, the issue is with cluster health validator and we need more info.
If it's what happen, then excellent, this is what we expect.

**Comment by aleksbykov** [comment]
@roydahan @bentsi @fruch @enaydanov 
Need your help in resolving the issue.
Disrupt method [disrupt_remove_node_then_add_node](https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2142) has next logic:
1. Stop the scylla on target node https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2172
2. Terminate instance https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2175
3. Remove node from up_and_normal list https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2178
4. run repair on each node https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2185
5. run nodetool removenode target_node https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2198
6. assert status of command https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2199
7. Add new node https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2207

The issue was found during job [longevity-cdc-4h](https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-cdc-4h-test/8). 
Nemesis started. Scylla successfully stopped on target node. At this moment the status in cluster is DN. after that the instance is terminated https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2175 and its ip was put into cluster.dead_nodes_ip_address_list: https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/cluster.py#L3019

then commands `nodetool repai`r and `nodetool removenode` are failed: https://github.com/scylladb/scylla/issues/7965

The nemesis is failed on assertion: https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/nemesis.py#L2199
and all rest of nemesis code is not executed. So we get situation that cluster have 5 instances alive and nodetool status return result that 5 nodes are UN and 6th node is DN.

After that the health_validator check the cluster status with function [`check_nodes_status`](https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/utils/health_checker.py#L36).
and return Event with severity Error https://github.com/scylladb/scylla-cluster-tests/blob/26d4bdfd231554e1fdd001e2c789cf8b8629ac82/sdcm/utils/health_checker.py#L54 instead of event with severity Critical, because the ip of terminated node is in dead_nodes_ip_list.

Because of event has severity Error, the test is continue to run. and health_validator will continue report that one node in cluster has status DN, but will not stop the test. This could lead that no instances stay in cluster if the nemesis TerminateAndRemoveNode will be run several times and each time command `nodetool removenode` will fail

The issue could be resolved in several ways:
1. replace the `assert` with if statements and trigger Critical event if nodetool command failed
2. instead of critical event in if statemnts, remove ip from dead_node list, then health_validator will trigger critical event
3. And critical event into nemesis.py:log_time_elapsed_and_status in addition to log.error message that number of nodes is differ before and after the nemesis
4.  if we assume that test could continue to run, we can add last_cluster_status_checker, which will store latest wrong health_validator results, and if current nemesis detect that status before and after execution is the same, change severity of reporting from error to debug

**Comment by roydahan** [comment]
@aleksbykov thanks for the very detailed summary.
I support option 2 because it sounds most natively fit to our current design.
It basically restore the configuration to the previous state.

Another option that could be even simpler, is to remove the node from up_and_normal_list ONLY after the nodetool remove finished.
If needed, we can run the the repair on the [list] - (dead_node).

Regarding the assert vs If it's even more general question, I don't think we currently have asserts inside the nemesis.

@fruch , @bentsi , @juliayakovlev thoughts?

**Comment by juliayakovlev** [comment]
> @aleksbykov thanks for the very detailed summary.
> I support option 2 because it sounds most natively fit to our current design.
> It basically restore the configuration to the previous state.
> 
> Another option that could be even simpler, is to remove the node from up_and_normal_list ONLY after the nodetool remove finished.

Agree with this option. Remove from up_and_normal_list and add to dead_node list only if `nodetool removenode` succeeded. Not sure if failure of `repair` should raise critical event.

> If needed, we can run the the repair on the [list] - (dead_node).
> 
> Regarding the assert vs If it's even more general question, I don't think we currently have asserts inside the nemesis.
> 
> @fruch , @bentsi , @juliayakovlev thoughts?

**Comment by roydahan** [comment]
@aleksbykov if we haven't done so yet, let's do option number one/two.
Simplest as possible, remove the assert and fail the nemesis and then the test will fail due to DN.
