### ISSUE TITLE
artifacts-docker-test clean-resources fails with: "AMI for scylla version latest wasn't found"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3185]
Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 7
Backend: docker
Test-id: b8fad7d2-eae1-4236-9800-c4777ca460d8
Start time: 2021-01-29 18:52:07
End time: 2021-01-29 18:58:34
Started by user: timer

System under test
ScyllaDB version:
Actual docker image used: scylladb/scylla-nightly:4.4.rc0-0.20210128.f470c5d4d
Instance type: N/A
Scylla packages installed:
scylla-conf-4.4.rc0-0.20210128.f470c5d4d.x86_64
scylla-kernel-conf-4.4.rc0-0.20210128.f470c5d4d.x86_64
scylla-tools-core-4.4.rc0-0.20210128.f470c5d4d.noarch
scylla-node-exporter-4.4.rc0-0.20210128.f470c5d4d.x86_64
scylla-python3-4.4.rc0-0.20210128.f470c5d4d.x86_64
scylla-jmx-4.4.rc0-0.20210128.f470c5d4d.noarch
scylla-tools-4.4.rc0-0.20210128.f470c5d4d.noarch
scylla-server-4.4.rc0-0.20210128.f470c5d4d.x86_64
scylla-4.4.rc0-0.20210128.f470c5d4d.x86_64

https://jenkins.scylladb.com/job/scylla-4.4/job/artifacts/job/artifacts-docker-test/7/

error:
```
21:02:30  Traceback (most recent call last):
21:02:30    File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/./sct.py", line 866, in <module>
21:02:30      cli()
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
21:02:30      return self.main(*args, **kwargs)
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
21:02:30      rv = self.invoke(ctx)
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
21:02:30      return _process_result(sub_ctx.command.invoke(sub_ctx))
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
21:02:30      return ctx.invoke(self.callback, **ctx.params)
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
21:02:30      return callback(*args, **kwargs)
21:02:30    File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
21:02:30      return f(get_current_context(), *args, **kwargs)
21:02:30    File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/./sct.py", line 160, in clean_resources
21:02:30      clean_func = partial(clean_resources_according_post_behavior, config=SCTConfiguration(), logdir=logdir)
21:02:30    File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/sct_config.py", line 1233, in __init__
21:02:30      raise ValueError("AMI for scylla version {} wasn't found".format(scylla_version))
21:02:30  ValueError: AMI for scylla version latest wasn't found
```

**Comment by fruch** [comment]
seem like it's might be related to this change coming from master:
https://github.com/scylladb/scylla-cluster-tests/commit/7df555d336599fe4b1b837fc6b2a47d757138ed6
@amoskong can you elaborate on why this was changed ?

**Comment by roydahan** [comment]
@fruch, I don't understand how is this commit related?

**Comment by fruch** [comment]
> @fruch, I don't understand how is this commit related?

it change it from a version we could find an AMI for, (even that we don't need to be looking for AMI at that point, but we do regardless), to a `scylla_version` we can't find an AMI for.

that commit is the root cause that surfaced up this issue, not necessary reverting it is the fix.
it's not clear to me why that change was happening, for what reason.

**Comment by roydahan** [comment]
ok, but why do we need AMI for docker test?

**Comment by amoskong** [comment]
The real test passed, the problem occurred in cleaning resources.
We need to assign backend when we clean the resources.

**Comment by amoskong** [comment]
https://jenkins.scylladb.com/job/scylla-4.4/job/artifacts/job/artifacts-docker-test/10/console
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/231/

artifacts-docker tests of master and 4.4 had been PASSed

**Comment by hagitsegev** [comment]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/artifacts/job/artifacts-docker-test/231 is OK.
