### ISSUE TITLE
KCL log is not collected by SCT log collector

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3188]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by fruch** [comment]
@yarongilor 

Is this still true ?

**Comment by yarongilor** [comment]
Fixed in https://github.com/scylladb/scylla-cluster-tests/pull/3463
