### ISSUE TITLE
docker artifact test fail to clean resources (master, enterprise, 4.4)

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#3192]
This happened on last 3 runs of 
https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/artifacts/job/artifacts-docker-test/
Last run on https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-docker-test/32/console and 
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/artifacts/job/artifacts-docker-test/230/

19:46:34  Traceback (most recent call last):
19:46:34    File "/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/./sct.py", line 866, in <module>
19:46:34      cli()
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
19:46:34      return self.main(*args, **kwargs)
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
19:46:34      rv = self.invoke(ctx)
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
19:46:34      return _process_result(sub_ctx.command.invoke(sub_ctx))
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
19:46:34      return ctx.invoke(self.callback, **ctx.params)
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
19:46:34      return callback(*args, **kwargs)
19:46:34    File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
19:46:34      return f(get_current_context(), *args, **kwargs)
19:46:34    File "/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/./sct.py", line 160, in clean_resources
19:46:34      clean_func = partial(clean_resources_according_post_behavior, config=SCTConfiguration(), logdir=logdir)
19:46:34    File "/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/sct_config.py", line 1233, in __init__
19:46:34      raise ValueError("AMI for scylla version {} wasn't found".format(scylla_version))
19:46:34  ValueError: AMI for scylla version latest wasn't found

**Comment by roydahan** [comment]
Dup of #3185
