### ISSUE TITLE
Rolling Upgrade tests should be deterministic about on which version they run queries on (old or new)

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#3198]
In order to avoid issues like scylladb/scylla-enterprise#1612 going under the radar the rolling upgrade test should be deterministic 
about which versions they run the queries and different verification functions on. In the aforementioned issue, the test is flaky 
since there is a difference in behavior between when the alter query runs on an upgraded coordinator node or on a plain node. 
The test is prone to fail when the former happens. This means that the test should run queries of all types on both types of nodes 
or the test is flaky and can pass even when there is a bug that the queries should have caught and the cql driver chooses the 
"wrong" node as a coordinator.

**Comment by roydahan** [comment]
AFAIK there is no way to control which coordinator will serve the client.
Therefore, it's impossible for us to do it.

**Comment by eliransin** [comment]
@roydahan - I don't understand this pushback.
https://docs.datastax.com/en/developer/python-driver/3.24/api/cassandra/cluster/#cassandra.cluster.Session.execute
Notice the `host` parameter.
According to the documentation:
`execute (statement[, parameters][, timeout][, trace][, custom_payload][, paging_state][, host][, execute_as])`

```
host is the cassandra.pool.Host that should handle the query. If the host specified is down or not yet connected, the query will fail with NoHostAvailable. Using this is discouraged except in a few cases, e.g., querying node-local tables and applying schema changes.
```

**Comment by eliransin** [comment]
https://docs.datastax.com/en/developer/python-driver/3.24/api/cassandra/policies/#cassandra.policies.LoadBalancingPolicy
You can also rig the LoadBalancing policy and have 3 different sessions:
1. session with `OnlyOldLoadBalancingPolicy`
2. session with `OnlyNewLoadBalancingPolicy`
3. session with the normal default or whatever you use today:  `LoadBalancingPolicy`
You will of course need to implement 1 and 2...

**Comment by roydahan** [comment]
> @roydahan - I don't understand this pushback.
The tests should reflect real world scenarios.
Moreover:
> https://docs.datastax.com/en/developer/python-driver/3.24/api/cassandra/cluster/#cassandra.cluster.Session.execute
> Notice the `host` parameter.
> According to the documentation:
> `execute (statement[, parameters][, timeout][, trace][, custom_payload][, paging_state][, host][, execute_as])`
> 
> ```
> host is the cassandra.pool.Host that should handle the query. If the host specified is down or not yet connected, the query will fail with NoHostAvailable. Using this is discouraged except in a few cases, e.g., querying node-local tables and applying schema changes.
> ```

AFAIK, host parameter doesn't change anything, since we have HWLB and the request can reach any coordinator.
I don't know about LoadBalancingPolicy but I'm pretty positive it doesn't work as you expect it to work.

**Comment by eliransin** [comment]
HWLB? What do you mean by that? Hardware LB? You know it doesn't make any sense right? If this was the case so token awareness was not working at all (This is a product of the TokenAwareLoadBalancingPolicy).
And another question on that - how does your tests query local tables for example?

**Comment by eliransin** [comment]
Has anyone tried it? Don't you think that the test flakiness worth fixing?

**Comment by roydahan** [comment]
> HWLB? What do you mean by that? Hardware LB? You know it doesn't make any sense right? If this was the case so token awareness was not working at all (This is a product of the TokenAwareLoadBalancingPolicy).

Heat Weighted Load Balancing.
This is how scylla works and this is how we test it for a long time.

> And another question on that - how does your tests query local tables for example?
I doubt we care and if we really need, we have the tricks to do it (like stopping all other nodes).

**Comment by roydahan** [comment]
> Has anyone tried it? Don't you think that the test flakiness worth fixing?

It's not the first time we face this issue, in dtest we do it all the time.
