### ISSUE TITLE
Pull request check fails: unauthorized: please use personal access token to login

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#3218]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master

Failed check: https://jenkins.scylladb.com/blue/organizations/jenkins/sct-github-PRs-scan%2Fscylla-cluster-tests/detail/PR-3212/5/pipeline/
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-3212/workflow-stage/5

### Description

When I pushed a new change to https://github.com/scylladb/scylla-cluster-tests/pull/3212, all of the four checks of the pr failed, with the following error:
```
[2021-02-10T08:41:19.456Z] Error response from daemon: Get https://registry-1.docker.io/v2/scylladb/hydra/manifests/v0.87: unauthorized: please use personal access token to login
```

Upon rerun, however, the error did not reproduce.

**Comment by fruch** [comment]
happened again 
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-3225/1/

**Comment by fruch** [comment]
And again:
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-3217/8/console

**Comment by fruch** [comment]
It was a specific builder having the issue, when logging into it, seem like someone did `docker login`  hence the failure
```
[jenkins@aws-scylla-qa-builder ~]$ docker login                                                       
Authenticating with existing credentials...                                                           
Stored credentials invalid or expired                                                                                                                                                                        
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (yaronkaikov): ^C                      
```

FYI @yaronkaikov, please don't login to dockerhub on the SCT builders (on jenkins user), since break them for us.
