### ISSUE TITLE
artifact tests: keep_on_failure logic is not respected in artifact tests (and possibly other tests)

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#3232]
When running in Jenkins, the clean resources stage of the artifact tests does not respect the "keep_on_failure" setting for db
instances.
Link to failing job:
https://jenkins.scylladb.com/job/scylla-enterprise/job/artifacts/job/artifacts-centos7-test/79/

**Comment by roydahan** [comment]
@enaydanov can you please check?

**Comment by enaydanov** [comment]
There are no critical events during this run but only critical events matter for keep-on-failure.
