### ISSUE TITLE
loader ami is overridden by default ami when running on a different region

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3257]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 4.4

*Installation details*
Scylla version (or git commit hash): `4.4.rc1-0.20210210.5b6c28428 with build-id 6b0809e6195738bc6d0948a86885be2cadd9eac1`
Cluster size: 1 nodes (i3.8xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-01ca3b82f1341c9ac` (aws: eu-north-1)

Test: `longevity-5000-tables-test`
Test name: `longevity_test.LongevityTest.test_user_batch_custom_time`
Test config file(s):
- [longevity-5000-tables.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/d87c34b777642d5b30737a7d469409a111d1ed72/test-cases/longevity/longevity-5000-tables.yaml)

### Logs
Test id: `77831148-1ed7-430b-867d-11c26275d85b`
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/77831148-1ed7-430b-867d-11c26275d85b/20210217_115351/sct-runner-77831148.zip](https://cloudius-jenkins-test.s3.amazonaws.com/77831148-1ed7-430b-867d-11c26275d85b/20210217_115351/sct-runner-77831148.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-5000-tables-test/3/)

### Description

scenario:
1. test yaml has:
   eu-west-1:
     ami_id_loader: 'ami-0bf19545bc7bc9e1f'  
```
regions_data:
  us-east-1:
    ami_id_loader: 'ami-0b94f0e897d884b1b'
  eu-west-1:
    ami_id_loader: 'ami-0bf19545bc7bc9e1f'
  us-west-2:
    ami_id_loader: 'ami-063a97bde47353690'
```
2.    The test was selected to run on eu-north-1.
==> RESULTS:

1) then test yaml 'ami-0bf19545bc7bc9e1f'  of eu-west-1 is mentioned but ignored.
2) the default loader ami for eu-north-1 was taken from aws_config.yaml - 'ami-0e7be192027c68454' # Loader dedicated AMI v16
```
12:22:28  ami_id_loader: ami-0bf19545bc7bc9e1f
12:24:50  < t:2021-02-21 10:24:50,315 f:sct_config.py   l:1320 c:sdcm.sct_config      p:INFO  > ami_id_loader: ami-0e7be192027c68454
```
3) the overriding loader AMI is not reported in test email anywhere. 

### Steps to Reproduce

1. rerun the test same where selecting a region different that the test yaml.

**Expected behavior:** no override

**Actual behavior:** override

**Comment by yarongilor** [comment]
Cc @roydahan

**Comment by fruch** [comment]
@yarongilor what exactly is the bug here... it run the loader according to the region. What exactly do you expect it todo ?

**Comment by roydahan** [comment]
AFAIU, we have Ami for loader inside the test yaml to be used which is not
the Ami stated in the defaults AWS config file.
But the loader Ami that is being used is the one from the default and not
the one from the yaml.

What I’m not sure about Yaron’s description is if it happens only when
changing a region or always.

Another possibility is that Yaron chose a region that wasn’t in the test
yaml and that’s why it took the default. In this case it’s not a bug.

**Comment by yarongilor** [comment]
i expect that:
 if any loader AMI is specified ==> test must NOT take any default for any region.
it totally doesn't make sense to do so.
you can decide how to fail the test in a case where the are missing AMIs for selected regions but it surely doesn't make sense to override it.

**Comment by yarongilor** [comment]
you will probably want to use this logic for scalability, performance and driver-related-features tests.

of course an alternative solution would be copying AMI automatically to a needed region.

**Comment by roydahan** [comment]
Yaron, If the region isn't in the yaml, the region was not override.
It was taken from the config where it's the only place mentioned.

It'll not be simple to change and anyway the direction is not using AMI's.

So, as a temp fix, please check all places we specify a loader AMI that isn't the default and make sure it has the correct version for all regions.

**Comment by fgelcer** [comment]
we now search loader images by name. problem is mitigated even before that though.
