### ISSUE TITLE
Test wasn't stopping cleanly on critical event

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#3276]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log:
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/63/

### Summary

Test failed catching the critical error, but kept running for 3 more days:
```
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1289, in verify_stress_thread
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     results, errors = cs_thread_pool.verify_results()
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 263, in verify_results
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     for future in concurrent.futures.as_completed(self.results_futures, timeout=self.timeout):
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 245, in as_completed
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     waiter.event.wait(wait_timeout)
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/threading.py", line 574, in wait
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     signaled = self._cond.wait(timeout)
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/threading.py", line 316, in wait
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     gotit = waiter.acquire(True, timeout)
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 201, in critical_failure_handler
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     raise AssertionError("Critical Error has failed the test")
< t:2021-02-26 14:19:01,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > AssertionError: Critical Error has failed the test
```

## Logs

* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/db-cluster-147194be.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/loader-set-147194be.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/monitor-set-147194be.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/147194be-61d9-456d-b7f4-2631e84617a9/20210301_065832/sct-runner-147194be.zip

**Comment by fruch** [comment]
Also happened on:
## Logs
* **db-cluster** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/db-cluster-ad480eeb.zip
* **loader-set** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/loader-set-ad480eeb.zip
* **monitor-set** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/monitor-set-ad480eeb.zip
* **sct-runner** - https://cloudius-jenkins-test.s3.amazonaws.com/ad480eeb-4248-4276-b93a-c88ef24cf6f9/20210228_051940/sct-runner-ad480eeb.zip
* Restore Monitor Stack command: $ hydra investigate show-monitor ad480eeb-4248-4276-b93a-c88ef24cf6f9
* Show all stored logs command: $ hydra investigate show-logs ad480eeb-4248-4276-b93a-c88ef24cf6f9

**Comment by fruch** [comment]
@enaydanov can you help me figure this one out ? couldn't easily find the reason why test were stopped after the critical events in those cases

**Comment by enaydanov** [comment]
@fruch it got many critical events in a short time. Do you think it can be a cause of this problem? Many SIGUSR2 signals? I think we need a flag that test is already stopping and don't try to send SIGUSR2 again.

**Comment by fruch** [comment]
> @fruch it got many critical events in a short time. Do you think it can be a cause of this problem? Many SIGUSR2 signals? I think we need a flag that test is already stopping and don't try to send SIGUSR2 again.

Could be, I thought it had such a prevention (at least I think it had some safety before), but I guess we could add more.

**Comment by fruch** [comment]
> it seems like this one was fixed already

I haven't seen it since then

**Comment by fruch** [comment]
> it seems like this one was fixed already

I haven't seen it since then
