### ISSUE TITLE
NonDisruptiveMonkey mgmt_repair_cli fails during DisruptiveMonkey  repair_streaming_err

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3315]
scenario:
1. DisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method repair_streaming_err
2. NonDisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method mgmt_repair_cli
==> result:
mgmt_repair_cli fails with:
```
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > sctool output: ╭─────────────────────────────────────────────────────────────┬───────────┬───────────────────────────────┬─────────────╮
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > │ Task                                                        │ Arguments │ Next run                      │ Status      │
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > ├─────────────────────────────────────────────────────────────┼───────────┼───────────────────────────────┼─────────────┤
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck/fc6bc066-c0a7-4e6d-84ce-db4539611d07            │           │ 07 Mar 21 23:45:14 UTC (+15s) │ DONE        │
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck_alternator/a8d6fdcd-67e8-4519-ad39-53ab507dbcb3 │           │ 07 Mar 21 23:45:14 UTC (+15s) │ DONE        │
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > │ healthcheck_rest/cd344b6b-a964-42ab-bc2f-a2af87cc2997       │           │ 07 Mar 21 23:45:59 UTC (+1m)  │ NEW         │
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > │ repair/2254c47e-c168-4656-9a3d-8be4b4d93a1c                 │           │ 07 Mar 21 23:54:29 UTC        │ ERROR (1/4) │
< t:2021-03-07 23:45:03,028 f:cli.py          l:1001 c:sdcm.mgmt.cli        p:DEBUG > ╰─────────────────────────────────────────────────────────────┴───────────┴───────────────────────────────┴─────────────╯
< t:2021-03-07 23:45:03,028 f:cli.py          l:1017 c:sdcm.mgmt.cli        p:DEBUG > sctool res after parsing: [['Task', 'Arguments', 'Next run', 'Status'], ['healthcheck/fc6bc066-c0a7-4e6d-84ce-db4539611d07', '', '07 Mar 21 23:45:14 UTC (+15s)', 'DONE'], ['healthcheck_alternator/
a8d6fdcd-67e8-4519-ad39-53ab507dbcb3', '', '07 Mar 21 23:45:14 UTC (+15s)', 'DONE'], ['healthcheck_rest/cd344b6b-a964-42ab-bc2f-a2af87cc2997', '', '07 Mar 21 23:45:59 UTC (+1m)', 'NEW'], ['repair/2254c47e-c168-4656-9a3d-8be4b4d93a1c', '', '07 Mar 21 23:54:29 UTC', 'ERROR (1/4)']]
< t:2021-03-07 23:45:03,028 f:cli.py          l:1132 c:sdcm.mgmt.cli        p:DEBUG > repair/2254c47e-c168-4656-9a3d-8be4b4d93a1c status value is:ERROR (1/4)
< t:2021-03-07 23:45:03,028 f:nemesis.py      l:1014 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: ('Exception in random_disrupt_method %s: %s', 'mgmt_repair_cli', AssertionError('Task: repair/2254c47e-c168-4656-9a3d-8be4b4d93a1c final status is: ERROR.'))
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: Unhandled exception in method <function NonDisruptiveMonkey.disrupt at 0x7fd6e9beeca0> < t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: Unhandled exception in method <function NonDisruptiveMonkey.disrupt at 0x7fd6e9beeca0>
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2826, in wrapper
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3649, in disrupt
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method(disrupt_methods=self.disrupt_methods_list)
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1004, in call_random_disrupt_method
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     self.execute_disrupt_method(disrupt_method)
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1011, in execute_disrupt_method
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 163, in wrapped
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     res = func(*args, **kwargs)
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1703, in disrupt_mgmt_repair_cli
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR >     assert task_final_status == TaskStatus.DONE, 'Task: {} final status is: {}.'.format(
< t:2021-03-07 23:45:03,029 f:nemesis.py      l:2836 c:sdcm.nemesis         p:ERROR > AssertionError: Task: repair/2254c47e-c168-4656-9a3d-8be4b4d93a1c final status is: ERROR.
```

suggested fix: a full manager repair on all nodes should never run simultaneously with a disruptive nemesis that may take down a db node. it can, instead, run on a single node (the nemesis 'target node') only.

*Installation details*
Scylla version (or git commit hash): `4.4.rc3-0.20210304.c2d924757 with build-id 1d0929cbdc3fd39b79157e974cd8d08cd2610afb`
Cluster size: 5 nodes (i3en.3xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-07a91c0d7ed3e47be` (aws: eu-north-1)

Test: `longevity-2tb-4days-1Dis-2NonDis-Nemesises-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/29ec92f568d071fd6efbc1485303cd650eb7a09e/test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor ff466b17-7870-41bb-ba3a-d5247f4827d7`
Show all stored logs command: `$ hydra investigate show-logs ff466b17-7870-41bb-ba3a-d5247f4827d7`

Test id: `ff466b17-7870-41bb-ba3a-d5247f4827d7`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/db-cluster-ff466b17.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/db-cluster-ff466b17.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/loader-set-ff466b17.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/loader-set-ff466b17.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/monitor-set-ff466b17.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/monitor-set-ff466b17.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/sct-runner-ff466b17.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ff466b17-7870-41bb-ba3a-d5247f4827d7/20210309_154015/sct-runner-ff466b17.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-2tb-4days-1Dis-2NonDis-Nemesises-test/4/)

**Comment by fruch** [comment]
> suggested fix: a full manager repair on all nodes should never

Never what ? Can you explain what's the issue again ? You claim we can't do any other operations during repairs ?

**Comment by yarongilor** [comment]
> > suggested fix: a full manager repair on all nodes should never
> 
> Never what ? Can you explain what's the issue again ? You claim we can't do any other operations during repairs ?

(the next line was erased mistakenly, fixed that)
suggested fix: a full manager repair on all nodes should never run simultaneously with a disruptive nemesis that may take down a db node. it can, instead, run on a single node (the nemesis 'target node') only.

right, we cannot do any disruptive events during a general cluster repair.
