### ISSUE TITLE
LWT stress timeout error during memory-stress nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3346]
During memory-stress nemesis, the DB node gets a timeout of the alternator stress that uses LWT.
we probably should consider filtering such an event during this nemesis, since it may be expected.

error event received:
```
2021-03-24 21:22:29.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=26966 node=Node alternator-3h-4-4-db-node-ebf8c37f-6 [13.48.135.51 | 10.0.2.157] (seed: False)
2021-03-24T21:22:29+00:00  alternator-3h-4-4-db-node-ebf8c37f-6 !INFO    | scylla: [shard 11] rpc - client 10.0.2.250:52959 msg_id 13966:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
```
nemesis log:
```
< t:2021-03-24 21:18:37,791 f:nemesis.py      l:1008 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method memory_stress
< t:2021-03-24 21:18:37,792 f:nemesis.py      l:566  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> MemoryStress on Node alternator-3h-4-4-db-node-ebf8c37f-6 [13.48.135.51 | 10.0.2.157] (seed: False)
< t:2021-03-24 21:22:54,918 f:nemesis.py      l:1018 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method memory_stress

```
*Installation details*
Scylla version (or git commit hash): `4.4.0-0.20210324.dbb550e1a with build-id c41c64de4b206cac92615cfc0b3f21d915150562`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-043e18e3fb2db2c06` (aws: eu-north-1)

Test: `longevity-alternator-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0d21beeb95740f69f66ef07af45df7d24a22b9d0/test-cases/longevity/longevity-alternator-3h.yaml)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor ebf8c37f-5536-4bfa-9aa6-7150fac01c5a`
Show all stored logs command: `$ hydra investigate show-logs ebf8c37f-5536-4bfa-9aa6-7150fac01c5a`

Test id: `ebf8c37f-5536-4bfa-9aa6-7150fac01c5a`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-alternator-20210324_234720-alternator-3h-4-4-monitor-node-ebf8c37f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-alternator-20210324_234720-alternator-3h-4-4-monitor-node-ebf8c37f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210324_234443-alternator-3h-4-4-monitor-node-ebf8c37f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210324_234443-alternator-3h-4-4-monitor-node-ebf8c37f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-overview-20210324_234055-alternator-3h-4-4-monitor-node-ebf8c37f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_234054/grafana-screenshot-overview-20210324_234055-alternator-3h-4-4-monitor-node-ebf8c37f-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/db-cluster-ebf8c37f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/db-cluster-ebf8c37f.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/loader-set-ebf8c37f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/loader-set-ebf8c37f.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/monitor-set-ebf8c37f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/monitor-set-ebf8c37f.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/sct-runner-ebf8c37f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/ebf8c37f-5536-4bfa-9aa6-7150fac01c5a/20210324_235216/sct-runner-ebf8c37f.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-alternator-3h-test/30/)

**Comment by roydahan** [comment]
We should check with dev if we can completely ignore the error: "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE".

It can happen in any of the disruptive nemesis.
