### ISSUE TITLE
support to test with Ubuntu (20.04) based scylla AMI

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#3355]
##### Problem

Currently the default scylla_linux_distro is 'centos', when ubuntu based AMI is passed, scylla-manager will fail to install.
filed job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/326/
test id: fefd60cd-4567-4287-b3e2-6a8a2e2a6dd6

##### Workaround
cluster /node setup will identify the distro by itself, if `use_mgmt` is set to false, everything works well.
```
use_mgmt: false
```
example: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/302/

TODO: need to add `scylla_linux_distro` \ `scylla_mgmt_pkg` parameters in longevity pipeline, and pass correct value in trigger longevity jobs with different AMIs.

We don't have official scylla-manager repo for Ubuntu 20.04 in http://downloads.scylladb.com/deb/ubuntu/

![Screenshot from 2021-03-31 10-23-41](https://user-images.githubusercontent.com/309708/113081409-336cdc80-920b-11eb-8acb-71e62952a2ca.png)

TODO: Need to check if the unstable repo works well
http://downloads.scylladb.com.s3.amazonaws.com/manager/deb/unstable/focal/master/latest/scylla-manager-master/scylla-manager.list

#### Test logs:
08:10:52  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/fefd60cd-4567-4287-b3e2-6a8a2e2a6dd6/20210330_000807/db-cluster-fefd60cd.zip  |
08:10:52  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/fefd60cd-4567-4287-b3e2-6a8a2e2a6dd6/20210330_000807/monitor-set-fefd60cd.zip |
08:10:52  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/fefd60cd-4567-4287-b3e2-6a8a2e2a6dd6/20210330_000807/loader-set-fefd60cd.zip  |
08:10:52  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/fefd60cd-4567-4287-b3e2-6a8a2e2a6dd6/20210330_000807/sct-runner-fefd60cd.zip  |

**Comment by fgelcer** [comment]
Scylla AMI base version already moved to Ubuntu 22.04
