### ISSUE TITLE
branch-2021.1: sdcm/tester.py NameError: name 'boto3' is not defined

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#3400]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:  branch-2021.1 (f54d17548c074e6fe555c6e6f7a3d7b4709f9d79)
* **scylla**:2021.1.rc1

### Logs
* test_id: 0b3534fe-b6d3-4166-9948-7a19ba7b093b
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/0b3534fe-b6d3-4166-9948-7a19ba7b093b/20210413_023258/sct-runner-0b3534fe.zip 

### Description

Job #2 failed for test issue:

```
> File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 463, in setUp
> self.init_resources()
> File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1092, in init_resources
> self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
> File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 760, in get_cluster_aws
> session = boto3.session.Session(region_name=region)

NameError: name 'boto3' is not defined
```

**Comment by amoskong** [comment]
The problem was introduced in https://github.com/scylladb/scylla-cluster-tests/commit/db70d87ada34544005f3a5a502c5af0597bed4ae

**Comment by fgelcer** [comment]
problem fixed in my job, hence closing this issue.
