### ISSUE TITLE
Test repair-based node operations?

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#3470]
I noticed that there are no test config files (.yaml) in SCT repo - master branch at least - that would enable repair-based node operations. I think this feature is quite important to be tested by SCT. Shouldn't we have at least one longevity running regularly with this option enabled? AFAIK we do plan to eventually turn it on by default, so it would be good to start testing it with "real" clusters.

Perhaps there is a Jenkins job (which I can't find because Jenkins' search gives an error :+1: ) that is testing this by enabling it somehow through a parameter. In this case we can probably close the issue.

**Comment by roydahan** [comment]
We don't test thins out of a context of a release.
If/when there will be a release that enables this by default it will get tested.
