### ISSUE TITLE
GCE image: Use scylla-images projoect instead of  skilled-adapter-452

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#3568]
Since all gce images are being created on scylla-images project. 
Let's use only one project for gce-images to avoid unneeded copy and permissions issues

**Comment by yaronkaikov** [comment]
@bentsi @roydahan , any idea when can we get it done?

**Comment by roydahan** [comment]
Not sure it'll be done and if so, not soon.

**Comment by yaronkaikov** [comment]
@roydahan @fruch I think you guys just created a new project, right? are we still going to use the old one?

**Comment by fruch** [comment]
we are going to use both for now, I fail to see how it's related to this issue (also I fail to understand what it this issue)

**Comment by fruch** [comment]
images from `scylla-images` are supposed to be public.
the only issue we have is that we can't list them, so we need permissions for that.

it's one service account per project that need this access (for SCT)

**Comment by roydahan** [comment]
Now I don't remember what is this issue about.
Did you want us to move working with the scylla-images project?

If so, this issue isn't relevant and we should keep scylla-images project separated from the rest of the projects we use or may use in the future (can/will be more than one).
