### ISSUE TITLE
Add ability to login to grafana 3.8 to get live snapshot for grafana dashboard

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#3612]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:master
* **scylla**: latest
* **scylla-monitoring**: monitoring 3.8, grafana 3.8

### Description

Need to add to sct GrafanaSnapshot ability to login to grafana 3.8. after authorization it will be possible to create grafana livesnapshots.

**Comment by slivne** [comment]
user admin
password admin

**Comment by slivne** [comment]
(default user - we do not need to complicate the system for tests)
