### ISSUE TITLE
gemini-1tb-10h-test fails by timeout

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3739]
Average time for gemini-1tb-10h-test to complete is 12h30m, while timeout set to 13h
It is result of having `--duration 36000s --warmup 7200s` in `test-cases/gemini/gemini-1tb-10h.yaml`

So we need to reduce warmup either duration or warmup 

test_id: 0c5f2867-f392-4e06-be98-c32ff3025855

**Comment by roydahan** [comment]
Let's reduce duration by one hour.

**Comment by dkropachev** [comment]
> Let's reduce duration by one hour.

I think it worth to mention that since it is claiming to be 10h run, we need to make duration + warmup = 36000
