### ISSUE TITLE
test_cassandra_rackdc started to bring cluster to the state when one node does not see others 

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3786]
### Steps to Reproduce

1. sct.py run-pytest functional_tests/scylla_operator --backend k8s-local-kind --config test-cases/scylla-operator/functional.yaml --logdir="`pwd`"

**Expected behavior:** [What you expected to happen]
Test is passed

**Actual behavior:** [What actually happened]
It is stuck in the middle

**Comment by vponomaryov** [comment]
It is bug in the operator. Setting of "prefer_local=true" option breaks Scylla clusters: https://github.com/scylladb/scylla-operator/issues/797

**Comment by vponomaryov** [comment]
So, I am closing this issue, because it will be addressed in the operator itself at https://github.com/scylladb/scylla-operator/issues/797
