### ISSUE TITLE
Stress Threads doesn't stop when a critical event is triggered

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#3851]
While testing scylla-4.5  I noticed that even when we have a critical event and the test main thread is stopping, the test still wait for the stress threads to finish and doesn't stop all threads immediately  as expected.

To reproduce: Run longevity-50gb-3d on 4.5.rc5  (triggers critical event from one stress thread quite fast).

An example job where it happens: 
https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/Reproducers/job/longevity-50gb-3days-missed-keys/28/
(running from a private reproducer branch that should be based on 4.5).

But  also official one can be looked at: https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/longevity/job/longevity-50gb-3days-test/

**Comment by bentsi** [comment]
the issue is in the full scan thread since we never stop it at the end of the test. Dmitriy, I'll open a task to fix this.

**Comment by dkropachev** [comment]
Thanks @bentsi for analisys, i will fix it.
