### ISSUE TITLE
EKS Logging feature is getting charged

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3859]
We turn cluster loggin on by default at https://github.com/scylladb/scylla-cluster-tests/blob/0b2812c1feb425b5186ec46032fa7398093d427d/sdcm/cluster_k8s/eks.py#L260-L273

According to the AWS [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html) we are getting charged for it:

```
logging (dict) --
Enable or disable exporting the Kubernetes control plane logs for your cluster to CloudWatch Logs. By default, cluster control plane logs aren't exported to CloudWatch Logs. For more information, see Amazon EKS Cluster control plane logs in the * Amazon EKS User Guide * .

Note

CloudWatch Logs ingestion, archive storage, and data scanning rates apply to exported control plane logs. For more information, see CloudWatch Pricing .
```

Probably it worth of turning it off by default and turn it on only for tests we need.
Also since we turn them on, we could collect them from the EKS into sct folder

**Comment by fruch** [comment]
@vponomaryov looks like it's still the case, as far as I know we are not using those logs regularly, we should enable them only when we enable the logging we even have SCT configuration for it

**Comment by vponomaryov** [comment]
> @vponomaryov looks like it's still the case, as far as I know we are not using those logs regularly, we should enable them only when we enable the logging we even have SCT configuration for it

Right, it is still the case.
