### ISSUE TITLE
mgmtBackup task didn't reach "final" state - longevity-200gb

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#3902]
Test-id: 9c20da8f-f455-4c3a-b333-3ef70ee52c66
Start time: 2021-08-20 03:00:22
End time: 2021-08-22 09:12:31

e-9c20da8f-2 [13.49.78.26 | 10.0.2.234] (seed: False) errors=RetryError[Wait for: Waiting until task: backup/d9b7babf-d8ed-4add-afef-28254065a5a5 reaches status of: ['ERROR (4/4)', 'DONE']: timeout - 54000 seconds - expired]
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for
    res = retry.call(func, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 168, in reraise
    raise self
tenacity.RetryError: RetryError[<Future at 0x7f9a48048310 state=finished returned bool>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2905, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1784, in disrupt_mgmt_backup_specific_keyspaces
    self._mgmt_backup(backup_specific_tables=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1816, in _mgmt_backup
    status = mgr_task.wait_and_get_final_status(timeout=54000, step=5, only_final=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 303, in wait_and_get_final_status
    res = self.wait_for_status(list_status=list_final_status, timeout=timeout, step=step)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 267, in wait_for_status
    is_status_reached = wait.wait_for(func=self.is_status_in_list, step=step, throw_exc=True,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 72, in wait_for
    raise RetryError(err) from ex
tenacity.RetryError: RetryError[Wait for: Waiting until task: backup/d9b7babf-d8ed-4add-afef-28254065a5a5 reaches status of: ['ERROR (4/4)', 'DONE']: timeout - 54000 seconds - expired]

In this case, we should print to the log the actual state of the task.
Ans possibly all the tasks statuses because it may point on a real issue.

**Comment by yarongilor** [comment]
@ShlomiBalalis , can you please advice - 
i see this error now in master 200gb longevity:
```


MgmtBackup | 1 | nodestartendduration | node | start | end | duration | nodestartenddurationerrorNode longevity-200gb-48h-verify-limited--db-node-22e086a5-4 [13.49.65.248 \| 10.0.0.221] (seed: False)2021-11-09 11:44:342021-11-10 02:45:0054025RetryError[Wait for: Waiting until task: backup/ca00591c-3359-4dc2-bfb1-ff4b2ef1de03 reaches status of: ['ERROR (4/4)', 'DONE']: timeout - 54000 seconds - expired] | node | start | end | duration | error | Node longevity-200gb-48h-verify-limited--db-node-22e086a5-4 [13.49.65.248 \| 10.0.0.221] (seed: False) | 2021-11-09 11:44:34 | 2021-11-10 02:45:00 | 54025 | RetryError[Wait for: Waiting until task: backup/ca00591c-3359-4dc2-bfb1-ff4b2ef1de03 reaches status of: ['ERROR (4/4)', 'DONE']: timeout - 54000 seconds - expired]
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


Node longevity-200gb-48h-verify-limited--db-node-22e086a5-4 [13.49.65.248 \| 10.0.0.221] (seed: False) | 2021-11-09 11:44:34 | 2021-11-10 02:45:00 | 54025 | RetryError[Wait for: Waiting until task: backup/ca00591c-3359-4dc2-bfb1-ff4b2ef1de03 reaches status of: ['ERROR (4/4)', 'DONE']: timeout - 54000 seconds - expired]


```
is it a different issue?



*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.dev-0.20211107.4950ce539 with build-id 8d7a7f85964575a8775f8358cef3ff74141e07fd`
Cluster size: 4 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-200gb-48h-verify-limited--db-node-22e086a5-1 (13.53.161.246 | 10.0.3.162): 14 shards
   longevity-200gb-48h-verify-limited--db-node-22e086a5-3 (13.53.123.18 | 10.0.0.75): 14 shards
   longevity-200gb-48h-verify-limited--db-node-22e086a5-4 (13.49.65.248 | 10.0.0.221): 14 shards
   longevity-200gb-48h-verify-limited--db-node-22e086a5-5 (16.170.159.255 | 10.0.0.232): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-200gb-48h-verify-limited--db-node-22e086a5-2 (13.53.122.101 | 10.0.1.223): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0ac0c6c9087bf4b09` (aws: eu-north-1)


Test: `longevity-200gb-48h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d1ae0d0636d6781d168fc6fc1a6932f0638c3827/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor 22e086a5-c3b0-495f-b061-0626f4356154`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=22e086a5-c3b0-495f-b061-0626f4356154)
Show all stored logs command: `$ hydra investigate show-logs 22e086a5-c3b0-495f-b061-0626f4356154`

Test id: `22e086a5-c3b0-495f-b061-0626f4356154`


Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/db-cluster-22e086a5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/db-cluster-22e086a5.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/loader-set-22e086a5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/loader-set-22e086a5.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/monitor-set-22e086a5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/monitor-set-22e086a5.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/sct-runner-22e086a5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/22e086a5-c3b0-495f-b061-0626f4356154/20211110_220939/sct-runner-22e086a5.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/148/)
