### ISSUE TITLE
soft_reboot_node nemesis fails with critical error: POWER_OFF

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3942]
soft_reboot_node nemesis fails with critical error: POWER_OFF.
so there may be several different problems here:
1. scylla issue (not high chances for that)
2. Wrong semantics of event - "power-off" instead of something like "reboot".
3. Missing filtering to nemesis for the reboot related operations.

error log:
```
< t:2021-09-09 11:38:55,273 f:nemesis.py      l:1079 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ScyllaCloudLimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method soft_reboot_node
< t:2021-09-09 11:39:40,535 f:nemesis.py      l:674  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ScyllaCloudLimitedChaosMonkey: Set current_disruption -> SoftRebootNode Node longevity-small-set-1h-select-n-db-node-20329e32-1 [34.73.221.238 | 172.31.0.6] (seed: True)
< t:2021-09-09 11:41:33,501 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-08-18 21:10:04.000: (DatabaseLogEvent Severity.CRITICAL) period_type=one-time event_id=343ddf1b-0616-475d-bef3-2e7a34a606df: type=POWER_OFF regex=Powering Off line_number=18705 node=Node longevity-small-set-1h-select-n-db-node-20329e32-1 [34.73.221.238 | 172.31.0.6] (seed: True)
< t:2021-09-09 11:44:00,342 f:nemesis.py      l:1089 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ScyllaCloudLimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method soft_reboot_node

```

*Installation details*
Kernel version: `5.8.0-1038-gcp`
Scylla version (or git commit hash): `2021.1.5-0.20210818.fc817c0cd with build-id e1833668b46dfa6bd43faf42dac2dee5bdef0659`
Cluster size: 6 nodes (n1-highmem-8)
Scylla running with shards number (live nodes):
   longevity-small-set-1h-select-n-db-node-20329e32-1 (34.73.221.238 | 172.31.0.6): 4 shards
   longevity-small-set-1h-select-n-db-node-20329e32-2 (35.231.71.227 | 172.31.0.3): 4 shards
   longevity-small-set-1h-select-n-db-node-20329e32-3 (35.231.83.165 | 172.31.0.7): 4 shards
   longevity-small-set-1h-select-n-db-node-20329e32-4 (35.196.124.79 | 172.31.0.8): 4 shards
   longevity-small-set-1h-select-n-db-node-20329e32-5 (34.139.253.245 | 172.31.0.5): 4 shards
   longevity-small-set-1h-select-n-db-node-20329e32-6 (35.237.23.197 | 172.31.0.4): 4 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce-siren: us-east1)

Test: `cloud-longevity-small-data-set-1h-gcp_dbg`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- scylla_cloud_nemesis_small_set.yaml (Siren repo)
- scylla_cloud.yaml (Siren repo)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 20329e32-ca67-4cb6-bd7f-901c09874b51`
Show all stored logs command: `$ hydra investigate show-logs 20329e32-ca67-4cb6-bd7f-901c09874b51`

Test id: `20329e32-ca67-4cb6-bd7f-901c09874b51`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114442/grafana-screenshot-cloud-longevity-small-data-set-1h-gcp_dbg-scylla-per-server-metrics-nemesis-20210909_114612-longevity-small-set-1h-select-n-monitor-node-20329e32-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114442/grafana-screenshot-cloud-longevity-small-data-set-1h-gcp_dbg-scylla-per-server-metrics-nemesis-20210909_114612-longevity-small-set-1h-select-n-monitor-node-20329e32-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114442/grafana-screenshot-overview-20210909_114442-longevity-small-set-1h-select-n-monitor-node-20329e32-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114442/grafana-screenshot-overview-20210909_114442-longevity-small-set-1h-select-n-monitor-node-20329e32-0-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/db-cluster-20329e32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/db-cluster-20329e32.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/loader-set-20329e32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/loader-set-20329e32.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/monitor-set-20329e32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/monitor-set-20329e32.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/sct-runner-20329e32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/20329e32-ca67-4cb6-bd7f-901c09874b51/20210909_114818/sct-runner-20329e32.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-small-data-set-1h-gcp_dbg/30/)

**Comment by roydahan** [comment]
@yarongilor what is the issue here?
You are copy pasting things without editing the issue description and without explaining what's broken.

@amoskong I think you added this type of critical event as part of "937b201765a737e8cba05b880d2863a54210ebc0".

**Comment by roydahan** [comment]
@KnifeyMoloko if this happens in another run, please add the information here.

**Comment by yarongilor** [comment]
Amos is fixing it.

**Comment by yarongilor** [comment]
I didn't see any fix by @amoskong . this still fails siren longevities. @roydahan is there any fix for this?

**Comment by amoskong** [comment]
> I didn't see any fix by @amoskong . this still fails siren longevities. @roydahan is there any fix for this?

There is another fix:

https://github.com/scylladb/scylla-cluster-tests/pull/3972

**Comment by dkropachev** [comment]
Fixed at https://github.com/scylladb/scylla-cluster-tests/pull/3972
