### ISSUE TITLE
artifact failed on `SCT collect logs data()`

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#3988]
Seen for multiple SCT artifacts tests:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/323/
and also in  https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/287/

from ubuntu:20.04 logs i see the following error
```
11:59:01  < t:2021-09-30 08:58:51,290 f:wait.py         l:65   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
11:59:01  < t:2021-09-30 08:58:51,290 f:wait.py         l:69   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7ff611ebd9d0 state=finished returned bool>)
```

and 
```12:07:51  < t:2021-09-30 09:07:51,703 f:threads_and_processes_alive.py l:53   c:sdcm.utils.threads_and_processes_alive p:ERROR > There are some threads left alive from following modules: multiprocessing.queues,sdcm.remote.remote_cmd_runner,paramiko.transport
12:07:51  < t:2021-09-30 09:07:51,703 f:tester.py       l:2321 c:ArtifactsTest        p:ERROR > Please check /jenkins/slave/workspace/scylla-master/artifacts/artifacts-ubuntu2004-test/scylla-cluster-tests/20210930-085314-419721/left_processes.log log to see them
```

**Comment by yaronkaikov** [comment]
@scylladb/qa-team

**Comment by fgelcer** [comment]
@yaronkaikov , the 1st error is fine, we added a retry in the call to `apt-get install`, because `apt-get` is a singelton command, and system calls can get it busy, and it was failing...
what is the issue you see?

**Comment by yaronkaikov** [comment]
The artifact failed on `collect logs data` stage and therefor fail the job so unified-deb is also failing

**Comment by fgelcer** [comment]
this is the failure in the collect_logs:
```
12:08:00  Host 34.74.130.23 not found in /jenkins/.ssh/known_hosts
12:10:10  ssh: connect to host 34.74.130.23 port 22: Connection timed out
12:10:10  rsync: connection unexpectedly closed (0 bytes received so far) [sender]
12:10:10  rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
12:10:10  Cleaning SSH agent
12:10:10  Agent pid 7161 killed
```

**Comment by fgelcer** [comment]
@enaydanov , it seems related to the runner @amoskong added to these jobs (and removed afterwards)

**Comment by fgelcer** [comment]
looking into [this job](https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/287/) i see:

```
13:14:28  Traceback (most recent call last):
13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/./sct.py", line 1198, in <module>
13:14:28      cli()
13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
13:14:28      return self.main(*args, **kwargs)
13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
13:14:28      rv = self.invoke(ctx)
13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
13:14:28      return _process_result(sub_ctx.command.invoke(sub_ctx))
13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
13:14:28      return ctx.invoke(self.callback, **ctx.params)
13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
13:14:28      return callback(*args, **kwargs)
13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/./sct.py", line 920, in collect_logs
13:14:28      config = SCTConfiguration()
13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/sct_config.py", line 1368, in __init__
13:14:28      for key, value in regions_data[region].items():
13:14:28  KeyError: 'null'
```

before that, i see that:
```
export SCT_REGION_NAME=null
```

was this caused by any change in the regions (GCE vs AWS)?
shouldn't we send this `SCT_REGION_NAME` for the GCE region?
@enaydanov @dkropachev @bentsi ?

**Comment by yaronkaikov** [comment]
@enaydanov @dkropachev @bentsi @fgelcer maybe related to https://github.com/scylladb/scylla-cluster-tests/pull/3791/commits/697eef65f5e47c6e4e67ee7a9933dc1f4f561748 ?

**Comment by fgelcer** [comment]
> @enaydanov @dkropachev @bentsi @fgelcer maybe related to [697eef6](https://github.com/scylladb/scylla-cluster-tests/commit/697eef65f5e47c6e4e67ee7a9933dc1f4f561748) ?

nope, looks related to https://github.com/scylladb/scylla-cluster-tests/commit/5cad86d

**Comment by fgelcer** [comment]
@yaronkaikov , this is my fix suggestion in here:
https://github.com/scylladb/scylla-cluster-tests/pull/3994

**Comment by amoskong** [comment]
> @enaydanov , it seems related to the runner @amoskong added to these jobs (and removed afterwards)

In https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/323/console

No new sct runner is created (it's expected.), but there was a sct_runner_ip exists in running runCollectLogs(), runCleanupResource(), runSendEmail().

I just sent a PR to clean the old sct_runner_ip file.

- https://github.com/scylladb/scylla-cluster-tests/pull/3993

**Comment by fgelcer** [comment]
> > @enaydanov , it seems related to the runner @amoskong added to these jobs (and removed afterwards)
> 
> In https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/323/console
> 
> No new sct runner is created (it's expected.), but there was a sct_runner_ip exists in running runCollectLogs(), runCleanupResource(), runSendEmail().
> 
> I just sent a PR to clean the old sct_runner_ip file.
> 
> * [fix(artifactsPipeline): clean the old sct_runner_ip #3993](https://github.com/scylladb/scylla-cluster-tests/pull/3993)

thank you @amoskong ... i'm not sure the PR you sent is the full solution, but it doesn't bother to remove old `sct_runner_ip` files in the beginning of a test call

**Comment by amoskong** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-ubuntu2004-test/321/

This is a PASSed job, the commit (58fb3f6abbbd8379be18d949fbaba19fb653b986) is after my fix (4526c7a95074a83f0d92c43ad2769f6a821a3f34  fix(artifacts pipeline): disable sct runner).

It's strange that the sct_runner_ip file exists, however the only fix solution is cleaning the old sct_runner_ip before executing the tests.

**Comment by fgelcer** [comment]
@amoskong @bentsi , seems like not all artifact tests were fixed...
see [this one](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/41/), it seems to be failing with same symptoms (hence i think it has the same issue)

**Comment by yaronkaikov** [comment]
@amoskong @bentsi So after ubuntu 20.04 artifact passed once, now it's failing again
```
21:59:53  Unable to get events main device
21:59:53  Traceback (most recent call last):
21:59:53    File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-ubuntu2004-test@2/scylla-cluster-tests/sdcm/sct_events/base.py", line 200, in publish_or_dump
21:59:53      proc = get_events_main_device(_registry=self._events_processes_registry)
21:59:53    File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-ubuntu2004-test@2/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 182, in get_events_process
21:59:53      return get_default_events_process_registry(_registry=_registry).get_events_process(name=name)
21:59:53    File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-ubuntu2004-test@2/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 173, in get_default_events_process_registry
21:59:53      raise RuntimeError("You should create default EventsProcessRegistry first")
21:59:53  RuntimeError: You should create default EventsProcessRegistry first
```
Don't know if it's related to this fix or something else

**Comment by amoskong** [comment]
> looking into [this job](https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/287/) i see:
> 
> ```
> 13:14:28  Traceback (most recent call last):
> 13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/./sct.py", line 1198, in <module>
> 13:14:28      cli()
> 13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
> 13:14:28      return self.main(*args, **kwargs)
> 13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
> 13:14:28      rv = self.invoke(ctx)
> 13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
> 13:14:28      return _process_result(sub_ctx.command.invoke(sub_ctx))
> 13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
> 13:14:28      return ctx.invoke(self.callback, **ctx.params)
> 13:14:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
> 13:14:28      return callback(*args, **kwargs)
> 13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/./sct.py", line 920, in collect_logs
> 13:14:28      config = SCTConfiguration()
> 13:14:28    File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/sct_config.py", line 1368, in __init__
> 13:14:28      for key, value in regions_data[region].items():
> 13:14:28  KeyError: 'null'
> ```
> 
> before that, i see that:
> 
> ```
> export SCT_REGION_NAME=null
> ```
> 
> was this caused by any change in the regions (GCE vs AWS)? shouldn't we send this `SCT_REGION_NAME` for the GCE region? @enaydanov @dkropachev @bentsi ?


I just sent a fix : https://github.com/scylladb/scylla-cluster-tests/pull/3997

```
Our SCT parameter of aws region is region_name (SCT_REGION_NAME), but we
used aws_region in yaml config and some vars functions.

Artifacts Pipeline and yaml configs use matched region_name, but it
called the shared functions (eg: runCollectLogs).

The grace change should change all the parameter in yaml config and
vars functions to region_name, but it's too big change.

This patch only changed the parameter name in artifacts pipeline to
match with runCollectLogs().
```

**Comment by amoskong** [comment]
After applied sct fix (https://github.com/scylladb/scylla-cluster-tests/pull/3997), the KeyError in runCollectLogs() disappeared.
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/289/
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/42/

It seems the jobs failed for ami issue, timeout to connect the instance.

I rerun the last Passed job, and the new jobs passed, the AMI should be good.
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/290/
- https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/43/
