### ISSUE TITLE
GCE loader setup fails with: CreateGCENodeError: Failed to create node

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3989]
job log: https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-small-data-set-1h-gcp_dbg/51/
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 123, in wrapper
    return method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 111, in inner
    res = func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 530, in setUp
    self.init_resources()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1342, in init_resources
    self.get_cluster_gce(loader_info=loader_info, db_info=db_info,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 734, in get_cluster_gce
    self.loaders = LoaderSetGCE(gce_image=self.params.get('gce_image_loader'),
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 519, in __init__
    GCECluster.__init__(self,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 227, in __init__
    super().__init__(cluster_uuid=cluster_uuid,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3174, in __init__
    self.add_nodes(n_nodes, enable_auto_bootstrap=self.auto_bootstrap)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 461, in add_nodes
    node = self._create_node(instance, node_index, dc_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 442, in _create_node
    raise CreateGCENodeError('Failed to create node: %s' % ex) from ex
sdcm.cluster_gce.CreateGCENodeError: Failed to create node: Critical Error has failed the test

```

19:44:13  +----------------------------------------------------------------------------------------------------------------------------------------------+
19:44:13  |                                       Collected logs by test-id: 8203ad8a-e103-425b-a321-c6b3ae8973a5                                        |
19:44:13  +-------------+--------------------------------------------------------------------------------------------------------------------------------+
19:44:13  | Cluster set | Link                                                                                                                           |
19:44:13  +-------------+--------------------------------------------------------------------------------------------------------------------------------+
19:44:13  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/8203ad8a-e103-425b-a321-c6b3ae8973a5/20210929_164345/db-cluster-8203ad8a.tar.gz |
19:44:13  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/8203ad8a-e103-425b-a321-c6b3ae8973a5/20210929_164345/loader-set-8203ad8a.tar.gz |
19:44:13  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/8203ad8a-e103-425b-a321-c6b3ae8973a5/20210929_164345/sct-runner-8203ad8a.tar.gz |
19:44:13  +-------------+--------------------------------------------------------------------------------------------------------------------------------+

**Comment by vponomaryov** [comment]
The problem is not in the loaders.
The job failed due to the appearance of the following critical event:

```
2021-09-29 16:42:50.079 <2021-08-18 21:10:04.000>: (DatabaseLogEvent Severity.CRITICAL) \
    period_type=one-time \
    event_id=364f50a0-e3fa-411a-8c1b-76845c050363: \
    type=POWER_OFF \
    regex=Powering Off \
    line_number=1972 \
    node=Node \
    longevity-small-set-1h-cluster--db-node-8203ad8a-1 [104.196.207.173 | 172.31.0.8] (seed: False)
```

Node logs have following:

```
 !INFO    | systemd-logind[3220]: Power key pressed.
 !INFO    | systemd-logind[3220]: Powering Off...
```
Then, I suppose that recent switch from the "aws-siren" and "gce-siren" backend names to "aws" and "gce" caused this failure.
The cause is hard dependency on the "*-siren" name and when it is not like this then node tags are not set which leads to unexpected behavior like here.

**Comment by yarongilor** [comment]
Probably during loader setup, the issue of https://github.com/scylladb/scylla-cluster-tests/issues/3942 was reproduced. so this might only be a duplicate of it.
