### ISSUE TITLE
4.3: ami artifact test is failing due to timeout

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#3991]
Seen in https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/artifacts/job/artifacts-ami-test/910/console

It's failing for a while now, preventing next-machine-image to pass  .

Need to be fix so we can start the a new release

**Comment by bentsi** [comment]
It has a dracut issue
![image](https://user-images.githubusercontent.com/5269241/135890135-cc8972ac-59bf-4cee-b54b-578d04e1a378.png)

**Comment by yaronkaikov** [comment]
Job passed while running from next. it looks like a bug in `next-machine-image` which is using the wrong branch . we have a workaround for that

**Comment by bentsi** [comment]
the issue was in the Releng side, scylla-machine-image next job didn't use next-4.3 branch, so the fix `2205301 - aws: add xen-blkfront driver to kernel-ml initramfs (4 weeks ago) <Takuya ASADA>` was not applied. Yaron fixed and AMI job passes now.
