### ISSUE TITLE
no timeout on wait_for_init() during decommission nemesis

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#402]
no timeout on wait_for_init() during decommission nemesis. SCT waits forever for the node to join.

**Comment by amoskong** [comment]
The problem exists in the while loop, the timeout for wait_for_init() will work on node_setup, the timeout is necessary.

```
        while len(results) != len(node_list):
            try:
                results.append(queue.get(block=True, timeout=5))
                time_elapsed = time.time() - start_time
                self.log.info("(%d/%d) DB nodes ready. Time elapsed: %d s",
                              len(results), len(node_list),
                              int(time_elapsed))
            except Queue.Empty:
                pass
```

@larisau 
Do you have a suggested timeout?  half hour? or one hours for all nodes in parallel.

**Comment by amoskong** [comment]
The timeout had been added by 39fc8c85029a161b9d2ec8df5069cb3c481adf48
