### ISSUE TITLE
Images: query for last tested image

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#4023]
We have some historic - not making sense flow on AMI (comes from the days we used Jenkins free style jobs):
- We create the AMI with some tags (such as ScyllaVersion).
- We test the AMI (artifact test).
- If passed, we add some tags, such as branch (should be releaseName), operating-system and build-id.
- Now comes Hydra, and queries to find the latest tested (by artifact test) AMI.

This process does not make sense:
- We have questions such as: Last few AMIs don't have branch tag (happens when recent AMIs didn't pass the artifact test).
- We have mistakes when we need to add / change code, as tags are done on AMI directly, and on pkg after test.

Imporve the flow, so:
- All images will create the same tags / labels when images are created (align names to camel case, as most of the other tags / labels)
- Releng should add "tested" tag when image passes artifact test (just before copy it to more regions if needed).
- Hydra should be updated to query for tested AMIs, with the aligned tag names.
- Releng should clean the process, so tags will be created with the AMI, and "tested" tag will be added after test.

To do with pgs issue: https://github.com/scylladb/scylla-pkg/issues/2440

At the end of process we will have:
branch => releaseName
operating-system => operatingSystem
build-id => buildID
New (when passes artifact test): tested (or artifactTested)

**Comment by fruch** [comment]
for reference 25192eb55528a5cfcd7a86ed1facc5a7bd5561b4 implemented a `tag_ami_with_result` which make SCT test tag their outcome on the AMI used.

similar approach to what suggested here, but we never used it regularly.

**Comment by yaronkaikov** [comment]
Not planned at the moment (i think it's the first time i see it)..

**Comment by yaronkaikov** [comment]
you can close it for now, we have an open issue in pkg. if we decide to do it i will reopen this. need to understand what is the meaning of this :-)
