### ISSUE TITLE
Please publish metadata for decoding backtraces in SCT reports

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cluster-tests#4054]
The performance regression report (and maybe other reports as well)
may contain backtraces from the run.

To decode them we need:

1 The build_id of scylla that was tested
2. Exact kernel version: `$(uname -r)`
3. Kernel symbols: `cat /proc/kallsyms | gzip > /tmp/kallsyms.gz`

/cc @avikivity

**Comment by fgelcer** [comment]
> Note: running gzip directly from /proc/kallsyms prints an error, hence the weird usage of `cat` above...
> 
> ```
> $ gzip < /proc/kallsyms > /tmp/kallsyms.gz
> gzip: stdin: file size changed while zipping
> ```

and we need to read `/proc/kallsyms` as root, otherwise the memory addresses will be empty

**Comment by fruch** [comment]
@fgelcer this was done ?

**Comment by fgelcer** [comment]
> @fgelcer this was done ?

it was done, but for the reason of nodes being terminated during some of the tests, we need to move this code to the "setup" phase, and not tear down (as some nodes were already terminated during tear down, and the kernel backtraces will be in the logs, and no way to decode them)..
should we create a new issue for it, and close this one, or this one can hold it for this needed task?

**Comment by fruch** [comment]
@fgelcer 
In all SCT runs we are using identical db machines (and kernel, maybe in the upgrade test it can be changed)
getting kernel symbol from one node, should be identical to the others, so it's good enough to take one. (yeah I know collection is identical for each node), but if one node was up at the end of the test, you'll get the symbols.

**Comment by fgelcer** [comment]
> @fgelcer In all SCT runs we are using identical db machines (and kernel, maybe in the upgrade test it can be changed) getting kernel symbol from one node, should be identical to the others, so it's good enough to take one. (yeah I know collection is identical for each node), but if one node was up at the end of the test, you'll get the symbols.

@fruch , wrong, we proved that, even on the very same node, every time the map is re-shuffled, so if the node restarts, the map will be different...

**Comment by fruch** [comment]
> > @fgelcer In all SCT runs we are using identical db machines (and kernel, maybe in the upgrade test it can be changed) getting kernel symbol from one node, should be identical to the others, so it's good enough to take one. (yeah I know collection is identical for each node), but if one node was up at the end of the test, you'll get the symbols.
> 
> @fruch , wrong, we proved that, even on the very same node, every time the map is re-shuffled, so if the node restarts, the map will be different...

so moving it to the setup won't help you either when nemesis is running, it can also reboot the machine...
it need to be collect when identified, we have an sct event for that ?

**Comment by fgelcer** [comment]
> > > @fgelcer In all SCT runs we are using identical db machines (and kernel, maybe in the upgrade test it can be changed) getting kernel symbol from one node, should be identical to the others, so it's good enough to take one. (yeah I know collection is identical for each node), but if one node was up at the end of the test, you'll get the symbols.
> > 
> > 
> > @fruch , wrong, we proved that, even on the very same node, every time the map is re-shuffled, so if the node restarts, the map will be different...
> 
> so moving it to the setup won't help you either when nemesis is running, it can also reboot the machine... it need to be collect when identified, we have an sct event for that ?

or either another solution is to collect this file (with same time and date) version for each boot of it... i will open a task in trello to follow it, and then we will close this issue

**Comment by fgelcer** [comment]
https://trello.com/c/lokjpJC7/4716-kallsyms-collection-it-should-happen-for-each-time-the-node-boot-and-save-it-with-multiple-different-versions-most-likely-based
