### ISSUE TITLE
Artifact test for AMI on Arm fails to run

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#4092]
I tried to run artifact test on Arm:
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ami-test/34/console
Instance type: c6gd.xlarge
AMI-ID: ami-03565db086c6fbaf2

It tries to install Scylla manager (which does not have an Arm build) and gets into an endless loop.

Is there a way to skip the manager? so I can run a test to see if there are more issues?

**Comment by dkropachev** [comment]
fixed
