### ISSUE TITLE
send email pipeline fails: "Results file not found"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4100]
see in job:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h/40/execution/node/217/log/

**Comment by yarongilor** [comment]
@aleksbykov , can you please advise - is there a chance this is a known issue?
otherwise i'll start checking what went wrong.

**Comment by yarongilor** [comment]
@fgelcer , can this issue be related to change of https://github.com/scylladb/scylla-cluster-tests/pull/3987  ?

**Comment by yarongilor** [comment]
can it be related to a previous failure collecting sct log?
like in https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/147/execution/node/167/log/:  
" 11:07:22  There are no logs collected for sct-runner "

**Comment by fgelcer** [comment]
@yarongilor , since #4104 was merged, check if this issue doesn't reproduce again, and close it please

**Comment by yarongilor** [comment]
> @yarongilor , since #4104 was merged, check if this issue doesn't reproduce again, and close it please

waiting for 200gb 2d job to finish in order to verify.

**Comment by dkropachev** [comment]
Fixed - https://github.com/scylladb/scylla-cluster-tests/pull/4115

**Comment by dkropachev** [comment]
Closed at https://github.com/scylladb/scylla-cluster-tests/pull/4104
