### ISSUE TITLE
Enable ARM artifact tests for 2021.1

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#4127]
Need to merge/backport ARM artifact tests for 2021.1
I created the jobs on 
https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/artifacts/job/artifacts-ubuntu2004-arm-test/
and
https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/artifacts/job/artifacts-centos8-arm-test/

**Comment by yaronkaikov** [comment]
@bentsi @roydahan Who can do this ?

**Comment by roydahan** [comment]
I can do it.
I'll try doing it in the next couple of days.

**Comment by roydahan** [comment]
Done.
