### ISSUE TITLE
artifacts docker test failed with argus_test_run.py, line 223, in from_sct_config region=regions[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4129]
error log:
```
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR > ERROR SETTING UP ARGUS CONNECTION < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR > ERROR SETTING UP ARGUS CONNECTION
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR > Traceback (most recent call last):
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 368, in argus_test_run
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR >     argus_test_run = ArgusTestRun.from_sct_config(test_id=UUID(self.test_id),
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/argus_test_run.py", line 223, in from_sct_config
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR >     region=regions[0], private_ip=get_my_ip())
21:07:50  < t:2021-11-14 19:07:49,405 f:tester.py       l:374  c:ArtifactsTest        p:ERROR > IndexError: list index out of range
```

see full log in:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/356/execution/node/52/log/?consoleFull

Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 356
Backend: docker
Kernel version: N/A
Test-id: c8ae408f-f891-468b-afad-11b9398a72d8
Start time: 2021-11-14 19:07:49
End time: 2021-11-14 19:11:00
Started by user: hagit.segev
Test result
FAILED
System under test
ScyllaDB version: N/A
Actual docker image used: Node has not been initialized
Instance type: N/A
Scylla packages installed:
No scylla packages are installed. Please check log files.
Last events by severity
CRITICAL - [0]
No events with this severity
ERROR - [1]
2021-11-14 19:10:58.968: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=39a326a5-f583-4b9d-bcee-18d10746a869, source=ArtifactsTest.SetUp()
exception=The command '/bin/bash -c apt-get update &&     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections &&     apt install -y sudo &&     adduser --disabled-password --gecos "" $USER || true  &&     usermod -aG sudo $USER &&     sudo -Hu $USER sh -c "mkdir -m 700 ~/.ssh" &&     echo "$USER  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers &&     apt install -y         iproute2         collectd         rsync &&     rm -rf /var/lib/apt/lists/* &&     echo $'[program:collectd]\ncommand=/usr/sbin/collectd\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\nstderr_logfile=/dev/stderr\nstderr_logfile_maxbytes=0' > /etc/supervisord.conf.d/collectd.conf &&     echo $'[program:scylla-manager]\ncommand=/usr/bin/scylla-manager --developer-mode\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\nstderr_logfile=/dev/stderr\nstderr_logfile_maxbytes=0' > /etc/supervisord.conf.d/scylla-manager.conf &&     echo "autostart=false" >> /etc/supervisord.conf.d/scylla-server.conf &&     echo "autostart=false" >> /etc/supervisord.conf.d/scylla-housekeeping.conf &&     sed -i "\:/dev/stderr:d" /etc/bashrc' returned a non-zero code: 2
WARNING - [0]
No events with this severity
Running instances
No instances
Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor c8ae408f-f891-468b-afad-11b9398a72d8
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs c8ae408f-f891-468b-afad-11b9398a72d8
Logs:
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/c8ae408f-f891-468b-afad-11b9398a72d8/20211114_191143/monitor-set-c8ae408f.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/c8ae408f-f891-468b-afad-11b9398a72d8/20211114_191143/sct-runner-c8ae408f.tar.gz
Links:
Build URL: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/356/
--

**Comment by bentsi** [comment]
This is the error that failed the test:
(look the message `TearDown is starting...`)
```
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 202, in _create_nodes
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >     node = self._create_node(node_index)
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 184, in _create_node
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >     ContainerManager.build_container_image(node, "node")
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 363, in build_container_image
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >     image, logs = docker_client.images.build(tag=image_tag, **dockerfile_args, **build_args)
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/models/images.py", line 287, in build
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR >     raise BuildError(chunk['error'], result_stream)
22:11:09  < t:2021-11-14 19:10:58,969 f:tester.py       l:137  c:sdcm.tester          p:ERROR > docker.errors.BuildError: The command '/bin/bash -c apt-get update &&     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections &&     apt install -y sudo &&     adduser --disabled-password --gecos "" $USER || true  &&     usermod -aG sudo $USER &&     sudo -Hu $USER sh -c "mkdir -m 700 ~/.ssh" &&     echo "$USER  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers &&     apt install -y         iproute2         collectd         rsync &&     rm -rf /var/lib/apt/lists/* &&     echo $'[program:collectd]\ncommand=/usr/sbin/collectd\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\nstderr_logfile=/dev/stderr\nstderr_logfile_maxbytes=0' > /etc/supervisord.conf.d/collectd.conf &&     echo $'[program:scylla-manager]\ncommand=/usr/bin/scylla-manager --developer-mode\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\nstderr_logfile=/dev/stderr\nstderr_logfile_maxbytes=0' > /etc/supervisord.conf.d/scylla-manager.conf &&     echo "autostart=false" >> /etc/supervisord.conf.d/scylla-server.conf &&     echo "autostart=false" >> /etc/supervisord.conf.d/scylla-housekeeping.conf &&     sed -i "\:/dev/stderr:d" /etc/bashrc' returned a non-zero code: 2
22:11:09  < t:2021-11-14 19:10:58,972 f:tester.py       l:2298 c:ArtifactsTest        p:INFO  > TearDown is starting...
```
so this is not the root cause for the test failure
please investigate the issue
