### ISSUE TITLE
rolling-upgrade-alternator-test fails with: "Table usertable already exists"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4133]
Looks like Alternator "usertable" is tried to be created twice - a second time after the upgrade. probably should just skip the 'create-table' part for the second stress run. 
got an error of:
```
2021-11-12 06:17:45.588: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=8c1b3a87-3c6f-4850-9c60-cf389d3c6175, source=UpgradeTest.test_generic_cluster_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 800, in test_generic_cluster_upgrade
stress_thread_pool = self._run_stress_workload("stress_during_entire_upgrade", wait_for_finish=False)
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 780, in _run_stress_workload
self.pre_create_alternator_tables()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 683, in pre_create_alternator_tables
self.alternator.create_table(node=node, schema=schema)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/alternator/api.py", line 62, in create_table
table = dynamodb_api.resource.create_table(
File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 520, in do_action
response = action(self, *args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/boto3/resources/action.py", line 83, in __call__
response = getattr(parent.meta.client, operation_name)(*args, **params)
File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 386, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 705, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the CreateTable operation: Table usertable already exists
```

Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor fb3fa1a4-1393-4700-877b-30714521cf28
Restore monitor on AWS instance using Jenkins job
Show all stored logs command: $ hydra investigate show-logs fb3fa1a4-1393-4700-877b-30714521cf28
Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/fb3fa1a4-1393-4700-877b-30714521cf28/20211112_063930/db-cluster-fb3fa1a4.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/fb3fa1a4-1393-4700-877b-30714521cf28/20211112_063930/loader-set-fb3fa1a4.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/fb3fa1a4-1393-4700-877b-30714521cf28/20211112_063930/monitor-set-fb3fa1a4.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/fb3fa1a4-1393-4700-877b-30714521cf28/20211112_063930/sct-runner-fb3fa1a4.tar.gz
Links:
Build URL: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/60/
--

**Comment by yarongilor** [comment]
@soyacz , would you like to check it out?

**Comment by roydahan** [comment]
How is it related to @soyacz ?
When did it start happening? Is it consistent on every run of this test?

I think @Orenef11 added this test, but it was long ago, so I don't understand why it started happening.

**Comment by Orenef11** [comment]
Hi Roy,

Yes, I added it.
Do you want me to fix it?

**Comment by roydahan** [comment]
I don't know what's broken and why suddenly it fails.
Let's wait for answers from @yarongilor

**Comment by yarongilor** [comment]
> I don't know what's broken and why suddenly it fails. Let's wait for answers from @yarongilor

@roydahan , looks like it was added in this PR: https://github.com/scylladb/scylla-cluster-tests/pull/3973

**Comment by soyacz** [comment]
> > I don't know what's broken and why suddenly it fails. Let's wait for answers from @yarongilor
> 
> @roydahan , looks like it was added in this PR: #3973

In this PR I did some refactor and simplification - I should have moved this `pre_create_alternator_tables` out of running stress fuction. Will be fixed by @Orenef11 PR.

**Comment by Orenef11** [comment]
> > > I don't know what's broken and why suddenly it fails. Let's wait for answers from @yarongilor
> > 
> > 
> > @roydahan , looks like it was added in this PR: #3973
> 
> In this PR I did some refactor and simplification - I should have moved this `pre_create_alternator_tables` out of running stress fuction. Will be fixed by @Orenef11 PR.

Yes, my PR will fix it, and we will not get this error again.
