### ISSUE TITLE
syslog-ng errors with destination queue full

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4165]
### Versions
* **SCT**: master
* Test: longevity_lwt_test.LWTLongevityTest.test_lwt_longevity
* Build number: 309
* Backend: aws: eu-north-1
* Kernel version: 5.4.0-1035-aws
* Test-id: dfee7085-39f4-4e8e-b5ca-b04b992b72a8
* Start time: 2021-11-26 14:41:35
* End time: 2021-11-26 18:10:33
* Started by user: timer
* Cassandra-stress uses shared-aware driver

### Logs
* test_id:  dfee7085-39f4-4e8e-b5ca-b04b992b72a8
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181033/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20211126_181144-longevity-lwt-3h-master-monitor-node-dfee7085-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181033/grafana-screenshot-overview-20211126_181033-longevity-lwt-3h-master-monitor-node-dfee7085-1.png
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181506/db-cluster-dfee7085.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181506/loader-set-dfee7085.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181506/monitor-set-dfee7085.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/dfee7085-39f4-4e8e-b5ca-b04b992b72a8/20211126_181506/sct-runner-dfee7085.tar.gz

### Description

The event system logging broke about 30 minutes into the test run with what seems to be issues with the syslong-ng queue. As a result some events where left unpaired (i.e. the "end" of a continuous event could not be resolved to a "begin" event).

Example errors in one of the db nodes:
Initial error:

```
2021-11-26T16:38:32+00:00 longevity-lwt-3h-master-db-node-dfee7085-3 !     ERR | error: kex_exchange_identification: Connection closed by remote host
```

```
2021-11-26T14:24:57+00:00 longevity-lwt-3h-master-db-node-dfee7085-1 !     ERR | Destination reliable queue full, dropping message; filename      ='/tmp/syslog-ng-00000.rqf', queue_len='828', mem_buf_size='100000', disk_buf_size='2000000', persist_name='afsocket_dd_qfile(stream,10.0.2.      51:49153)'
```

**Comment by dkropachev** [comment]
It is a log throttling, I have an idea how to work it around

**Comment by soyacz** [comment]
> It is a log throttling, I have an idea how to work it around
@dkropachev according to https://www.syslog-ng.com/community/b/blog/posts/common-syslog-ng-error-messages-solutions this can be avoided by setting `flags(flow-control)` in syslog-ng configuration. Do we set this? Can we?

**Comment by dkropachev** [comment]
@soyacz , we don't use it and probably should add it for minor cases, but it won't help in case of nodetool repair, since throttling is there quque gonna get full and you will see same messages.

**Comment by soyacz** [comment]
according to docs it should help - but may cause logs to arrive late, so again timestamps will be out of order.
I think as a quick fix we could just enable this setting in one PR and in another fix issue with throttling.

**Comment by roydahan** [comment]
@dkropachev is it again due to too many log messages during repair?
If so, do we have some kind of breakdown of what are the messages about?
Let's do it and open an issue in scylla for these unneeded verbosity.

**Comment by fgelcer** [comment]
@dkropachev , what is the status of this one?

**Comment by bentsi** [comment]
@roydahan this was caused by Scylla, since it creates too many logs when repair/compaction happens. Dmitriy opened an issue
in the Scylla repo: https://github.com/scylladb/scylla/issues/9820
