### ISSUE TITLE
saving ES document throws an error, but do save the content

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4174]
### Versions
* **SCT**: branch-perf-v12
* **scylla**: master

### Logs
* test_id: 6590dc42-103d-47df-93ac-f7e1544af1ec
* job log: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-250gb-with-nemesis/131/

### Description

i'm seeing such failures for a while now, and before changing the `total_fields.limit` we see error events such as:
```
2021-11-26 12:03:12.444: (ElasticsearchEvent Severity.ERROR) period_type=one-time event_id=43ead58e-e502-481c-9b55-1e9817743177: doc_id=6590dc42-103d-47df-93ac-f7e1544af1ec error=RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
2021-11-26 12:12:48.740: (ElasticsearchEvent Severity.ERROR) period_type=one-time event_id=5ff7d00e-8930-4638-a20c-d30b9ea06c53: doc_id=6590dc42-103d-47df-93ac-f7e1544af1ec error=RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
2021-11-26 12:53:42.905: (ElasticsearchEvent Severity.ERROR) period_type=one-time event_id=a7d67d11-30e8-49a1-ac2e-6ec11b1f5cca: doc_id=6590dc42-103d-47df-93ac-f7e1544af1ec error=RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
```

they happened in the same test, with some time apart, but there is a document created, and it seems to contain (at least most of) the data created during this test.

it could be an issue in SCT, but it could be also an issue with some other underlying package.

**Comment by fgelcer** [comment]
@KnifeyMoloko FYI

**Comment by fgelcer** [comment]
@aleksbykov FYI

**Comment by aleksbykov** [comment]
@fgelcer it could be , that document is created with less number of fields, but with it is going to updated such error is happened.

**Comment by fgelcer** [comment]
> @fgelcer it could be , that document is created with less number of fields, but with it is going to updated such error is happened.

so you think it saved up to 1000 fields, and than failed?
i have now increased these indexes so it won't be a problem anymore

**Comment by aleksbykov** [comment]
> > @fgelcer it could be , that document is created with less number of fields, but with it is going to updated such error is happened.
> 
> so you think it saved up to 1000 fields, and than failed? i have now increased these indexes so it won't be a problem anymore

yes, i think so. because when we create document, it has set of predefined fileds. and then we update it with test_details and setup details. sections which has the largest number of fields

**Comment by fgelcer** [comment]
> > > @fgelcer it could be , that document is created with less number of fields, but with it is going to updated such error is happened.
> > 
> > 
> > so you think it saved up to 1000 fields, and than failed? i have now increased these indexes so it won't be a problem anymore
> 
> yes, i think so. because when we create document, it has set of predefined fileds. and then we update it with test_details and setup details. sections which has the largest number of fields

i have changed the limit in the indexes that are failing, and running the test again...
will report soon

**Comment by fgelcer** [comment]
i have increased the limits in these indexes, and this error is not showing anymore.
