### ISSUE TITLE
[artifacts-ami-test] The test run on the master node which has no docker

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#4203]
For some reason, the `artifacts-ami-test` (and others) running on the Jenkins master-node which has
no docker installed and it caused the error below,

I guess the tests themselves has nothing with the Jenkins master but the starting-point (`hydra.sh`) is
starting on Jenkins - and the question is why? if we have no good reason we should avoid running on
the master node.

It's reproducible.

**Note:** I see this issue on many other tests.

/cc @fruch 

```
22:03:23  + ./docker/env/hydra.sh run-test artifacts_test --backend aws --logdir /var/lib/jenkins/jobs/scylla-4.6/jobs/artifacts/jobs/artifacts-ami-test/workspace@2/scylla-cluster-tests
22:03:23  Running on Build Server...
22:03:23  ./docker/env/hydra.sh: line 144: docker: command not found
22:03:23  Docker not installed!!! Please run 'install-hydra.sh'!
```

**Comment by fgelcer** [comment]
why is it running on Jenkins mater? it shouldn't.

**Comment by yaronkaikov** [comment]
@benipeled Can you share one of the links?
is it in master branch or release?

**Comment by benipeled** [comment]
> why is it running on Jenkins mater? it shouldn't.

@fgelcer good question, that's probably the issue :)



> @benipeled Can you share one of the links? is it in master branch or release?

@yaronkaikov good point, I can't see it on `master` but on 4.6 - see the last two runs on
https://jenkins.scylladb.com/job/scylla-4.6/job/artifacts/job/artifacts-ami-test/

**Comment by yaronkaikov** [comment]
@benipeled it's a pkg issue, we are missing a backport https://github.com/scylladb/scylla-pkg/commit/e16ab5d9d3bcb82896ffd051f7fa89294d2bb1a8  - will do it now

**Comment by benipeled** [comment]
cherry-picked - https://github.com/scylladb/scylla-pkg/commit/75d2c755baccb49358213466c5ad10ac89a806e0
