### ISSUE TITLE
ResetLocalSchema nemesis fails due missing line in logs

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4211]
When running resetlocalschema nemesis, it fails with message `AssertionError: Schema version has not been recalculated`.
This happens because line containing `schema_tables - Schema version changed to` is not found.
While looking into messages.log we may find such a line, even in the same second as the error.

test_id: `36ad154f-65f1-43a6-a6d1-e40dcc5511cc`

 db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/db-cluster-36ad154f.tar.gz  |
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/monitor-set-36ad154f.tar.gz |
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/loader-set-36ad154f.tar.gz  |
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/sct-runner-36ad154f.tar.gz

**Comment by dkropachev** [comment]
> When running resetlocalschema nemesis, it fails with message `AssertionError: Schema version has not been recalculated`. This happens because line containing `schema_tables - Schema version changed to` is not found. While looking into messages.log we may find such a line, even in the same second as the error.

I need test_id, link to logs

**Comment by soyacz** [comment]
@dkropachev sorry, issue updated.

**Comment by juliayakovlev** [comment]
Message with pattern `schema_tables - Schema version changed to` appeared in the log later then really happened.

`nodetool  resetlocalschema`  started at `23:31:38,467` and finished at `23:31:39,472`:
```
< t:2021-12-08 23:31:38,467 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  resetlocalschema "...
< t:2021-12-08 23:31:39,472 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  resetlocalschema " finished with status 0
```

But a message with the sought pattern arrived to the log latter, at `t:2021-12-08 23:31:39,686`:
```
< t:2021-12-08 23:31:39,686 f:db_log_reader.py l:105  c:sdcm.db_log_reader   p:DEBUG > 021-12-08T23:31:39+00:00 longevity-10gb-3h-4-6-db-node-36ad154f-0-7 !    INFO |  [shard 1] schema_tables - Schema version changed to ff092222-c12e-384f-8574-2cde5c48c65f
```

So the nemesis failed, at `23:31:39,475`:
```
< t:2021-12-08 23:31:39,475 f:nemesis.py      l:221  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Update nemesis info with: {'start': 1639006296, 'end': 1639006299, 'duration': 2, 'node': 'Node 
longevity-10gb-3h-4-6-db-node-36ad154f-0-7 [34.73.124.159 | 10.142.0.14] (seed: False)', 'subtype': 'end', 'error': 'Schema version has not been recalculated', 'full_traceback': 'Traceback (most recent call last
):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3015, in wrapper\n    result = method(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 531, in disrupt_reset
localschema\n    assert list(rlocal_schema_res), "Schema version has not been recalculated"\nAssertionError: Schema version has not been recalculated\n'}
```

**Comment by dkropachev** [comment]
> Schema version has not been recalculated

Thanks Julia

**Comment by roydahan** [comment]
Is this one can be closed?

**Comment by soyacz** [comment]
this fix should help. Closing.
