### ISSUE TITLE
Ignored error events are still reported

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4217]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master/ 4.6.rc1

### Logs
* test_id: fa0623fd-f5cd-47b1-8005-fc424c9ae054
Logs:
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_214703/grafana-screenshot-gemini-1tb-10h-scylla-per-server-metrics-nemesis-20211209_214928-gemini-1tb-10h-master-monitor-node-fa0623fd-1.png
grafana - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_214703/grafana-screenshot-overview-20211209_214703-gemini-1tb-10h-master-monitor-node-fa0623fd-1.png
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_215721/db-cluster-fa0623fd.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_215721/loader-set-fa0623fd.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_215721/monitor-set-fa0623fd.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/fa0623fd-f5cd-47b1-8005-fc424c9ae054/20211209_215721/sct-runner-fa0623fd.tar.gz

### Steps to Reproduce

Run `NodetoolEnospc` nemesis

**Expected behavior:** During `NodetoolEnospc` nemesis, there are errors about 'no space left on device'. They are ignored by test and should not appear in SCT report. So there's no confusion if they happened during the nemesis. Test shouldn't be failed because of them.

**Actual behavior:** Errors are showing in report in ERROR section. Possibly failing the test.

**Comment by dkropachev** [comment]
There is no such error reported:
```
grep space ./sct-runner-fa0623fd/critical.log ./sct-runner-fa0623fd/error.log 
```

Currently we ignore only 'No space left on device', so this error is rightfully leaking thru the filter.
I have created scylla issue to figure out whether it is legit scylla issue or we can just ignore it.

https://github.com/scylladb/scylla/issues/9798

**Comment by enaydanov** [comment]
Don't see filtered events in the error.log

**Comment by dkropachev** [comment]
Here is good example of the issue: 

`11519ba5-9e2a-434a-8428-290775fc5d80`

db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/11519ba5-9e2a-434a-8428-290775fc5d80/20211213_162937/db-cluster-11519ba5.tar.gz
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/11519ba5-9e2a-434a-8428-290775fc5d80/20211213_162937/monitor-set-11519ba5.tar.gz
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/11519ba5-9e2a-434a-8428-290775fc5d80/20211213_162937/loader-set-11519ba5.tar.gz
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/11519ba5-9e2a-434a-8428-290775fc5d80/20211213_162937/sct-runner-11519ba5.tar.gz

**Comment by fgelcer** [comment]
> Currently to indentify a node on which event is running and to which event filter is applying we are using str(node) which gives out the following thing: ` Node longevity-small-set-1h-master-db-node-11519ba5-3 [34.246.227.233 | 172.20.25.97] (seed: True)`
> 
> As you can see, if (as example) seed status is changing on the node, events and filters are not matching anymore, as result filters can fail, which can fail the test.

why is it a node changing its seed status? do we have nemesis that plays with that?

**Comment by enaydanov** [comment]
Bentsi and I think that the node was not changed the seed status but it's the problem of sharing data between two processes inside SCT: main and DB logs reader.

**Comment by dkropachev** [comment]
@enaydanov , @bentsi , What is happening here is when we create db_log_reader process node is coppied into context of the child process and it keeps it's state unchanged during whole run.
At the time when it is happening is_seed is reporting Flase, because we did not set it's seed param yet.

Later on we change it's seed parameter and on the main process it is getting is_seed as True, while in db_log_reader context it is keeping it False, since those context are not in sync.

The solution would be the same - to use `node.name` instead of the `str(node)` in the event body.

**Comment by fgelcer** [comment]
> The solution would be the same - to use `node.name` instead of the `str(node)` in the event body.

that would definitely work, if this is the problem
