### ISSUE TITLE
Test is stuck after teardown completed and at the end was killed by jenkins with "error waiting for container: unexpected EOF"

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4249]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.rc1-0.20211208.542394c82 with build-id 96acb395cfbc08ffdc30ac34e1333b99d93b83d7`
Cluster size: 5 nodes (i3en.3xlarge)
Scylla running with shards number (live nodes):
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-2 (54.220.72.97 | 10.0.2.199): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-3 (54.216.90.33 | 10.0.0.45): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-5 (54.194.156.98 | 10.0.1.175): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-6 (54.194.67.86 | 10.0.0.46): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-8 (18.202.220.250 | 10.0.1.243): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-9 (34.244.72.5 | 10.0.3.25): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-10 (54.195.168.183 | 10.0.2.32): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-11 (34.250.104.247 | 10.0.2.198): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-12 (54.75.127.75 | 10.0.0.25): 12 shards
Scylla running with shards number (terminated nodes):
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-1 (52.211.88.74 | 10.0.1.80): 12 shards
   longevity-tls-2tb-4d-1dis-2nondis-4-db-node-a5420a05-4 (3.250.167.239 | 10.0.1.141): 12 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-026af3fe59e2ee4ba` (aws: eu-west-1)

Test: `longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d1ae0d0636d6781d168fc6fc1a6932f0638c3827/test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml)

**Issue description**

there were several `CRITICAL` events, and they had huge time difference between them, and the test didn't stop - expect the test to stop at c-s critical event.
1st event:
```
2021-12-17 04:02:49.104: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=bff3d247-567a-46ea-8d8f-bbc30b2c059f duration=41s: node=Node longevity-tls-2tb-4d-1dis-2nondis-4-loader-node-a5420a05-2 [52.49.36.246 | 10.0.2.101] (seed: False)
stress_cmd=cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=2460m -port jmx=6868 -mode cql3 native -rate threads=10
errors:
Stress command completed with bad status 1: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.45:9042] Timed out waiting
```

next event (there were dozens of critical events at the very same time):
```
2021-12-17 11:15:05.726: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=4851238f-00fb-405a-a47a-05f9d6d089b2: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=42159 node=Node longevity-tls-2tb-4d-1dis-2nondis-4-loader-node-a5420a05-1 [54.154.203.52 | 10.0.0.129] (seed: False)
java.io.IOException: Operation x10 on key(s) [364b394f4f384c4c3630]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

after that, another one:
```
2021-12-18 21:02:23.262: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=4851238f-00fb-405a-a47a-05f9d6d089b2 duration=1d17h0m25s: node=Node longevity-tls-2tb-4d-1dis-2nondis-4-loader-node-a5420a05-1 [54.154.203.52 | 10.0.0.129] (seed: False)
stress_cmd=cassandra-stress mixed cl=QUORUM duration=2460m -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=50 -pop seq=1..2147483648  -log interval=5 -col 'size=FIXED(64) n=FIXED(16)'
errors:
Stress command completed with bad status 1: Failed to connect over JMX; not collecting these stats
Failed to connect over JMX; not collecting th
```

there were other ones in between them (as maybe took some time to SCT to parse and raise all of them), but these are the "main" events.

Restore Monitor Stack command: `$ hydra investigate show-monitor a5420a05-20f0-401a-923e-8ccd93b92bfd`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a5420a05-20f0-401a-923e-8ccd93b92bfd)
Show all stored logs command: `$ hydra investigate show-logs a5420a05-20f0-401a-923e-8ccd93b92bfd`

Test id: `a5420a05-20f0-401a-923e-8ccd93b92bfd`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_220556/grafana-screenshot-longevity-2tb-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test-scylla-per-server-metrics-nemesis-20211218_220901-longevity-tls-2tb-4d-1dis-2nondis-4-monitor-node-a5420a05-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_220556/grafana-screenshot-longevity-2tb-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test-scylla-per-server-metrics-nemesis-20211218_220901-longevity-tls-2tb-4d-1dis-2nondis-4-monitor-node-a5420a05-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_220556/grafana-screenshot-overview-20211218_220556-longevity-tls-2tb-4d-1dis-2nondis-4-monitor-node-a5420a05-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_220556/grafana-screenshot-overview-20211218_220556-longevity-tls-2tb-4d-1dis-2nondis-4-monitor-node-a5420a05-1.png)
critical - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/critical.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/critical.log.tar.gz)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/db-cluster-a5420a05.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/db-cluster-a5420a05.tar.gz)
debug - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/debug.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/debug.log.tar.gz)
email_data - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/email_data.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/email_data.json.tar.gz)
error - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/error.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/error.log.tar.gz)
event - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/events.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/events.log.tar.gz)
left_processes - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/left_processes.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/left_processes.log.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/loader-set-a5420a05.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/loader-set-a5420a05.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/monitor-set-a5420a05.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/monitor-set-a5420a05.tar.gz)
normal - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/normal.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/normal.log.tar.gz)
output - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/output.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/output.log.tar.gz)
event - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/raw_events.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/raw_events.log.tar.gz)
summary - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/summary.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/summary.log.tar.gz)
warning - [https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/warning.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/warning.log.tar.gz)
sct - https://cloudius-jenkins-test.s3.amazonaws.com/a5420a05-20f0-401a-923e-8ccd93b92bfd/20211218_235712/sct.log.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.6/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/3/)

**Comment by fgelcer** [comment]
this test had in total of 84 critical events

**Comment by dkropachev** [comment]
This problem become more common recently, there is no clear reason for it.
I've investigated a run that have had same issue, but there was literally zero threads/processes at the end test.

Threading exit hook is not a reason.
