### ISSUE TITLE
compute_engine.list_nodes() failed because of ". Please try again or contact Google Support" errir

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla-cluster-tests#4279]
08:33:23    File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-gce-image-test/scylla-cluster-tests/sdcm/utils/common.py", line 834, in list_instances_gce
08:33:23      all_gce_instances = compute_engine.list_nodes()
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 2607, in list_nodes
08:33:23      self._ex_populate_volume_dict()
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 7948, in _ex_populate_volume_dict
08:33:23      aggregated_items = self.connection.request_aggregated_items(
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 170, in request_aggregated_items
08:33:23      response = self.request(request_path, method='GET').object
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 126, in request
08:33:23      response = super(GCEConnection, self).request(*args, **kwargs)
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/common/google.py", line 811, in request
08:33:23      return super(GoogleBaseConnection, self).request(
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/common/base.py", line 655, in request
08:33:23      response = responseCls(**kwargs)
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/common/base.py", line 169, in __init__
08:33:23      self.object = self.parse_body()
08:33:23    File "/usr/local/lib/python3.10/site-packages/libcloud/common/google.py", line 294, in parse_body
08:33:23      raise GoogleBaseError(message, self.status, code)
08:33:23  libcloud.common.google.GoogleBaseError: {'message': "Internal error. Please try again or contact Google Support. (Code: '5D4573AADC0FA.383C2FF.E80DCA0A')", 'domain': 'global', 'reason': 'backendError'}

[JOB url](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-gce-image-test/352/execution/node/91/log/)

**Comment by Orenef11** [comment]
Do you see this bug in the past?

**Comment by roydahan** [comment]
No, but it's probably a temporary issue.
Did you try again?

**Comment by Orenef11** [comment]
> No, but it's probably a temporary issue. Did you try again?

Yes, it was a temporary issue.
The second run was passed.
