### ISSUE TITLE
Nemesis: The add-new-node operation completion is verified by nodetool status and not by node-init-complation

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4331]
See details in: 
https://github.com/scylladb/scylla/issues/9629#issuecomment-998926636
As in the above link example: 

1. A replace node nemesis adds a new node.
2. SCT check for nodetool status of the newly added node to be "UN"
3. The replace nemesis completed (and another nemesis can start)
4. The new node actual init is completed only later on (can take an hour)
5. Thus it prevents and may fail some operations of the next started nemesis like nodetool decommission.

Suggested solution is:
Do not validate the new-node completed being added to cluster by the nodetool status, rather by looking for the node's init-completed message in log (probably can be found in an existing method of wait-db-up or something).

**Comment by yarongilor** [comment]
Consider opening a nodetool issue for this as well: "nodetool status " command should not show an initializing node as "UN" but rather as "UJ" or any other relevant alternative.

**Comment by roydahan** [comment]
Please consult with @slivne on the expected behaviour.

**Comment by roydahan** [comment]
@yarongilor did you look into it?

**Comment by yarongilor** [comment]
> Consider opening a nodetool issue for this as well: "nodetool status " command should not show an initializing node as "UN" but rather as "UJ" or any other relevant alternative.

@slivne can you please advise? can we open an issue for nodetool so user will be able to know when node is really up and normal (and cluster is ready for running another nodetool operation)?

**Comment by yarongilor** [comment]
It is agreed that both a nodetool issue and SCT fix are advised.
Opened https://github.com/scylladb/scylla-tools-java/issues/290 .

**Comment by roydahan** [comment]
So I don't understand how we don't have issues right now with our tests...

**Comment by fgelcer** [comment]
@yarongilor , what about this issue?

**Comment by fgelcer** [comment]
ping @yarongilor

**Comment by yarongilor** [comment]
it looks like the current state is accepted, according to this [comment](https://github.com/scylladb/scylla-dtest/pull/3463#issuecomment-1707541714).

 if the [issue](https://github.com/scylladb/scylla-cluster-tests/issues/4331) will ever be reproduced, we can add a fix (Change new node status verification from nodetool status to node-init complete)
