### ISSUE TITLE
make all sct - instances connections configurable

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#436]
GCE:
We use public ip for prometheus connection between db/loader and monitor in multiple DCs case.
It doesn't work in qavpc, it's not allowed to access 9180/9100/9103 ports by public ip.

Solutions:
- option1: add rule to allow to access 9180/9100/9103 ports by public ip.
- option2: always use private ip for prometheus target (GCE) 
- option3: make (sct - instances) all connections configurable

@roydahan

**Comment by roydahan** [comment]
adding rule is good enough, let's do this.

**Comment by amoskong** [comment]
done.
