### ISSUE TITLE
Performance jobs select ARM AMI's for i3 instances

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4370]
Performance test jobs select ARM based AMI's, while using i3 instances - causing error:
```RunInstances operation: The i3.4xlarge instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.```

Fix requires backporting to `branch-perf-v8`, `branch-perf-v11`,  `branch-perf-v10`, `branch-perf-v12`, `wait-create-es-doc'` (this one from git@github.com:aleksbykov/scylla-cluster-tests.git):
https://github.com/scylladb/scylla-cluster-tests/pull/4321
https://github.com/scylladb/scylla-cluster-tests/pull/4326

**Comment by dkropachev** [comment]
@roydahan , could you please approve it.

**Comment by fruch** [comment]
I've cherry-picked fixes to those branches:
branch-perf-v8, branch-perf-v11, branch-perf-v10, branch-perf-v12

where did you found that branch used from @aleksbykov own fork ? we shouldn't be using private forks on those jobs.

**Comment by aleksbykov** [comment]
@soyacz which job has my branch?

**Comment by fruch** [comment]
@soyacz mentioned `wait-create-es-doc`, I don't know why...

**Comment by soyacz** [comment]
see job: https://jenkins.scylladb.com/job/scylla-master/view/master-weekly-performance-tests/job/scylla-master-perf-regression-cdc-test-latency/configure

**Comment by fruch** [comment]
> see job: https://jenkins.scylladb.com/job/scylla-master/view/master-weekly-performance-tests/job/scylla-master-perf-regression-cdc-test-latency/configure

@aleksbykov please change it back to the correct perf branch needed for this job

**Comment by aleksbykov** [comment]
@fruch @soyacz , yes already set right branch
