### ISSUE TITLE
Perf test email not sent due attachment size

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4376]
Perf test: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-250gb-with-nemesis/167
(branch `branch-perf-v12`)

Failed to send results email due to:
```
21:37:49  Traceback (most recent call last):
21:37:49    File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis@3/scylla-cluster-tests/sdcm/send_email.py", line 635, in send_perf_email
21:37:49      reporter.send_email(subject=subject, content=html, files=email_content['attachments'])
21:37:49    File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis@3/scylla-cluster-tests/sdcm/results_analyze/__init__.py", line 164, in send_email
21:37:49      email.send(subject, content, html=html, recipients=self._email_recipients, files=files)
21:37:49    File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis@3/scylla-cluster-tests/sdcm/send_email.py", line 117, in send
21:37:49      email = self.prepare_email(subject, content, recipients, html, files)
21:37:49    File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-latency-250gb-with-nemesis@3/scylla-cluster-tests/sdcm/send_email.py", line 102, in prepare_email
21:37:49      raise AttachementSizeExceeded(current_size=attachment_size, limit=self._attachments_size_limit)
21:37:49  sdcm.send_email.AttachementSizeExceeded
```

**Comment by soyacz** [comment]
maybe we should post these attachments to s3 and just provide link in email?

**Comment by fgelcer** [comment]
what i see in here, is that the `reactor_stall_events_list.html` attachment file (basically, all the `debug.log` file) has 21Mb, meaning that, it is too big to be sent by email...

what should be done is to limit the file size (maybe the amount of entries), or just, as suggested, just add the link to the logs...
in other hand, maybe we should leave only the `ReactorStall` events, and remove the `KernelCallstack` ones, so the file result file will be much smaller...

another thing that should be addressed is to remove the WARNING events from the email body...

**Comment by fgelcer** [comment]
> what i see in here, is that the `reactor_stall_events_list.html` attachment file (basically, all the `debug.log` file) has 21Mb, meaning that, it is too big to be sent by email...
> 
> what should be done is to limit the file size (maybe the amount of entries), or just, as suggested, just add the link to the logs... in other hand, maybe we should leave only the `ReactorStall` events, and remove the `KernelCallstack` ones, so the file result file will be much smaller...
> 
> another thing that should be addressed is to remove the WARNING events from the email body...

@aleksbykov , WDYT? i will try to write these fixes tomorrow, so i would like to hear your opinion beforehand.

**Comment by roydahan** [comment]
@fgelcer what is the status of this?
According to @ilya-rarov we hit this in this week results.

**Comment by fgelcer** [comment]
> @fgelcer what is the status of this? According to @ilya-rarov we hit this in this week results.

yes, i saw it with him, and this is the next task in my pipeline

**Comment by aleksbykov** [comment]
> > what i see in here, is that the `reactor_stall_events_list.html` attachment file (basically, all the `debug.log` file) has 21Mb, meaning that, it is too big to be sent by email...
> > what should be done is to limit the file size (maybe the amount of entries), or just, as suggested, just add the link to the logs... in other hand, maybe we should leave only the `ReactorStall` events, and remove the `KernelCallstack` ones, so the file result file will be much smaller...
> > another thing that should be addressed is to remove the WARNING events from the email body...
> 
> @aleksbykov , WDYT? i will try to write these fixes tomorrow, so i would like to hear your opinion beforehand.

@fgelcer sorry a bit missed. I already prepare fix with removing the warning messages. I am going to create a pr today.
I think we can limit number of events in email and attached files with 100 entities. only for each and add some notes that all info could be found in logs.
