### ISSUE TITLE
test_drain_terminate_decommission_add_node_kubernetes fails on the local K8S (kind)

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4404]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 4.5.3
* **operator**: 1.7.0 and 1.7.1

### Logs
* test_id: 94dc01cf-eb86-4076-838f-9f65fc52deee
* job log: https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.7/job/functional/job/functional-k8s-local-kind-aws/5

### Description

If we run K8S functional test called `test_drain_terminate_decommission_add_node_kubernetes` on the local K8S (kind) backend
using Scylla 4.5.3 we get following error:

```

12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > WARN  2022-02-02 10:04:16,008 [shard 0] seastar - Exceptional future ignored: seastar::sleep_aborted (Sleep is aborted), backtrace: 0x4348b8e 0x4349030 0x43493d8 0x3f66efb 0x1b08bc6 0x3fb225f 0x3fb3447 0x3f50ad5 0x3f4fef6 0xe8ffa4 /opt/scylladb/libreloc/libc.so.6+0x281e1 0xe8cd4d
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x4348b8e
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x4349030
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x43493d8
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x3f66efb
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x1b08bc6
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x3fb225f
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x3fb3447
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x3f50ad5
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0x3f4fef6
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0xe8ffa4
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > /opt/scylladb/libreloc/libc.so.6+0x281e1
12:04:20  < t:2022-02-02 10:04:16,098 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > 0xe8cd4d
```

Then, we get lots of following errors till the test timeout:

```
12:08:31  < t:2022-02-02 10:08:21,938 f:file_logger.py  l:89   c:sdcm.sct_events.file_logger p:INFO  > NFO  2022-02-02 10:08:21,873 [shard 0] rpc - client 10.96.126.188:7000: unknown verb exception 6 ignored
```

It works ok on the EKS backend.
It works ok with Scylla 4.4.x

### Steps to Reproduce

1. Deploy Scylla 4.5.3 on local K8S (kind)
2. Run `test_drain_terminate_decommission_add_node_kubernetes` test
3. See error

**Expected behavior:** There should not be any backtrace and recreated pod must get up ok.

**Actual behavior:** Scylla cluster gets broken.

**Comment by vponomaryov** [comment]
K8S logs: [kind-replace-failure-v2.tar.gz](https://github.com/scylladb/scylla-cluster-tests/files/7988943/kind-replace-failure-v2.tar.gz)

**Comment by vponomaryov** [comment]
From the another run:

```
node-2 logs:

E0202 17:58:22.979228       1 sidecar/probes.go:109] "readyz probe: can't get scylla native transport" err="giving up after 1 attempts: agent [HTTP 404] Not found" Service="scylla/sct-cluster-dc-1-kind-2" Node="10.96.86.25"
E0202 17:58:32.979570       1 sidecar/probes.go:109] "readyz probe: can't get scylla native transport" err="giving up after 1 attempts: agent [HTTP 404] Not found" Service="scylla/sct-cluster-dc-1-kind-2" Node="10.96.86.25"
E0202 17:58:42.979052       1 sidecar/probes.go:109] "readyz probe: can't get scylla native transport" err="giving up after 1 attempts: agent [HTTP 404] Not found" Service="scylla/sct-cluster-dc-1-kind-2" Node="10.96.86.25"
INFO  2022-02-02 17:58:43,410 [shard 0] gossip - Gossip not settled after 1 polls.
INFO  2022-02-02 17:58:46,411 [shard 0] gossip - Gossip settled after 1 extra polls; proceeding
INFO  2022-02-02 17:58:46,455 [shard 0] storage_service - JOINING: sleeping 30000 ms for pending range setup
INFO  2022-02-02 17:58:46,455 [shard 0] gossip - Waiting for pending range setup...
I0202 17:58:52.978060       1 sidecar/probes.go:121] "readyz probe: node is not ready" Service="scylla/sct-cluster-dc-1-kind-2"
I0202 17:59:02.978803       1 sidecar/probes.go:121] "readyz probe: node is not ready" Service="scylla/sct-cluster-dc-1-kind-2"
I0202 17:59:12.979389       1 sidecar/probes.go:121] "readyz probe: node is not ready" Service="scylla/sct-cluster-dc-1-kind-2"

$ kubectl get svc -n scylla
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                               AGE
sct-cluster-client        ClusterIP   None            <none>        9180/TCP,5090/TCP                                                                     40m
sct-cluster-dc-1-kind-0   ClusterIP   10.96.178.104   <none>        7000/TCP,7001/TCP,7199/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,10001/TCP,9160/TCP   40m
sct-cluster-dc-1-kind-1   ClusterIP   10.96.79.79     <none>        7000/TCP,7001/TCP,7199/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,10001/TCP,9160/TCP   40m
sct-cluster-dc-1-kind-2   ClusterIP   10.96.86.25     <none>        7000/TCP,7001/TCP,7199/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,10001/TCP,9160/TCP   11m

$ kubectl exec -it sct-cluster-dc-1-kind-0 -n scylla -c scylla -- bash
# nodetool status
Datacenter: dc-1
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
DN  10.96.156.194  199.65 KB  256          ?       921a700c-8d58-4220-a735-bb80554f9e25  kind
UN  10.96.178.104  103 KB     256          ?       10de0f2f-9e6b-4fce-88bb-f45d4fdf4ab0  kind
UJ  10.96.86.25    ?          256          ?       4c10f33c-a5df-462c-8d17-3e9f8a040c38  kind
UN  10.96.79.79    153.4 KB   256          ?       47b3b678-a360-40da-a4c8-299f3ff9e733  kind

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

The new pod (UJ  10.96.86.25) tries to join the cluster and fails to do it all the time. From time to time it gets removed from the list of nodes in nodetool.
The old one (DN  10.96.156.194 ) doesn't get removed in such a case at all.

**Comment by bentsi** [comment]
we need to investigate this and get to the root cause. I will add a task for that

**Comment by fruch** [comment]
@vponomaryov 
"Sleep is aborted" during shutdown isn't a real issue, it's harmless
"unknown verb exception 6" is also harmless

I job log https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.7/job/functional/job/functional-k8s-local-kind-aws/5
I see this failure:
```
ERROR 2022-02-02 10:08:13,304 [shard 0] init - Startup failed: std::runtime_error (A node required to move the data consistently is down (10.96.236.180).  If you wish to move the data from a potentially inconsistent replica, restart the node with consistent_rangemovement=false)
```

node 10.96.236.180 is needed to stream data out of it

cause for some reason node-2 is bootstraping (scylla can't bootstrap, while a node is down)
```
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - JOINING: waiting for ring information
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - JOINING: schema complete, ready to bootstrap
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - JOINING: waiting for pending range calculation
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - JOINING: calculation complete, ready to bootstrap
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - Checking bootstrapping/leaving nodes: ok
INFO  2022-02-02 10:06:59,105 [shard 0] storage_service - JOINING: getting bootstrap token
```
also node-2, is restarting with the same ip address, after it was decommissioned (which is very problematic for scylla):
```
ERROR 2022-02-02 10:08:13,304 [shard 0] init - Startup failed: std::runtime_error (A node required to move the data consistently is down (10.96.236.180).  If you wish to move the data from a potentially inconsistent replica, restart the node with consistent_rangemovement=false)
2022-02-02 10:08:13,343 INFO exited: scylla (exit status 1; not expected)
```

Question is why it's bootstrapping, cause SCT configuration ? or cause of the operator ?, in EKS/GKS we get new ip_address on restarts/scheduled pods ?

**Comment by vponomaryov** [comment]
> Question is why it's bootstrapping, cause SCT configuration ? or cause of the operator ?, in EKS/GKS we get new ip_address on restarts/scheduled pods ?
It is bootstrapping because we add the node to the existing cluster. SCT's config for enabling or disabling auto bootstrapping doesn't make any effect here AFAIK. So, it must be operator.
Restarts do not change IP addresses because "containers" get restarted keeping its parent resource "pod" stay the same.
And IP addresses are bound to pods.

Also, tested scylla-4.6.3 with the Calico networking in KinD tool. It generates random IP addresses. Problem stayed.
Also, the problem is flaky. I had 2 successful runs having the same configuration among lots of failures.

**Comment by fruch** [comment]
> > Question is why it's bootstrapping, cause SCT configuration ? or cause of the operator ?, in EKS/GKS we get new ip_address on restarts/scheduled pods ?
> 
> It is bootstrapping because we add a node to an existing cluster. SCT's config for enabling or disabling auto bootstrapping doesn't make any effect here AFAIK. So, it must be operator. And, according to Scylla docs, it is expected. We must enable bootstrapping when we add a new node. Restarts do not change IP addresses because "containers" get restarted keeping its parent resource "pod" stay the same. And IP addresses are bound to pods.
> 
> Also, tested scylla-4.6.3 with the Calico networking in KinD tool. It generates random IP addresses. Problem stayed. Also, the problem is flaky. I had 2 successful runs having the same configuration among lots of failures.

So my guess the operater doesn't wait enough for making sure the old node is purged from the system.

It's question to both scylla and operator, why this is happing (move the ball to there, start with operator)

**Comment by vponomaryov** [comment]
Filed operator bug report in the operator repo: https://github.com/scylladb/scylla-operator/issues/982
