### ISSUE TITLE
artifacts-ami-test-arm failing due to wrong availability zone

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#4442]
The current default availability zone is `a` and the new instance type we are using for this test `im4gn.xlarge` is not available on this zone. 
```
13:28:48  < t:2022-02-13 11:28:48,175 f:tester.py       l:137  c:sdcm.tester          p:ERROR > botocore.exceptions.ClientError: An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (im4gn.xlarge) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1b, us-east-1c, us-east-1d.
```

https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test-arm/23/console

**Comment by fgelcer** [comment]
@yaronkaikov , it should have a fix similar to what @ShlomiBalalis did in here #4307

**Comment by fgelcer** [comment]
@yaronkaikov , i see it is supposed to be correctly set in the pipeline ([here](https://github.com/scylladb/scylla-cluster-tests/blob/c400ba1be60fcb4a6bf84907ee86367376e88768/jenkins-pipelines/artifacts-ami-arm.jenkinsfile#L10)), so maybe you are setting this parameter in the call of this pipeline?

**Comment by fgelcer** [comment]
and i see (at least for master) that the job is using the wrong pipeline file:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test-arm/configure

**Comment by yaronkaikov** [comment]
@fgelcer can you have a look on this failure? https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test-arm/26/

**Comment by fgelcer** [comment]
> @fgelcer can you have a look on this failure? https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test-arm/26/

@yaronkaikov , this is the failure:
```
An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (im4gn.xlarge) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1b, us-east-1c, us-east-1d.
```

in the parameters of the new run, i still see it "using" the wrong availability zone:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-test-arm/26/parameters/

**Comment by yaronkaikov** [comment]
@fgelcer Just triggered the job again, Thanks

**Comment by yaronkaikov** [comment]
I will wait to see it's passing then i will close this issue

**Comment by fgelcer** [comment]
@yaronkaikov , last build passed.
