### ISSUE TITLE
LoadAndStream nemesis fails with - AssertionError: Load and stream wasn't finished on the node

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4443]
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220209.5099b1e27 with build-id b0986550af32b8da96b50442a53423047ed91696`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   alternator-3h-master-db-node-250cd553-1 (54.195.181.238 | 10.0.3.226): 14 shards
   alternator-3h-master-db-node-250cd553-2 (34.247.155.5 | 10.0.1.84): 14 shards
   alternator-3h-master-db-node-250cd553-3 (54.229.15.27 | 10.0.2.132): 14 shards
   alternator-3h-master-db-node-250cd553-4 (34.240.17.36 | 10.0.2.96): 14 shards
   alternator-3h-master-db-node-250cd553-6 (54.75.123.18 | 10.0.2.170): 14 shards
   alternator-3h-master-db-node-250cd553-7 (3.250.196.83 | 10.0.0.81): 14 shards
Scylla running with shards number (terminated nodes):
   alternator-3h-master-db-node-250cd553-5 (52.30.193.66 | 10.0.1.253): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f894d9df1a4e76fc` (aws: eu-west-1)

Test: `longevity-alternator-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h.yaml&source=gmail-html&ust=1644840237392000&usg=AOvVaw2gaP-la5ylLzPeP41ckZoa))

**Issue description**

====================================

```
2022-02-13 07:37:07.130: (DisruptionEvent Severity.ERROR) period_type=end event_id=9999f243-f0fc-4425-96da-0ffdf92ed4e5 duration=1m58s: nemesis_name=LoadAndStream target_node=Node alternator-3h-master-db-node-250cd553-7 [3.250.196.83 | 10.0.0.81] (seed: False) errors=Load and stream wasn't finished on the node alternator-3h-master-db-node-250cd553-7
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3165, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/version_utils.py", line 428, in inner
return mapped_func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1101, in disrupt_load_and_stream
SstableLoadUtils.validate_load_and_stream_status(load_on_node, system_log_follower)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py", line 207, in validate_load_and_stream_status
cls.wait_for_load_and_stream_finish(node, system_log_follower, keyspace_name, table_name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py", line 176, in wait_for_load_and_stream_finish
assert load_and_stream_messages, f"Load and stream wasn't finished on the node {[node.name](http://node.name/)}"
AssertionError: Load and stream wasn't finished on the node alternator-3h-master-db-node-250cd553-7
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 250cd553-812b-4a5d-ae3b-2741acad5329`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=250cd553-812b-4a5d-ae3b-2741acad5329](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id%3D250cd553-812b-4a5d-ae3b-2741acad5329&source=gmail-html&ust=1644840237392000&usg=AOvVaw3wcDHB3pdPs308l4u3HNvk))
Show all stored logs command: `$ hydra investigate show-logs 250cd553-812b-4a5d-ae3b-2741acad5329`

Test id: `250cd553-812b-4a5d-ae3b-2741acad5329`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20220213_075746-alternator-3h-master-monitor-node-250cd553-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20220213_075746-alternator-3h-master-monitor-node-250cd553-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20220213_075746-alternator-3h-master-monitor-node-250cd553-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20220213_075746-alternator-3h-master-monitor-node-250cd553-1.png)&source=gmail-html&ust=1644840237392000&usg=AOvVaw2P8bvdojJfIoDxKaKTZz_Q)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-overview-20220213_075511-alternator-3h-master-monitor-node-250cd553-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-overview-20220213_075511-alternator-3h-master-monitor-node-250cd553-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-overview-20220213_075511-alternator-3h-master-monitor-node-250cd553-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_075511/grafana-screenshot-overview-20220213_075511-alternator-3h-master-monitor-node-250cd553-1.png)&source=gmail-html&ust=1644840237392000&usg=AOvVaw1vd7Doh75rnGAYtwCbiC7M)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/db-cluster-250cd553.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/db-cluster-250cd553.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/db-cluster-250cd553.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/db-cluster-250cd553.tar.gz)&source=gmail-html&ust=1644840237392000&usg=AOvVaw0gFtxm66dZVuHM8uL1om7E)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/loader-set-250cd553.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/loader-set-250cd553.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/loader-set-250cd553.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/loader-set-250cd553.tar.gz)&source=gmail-html&ust=1644840237393000&usg=AOvVaw3JDnioNSEoSoNlXt6cclsS)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/monitor-set-250cd553.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/monitor-set-250cd553.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/monitor-set-250cd553.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/monitor-set-250cd553.tar.gz)&source=gmail-html&ust=1644840237393000&usg=AOvVaw1QBDDbisdAfhrHmFM4zVqd)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/sct-runner-250cd553.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/sct-runner-250cd553.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/sct-runner-250cd553.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/250cd553-812b-4a5d-ae3b-2741acad5329/20220213_081008/sct-runner-250cd553.tar.gz)&source=gmail-html&ust=1644840237393000&usg=AOvVaw0VNi2aQ0Cr4BuWbPNjrcz9)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/340/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/340/&source=gmail-html&ust=1644840237393000&usg=AOvVaw0i5sSsIGxwc3efZ6hmJAMo))

**Comment by juliayakovlev** [comment]
It's Scylla issue:
https://github.com/scylladb/scylla/issues/9902
