### ISSUE TITLE
upgrade test - ignore_upgrade_cdc_errors not ignoring CDC error for branch-2021.1

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4451]
following fix on #3617 for issue https://github.com/scylladb/scylla/issues/6697, in the last run for 2021.1 release https://jenkins.scylladb.com/view/nexts/job/enterprise-2021.1/job/rolling-upgrade/job/rolling-upgrade-centos7-test/85/ we are still getting errors for this log prints:
```
< t:2022-02-13 14:54:51,906 f:cluster.py      l:1505 c:sdcm.cluster         p:DEBUG > 2022-02-13T14:54:40+00:00  rolling-upgrade-2021-1-centos-db-node-5f4781d5-0-4 !ERR     | scylla: [shard 0] cdc - Could not retrieve CDC streams with timestamp {2022/02/13 14:15:52} upon gossip event. Reason: "std::runtime_error (Could not find CDC generation with timestamp 2022/02/13 14:15:52 in distributed system tables (current time: 2022/02/13 14:54:40), even though some node gossiped about it.)". Action: not retrying.
```

need to understand why (maybe the filter in this branch is broken?), and address it.

logs are here
https://cloudius-jenkins-test.s3.amazonaws.com/5f4781d5-952a-4ffe-8d1e-48b28813a5ca/20220213_170737/db-cluster-5f4781d5.tar.gz
https://cloudius-jenkins-test.s3.amazonaws.com/5f4781d5-952a-4ffe-8d1e-48b28813a5ca/20220213_170737/sct-runner-5f4781d5.tar.gz

**Comment by yarongilor** [comment]
Reproduced in 2021.1.13:

Test details
Test: upgrade_test.UpgradeTest.test_generic_cluster_upgrade
Build number: 93
Backend: gce: eu-west-1
Kernel version: 3.10.0-1160.71.1.el7.x86_64
Test-id: 34327404-050a-4b57-865e-2ff5fac7e2c3
Start time: 2022-08-08 15:05:42
End time: 2022-08-08 16:29:36
Started by user: yaronkaikov
Test result
FAILED
System under test
ScyllaDB version: 2020.1.14-0.20220616.4769279f8 with build-id 5d90e513ebcd04f191c0374f1669d431a12fd1fc (-)
Target ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2021.1/rpm/centos/2022-08-07T16:41:09Z/scylla.repo
Instance type: n1-highmem-8
Number of ScyllaDB nodes: 3
Last events by severity
CRITICAL - [0]
No events with this severity
ERROR - [5]
```
2022-08-08 15:42:59.000: (DatabaseLogEvent Severity.ERROR): type=RUNTIME_ERROR regex=std::runtime_error line_number=4948 node=Node rolling-upgrade-2021-1-centos-db-node-34327404-0-3 [34.75.26.56 | 10.142.1.75] (seed: False)
2022-08-08T15:42:59+00:00  rolling-upgrade-2021-1-centos-db-node-34327404-0-3 !ERR     | scylla: [shard 0] cdc - Could not retrieve CDC streams with timestamp {2022/08/08 14:54:36} upon gossip event. Reason: "std::runtime_error (Could not find CDC generation with timestamp 2022/08/08 14:54:36 in distributed system tables (current time: 2022/08/08 15:42:59), even though some node gossiped about it.)". Action: not retrying.
```

**Comment by fruch** [comment]
@fgelcer the PR mentioned here was never merged, it was closed in favor of a PR that was never backported to 2021.1, if this need to be ignored someone need to do the work.

**Comment by fgelcer** [comment]
> @fgelcer the PR mentioned here was never merged, it was closed in favor of a PR that was never backported to 2021.1, if this need to be ignored someone need to do the work.

should be backport it to `branch-2021.1` then?

**Comment by fruch** [comment]
> > @fgelcer the PR mentioned here was never merged, it was closed in favor of a PR that was never backported to 2021.1, if this need to be ignored someone need to do the work.
> 
> should be backport it to `branch-2021.1` then?

#3617 extended the ignore time, by enlarging the context, #3907 is a feature/fix that might have covered achieved the same (at least according to @amoskong), @benipeled seems to have decided no to backport cause of it's complexity (spans across lots of files).

So it's or resurrect #3617, or opening a PR based on #3907 for backporting
I'm guessing re-implementing #3617 would be easier, and less affect on other code in the branch

**Comment by fgelcer** [comment]
> > > @fgelcer the PR mentioned here was never merged, it was closed in favor of a PR that was never backported to 2021.1, if this need to be ignored someone need to do the work.
> > 
> > 
> > should be backport it to `branch-2021.1` then?
> 
> #3617 extended the ignore time, by enlarging the context, #3907 is a feature/fix that might have covered achieved the same (at least according to @amoskong), @benipeled seems to have decided no to backport cause of it's complexity (spans across lots of files).
> 
> So it's or resurrect #3617, or opening a PR based on #3907 for backporting I'm guessing re-implementing #3617 would be easier, and less affect on other code in the branch

i don't understand why Beni Peled was mentioned in here, but in any case, i will try to give a ride with #3617 and see if that eventually solve the problem

**Comment by fruch** [comment]
> > > > @fgelcer the PR mentioned here was never merged, it was closed in favor of a PR that was never backported to 2021.1, if this need to be ignored someone need to do the work.
> > > 
> > > 
> > > should be backport it to `branch-2021.1` then?
> > 
> > 
> > #3617 extended the ignore time, by enlarging the context, #3907 is a feature/fix that might have covered achieved the same (at least according to @amoskong), @benipeled seems to have decided no to backport cause of it's complexity (spans across lots of files).
> > So it's or resurrect #3617, or opening a PR based on #3907 for backporting I'm guessing re-implementing #3617 would be easier, and less affect on other code in the branch
> 
> i don't understand why Beni Peled was mentioned in here, but in any case, i will try to give a ride with #3617 and see if that eventually solve the problem

I've meant @bentsi  , both starts with `ben` :)
