### ISSUE TITLE
Get manager backup progress error: unknown command "progress" for "sctool"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4527]
*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `2021.1.8-0.20220106.fcdf103fd with build-id e7277ef17c9e486dde5dba5b5f8609af2f05d98d`
Cluster size: 6 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-1 (63.32.204.218 | 172.29.13.145): 8 shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-3 (34.241.243.118 | 172.29.14.62): 8 shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-4 (46.137.55.212 | 172.29.13.95): 8 shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-6 (99.81.128.45 | 172.29.12.232): 8 shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-7 (54.228.29.134 | 172.29.12.8): 8 shards
Scylla running with shards number (terminated nodes):
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-2 (54.75.1.58 | 172.29.12.189): None shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-5 (99.81.21.152 | 172.29.14.30): None shards
   longevity-100gb-48h-cloud-master-db-node-4d8ccb61-8 (54.220.183.75 | 172.29.14.241): None shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f1ed0c0f50a76eec` (aws: eu-west-1)

Test: `cloud-longevity-100gb-3d`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- scylla_cloud_longevity-100GB-48h.yaml (Siren repo)
- scylla_cloud_defaults.yaml (Siren repo)
- scylla_cloud.yaml (Siren repo)

**Issue description**

After adding support of sctool 3.0 with commit "refactor(manager): Rewritten the manager code to use the new 3.0 cli", the test failed to get manager backup progress.

sctool res after parsing: [['Client version: 2.5.4-0.20211201.8aef1088'], ['Server version: 2.5.4-0.20211201.8aef1088']]

Get progress of manager backup wrong command - should be "task progress", but ran:
```
/opt/scylla/scylla-cloud -c /opt/scylla/scylla-dbaas.yml cluster manager sctool --cluster-id 16027 -- progress backup/d7936c29-42e3-49b5-9342-4730a87c594c
```
 And it failed with Error: `unknown command "progress" for "sctool"`

Restore Monitor Stack command: `$ hydra investigate show-monitor 4d8ccb61-d454-4000-9e2e-739e08055a14`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=4d8ccb61-d454-4000-9e2e-739e08055a14](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3D4d8ccb61-d454-4000-9e2e-739e08055a14&source=gmail-html&ust=1647510012862000&usg=AOvVaw13tm47aZ5x2Yc2Z_L7L4gt))
Show all stored logs command: `$ hydra investigate show-logs 4d8ccb61-d454-4000-9e2e-739e08055a14`

Test id: `4d8ccb61-d454-4000-9e2e-739e08055a14`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-cloud-longevity-100gb-3d-scylla-per-server-metrics-nemesis-20220311_123340-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-cloud-longevity-100gb-3d-scylla-per-server-metrics-nemesis-20220311_123340-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-cloud-longevity-100gb-3d-scylla-per-server-metrics-nemesis-20220311_123340-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-cloud-longevity-100gb-3d-scylla-per-server-metrics-nemesis-20220311_123340-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png)&source=gmail-html&ust=1647510012862000&usg=AOvVaw2oZchX2yZ4R-Q-Aj0T5H8W)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-overview-20220311_123049-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-overview-20220311_123049-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-overview-20220311_123049-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_123049/grafana-screenshot-overview-20220311_123049-longevity-100gb-48h-cloud-master-monitor-node-4d8ccb61-1.png)&source=gmail-html&ust=1647510012862000&usg=AOvVaw30zjZX0zEa08RofbIvOeDX)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/db-cluster-4d8ccb61.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/db-cluster-4d8ccb61.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/db-cluster-4d8ccb61.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/db-cluster-4d8ccb61.tar.gz)&source=gmail-html&ust=1647510012862000&usg=AOvVaw2elCZaR_RsP03ClJ-z1Vi9)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/loader-set-4d8ccb61.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/loader-set-4d8ccb61.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/loader-set-4d8ccb61.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/loader-set-4d8ccb61.tar.gz)&source=gmail-html&ust=1647510012862000&usg=AOvVaw1fNBOvFcAFVxs9UV-wHRuF)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/monitor-set-4d8ccb61.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/monitor-set-4d8ccb61.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/monitor-set-4d8ccb61.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/monitor-set-4d8ccb61.tar.gz)&source=gmail-html&ust=1647510012862000&usg=AOvVaw3OnFM3Z44JS6HHC9BUK4Wg)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/sct-runner-4d8ccb61.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/sct-runner-4d8ccb61.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/sct-runner-4d8ccb61.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/sct-runner-4d8ccb61.tar.gz)&source=gmail-html&ust=1647510012862000&usg=AOvVaw13jL_S7YqoybkOARLA63hj)
siren-manager-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/siren-manager-set-4d8ccb61.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/siren-manager-set-4d8ccb61.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/siren-manager-set-4d8ccb61.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/4d8ccb61-d454-4000-9e2e-739e08055a14/20220311_124905/siren-manager-set-4d8ccb61.tar.gz)&source=gmail-html&ust=1647510012862000&usg=AOvVaw3-46k7tNhGtFBwYzn7SXbD)

[Jenkins job URL]([https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-100gb-3d/100/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-100gb-3d/100/&source=gmail-html&ust=1647510012862000&usg=AOvVaw0h8b-MTjzb23SZSjFGW56B))

**Comment by bentsi** [comment]
@ShlomiBalalis please look into

**Comment by fgelcer** [comment]
ping @ShlomiBalalis
