### ISSUE TITLE
Launch of nodetool command when JMX server is not ready during the RebuildStreamingErr nemesis

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#4539]
## Installation details

Kernel Version: 5.11.0-1028-aws

Scylla version (or git commit hash): `5.1.dev-20220303.0544973b15dd` with build-id `3b69cb8b4d61d8190175613119fcc982a0b5eddb`

Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-maste-oracle-db-node-7fc9fe63-1 (44.200.3.219 | 10.0.1.217) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-4 (3.239.46.151 | 10.0.1.184) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 (3.235.9.52 | 10.0.0.207) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-2 (3.222.205.82 | 10.0.0.64) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-1 (3.238.195.252 | 10.0.1.74) (shards: 2)

OS / Image: `ami-0e1d3b0b20fb2421e` (aws: us-east-1)

Test: `gemini-3h-with-nemesis-test`

Test id: `7fc9fe63-d9e9-4a55-9500-9f5606fe74a6`

Test name: `gemini/gemini-3h-with-nemesis-test`

Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/234f79a81bc97d0e44c3ab51441017b646fdf393/test-cases/gemini/gemini-3h-with-nemesis.yaml)

## Issue description
The issue occurred during the nemesis `disrupt_rebuild_streaming_err` running on the node `gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3`

**SCT log:** The node-3 was going to be rebooted 
```
< t:2022-03-20 07:55:17,365 f:cluster.py      l:1041 c:sdcm.cluster_aws     p:DEBUG > Node gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 [3.235.9.52 | 10.0.0.207] (seed: False): Hardly rebooting node
```
**Node-3 log:** Node has been rebooted and began starting up
```
Mar 20 07:56:21 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 systemd[1]: Stopped Scylla Server.
-- Reboot --
Mar 20 07:57:09 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 systemd[1]: Condition check resulted in Scylla Cloud Image Setup service being skipped.
Mar 20 07:57:09 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 systemd[1]: Starting Scylla Server...
```

After a while, Scylla service started and began to listen CQL ports

```
Mar 20 07:57:17 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 systemd[1]: Started Scylla Server.
```
```
Mar 20 07:57:42 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 scylla[756]:  [shard 0] cql_server_controller - Starting listening for CQL clients on 10.0.0.207:9042 (unencrypted, non-shard-aware)
Mar 20 07:57:42 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 scylla[756]:  [shard 0] cql_server_controller - Starting listening for CQL clients on 10.0.0.207:19042 (unencrypted, shard-aware)
```
**SCT log:** Meanwhile, the nemesis was waiting for Scylla to be up
```
< t:2022-03-20 07:57:13,782 f:nemesis.py      l:2813 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.GeminiChaosMonkey: Recover the target node by a final rebuild
```
When it discovered Scylla was up it ran the command `/usr/bin/nodetool  rebuild`. This command failed with the following error
```
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_rebuild_streaming_err at 0x7f021070c040> < t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_rebuild_streaming_err at 0x7f021070c040>
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3314, in wrapper
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2840, in disrupt_rebuild_streaming_err
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     self.break_streaming_task_and_rebuild(task='rebuild')
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2823, in break_streaming_task_and_rebuild
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     self.target_node.run_nodetool('rebuild')
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2621, in run_nodetool
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     result = connection.run(**command_kwargs)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > Command: '/usr/bin/nodetool  rebuild '
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
< t:2022-03-20 07:58:18,516 f:nemesis.py      l:3324 c:sdcm.nemesis         p:ERROR > 
```
**Node-3 log:** It turned out, the JMX server on the node was not actually up and running at the time the `nodetool` command had been run. It was ready to receive the connections on 7199 port about 2 minutes later
```
Mar 20 07:58:44 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 scylla-jmx[879]: Starting the JMX server
```
```
Mar 20 08:00:31 gemini-with-nemesis-3h-normal-maste-db-node-7fc9fe63-3 scylla-jmx[879]: JMX is enabled to receive remote connections on port: 7199
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7fc9fe63-d9e9-4a55-9500-9f5606fe74a6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7fc9fe63-d9e9-4a55-9500-9f5606fe74a6)
- Show all stored logs command: `$ hydra investigate show-logs 7fc9fe63-d9e9-4a55-9500-9f5606fe74a6`

## Logs:
- **db-cluster-7fc9fe63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/db-cluster-7fc9fe63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/db-cluster-7fc9fe63.tar.gz)
- **monitor-set-7fc9fe63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/monitor-set-7fc9fe63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/monitor-set-7fc9fe63.tar.gz)
- **loader-set-7fc9fe63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/loader-set-7fc9fe63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/loader-set-7fc9fe63.tar.gz)
- **sct-runner-7fc9fe63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/sct-runner-7fc9fe63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/sct-runner-7fc9fe63.tar.gz)
- **parallel-timelines-report-7fc9fe63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/parallel-timelines-report-7fc9fe63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7fc9fe63-d9e9-4a55-9500-9f5606fe74a6/20220320_082539/parallel-timelines-report-7fc9fe63.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis-test/311/)

**Comment by fruch** [comment]
looks like the nemesis is calling the wrong api call, should be calling `start_scylla`/`stop_scylla` functions, and `not start_scylla_server`
```
    @log_run_info
    def start_scylla(self, verify_up=True, verify_down=False, timeout=500):
        self.start_scylla_server(verify_up=verify_up, verify_down=verify_down, timeout=timeout)
        if verify_up:
            self.wait_jmx_up(timeout=timeout)
```

but question is why the JMX has stopped at all ? maybe it crashed ?
