### ISSUE TITLE
Random timeout error in rolling-upgrade tests

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4552]
Rolling upgrade tests randomly fail due timeout error.
The test time usually varies between 4h to 5.5h (usually close to 5-5.5h), but often fail due timeout (6h).
I tried to deduct something from monitoring (unfortunately restore monitor doesn't work for 5.0, so I had to view only screenshots) and I noticed that load differs quite a lot between tests. E.g. tests that pass, are characterized by much lower disk usage (having 100-200 GB of data) while tests that fail have usually high disk usage (over 400 GB). Also disk fill up process starts at different test times (and has different slope).

examples from rolling-upgrade-ami test, but it is similar for other typical rolling-upgrade tests.

example screenshot from passing test (http://13.48.103.68/test_run/c4be2d3a-4924-49d4-85cf-46890a3a26fb):
![grafana-screenshot-overview-20220305_085029-rolling-upgrade-master-centos-monitor-node-c4be2d3a-1](https://user-images.githubusercontent.com/18242288/159951999-c30166e1-0eb1-4395-b7bd-09bee9f631f3.png)

example screenshot from failing test  (http://13.48.103.68/test_run/b4459dc2-1abb-4ae4-831b-3534e80560ea):
![grafana-screenshot-overview-20220319_103925-rolling-upgrade-master-centos-monitor-node-b4459dc2-1](https://user-images.githubusercontent.com/18242288/159952123-a2bf7402-8e45-439f-b74d-749646acb5d6.png)

we could prolong timeout for this test, but it will only hide the problem.

**Comment by soyacz** [comment]
13:05:12  +-----------------------------------------------------------------------------------------------------------------------------------------------+
13:05:12  |                                        Collected logs by test-id: b4459dc2-1abb-4ae4-831b-3534e80560ea                                        |
13:05:12  +-------------+---------------------------------------------------------------------------------------------------------------------------------+
13:05:12  | Cluster set | Link                                                                                                                            |
13:05:12  +-------------+---------------------------------------------------------------------------------------------------------------------------------+
13:05:12  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/b4459dc2-1abb-4ae4-831b-3534e80560ea/20220319_105208/db-cluster-b4459dc2.tar.gz  |
13:05:12  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/b4459dc2-1abb-4ae4-831b-3534e80560ea/20220319_105208/monitor-set-b4459dc2.tar.gz |
13:05:12  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/b4459dc2-1abb-4ae4-831b-3534e80560ea/20220319_105208/loader-set-b4459dc2.tar.gz  |
13:05:12  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/b4459dc2-1abb-4ae4-831b-3534e80560ea/20220319_105208/sct-runner-b4459dc2.tar.gz  |
13:05:12  +-------------+---------------------------------------------------------------------------------------------------------------------------------+

**Comment by ShlomiBalalis** [comment]
@fruch I'll open a corrisponding issue in scylla, then.

**Comment by bentsi** [comment]
@ShlomiBalalis did you open an issue?

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis did you open an issue?

I did not. Opened one now: https://github.com/scylladb/scylla/issues/10322

**Comment by soyacz** [comment]
I've investigated the issue more deeply. I've found out that for certain gemini seed values, gemini is causing very high disk usage (sometimes it is even 0.5 TB). When this happens upgrade tests are failing due timeout errors (high disk usage prolongs all the compactions, also disks are fully utilized during gemini, making everything to work more slowly).

I see 2 solutions:
1. fix `gemini_seed` for rolling upgrade jobs (we can select some from historical executions that are creating acceptable load)
2. Fix gemini... I don't know if we have such capability and if this is actual bug in gemini.

@fruch @ShlomiBalalis @roydahan what do you think?

**Comment by roydahan** [comment]
@soyacz on what branch is it?
We (me and Fabio) already investigated this and found out that latest changes like the Gemini load and the cdc stresser (IIRC) introduced randomness that we don't want in these tests.
@fgelcer should have sent (or already sent) a fix to remove all these commands (including Gemini) from the rolling-upgrades.

**Comment by soyacz** [comment]
@roydahan this problem exists on 5.0/2022.1 branches and possibly on master (if there was no fix recently for this).

**Comment by roydahan** [comment]
I thought we removed the gemini-cmd completely from the test.
For now, we will pick a gemini seed that we know that should pass on this test and set it as part of the "gemini_cmd" for this test.
