### ISSUE TITLE
longevity-10gb-3h-scylla-debug-test in master fails 

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#4577]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: aed2807e52b56f6774156d9a030be4d0fb24e302
* **scylla**: ami-0c0ea78929cddded3

### Logs
* test_id: be24a280-4f8c-40e6-82b2-dec406c0f52a
* job log: [Jenkins Console](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-scylla-debug-test/138/consoleFull)

```log
 < t:2022-03-30 09:57:46,354 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-30 09:57:46.352: (TestFrameworkEvent Severity.CRITICAL) period_type=one-time event_id=877d4542-91c7-4b64-8aa8-f0c5909bdc4e, source=ScyllaAWSCluster.update_scylla_packages() message=Did not get the right packages for this distro
```

### Description

Longevity test of scylla debug build keeps stopping with this error

### Steps to Reproduce

1. Start the job
2. Wait until node configuration starts
3. See the error

**Expected behavior:** Text continues as normal

**Actual behavior:** `Did not get the right packages for this distro` error is produced, test ends abruptly

**Comment by fgelcer** [comment]
https://github.com/scylladb/scylla-pkg/issues/2836
