### ISSUE TITLE
[2022.1] rolling-upgrade tests fail while trying to read a non-exists repo file - test failed to get the base_versions

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#4581]
### Description
The 2022.1 rolling-upgrade tests fail while trying to read a non-exists repo file [0],
Following a quick ingestion with @ShlomiBalalis - the `base_versions` is empty

test must print proper error messages in case it fails to calculate (a.k.a. auto mode) the `base_versions`.
logs must be improved, and IMHO the whole pipeline can be stopped at this point, as if we don't have any `base_version` to upgrade, it is worthless and confusion to continue with the "next" stages of the pipeline.

### Steps to Reproduce
1. Trigger one of 2022.1 rolling-upgrade tests with empty `based_versions`

Example failure [1]
Example issue-verification with `base_versions = 2021.1`

[0] http://downloads.scylladb.com/downloads/scylla-enterprise/rpm/centos/scylla-enterprise-2022.1/noarch/repodata/repomd.xml
[1] https://jenkins.scylladb.com/view/nexts/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-centos7-test/2/
[2] https://jenkins.scylladb.com/view/nexts/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-centos7-test/3/

**Comment by rayakurl** [comment]
@KnifeyMoloko - please handle. thanks

**Comment by KnifeyMoloko** [comment]
@benipeled I can't reproduce this issue - running an upgrade job for 2022.1 with empty `base_versions` seems to work fine now: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-rolling-upgrade-centos-07-base-version-fix/14 Possibly Fabio's fix resolved the underlying issue.

As for proper log messages, I can see we got: 
`The following repository URL 'http://downloads.scylladb.com/downloads/scylla-enterprise/rpm/centos/scylla-enterprise-2022.1/x86_64/repodata/repomd.xml' is incorrect`
in the logs, plus info that the shell script failed in `supportedUpgradeFromVersions` along with it's `stderr` output, which is what is needed for debugging any script-related issues. Could you elaborate on what you would want to see in the logs instead? 

The pipeline in [2] also failed pretty much right after failing to get the list of supported upgrade versions and didn't run any stages in the `Run SCT stages'`. I can add a defensive try / catch block with an `error` call to abort the whole thing at the point the script fails.

**Comment by benipeled** [comment]
> @benipeled I can't reproduce this issue - running an upgrade job for 2022.1 with empty `base_versions` seems to work fine now: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-rolling-upgrade-centos-07-base-version-fix/14 Possibly Fabio's fix resolved the underlying issue.

Probably because
1. The issue was reported when we have no rc* for 2022.1 which cause a failure on an attempt to use the final target location which of course does not exist.
2. There was an issue with the repo path - fixed.

> As for proper log messages, I can see we got: `The following repository URL 'http://downloads.scylladb.com/downloads/scylla-enterprise/rpm/centos/scylla-enterprise-2022.1/x86_64/repodata/repomd.xml' is incorrect` in the logs, plus info that the shell script failed in `supportedUpgradeFromVersions` along with it's `stderr` output, which is what is needed for debugging any script-related issues. Could you elaborate on what you would want to see in the logs instead?

Same here, it's a rare case of the first release when the final-target repo doesn't exist yet - so the log is inaccurate but you're right that we can catch it with the current logs,

Thanks for the investigation!
Closing the issue.

**Comment by fgelcer** [comment]
the idea here was to improve the logging inside the function that calculates the `base_versions`, so in case there is a failure, we will have a good log, and it will fail the whole pipeline (doesn't need to continue running in this case).
