### ISSUE TITLE
`nodetool decomission` causes compaction to stop and emit an error message

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#4612]
Maybe this message should be added to filtered ones? It happened during `disrupt_nodetool_decommission` nemesis and nemesis itself succeeded.

db-log:
```
2022-04-17 04:44:07.464 <2022-04-17 04:44:07.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=fd53bc7d-c431-417d-903b-c782d4f71e15: type=DATABASE_ERROR regex=Exception  line_number=177824 node=longevity-10gb-3h-master-db-node-edf14c08-1
2022-04-17T04:44:07+00:00 longevity-10gb-3h-master-db-node-edf14c08-1 !    INFO |  [shard 10] compaction - [Compact keyspace1.standard1 ff8f7410-be08-11ec-bb84-9e41a244758f] Compacting of 2 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for keyspace1/standard1 was stopped due to: user-triggered operation)
```

## Installation details

Kernel Version: 5.13.0-1021-aws

Scylla version (or git commit hash): `5.1.dev-20220415.75786c42cb2e` with build-id `624bf766a24fba740b118c805912a1b94df59dc5`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-edf14c08-7 (54.75.59.173 | 10.0.3.132) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-6 (54.246.76.57 | 10.0.0.216) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-5 (3.251.70.147 | 10.0.0.252) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-4 (52.214.115.229 | 10.0.0.159) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-3 (34.248.119.141 | 10.0.2.2) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-2 (54.75.1.104 | 10.0.1.122) (shards: 14)
- longevity-10gb-3h-master-db-node-edf14c08-1 (54.220.222.183 | 10.0.2.202) (shards: 14)

OS / Image: `ami-0ac9cc9b9c7b1a0f0` (aws: eu-west-1)

Test id: `edf14c08-7a3e-4ccc-a612-018b35e154fa`

Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1db1271a4a1de09f1d87b1f43e367e8cedca2af1/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor edf14c08-7a3e-4ccc-a612-018b35e154fa`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=edf14c08-7a3e-4ccc-a612-018b35e154fa)
- Show all stored logs command: `$ hydra investigate show-logs edf14c08-7a3e-4ccc-a612-018b35e154fa`

## Logs:
- **db-cluster-edf14c08.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/db-cluster-edf14c08.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/db-cluster-edf14c08.tar.gz)
- **monitor-set-edf14c08.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/monitor-set-edf14c08.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/monitor-set-edf14c08.tar.gz)
- **loader-set-edf14c08.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/loader-set-edf14c08.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/loader-set-edf14c08.tar.gz)
- **normal-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/normal-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/normal-edf14c08.log.tar.gz)
- **summary-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/summary-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/summary-edf14c08.log.tar.gz)
- **events-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/events-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/events-edf14c08.log.tar.gz)
- **output-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/output-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/output-edf14c08.log.tar.gz)
- **debug-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/debug-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/debug-edf14c08.log.tar.gz)
- **sct-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/sct-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/sct-edf14c08.log.tar.gz)
- **error-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/error-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/error-edf14c08.log.tar.gz)
- **critical-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/critical-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/critical-edf14c08.log.tar.gz)
- **raw_events-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/raw_events-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/raw_events-edf14c08.log.tar.gz)
- **warning-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/warning-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/warning-edf14c08.log.tar.gz)
- **email_data-edf14c08.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/email_data-edf14c08.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/email_data-edf14c08.json.tar.gz)
- **argus-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/argus-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/argus-edf14c08.log.tar.gz)
- **left_processes-edf14c08.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/left_processes-edf14c08.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/left_processes-edf14c08.log.tar.gz)
- **parallel-timelines-report-edf14c08.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/parallel-timelines-report-edf14c08.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edf14c08-7a3e-4ccc-a612-018b35e154fa/20220417_070418/parallel-timelines-report-edf14c08.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/472/)

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/4592 was supposed to squelch those errors, @fgelcer do you know why it's not working ?

**Comment by fruch** [comment]
I think https://github.com/scylladb/scylla-cluster-tests/pull/4633 would fix the issue
