### ISSUE TITLE
KeyError: 'cassandra_fio_lcs_64k_read' during `.setUp()`

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#4613]
looks like certain fio results are not being saved / saved into a wrong directory, leading to this error:
```
< t:2022-04-15 05:57:05,220 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > cat: /home/ubuntu/cassandra-fio/reports/lcs.64k.fio.json: No such file or directory
< t:2022-04-15 05:57:05,220 f:benchmarks.py   l:305  c:sdcm.utils.benchmarks p:WARNING > Failed to get cassandra-fio result for node longevity-10gb-3h-master-db-node-f8f869f9-0-4 with except
ion:
< t:2022-04-15 05:57:05,220 f:benchmarks.py   l:305  c:sdcm.utils.benchmarks p:WARNING > Expecting value: line 1 column 1 (char 0)
< t:2022-04-15 05:57:05,220 f:common.py       l:397  c:utils                p:DEBUG > [ThreadPoolExecutor-5_3] Done.
< t:2022-04-15 05:57:05,259 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > cat: /home/ubuntu/cassandra-fio/reports/lcs.64k.fio.json: No such file or directory
```

```
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 133, in wrapper
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 616, in setUp
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1413, in init_resources
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.get_cluster_gce(loader_info=loader_info, db_info=db_info,
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 811, in get_cluster_gce
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.db_cluster = ScyllaGCECluster(gce_image=gce_image_db,
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 482, in __init__
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3580, in __init__
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(*args, **kwargs)
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 215, in __init__
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(cluster_uuid=cluster_uuid,
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3079, in __init__
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.run_node_benchmarks()
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3448, in run_node_benchmarks
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.node_benchmark_manager.run_benchmarks()
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 125, in run_benchmarks
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self._compare_results()
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 155, in _compare_results
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     cassandra_fio_read_bw=runner.benchmark_results["cassandra_fio_lcs_64k_read"]["read"]["bw"],
< t:2022-04-15 05:57:05,980 f:tester.py       l:140  c:sdcm.tester          p:ERROR > KeyError: 'cassandra_fio_lcs_64k_read'

```

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-f8f869f9-0-6 (34.138.44.200 | 10.142.0.134) (shards: 16)
- longevity-10gb-3h-master-db-node-f8f869f9-0-5 (34.139.127.16 | 10.142.0.133) (shards: 16)
- longevity-10gb-3h-master-db-node-f8f869f9-0-4 (34.148.209.7 | 10.142.0.127) (shards: 16)
- longevity-10gb-3h-master-db-node-f8f869f9-0-3 (35.190.146.172 | 10.142.0.126) (shards: 16)
- longevity-10gb-3h-master-db-node-f8f869f9-0-2 (34.75.166.228 | 10.142.0.123) (shards: 16)
- longevity-10gb-3h-master-db-node-f8f869f9-0-1 (34.75.71.120 | 10.142.0.116) (shards: 16)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/7811778742672769463` (gce: us-east1)
Test id: `f8f869f9-dc28-45b9-a6df-11475092bd05`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1db1271a4a1de09f1d87b1f43e367e8cedca2af1/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor f8f869f9-dc28-45b9-a6df-11475092bd05`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f8f869f9-dc28-45b9-a6df-11475092bd05)
- Show all stored logs command: `$ hydra investigate show-logs f8f869f9-dc28-45b9-a6df-11475092bd05`

## Logs:
- **db-cluster-f8f869f9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/db-cluster-f8f869f9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/db-cluster-f8f869f9.tar.gz)
- **sct-runner-f8f869f9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/sct-runner-f8f869f9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/sct-runner-f8f869f9.tar.gz)
- **parallel-timelines-report-f8f869f9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/parallel-timelines-report-f8f869f9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f8f869f9-dc28-45b9-a6df-11475092bd05/20220415_055810/parallel-timelines-report-f8f869f9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/164/)

**Comment by fgelcer** [comment]
@vponomaryov , wasn't it fixed on #4589 ?

**Comment by vponomaryov** [comment]
> sdcm/utils/benchmarks.py

Looks like there is one more place to apply the same fix.
Before it was done in the "_get_average_results" method.
Now it must also be added to the "_get_average_results" method the same way.
Will do it.

**Comment by vponomaryov** [comment]
Closing because the fix (https://github.com/scylladb/scylla-cluster-tests/pull/4614) has been merged.
