### ISSUE TITLE
`snap: command not found` when trying to install stress-ng

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#4622]
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3310, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3032, in disrupt_memory_stress
    self.target_node.remoter.sudo('snap install stress-ng')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
    return self.run(cmd=cmd,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo snap install stress-ng'

Exit code: 1

Stderr:

sudo: snap: command not found
```

## Installation details

Kernel Version: 5.13.0-1024-gcp
Scylla version (or git commit hash): `5.1.dev-20220420.097fbc7c5dfb` with build-id `511eb4ac91c0a740ea4ee9386d1d969e5fcef1f1`
Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-127b262e-0-9 (34.148.68.231 | 10.142.0.96) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-8 (34.75.228.141 | 10.142.0.88) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-7 (34.139.114.1 | 10.142.0.90) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-6 (34.139.204.94 | 10.142.0.76) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-5 (35.196.75.151 | 10.142.0.75) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-4 (35.196.215.172 | 10.142.0.72) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-3 (34.75.228.141 | 10.142.0.66) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-2 (35.196.238.216 | 10.142.0.64) (shards: 16)
- longevity-10gb-3h-master-db-node-127b262e-0-1 (34.139.223.26 | 10.142.0.61) (shards: 16)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/1230944953122848076` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `127b262e-dbc7-44c8-9d82-ce0af125d18b`
Test name: `scylla-master/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa6ed9c2efde0b25bde7299889b4284a1f15f4a7/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 127b262e-dbc7-44c8-9d82-ce0af125d18b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=127b262e-dbc7-44c8-9d82-ce0af125d18b)
- Show all stored logs command: `$ hydra investigate show-logs 127b262e-dbc7-44c8-9d82-ce0af125d18b`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/166/)

**Comment by fruch** [comment]
cause of https://github.com/scylladb/scylla-machine-image/pull/334 was don't have snapd anymore, we should install it ourselves, during this nemesis:
https://snapcraft.io/install/stress-ng/ubuntu#install

**Comment by k0machi** [comment]
I think we could also just statically build stress-ng and store it in one of the s3 buckets and then download it during the test
