### ISSUE TITLE
disrupt_toggle_table_ics fails with: ValueError: 'DateTieredCompactionStrategy' is not a valid CompactionStrategy

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4632]
failure log:
```
Nemesis Information
Class: Sisyphus
Name: disrupt_toggle_table_ics
Status: Failed
Duration: 57 seconds
Failure reason

                                            Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3307, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2025, in disrupt_toggle_table_ics
    self.toggle_table_ics()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1884, in toggle_table_ics
    cur_compaction_strategy = get_compaction_strategy(node=self.target_node, keyspace=keyspace,
  File "/home/ubuntu/scylla-cluster-tests/test_lib/compaction.py", line 43, in get_compaction_strategy
    compaction = CompactionStrategy.from_str(output_str=dict_compaction_values['class'])
  File "/home/ubuntu/scylla-cluster-tests/test_lib/compaction.py", line 20, in from_str
    return CompactionStrategy[CompactionStrategy(output_str).name]
  File "/usr/local/lib/python3.10/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 701, in __new__
    raise ve_exc
ValueError: 'DateTieredCompactionStrategy' is not a valid CompactionStrategy
```

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 5 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-9 (34.244.29.126 | 10.0.1.33) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-8 (34.242.98.103 | 10.0.0.75) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-7 (34.240.92.121 | 10.0.3.99) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-6 (54.170.130.171 | 10.0.1.93) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-5 (54.229.192.69 | 10.0.3.21) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-4 (34.242.156.216 | 10.0.1.246) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-3 (54.216.104.235 | 10.0.0.97) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-2 (34.248.4.59 | 10.0.1.159) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-16 (52.30.28.24 | 10.0.1.71) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-15 (54.170.135.152 | 10.0.0.80) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-14 (52.31.187.216 | 10.0.0.98) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-13 (3.251.64.59 | 10.0.0.68) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-12 (54.195.190.24 | 10.0.2.101) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-11 (34.250.174.87 | 10.0.1.96) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-10 (18.202.221.213 | 10.0.3.76) (shards: 12)
- longevity-large-partitions-200k-pks-db-node-e9f28ce7-1 (34.243.130.155 | 10.0.1.239) (shards: 12)

OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `longevity-large-partition-200k-pks-4days-test`
Test id: `e9f28ce7-cdee-47f4-8f0a-a75e863c8f46`
Test name: `enterprise-2022.1/longevity/longevity-large-partition-200k-pks-4days-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7f5f150f522fd17c764c1b64e1a8f750c7a8cf18/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor e9f28ce7-cdee-47f4-8f0a-a75e863c8f46`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e9f28ce7-cdee-47f4-8f0a-a75e863c8f46)
- Show all stored logs command: `$ hydra investigate show-logs e9f28ce7-cdee-47f4-8f0a-a75e863c8f46`

## Logs:
- **db-cluster-e9f28ce7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/db-cluster-e9f28ce7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/db-cluster-e9f28ce7.tar.gz)
- **monitor-set-e9f28ce7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/monitor-set-e9f28ce7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/monitor-set-e9f28ce7.tar.gz)
- **loader-set-e9f28ce7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/loader-set-e9f28ce7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/loader-set-e9f28ce7.tar.gz)
- **sct-runner-e9f28ce7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/sct-runner-e9f28ce7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9f28ce7-cdee-47f4-8f0a-a75e863c8f46/20220417_205024/sct-runner-e9f28ce7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-large-partition-200k-pks-4days-test/2/)

**Comment by yarongilor** [comment]
root cause of issue is:
```
< t:2022-04-13 12:14:17,085 f:nemesis.py      l:1510 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: _modify_table_property: ALTER TABLE keyspace1.standard1 WITH compaction = {'class': 'DateTieredCompactionStrategy'};
< t:2022-04-13 12:14:37,807 f:common.py       l:1324 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE keyspace1.standard1 WITH compaction = {'class': 'DateTieredCompactionStrategy'};' ...
< t:2022-04-13 12:14:38,156 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-13T12:14:37+00:00 longevity-large-partitions-200k-pks-db-node-e9f28ce7-5 ! WARNING |  [shard 3] compaction - DateTieredCompactionStrategy is deprecated. Usually cases for which it is used are better handled by TimeWindowCompactionStrategy. Please change your compaction strategy to TWCS as DTCS will be retired in the near future
```

**Comment by yarongilor** [comment]
@raphaelsc , @roydahan can you please advise. is there still some backward compatibility support for DateTieredCompactionStrategy or not in 2021.1 ?

( if not, we can remove it from SCT in: https://github.com/scylladb/scylla-cluster-tests/blob/f6127f678a84847d84fce3b020e2cbcd989588ec/sdcm/nemesis.py#L1918 )

**Comment by yarongilor** [comment]
or, in the oposite case, we can add to _DateTieredCompactionStrategy_ `CompactionStrategy(Enum)`.

**Comment by slivne** [comment]
there is a flag to disable DTCS in scylla.yaml

    , restrict_dtcs(this, "restrict_dtcs", liveness::LiveUpdate, value_status::Used, db::tri_mode_restriction_t::mode::WARN, "Controls whether to prevent setting DateTieredCompactionStrategy. Can be true, false, or warn.")

check if it was set to false

by default its only wanrning.
