### ISSUE TITLE
Cassandra-stress load was started in the same time with Resetlocalschema nemesis and failed with error "No schema agreement from live replicas after 10 s"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4659]
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-2022-1-db-node-926641be-6 (13.48.67.146 | 10.0.0.82) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-926641be-5 (13.48.104.97 | 10.0.2.188) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-926641be-4 (13.48.24.143 | 10.0.2.191) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-926641be-3 (16.16.25.239 | 10.0.0.141) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-926641be-2 (13.51.106.204 | 10.0.2.215) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-926641be-1 (16.170.237.103 | 10.0.0.163) (shards: 14)

OS / Image: `ami-001615890d21c8784` (aws: eu-north-1)

Test: `longevity-mv-si-4days-test`
Test id: `926641be-3a39-4304-86cc-38fc4022ed18`
Test name: `enterprise-2022.1/longevity/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/26669988977199aa81816c32f017be68c3fc0dea/test-cases/longevity/longevity-mv-si-4days.yaml)

## Issue description

Cassandra-stress load was started in the same time with `Resetlocalschema` nemesis and failed with error:
```
No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
```

```
< t:2022-04-28 00:44:10,378 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-28 00:44:10.377: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=9b231a23-a8bf-4e88-a625-95ed4feb598a: node=Node longevity-mv-si-4d-2022-1-loader-node-926641be-1 [16.170.157.151 | 10.0.0.5] (seed: False)
< t:2022-04-28 00:44:10,378 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress user profile=/tmp/c-s_profile_2si_2queries.yaml ops'(insert=10,si_p_read1=1,si_p_read2=1)' cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10

< t:2022-04-28 00:44:12,769 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  resetlocalschema "...
< t:2022-04-28 00:44:12,769 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-28 00:44:12.767: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=b2001a2b-e57e-47e0-b2ae-bb4c893ab999: nodetool_command=resetlocalschema node=longevity-mv-si-4d-2022-1-db-node-926641be-4

< t:2022-04-28 00:44:53,023 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > Warming up si_p_read1 with 0 iterations...
< t:2022-04-28 00:44:53,023 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: WARN  00:44:25,781 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
< t:2022-04-28 00:44:53,023 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  00:44:36,506 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
< t:2022-04-28 00:44:53,024 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-28 00:44:53.023: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=9b231a23-a8bf-4e88-a625-95ed4feb598a duration=42s: node=Node longevity-mv-si-4d-2022-1-loader-node-926641be-1 [16.170.157.151 | 10.0.0.5] (seed: False)
< t:2022-04-28 00:44:53,024 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress user profile=/tmp/c-s_profile_2si_2queries.yaml ops'(insert=10,si_p_read1=1,si_p_read2=1)' cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10
< t:2022-04-28 00:44:53,024 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > errors:
< t:2022-04-28 00:44:53,024 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-04-28 00:44:53,024 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: WARN  00:44:25,781 No schema agreement from live replicas after 10 s. The schema may not be up to da
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 926641be-3a39-4304-86cc-38fc4022ed18`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=926641be-3a39-4304-86cc-38fc4022ed18)
- Show all stored logs command: `$ hydra investigate show-logs 926641be-3a39-4304-86cc-38fc4022ed18`

## Logs:
- **db-cluster-926641be.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/db-cluster-926641be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/db-cluster-926641be.tar.gz)
- **monitor-set-926641be.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/monitor-set-926641be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/monitor-set-926641be.tar.gz)
- **loader-set-926641be.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/loader-set-926641be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/loader-set-926641be.tar.gz)
- **sct-runner-926641be.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/sct-runner-926641be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/926641be-3a39-4304-86cc-38fc4022ed18/20220428_010618/sct-runner-926641be.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-mv-si-4days-test/3/)

**Comment by fruch** [comment]
@juliayakovlev isn't this a scylla issue ? sound like only node is effected by this command,  but it shouldn't take so much time to recover...

**Comment by juliayakovlev** [comment]
@fruch I do not think so. Because c-s command was started at `00:44:10,378` and reset schema - at `00:44:12,769`. C-s warmup failed at `00:44:53,023`. So c-s tried to warmup exactly in same time when reset was performed.
