### ISSUE TITLE
Sudo snap install stress-ng failed during MemoryStress

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4665]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220421.cc40685c288f` with build-id `fde9a351743afef6ce27c7787712211d9ee8f41f`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-acecfe6e-9 (54.194.242.138 | 10.0.1.123) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-8 (34.243.183.187 | 10.0.0.144) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-7 (34.240.111.77 | 10.0.3.13) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-6 (18.202.225.136 | 10.0.0.71) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-5 (52.215.235.205 | 10.0.2.81) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-4 (34.244.12.198 | 10.0.1.34) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-3 (34.242.229.178 | 10.0.0.33) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-2 (52.208.144.39 | 10.0.3.200) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-1 (34.243.226.229 | 10.0.3.228) (shards: 8)

OS / Image: `ami-07d353a9e8649b3a1` (aws: eu-west-1)

Test: `longevity-twcs-48h-test`
Test id: `acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
During MemoryStress nemesis the `sudo snap install stress-ng` command failed, apparently due to `snap` not being present on the node.
```
                                            Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3309, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3031, in disrupt_memory_stress
    self.target_node.remoter.sudo('snap install stress-ng')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
    return self.run(cmd=cmd,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo snap install stress-ng'

Exit code: 1

Stdout:



Stderr:

sudo: snap: command not found
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=acecfe6e-3e7b-436a-9f53-023a9d25b9ee)
- Show all stored logs command: `$ hydra investigate show-logs acecfe6e-3e7b-436a-9f53-023a9d25b9ee`

## Logs:
- **db-cluster-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz)
- **monitor-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz)
- **loader-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz)
- **normal-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz)
- **summary-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz)
- **events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz)
- **output-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz)
- **debug-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz)
- **sct-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz)
- **error-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz)
- **critical-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz)
- **raw_events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz)
- **warning-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz)
- **email_data-acecfe6e.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz)
- **argus-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz)
- **left_processes-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/29/)

**Comment by fruch** [comment]
Was fixed by #4634
