### ISSUE TITLE
Hard reboot not triggering during MultipleHardReboot

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4677]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220428.333fdcb3f544` with build-id `415dea72992f5c04c11c4171a5b878d2e1c48fa9`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-0b394e0c-9 (54.217.53.62 | 10.0.1.39) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-8 (54.154.185.76 | 10.0.1.49) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-7 (34.245.123.219 | 10.0.3.213) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-6 (34.246.177.144 | 10.0.1.212) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-5 (54.170.241.166 | 10.0.1.177) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-4 (3.250.227.113 | 10.0.3.196) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-3 (34.244.157.128 | 10.0.2.122) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-23 (54.217.23.250 | 10.0.3.120) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-22 (176.34.145.73 | 10.0.1.83) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-21 (34.246.182.232 | 10.0.1.45) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-20 (54.246.160.249 | 10.0.1.168) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-2 (54.154.157.131 | 10.0.1.81) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-19 (54.217.44.110 | 10.0.3.236) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-18 (54.194.47.81 | 10.0.1.96) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-17 (34.242.77.34 | 10.0.3.181) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-16 (176.34.145.249 | 10.0.3.102) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-15 (52.16.19.172 | 10.0.0.248) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-14 (34.250.243.148 | 10.0.1.101) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-13 (34.250.252.190 | 10.0.3.174) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-12 (54.154.122.188 | 10.0.1.218) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-11 (54.195.139.136 | 10.0.2.246) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-10 (34.252.148.182 | 10.0.2.219) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-0b394e0c-1 (54.228.86.52 | 10.0.2.107) (shards: 14)

OS / Image: `ami-0bad52798af1cde66` (aws: eu-west-1)

Test: `longevity-50gb-3days`
Test id: `0b394e0c-bc90-4475-a4ab-f7a219a4c91f`
Test name: `scylla-master/longevity/longevity-50gb-3days`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3615a6c5d451a30d2929dd1593784ba7c643783f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

**>>>>>>>**
During `MultipleHardReboot` nemesis we reboot the instance and check it's uptime to see that it changed. In this run the uptime value stayed the same for >45 minutes. Other reboots in the same run did not bump into this issue.

```
2022-04-30 01:27:14.763: (DisruptionEvent Severity.ERROR) period_type=end event_id=9527fffe-27bc-4ea8-89ca-c2b583569bdc duration=50m26s: nemesis_name=MultipleHardRebootNode target_node=Node longevity-tls-50gb-3d-master-db-node-0b394e0c-16 [176.34.145.249 | 10.0.3.102] (seed: False) errors=RetryError[Wait for: uptime_changed: timeout - 2700 seconds - expired]
```

Node logs:
```
Apr 30 00:37:25 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 scylla[32699]:  [shard 0] init - Scylla version 5.1.dev-0.20220428.333fdcb3f544 shutdown complete.
Apr 30 00:38:27 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: scylla-server.service: Succeeded.
Apr 30 00:38:27 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: Stopped Scylla Server.
Apr 30 00:38:27 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: scylla-image-setup.service: Succeeded.
Apr 30 00:38:27 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: Stopped Scylla Cloud Image Setup service.
-- Reboot --
Apr 30 00:39:22 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: Condition check resulted in Scylla Cloud Image Setup service being skipped.
Apr 30 00:39:22 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 systemd[1]: Starting Scylla Server...
Apr 30 00:39:24 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 scylla_prepare[823]: File /etc/default/irqbalance.scylla.orig already exists - not overwriting.
Apr 30 00:39:24 longevity-tls-50gb-3d-master-db-node-0b394e0c-16 scylla_prepare[823]: Restarting irqbalance: going to ban the following IRQ numbers: 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 216, 217, 215, 212, 214, 213, 218, 211 ...
```
After this there are no further attempts at rebooting the node, even though `sct.log` claims otherwise.

From `sct.log`:
```
< t:2022-04-30 00:42:09,371 f:nemesis.py      l:614  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Rebooting 2 out of 6 times
< t:2022-04-30 00:42:09,371 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "uptime -s"...
< t:2022-04-30 00:42:09,380 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022-04-30 00:39:14 
< t:2022-04-30 00:42:09,881 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "uptime -s" finished with status 0 
< t:2022-04-30 00:42:09,881 f:cluster.py      l:1062 c:sdcm.cluster_aws     p:DEBUG > Node longevity-tls-50gb-3d-master-db-node-0b394e0c-16 [176.34.145.249 | 10.0.3.102] (seed: False): Hardly rebooting node
< t:2022-04-30 00:42:09,882 f:connectionpool.py l:273  c:urllib3.connectionpool p:DEBUG > Resetting dropped connection: ec2.eu-west-1.amazonaws.com
...
...
...
< t:2022-04-30 01:27:04,243 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "uptime -s" finished with status 0
< t:2022-04-30 01:27:04,243 f:wait.py         l:49   c:sdcm.wait            p:DEBUG > wait_for: Retrying uptime_changed: attempt 264 ended with: False
```

This results in the following error:
```
2022-04-30 01:27:14.763: (DisruptionEvent Severity.ERROR) period_type=end event_id=9527fffe-27bc-4ea8-89ca-c2b583569bdc duration=50m26s: nemesis_name=MultipleHardRebootNode target_node=Node longevity-tls-50gb-3d-master-db-node-0b394e0c-16 [176.34.145.249 | 10.0.3.102] (seed: False) errors=RetryError[Wait for: uptime_changed: timeout - 2700 seconds - expired]
```

This might be the same issue as: https://github.com/scylladb/scylla-cluster-tests/issues/1503
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0b394e0c-bc90-4475-a4ab-f7a219a4c91f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0b394e0c-bc90-4475-a4ab-f7a219a4c91f)
- Show all stored logs command: `$ hydra investigate show-logs 0b394e0c-bc90-4475-a4ab-f7a219a4c91f`

## Logs:
- **db-cluster-0b394e0c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/db-cluster-0b394e0c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/db-cluster-0b394e0c.tar.gz)
- **monitor-set-0b394e0c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/monitor-set-0b394e0c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/monitor-set-0b394e0c.tar.gz)
- **loader-set-0b394e0c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/loader-set-0b394e0c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/loader-set-0b394e0c.tar.gz)
- **normal-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/normal-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/normal-0b394e0c.log.tar.gz)
- **summary-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/summary-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/summary-0b394e0c.log.tar.gz)
- **events-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/events-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/events-0b394e0c.log.tar.gz)
- **output-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/output-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/output-0b394e0c.log.tar.gz)
- **debug-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/debug-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/debug-0b394e0c.log.tar.gz)
- **sct-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/sct-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/sct-0b394e0c.log.tar.gz)
- **error-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/error-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/error-0b394e0c.log.tar.gz)
- **critical-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/critical-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/critical-0b394e0c.log.tar.gz)
- **raw_events-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/raw_events-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/raw_events-0b394e0c.log.tar.gz)
- **warning-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/warning-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/warning-0b394e0c.log.tar.gz)
- **email_data-0b394e0c.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/email_data-0b394e0c.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/email_data-0b394e0c.json.tar.gz)
- **argus-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/argus-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/argus-0b394e0c.log.tar.gz)
- **left_processes-0b394e0c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/left_processes-0b394e0c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0b394e0c-bc90-4475-a4ab-f7a219a4c91f/20220430_083527/left_processes-0b394e0c.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/134/)

**Comment by fruch** [comment]
Seems like AWS got the request to reboot, but it didn't excecute/worked:
https://eu-west-1.console.aws.amazon.com/cloudtrail/home?region=eu-west-1#/events?ResourceType=AWS::EC2::Instance&StartTime=2022-04-30T00:30:00.000Z&EndTime=2022-04-30T00:44:00.000Z

Sounds like an AWS issue to me

**Comment by soyacz** [comment]
Similar issue happened on Azure, where during restart we clearly see db activity in logs stopped (I believe node got restarted) but SCT couldn't detect this restart.
```
tenacity.RetryError: RetryError[Wait for: uptime_changed: timeout - 2700 seconds - expired]
```
According to events log in Azure, restart took ~17 mins, but in logs we can see 30 sec's gap between last db activity and next log line:
```
2022-09-08T05:32:31+00:00 longevity-10gb-3h-5-0-db-node-eastus-6 !    INFO |  [shard 6] compaction - [Compact keyspace1.standard1 a22c6a80-2f37-11ed-bba6-d218ef953273] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-002c97002f1e11ed804c27247235371d/md-2174-big-Data.db:level=0]. 14MB to 8MB (~56% of original) in 466ms = 17MB/s. ~56704 total partitions merged to 32580.
2022-09-08T05:32:31+00:00 longevity-10gb-3h-5-0-db-node-eastus-6 !    INFO |  [shard 7] compaction - [Compact keyspace1.standard1 a24856f0-2f37-11ed-8c33-d213ef953273] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-002c97002f1e11ed804c27247235371d/md-2175-big-Data.db:level=0]. 14MB to 8MB (~56% of original) in 467ms = 17MB/s. ~56576 total partitions merged to 32601.
2022-09-08T05:33:00+00:00 longevity-10gb-3h-5-0-db-node-eastus-6 !    INFO | {"L":"INFO","T":"2022-09-08T05:33:00.003Z","N":"http","M":"GET /storage_service/host_id","from":"10.0.0.13:54730","status":200,"bytes":417,"duration":"0ms"}
2022-09-08T05:33:00+00:00 longevity-10gb-3h-5-0-db-node-eastus-6 !    INFO | {"L":"INFO","T":"2022-09-08T05:33:00.008Z","N":"http","M":"GET /storage_service/scylla_release_version","from":"10.0.0.13:54730","status":200,"bytes":28,"duration":"0ms"}

```
## Installation details

Kernel Version: 5.15.0-1019-azure
Scylla version (or git commit hash): `5.0.3-20220907.b9a61c8e9` with build-id `7be266d2954825cdf843c744de04a0443a8f156c`

Cluster size: 6 nodes (Standard_L8s_v2)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-8 (13.92.155.100 | 10.0.0.14) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-7 (40.87.53.170 | 10.0.0.14) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-6 (52.255.203.180 | 10.0.0.10) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-5 (52.255.170.241 | 10.0.0.9) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-4 (20.232.42.211 | 10.0.0.8) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-3 (20.231.196.73 | 10.0.0.7) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-2 (20.25.80.233 | 10.0.0.6) (shards: 8)
- longevity-10gb-3h-5-0-db-node-28e91d4f-eastus-1 (20.185.223.11 | 10.0.0.5) (shards: 8)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.0.3-x86_64-2022-09-07T23-52-03Z` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `28e91d4f-f229-409d-bcd4-41e4041bb9ff`
Test name: `scylla-5.0/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/92d756c21a9cb6c111c8423963968b07020a687b/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 28e91d4f-f229-409d-bcd4-41e4041bb9ff`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=28e91d4f-f229-409d-bcd4-41e4041bb9ff)
- Show all stored logs command: `$ hydra investigate show-logs 28e91d4f-f229-409d-bcd4-41e4041bb9ff`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-10gb-3h-azure-test/12/)

**Comment by fruch** [comment]
@soyacz this doesn't sound related to the issue @KnifeyMoloko was facing, there I've clearly showed that it was AWS issue that didn't rebooted the machine.

in your case what was the uptime ? i.e. SCT cause is waiting for uptime to change.

anyhow I would open a different issue, and close this one, they are not the same

**Comment by soyacz** [comment]
True, issue is somewhere else. I'll open another one.
Regarding this one - maybe we could solve it by proper protection against AWS issue?

**Comment by fruch** [comment]
> True, issue is somewhere else. I'll open another one. Regarding this one - maybe we could solve it by proper protection against AWS issue?

`proper protection` from what exactly ? we are checking uptime to make sure the boot happened, if AWS got a request but never executed it, how would we know, and what exactly we should do ?

**Comment by soyacz** [comment]
> > True, issue is somewhere else. I'll open another one. Regarding this one - maybe we could solve it by proper protection against AWS issue?
> 
> `proper protection` from what exactly ? we are checking uptime to make sure the boot happened, if AWS got a request but never executed it, how would we know, and what exactly we should do ?

Protection from not triggering reboot. Maybe there's some way to find out instance didn't get reboot request?

**Comment by fruch** [comment]
> > > True, issue is somewhere else. I'll open another one. Regarding this one - maybe we could solve it by proper protection against AWS issue?
> > 
> > 
> > `proper protection` from what exactly ? we are checking uptime to make sure the boot happened, if AWS got a request but never executed it, how would we know, and what exactly we should do ?
> 
> Protection from not triggering reboot. Maybe there's some way to find out instance didn't get reboot request?

This specific thing, happened once as far as we know, I don't think it's worth our while to chase it. if it would start happening more often it might worth the attention, meanwhile I would leave it.

**Comment by KnifeyMoloko** [comment]
We didn't see this reproducing - closing this issue.
