### ISSUE TITLE
Gemini Test fails with 'Validation failed: rows differ'

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#4693]
## Installation details

Kernel Version: 5.13.0-1019-aws
Scylla version (or git commit hash): `5.1.dev-20220317.c45050895403` with build-id `076f513b6143670def988c7626389b270411f8f7`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-64d7e14c-1 (54.154.140.227 | 10.0.1.161) (shards: 14)
- gemini-1tb-10h-master-db-node-64d7e14c-3 (3.250.164.11 | 10.0.1.88) (shards: 14)
- gemini-1tb-10h-master-db-node-64d7e14c-2 (34.250.178.204 | 10.0.3.79) (shards: 14)
- gemini-1tb-10h-master-db-node-64d7e14c-1 (34.245.131.62 | 10.0.0.57) (shards: 14)

OS / Image: `ami-0d27db767997d0ec4` (aws: eu-west-1)

Test: `gemini-1tb-10h`
Test id: `64d7e14c-b7cb-45ea-930c-aea2cd8a81c0`
Test name: `gemini/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cf1a7533b0af12a4484921aa18db289b82b4f94/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description
Gemini test fails on initial preparation with this error:
```
2022-03-25 06:02:42.187: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=9a4a8e2b-5582-4303-80c4-b8aba068ef59, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 19720831, 'write_errors': 0, 'read_ops': 5, 'read_errors': 1, 'errors': [{'timestamp': '2022-03-25T05:35:35.798586012Z', 'message': 'Validation failed: rows differ (-map[ck0:1623649325 ck1:175.75.124.199 ck2:[51 49 51 48 51 56 54 50 51 56 54 102 52 51 55 48 51 51 51 49 51 49 55 50 51 50 52 54 53 50 55 51 51 48 54 55 52 53 51 48 51 48 55 48 53 54 53 97 51 48 54 55 53 55 55 50 51 54 53 52 55 53 51 56 54 55 54 57 54 55 51 55 53 97 51 53 53 97 55 56 54 100 52 53 55 56 51 53 54 101 51 48 51 52 52 102 50 98 51 53 52 55 54 101 55 52 53 53 54 56 51 56 51 56 54 53 55 97 55 53 55 54 55 52 51 53 53 50 54 53 52 99 51 48 53 50 52 98 54 97 55 54 54 53 53 54 52 54 51 48 53 51 52 50 52 98 53 54 52 52 55 52 52 97 54 56 54 52 54 99 54 98 54 99 55 52 54 52 53 55 54 51 53 57 52 100 53 48 55 48 55 57 55 48 52 56 52 50 55 48 52 50 53 57 55 54 54 50 52 98 54 50 54 55 54 49 52 99 54 99 54 57 53 55 52 99 55 51 54 49 52 100 53 97 54 102 55 53 53 54 51 56 53 52 55 50 52 99 51 50 55 55 55 51 53 53 53 48 52 49 52 56 55 49 54 52 54 55 54 99 54 52 54 53 52 57 53 48 53 57 53 56 53 97 51 50 51 49 55 49 52 51 55 52 54 57 55 53 55 54 54 56 53 52 52 52 51 48 54 54 55 53 52 98 51 48 52 101 52 55 52 57 55 51 55 97 51 57 53 49 52 102 52 54 51 49 53 48 54 99 54 55 55 52 52 102 53 54 52 97 51 49 54 57 55 50 54 97 55 53 54 101 51 56 50 98 50 98 52 51 55 52 53 52 51 54 52 49 52 50 52 50 55 52 53 48 55 56 52 101 53 52 52 50 55 56 51 49 55 49 51 53 52 52 54 56 52 51 54 54 52 52 51 49 51 49 53 51 54 57 53 54 55 54 52 54 53 56 51 51 54 100 54 53 54 99 52 57 55 53 54 50 50 102 54 102 52 51 53 54 51 56 52 102 52 56 53 48 53 48 52 53 54 97 53 97 54 51 54 50 55 97 52 51 52 97 55 97 54 97 54 56 51 53 55 49 52 98 52 102 55 50 52 100 52 102 54 55 52 100 54 51 5
<...>
0x35, 0x33, 0x35, 0x35, 0x35, 0x32, 0x35, 0x61, 0x36, 0x37, 0x35, 0x33, 0x33, 0x38, 0x35, 0x30, 0x32, 0x66, 0x36, 0x32, 0x36, 0x33, 0x34, 0x31, 0x33, 0x34, 0x34, 0x62, 0x36, 0x64, 0x33, 0x38, 0x36, 0x32, 0x36, 0x37, 0x37, 0x34, 0x36, 0x32, 0x34, 0x36, 0x36, 0x61, 0x33, 0x38, 0x36, 0x35, 0x36, 0x63, 0x36, 0x63, 0x33, 0x31, 0x34, 0x34, 0x34, 0x61, 0x35, 0x30, 0x33, 0x34, 0x35, 0x33, 0x33, 0x36, 0x32, 0x66, 0x34, 0x62, 0x34, 0x66, 0x35, 0x32, 0x34, 0x31, 0x33, 0x30, 0x36, 0x63},\n  \t"col0": string("YzJGgQ1YVVZlDuMRCznIwZlZnyZLDuTceSVKFDt+Q2FM1JsmqORFj3d+RZkT9P75P+fgmApHmIIn5Kf7TR1mYhEfqiIV+8ZkWZazyycLs3Q8i7y/yN6FcHHnvUCUh7mxKsYUh15lFLCzrRY362oYCGYGb4/5yrIM5qKFm+wei/K1Nb5z3m58kcr7vFBs9I3WbYfnK3eUPq+6on3c0LgP+lNAFR+LacDmuK1zZHCOh5RvsJ/cjBkBt5NKTdxzQ9mjpNCW1hl135O6cDEaEdchFO7OU1fbQD1M1AGylmbTL2dbQeUHUkU72ZnXtGgaxRmRyWMb3+VjsSgcSX1kGh9BsrcgkHhybljNRUksCagnzlHWcZqFLowBp/zh8GFBL6vWs+965skSmVlTeJUmTQkXb6qwgvZZyadKaONOhNayQ"),\n  \t"col1": map[*big.Int]gocql.UUID{\n+ \t\ts"1930848517341852946": s"654dec80-2b26-11ec-8054-0aeeec2aead5",\n+ \t\ts"8854144879374200533": s"f4ddbc80-51f4-11e4-8053-0aeeec2aead5",\n+ \t\ts"9002083867250139895": s"a9532280-24fd-11d3-8052-0aeeec2aead5",\n- \t\ts"1930848517341852946": s"654dec80-2b26-11ec-8054-0aeeec2aead5",\n- \t\ts"8854144879374200533": s"f4ddbc80-51f4-11e4-8053-0aeeec2aead5",\n- \t\ts"9002083867250139895": s"a9532280-24fd-11d3-8052-0aeeec2aead5",\n  \t},\n  \t"col10": int8(-15),\n  \t"col2":  []*inf.Dec{s"642412285482980.875", s"1962561751704345.753", s"7289442058512851.898", s"8720640460457683.257"},\n  \t... // 28 identical entries\n  }\n', 'query': 'SELECT * FROM ks1.table1 WHERE pk0=1765255319 AND pk1=1374497009476053232 AND pk2=307542468 AND pk3=-93 AND ck0>1211557281 AND ck0<1644139677 '}]}]
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 64d7e14c-b7cb-45ea-930c-aea2cd8a81c0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=64d7e14c-b7cb-45ea-930c-aea2cd8a81c0)
- Show all stored logs command: `$ hydra investigate show-logs 64d7e14c-b7cb-45ea-930c-aea2cd8a81c0`

## Logs:
- **db-cluster-64d7e14c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/db-cluster-64d7e14c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/db-cluster-64d7e14c.tar.gz)
- **monitor-set-64d7e14c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/monitor-set-64d7e14c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/monitor-set-64d7e14c.tar.gz)
- **loader-set-64d7e14c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/loader-set-64d7e14c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/loader-set-64d7e14c.tar.gz)
- **sct-runner-64d7e14c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/sct-runner-64d7e14c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/64d7e14c-b7cb-45ea-930c-aea2cd8a81c0/20220325_061438/sct-runner-64d7e14c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/150/)

**Comment by roydahan** [comment]
Same comment as in: https://github.com/scylladb/scylla-cluster-tests/issues/4692#issuecomment-1117188238
