### ISSUE TITLE
Grafana snapshots doesn't work on our dashaboard

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#470]
Error getting in developer webtools:

Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
scylla-per-server-metrics-nemesis-master?from=now-1h&to=now:1 Failed to load https://snapshots-origin.raintank.io/api/snapshots: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://35.190.136.105:3000' is therefore not allowed access. The response had HTTP status code 413.

**Comment by amoskong** [comment]
It's an access error of crossing domain. I didn't see this error in console of developer tools.

<img width="1209" alt="wx20180117-103804 2x" src="https://user-images.githubusercontent.com/309708/35022769-a0ff7966-fb72-11e7-984f-2f1c13786490.png">


Did you do some special operations? or just open `http://35.190.136.105:3000/dashboard/db/scylla-per-server-metrics-nemesis-master?from=now-1h&to=now`

**Comment by amoskong** [comment]
Similar Grafana issue: https://github.com/grafana/grafana/issues/4778
It had been fixed in `3.0.0-beta6`

But current SCT uses grafana-3.1.1-1470047149.x86_64.rpm

**Comment by amoskong** [comment]
The share snapshot works well in my side (as past, I used that in the past). And There is no error in developer tools console in taking snapshot.

Result: https://snapshot.raintank.io/dashboard/snapshot/41vwBtwGq4q9YiIkr4yFgfLks42FVHSU

<img width="761" alt="wx20180118-113149 2x" src="https://user-images.githubusercontent.com/309708/35079561-579d2558-fc43-11e7-993f-ee861e9f69c2.png">
<img width="1121" alt="wx20180118-113236 2x" src="https://user-images.githubusercontent.com/309708/35079559-55638200-fc43-11e7-9108-249a2cf8894e.png">

@roydahan

**Comment by amoskong** [comment]
Can you provide me a live environment when you touch this problem?  @roydahan

**Comment by roydahan** [comment]
@amoskong none of the recent performance (2 months) runs have a snapshot.

I don't know if what I wrote above it the root cause, please solve the snapshot issue in perf regression.

**Comment by amoskong** [comment]
I found the snapshot exist in latest 2.1/2.0 perf job.

- 2.1 perf job [snapshot](http://jenkins.cloudius-systems.com:8080/view/scylla-2.1/job/scylla-2.1-perf-regression-gce/label=gce3,sub_test=test_write/26/artifact/latest/test-results/1-performance_regression_test.py%3APerformanceRegressionTest.test_write/perf-regression-2-1-0-monitor-set-7eca4766/grafana-snapshot-0.png) , 2018/02/18
- 2.0 perf job [snapshot](http://jenkins.cloudius-systems.com:8080/job/scylla-2.0-perf-regression-gce/label=gce3,sub_test=test_write/8/artifact/latest/test-results/1-performance_regression_test.py%3APerformanceRegressionTest.test_write/perf-regression-2-0-3-monitor-set-64b6ad89/grafana-snapshot-0.png) ,  2018/02/18

**Comment by roydahan** [comment]
Yes, I just noticed that some of them have snapshots.
If I'll find some that don't have, i'll report them.
