### ISSUE TITLE
Remoter methods should fail fast with proper error when wrong credentials provided

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4709]
When using remoter.is_up() method, when wrong credentials are provided it waits until timeout occurs.
After timeout just returns False without any information. Which is wrong as ssh was up.

Additionally when running some commands with wrong credentials it raises wrong kind of error:
```
sdcm.remote.base.SSHConnectTimeoutError: Unable to run "sudo cloud-init status --wait": failed connecting to "20.106.242.55" during 60s
```
Remoter methods should fail fast in that case with authentication error.

**Comment by fgelcer** [comment]
do you have logs of this failure?
in which test does it happen?

**Comment by soyacz** [comment]
No specific logs, nor happening in test (at least now) - it's an error in SCT that leads to problems during development when sometimes things are not properly set.

**Comment by fruch** [comment]
It's a bit more problematic, since some times we do connect when credentials are yet set, so we keep trying. Failing fast in such case, can break some connecting to newly created node.

**Comment by soyacz** [comment]
Thanks @fruch for this point. This may happen only for the first ssh connection after provision. It's complicating the things a bit more than I thought. Anyway I see it as an error but effort (at this point) may not bring proper ROI.
