### ISSUE TITLE
When using branch2.1 or master - the monitor server doesn't include all dashboards

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#471]
The only dashboard included is the new nemesis and latency one:
![screen shot 2018-01-08 at 18 39 37](https://user-images.githubusercontent.com/20959584/34681050-4f4c3e22-f4a3-11e7-9f01-f8d77b29fd18.png)

**Comment by amoskong** [comment]
I didn't reproduce the problem with latest SCT master.

![image](https://user-images.githubusercontent.com/309708/35040163-19856a24-fbbb-11e7-902d-46937f59f45b.png)

![image](https://user-images.githubusercontent.com/309708/35041307-42ce84f2-fbbf-11e7-8fc3-52eb6459e795.png)

@roydahan  Can you show me a problem job? we can find some clue on the log.

**Comment by roydahan** [comment]
ok, weird.
I'll report back when running 2.1 again if the problem there still exist.

**Comment by roydahan** [comment]
ok, the problem is in branch-2.1.

![screen shot 2018-01-17 at 17 47 10](https://user-images.githubusercontent.com/20959584/35051701-85677a14-fbae-11e7-995a-9d0cfc2b999d.png)

**Comment by amoskong** [comment]
It's caused by rename in scylla-grafana-monitor project.
I will post a fix to sct master & branch-2.1

The problem exists both in sct master & branch-2.1, it can be reproduced
100% with clean env.

**Comment by amoskong** [comment]
scylla-grafana-monitoring project starts to use dashboard template, it's not good to repeatedly parse the templates in SCT. But current script in scylla-grafana-monitoring project doesn't support remote grafana server.

I just posted a PR: support to load dashboard to remote grafana installation [#268](https://github.com/scylladb/scylla-grafana-monitoring/pull/268)

**Comment by amoskong** [comment]
Another solution is convert the templates to final dashboard file in SCT by calling `make_dashboards.py` script in `scylla-grafana-monitoring`, then we don't need to change `scylla-grafana-monitoring`.

I will send out the PR after testing.
