### ISSUE TITLE
Unexpected error "disallowed character ',' in args " from "cluster manager sctool --  backup  --keyspace "

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4711]
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2021.1.10-20220410.e8e681dee` with build-id `f407f6d42e2570c781e916292747e651dd7f50da`
Cluster size: 6 nodes (i3.2xlarge)

OS / Image: `ami-02baaf20135f94bac` (aws: eu-west-1)

Test: `cloud-longevity-100gb-3d`
Test id: `3b5f47a7-e22c-464d-b423-415a61ef1241`
Test name: `siren-tests/longevity-tests/cloud-longevity-100gb-3d`
Test config file(s):

- [scylla_cloud_longevity-100GB-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6eee438422b5b93ba7c06003602ef15b28725a3a//home/ubuntu/scylla-cluster-tests/siren-tests/sct_plugin/configurations/scylla_cloud_longevity-100GB-48h.yaml)

## Issue description

Manager backup for few keyspaces failed with `disallowed character ',' in args ` error:
```
2022-05-05 01:24:02.665: (DisruptionEvent Severity.ERROR) period_type=end event_id=406013b9-62a8-432f-8403-0943682945ab duration=23s: nemesis_name=MgmtBackupSpecificKeyspaces target_node=Node longevity-100gb-48h
-cloud-master-db-node-3b5f47a7-7 [79.125.37.88 | 172.27.126.216] (seed: True) errors=Encountered an error on sctool command: backup -c CLOUD_CLUSTER_ID --keyspace keyspace1,ks_truncate  --location AWS_EU_WEST_1 
: Encountered a bad command exit code!

Command: '/opt/scylla/scylla-cloud -c /opt/scylla/scylla-dbaas.yml cluster manager sctool --cluster-id 17885 --  backup  --keyspace keyspace1,ks_truncate  --location AWS_EU_WEST_1 '

Exit code: 1

Stdout:



Stderr:

{"level":"info","ts":1651713842.5973096,"caller":"scylla-cloud/main.go:66","msg":"Command failed","error":"m.Handler.Cluster.ManagerSctoolRun: disallowed character ',' in args ","errorVerbose":"disallowed charac
ter ',' in args \nm.Handler.Cluster.ManagerSctoolRun\ngithub.com/scylladb/siren/command/cluster/manager.(*sctoolCmd).run\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/cluster/manager/sct
ool.go:55\ngithub.com/scylladb/siren/command/cluster/context.BuildContextMiddleware.func1.1\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/cluster/context/context.go:53\ngithub.com/scylla
db/siren/command.Use.func1.1\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/middleware.go:36\ngithub.com/scylladb/siren/command.Use.func1.1\n\t/home/runner/work/siren/siren/src/github.com
/scylladb/siren/command/middleware.go:36\ngithub.com/scylladb/siren/command.Use.func1.1\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/middleware.go:36\ngithub.com/scylladb/siren/command.
Use.func1.1\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/middleware.go:36\ngithub.com/scylladb/siren/command.(*App).TreeMiddleware.func1\n\t/home/runner/work/siren/siren/src/github.com/
scylladb/siren/command/tree.go:20\ngithub.com/scylladb/siren/command.Use.func1.1\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/command/middleware.go:36\ngithub.com/spf13/cobra.(*Command).execute
\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/vendor/github.com/spf13/cobra/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/work/siren/siren/src/github.com/scylladb/s
iren/vendor/github.com/spf13/cobra/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/vendor/github.com/spf13/cobra/command.go:895\nmain.main
\n\t/home/runner/work/siren/siren/src/github.com/scylladb/siren/cmd/scylla-cloud/main.go:42\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/proc.go:225\nruntime.goexit\n\t/opt/hostedtoolcache/go/
1.16.5/x64/src/runtime/asm_amd64.s:1371"}
Error: m.Handler.Cluster.ManagerSctoolRun: disallowed character ',' in args 
```

But by Scylla doc it's correct syntax: https://manager.docs.scylladb.com/stable/sctool/backup.html#:~:text=does%20not%20recur.-,%2DK%2C%20%2D%2Dkeyspace,-%3Clist%20of%20glob

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3b5f47a7-e22c-464d-b423-415a61ef1241`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3b5f47a7-e22c-464d-b423-415a61ef1241)
- Show all stored logs command: `$ hydra investigate show-logs 3b5f47a7-e22c-464d-b423-415a61ef1241`

## Logs:
- **db-cluster-3b5f47a7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/db-cluster-3b5f47a7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/db-cluster-3b5f47a7.tar.gz)

- **siren-manager-set-3b5f47a7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/siren-manager-set-3b5f47a7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/siren-manager-set-3b5f47a7.tar.gz)
- **sct-runner-3b5f47a7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/sct-runner-3b5f47a7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b5f47a7-e22c-464d-b423-415a61ef1241/20220506_115848/sct-runner-3b5f47a7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-100gb-3d/111/)
                            

### What is the expected result?

...

### What happens instead?

...

**Comment by fruch** [comment]
@juliayakovlev this error is coming out of siren, sounds like a bug in their code, not passing command line args as is.

**Comment by ShlomiBalalis** [comment]
> @juliayakovlev this error is coming out of siren, sounds like a bug in their code, not passing command line args as is.

It does, I just asked her to open an issue here so I can make sure of that first

**Comment by juliayakovlev** [comment]
@ShlomiBalalis can you, please, put here link to the commit of fix?

**Comment by fruch** [comment]
https://github.com/scylladb/siren/issues/7338
