### ISSUE TITLE
OperationTimeoutErrors during MemoryStress nemesis

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4715]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220504.b26a3da584cc` with build-id `ab2a33a30756c1513f4c516cd272291e75acec0e`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-a48dfe45-9 (34.247.156.147 | 10.0.0.208) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-8 (54.246.75.73 | 10.0.0.172) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-7 (34.251.121.154 | 10.0.3.56) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-6 (54.195.144.156 | 10.0.2.227) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-5 (54.195.153.219 | 10.0.0.150) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-4 (54.216.87.226 | 10.0.3.184) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-3 (54.154.186.250 | 10.0.0.91) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-2 (3.250.70.169 | 10.0.2.237) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-14 (18.203.111.253 | 10.0.2.8) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-13 (52.212.73.19 | 10.0.3.185) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-12 (34.248.246.26 | 10.0.1.181) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-11 (34.244.124.188 | 10.0.3.235) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-10 (54.229.189.251 | 10.0.2.184) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-a48dfe45-1 (34.244.125.143 | 10.0.3.14) (shards: 14)

OS / Image: `ami-0961efebe1f65ab2e` (aws: eu-west-1)

Test: `longevity-50gb-3days`
Test id: `a48dfe45-11ab-40ea-9d30-359a892627d8`
Test name: `scylla-master/longevity/longevity-50gb-3days`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea4aaa1b4f8b631fea2df71d8206e815c3d7614d/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

**>>>>>>>**
During `MemoryStress` nemesis we're getting OperationTimeoutErrors from c-s. While this is not perfect, I think these errors can be filtered out or have a reduced severity for this nemesis. It's reasonable to assume some timeouts may happen when we're starving the node for memory.

Example error:
```
java.io.IOException: Operation x10 on key(s) [504d4e374e4c4e353030]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a48dfe45-11ab-40ea-9d30-359a892627d8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a48dfe45-11ab-40ea-9d30-359a892627d8)
- Show all stored logs command: `$ hydra investigate show-logs a48dfe45-11ab-40ea-9d30-359a892627d8`

## Logs:
- **db-cluster-a48dfe45.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/db-cluster-a48dfe45.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/db-cluster-a48dfe45.tar.gz)
- **monitor-set-a48dfe45.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/monitor-set-a48dfe45.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/monitor-set-a48dfe45.tar.gz)
- **loader-set-a48dfe45.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/loader-set-a48dfe45.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/loader-set-a48dfe45.tar.gz)
- **normal-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/normal-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/normal-a48dfe45.log.tar.gz)
- **summary-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/summary-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/summary-a48dfe45.log.tar.gz)
- **events-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/events-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/events-a48dfe45.log.tar.gz)
- **output-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/output-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/output-a48dfe45.log.tar.gz)
- **debug-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/debug-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/debug-a48dfe45.log.tar.gz)
- **sct-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/sct-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/sct-a48dfe45.log.tar.gz)
- **error-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/error-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/error-a48dfe45.log.tar.gz)
- **critical-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/critical-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/critical-a48dfe45.log.tar.gz)
- **raw_events-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/raw_events-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/raw_events-a48dfe45.log.tar.gz)
- **warning-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/warning-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/warning-a48dfe45.log.tar.gz)
- **email_data-a48dfe45.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/email_data-a48dfe45.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/email_data-a48dfe45.json.tar.gz)
- **argus-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/argus-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/argus-a48dfe45.log.tar.gz)
- **left_processes-a48dfe45.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/left_processes-a48dfe45.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a48dfe45-11ab-40ea-9d30-359a892627d8/20220506_140245/left_processes-a48dfe45.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/135/)

**Comment by fruch** [comment]
@KnifeyMoloko, since we are limiting memory only on one node, we should have enough operational nodes during the stress, to answer correctly.  this case has 6 nodes and tables probably using RF=3, which mean 2 out of 3 nodes should be ACKing the this write.

this sound like an issue for scylla if failing to write.
