### ISSUE TITLE
fail to add a new node due to lack of capacity, mid test. (DecommissionStreamingErr/disrupt_add_remove_dc)

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4753]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220513.8e8dc2c930f5` with build-id `db03bd099e34fdbcc0ab957324be67cc42850a83`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-c9f794b8-7 (54.216.106.66 | 10.0.1.5) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-6 (52.18.99.80 | 10.0.3.232) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-5 (52.214.140.124 | 10.0.3.163) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-4 (54.170.147.47 | 10.0.3.190) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-3 (34.254.232.106 | 10.0.3.207) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-2 (54.170.172.233 | 10.0.1.15) (shards: 7)
- longevity-twcs-48h-master-db-node-c9f794b8-1 (52.212.87.178 | 10.0.0.112) (shards: 7)

OS / Image: `ami-0d71c53b714b555e3` (aws: eu-west-1)

Test: `longevity-twcs-48h-test`
Test id: `c9f794b8-8c72-4b82-92bd-802fae8ef143`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ec8c055433d0d9024cd7f70ef63964013b230687/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
`DecommissionStreamingErr` nemesis attempts to decommission a node and stop it from leaving. If that fails, it will add a new node to the test cluster. In some cases, there might not be enough capacity in the region for a new node to be added:

```
2022-05-16 16:38:04: botocore.exceptions.ClientError: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient i3en.2xlarge capacity in the Availability Zone you requested (eu-west-1a). Our system will be working on provisioning additional capacity. You can currently get i3en.2xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-1b, eu-west-1c.
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor c9f794b8-8c72-4b82-92bd-802fae8ef143`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c9f794b8-8c72-4b82-92bd-802fae8ef143)
- Show all stored logs command: `$ hydra investigate show-logs c9f794b8-8c72-4b82-92bd-802fae8ef143`

## Logs:
- **db-cluster-c9f794b8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/db-cluster-c9f794b8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/db-cluster-c9f794b8.tar.gz)
- **monitor-set-c9f794b8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/monitor-set-c9f794b8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/monitor-set-c9f794b8.tar.gz)
- **loader-set-c9f794b8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/loader-set-c9f794b8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/loader-set-c9f794b8.tar.gz)
- **sct-runner-c9f794b8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/sct-runner-c9f794b8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9f794b8-8c72-4b82-92bd-802fae8ef143/20220516_182153/sct-runner-c9f794b8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/34/)

**Comment by fruch** [comment]
This one is hard to solve, since we don't want to span a test across multiple zones (cost wise), we probably should be using random zones for AWS, like we are doing for GCE. also random regions might help a bit (for us not shooting ourselves in the foot, and using all of specific instance type i.e. i3en.2xlarge)

could be that specific test case that uses `i3en` we might need to move to region that has more of those available. (i.e. if this kind of failure is proven to happen too many times)

**Comment by fruch** [comment]
happens during `disrupt_add_remove_dc`
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3599, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3489, in disrupt_add_remove_dc
    new_node = self._add_new_node_in_new_dc()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3431, in _add_new_node_in_new_dc
    new_node = self.cluster.add_nodes(1, dc_idx=0, enable_auto_bootstrap=True)[0]  # add node
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 844, in add_nodes
    added_nodes = super().add_nodes(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 394, in add_nodes
    instances = self._create_or_find_instances(count=count, ec2_user_data=ec2_user_data, dc_idx=dc_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 358, in _create_or_find_instances
    return self._create_instances(count, ec2_user_data, dc_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 212, in _create_instances
    instances = self._create_on_demand_instances(count, interfaces, ec2_user_data, dc_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 141, in _create_on_demand_instances
    instances = self._ec2_services[dc_idx].create_instances(**params)
  File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient i3.4xlarge capacity in the Availability Zone you requested (eu-west-1a). Our system will be working on provisioning additional capacity. You can currently get i3.4xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-1b, eu-west-1c.
```

## Installation details

Kernel Version: 5.13.0-1031-aws
Scylla version (or git commit hash): `5.1.dev-20220706.a0ffbf3291b7` with build-id `3490fa9f14da510e97a1d0f53f693cac13a70494`
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-verify-limited--db-node-81079189-6 (34.249.28.142 | 10.0.3.83) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-81079189-5 (34.246.190.41 | 10.0.1.242) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-81079189-4 (34.243.250.185 | 10.0.0.96) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-81079189-3 (34.254.248.101 | 10.0.0.24) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-81079189-2 (54.194.31.143 | 10.0.1.76) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-81079189-1 (34.240.148.36 | 10.0.0.184) (shards: 14)


OS / Image: `ami-07d73e5ea1fc772eb` (aws: eu-west-1)

Test: `longevity-200gb-48h`
Test id: `81079189-021f-4f1d-9751-241137e99892`
Test name: `scylla-master/longevity/longevity-200gb-48h`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/add194678d746f8a5382a7eeced83d1975ba3976/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)


- Restore Monitor Stack command: `$ hydra investigate show-monitor 81079189-021f-4f1d-9751-241137e99892`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=81079189-021f-4f1d-9751-241137e99892)
- Show all stored logs command: `$ hydra investigate show-logs 81079189-021f-4f1d-9751-241137e99892`

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/186/)

**Comment by fruch** [comment]
basically `get_ec2_network_configuration` can be aware of multiple zones, 
but the rest of the code in `cluster_aws.py` assumes one subnet_id per region, so we'll need to refactor all places using `subnet_id` to be able to randomize one of the subnets of a region, or switch to the next one on capacity failures.
