### ISSUE TITLE
artifacts offline installer - Ubuntu 20.04 ARM missing during installation

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4769]
### Versions
* **SCT**: master (8a3efc46a1a5ad5ef7eeb7b708437a2c096a144b)
* **scylla**: `5.1.dev.0.20220519.e6fe9cc683f4`

### Logs
* test_id: `4b283f13-51a8-4565-afdb-6d40ad4b5038`
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/artifacts-offline-install/job/artifacts-ubuntu2004-arm-test/3

### Description

```
Command: 'sudo update-java-alternatives --jre-headless -s java-1.8.0-openjdk-amd64'
Exit code: 1
Stdout:

Stderr:
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-1.8.0-openjdk-amd64
```

could it be that Scylla package must include that file?

**Comment by fgelcer** [comment]
@syuu1228 , could you please advise?

**Comment by fruch** [comment]
LOL, @fgelcer look closer on the directory name we are configuring here... it's says amd64...
while here we clearly installed the java into `/usr/lib/jvm/java-8-openjdk-arm64`

we should use this directory:
```
/usr/lib/jvm/java-8-openjdk-`dpkg-architecture -q DEB_BUILD_ARCH`
```
