### ISSUE TITLE
Cannot run SCT test without sct-runner

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4770]
We cannot run SCT test from local machines, we **must** use sct-runner.

There are cql errors (during setting rf for auth table) when not using sct runner due to using private ip’s for connection (in scylla yaml there are private rpc addresses set, so sct uses private ip’s for cql)
As workaround, set: SCT_INTRA_NODE_COMM_PUBLIC=true

This issue has been introduced in PR: https://github.com/scylladb/scylla-cluster-tests/pull/4375

**Comment by soyacz** [comment]
@juliayakovlev in mentioned PR we deliberately set python driver to use private ip's. Why was this necessary?

**Comment by juliayakovlev** [comment]
@soyacz We use IPs (private/public/IPv6) depends on test configuration. Commonly if a test is configured to be run with private, it will use private IPs.
Can you, please, let me example of the problem (link, logs, something)

**Comment by fruch** [comment]
> e rpc addresses set, so sct uses private ip’s for cql

As @juliayakovlev mentioned, as of forever, for debugging SCT from local machine, you'll need to configure the cluster to use public addresses. there are some places in the code that was wrongly using public addresses

Soon in AWS, once we'll move to VPC peering, it would be even tricker, since we'll be closing the Security group for external connections. (we probably gonna have a solution, but adding new security groups for test who needs them)

**Comment by soyacz** [comment]
@fruch But before this commit I could run SCT tests from my laptop only after setting ssh connection to public.
But now, to be able to work in the same way, I have to set up also SCT_INTRA_NODE_COMM_PUBLIC=true - which is not optimal.

Is it intended we drop support for running SCT without sct runner?

**Comment by juliayakovlev** [comment]
> @fruch But before this commit I could run SCT tests from my laptop only after setting ssh connection to public. But now, to be able to work in the same way, I have to set up also SCT_INTRA_NODE_COMM_PUBLIC=true - which is not optimal.
> 
> Is it intended we drop support for running SCT without sct runner?

@soyacz if you let me logs, I could check it. 
Commonly the change was performs to align SCT with Scylla, how Scylla uses addresses from scylla.yaml config. Before SCT used its internal definition for different connection types. Now it works as Scylla

**Comment by fruch** [comment]
> @fruch But before this commit I could run SCT tests from my laptop only after setting ssh connection to public. But now, to be able to work in the same way, I have to set up also SCT_INTRA_NODE_COMM_PUBLIC=true - which is not optimal.
> 
> Is it intended we drop support for running SCT without sct runner?

Having to define 2 environment variables, is sub optimal ?, I guess it wasn't intentional breakage. but probably by mistake.

**Comment by soyacz** [comment]
> @soyacz if you let me logs, I could check it.

No need to check logs, just python driver which sits e.g. on builder (or localhost when running locally) uses private IP's which won't work.


> Having to define 2 environment variables, is sub optimal ?

The bigger problem is when setting COMM_PUBLIC, Scylla uses public ip's for communication - this is sub optimal (and increases costs). 

Any idea how we could make it work without sct-runner?

**Comment by fruch** [comment]
@soyacz is still the case ? i.e. that we must have SCT_INTRA_NODE_COMM_PUBLIC to work from local setup ?

**Comment by soyacz** [comment]
> @soyacz is still the case ? i.e. that we must have SCT_INTRA_NODE_COMM_PUBLIC to work from local setup ?

I didn't try it for some time, but I think it's still an issue.

**Comment by fruch** [comment]
@temichus is hitting this as well when trying to run from a local host

**Comment by roydahan** [comment]
We can use the SCT_INTRA_NODE_COMM_PUBLIC.
