### ISSUE TITLE
Overload exception - alternator multiDC

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#4777]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.0~rc5-20220515.9da666e77` with build-id `5992da65161c733b3f85b8c93bbbb5151d4d321c`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-multidc-5-0-db-node-a8368f72-7 (3.250.194.158 | 3.250.194.158) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-6 (3.237.51.133 | 3.237.51.133) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-5 (34.232.48.183 | 34.232.48.183) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-4 (3.238.195.237 | 3.238.195.237) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-3 (34.243.207.223 | 34.243.207.223) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-2 (54.170.183.99 | 54.170.183.99) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-1 (34.247.184.71 | 34.247.184.71) (shards: 14)

OS / Image: `ami-028dc71f18948aff6 ami-03731266bb9dfb68f` (aws: eu-west-1)

Test: `longevity-alternator-3h-multidc-test`
Test id: `a8368f72-24b1-493e-bce8-edca6b9886ee`
Test name: `scylla-5.0/longevity/longevity-alternator-3h-multidc-test`
Test config file(s):

- [longevity-alternator-3h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/36019f38f4ec4a78f8cf40d2b58f887ab5c21c13/test-cases/longevity/longevity-alternator-3h-multidc.yaml)

## Issue description

**>>>>>>>**
Scenario:
1. running ycsb Alternator load on multi-dc cluster (LWT + a non LWT tables)
2. First issue noticed: number of requests is very low - not more than 400. in 4.6 run it had 1k - 2.5k
3. run a nemesis of disrupt_remove_node_then_add_node: remove a node, then add a new node and initialize it.
4. YCSB got an error of overload with "Too many in flight hints"
error:
```

2022-05-22 11:31:26.749: (YcsbStressEvent Severity.ERROR) period_type=not-set event_id=c497cbdf-5c2d-4b12-8bc4-268867ebd96b: type=error node=Node alternator-3h-multidc-5-0-loader-node-a8368f72-2 [34.247.167.126 | 10.0.1.196] (seed: False)
stress_cmd=bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true -p table=usertable_no_lwt -p maxexecutiontime=10800 -s  -P /tmp/dynamodb.properties
errors:
9856294 [Thread-9] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.services.dynamodbv2.model.InternalServerErrorException: Internal server error: exceptions::overloaded_exception (Too many in flight hints: 10485768) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalServerError; Request ID: null; Proxy: null)
```

running nemesis details:
```


disrupt_remove_node_then_add_node | alternator-3h-multidc-5-0-db-node-a8368f72-2 | Succeeded | 2022-05-22 11:00:53 | 2022-05-22 12:09:53
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_remove_node_then_add_nodeStatus: SucceededDuration: 1 hour, 9 minutesTarget InformationName: alternator-3h-multidc-5-0-db-node-a8368f72-2Public IP: 54.170.183.99Private IP: 54.170.183.99State: terminatedShards: 14

```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a8368f72-24b1-493e-bce8-edca6b9886ee`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a8368f72-24b1-493e-bce8-edca6b9886ee)
- Show all stored logs command: `$ hydra investigate show-logs a8368f72-24b1-493e-bce8-edca6b9886ee`

## Logs:
- **db-cluster-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/db-cluster-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/db-cluster-a8368f72.tar.gz)
- **monitor-set-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/monitor-set-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/monitor-set-a8368f72.tar.gz)
- **loader-set-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/loader-set-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/loader-set-a8368f72.tar.gz)
- **sct-runner-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/sct-runner-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/sct-runner-a8368f72.tar.gz)
- **parallel-timelines-report-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/parallel-timelines-report-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/parallel-timelines-report-a8368f72.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-alternator-3h-multidc-test/4/)

_Originally posted by @yarongilor in https://github.com/scylladb/scylla/issues/10534#issuecomment-1134461085_

**Comment by fruch** [comment]
`error: exceptions::overloaded_exception (Too many in flight hints: 10485768)` is an error coming from scylla (i.e. it has nothing todo with YCSB)

**Comment by nyh** [comment]
@roydahan is this scenario simulating normal steady behavior, or some sort of overload/problem situation?

Because I think (@psarna ?) an "overloaded exception" is a deliberate Scylla feature where we temporarily fail a request because we're too overloaded. Alternator returns InternalServerErrorException so the client knows it is supposed to retry (that is what the Amazon clients do in this case - they retry - not print the error. I don't know about YCSB.

Maybe YSCB and/or SCT should know to retry on such failures and only start to get worried if there are a lot of them (e.g., count them, or whatever).

On the other hand, if this test is supposed to simulate some nice, steady, workload, it's curious why we got even one of these errors, so maybe it's better to know?

**Comment by roydahan** [comment]
@yarongilor is investigating this, I just took it out of a Scylla issue he commented about.
I think that when he compares it to 4.6 he saw that the throughput is much higher compared to 5.0, but I'll let him add the information.

This is the monitor he shared: http://3.222.205.29:3000/d/alternator-5-0/alternator?orgId=1&from=1653207496879&to=1653221994308

http://3.222.205.29:3000/d/EoZ_3_unk/longevity-alternator-3h-multidc-test-scylla-per-server-metrics-nemesis-master?from=1653211726944&to=1653222578053&orgId=1

The issue happens at 11:30, while running a repair on a newly added node after we removed a terminated node.

**Comment by yarongilor** [comment]
5.0 requests performance:

![Screenshot from 2022-05-23 14-22-23](https://user-images.githubusercontent.com/9427929/169810745-269dc90e-cf0b-42a1-b6ec-9f1b21f2bd95.png)

4.6 requests performance:
![4_6_requests_alternator_multi_dc](https://user-images.githubusercontent.com/9427929/169811077-0903a30b-4dd8-46e8-b5db-8d157f58a1cc.png)

**Comment by psarna** [comment]
> Because I think (@psarna ?) an "overloaded exception" is a deliberate Scylla feature where we temporarily fail a request because we're too overloaded. 

Yes, the name of this exception sounds generic, but the exact meaning of this error, specified in Cassandra, is "coordinator is overloaded", and drivers usually react to such errors by retrying on another coordinator. Although that of course depends on their retry policy.

**Comment by fruch** [comment]
> > > Because I think (@psarna ?) an "overloaded exception" is a deliberate Scylla feature where we temporarily fail a request because we're too overloaded.
> > 
> > 
> > Yes, the name of this exception sounds generic, but the exact meaning of this error, specified in Cassandra, is "coordinator is overloaded", and drivers usually react to such errors by retrying on another coordinator. Although that of course depends on their retry policy.
> 
> Thanks. Just note that in this case, Alternator took Scylla's "overloaded exception" and converted (like it does to all unknown exceptions) it to a generic "Internal Server Error" (http code 500), and this in the DynamoDB world also means that the client would retry - this is built into the driver (though it doesn't have any special logic for retrying on a different node, because DynamoDB doesn't even have the notion of multiple server nodes, this is something we hacked on).

looking at YCSB code, seems like there are retries (that the default in AWS SDK), and from the log, 52 failed operations:
```
[UPDATE-FAILED], Operations, 52
[UPDATE-FAILED], AverageLatency(us), 361222.46153846156
[UPDATE-FAILED], MinLatency(us), 65216
[UPDATE-FAILED], MaxLatency(us), 631807
[UPDATE-FAILED], 95thPercentileLatency(us), 556543
[UPDATE-FAILED], 99thPercentileLatency(us), 592383
```

**Comment by yarongilor** [comment]
> > > > Because I think (@psarna ?) an "overloaded exception" is a deliberate Scylla feature where we temporarily fail a request because we're too overloaded.
> > > 
> > > 
> > > Yes, the name of this exception sounds generic, but the exact meaning of this error, specified in Cassandra, is "coordinator is overloaded", and drivers usually react to such errors by retrying on another coordinator. Although that of course depends on their retry policy.
> > 
> > 
> > Thanks. Just note that in this case, Alternator took Scylla's "overloaded exception" and converted (like it does to all unknown exceptions) it to a generic "Internal Server Error" (http code 500), and this in the DynamoDB world also means that the client would retry - this is built into the driver (though it doesn't have any special logic for retrying on a different node, because DynamoDB doesn't even have the notion of multiple server nodes, this is something we hacked on).
> 
> looking at YCSB code, seems like there are retries (that the default in AWS SDK), and from the log, 52 failed operations:
> 
> ```
> [UPDATE-FAILED], Operations, 52
> [UPDATE-FAILED], AverageLatency(us), 361222.46153846156
> [UPDATE-FAILED], MinLatency(us), 65216
> [UPDATE-FAILED], MaxLatency(us), 631807
> [UPDATE-FAILED], 95thPercentileLatency(us), 556543
> [UPDATE-FAILED], 99thPercentileLatency(us), 592383
> ```

1. In any case, this error didn't happen before.
2. There is also a significant performance degradation shown in this test between 4.6 and 5.0: 2.5K requests vs. 400 requests.

**Comment by roydahan** [comment]
> 2. There is also a significant performance degradation shown in this test between 4.6 and 5.0: 2.5K requests vs. 400 requests.


@yarongilor are you basing this on a run that you did for 4.6 with SCT branch-5.0?
(In other words, did you run both with the same branch?)

**Comment by yarongilor** [comment]
> > 2. There is also a significant performance degradation shown in this test between 4.6 and 5.0: 2.5K requests vs. 400 requests.
> 
> @yarongilor are you basing this on a run that you did for 4.6 with SCT branch-5.0? (In other words, did you run both with the same branch?)

no, just compared it to past 4.6 run results with SCT-4.6.

**Comment by roydahan** [comment]
So we need a run with branch-5.0 and use Scylla 4.6.0 to compare.

**Comment by roydahan** [comment]
update on the reproducer run?

**Comment by yarongilor** [comment]
> So we need a run with branch-5.0 and use Scylla 4.6.0 to compare.

The error is not reproduced. didn't get any overload exception and RemoveNodeThenAddNode nemesis passed ok.


*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.6.3-0.20220414.8bf149fdd with build-id 8d16d8972498cc769071ff25309b009eb77bf77a`
Cluster size: 3 3 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   alternator-3h-multidc-5-0-db-node-d4203c75-1 (54.154.40.142 | 10.0.1.212): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-2 (18.203.231.76 | 10.0.1.160): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-4 (34.205.26.21 | 10.0.3.32): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-5 (3.234.154.167 | 10.0.2.50): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-6 (3.228.14.212 | 10.0.3.24): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-7 (34.249.100.41 | 10.0.3.63): 14 shards
Scylla running with shards number (terminated nodes):
   alternator-3h-multidc-5-0-db-node-d4203c75-3 (54.216.119.238 | 10.0.3.52): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-03d8b6dcd63bd4e24 ami-09c658571b2d46d18` (aws: eu-west-1 us-east-1)


Test: `longevity-alternator-3h-multidc-test_repro`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h-multidc.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h-multidc.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h-multidc.yaml&source=gmail-html&ust=1653644328414000&usg=AOvVaw3ZzTgdUbhhlESKQsb3Cb_B))


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor d4203c75-a33d-4a28-b1f4-d5922483925e`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=branch-5.0&test_id=d4203c75-a33d-4a28-b1f4-d5922483925e](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dbranch-5.0%26test_id%3Dd4203c75-a33d-4a28-b1f4-d5922483925e&source=gmail-html&ust=1653644328414000&usg=AOvVaw3X6kkLZYzjvOA99qGwrIMe))
Show all stored logs command: `$ hydra investigate show-logs d4203c75-a33d-4a28-b1f4-d5922483925e`

Test id: `d4203c75-a33d-4a28-b1f4-d5922483925e`


Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw1I6yp_Z8OWJ7jZlmcvLgcD)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw3XxilJa2ZaSGI_eBRMsnnV)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw2ohtwmCM8LkbhktbkQ7zBM)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz)&source=gmail-html&ust=1653644328414000&usg=AOvVaw1QBKFn57uINfm3lJYrtu8V)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw31rexAIX70-MIz6UQaxCVG)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw19YSw46sNdOIiAriWh0QpB)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw3TMuTWkDh-u9k3SKd0FV8p)


[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/longevity-alternator-3h-multidc-test_repro/2/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/longevity-alternator-3h-multidc-test_repro/2/&source=gmail-html&ust=1653644328415000&usg=AOvVaw2RQYJyxVsK4TvmFlUe_Cb1))

**Comment by roydahan** [comment]
Ok, please organize all information and open a new issue with all the details and clear description of the regression and the performance change.

**Comment by yarongilor** [comment]
@roydahan , according to the 5.0 comparison the performance is identical and no regression. So only the only difference and issue left is the YCSB error of "Too many in flight hints". should i report a new issue for only this error?

**Comment by roydahan** [comment]
Yes, open a new  issue for the error.
Provide the information in organized matter.
Provide relevant logs only and reference to the logs timestamps and names.

**Comment by yarongilor** [comment]
opened https://github.com/scylladb/scylla/issues/10702
