### ISSUE TITLE
Sending email by the job features-add-new-dc-test failed with `No reporter found` 

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#4779]
### Prerequisites

* [ ] ~~Are you rebased to master ?~~
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2022.1

### Description
The failed Job: `features-add-new-dc-test`
Example of the failed build: https://jenkins.scylladb.com/job/enterprise-2022.1/job/features-/job/features-add-new-dc-test/2/

The SCT stage passed, but `Send email with result` stage failed with the warning (and the whole job was marked as failed)
```
19:03:38    warnings.warn(
19:03:39  No reporter found
19:03:40  Cleaning SSH agent
19:03:40  Agent pid 2608766 killed
```
Looks like SCT is not configured to use one of the existing Email Reporters with this kind of job or it does not have the appropriate Reporter at all

**Comment by fgelcer** [comment]
@vponomaryov @soyacz  FYI

**Comment by soyacz** [comment]
Looks like `build_reporter` method searches right reporter class by some pattern in the test name.
Solution would be to add 'Functional' into the name (maybe instead `features` make it `Functional`?) or fix matching in this method.

Anyone knows if `FunctionalEmailReporter` will work for this case?
