### ISSUE TITLE
README.rst refers to non-working "hydra ls" command

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#4781]
README.rst suggests that `hydra ls -l` should work.
But it doesn't:
```
Usage: sct.py [OPTIONS] COMMAND [ARGS]...
Try 'sct.py --help' for help.

Error: No such command 'ls'.
```

If somebody really wants to run "ls" (I don't know why it's important..), I see that `hydra bash -c ls` does work.

**Comment by fruch** [comment]
yeah, this line is from before `sct.py` was implemented

now we support `bash/python` as the first command the rest is routed to `sct.py` click application

**Comment by nyh** [comment]
I don't want to create a dozen issues, so I'll just comment here that the reference in README.rst to `hydra prepare-aws-region` is also wrong. I don't understand what this was supposed to do and what replaced it, but it doesn't work now.

**Comment by fruch** [comment]
> I don't want to create a dozen issues, so I'll just comment here that the reference in README.rst to `hydra prepare-aws-region` is also wrong. I don't understand what this was supposed to do and what replaced it, but it doesn't work now.

The prepare region command is a maintenance command (meant for SCT admins), it probably need to be moved to a different file

**Comment by nyh** [comment]
@nuivall fell on this `hydra ls` "example" today as well. How many more people need to try this command and fail before we change the example?

**Comment by fgelcer** [comment]
i think this is fixed

**Comment by fruch** [comment]
> hydra ls

it's still mentioned in `install-hydra.sh`
