### ISSUE TITLE
Hydra downloads ssh keys twice per run - thats one or two times too many

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#4782]
When I run `hydra bash` (for example), I see SSH keys being downloaded twice:
```
$ hydra bash
Pull version v1.13 from Docker Hub...
v1.13: Pulling from scylladb/hydra
Digest: sha256:0629f8a22c712fbfde7ff889db6d75cee7e5d55b147b84ab89f6d6a1b1092fd6
Status: Image is up to date for scylladb/hydra:v1.13
docker.io/scylladb/hydra:v1.13
Obtaining QA SSH keys...
QA SSH keys obtained.
Going to run 'bash'...
Obtaining QA SSH keys...
QA SSH keys obtained.
```
Indeed, docker/env/hydra.sh has two calls:
```
# Check for SSH keys
if [[ -z "$HYDRA_HELP" ]]; then
    if [ -z "$HYDRA_DRY_RUN" ]; then
        ${SCT_DIR}/get-qa-ssh-keys.sh
    else
        echo ${SCT_DIR}/get-qa-ssh-keys.sh
    fi
fi

...
if [[ -z "${HYDRA_HELP}" ]]; then
    PREPARE_CMD+="; ${SCT_DIR}/get-qa-ssh-keys.sh"
fi
```

As a first step, we shouldn't do this twice per run - once should be enough.

As a second step, I think it's no necessary to do the actual download even once per run. If the user already has these files, why do we need to download them again on every run? Are we worried that one day we'll want to change these keys and nobody will remember to delete the old keys? If this is the case, how about only checking for a new file once per hour or once per day (say), not every time?

On my machine (and in the fast office network), one run of `get-qa-ssh-keys.sh` takes 1.3 seconds, and the two of them take around 2.6 seconds. This isn't enough time to get coffee, but is certainly noticeable and wasteful.

**Comment by nyh** [comment]
> I agree, we could also potentially store known keys' fingerprints (since those are intended to be public anyway) inside the script, so that if we ever change the keys, the new ones will be downloaded anyway.

Right, this would be similar to what the script already does regarding docker versions, where it doesn't try to reload an image with the same version it expects (although it turns out this code was broken too - see https://github.com/scylladb/scylla-cluster-tests/pull/4784).

An even simpler approach than checksums would be to change the **filename**. E.g., we now download the file "scylla-qa-ec2" but when it changes, put the new file in "scylla-qa-ec2-v2" and change the script to download "scylla-qa-ec2-v2" - but only if it doesn't yet exist. We can have a symbolic link to the name "scylla-qa-ec2" for the convenience of the user and the other scripts, who can use the name "scylla-qa-ec2" for the latest version.

**Comment by nyh** [comment]
@nuivall just encountered another downside of this key-fetching-every time behavior: If your AWS credentials are set up and SCT could correctly create VMs but they are not enough for fetching the QA keys, hydra doesn't work because it fails to fetch the keys. Even if you manually copied the key files to your $HOME/.ssh.

**Comment by fruch** [comment]
> @nuivall just encountered another downside of this key-fetching-every time behavior: If your AWS credentials are set up and SCT could correctly create VMs but they are not enough for fetching the QA keys, hydra doesn't work because it fails to fetch the keys. Even if you manually copied the key files to your $HOME/.ssh. 

I can't guarantee SCT would be able to function without access to our s3 bucket.

I'm o.k. with failing fast on it, and @nuivall would need to fix the account it's running from.

I don't see how it's related to this issue that is about the time this is taking.

**Comment by nuivall** [comment]
It's more about the fact that if valid keys are already present in ~/.ssh why should it try to download them from s3?

**Comment by fruch** [comment]
> It's more about the fact that if valid keys are already present in ~/.ssh why should it try to download them from s3?

The reason for it was the rotation of those keys, on builders which are static.
 
We are planning to retire all the static builders, but that would take a while.

And again even if we would be checking for dates or fingerprinting, we would need s3 access.

**Comment by nyh** [comment]
> And again even if we would be checking for dates or fingerprinting, we would need s3 access 

Why? As explained above, SCT can know which key it expects (its date, checksum or name). When the key is rotated, the SCT code will change to change its expectation.

The bigger question is does SCT need Scylla AWS account (and not some other AWS account) for anything besides the key fetching. If (and only if)  the answer is no, this gives another reason why the excessive key fetching is bad.

**Comment by fruch** [comment]
> 
> > And again even if we would be checking for dates or fingerprinting, we would need s3 access 
> 
> Why? As explained above, SCT can know which key it expects (its date, checksum or name). When the key is rotated, the SCT code will change to change its expectation.
> 
> The bigger question is does SCT need Scylla AWS account (and not some other AWS account) for anything besides the key fetching. If (and only if)  the answer is no, this gives another reason why the excessive key fetching is bad.
> 

The answer is yes, lots of things are wired to our account beside this.

Running on a different AWS account might be doable, but no one currently cares (or willing to invest) in that use case.
