### ISSUE TITLE
Check if #REMOTER_SUDO really need to be using sudo

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4809]
Seems like all that those command are being use to, is to run nodetool.
I can't think of a reason why we to run nodetool as root.

We should try to change it to regular run command, and see if it's has any effect on the upgrade test

**Comment by fruch** [comment]
seem like the usage of root for those command is from ~2017 when @roydahan introduced those.

@roydahan you have any recollection of why it was using root ?

**Comment by roydahan** [comment]
I don't remember.
Maybe there was a command that wasn't sudo or we had a version where sstables were owned by root.
