### ISSUE TITLE
Configuration script is ignored on AWS nodes

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4818]
##Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 8
Backend: gce: us-east1
Kernel version: 5.13.0-1024-gcp
Test-id: ca92a910-64f9-416e-8a01-0a6f79a2ccaa
Start time: 2022-05-27 19:40:46
End time: 2022-05-27 19:50:45
Started by user: maciej.cisowski
Private repo: http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2022-05-25T04:06:35Z/scylladb-master/scylla.list

## Test result
SUCCESS

##System under test
ScyllaDB version: 5.1.dev-0.20220525.dc5c9321fee9 with build-id 5b7f6260568fb8c82a0a426141fc01c4d21edf8a
ScyllaDB repo: http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2022-05-25T04:06:35Z/scylladb-master/scylla.list
Actual gce image used: ubuntu-2004-focal-v20220419
AWS region: us-east1
Instance type: n1-standard-2
Scylla packages installed:
scylla 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-conf 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-jmx 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-kernel-conf 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-manager-agent 2.6.3~0.20220307.89b222a1a68
scylla-node-exporter 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-python3 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-server 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-tools 5.1.dev-0.20220525.dc5c9321fee9-1
scylla-tools-core 5.1.dev-0.20220525.dc5c9321fee9-1

<<<<<< Issue description
When running on AWS the script we pass in our `UserData` object is ignored on cloud-init. Therefore any config changes included in that script will not be made. 

`cloud-init` logs from AWS node:
```
May 27 19:13:31 ip-10-0-3-7 cloud-init[480]: 2022-05-27 19:13:31,558 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'{"scylla_yaml": {"cluste'...'
```
<<<<<<I

##Restore commands:
Restore Monitor Stack command: $ hydra investigate show-monitor ca92a910-64f9-416e-8a01-0a6f79a2ccaa
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=add-ubuntu22-artifacts-test&test_id=ca92a910-64f9-416e-8a01-0a6f79a2ccaa)
Show all stored logs command: $ hydra investigate show-logs ca92a910-64f9-416e-8a01-0a6f79a2ccaa

##Logs:
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/ca92a910-64f9-416e-8a01-0a6f79a2ccaa/20220527_195112/db-cluster-ca92a910.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ca92a910-64f9-416e-8a01-0a6f79a2ccaa/20220527_195112/db-cluster-ca92a910.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/ca92a910-64f9-416e-8a01-0a6f79a2ccaa/20220527_195112/sct-runner-ca92a910.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ca92a910-64f9-416e-8a01-0a6f79a2ccaa/20220527_195112/sct-runner-ca92a910.tar.gz)

##Links:
[Build URL](https://jenkins.scylladb.com/job/scylla-staging/job/maciej/job/artifacts-2004/8/)

**Comment by KnifeyMoloko** [comment]
This is also related to: https://github.com/scylladb/scylla-machine-image/issues/357

**Comment by fruch** [comment]
@KnifeyMoloko I think we need to have a fix in SCT for this, since we need to test ubuntu22 for scylla-5.0 and 2022.1, I don't think we have time for developing anything new in machine-image right now.

**Comment by fruch** [comment]
For now I think we can use the `use_preinstalled_scylla: false` in a way to know we can use regular cloud-init user-data.
for those artifacts or rolling-upgrade tests

**Comment by fgelcer** [comment]
> For now I think we can use the `use_preinstalled_scylla: false` in a way to know we can use regular cloud-init user-data. for those artifacts or rolling-upgrade tests

it is a premise of artifacts test to have `use_preinstaled_scylla: false`

**Comment by roydahan** [comment]
Is it something specific to ubuntu22?
Don't we use the UserData to configure things in our provision?

**Comment by KnifeyMoloko** [comment]
> Is it something specific to ubuntu22? Don't we use the UserData to configure things in our provision?

This issue comes up on Ubuntu22, the other distros are not affected since everything worked fine until `openssh 8.8`. I already have a partial solution (hacking our `ec2_client` module to use `cloud-init`) which is enough for artifacts. The problem is with UserData in our provision, where we dump a JSON with a json-ized `scylla_yaml` and a `post_configuration_script`. As far as I can tell this actually doesn't get used by SCT directly. We construct the same `post_configuration_script` when running `configure_remote_logging` in `BaseNode`'s `init` method and use that.

**Comment by fruch** [comment]
> > Is it something specific to ubuntu22? Don't we use the UserData to configure things in our provision?
> 
> This issue comes up on Ubuntu22, the other distros are not affected since everything worked fine until `openssh 8.8`. I already have a partial solution (hacking our `ec2_client` module to use `cloud-init`) which is enough for artifacts. The problem is with UserData in our provision, where we dump a JSON with a json-ized `scylla_yaml` and a `post_configuration_script`. As far as I can tell this actually doesn't get used by SCT directly. We construct the same `post_configuration_script` when running `configure_remote_logging` in `BaseNode`'s `init` method and use that.

the user-data is being used, first it's for configuration of scylla yaml, it's also pass the cluster name and the configuration option to tell scylla no to start automatically, and wait for us to start the service.

**Comment by fruch** [comment]
@KnifeyMoloko can we close this one ? or you want to leave it as a placeholder for implementing the mime multipart option we now have in master ?

**Comment by KnifeyMoloko** [comment]
I think we can close this one.
