### ISSUE TITLE
SCT failing to bring up the cluster because rsyslog docker can't find SSH key

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#4843]
I tried to run on SCT master the following test:
```
export SCT_SCYLLA_VERSION=5.0.rc6
export SCT_IP_SSH_CONNECTIONS=public
export SCT_INTRA_NODE_COMM_PUBLIC=true
export SCT_CLUSTER_HEALTH_CHECK=false
export SCT_REGION_NAME=eu-north-1
export SCT_INSTANCE_PROVISION=spot
export SCT_RUN_DB_NODE_BENCHMARKS=false
export JOB_NAME=local_run
hydra run-test performance_regression_alternator_test.PerformanceRegressionAlternatorTest.test_write --backend aws --config nyh/alternator-throughput-1.yaml
```

(my nyh/alternator-throughput-1.yaml is the copy of the existing alternator throughput yaml with a zero removed from all the numbers).

After 25 minutes, the test ended with an unclear error about logs 

```
< t:2022-05-31 15:02:35,412 f:wait.py         l:68   c:sdcm.wait            p:ERROR > Wait for: wait for db logs: timeout - 300 seconds - expired
```

see the full log below. It appears that SCT didn't even finish configuring the nodes, and didn't get to run the monitoring - at the end I am left with a live monitoring node running nothing (I successfully sshed to it and checked).  But I don't understand what went wrong that caused sct to stop setting up the cluster.

[sct.log](https://github.com/scylladb/scylla-cluster-tests/files/8805945/sct.log)

I ssh'ed into one of the db nodes, and Scylla seems to be running fine there.

**Comment by nyh** [comment]
I removed all the garbage docker processes with
```
docker kill `docker ps -q`
docker rm `docker ps -q -a`
```
And the bug remains - I still get these dockers being restarted constantly.
I ran "docker logs" on one of them, and got:

```
[WARN ] SSH_TUNNEL_HOST will be deprecated in v2.0
[WARN ] SSH_TUNNEL_LOCAL will be deprecated in v2.0
[WARN ] SSH_TUNNEL_REMOTE will be deprecated in v2.0
[WARN ] SSH_HOSTUSER will be deprecated in v2.0
[WARN ] SSH_HOSTNAME will be deprecated in v2.0
[WARN ] SSH_HOSTPORT will be deprecated in v2.0
[ERROR] No SSH Key file found
```

So I think now I know what the bug is. I just don't know how to tell it where the SSH Key file is...

**Comment by fruch** [comment]
> I removed all the garbage docker processes with
> 
> ```
> docker kill `docker ps -q`
> docker rm `docker ps -q -a`
> ```
> 
> And the bug remains - I still get these dockers being restarted constantly. I ran "docker logs" on one of them, and got:
> 
> ```
> [WARN ] SSH_TUNNEL_HOST will be deprecated in v2.0
> [WARN ] SSH_TUNNEL_LOCAL will be deprecated in v2.0
> [WARN ] SSH_TUNNEL_REMOTE will be deprecated in v2.0
> [WARN ] SSH_HOSTUSER will be deprecated in v2.0
> [WARN ] SSH_HOSTNAME will be deprecated in v2.0
> [WARN ] SSH_HOSTPORT will be deprecated in v2.0
> [ERROR] No SSH Key file found
> ```
> 
> So I think now I know what the bug is. I just don't know how to tell it where the SSH Key file is...

working log of the autossh docker image is:
```
[WARN ] SSH_TUNNEL_HOST will be deprecated in v2.0
[WARN ] SSH_TUNNEL_LOCAL will be deprecated in v2.0
[WARN ] SSH_TUNNEL_REMOTE will be deprecated in v2.0
[WARN ] SSH_HOSTUSER will be deprecated in v2.0
[WARN ] SSH_HOSTNAME will be deprecated in v2.0
[WARN ] SSH_HOSTPORT will be deprecated in v2.0
Agent pid 9
Identity added: (stdin) (fruch@scylladb.com)
[INFO] Using autossh 1.4g
[INFO] Tunneling scyllaadm@13.53.198.169:5000 to 127.0.0.1:49156
> autossh -M 0 -N -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -t -t -R 5000:127.0.0.1:49156 -p 22 scyllaadm@13.53.198.169
Warning: Permanently added '13.53.198.169' (ECDSA) to the list of known hosts.
```

**Comment by fruch** [comment]
@nyh 
also check that the key is mounted correctly

```bash
❯ docker inspect perf-alternator-fruch-db-node-a598e28c-3-13.53.198.169-autossh-rsyslog | jq '.[0].Mounts'
[
  {
    "Type": "bind",
    "Source": "/home/fruch/.ssh/scylla-qa-ec2",
    "Destination": "/id_rsa",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  }
]
```

**Comment by nyh** [comment]
I also see
```
[
  {
    "Type": "bind",
    "Source": "/home/nyh/.ssh/scylla-qa-ec2",
    "Destination": "/id_rsa",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  }
]
```

And have this file.
```
-rw-------. 1 nyh nyh 3381 Nov 29  2020 /home/nyh/.ssh/scylla-qa-ec2
```
changing this file to be world-readable didn't help. I don't know what else to try.

**Comment by nyh** [comment]
> 
> ```
> -rw-------. 1 nyh nyh 3381 Nov 29  2020 /home/nyh/.ssh/scylla-qa-ec2
> ```
> 
> changing this file to be world-readable didn't help. I don't know what else to try.

Actually it made a difference in difference of the failure - in the log:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/home/nyh/.ssh/scylla-qa-ec2' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/nyh/.ssh/scylla-qa-ec2": bad permissions
scyllaadm@16.171.52.97: Permission denied (publickey).
```
So the file **is** found.

**Comment by fruch** [comment]
> I suspect that the bind might not work because of relabeling problems (missing -Z option), and checking that suspicion now. I have selinux enabled - do you?

No I don't, too annoying, I've disabled it years ago

**Comment by nyh** [comment]
selinux never ever bothered me except when running SCT :-(
Sadly, I can't even try to fix this problem, because now I started getting a different problem - much earlier during the test run - without having changed anything:

botocore.exceptions.ClientError: An error occurred (InternalError) when calling the RequestSpotInstances operation (reached max retries: 4): An internal error has occurred

I should start printing those meaningless error messages on t-shirts :-(

**Comment by nyh** [comment]
By the way, wondering out loud here (as a thought for the future), was using some guy's random docker image (jnovack/autossh, why do we even trust the code in it?) the best way to run ssh? Why can't we just run ssh on the host, or even on the same docker container that you already have for hydra - and not run 10 additional dockers?

**Comment by nyh** [comment]
Unfortunately fixing autossh (https://github.com/scylladb/scylla-cluster-tests/pull/4851) was not enough. I see now in "docker ps" that all these autossh docker images work without constantly restarting, and initially seemed to be working well, but after an hour I see in their logs:
```
[WARN ] SSH_TUNNEL_HOST will be deprecated in v2.0
[WARN ] SSH_TUNNEL_LOCAL will be deprecated in v2.0
[WARN ] SSH_TUNNEL_REMOTE will be deprecated in v2.0
[WARN ] SSH_HOSTUSER will be deprecated in v2.0
[WARN ] SSH_HOSTNAME will be deprecated in v2.0
[WARN ] SSH_HOSTPORT will be deprecated in v2.0
Agent pid 9
Identity added: (stdin) (fruch@scylladb.com)
[INFO] Using autossh 1.4g
[INFO] Tunneling scyllaadm@34.243.167.175:5000 to 127.0.0.1:49186
> autossh -M 0 -N -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -t -t -R 5000:127.0.0.1:49186 -p 22 scyllaadm@34.243.167.175
Warning: Permanently added '34.243.167.175' (ECDSA) to the list of known hosts.
connect_to 127.0.0.1 port 49186: failed.
connect_to 127.0.0.1 port 49186: failed.
connect_to 127.0.0.1 port 49186: failed.
connect_to 127.0.0.1 port 49186: failed.
connect_to 127.0.0.1 port 49186: failed.
connect_to 127.0.0.1 port 49186: failed.
```
With the last message repeated about 30 times. I don't know what it means. Note that at the point I'm seeing these messages, Hydra has already died, but the autossh docker instances have all remained running (why, by the way?) so maybe this error is just saying that Hydra is gone?

The overall hydra run still fails, with the error message:
```
Exception: No db log from the following nodes:
perf-alternator-nyh-db-node-78ebbf7d-1
perf-alternator-nyh-db-node-78ebbf7d-2
perf-alternator-nyh-db-node-78ebbf7d-3
```

So now I'm back to trying to guess what might be wrong :-(

**Comment by nyh** [comment]
By the way, I wonder where it's this "fruch@scylladb.com" address comes from :-) @fruch

**Comment by fruch** [comment]
> By the way, I wonder where it's this "[fruch@scylladb.com](mailto:fruch@scylladb.com)" address comes from :-) @fruch

Guess who signed that key...

**Comment by fruch** [comment]
Next victim is the syslog-ng docker that this tunnel is pointing to (that 127.0.0.1 49186)

Maybe it's suffering from the same issue, but on it's mounted configuration file ?

**Comment by nyh** [comment]
I also thought maybe I have more selinux-related problems, so I tried to temporarily disable selinux (setenforce 0), and running it, and so far, touch wood. It seems maybe it's running... If it does work I'll try to return selinux and check that syslog-ng thing.

**Comment by nyh** [comment]
Yes, "setenforce 0" fixed the problems and finally I got a working monitoring node. I'll try to provide another patch to make it work without setenforce 0.
