### ISSUE TITLE
Can't run SCT on us-east-2?

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#4864]
@dorlaor asked me to run the new Alternator benchmark on the new i4i instance types. So after I managed to run a test with SCT on i3.2xlarge, I set out to run it on i4i.2xlarge. I decided to use the **us-east-2** region because I noticed that not all regions have the i4i instances, and apparently us-east-2 does.

Anyway, when I configure the test yaml with `instance_type_db: 'i4i.2xlarge'` and set `export SCT_REGION_NAME=us-east-2`, when I try to run it I get the following unintelligible error:

```
< t:2022-06-06 10:40:00,630 f:log.py          l:23   c:sdcm.utils.log       p:ERROR >   File "/home/nyh/scylla-cluster-tests/sdcm/sct_config.py", line 2006, in init_and_verify_sct_config
< t:2022-06-06 10:40:00,630 f:log.py          l:23   c:sdcm.utils.log       p:ERROR >     sct_config = SCTConfiguration()
< t:2022-06-06 10:40:00,630 f:log.py          l:23   c:sdcm.utils.log       p:ERROR >   File "/home/nyh/scylla-cluster-tests/sdcm/sct_config.py", line 1435, in __init__
< t:2022-06-06 10:40:00,630 f:log.py          l:23   c:sdcm.utils.log       p:ERROR >     for key, value in regions_data[region].items():
< t:2022-06-06 10:40:00,630 f:log.py          l:23   c:sdcm.utils.log       p:ERROR > KeyError: 'us-east-2'
```

The sct_config.py line 1435 suggests that "region_data" is missing for "us-east-2". But what does this mean? Is us-east-2 not supported at all? Or I need to supply more information or what?

My request is that,
1. Please tell me how I can run with the new i4i instance types. I don't *have* to use us-east-2 if there's a better region. I just have to run with i4i because @dorlaor asked for it.
2. Please make the error message friendlier - if a certain region is not supported, please say so (and bonus points for listing the regions which _are_ supported). If the user needs to supply additional "data" for the region, please write out which data is missing and how to supply it.

**Comment by nyh** [comment]
I just discovered that us-east-1 also has this instance type (unlike eu-north-1 I had tried earlier), and us-east-1 does with with SCT, so my immediate problem is solved.
It would still nice to know why us-east-2 doesn't work with SCT, and if it officially doesn't work, let's have a better error message for that.

**Comment by fruch** [comment]
@nyh, this basically drill to the set of specific AMIs we are using for loaders and monitor.
we don't have a lookup code for them, but we mention the AMI ids specifically here. (sort of to pin them down)

https://github.com/scylladb/scylla-cluster-tests/blob/master/defaults/aws_config.yaml#L10

the code need to be fixed not to fail on missing key, but it would fail later one, since you won't have AMIs for loader and monitor. (you can supply them by using SCT_AMI_ID_LOADER and SCT_AMI_ID_MONITOR)

**Comment by nyh** [comment]
@fruch, thanks, I see. I think then we have two options which are both better than what we have today:
1. Make SCT work on *every* reasonable region by putting the AMIs there too,
2. us-east-2 will be an error, but will have tell you exactly that us-east-2 is not supported and the list of supported regions are ... (with the list of keys of region_data being printed). If you think it's reasonable that someone might want to manually override the loader and monitor AMIs I guess you can print this too, but I don't know where I would get such AMIs, so it doesn't look (to me) like a useful option.

**Comment by fruch** [comment]
> @fruch, thanks, I see. I think then we have two options which are both better than what we have today:
> 
> 1. Make SCT work on _every_ reasonable region by putting the AMIs there too,

it's matter of find them, and writing them down.

> 2. us-east-2 will be an error, but will have tell you exactly that us-east-2 is not supported and the list of supported regions are ... (with the list of keys of region_data being printed). If you think it's reasonable that someone might want to manually override the loader and monitor AMIs I guess you can print this too, but I don't know where I would get such AMIs, so it doesn't look (to me) like a useful option.

Once the regions_data key access is fixed, the error would be like:
```
>           assert _opt['name'] in self, "{} missing from config for {}".format(_opt['name'], backend)
E           AssertionError: ami_id_loader missing from config for aws
```

**Comment by nyh** [comment]
> > @fruch, thanks, I see. I think then we have two options which are both better than what we have today:
> > 
> > 1. Make SCT work on _every_ reasonable region by putting the AMIs there too,
> 
> it's matter of find them, and writing them down.

Isn't this easy to do?
Moreover, it would be even better to do *both* things I suggested - add a few regions you can easily think about (like us-east-2), and if somebody tries us-east-42 which you didn't think about, print a reasonable error message.

> Once the regions_data key access is fixed, the error would be like:
> 
> ```
> >           assert _opt['name'] in self, "{} missing from config for {}".format(_opt['name'], backend)
> E           AssertionError: ami_id_loader missing from config for aws
> ```

I don't think this is clear enough... What is "config for aws" and what "ami_id_loader"? These phrases have nothing to do with what the I did to run the test, and I wouldn't know what they mean...

Instead, I think something like this will be clearer:

**Region "us-east-2" is not supported. Please set SCT_REGION_NAME to one of the supported regions (us-east-1, eu-north1, ... [whole list here]), or set SCT_AMI_ID_LOADER and SCT_AMI_ID_MONITOR to the relevant AMIs in us-east-2.**
