### ISSUE TITLE
Scylla node running out of space during nodetool upgradesstables [rolling upgrade]

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#4868]
## Installation details

Kernel Version: 4.18.0-365.el8.x86_64

Scylla version (or git commit hash): `5.0.rc1-20220206.891990ec0` with build-id `20d9fa2c6020017f4afdc4941c0cca9c9a29d94a`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-8-db-node-8545a53a-0-4 (34.74.194.129 | 10.142.0.111) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-8545a53a-0-3 (104.196.129.127 | 10.142.0.101) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-8545a53a-0-2 (34.74.70.54 | 10.142.0.47) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-8545a53a-0-1 (34.74.165.210 | 10.142.0.44) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: eu-west-1)

Test: `rolling-upgrade-centos8-test`

Test id: `8545a53a-e312-4dff-80ee-b0e538322bfb`

Test name: `rolling-upgrade/rolling-upgrade-centos8-test`

Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cf1a7533b0af12a4484921aa18db289b82b4f94/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

Upgrade destination build: http://downloads.scylladb.com/unstable/scylla/master/rpm/centos/2022-03-16T04:02:25Z/scylla.repo

As part of the test, node 3 was upgraded once (successfully) and rollbacked. Afterwards, it was upgraded a second time . At first, the upgrade process went smoothly. However, when the test attempted to upgrade the sstables, the node ran out of space and the presedure failed:
```
< t:2022-03-26 09:18:46,779 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  upgradesstables -a"...
< t:2022-03-26 09:18:46,780 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-26 09:18:46.778: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=27a66bc4-1cfb-4463-b97e-06f133176311: nodetool_command=upgradesstables node=rolling-upgrade-master-centos-8-db-node-8545a53a-0-3
...
2022-03-26T09:24:47+00:00 rolling-upgrade-master-centos-8-db-node-8545a53a-0-3 !    INFO | [shard 4] compaction_manager - Asked to stop
2022-03-26T09:24:47+00:00 rolling-upgrade-master-centos-8-db-node-8545a53a-0-3 !    INFO | [shard 4] compaction_manager - Stopping 1 tasks for 0 ongoing compactions due to shutdown
2022-03-26T09:24:47+00:00 rolling-upgrade-master-centos-8-db-node-8545a53a-0-3 !     ERR | [shard 4] compaction_manager - Upgrade task 0x602008764f10 for table ks1.table1_scylla_cdc_log [0x60200088a800]: failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8545a53a-e312-4dff-80ee-b0e538322bfb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8545a53a-e312-4dff-80ee-b0e538322bfb)
- Show all stored logs command: `$ hydra investigate show-logs 8545a53a-e312-4dff-80ee-b0e538322bfb`

## Logs:
- **db-cluster-8545a53a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/db-cluster-8545a53a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/db-cluster-8545a53a.tar.gz)
- **monitor-set-8545a53a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/monitor-set-8545a53a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/monitor-set-8545a53a.tar.gz)
- **loader-set-8545a53a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/loader-set-8545a53a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/loader-set-8545a53a.tar.gz)
- **sct-runner-8545a53a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/sct-runner-8545a53a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8545a53a-e312-4dff-80ee-b0e538322bfb/20220326_093121/sct-runner-8545a53a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/127/)

**Comment by roydahan** [comment]
@enaydanov this is another case where we don't clean snapshots.
