### ISSUE TITLE
"Too many in flight hints" on large-partitions load

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#4878]
Might be reproduced in rc5 different test as well:
```
$ grep -i 'Too many in flight hints' -B 7 -A 5 error.log 
errors:

Stress command completed with bad status 1: 2022/05/30 10:44:35 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=
2022-05-30 10:53:01.360: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=0cfcfd05-d2e8-425d-ad0c-a8bbda08fe2b duration=56m40s: node=Node ics-longevity-toggle-strategy-large-loader-node-a411a4b1-3 [54.246.23.194 | 10.0.3.215] (seed: False)
stress_cmd=scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=400 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1601 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=90s -error-at-row-limit 1000
errors:

Stress command completed with bad status 1: 2022/05/30 10:01:21 Too many in flight hints: 10488620
2022/05/30 10:01:21 Too many in flight hints:
2022-05-30 10:53:02.812 &lt;2022-05-30 10:44:58.000&gt;: (ScyllaBenchLogEvent Severity.ERROR) period_type=one-time event_id=33894371-7b54-4b3d-a6ee-a004457b3c23: type=ConsistencyError regex=received only line_number=5926 node=Node ics-longevity-toggle-strategy-large-loader-node-a411a4b1-1 [34.244.188.165 | 10.0.0.198] (seed: False)
2022/05/30 10:44:58 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2022-05-30 10:53:03.258: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=33894371-7b54-4b3d-a6ee-a004457b3c23 duration=40m21s: node=Node ics-longevity-toggle-strategy-large-loader-node-a411a4b1-1 [34.244.188.165 | 10.0.0.198] (seed: False)
stress_cmd=scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=1000 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1001 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -iterations=20 -timeout=90s -error-at-row-limit 1000
errors:

Stress command completed with bad status 1: 2022/05/30 10:12:55 Too many in flight hints: 10510695
2022/05/30 10:12:55 Too many in flight hints:
2022-05-30 10:53:05.862: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=a6b79665-75e0-48a5-a138-a549c7d459ba duration=59m5s: node=Node ics-longevity-toggle-strategy-large-loader-node-a411a4b1-1 [34.244.188.165 | 10.0.0.198] (seed: False)
stress_cmd=scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=300 -clustering-row-count=200000 -clustering-row-size=uniform:10..10240 -partition-offset=1001 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=90s -error-at-row-limit 1000
errors:

Stress command completed with bad status 1: 2022/05/30 10:12:55 Too many in flight hints: 10510695
2022/05/30 10:12:55 Too many in flight hints:
2022-05-30 10:54:44.464: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=1e22ecd1-c86b-46c8-97d2-0b2e3dee9ae9 duration=56m3s: node=Node ics-longevity-toggle-strategy-large-loader-node-a411a4b1-1 [34.244.188.165 | 10.0.0.198] (seed: False)
stress_cmd=scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=15 -clustering-row-count=100000 -partition-offset=15 -clustering-row-size=uniform:3072..5120 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=90s -iterations 10 -validate-data -error-at-row-limit 1000
errors:
```

## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `2022.1~rc5-20220515.6a1e89fbb` with build-id `5cecadda59974548befb4305363bf374631fc3e1`
Cluster size: 5 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- ics-longevity-toggle-strategy-large-db-node-a411a4b1-5 (54.75.53.162 | 10.0.1.171) (shards: 12)
- ics-longevity-toggle-strategy-large-db-node-a411a4b1-4 (54.195.159.112 | 10.0.2.217) (shards: 12)
- ics-longevity-toggle-strategy-large-db-node-a411a4b1-3 (18.202.218.245 | 10.0.0.236) (shards: 12)
- ics-longevity-toggle-strategy-large-db-node-a411a4b1-2 (54.170.149.237 | 10.0.0.140) (shards: 12)
- ics-longevity-toggle-strategy-large-db-node-a411a4b1-1 (34.241.252.30 | 10.0.1.92) (shards: 12)

OS / Image: `ami-02032eaf873ada3b0` (aws: eu-west-1)

Test: `ics-longevity-toggle-strategy-large-partitions-24h-test`
Test id: `a411a4b1-e683-4ac7-84ad-1b89b8caa6f9`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/ICS/ics-longevity-toggle-strategy-large-partitions-24h-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60c56c3aec1acc9df1b3922952434be84757713/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a411a4b1-e683-4ac7-84ad-1b89b8caa6f9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a411a4b1-e683-4ac7-84ad-1b89b8caa6f9)
- Show all stored logs command: `$ hydra investigate show-logs a411a4b1-e683-4ac7-84ad-1b89b8caa6f9`

## Logs:
- **db-cluster-a411a4b1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/db-cluster-a411a4b1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/db-cluster-a411a4b1.tar.gz)
- **monitor-set-a411a4b1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/monitor-set-a411a4b1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/monitor-set-a411a4b1.tar.gz)
- **loader-set-a411a4b1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/loader-set-a411a4b1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/loader-set-a411a4b1.tar.gz)
- **sct-runner-a411a4b1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/sct-runner-a411a4b1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a411a4b1-e683-4ac7-84ad-1b89b8caa6f9/20220531_062113/sct-runner-a411a4b1.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-toggle-strategy-large-partitions-24h-test/3/)

_Originally posted by @yarongilor in https://github.com/scylladb/scylla/issues/10702#issuecomment-1147510114_

**Comment by yarongilor** [comment]
rerunning with rc7 to see if it is reproduced..
https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-toggle-strategy-large-partitions-24h-test/

**Comment by yarongilor** [comment]
@roydahan , in rc7 a lot of "Too many in flight hints" messages were found in log, but the scylla-bench failures for that are not reproduced (s-b probably ran ok for ~ 5 hours until test failed) . should i open a new issue anyway?

**Comment by yarongilor** [comment]
opened https://github.com/scylladb/scylla-enterprise/issues/2286
