### ISSUE TITLE
rebuild_streaming_err: nodetool rebuild was started after hard reboot BEFORE Scylla started up

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4888]
## Installation details

Kernel Version: 5.13.0-1028-aws
Scylla version (or git commit hash): `5.1.dev-20220609.f06012922325` with build-id `006b326429f53f1a7584be4fbe23b27442cbe2eb`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-f9ec8333-9 (34.250.158.24 | 10.0.3.197) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-8 (3.250.32.91 | 10.0.3.201) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-7 (3.250.32.98 | 10.0.0.38) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-6 (54.74.128.0 | 10.0.2.203) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-5 (54.154.184.140 | 10.0.1.190) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-4 (34.245.56.237 | 10.0.1.180) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-3 (18.202.224.31 | 10.0.1.53) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-2 (54.217.1.112 | 10.0.2.241) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-11 (34.242.192.66 | 10.0.2.103) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-10 (54.76.32.79 | 10.0.3.83) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-f9ec8333-1 (34.247.83.108 | 10.0.2.97) (shards: 14)

OS / Image: `ami-079c11ce7649dc53e` (aws: eu-west-1)

Test: `longevity-50gb-3days`
Test id: `f9ec8333-2260-4dd1-9864-9b9f8470ed75`
Test name: `scylla-master/longevity/longevity-50gb-3days`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/84a6efb47a93f7dd81f0a19e8a83f0544730e589/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

Argus link:
http://13.48.103.68/test/a2b90d5a-c79b-4f9d-a9a7-98974e88c866/runs?additionalRuns[]=f9ec8333-2260-4dd1-9864-9b9f8470ed75

## Issue description

Nemesis `disrupt_rebuild_streaming_err` failed with error:
```
2022-06-11 07:27:26.282: (NodetoolEvent Severity.WARNING) period_type=end event_id=e6a5e4f8-0e67-4102-ba45-e57a6be95220 duration=2m46s: nodetool_command=rebuild node=longevity-tls-50gb-3d-master-db-node-f9ec8333
-4 errors=['Encountered a bad command exit code!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  rebuild "\n\nExit code: 1\n\nStdout:\n\n\n\nStderr:\n\nnodetool: Failed to connect to \'127.0.0.1:7
199\' - ConnectException: \'Connection refused (Connection refused)\'.\n\n']
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2644, in run_nodetool
    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild "

Exit code: 1

Stdout:



Stderr:

nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
```

`nodetool rebuild` was started after hard reboot BEFORE Scylla started up.
Starting Scylla Server at `07:27:22`:
```
Jun 11 07:26:26 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: scylla-server.service: Succeeded.
Jun 11 07:26:26 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: Stopped Scylla Server.
Jun 11 07:26:26 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: scylla-image-setup.service: Succeeded.
Jun 11 07:26:26 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: Stopped Scylla Cloud Image Setup service.
-- Reboot --
Jun 11 07:27:22 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: Condition check resulted in Scylla Cloud Image Setup service being skipped.
Jun 11 07:27:22 longevity-tls-50gb-3d-master-db-node-f9ec8333-4 systemd[1]: Starting Scylla Server...
```

But nodetool was started even before - `07:24:39.884`:
```
2022-06-11 07:24:39.884: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=e6a5e4f8-0e67-4102-ba45-e57a6be95220: nodetool_command=rebuild node=longevity-tls-50gb-3d-master-db-node-f9ec8333-4
```

Also we have to fix this one https://github.com/scylladb/scylla-cluster-tests/issues/4819. it also will cause to failure

- Restore Monitor Stack command: `$ hydra investigate show-monitor f9ec8333-2260-4dd1-9864-9b9f8470ed75`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f9ec8333-2260-4dd1-9864-9b9f8470ed75)
- Show all stored logs command: `$ hydra investigate show-logs f9ec8333-2260-4dd1-9864-9b9f8470ed75`

## Logs:
- **db-cluster-f9ec8333.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/db-cluster-f9ec8333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/db-cluster-f9ec8333.tar.gz)
- **monitor-set-f9ec8333.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/monitor-set-f9ec8333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/monitor-set-f9ec8333.tar.gz)
- **loader-set-f9ec8333.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/loader-set-f9ec8333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/loader-set-f9ec8333.tar.gz)
- **normal-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/normal-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/normal-f9ec8333.log.tar.gz)
- **summary-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/summary-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/summary-f9ec8333.log.tar.gz)
- **events-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/events-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/events-f9ec8333.log.tar.gz)
- **output-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/output-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/output-f9ec8333.log.tar.gz)
- **debug-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/debug-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/debug-f9ec8333.log.tar.gz)
- **sct-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/sct-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/sct-f9ec8333.log.tar.gz)
- **error-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/error-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/error-f9ec8333.log.tar.gz)
- **critical-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/critical-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/critical-f9ec8333.log.tar.gz)
- **raw_events-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/raw_events-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/raw_events-f9ec8333.log.tar.gz)
- **warning-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/warning-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/warning-f9ec8333.log.tar.gz)
- **argus-f9ec8333.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/argus-f9ec8333.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9ec8333-2260-4dd1-9864-9b9f8470ed75/20220613_043149/argus-f9ec8333.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/140/)

**Comment by KnifeyMoloko** [comment]
Closing with: https://github.com/scylladb/scylla-cluster-tests/pull/4953
