### ISSUE TITLE
C-S failing during `RestartWithResharding` in `scale-many-clients-4h-test`

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4939]
## Installation details

Kernel Version: 5.13.0-1029-aws
Scylla version (or git commit hash): `5.0~rc8-20220612.f28542a71` with build-id `85cf87619b93155a574647ec252ce5a043c7fe77`
Cluster size: 4 nodes (i3.metal)

Scylla Nodes used in this run:
- longevity-many-clients-4h-5-0-db-node-5ef689db-4 (52.31.156.144 | 10.0.3.178) (shards: 70)
- longevity-many-clients-4h-5-0-db-node-5ef689db-3 (54.77.193.218 | 10.0.3.1) (shards: 70)
- longevity-many-clients-4h-5-0-db-node-5ef689db-2 (34.252.18.209 | 10.0.2.215) (shards: 70)
- longevity-many-clients-4h-5-0-db-node-5ef689db-1 (34.244.54.151 | 10.0.2.204) (shards: 70)

OS / Image: `ami-088626a20ac6084a7` (aws: eu-west-1)

Test: `scale-many-clients-4h-test`
Test id: `5ef689db-27ce-42fd-889d-255490bc5644`
Test name: `scylla-5.0/scale/scale-many-clients-4h-test`
Test config file(s):

- [longevity-many-clients-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/09eb603bcf7ef2ee88191ed4f3b9e458e2198816/test-cases/scale/longevity-many-clients-4h.yaml)

## Issue description

**>>>>>>>**
While running the `scale-many-clients`we started CassandraStress on the loaders with the c-s command:

```
Running command "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=F2DDEMVU168M5GCW0DC5; cassandra-stress write cl=QUORUM duration=240m -schema keyspace=keyspace28 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=4 -pop seq=1..20971520 -col 'n=FIXED(2) size=FIXED(256)' -log interval=5 -node 10.0.2.204 -errors skip-unsupported-columns"
```

While running `RestartWithResharding` we stop one fo the Scylla db nodes:
```
< t:2022-06-21 13:53:08,492 f:decorators.py   l:112  c:sdcm.utils.decorators p:DEBUG > BEGIN: stop_scylla <AWSNode>
< t:2022-06-21 13:53:08,492 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo systemctl stop scylla-server.service"...
```

This, predictably, leads to the c-s client not being able to connect to the stopped node:
```
< t:2022-06-21 13:53:09,000 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.TransportException: [ip-10-0-2-204.eu-west-1.compute.internal/10.0.2.204:9042] Connection has been closed
```

Wich leads to c-s completing with a bad return code:

```
2022-06-21 13:53:43.832: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=bd970120-887f-4440-8ffc-29a209c9f9ef duration=17s: node=Node longevity-many-clients-4h-5-0-loader-node-5ef689db-7 [34.254.181.87 | 10.0.0.71] (seed: False)
stress_cmd=cassandra-stress write cl=QUORUM duration=240m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=4 -pop seq=1..20971520 -col 'n=FIXED(2) size=FIXED(256)' -log interval=5
errors:
Stress command completed with bad status 1: WARN  13:53:28,078 Error creating netty channel to /10.0.2.204:9042
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5ef689db-27ce-42fd-889d-255490bc5644`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5ef689db-27ce-42fd-889d-255490bc5644)
- Show all stored logs command: `$ hydra investigate show-logs 5ef689db-27ce-42fd-889d-255490bc5644`

## Logs:
- **db-cluster-5ef689db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/db-cluster-5ef689db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/db-cluster-5ef689db.tar.gz)
- **monitor-set-5ef689db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/monitor-set-5ef689db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/monitor-set-5ef689db.tar.gz)
- **loader-set-5ef689db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/loader-set-5ef689db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/loader-set-5ef689db.tar.gz)
- **sct-runner-5ef689db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/sct-runner-5ef689db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/sct-runner-5ef689db.tar.gz)
- **parallel-timelines-report-5ef689db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/parallel-timelines-report-5ef689db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ef689db-27ce-42fd-889d-255490bc5644/20220621_141336/parallel-timelines-report-5ef689db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/scale/job/scale-many-clients-4h-test/4/)

**Comment by fgelcer** [comment]
if we are using shard aware driver, and the c-s command started before we restarted the node, and considering we are using `cl=QUORUM` this failure is not expected, as we should still have quorum to write.

**Comment by fruch** [comment]
`WARN  13:53:28,078 Error creating netty channel to /10.0.2.204:9042`
is just happens to be the first line with `error` string in it, it doesn't mean the stress command failed cause of that (the error itself was connection refused)

the real problem is that by default we are pass only one node to the stress command:
`-node 10.0.2.204`

since that in this test case, we keep creating new stress command during the run, while nemesis are working.
we need to change this default and pass to the stress commands all the nodes at contact points.

it was happening also for 5000 tables test case
https://github.com/scylladb/scylla-cluster-tests/pull/4684

@roydahan wanted to wait with backporting, so we never backported it

also @KnifeyMoloko I'm not sure that fix would cover you test case, we probably need to start doing that by default regardless

**Comment by fruch** [comment]
> @fruch the solution to the problem you raised when we start new stress commands during the test is to get the a live node IP at that moment, not necessarily all nodes IPs. Also, it wouldn't help if we take the original nodes IPs from the begining of the test, because they may all have been replaced by that point. So, one node IP but relevant one is the actual solution.
> 
> @KnifeyMoloko / @fgelcer please find the actual problem because I don't see it....

I don't understand why not adding all the known nodes (at the time of starting the stress thread, we don't and shouldn't cache it) isn't good ? why bet with which is the live node ? this is how we suggest to customers to have multiple contact point when they initialize the driver, why shouldn't we do the same ?

**Comment by roydahan** [comment]
List or one node should be the same AFAIK.
As long as we provide the "live nodes at that moment" I'm fine with it.
But again, I don't think this is the issue here.

**Comment by fruch** [comment]
> List or one node should be the same AFAIK. As long as we provide the "live nodes at that moment" I'm fine with it. But again, I don't think this is the issue here.

It's the issue here, the stress is supplies with a node that's currently down (cause it's default is to pick node-1, this happens across most of the stress code)

Again to avoid figuring out which node is alive we should just supply them all, that driver should figure it out.
