### ISSUE TITLE
Provision resources jenkins stage is not failing on error

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4950]
When there's an error during jenkins 'provision resources' stage it should be marked as failed and should not continue the test. Currently it is progressing to sct test stage which then fails.
Example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/45/

**Comment by soyacz** [comment]
Yes, we should collect logs - need to remember about it when fixing this issue.

**Comment by fruch** [comment]
Needless to say that not having logs is much more serve the the fall through to next stages, which might be confusing a bit but tolerable.

**Comment by soyacz** [comment]
this is already done.
