### ISSUE TITLE
Rebuild is reported as "in progress" although it was expected to get terminated by then

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#4954]
## Installation details

Kernel Version: 5.13.0-1017-aws

Scylla version (or git commit hash): `5.0~rc2-20220316.839d9ef41` with build-id `1319e7e64335b7e5c7531f773e92ef997b6c51ba`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-5-0-db-node-3881062c-9 (54.195.190.69 | 10.0.0.169) (shards: 16)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-8 (34.249.29.134 | 10.0.3.15) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-7 (52.213.81.129 | 10.0.0.214) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-6 (54.246.16.168 | 10.0.2.174) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-5 (34.243.175.97 | 10.0.0.120) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-4 (34.245.138.220 | 10.0.3.141) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-31 (54.75.109.84 | 10.0.0.45) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-30 (34.245.123.43 | 10.0.2.83) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-3 (54.220.81.180 | 10.0.3.110) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-29 (34.243.209.146 | 10.0.1.35) (shards: 16)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-28 (34.251.223.213 | 10.0.1.1) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-27 (34.246.194.35 | 10.0.1.66) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-26 (34.245.131.249 | 10.0.3.238) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-25 (63.35.234.40 | 10.0.1.187) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-24 (3.250.121.28 | 10.0.2.28) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-23 (54.247.49.133 | 10.0.0.35) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-22 (52.50.74.171 | 10.0.3.60) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-21 (54.195.183.149 | 10.0.3.220) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-20 (3.249.249.193 | 10.0.0.80) (shards: 16)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-2 (34.251.61.72 | 10.0.1.10) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-19 (34.247.66.31 | 10.0.0.46) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-18 (52.48.169.233 | 10.0.2.172) (shards: 16)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-17 (34.240.129.153 | 10.0.2.223) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-16 (34.242.235.139 | 10.0.2.4) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-15 (3.250.78.213 | 10.0.3.115) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-14 (54.246.194.131 | 10.0.3.235) (shards: 16)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-13 (63.32.45.100 | 10.0.0.184) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-12 (54.194.56.111 | 10.0.3.242) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-11 (34.244.28.81 | 10.0.3.92) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-10 (3.250.82.152 | 10.0.0.177) (shards: 14)
- longevity-tls-50gb-3d-5-0-db-node-3881062c-1 (3.250.67.220 | 10.0.1.171) (shards: 14)

OS / Image: `ami-07df681f83cd78172` (aws: eu-west-1)

Test: `longevity-50gb-3days-test`

Test id: `3881062c-88f0-48ba-89f0-5fffbad30fdc`

Test name: `longevity/longevity-50gb-3days-test`

Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/234f79a81bc97d0e44c3ab51441017b646fdf393/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

At `2022-03-18 11:36:53` a `disrupt_rebuild_streaming_err` nemesis started on node 5. The nemesis starts a rebuild, interrupts it by rebooting the node after the streaming starts and at the end rebuilds it again (to recover the node after the reboot).

At first things were going as planned with the rebuild starting and the reboot interrupting it:
```
2022-03-18T11:40:20+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] storage_service - rebuild from dc: (any dc)
2022-03-18T11:40:20+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={replace}
2022-03-18T11:40:46+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] init - Signal received; shutting down
2022-03-18T11:40:46+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 ! WARNING |  [shard 0] storage_service - Error while rebuilding node: seastar::sleep_aborted (Sleep is aborted)
```
However, after the machine was rebooted and scylla has started, the attempted (second) rebuild failed since there was already a rebuild process running:
```
< t:2022-03-18 11:43:50,536 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild "...
< t:2022-03-18 11:43:58,665 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild "; Exit status: 1
< t:2022-03-18 11:43:58,665 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > STDOUT: nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation rebuild is in progress, try again)
```
And that seem to be because after scylla has started again a rebuild has started as well, even though we didn't execute it:
```
2022-03-18T11:40:50+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc2-0.20220316.839d9ef41 shutdown complete.
...
2022-03-18T11:43:07+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] gossip - Gossip not settled after 1 polls.
2022-03-18T11:43:07+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] storage_service - rebuild from dc: (any dc)
2022-03-18T11:43:07+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={replace}
2022-03-18T11:43:07+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO | Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:config' at Fri, 18 Mar 2022 11:43:06 +0000. Up 30.28 seconds.
...
2022-03-18T11:43:35+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc2-0.20220316.839d9ef41 initialization completed.
...
2022-03-18T11:45:42+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] range_streamer - Rebuild succeeded, took 152 seconds, nr_ranges_remaining=0
2022-03-18T11:45:42+00:00 longevity-tls-50gb-3d-5-0-db-node-3881062c-5 !    INFO |  [shard 0] storage_service - Streaming for rebuild successful
```

The nemesis has ran 4 times in this longevity run, and it only failed once, giving it 25% consistency.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3881062c-88f0-48ba-89f0-5fffbad30fdc`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3881062c-88f0-48ba-89f0-5fffbad30fdc)
- Show all stored logs command: `$ hydra investigate show-logs 3881062c-88f0-48ba-89f0-5fffbad30fdc`

## Logs:
- **db-cluster-3881062c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/db-cluster-3881062c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/db-cluster-3881062c.tar.gz)
- **monitor-set-3881062c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/monitor-set-3881062c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/monitor-set-3881062c.tar.gz)
- **loader-set-3881062c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/loader-set-3881062c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/loader-set-3881062c.tar.gz)
- **normal-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/normal-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/normal-3881062c.log.tar.gz)
- **summary-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/summary-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/summary-3881062c.log.tar.gz)
- **events-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/events-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/events-3881062c.log.tar.gz)
- **output-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/output-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/output-3881062c.log.tar.gz)
- **debug-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/debug-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/debug-3881062c.log.tar.gz)
- **sct-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/sct-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/sct-3881062c.log.tar.gz)
- **error-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/error-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/error-3881062c.log.tar.gz)
- **critical-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/critical-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/critical-3881062c.log.tar.gz)
- **raw_events-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/raw_events-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/raw_events-3881062c.log.tar.gz)
- **warning-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/warning-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/warning-3881062c.log.tar.gz)
- **email_data-3881062c.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/email_data-3881062c.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/email_data-3881062c.json.tar.gz)
- **argus-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/argus-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/argus-3881062c.log.tar.gz)
- **left_processes-3881062c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/left_processes-3881062c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3881062c-88f0-48ba-89f0-5fffbad30fdc/20220320_173722/left_processes-3881062c.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-50gb-3days-test/2/)

**Comment by asias** [comment]
> My guess that it the first `nodetool rebuild` failed with RetryableNetworkException and retried again.

@enaydanov Thanks for figuring this out.

I saw your SCT PR. But could we add log in sct to 100% sure the rebuild is because of the retry? I want to see the retry log.

**Comment by juliayakovlev** [comment]
duplicate of https://github.com/scylladb/scylla-cluster-tests/issues/4819
