### ISSUE TITLE
config backup files are not recovered for RHEL in upgrade tests

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4987]
When doing upgrade tests `*.autobackup` files are not recovered after Scylla installation.
It is causing errors when doing upgrade from OSS to enterprise version because `yum remove` moves configs to `.rpmsave` and new installation is creating default ones.

**Comment by soyacz** [comment]
Looks like problem is here: https://github.com/scylladb/scylla-cluster-tests/blob/master/upgrade_test.py#L92
there should be `&&` instead of `||`

**Comment by fgelcer** [comment]
the curious part is that this code is in place since July 2021 and we haven't seen this failure before...

**Comment by fruch** [comment]
> the curious part is that this code is in place since July 2021 and we haven't seen this failure before...

keep in mind it's only relevant to enterprise, and seem like it was fixed, but only for 2021.1.
https://github.com/scylladb/scylla-cluster-tests/pull/3822

we should STOP doing fixes like that straight into release branches...

**Comment by fgelcer** [comment]
@soyacz , so @fruch found that the correct fix for it was in place only for `branch-2021.1` instead of master.. you can either re-submit your fix (including the other missing part of it) or try to backport the relevant fix to master, and then to `branch-2022.1`
