### ISSUE TITLE
SCT raised BACKTRACE event and not ReactorStall warning

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5016]
## Installation details

Kernel Version: 4.18.0-394.el8.x86_64

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-centos8-jenkins-db-node-713ba59a-0-1 (34.74.132.101 | 10.142.0.86) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `artifacts-centos8-nonroot-test`
Test id: `713ba59a-e212-42e3-be12-1946c1db0e55`
Test name: `scylla-enterprise/artifacts-offline-install/artifacts-centos8-nonroot-test`
Test config file(s):

- [centos8.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/78ce567cd6f87db87e006cfa71b23ea73ece33c0/test-cases/artifacts/centos8.yaml)

## Issue description

Seem like the log parsing missing the start of the line:
```
2022-07-14 09:28:34.397: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=95b1b4e2-327d-496b-8972-bdc122138f80: type=BACKTRACE regex=backtrace line_number=1433 node=artifacts-centos8-jenkins-db-node-713ba59a-0-1
eactor stalled for 32 ms on shard 1. Backtrace: 0x4e0d6e2 0x4e0c340 0x4e0d5f0 0x7f230af20a1f 0x14de339 0x14dc3b0 0x14d680c 0x14d5ff6 0x14e4d52 0x14d0238 0x1aec3c6 0x508c7e1
0x4e0d6e2
0x4e0c340
0x4e0d5f0
0x7f230af20a1f
0x14de339
0x14dc3b0
0x14d680c
0x14d5ff6
0x14e4d52
0x14d0238
0x1aec3c6
0x508c7e1
```

logs lines:
```
INFO  2022-07-14 09:28:34,095 [shard 1] database - Flushing non-system tables
Reactor stalled for 32 ms on shard 1. Backtrace: 0x4e0d6e2 0x4e0c340 0x4e0d5f0 0x7f230af20a1f 0x14de339 0x14dc3b0 0x14d680c 0x14d5ff6 0x14e4d52 0x14d0238 0x1aec3c6 0x508c7e1
kernel callstack:
INFO  2022-07-14 09:28:35,102 [shard 1] database - Flushed non-system tables
```

SCT log:
```
< t:2022-07-14 09:28:34,389 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Reactor stalled for 32 ms on shard 1. Backtrace: 0x4e0d6e2 0x4e0c340 0x4e0d5f0 0x7f230af20a1f 0x14de339 0x14dc3b0 0x14d680c 0x14d5ff6 0x14e4d52 0x14d0238 0x1aec3c6 0x508c7e1
< t:2022-07-14 09:28:34,398 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/jenkins/slave/workspace/scylla-enterprise/artifacts-offline-install/artifacts-centos8-nonroot-test/scylla-cluster-tests/20220714-091641-495449,id=0x7f9dfebab310,default=True]
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-07-14 09:28:34.397: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=95b1b4e2-327d-496b-8972-bdc122138f80: type=BACKTRACE regex=backtrace line_number=1433 node=artifacts-centos8-jenkins-db-node-713ba59a-0-1
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > eactor stalled for 32 ms on shard 1. Backtrace: 0x4e0d6e2 0x4e0c340 0x4e0d5f0 0x7f230af20a1f 0x14de339 0x14dc3b0 0x14d680c 0x14d5ff6 0x14e4d52 0x14d0238 0x1aec3c6 0x508c7e1
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x4e0d6e2
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x4e0c340
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x4e0d5f0
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x7f230af20a1f
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14de339
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14dc3b0
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14d680c
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14d5ff6
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14e4d52
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x14d0238
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x1aec3c6
< t:2022-07-14 09:28:34,401 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 0x508c7e1
```

clearly it's SCT parsing code, that removed the first letter of that line, before applying the event regexs

- Restore Monitor Stack command: `$ hydra investigate show-monitor 713ba59a-e212-42e3-be12-1946c1db0e55`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=713ba59a-e212-42e3-be12-1946c1db0e55)
- Show all stored logs command: `$ hydra investigate show-logs 713ba59a-e212-42e3-be12-1946c1db0e55`

## Logs:
- **db-cluster-713ba59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/713ba59a-e212-42e3-be12-1946c1db0e55/20220714_093233/db-cluster-713ba59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/713ba59a-e212-42e3-be12-1946c1db0e55/20220714_093233/db-cluster-713ba59a.tar.gz)
- **sct-runner-713ba59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/713ba59a-e212-42e3-be12-1946c1db0e55/20220714_093233/sct-runner-713ba59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/713ba59a-e212-42e3-be12-1946c1db0e55/20220714_093233/sct-runner-713ba59a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/artifacts-offline-install/job/artifacts-centos8-nonroot-test/276/)

**Comment by fruch** [comment]
I think that this is the cause:
```
self._last_log_position = db_file.tell() + 1
```

but it would be have to test specifically

**Comment by fgelcer** [comment]
> I think that this is the cause:
> 
> ```python
> self._last_log_position = db_file.tell() + 1
> ```
> 
> but it would be have to test specifically

is it the reason why the word `Reactor` is cut of?

like in the event's next line:
`eactor stalled for`

**Comment by fruch** [comment]
> > I think that this is the cause:
> > ```python
> > self._last_log_position = db_file.tell() + 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it would be have to test specifically
> 
> is it the reason why the word `Reactor` is cut of?
> 
> like in the event's next line: `eactor stalled for`

I've seen it a lot that log line are cut, but it mostly fall on the date and doesn't harm anything.
in this case it did

again testing exactly the case of writing to the file while reading it, it's a bit trick to unittest.

**Comment by fgelcer** [comment]
so for that specific event, we can add to the reactor stall event's regex:
current:
```
regex="Reactor stalled"
```

can be added"
```
regex="Reactor stalled| stalled for"
```

**Comment by fruch** [comment]
I think it would be better to solve/test the root cause

making complex regex is problem, keep in mind we run those on every single log line.
