### ISSUE TITLE
SDKMAN workaround failed to install, failing the test

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#5018]
## Installation details

Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-9b8be9ea-0-6 (34.138.123.230 | 10.142.0.242) (shards: 14)
- longevity-10gb-3h-master-db-node-9b8be9ea-0-5 (35.196.59.122 | 10.142.0.241) (shards: 14)
- longevity-10gb-3h-master-db-node-9b8be9ea-0-4 (34.73.160.207 | 10.142.0.203) (shards: 14)
- longevity-10gb-3h-master-db-node-9b8be9ea-0-3 (34.148.145.26 | 10.142.0.81) (shards: 14)
- longevity-10gb-3h-master-db-node-9b8be9ea-0-2 (34.148.134.226 | 10.142.0.68) (shards: 14)
- longevity-10gb-3h-master-db-node-9b8be9ea-0-1 (35.196.89.224 | 10.142.0.38) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/3518016154924828255` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `9b8be9ea-382b-4041-a11e-2962091b19fc`
Test name: `scylla-master/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a2d988688a1be6b69f953e1a66572a2f6736347a/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**
the issue here is that the installation of the `SDKMAN` (workaround to the JDK issue we had because of newer version, before it was fixed in all Scylla versions) failed on the monitor, and failed the whole setup and the test.

```
2022-07-12 06:06:10.798: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=937715e0-e092-4676-beba-a07c1c6ce337, source=LongevityTest.SetUp()
exception=[Node longevity-10gb-3h-master-monitor-node-9b8be9ea-0-1 [35.229.32.153 | 10.142.0.248] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'bash -cxe "\nsource "/home/$USER/.sdkman/bin/sdkman-init.sh"\nsed -i s/sdkman_auto_answer=false/sdkman_auto_answer=true/  ~/.sdkman/etc/config\nsed -i s/sdkman_auto_env=false/sdkman_auto_env=true/  ~/.sdkman/etc/config\nsdk install java 8.0.302-open\nsdk default java 8.0.302-open\n"'
Exit code: 1
Stdout:
* 2022-07-06: gradle 7.5-rc-4 available on SDKMAN!
================================================================================[0m
Downloading: java 8.0.302-open
In progress...
Download has failed, aborting!
Can not install java 8.0.302-open at this time...
Stderr:
+ __sdkman_validate_binary_input /home/scylla-test/.sdkman/tmp/java-8.0.302-open.bin
+ tar tzf /home/scylla-test/.sdkman/tmp/java-8.0.302-open.bin
+ echo 'Download has failed, aborting!'
+ echo ''
+ echo 'Can not install java 8.0.302-open at this time...'
+ return 1
+ return 1
+ return 1
+ return 1
+ return 1
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3512, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4947, in node_setup
self.install_scylla_manager(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4955, in install_scylla_manager
node.install_scylla(scylla_repo=scylla_repo)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2055, in install_scylla
self.remoter.run(shell_script_cmd("""
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -cxe "\nsource "/home/$USER/.sdkman/bin/sdkman-init.sh"\nsed -i s/sdkman_auto_answer=false/sdkman_auto_answer=true/  ~/.sdkman/etc/config\nsed -i s/sdkman_auto_env=false/sdkman_auto_env=true/  ~/.sdkman/etc/config\nsdk install java 8.0.302-open\nsdk default java 8.0.302-open\n"'
Exit code: 1
Stdout:
* 2022-07-06: gradle 7.5-rc-4 available on SDKMAN!
================================================================================[0m
Downloading: java 8.0.302-open
In progress...
Download has failed, aborting!
Can not install java 8.0.302-open at this time...
Stderr:
+ __sdkman_validate_binary_input /home/scylla-test/.sdkman/tmp/java-8.0.302-open.bin
+ tar tzf /home/scylla-test/.sdkman/tmp/java-8.0.302-open.bin
+ echo 'Download has failed, aborting!'
+ echo ''
+ echo 'Can not install java 8.0.302-open at this time...'
+ return 1
+ return 1
+ return 1
+ return 1
+ return 1
```

important to point out that the next 2 builds passed the setup phase (build 210 failed with spot termination, and build 211 finished with status pass)

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9b8be9ea-382b-4041-a11e-2962091b19fc`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9b8be9ea-382b-4041-a11e-2962091b19fc)
- Show all stored logs command: `$ hydra investigate show-logs 9b8be9ea-382b-4041-a11e-2962091b19fc`

## Logs:
- **db-cluster-9b8be9ea.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/db-cluster-9b8be9ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/db-cluster-9b8be9ea.tar.gz)
- **monitor-set-9b8be9ea.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/monitor-set-9b8be9ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/monitor-set-9b8be9ea.tar.gz)
- **loader-set-9b8be9ea.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/loader-set-9b8be9ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/loader-set-9b8be9ea.tar.gz)
- **sct-runner-9b8be9ea.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/sct-runner-9b8be9ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/sct-runner-9b8be9ea.tar.gz)
- **parallel-timelines-report-9b8be9ea.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/parallel-timelines-report-9b8be9ea.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9b8be9ea-382b-4041-a11e-2962091b19fc/20220712_061452/parallel-timelines-report-9b8be9ea.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/209/)

**Comment by fgelcer** [comment]
we should maybe add a retry, or even, as best effort, to continue even if the workaround didn't work, so it might fail later, or if the current version contains the fix (like master), it should not fail

**Comment by fruch** [comment]
sound like a networking issue, I wouldn't touch until it would happen more frequently...

**Comment by fgelcer** [comment]
yep, that's the reason i reported this issue, so if it starts to be too frequent, we will need to fix it, but soon we will remove it anyway, as the old Scylla versions were released, and they include the fix in Scylla itself...
we are waiting only for all OSS versions to be released as well (right now only enterprise ones were released) to remove this change completely

**Comment by fgelcer** [comment]
we started reverting this workaround, so i'm closing it, as most likely we won't see it again, and hopefully we will remove completely this workaround soon
