### ISSUE TITLE
show-monitor default time range

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5045]
when recovering monitoring with `hydra show-monitor`, grafana dashboard is set to recent 30 mins and obviously shows nothing for that range. It's cumbersome to set proper time range and to navigate with it.
There should be possibility to make default time range that fits test time range. First google search showed: https://community.grafana.com/t/default-time-range-for-dashboards/13937
There should be some setting that we can automatically set.

**Comment by fruch** [comment]
question is when to put those default into the configuration file of the dashboard ? when we collect the, or during the show-monitor command itself.

few more issues related:
* change default dashboard to the nemesis one (our own)
* change the default event filter, to show ERROR and CRITICAL, not WARNING and NORMAL

**Comment by soyacz** [comment]
> question is when to put those default into the configuration file of the dashboard ? when we collect the, or during the show-monitor command itself.
> 
> few more issues related:
> 
> * change default dashboard to the nemesis one (our own)
> * change the default event filter, to show ERROR and CRITICAL, not WARNING and NORMAL

I propose doing it in separate task.

**Comment by yaronkaikov** [comment]
@soyacz This is breaking docker artifact tests for `master`, `enterprise`, and `6.2` 
@lsfreitas @Annamikhlin FYI

**Comment by fruch** [comment]
@soyacz `update_default_time_range` should be noop, for cases we don't have monitor setup...

**Comment by soyacz** [comment]
> [@soyacz](https://github.com/soyacz) `update_default_time_range` should be noop, for cases we don't have monitor setup...

I tested it without monitor, but docker backend requires nodes to get monitor install path - I missed that case.
