### ISSUE TITLE
ClusterHealthValidation warnings on Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5046]
I spotted warnings in one of longevities:
`2022-07-04 07:26:21.670: (ClusterHealthValidatorEvent Severity.WARNING) period_type=one-time event_id=b66340c5-08cd-497d-b87f-3a00a63946a0: type=NodeStatus node=longevity-10gb-3h-master-db-node-e5137f6a-eastus-1 message=Unable to get nodetool status from `longevity-10gb-3h-master-db-node-e5137f6a-eastus-1': can only concatenate str (not "list") to str`

Need to investigate the root cause.
Test details:

## Installation details

Kernel Version: 5.13.0-1031-azure
Scylla version (or git commit hash): `5.1.dev-20220704.bfa3c0e73457` with build-id `25b0f62507683c39926c847acf5d757e1229ed41`
Cluster size: 6 nodes (Standard_L8s_v2)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-7 (104.45.148.110 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-6 (20.232.195.79 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-5 (20.124.243.108 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-4 (20.124.243.18 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-3 (52.149.214.139 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-2 (52.149.214.117 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-e5137f6a-eastus-1 (52.149.214.112 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/ScyllaDB-5.1.dev-0.20220704.bfa3c0e73457-1-build-183` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d1a4b561d1910705e88fe0c41d87e0dbfd0f84f4/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e)
- Show all stored logs command: `$ hydra investigate show-logs e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e`

## Logs:
- **db-cluster-e5137f6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/db-cluster-e5137f6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/db-cluster-e5137f6a.tar.gz)
- **monitor-set-e5137f6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/monitor-set-e5137f6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/monitor-set-e5137f6a.tar.gz)
- **loader-set-e5137f6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/loader-set-e5137f6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/loader-set-e5137f6a.tar.gz)
- **sct-runner-e5137f6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/sct-runner-e5137f6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/sct-runner-e5137f6a.tar.gz)
- **parallel-timelines-report-e5137f6a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/parallel-timelines-report-e5137f6a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e5137f6a-cdb2-4f7a-a58b-cfc4477b4b6e/20220704_104313/parallel-timelines-report-e5137f6a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/48/)

**Comment by fgelcer** [comment]
does it happen only on Azure?
@KnifeyMoloko , have you spotted such thing using the unified provisioning?

**Comment by soyacz** [comment]
> does it happen only on Azure? @KnifeyMoloko , have you spotted such thing using the unified provisioning?

I spotted it there, possibly it's showing in other places, but I doubt. When we know the root cause we'll see.
It's not in every run, just spotted it once so far.
