### ISSUE TITLE
Poor retry mechanism in node_setup

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#505]
try:
+            node.remoter.run('nodetool status', verbose=True)
+        except Exception as ex:
+            self.log.error('Failed running nodetool status, error: %s. Retrying...', ex)
+            time.sleep(5)
+            node.remoter.run('nodetool status', verbose=True)

This naive approach causes many tests to fail when "nodetool status" is issued while node isn't ready.

1. wait and try more than once.
2. handle exception and stop the test in case it failed after all retries.

**Comment by larisau** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/507
