### ISSUE TITLE
GCE sct-runner are not cleared by instance stopper script

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5051]
since we add the network tag `keep-alive`, and never remove it, the instance stopper script doesn't clear it up.

the SCT code count on cleanup being done on the next job that would run, for `sct-project-1` which we only run a few jobs, it can be days before instances would be cleaned out.

1) we need to remove that network tag at the end of the test
2) we should fix the cleanup script to align with how AWS works, using the GCE metadata for getting the `keep: 5` by hours

**Comment by fruch** [comment]
The cleanup process isn't using network tags anymore, right @soyacz ?

**Comment by soyacz** [comment]
> The cleanup process isn't using network tags anymore, right @soyacz ?

right, this one can be closed I suppose
