### ISSUE TITLE
Missing details when cloud-init --wait fails

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5058]
During provisioning, when `sudo cloud-init status --wait` fails, we can see message like this:
 `2022-07-26 03:59:20.771: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=df4992e2-0ef0-4b81-9b4f-b4f2e1a18fe0, source=LongevityTest.SetUp()
exception=Encountered a bad command exit code!
Command: 'sudo cloud-init status --wait'
Exit code: 1
Stdout:
status: error
Stderr:
`
So we don't know which node it happened.

Improve failure message with more details (e.g. vm name, error msg?)

**Comment by fruch** [comment]
maybe using --long ?
