### ISSUE TITLE
Epel gpg key sometimes fails to download (Centos7 mirrors on Azure are unreliable and failed with 503)

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5060]
Sometimes `epel` repository GPG key fails to download and cloud-init fails installation of syslog-ng:
```
Jul 26 03:49:49 longevity-10gb-3h-master-loader-node-eastus-1 cloud-init[1248]: Retrieving key from http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
Jul 26 03:49:50 longevity-10gb-3h-master-loader-node-eastus-1 cloud-init[1248]: GPG key retrieval failed: [Errno 14] HTTP Error 503 - Service Unavailable
Jul 26 03:49:50 longevity-10gb-3h-master-loader-node-eastus-1 cloud-init[1248]: 2022-07-26 03:49:50,057 - util.py[WARNING]: Failed to install packages: ['syslog-ng']
```

Investigate possible solution for this issue.

**Comment by soyacz** [comment]
One option would be placing this key on S3.
Another: upload this key to machine so it doesn't have to be downloaded (maybe it can be provided in epel configuration?)
And final (not recommended): disable gpgcheck when installing syslogng.

**Comment by fruch** [comment]
Seems like it's happening on the loader, can you supply more information? like which cloud it's happening, and what is the base image ? we probably need to switch to CentOS 8, or something newer.

**Comment by soyacz** [comment]
Azure, loader uses: 'OpenLogic:CentOS:7_9:latest'
Maybe switching to centos8 will help.
Anyway it happens only from time to time, but is very annoying.

**Comment by fruch** [comment]
Happened also on the monitor node, and keeps happening on azure:

```
Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: eventlog-0.2.13-4.el7.x86_64: [Errno 256] No more mirrors to try.
Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: 2022-08-22 05:03:40,406 - util.py[WARNING]: Failed to install packages: ['syslog-ng']
```

@soyacz let's switch the Azure loaders and monitors to ubuntu ?

**Comment by soyacz** [comment]
> Happened also on the monitor node, and keeps happening on azure:
> 
> ```
> Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: eventlog-0.2.13-4.el7.x86_64: [Errno 256] No more mirrors to try.
> Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: 2022-08-22 05:03:40,406 - util.py[WARNING]: Failed to install packages: ['syslog-ng']
> ```
> 
> @soyacz let's switch the Azure loaders and monitors to ubuntu ?

lets first try with gpgkey more reliable storage. I'll play with it today.

**Comment by fruch** [comment]
> > Happened also on the monitor node, and keeps happening on azure:
> > ```
> > Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: eventlog-0.2.13-4.el7.x86_64: [Errno 256] No more mirrors to try.
> > Aug 22 05:03:40 longevity-10gb-3h-master-monitor-node-eastus-1 cloud-init[1198]: 2022-08-22 05:03:40,406 - util.py[WARNING]: Failed to install packages: ['syslog-ng']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @soyacz let's switch the Azure loaders and monitors to ubuntu ?
> 
> lets first try with gpgkey more reliable storage. I'll play with it today.

it's not just the gpgkey, it's the mirrors are not available in all those cases, the key is on the mirror as well.
