### ISSUE TITLE
perf latency tests - need to add a delay after finishing grow_shrink nemsis 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-cluster-tests#5063]
The last part of the perf latency tests is adding 3 nodes and then decommissioning 3 nodes and then the test ends

At the end there is always a spike in latency and its not clear if this is because we are completing the test (and collecting data) or because there is a spike that needs investigation.

Please add 5 minutes delay (and if there is a delay make it longer by 5 minutes) so it will be easier to analyze if this is related to the last deomission or not

![Screenshot from 2022-07-26 21-07-41](https://user-images.githubusercontent.com/3465480/181079953-e0c6dea8-a9a3-4163-b2a8-5be862239fd2.png)

Its easy to see that there are no spikes in the 95% latency when nodes 6, 5 are decommissioned but when node4 is decommissioned there is a spike. 

It may be related to invalidation of the cache - but I expect that would also have some effect in node 6,5 decommission

**Comment by fgelcer** [comment]
AFAICT this is about `Test id: ec4f8157-79b4-4f57-a406-fa943680a2b0`

i don't see any effect of this spike in the latency collected for the decommission, but in the end, i will add a 5 min wait in the main nemesis, to be sure this spike is not related to the decommission, but most likely because we started stopping the stress and killing the nodes.

**Comment by fgelcer** [comment]
i have run a test with 10 min sleep after the `shrink_cluster` ended, and although there is some spike at the end of the nemesis (it is much smaller than the one reported in this issue originally), i don't think it is something we should care much.

the `test_id: 60407328-f42b-4ffc-9c62-7d3a3691c6fe` can be used to restore monitor for analysis, and i'm opening a PR to add it to the test, but i know @roydahan is against it:
#5095

@slivne FYI

**Comment by fgelcer** [comment]
here is screenshot (at the end of the load there is a peak, but because before that there were few much bigger peaks, it is not very clear from that POV):

![Screenshot from 2022-08-11 22-20-37](https://user-images.githubusercontent.com/32832995/184222201-566b7999-9190-4188-ae6b-846a1fe37615.png)

**Comment by roydahan** [comment]
This was done.
