### ISSUE TITLE
images rename `ScyllaVersion` tag to `scylla_version`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5068]
https://github.com/scylladb/scylla-machine-image/pull/383 is rename `ScyllaVersion` tag to `scylla_version`
we have one place using this tag, and we need to adapt the code

**Comment by fgelcer** [comment]
@soyacz , can you please address it?

**Comment by soyacz** [comment]
I'll adapt code in upcoming PR so it don't use it https://github.com/scylladb/scylla-cluster-tests/pull/5052  (will follow approach from AWS - it will take version from the name)

**Comment by soyacz** [comment]
Looks changes from https://github.com/scylladb/scylla-machine-image/pull/383 are not used by Azure. Issue:  https://github.com/scylladb/scylla-machine-image/issues/391
