### ISSUE TITLE
failed to download private repo by curl, err 301 Moved Permanently

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#508]
When trying to run longevity with official scylla 2.1 repo file:
http://repositories.scylladb.com/scylla/repo/6f6f3d487c18e09f0b42ed952b4a426f/centos/scylladb-2.1.repo

The following output of "sudo yum search scylla-enterprise" is returned.
(our code expect "no matches found" in case it's not scylla-enterprise)

``
if self.is_enterprise is None:
            result = self.remoter.run("sudo yum search scylla-enterprise", ignore_status=True)
            self.is_enterprise = True if ('scylla-enterprise.x86_64' in result.stdout or
                                          'No matches found' not in result.stdout) else False
``

Output:
```
22:01:13 Remote [scylla-test@10.142.0.21]: Running 'sudo yum search scylla-enterprise'
22:01:13 [10.142.0.21] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp5chmOC -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.21 "sudo yum search scylla-enterprise"'
22:01:13 [10.142.0.21] [stdout] Loaded plugins: fastestmirror
22:01:14 [10.142.0.21] [stdout] 
22:01:14 [10.142.0.21] [stdout] 
22:01:14 [10.142.0.21] [stdout] File contains no section headers.
22:01:14 [10.142.0.21] [stdout] file: file:///etc/yum.repos.d/scylla.repo, line: 1
22:01:14 [10.142.0.21] [stdout] '<html>\r\n'
22:01:14 [10.142.0.21] [stderr] Connection to 10.142.0.21 closed.
22:01:14 Remote [scylla-test@10.142.0.21]: Running 'sudo yum install -y scylla-enterprise'
22:01:14 [10.142.0.21] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp5chmOC -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.21 "sudo yum install -y scylla-enterprise"'
22:01:14 [10.142.0.21] [stdout] Loaded plugins: fastestmirror
22:01:14 [10.142.0.21] [stdout] 
22:01:14 [10.142.0.21] [stdout] 
22:01:14 [10.142.0.21] [stdout] File contains no section headers.
22:01:14 [10.142.0.21] [stdout] file: file:///etc/yum.repos.d/scylla.repo, line: 1
```

This is the output when using the repo file we get from rpm job in jenkins:
```
Warning: No matches found for: scylla-enterprise
22:44:24 [10.142.0.36] [stdout] No matches found
```

**Comment by amoskong** [comment]
The error `No matches found` returned from `yum search scylla-enterprise` is harmless.
When this error is returned, it will be treated as non enterprise (is_enterprise=False).

```
scylla-cluster-tests amoskong$ git grep 'yum search'
sdcm/cluster.py:            result = self.remoter.run("sudo yum search scylla-enterprise", ignore_status=True)
```

**Comment by amoskong** [comment]
Where do you run the job? can you provide the full SCT log or job link?

On Tue, Feb 27, 2018 at 6:53 AM, Roy Dahan <notifications@github.com> wrote:
....

> 22:01:13 Remote [scylla-test@10.142.0.21]: Running 'sudo yum search scylla-enterprise'
> 22:01:13 [10.142.0.21] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp5chmOC -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.21 "sudo yum search scylla-enterprise"'
> 22:01:13 [10.142.0.21] [stdout] Loaded plugins: fastestmirror
> 22:01:14 [10.142.0.21] [stdout]
> 22:01:14 [10.142.0.21] [stdout]
> 22:01:14 [10.142.0.21] [stdout] File contains no section headers.
> 22:01:14 [10.142.0.21] [stdout] file: file:///etc/yum.repos.d/scylla.repo, line: 1
> 22:01:14 [10.142.0.21] [stdout] '<html>\r\n'
>
>
It seems the content of scylla.repo has problem. curl might fail to
download the repo file.
But I can get right repo by the private link now.

I logged in the instance (10.142.0.21), it seems it's not same one as yours.

> 22:01:14 [10.142.0.21] [stderr] Connection to 10.142.0.21 closed.
> 22:01:14 Remote [scylla-test@10.142.0.21]: Running 'sudo yum install -y scylla-enterprise'
> 22:01:14 [10.142.0.21] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp5chmOC -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.21 "sudo yum install -y scylla-enterprise"'
> 22:01:14 [10.142.0.21] [stdout] Loaded plugins: fastestmirror
> 22:01:14 [10.142.0.21] [stdout]
> 22:01:14 [10.142.0.21] [stdout]
> 22:01:14 [10.142.0.21] [stdout] File contains no section headers.
> 22:01:14 [10.142.0.21] [stdout] file: file:///etc/yum.repos.d/scylla.repo, line: 1
>
> This is the output when using the repo file we get from rpm job in jenkins:
>
> Warning: No matches found for: scylla-enterprise
> 22:44:24 [10.142.0.36] [stdout] No matches found
>
>

**Comment by amoskong** [comment]
I remember we had a similar problem which was caused by wrong sed in jenkins shell (updating the repo url). Need to check if it's same problem.

**Comment by larisau** [comment]
When I tried to download the file using curl I got this:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
Therefore 'yum search' and 'yum install' are failing. 
But when I used wget command to download, it worked for me.
The problem with wget is that's not present on most of our builders and should be installed...

**Comment by amoskong** [comment]
A quick answer, the problem can be solved by adding '-L' option in curl
cmdline.
I had prepared a patch for sct:
https://gist.github.com/amoskong/e6b6f48cc7c2e31d9f55e570f5bde486

CC Amnon: is it caused by redirection in private repo backend? can we avoid
this problem?

On Tue, Feb 27, 2018 at 3:43 PM, Larisa Ustalov <notifications@github.com>
wrote:

> When I tried to download the file using curl I got this:
>
> <html>
> <head><title>301 Moved Permanently</title></head>
>
>
*301 MOVED PERMANENTLY*
*The target resource has been assigned a new permanent URI and any future
references to this resource ought to use one of the enclosed URIs.*


> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>CloudFront</center>
> </body>
> </html>
>
> Therefore 'yum search' and 'yum install' are failing.
> But when I used wget command to download, it worked for me.
> The problem with wget is that's not present on most of our builders and
> should be installed...
>

**Comment by amoskong** [comment]
After appended the -L option to curl, the private repo can be downloaded successfully.
`yum search scylla-enterprise` still returned 'No matches found', but error of repo content disappeared, and scylla was installed correctly.

```
09:13:17 [104.196.50.199] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVMfnka -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 104.196.50.199 "sudo curl http://repositories.scylladb.com/scylla/repo/6f6f3d487c18e09f0b42ed952b4a426f/centos/scylladb-2.1.repo -o /etc/yum.repos.d/scylla.repo -L"'
09:13:17 [104.196.50.199] [stdout]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
09:13:17 [104.196.50.199] [stdout]                                  Dload  Upload   Total   Spent    Left  Speed
09:13:17 [104.196.50.199] [stdout] 
09:13:17 [104.196.50.199] [stdout]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
09:13:17 [104.196.50.199] [stdout] 100   183  100   183    0     0   1766      0 --:--:-- --:--:-- --:--:--  1776
09:13:18 [104.196.50.199] [stdout] 
09:13:18 [104.196.50.199] [stdout]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
09:13:18 [104.196.50.199] [stdout] 100   807  100   807    0     0    854      0 --:--:-- --:--:-- --:--:--  1197
09:13:18 [104.196.50.199] [stderr] Connection to 104.196.50.199 closed.
09:13:18 Remote [scylla-test@104.196.50.199]: Running 'sudo yum search scylla-enterprise'
09:13:18 [104.196.50.199] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVMfnka -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 104.196.50.199 "sudo yum search scylla-enterprise"'
09:13:18 [104.196.50.199] [stdout] Loaded plugins: fastestmirror
09:13:19 [104.196.50.199] [stdout] scylla-2.1                                               | 3.3 kB     00:00     
09:13:20 [104.196.50.199] [stdout] scylla-generic-2.1                                       | 3.3 kB     00:00     
09:13:20 [104.196.50.199] [stdout] scylladb-scylla-3rdparty                                 | 3.0 kB     00:00     
....
09:13:24 [104.196.50.199] [stdout]  * base: mirror.wdc1.us.leaseweb.net
09:13:24 [104.196.50.199] [stdout]  * epel: reflector.westga.edu
09:13:24 [104.196.50.199] [stdout]  * extras: ftp.linux.ncsu.edu
09:13:24 [104.196.50.199] [stdout]  * updates: mirrors.greenmountainaccess.net
09:13:24 [104.196.50.199] [stdout] Warning: No matches found for: scylla-enterprise
09:13:24 [104.196.50.199] [stdout] No matches found
09:13:24 [104.196.50.199] [stderr] Connection to 104.196.50.199 closed.
09:13:24 Remote [scylla-test@104.196.50.199]: Running 'sudo yum install -y scylla'
```
