### ISSUE TITLE
Cannot see grafana board on restored monitor

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5109]
When restoring monitor using jenkins job we cannot get into the board due to blocked port 3000 in sct-2 vpc.

**Comment by soyacz** [comment]
As a workaround I added security group that opens port 3000 (inbound) in east-us-1

**Comment by fruch** [comment]
@soyacz as a permanent solution we should attach the test sg as in `attach_test_sg_cmd`

we shouldn't punch holes in our default SGs

**Comment by fruch** [comment]
> @soyacz as a permanent solution we should attach the test sg as in `attach_test_sg_cmd`
> 
> we shouldn't punch holes in our default SGs

since now for all tests in this region this port is open

**Comment by soyacz** [comment]
> > @soyacz as a permanent solution we should attach the test sg as in `attach_test_sg_cmd`
> > we shouldn't punch holes in our default SGs
> 
> since now for all tests in this region this port is open

I didn't modify default SG's - I created one and I attached it to instance.

**Comment by soyacz** [comment]
I think it is fixed already
