### ISSUE TITLE
disrupt_delete_by_rows_range fails with: IndexError: range object index out of range

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5145]
*Installation details*
Kernel version: `5.15.0-1015-aws`
Scylla version (or git commit hash): `5.0.1-0.20220719.b177dacd3 with build-id 217f31634f8c8722cadcfe57ade8da58af05d415`
Cluster size: 5 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-1 (16.170.172.71 | 10.0.0.113): 8 shards
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-3 (16.16.63.251 | 10.0.3.7): 8 shards
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-4 (13.53.214.233 | 10.0.0.115): 8 shards
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-5 (13.51.241.246 | 10.0.0.216): 8 shards
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-6 (16.170.143.15 | 10.0.2.99): 8 shards
Scylla running with shards number (terminated nodes):
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-2 (13.49.224.48 | 10.0.1.7): 8 shards
   longevity-large-partitions-8h-scyll-db-node-d12f5bb5-7 (13.49.78.162 | 10.0.0.68): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-092747fb03a354372` (aws: eu-north-1)

Test: `longevity-large-partition-8h-test-rq`
Test name: `longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity`
Test config file(s):
- [longevity-large-partition-8h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/cdc4af506acb6a8b8a6423ae2874f19db2280535/test-cases/longevity/longevity-large-partition-8h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/cdc4af506acb6a8b8a6423ae2874f19db2280535/test-cases/longevity/longevity-large-partition-8h.yaml&source=gmail-html&ust=1660835639641000&usg=AOvVaw2TO6PNLTCXv7S-sXFij7WP))

**Issue description**

====================================

This scenario passed ok in previous 5.0 runs.
The only difference is that reversed-queries were added to scylla-bench stress.
nemesis failure:
```
(DisruptionEvent Severity.ERROR) period_type=end event_id=ec76c13b-df6f-46be-a7e3-f21ff2f2568f duration=1m22s: nemesis_name=DeleteByRowsRange target_node=Node longevity-large-partitions-8h-scyll-db-node-d12f5bb5-5 [13.51.241.246 | 10.0.0.216] (seed: False) errors=range object index out of range
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3163, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1665, in disrupt_delete_by_rows_range
self.delete_range_in_few_partitions(ks_cf, partitions_for_exclude)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1630, in delete_range_in_few_partitions
queries.append(f"delete from {ks_cf} where pk = {pkey} and ck >= {clustering_keys[0]} "
IndexError: range object index out of range
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor d12f5bb5-73ca-41c5-82c7-7ef755960778`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d12f5bb5-73ca-41c5-82c7-7ef755960778](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id%3Dd12f5bb5-73ca-41c5-82c7-7ef755960778&source=gmail-html&ust=1660835639641000&usg=AOvVaw0LNgNsOFu3ofjHk5yQYYUA))
Show all stored logs command: `$ hydra investigate show-logs d12f5bb5-73ca-41c5-82c7-7ef755960778`

Test id: `d12f5bb5-73ca-41c5-82c7-7ef755960778`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234136/grafana-screenshot-overview-20220815_234136-longevity-large-partitions-8h-scyll-monitor-node-d12f5bb5-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234136/grafana-screenshot-overview-20220815_234136-longevity-large-partitions-8h-scyll-monitor-node-d12f5bb5-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234136/grafana-screenshot-overview-20220815_234136-longevity-large-partitions-8h-scyll-monitor-node-d12f5bb5-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234136/grafana-screenshot-overview-20220815_234136-longevity-large-partitions-8h-scyll-monitor-node-d12f5bb5-1.png)&source=gmail-html&ust=1660835639641000&usg=AOvVaw0W8vOyaeeTuoc6MnBUttUh)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/db-cluster-d12f5bb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/db-cluster-d12f5bb5.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/db-cluster-d12f5bb5.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/db-cluster-d12f5bb5.tar.gz)&source=gmail-html&ust=1660835639641000&usg=AOvVaw2a5ZXcYLhhklqUM6qhauzo)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/loader-set-d12f5bb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/loader-set-d12f5bb5.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/loader-set-d12f5bb5.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/loader-set-d12f5bb5.tar.gz)&source=gmail-html&ust=1660835639641000&usg=AOvVaw0D3U-LNAPY4u94jpbcUptw)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/monitor-set-d12f5bb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/monitor-set-d12f5bb5.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/monitor-set-d12f5bb5.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/monitor-set-d12f5bb5.tar.gz)&source=gmail-html&ust=1660835639641000&usg=AOvVaw3GqatHYYaaQ96TzL3bWr8M)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/sct-runner-d12f5bb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/sct-runner-d12f5bb5.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/sct-runner-d12f5bb5.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d12f5bb5-73ca-41c5-82c7-7ef755960778/20220815_234906/sct-runner-d12f5bb5.tar.gz)&source=gmail-html&ust=1660835639641000&usg=AOvVaw2d-MbRHXpFVfrGS3VplMoz)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-8h-test-rq/2/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-8h-test-rq/2/&source=gmail-html&ust=1660835639641000&usg=AOvVaw26dsKhgXyevnoLuWKbAjfi))

**Comment by fruch** [comment]
@yarongilor I don't understand this run is from a code merged into SCT ? or from a branch of an ongoing PR ? why opening this as a bug and no handling it as part of the PR ?

**Comment by yarongilor** [comment]
@fruch it's from a PR but apparently not related to PR because it only changed a stress parameter.

**Comment by fruch** [comment]
> @fruch it's from a PR but apparently not related to PR because it only changed a stress parameter.

that's sound related to the PR, at least to me, 
i.e. you are introducing something new to SCT and it doesn't work. (so until solved you can't merged)

**Comment by roydahan** [comment]
@yarongilor IIRC this nemesis select X keys from the table in a reverse order to pick the partitions to be deleted.
Maybe something with your change broke it.

**Comment by yarongilor** [comment]
The only thing changed is adding the `select-order-by` parameter in the last read-stress. It runs after the `prepare` finished. If it is related then it could be an s-b issue.

**Comment by fgelcer** [comment]
@yarongilor , is this issue being reproduced in later runs?
