### ISSUE TITLE
stop SSH connection storm

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#5147]
seen in some performance job, we are having kind of a storm of SSH connections, and it is being suspected of affecting the cluster causing multiple `Reactor Stalls`.

here the comment about it in the issue, for reference:
https://github.com/scylladb/scylladb/issues/11038#issuecomment-1217762278

it could be that in newer branches we don't have it, but my suspicious is that the coredump checks are connecting (along with other "verifications") every few seconds to each one of the nodes, and it is apparently impacting these tests

now sure 100% this is the case, and not 100% how to fix it, but if we keep an open socket with that node, we could use it to run commands, rather than opening a new connection every time we want to run a command...

**Comment by fgelcer** [comment]
@fruch @enaydanov @soyacz @vponomaryov @roydahan , suggestions?

**Comment by fruch** [comment]
> @fruch @enaydanov @soyacz @vponomaryov @roydahan , suggestions?

We will need more information and details about those "storms" beside what Avi was saying, we are checking for coredump once in 30sec or once in a minute.

We are using the same connection, and forking the command we execute each time.

We can't stop doing that, maybe just configure the interval for different jobs.

And someone would need to take a closer look, if the coredump check is the only issue here.

**Comment by fgelcer** [comment]
yes, that is mainly the reason to having this issue, as i'm not sure where the problem is, if at all, and how could we mitigate it, or reduce its impact in the test (like you said, increasing the coredump check interval)

**Comment by soyacz** [comment]
I examined 'check_spot_termination` and it is doing ssh connection every 5 secs to each spot node.

**Comment by soyacz** [comment]
my proposal would be to enhance `node_exporter` to show metric regarding spot termination - like I proposed for coredump - and instead doing ssh connection, just send http get request and verify this metric.

**Comment by fruch** [comment]
> I examined 'check_spot_termination` and it is doing ssh connection every 5 secs to each spot node.

Perf tests are not running with spot, as far as I know.

**Comment by fruch** [comment]
> my proposal would be to enhance `node_exporter` to show metric regarding spot termination - like I proposed for coredump - and instead doing ssh connection, just send http get request and verify this metric.

Sounds like quite a big refactoring, which we probably won't backport into old perf branches.

We could experiment with the idea regardless.

But someone need to dig in that old branch and provided logs to understand if what Avi climbing is true and how we can mitigate it

**Comment by roydahan** [comment]
I would start with changing the "check_spot_termination" to every 45s.
The notification from AWS is 2 minutes ahead so we should be able to catch it by then.
