### ISSUE TITLE
scylla-bench fail to create table on auzre short longevity 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5168]
## Installation details

Kernel Version: 5.15.0-1017-azure
Scylla version (or git commit hash): `5.2.0~dev-20220824.6ce5e9079c1e` with build-id `d7559bfdcb8ca68f5a8b7568ee81e1cc505e8498`
Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-7 (52.224.104.205 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-6 (20.232.138.213 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-5 (20.232.138.190 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-4 (20.232.138.82 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-3 (20.232.137.237 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-2 (20.232.137.199 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-e9ffde0d-eastus-1 (20.232.137.125 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-08-24T09-18-32Z` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `e9ffde0d-6f24-481b-9e5c-b6996c4afcf8`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c84a4dcc7b10f9d9c9d386971cec5a7fe7fbe32f/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

The error event looks like this:
```
2022-08-24 13:28:35.465: (ScyllaBenchEvent Severity.ERROR) period_type=end event_id=768b9ee6-d223-45b0-a56d-2cc5a74d2a5f duration=6s: node=Node longevity-10gb-3h-master-loader-node-e9ffde0d-eastus-1 [20.231.195.225 | 10.0.0.11] (seed: False)
stress_cmd=scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=10 -clustering-row-count=5555 -clustering-row-size=uniform:10..20 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=60s -keyspace ks_truncate_large_partition -table test_table -error-at-row-limit 1000
errors:
Stress command completed with bad status 1: 2022/08/24 13:28:30 Found invalid peer '[HostInfo hostname="" connectAddress="10.0.0.5" peer="10.0.0
```

the acutal fail from log look like:
`2022/08/24 13:28:30 Cannot add table 'test_table' to non existing keyspace 'ks_truncate_large_partition'.`

looking on passing runs, this also fail like but the 2nd thread is failing. which raises a question why the orders metters here.
code is using `stop_test_on_failure` so both the failure isn't critical
```
        bench_thread = self.tester.run_stress_thread(
            stress_cmd=stress_cmd, stop_test_on_failure=False)
```

but in general looks like a race condition with creating the table/ks, and we should wait 30sec (after 1st thread start) like in the regular c-s thread, to let it create the keyspace and table 

- Restore Monitor Stack command: `$ hydra investigate show-monitor e9ffde0d-6f24-481b-9e5c-b6996c4afcf8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e9ffde0d-6f24-481b-9e5c-b6996c4afcf8)
- Show all stored logs command: `$ hydra investigate show-logs e9ffde0d-6f24-481b-9e5c-b6996c4afcf8`

## Logs:
- **db-cluster-e9ffde0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/db-cluster-e9ffde0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/db-cluster-e9ffde0d.tar.gz)
- **monitor-set-e9ffde0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/monitor-set-e9ffde0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/monitor-set-e9ffde0d.tar.gz)
- **loader-set-e9ffde0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/loader-set-e9ffde0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/loader-set-e9ffde0d.tar.gz)
- **sct-runner-e9ffde0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/sct-runner-e9ffde0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/sct-runner-e9ffde0d.tar.gz)
- **parallel-timelines-report-e9ffde0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/parallel-timelines-report-e9ffde0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9ffde0d-6f24-481b-9e5c-b6996c4afcf8/20220824_143016/parallel-timelines-report-e9ffde0d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/69/)

**Comment by fruch** [comment]
@soyacz any thought on what's different on azure, that it failed like that ? (it's not failing on AWS, not that I remember even seen it like that)

also we have those print in the scylla-bench logs:
```
2022/08/24 13:28:30 Found invalid peer '[HostInfo hostname="" connectAddress="10.0.0.5" peer="10.0.0.5" rpc_address="10.0.0.5" broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="10.0.0.5" connect_addr_source="connect_address" port=9042 data_centre="eastus" rack="" host_id="9f6c2ca0-8dd9-486f-b17b-bc938623161a" version="v3.0.8" state=UP num_tokens=256]' Likely due to a gossip or snitch issue, this host will be ignored
```

it's quite weird we don't have `broadcast_address`, and the at `rack` is empty, which snitch are using ? Azure specific (if we have one) ?

**Comment by soyacz** [comment]
we use AzureSnitch, but rack might be empty due not setting availability zone during provision. I'm just adding feature for handling availability zones for Azure, so I can test if it works when we specify it.

**Comment by soyacz** [comment]
I tested it with avaiability zone set and seems to work.
See that AzureSnitch has some problem as described in: https://github.com/scylladb/scylladb/issues/11386 so, sometimes it may not work.
