### ISSUE TITLE
Detect duplicated keys in configuration files

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5169]
@vponomaryov  suggestion that we should test for those kind of the cases.
problem is that the default behavier of pyyaml, is last one wins

if we want this kind of protection we can switch to using `ruamel.yaml` together with multiple calls to `anyconfig.merge` instead of `anyconfig.load` we are using so far

downside of it we couldn't support using json/ini or what ever anyconfig supports, but we don't anyhow. (it was questionalble at the beginning when yaml was picked, and anyconfig left us with the option to switch around, we never did)

the nice thing left for us with `anyconfig`, is the merging logic we can use. (or it can be thrown away)

```
>>> anyconfig.merge(a, ruamel.yaml.safe_load('abc: a\nabc: d'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1118, in safe_load
    return load(stream, SafeLoader, version)
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1071, in load
    return loader._constructor.get_single_data()
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 131, in construct_document
    for _dummy in generator:
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 674, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 263, in construct_mapping
    if self.check_mapping_key(node, key_node, mapping, key, value):
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 294, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<unicode string>", line 1, column 1:
    abc: a
    ^ (line: 1)
found duplicate key "abc" with value "d" (original value: "a")
  in "<unicode string>", line 2, column 1:
    abc: d
    ^ (line: 2)

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

**Comment by fruch** [comment]
@scylladb/qa-maintainers 

What do you think, still worth investing in this one ?

**Comment by soyacz** [comment]
So the main problem is duplicate entries in the same yaml file?

I wonder how often this behavior is causing problems - for me I don't recall many situations if any...

**Comment by vponomaryov** [comment]
We can close this as `resolved`:

```
$ git diff
diff --git a/test-cases/longevity/longevity-10gb-3h.yaml b/test-cases/longevity/longevity-10gb-3h.yaml
index c55793a70..404b4b4b1 100644
--- a/test-cases/longevity/longevity-10gb-3h.yaml
+++ b/test-cases/longevity/longevity-10gb-3h.yaml
@@ -5,6 +5,7 @@ stress_cmd: ["cassandra-stress write cl=QUORUM duration=180m -schema 'replicatio
 n_db_nodes: 6
 n_loaders: 2
 n_monitor_nodes: 1
+n_db_nodes: 8
 
 instance_type_db: 'i4i.2xlarge'
 gce_instance_type_db: 'n2-highmem-16'

$ git add test-cases/longevity/longevity-10gb-3h.yaml

$ git commit
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while constructing a mapping
  in "test-cases/longevity/longevity-10gb-3h.yaml", line 1, column 1
found duplicate key "n_db_nodes" with value "8" (original value: "6")
  in "test-cases/longevity/longevity-10gb-3h.yaml", line 8, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Check for added large files..............................................Passed
Check JSON...........................................(no files to check)Skipped
Detect AWS Credentials...................................................Passed
Detect Private Key.......................................................Passed
autopep8.............................................(no files to check)Skipped
ruff.................................................(no files to check)Skipped
```

**Comment by fruch** [comment]
> We can close this as `resolved`:
> 
> ```
> $ git diff
> diff --git a/test-cases/longevity/longevity-10gb-3h.yaml b/test-cases/longevity/longevity-10gb-3h.yaml
> index c55793a70..404b4b4b1 100644
> --- a/test-cases/longevity/longevity-10gb-3h.yaml
> +++ b/test-cases/longevity/longevity-10gb-3h.yaml
> @@ -5,6 +5,7 @@ stress_cmd: ["cassandra-stress write cl=QUORUM duration=180m -schema 'replicatio
>  n_db_nodes: 6
>  n_loaders: 2
>  n_monitor_nodes: 1
> +n_db_nodes: 8
>  
>  instance_type_db: 'i4i.2xlarge'
>  gce_instance_type_db: 'n2-highmem-16'
> 
> $ git add test-cases/longevity/longevity-10gb-3h.yaml
> 
> $ git commit
> Trim Trailing Whitespace.................................................Passed
> Fix End of Files.........................................................Passed
> Check Yaml...............................................................Failed
> - hook id: check-yaml
> - exit code: 1
> 
> while constructing a mapping
>   in "test-cases/longevity/longevity-10gb-3h.yaml", line 1, column 1
> found duplicate key "n_db_nodes" with value "8" (original value: "6")
>   in "test-cases/longevity/longevity-10gb-3h.yaml", line 8, column 1
> 
> To suppress this check see:
>     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
> 
> Check for added large files..............................................Passed
> Check JSON...........................................(no files to check)Skipped
> Detect AWS Credentials...................................................Passed
> Detect Private Key.......................................................Passed
> autopep8.............................................(no files to check)Skipped
> ruff.................................................(no files to check)Skipped
> ```

that's even better :)
