### ISSUE TITLE
Loader setup fails on ubuntu 22.04 due missing collectd package

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5174]
I was trying to use ubuntu 22.04 for loaders on Azure, but it was not getting configured properly due missing `collectd` package.
According to https://packages.ubuntu.com/search?keywords=collectd `collectd` is not found for 22.04.
```
2022-08-23 14:57:00.085: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=d7ae1555-5567-483a-b1d4-c68e4a1d7154, source=LongevityTest.SetUp()
exception=[Node longevity-mini-test-azure-fi-loader-node-653cab8c-eastus-1 [20.232.188.246 | 10.0.0.9] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo apt-get install -y collectd'
Exit code: 100
Stdout:
Reading package lists...
Building dependency tree...
Reading state information...
Package collectd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
Stderr:
E: Package 'collectd' has no installation candidate
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3484, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4529, in node_setup
collectd_setup.install(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/collectd.py", line 476, in install
self.node.remoter.run('sudo apt-get install -y collectd')
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo apt-get install -y collectd'
Exit code: 100
Stdout:
Reading package lists...
Building dependency tree...
Reading state information...
Package collectd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
Stderr:
E: Package 'collectd' has no installation candidate

```

Test id: `653cab8c-4798-4681-aa8e-7e31d634f857`

Logs:
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/db-cluster-653cab8c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/db-cluster-653cab8c.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/db-cluster-653cab8c.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/db-cluster-653cab8c.tar.gz)&source=gmail-html&ust=1661506455922000&usg=AOvVaw0zkG2X17ARbOUAt1t04msZ)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/loader-set-653cab8c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/loader-set-653cab8c.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/loader-set-653cab8c.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/loader-set-653cab8c.tar.gz)&source=gmail-html&ust=1661506455922000&usg=AOvVaw2Z-CNMbRU4lih7tx5vYheY)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/monitor-set-653cab8c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/monitor-set-653cab8c.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/monitor-set-653cab8c.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/monitor-set-653cab8c.tar.gz)&source=gmail-html&ust=1661506455922000&usg=AOvVaw092QJdFwvWyqpGNCbJxI9F)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/sct-runner-653cab8c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/sct-runner-653cab8c.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/sct-runner-653cab8c.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/653cab8c-4798-4681-aa8e-7e31d634f857/20220823_151414/sct-runner-653cab8c.tar.gz)&source=gmail-html&ust=1661506455922000&usg=AOvVaw1VsHescThLFicYuFQTW_n1)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/mini-longevity/36/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/mini-longevity/36/&source=gmail-html&ust=1661506455923000&usg=AOvVaw3cTh-MVR4ZUY2MeYGn5k3U))

**Comment by fruch** [comment]
here's the upstream bug for it, so we can track it:
https://bugs.launchpad.net/ubuntu/+source/collectd/+bug/1971093

weird it didn't yet affected our artifacts and rolling upgrade tests, or manager tests that @ShlomiBalalis recently introduced.

**Comment by soyacz** [comment]
maybe the case is only for Azure using official Canonical ubuntu server images?

**Comment by fruch** [comment]
> maybe the case is only for Azure using official Canonical ubuntu server images?

I don't think so, we might run into this on GCE/AWS as well at some point. but for scylla we don't install collectd, and we used new ubuntu only for scylla, not for loaders.

**Comment by fruch** [comment]
We should try replace collectd with node-exporter (similar to what we are using for scylla nowdays):
https://packages.ubuntu.com/focal/net/prometheus-node-exporter

the collectd is old relic from day we were reporting metrics of the stress command from the loader machine, we are not doing that anymore.

**Comment by soyacz** [comment]
do we bump ubuntu version for loaders?

**Comment by fruch** [comment]
> do we bump ubuntu version for loaders?

we could, but's nor urgent nor critical.

the more severe issue from my POV was that we didn't had dashboard to the collectd metrics, and people didn't know where to look for loader stats.
