### ISSUE TITLE
c-s load was started exactly in the time when one of the nodes from "-node" list was restarted and caused to test failure

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5180]
*Installation details*
Kernel version: `5.15.0-1017-aws`
Scylla version (or git commit hash): `2022.2.0~rc0-0.20220814.eb67e6127d6b with build-id 5fc03e7326d7fd7e3eb1228a48382a35fcd8c08f`
Cluster size: 5 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-1 (13.51.47.130 | 10.0.2.26): 7 shards
   longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-2 (13.48.29.183 | 10.0.3.6): 7 shards
   longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-3 (16.16.26.241 | 10.0.1.134): 7 shards
   longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-4 (13.49.72.72 | 10.0.0.34): 7 shards
   longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 (13.49.70.22 | 10.0.3.59): 7 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-06d6dae74850fc3e0` (aws: eu-north-1)

Test: `longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/8bda78ecfc6d1492ab38abcdcafae2f2a73499f4/test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/8bda78ecfc6d1492ab38abcdcafae2f2a73499f4/test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml&source=gmail-html&ust=1661839909039000&usg=AOvVaw03zH_xM_hR6uhfTjmTEJjb))

**Issue description**

Change that represented in https://github.com/scylladb/scylla-cluster-tests/pull/5042 may cause to the test failure because of c-s load was started exactly in the time when one of the nodes from "-node" list was restarted (under nemesis). 

Node reboot:
```
Aug 28 15:14:43 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 scylla[8522]:  [shard 0] init - Shutting down sighup was successful
Aug 28 15:14:43 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 scylla[8522]:  [shard 0] init - Scylla version 2022.2.0~rc0-0.20220814.eb67e6127d6b shutdown complete.
Aug 28 15:15:49 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 systemd[1]: scylla-server.service: Succeeded.
Aug 28 15:15:49 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 systemd[1]: Stopped Scylla Server.
Aug 28 15:15:49 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 systemd[1]: scylla-image-setup.service: Succeeded.
Aug 28 15:15:49 longevity-tls-2tb-48h-1dis-2nondis--db-node-33d5eb60-5 systemd[1]: Stopped Scylla Cloud Image Setup service.
-- Reboot --
```

C-s failure:
```
< t:2022-08-28 15:14:57,480 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-28 15:14:57.478: (CassandraStressEvent Severity.NORMAL) period_type=begin event_id=a5c3f6e7-6275-4543-bbda-3a3
2e628aa4f: node=Node longevity-tls-2tb-48h-1dis-2nondis--loader-node-33d5eb60-2 [13.53.33.194 | 10.0.0.235] (seed: False)


< t:2022-08-28 15:16:02,961 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-08-28 15:16:02.956: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=a5c3f6e7-6275-4543-bbda-3a32e628aa4f: type=IOException regex=java\.io\.IOException line_number=271 node=Node longevity-tls-2tb-48h-1dis-2nondis--loader-node-33d5eb60-2 [13.53.33.194 | 10.0.0.235] (seed: False)
< t:2022-08-28 15:16:02,961 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > java.io.IOException: Operation x0 on key(s) [394f504b4e3236343231]: Data returned was not validated

< t:2022-08-28 15:16:11,908 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  15:16:11,506 Error creating netty channel to ip-10-0-3-59.eu-north-1.compute.internal/10.0.3.59:9042


< t:2022-08-28 15:55:17,044 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=CC0YQNDUMCRM686BKA4T; cassandra-stress mixed cl=QUORUM duration=40m -schema keyspace=keyspace1 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -mode cql3 native  user=cassandra password=cassandra -rate threads=20 -pop seq=1..2147483  -log interval=5 -col 'size=FIXED(64) n=FIXED(16)'  -transport "truststore=/etc/scylla/ssl_conf/client/cacerts.jks truststore-password=cassandra" -node 10.0.2.26,10.0.3.6,10.0.1.134,10.0.0.34,10.0.3.59 -errors skip-unsupported-columns"; Exit status: 1

< t:2022-08-28 15:55:17,044 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > FAILURE
< t:2022-08-28 15:55:17,044 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: WARN  15:15:02,146 Error creating netty channel to /10.0.3.59:9042

< t:2022-08-28 15:55:17,044 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > java.lang.RuntimeException: Failed to execute stress action
< t:2022-08-28 15:55:17,044 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
< t:2022-08-28 15:55:17,044 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at org.apache.cassandra.stress.Stress.run(Stress.java:143)
< t:2022-08-28 15:55:17,044 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >         at org.apache.cassandra.stress.Stress.main(Stress.java:62)
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-28 15:55:17.046: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=a5c3f6e7-6275-4543-bbda-3a32e628aa4f duration=40m19s: node=Node longevity-tls-2tb-48h-1dis-2nondis--loader-node-33d5eb60-2 [13.53.33.194 | 10.0.0.235] (seed: False)
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress mixed cl=QUORUM duration=40m -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -mode cql3 native -rate threads=20 -pop seq=1..2147483  -log interval=5 -col 'size=FIXED(64) n=FIXED(16)' 
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > errors:
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: WARN  15:15:02,146 Error creating netty channel to /10.0.3.59:9042
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > com.datastax.shaded.netty.channel

```

Restore Monitor Stack command: `$ hydra investigate show-monitor 33d5eb60-b5ca-4c2f-b88d-e574f858a38a`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=move_disrupt_method_wrapper&test_id=33d5eb60-b5ca-4c2f-b88d-e574f858a38a](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmove_disrupt_method_wrapper%26test_id%3D33d5eb60-b5ca-4c2f-b88d-e574f858a38a&source=gmail-html&ust=1661839909039000&usg=AOvVaw0zFi730I0yYRJWO6V8LikE))
Show all stored logs command: `$ hydra investigate show-logs 33d5eb60-b5ca-4c2f-b88d-e574f858a38a`

Test id: `33d5eb60-b5ca-4c2f-b88d-e574f858a38a`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/33d5eb60-b5ca-4c2f-b88d-e574f858a38a/20220828_160619/db-cluster-33d5eb60.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33d5eb60-b5ca-4c2f-b88d-e574f858a38a/20220828_160619/db-cluster-33d5eb60.tar.gz)

loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/33d5eb60-b5ca-4c2f-b88d-e574f858a38a/20220828_160619/loader-set-33d5eb60.tar.gz

sct - [https://cloudius-jenkins-test.s3.amazonaws.com/33d5eb60-b5ca-4c2f-b88d-e574f858a38a/20220828_160619/sct-runner-33d5eb60.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33d5eb60-b5ca-4c2f-b88d-e574f858a38a/20220828_160619/sct-runner-33d5eb60.tar.gz)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/6/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/6/&source=gmail-html&ust=1661839909039000&usg=AOvVaw0Dhkc3Y41KRQtT7Y6Nt9ix))

**Comment by fruch** [comment]
@juliayakovlev I think the failure in the stress:
```
java.io.IOException: Operation x0 on key(s) [33353133374e324f3230]: Data returned was not validated
```

is cause of you shortening the prepare stage, i.e. the stress failing on data validation and not on host not available.

**Comment by juliayakovlev** [comment]
@fruch 
Looks like this is the failre reason:
```
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-28 15:55:17.046: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=a5c3f6e7-6275-4543-bbda-3a32e628aa4f duration=40m19s: node=Node longevity-tls-2tb-48h-1dis-2nondis--loader-node-33d5eb60-2 [13.53.33.194 | 10.0.0.235] (seed: False)
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress mixed cl=QUORUM duration=40m -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -mode cql3 native -rate threads=20 -pop seq=1..2147483  -log interval=5 -col 'size=FIXED(64) n=FIXED(16)' 
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > errors:
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: WARN  15:15:02,146 Error creating netty channel to /10.0.3.59:9042
< t:2022-08-28 15:55:17,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > com.datastax.shaded.netty.channel
```

**Comment by fruch** [comment]
It's just printing the last error line it found, it doesn't mean it's the actual reason.

**Comment by fruch** [comment]
This was fixed in c-s long ago
