### ISSUE TITLE
"got exception while processing a message: std::logic_error (rpc stream id 1 not found)" on reboot during RepairStreamingErr 

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5187]
*Installation details*
Kernel version: `5.15.0-1017-aws`
Scylla version (or git commit hash): `2021.1.14-0.20220824.814b676a5`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-1 (44.201.54.44 | 10.0.0.140): 14 shards
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-2 (3.93.39.9 | 10.0.1.92): 14 shards
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-4 (18.215.62.49 | 10.0.1.200): 14 shards
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-5 (3.239.248.164 | 10.0.0.84): 14 shards
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-6 (3.234.139.19 | 10.0.1.78): 14 shards
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-7 (3.230.170.80 | 10.0.0.146): 14 shards
Scylla running with shards number (terminated nodes):
  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-3 (44.204.170.37 | 10.0.2.185): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0cd81b8737ed4eeff` (aws: us-east-1)

Test: `longevity-cdc-4h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-cdc-100gb-4h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/ca8a02961c8a045df4e2ea49d1cc2fde06d11620/test-cases/longevity/longevity-cdc-100gb-4h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/ca8a02961c8a045df4e2ea49d1cc2fde06d11620/test-cases/longevity/longevity-cdc-100gb-4h.yaml&source=gmail-html&ust=1661857469370000&usg=AOvVaw2qBkjk7qdRBQjPIuRLIL7W))

**Issue description**

====================================
error:
```
2022-08-25 22:27:57.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=47796 node=Node longevity-cdc-100gb-4h-2021-1-db-node-f9660539-2 [3.93.39.9 | 10.0.1.92] (seed: False)
2022-08-25T22:27:57+00:00  longevity-cdc-100gb-4h-2021-1-db-node-f9660539-2 !INFO    | scylla:  [shard 10] rpc - client [10.0.1.200:62954](http://10.0.1.200:62954/) msg_id 28363:  got exception while processing a message: std::logic_error (rpc stream id 1 not found)
```

It happened during reboot node4 when node2 try connecting it:
```
< t:2022-08-25 22:27:54,094 f:cluster.py l:1098 c:sdcm.cluster_aws p:DEBUG > Node longevity-cdc-100gb-4h-2021-1-db-node-f9660539-4 [18.215.62.49 | 10.0.1.200] (seed: False): Hardly rebooting node
< t:2022-08-25 22:29:04,517 f:cluster.py l:1094 c:sdcm.cluster_aws p:DEBUG > Node longevity-cdc-100gb-4h-2021-1-db-node-f9660539-4 [18.215.62.49 | 10.0.1.200] (seed: False): Failed to get uptime during reboot, Unable to run "uptime -s": failed connecting to "10.0.1.200" during 60s
< t:2022-08-25 22:29:52,293 f:cluster.py l:1505 c:sdcm.cluster p:DEBUG > 2022-08-25T22:27:57+00:00 longevity-cdc-100gb-4h-2021-1-db-node-f9660539-2 !INFO | scylla: [shard 10] rpc - client [10.0.1.200:62954](https://www.google.com/url?q=http://10.0.1.200:62954&sa=D&source=docs&ust=1661774332219469&usg=AOvVaw1DFAcPaotyTwpSg262UBly) msg_id 28363: got exception while processing a message: std::logic_error (rpc stream id 1 not found)
```
This error is expected due to node reboot after a repair started, during RepairStreamingErr nemesis.
It should be filtered out

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor f9660539-b80c-48b8-b83b-ad385952d1ff`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=f9660539-b80c-48b8-b83b-ad385952d1ff](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3Df9660539-b80c-48b8-b83b-ad385952d1ff&source=gmail-html&ust=1661857469370000&usg=AOvVaw0pYIdshYxGFFb4W5ooGk0u))
Show all stored logs command: `$ hydra investigate show-logs f9660539-b80c-48b8-b83b-ad385952d1ff`

Test id: `f9660539-b80c-48b8-b83b-ad385952d1ff`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-longevity-cdc-4h-test-scylla-per-server-metrics-nemesis-20220826_001040-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-longevity-cdc-4h-test-scylla-per-server-metrics-nemesis-20220826_001040-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-longevity-cdc-4h-test-scylla-per-server-metrics-nemesis-20220826_001040-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-longevity-cdc-4h-test-scylla-per-server-metrics-nemesis-20220826_001040-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png)&source=gmail-html&ust=1661857469370000&usg=AOvVaw1bXUcoKkN1zBBsfGsxpsOi)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-overview-20220826_000705-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-overview-20220826_000705-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-overview-20220826_000705-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_000705/grafana-screenshot-overview-20220826_000705-longevity-cdc-100gb-4h-2021-1-monitor-node-f9660539-1.png)&source=gmail-html&ust=1661857469370000&usg=AOvVaw2uk4lByc6b62nX94UOfOcp)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/db-cluster-f9660539.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/db-cluster-f9660539.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/db-cluster-f9660539.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/db-cluster-f9660539.tar.gz)&source=gmail-html&ust=1661857469370000&usg=AOvVaw3-smCHEaxr9Gi1bYiUZtF1)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/loader-set-f9660539.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/loader-set-f9660539.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/loader-set-f9660539.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/loader-set-f9660539.tar.gz)&source=gmail-html&ust=1661857469370000&usg=AOvVaw1JXrCKvMWYpx_t8_x7u6u3)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/monitor-set-f9660539.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/monitor-set-f9660539.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/monitor-set-f9660539.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/monitor-set-f9660539.tar.gz)&source=gmail-html&ust=1661857469370000&usg=AOvVaw2Pb7VwBtXJvojP8_dc_MNL)
sct-runner - [[https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/sct-runner-f9660539.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/sct-runner-f9660539.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/sct-runner-f9660539.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/f9660539-b80c-48b8-b83b-ad385952d1ff/20220826_001511/sct-runner-f9660539.tar.gz)&source=gmail-html&ust=1661857469370000&usg=AOvVaw2rMqZ8JrVrsiRdTucZjdVv)

[Jenkins job URL]([https://jenkins.scylladb.com/job/enterprise-2021.1/job/longevity/job/longevity-cdc-4h-test/91/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/enterprise-2021.1/job/longevity/job/longevity-cdc-4h-test/91/&source=gmail-html&ust=1661857469370000&usg=AOvVaw3eGf8fUs57r0GynXC3Vr5O))

**Comment by yarongilor** [comment]
![Screenshot from 2022-08-29 14-03-03](https://user-images.githubusercontent.com/9427929/187188420-125516ea-9034-447c-be58-7ed0983d956d.png)

**Comment by roydahan** [comment]
@yarongilor Send PR to filter it in 2021.1
