### ISSUE TITLE
Azure: failure cause of spot termination fails to create email_results.json

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5211]
## Installation details

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-6 (20.83.148.174 | 10.0.0.10) (shards: -1)
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-5 (20.83.148.172 | 10.0.0.9) (shards: -1)
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-4 (20.83.148.170 | 10.0.0.8) (shards: -1)
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-3 (20.83.148.157 | 10.0.0.7) (shards: -1)
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-2 (20.83.148.151 | 10.0.0.6) (shards: -1)
- longevity-10gb-3h-master-db-node-4d7864c4-eastus-1 (20.83.148.146 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-08-31T12-46-19Z` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `4d7864c4-e593-4102-95fa-72c781bfe4cd`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d8115dd93844797e824dddf12683a15097b89d3c/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

Test get failed cause of spot termination, but failed to full teardown and create the `email_results.json` for the email report
so no mail, and argus still thinks it's running.
```
16:57:48  Traceback (most recent call last):
16:57:48    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/events_analyzer.py", line 50, in run
16:57:48      raise TestFailure(f"Got critical event: {event}")
16:57:48  sdcm.sct_events.events_analyzer.TestFailure: Got critical event: (SpotTerminationEvent Severity.CRITICAL) period_type=one-time event_id=143b4f1a-4ef3-46d3-8e82-7a19ade79758: node=Node longevity-10gb-3h-master-db-node-4d7864c4-eastus-1 [20.83.148.146 | 10.0.0.5] (seed: True) message=Got spot termination event for node: ['longevity-10gb-3h-master-db-node-eastus-1']. VM eviction time is Wed, 31 Aug 2022 13:57:57 GMT.
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4d7864c4-e593-4102-95fa-72c781bfe4cd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4d7864c4-e593-4102-95fa-72c781bfe4cd)
- Show all stored logs command: `$ hydra investigate show-logs 4d7864c4-e593-4102-95fa-72c781bfe4cd`

## Logs:
- **db-cluster-4d7864c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/db-cluster-4d7864c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/db-cluster-4d7864c4.tar.gz)
- **monitor-set-4d7864c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/monitor-set-4d7864c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/monitor-set-4d7864c4.tar.gz)
- **loader-set-4d7864c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/loader-set-4d7864c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/loader-set-4d7864c4.tar.gz)
- **sct-runner-4d7864c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/sct-runner-4d7864c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/sct-runner-4d7864c4.tar.gz)
- **parallel-timelines-report-4d7864c4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/parallel-timelines-report-4d7864c4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d7864c4-e593-4102-95fa-72c781bfe4cd/20220831_135815/parallel-timelines-report-4d7864c4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/72/)

**Comment by soyacz** [comment]
Issue with argus is due to failing setting sct-runner tags (https://github.com/scylladb/scylla-cluster-tests/issues/5173) - in collect-logs step, update Argus is happening after this breaking error. 
But email should be sent properly. I'll check that.
cc @KnifeyMoloko
