### ISSUE TITLE
screenshots are broken

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#5224]
### Versions
* **SCT**: branch-5.1
* **scylla**: 5.1.0~rc1-20220902.d10aee15e7e9

## Installation details

Kernel Version: 5.15.0-1017-gcp
Scylla version (or git commit hash): `5.1.0~rc1-20220902.d10aee15e7e9` with build-id `c127c717ecffa082ce97b94100d62b2549abe486`
Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-f5c9fe20-0-8 (35.185.40.129 | 10.142.0.36) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-7 (34.148.244.33 | 10.142.0.14) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-6 (35.190.153.236 | 10.142.0.19) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-5 (34.73.211.72 | 10.142.0.99) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-4 (35.237.185.213 | 10.142.0.94) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-3 (35.185.104.213 | 10.142.0.63) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-2 (34.75.177.80 | 10.142.0.41) (shards: 14)
- longevity-10gb-3h-master-db-node-f5c9fe20-0-1 (35.227.5.57 | 10.142.0.3) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/8643501423004157603` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9`
Test name: `scylla-5.1/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4f18985607e1743166218ff99df0ab8015f7c877/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**

the screenshots attached to Argus and to email are missing the 1st charts (that show the load, operations level and nemesis), maybe because with the new panels it became too long.

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9)
- Show all stored logs command: `$ hydra investigate show-logs f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9`

## Logs:
- **db-cluster-f5c9fe20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/db-cluster-f5c9fe20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/db-cluster-f5c9fe20.tar.gz)
- **monitor-set-f5c9fe20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/monitor-set-f5c9fe20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/monitor-set-f5c9fe20.tar.gz)
- **loader-set-f5c9fe20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/loader-set-f5c9fe20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/loader-set-f5c9fe20.tar.gz)
- **sct-runner-f5c9fe20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/sct-runner-f5c9fe20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/sct-runner-f5c9fe20.tar.gz)
- **parallel-timelines-report-f5c9fe20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/parallel-timelines-report-f5c9fe20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f5c9fe20-01a2-41a7-9e3b-e76337bc9bb9/20220903_141655/parallel-timelines-report-f5c9fe20.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/longevity/job/longevity-10gb-3h-gce-test/4/)

**Comment by fgelcer** [comment]
it too and example from the test mentioned in the subject:

![unnamed (1)](https://user-images.githubusercontent.com/32832995/188413914-47806d02-b93c-4512-b3ef-c8588e883b93.png)

**Comment by aleksbykov** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/5226
