### ISSUE TITLE
test longevity-5000-tables, sct runner runs out of disk space

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5234]
On two distinct runs we are getting ENOSPC on the runner while doing log collection:

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/scale-5000-tables-test/3/execution/node/192/log/

```
08:39:51  OSError: [Errno 28] No space left on device: '/home/ubuntu/sct-results/20220901-111753-594641/hosts/longevity-5000-tables-docker-l-db-node-e06c2c79-4/messages.log' -> '/home/ubuntu/sct-results/20220901-111817-596903/collected_logs/20220902_053340/db-cluster-e06c2c79/messages.log'
```

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/scale-5000-tables-test/2/execution/node/192/log/

```
08:34:07  OSError: [Errno 28] No space left on device: '/home/ubuntu/sct-results/20220831-195533-913329/hosts/longevity-5000-tables-docker-l-db-node-c8b54d45-1/messages.log' -> '/home/ubuntu/sct-results/20220831-195558-428450/collected_logs/20220901_052407/db-cluster-c8b54d45/messages.log'
```

it's not clear to yet, if the sizes of the db logs grow substantially, or it's the  sct.log that did.
anyhow the disk size of the runner is base on this logic:
```
    @staticmethod
    def instance_root_disk_size(test_duration) -> int:
        disk_size = 80  # GB
        if test_duration and test_duration > 3 * 24 * 60:  # 3 days
            # add 40G more space for jobs which test_duration is longer than 3 days
            return disk_size + 40
        return disk_size
```

we probably need some control to set the runner properties, like type/disks size, so we could configure it for some cases specifically

**Comment by fruch** [comment]
@roydahan heads up, if you were planning to run this test for the upcoming release.

**Comment by vponomaryov** [comment]
@fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386 :

**Comment by fruch** [comment]
> @fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386

based on what ?, on the name of the job ? on name of the configuration ?, i.e. the code calling this in the pipeline, and I rather have it configurable like any other thing in SCT

**Comment by vponomaryov** [comment]
> > @fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386
> 
> based on what ?, on the name of the job ? on name of the configuration ?, i.e. the code calling this in the pipeline, and I rather have it configurable like any other thing in SCT

Based on the job time range as a first step.

**Comment by fruch** [comment]
> > > @fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386
> > 
> > 
> > based on what ?, on the name of the job ? on name of the configuration ?, i.e. the code calling this in the pipeline, and I rather have it configurable like any other thing in SCT
> 
> Based on the job time range as a first step.

that code we already have, as I've mentioned it in the description here. I want a way to be able to set for specific test different parameters for the runner. in my case the test isn't 3days, it shorter, but might generate much more logs.

I think we need a coherent way to configure those, and not by embedding that logic into the the pipeline phase.
phase one, might be pipeline params only for those values.

**Comment by fgelcer** [comment]
> > > > @fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386
> > > 
> > > 
> > > based on what ?, on the name of the job ? on name of the configuration ?, i.e. the code calling this in the pipeline, and I rather have it configurable like any other thing in SCT
> > 
> > 
> > Based on the job time range as a first step.
> 
> that code we already have, as I've mentioned it in the description here. I want a way to be able to set for specific test different parameters for the runner. in my case the test isn't 3days, it shorter, but might generate much more logs.
> 
> I think we need a coherent way to configure those, and not by embedding that logic into the the pipeline phase. phase one, might be pipeline params only for those values.

maybe to calculate the data size by the stress commands? we can know ahead of time the size of each dataset, no?

**Comment by fruch** [comment]
> > > > > @fruch Just use `--root-disk-size-gb` cmd option: https://github.com/scylladb/scylla-cluster-tests/blob/4f189856/sct.py#L1386
> > > > 
> > > > 
> > > > based on what ?, on the name of the job ? on name of the configuration ?, i.e. the code calling this in the pipeline, and I rather have it configurable like any other thing in SCT
> > > 
> > > 
> > > Based on the job time range as a first step.
> > 
> > 
> > that code we already have, as I've mentioned it in the description here. I want a way to be able to set for specific test different parameters for the runner. in my case the test isn't 3days, it shorter, but might generate much more logs.
> > I think we need a coherent way to configure those, and not by embedding that logic into the the pipeline phase. phase one, might be pipeline params only for those values.
> 
> maybe to calculate the data size by the stress commands? we can know ahead of time the size of each dataset, no?

log size isn't necessary related to data size, if can be cause by a scylla or sct bug, but we need to be able to configure those values, and not that would be better then guessing  them.

**Comment by roydahan** [comment]
When getting test_duration we should get maybe one or more params that may hint on larger disk size needed for the runner.
