### ISSUE TITLE
[artifacts] The timeout parameter is too short (30m)

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#5247]
I saw a few artifacts jobs that failed [0][1] on a timeout that is currently configured to 30 minutes,
If the runtime-increase for these jobs is not an issue (and we should make sure it's not) we should update the `timeout: [time: 30, unit: 'MINUTES'],` to 60 for all artifacts jobs,

Or even better, set it once and global on `vars/artifactsPipeline.groovy`

[0] https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-rocky8-test/25/
[1] https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-debian10-test/25/

**Comment by fgelcer** [comment]
until today we had artifacts happening within the timeout set for it, so before increasing its timeout, we must understand why is it taking longer now

**Comment by benipeled** [comment]
5.0.3 release is (kind of) blocked by this issue + we have many failures from different branches following this issue

**Comment by benipeled** [comment]
Similar failure - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/520/
The job stuck on 
```
06:40:31  < t:2022-09-11 03:40:28,736 f:artifacts_test.py l:400  c:ArtifactsTest        p:INFO  > Validate version after restart
06:40:31  < t:2022-09-11 03:40:29,515 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-09-11 03:40:29.513: (ScyllaHousekeepingServiceEvent Severity.NORMAL) period_type=one-time event_id=6a1ff6b3-20a5-431b-bfec-8a46d6446a65: message=scylla-housekeeping-restart service running
06:42:44  < t:2022-09-11 03:42:36,216 f:wait.py         l:68   c:sdcm.wait            p:ERROR > Wait for: _file_exists: timeout - 600 seconds - expired
06:42:44  < t:2022-09-11 03:42:36,216 f:wait.py         l:72   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f1ebec99ab0 state=finished returned bool>)
06:42:44  < t:2022-09-11 03:42:36,217 f:remote_logger.py l:93   c:SSHScyllaFileLogger  p:ERROR > Error retrieving remote node DB service log: RetryError[Wait for: _file_exists: timeout - 600 seconds - expired]
```
and reach the timeout

**Comment by fruch** [comment]
looks like something bad is going with the housekeeping db:
```
< t:2022-09-11 03:29:16,277 f:housekeeping.py l:56   c:sdcm.utils.housekeeping p:DEBUG > Query: `SELECT id, version, ip, statuscode FROM housekeeping.checkversion WHERE uuid = %s ORDER BY -dt LIMIT 1', Args: ('fe1bf478-3180-11ed-830f-0242ac110002',)

< t:2022-09-11 03:37:17,351 f:housekeeping.py l:61   c:sdcm.utils.housekeeping p:INFO  > Result: [(27139603, '5.2.0~dev', '52.18.93.225', 'cr')]
```

8min query to the DB ???, and we have multiple of those in those tests.

**Comment by roydahan** [comment]
Since @amnonh is out, @slivne asked to workaround it for now by increasing the timeout since it's blocking the 5.0.3.
@benipeled / @fruch can one of you send a PR to increase the timeout in few minutes? (5?)

**Comment by fgelcer** [comment]
> Since @amnonh is out, @slivne asked to workaround it for now by increasing the timeout since it's blocking the 5.0.3. @benipeled / @fruch can one of you send a PR to increase the timeout in few minutes? (5?)

sent it here --> #5257
please review and merged, so we can re-run the jobs for 5.0.3

**Comment by amnonh** [comment]
I did some datbase optimization, now it completes under a second

**Comment by fgelcer** [comment]
> I did some datbase optimization, now it completes under a second

@amnonh , is it already in branch-5.0? or we should change something to get this optimizations into that branch?

**Comment by fruch** [comment]
> > I did some datbase optimization, now it completes under a second
> 
> @amnonh , is it already in branch-5.0? or we should change something to get this optimizations into that branch?

the part @amnonh is optimizing isn't part of any branched code... (it's affect them all)

**Comment by fgelcer** [comment]
so, this issue was created against `branch-5.0`, and i have run reverting the workaround (including Amnon's optimization) and it passed. Hence we can close this one.
