### ISSUE TITLE
Error: Prometheus container failed to start

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5250]
Might be related to commit
fb2f577d - fix(start_monitoring): Set large retention prometheus period (23 hours ago) <Aleksandr Bykov>

error:
```
2022-09-08 07:48:13.658: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=bb3a427f-ced8-4a2c-9be6-1c8a67c28bf3, source=LargePartitionLongevityTest.SetUp()
exception=[Node longevity-large-partitions-4d-scyll-monitor-node-c0dab257-1 [16.170.238.94 | 10.0.1.237] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'bash -ce \'\ncd -P /home/centos/sct-monitoring/scylla-monitoring-src\nmkdir -p /home/centos/sct-monitoring/scylla-monitoring-data\necho "" > UA.sh\nPATH=$PATH:/usr/sbin ./start-all.sh             -D "--label RunByUser=yarongilor --label TestName=longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity --label TestId=c0dab257-fd10-4103-85b3-d4184a267666 --label version=scylla-staging --label CreatedBy=SCT --label JenkinsJobTag=jenkins-scylla-staging-Longevity_yaron-longevity-large-partition-4days-test-rq-11 --label NodeType=monitor --label keep_action=terminate --label Name=longevity-large-partitions-4d-scyll-monitor-node-c0dab257-1 --label UserName=centos --label NodeIndex=1"             -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"`             -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"`             -N `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_manager_servers.yml"`             -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master,5.0             -b "-web.enable-admin-api -storage.tsdb.retention.time=365d"             -c \'GF_USERS_DEFAULT_THEME=dark\'\n\''
Exit code: 1
Stdout:
Loading prometheus data from /home/centos/sct-monitoring/scylla-monitoring-data
Wait for alert manager container to start
Wait for Loki container to start.
Using single hyphen is depricated and will be removed in future version use --web.enable-admin-api -storage.tsdb.retention.time=365d instead
1b18fc20274d62a060ee503f2b2de452de2dff2093722cb6cf02aef0c2527d0e
Wait for Prometheus container to start........
Error: Prometheus container failed to start
For more information use: docker logs aprom
Stderr:
af1d3a52da4e: Pull complete
4d08c466a1d1: Pull complete
9c6d6afbec8e: Pull complete
019f81b64579: Pull complete
efec518336ea: Pull complete
4a028982dd68: Pull complete
20e1e75ff0e2: Pull complete
f69724d873f8: Pull complete
Digest: sha256:56e7f18e05dd567f96c05046519760b356f52450c33f6e0055a110a493a41dc4
Status: Downloaded newer image for prom/prometheus:v2.37.0
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3433, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4814, in node_setup
self.start_scylla_monitoring(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 5132, in start_scylla_monitoring
node.remoter.run("bash -ce '%s'" % run_script, verbose=True)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -ce \'\ncd -P /home/centos/sct-monitoring/scylla-monitoring-src\nmkdir -p /home/centos/sct-monitoring/scylla-monitoring-data\necho "" > UA.sh\nPATH=$PATH:/usr/sbin ./start-all.sh             -D "--label RunByUser=yarongilor --label TestName=longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity --label TestId=c0dab257-fd10-4103-85b3-d4184a267666 --label version=scylla-staging --label CreatedBy=SCT --label JenkinsJobTag=jenkins-scylla-staging-Longevity_yaron-longevity-large-partition-4days-test-rq-11 --label NodeType=monitor --label keep_action=terminate --label Name=longevity-large-partitions-4d-scyll-monitor-node-c0dab257-1 --label UserName=centos --label NodeIndex=1"             -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"`             -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"`             -N `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_manager_servers.yml"`             -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master,5.0             -b "-web.enable-admin-api -storage.tsdb.retention.time=365d"             -c \'GF_USERS_DEFAULT_THEME=dark\'\n\''
Exit code: 1
Stdout:
Loading prometheus data from /home/centos/sct-monitoring/scylla-monitoring-data
Wait for alert manager container to start
Wait for Loki container to start.
Using single hyphen is depricated and will be removed in future version use --web.enable-admin-api -storage.tsdb.retention.time=365d instead
1b18fc20274d62a060ee503f2b2de452de2dff2093722cb6cf02aef0c2527d0e
Wait for Prometheus container to start........
Error: Prometheus container failed to start
For more information use: docker logs aprom
Stderr:
af1d3a52da4e: Pull complete
4d08c466a1d1: Pull complete
9c6d6afbec8e: Pull complete
019f81b64579: Pull complete
efec518336ea: Pull complete
4a028982dd68: Pull complete
20e1e75ff0e2: Pull complete
f69724d873f8: Pull complete
Digest: sha256:56e7f18e05dd567f96c05046519760b356f52450c33f6e0055a110a493a41dc4
Status: Downloaded newer image for prom/prometheus:v2.37.0

```

*Installation details*
Kernel version: `5.15.0-1015-aws`
Scylla version (or git commit hash): `5.0.2-0.20220807.299122e78 with build-id 01a9300a0f113d968f4d199f85240a43ff7f1a5a`
Cluster size: 4 nodes (i3en.3xlarge)
Scylla running with shards number (live nodes):
   longevity-large-partitions-4d-scyll-db-node-c0dab257-1 (16.171.55.178 | 10.0.1.79): 12 shards
   longevity-large-partitions-4d-scyll-db-node-c0dab257-2 (13.53.123.226 | 10.0.2.23): 12 shards
   longevity-large-partitions-4d-scyll-db-node-c0dab257-3 (13.48.105.19 | 10.0.1.61): 12 shards
   longevity-large-partitions-4d-scyll-db-node-c0dab257-4 (13.53.123.163 | 10.0.1.119): 12 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0d3bc0707779f43f5` (aws: eu-north-1)

Test: `longevity-large-partition-4days-test-rq`
Test name: `longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity`
Test config file(s):
- [longevity-large-partition-4days.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/5927a0ef41a9f26e1d67594fcc282f16d3eee0d6/test-cases/longevity/longevity-large-partition-4days.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/5927a0ef41a9f26e1d67594fcc282f16d3eee0d6/test-cases/longevity/longevity-large-partition-4days.yaml&source=gmail-html&ust=1662724050373000&usg=AOvVaw2-1Njcp1CkP7BEpHm8cELi))

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor c0dab257-fd10-4103-85b3-d4184a267666`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=scylla_bench_reversed_queries&test_id=c0dab257-fd10-4103-85b3-d4184a267666](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dscylla_bench_reversed_queries%26test_id%3Dc0dab257-fd10-4103-85b3-d4184a267666&source=gmail-html&ust=1662724050373000&usg=AOvVaw2qXZHy6s1CNQ4nzEdkMU02))
Show all stored logs command: `$ hydra investigate show-logs c0dab257-fd10-4103-85b3-d4184a267666`

Test id: `c0dab257-fd10-4103-85b3-d4184a267666`

Logs:
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/db-cluster-c0dab257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/db-cluster-c0dab257.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/db-cluster-c0dab257.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/db-cluster-c0dab257.tar.gz)&source=gmail-html&ust=1662724050373000&usg=AOvVaw0TFJnXILHLQkiqtTbWZYUx)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/loader-set-c0dab257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/loader-set-c0dab257.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/loader-set-c0dab257.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/loader-set-c0dab257.tar.gz)&source=gmail-html&ust=1662724050373000&usg=AOvVaw0kvlNsg0R2QnFYA95F42nC)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/monitor-set-c0dab257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/monitor-set-c0dab257.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/monitor-set-c0dab257.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/monitor-set-c0dab257.tar.gz)&source=gmail-html&ust=1662724050373000&usg=AOvVaw3DvPcMqGASQGtgXGVY7ScV)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/sct-runner-c0dab257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/sct-runner-c0dab257.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/sct-runner-c0dab257.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c0dab257-fd10-4103-85b3-d4184a267666/20220908_074909/sct-runner-c0dab257.tar.gz)&source=gmail-html&ust=1662724050373000&usg=AOvVaw2wbiC4ARQA9JYE85Ux1YYB)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/11/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-rq/11/&source=gmail-html&ust=1662724050373000&usg=AOvVaw1LNLdv5X4fh9GOT7ZIASyV))

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5252 fixes this issue
