### ISSUE TITLE
rebuild_streaming_err: nodetool rebuild was started after hard reboot before Scylla started up

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5285]
*Installation details*
Kernel version: `5.15.0-1019-aws`
Scylla version (or git commit hash): `2022.2.0~rc1-0.20220902.a9bc6d191031 with build-id 074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Relocatable package url: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc1.0.20220902.a9bc6d191031.tar.gz
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-2 (13.48.45.18 | 10.0.1.91): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-3 (16.170.143.164 | 10.0.1.53): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-6 (13.53.198.214 | 10.0.0.174): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-7 (13.50.5.213 | 10.0.0.77): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-8 (13.53.91.98 | 10.0.2.42): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-9 (13.51.47.12 | 10.0.1.169): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-1 (16.16.24.190 | 10.0.1.154): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-4 (13.49.23.122 | 10.0.1.126): 14 shards
   longevity-sla-100gb-4h-fullscan-db-node-79f1a711-5 (16.170.159.11 | 10.0.3.71): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-05f86f53369e36f05` (aws: eu-north-1)

Test: `staging-sla-fullscan-100gb-4h`
Test name: `longevity_sla_test.LongevitySlaTest.test_custom_time`
Test config file(s):
- [longevity-sla-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b952fd3e096ca8ec4a5e3e9929a74ffe4638e99b/test-cases/longevity/longevity-sla-100gb-4h.yaml)

**Issue description**

Nemesis `disrupt_rebuild_streaming_err` failed with error:
```
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_rebuild_streaming_err at 0x7f63018c7640>
 < t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_rebuild_streaming_err at 0x7f63018c7640
>
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3653, in wrapper
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3178, in disrupt_rebuild_streaming_err
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     self.start_and_interrupt_rebuild_streaming()
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3158, in start_and_interrupt_rebuild_streaming
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     self.target_node.run_nodetool("rebuild")
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2528, in run_nodetool
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     result = connection.run(**command_kwargs)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild "
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
< t:2022-09-14 18:29:48,474 f:nemesis.py      l:3663 c:sdcm.nemesis         p:ERROR > 
```

Rebuild was started and interrupted by node reboot. 
Scylla is starting at `Sep 14 18:29:15 `:
```
Sep 14 18:29:15 longevity-sla-100gb-4h-fullscan-db-node-79f1a711-8 scylla[1008]:  [shard  0] init - Scylla version 2022.2.0~rc1-0.20220902.a9bc6d191031 with build-id 074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda starting ...
```

And completed at `Sep 14 18:30:17`:
```
Sep 14 18:30:17 longevity-sla-100gb-4h-fullscan-db-node-79f1a711-8 scylla[1008]:  [shard  0] init - Scylla version 2022.2.0~rc1-0.20220902.a9bc6d191031 initialization completed.
```

But rebuild was triggered again at `18:29:46,471` (https://github.com/scylladb/scylla-cluster-tests/blob/291b4cefcf957ba5b48569d891e19c05940d9e33/sdcm/nemesis.py#L3163), when Scylla was not up yet
```
< t:2022-09-14 18:29:46,471 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  rebuild "...
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 79f1a711-716a-41e0-9533-6e6e20810b72`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=fullscan_support_in_sla_longevity&test_id=79f1a711-716a-41e0-9533-6e6e20810b72)
Show all stored logs command: `$ hydra investigate show-logs 79f1a711-716a-41e0-9533-6e6e20810b72`

Test id: `79f1a711-716a-41e0-9533-6e6e20810b72`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/79f1a711-716a-41e0-9533-6e6e20810b72/20220914_201044/db-cluster-79f1a711.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/79f1a711-716a-41e0-9533-6e6e20810b72/20220914_201044/db-cluster-79f1a711.tar.gz)

sct - [https://cloudius-jenkins-test.s3.amazonaws.com/79f1a711-716a-41e0-9533-6e6e20810b72/20220914_201044/sct-runner-79f1a711.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/79f1a711-716a-41e0-9533-6e6e20810b72/20220914_201044/sct-runner-79f1a711.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/staging-sla-fullscan-100gb-4h/14/)

**Comment by fruch** [comment]
@juliayakovlev  so we are not waiting for the node to be up and ready after the reboot ?
