### ISSUE TITLE
`disrupt_add_remove_dc` method does not clean its keyspace after deleting new dc

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#5299]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: `a1247e59bcdcd5a41782f0d1ca20474a71b03295`
* **scylla**: ami-07195ac2cba9f0291 (2022.2)

### Logs
* test_id: 939938a6-56d0-4745-afc7-d9da64274390
* job log:
- **db-cluster-939938a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/db-cluster-939938a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/db-cluster-939938a6.tar.gz)
- **monitor-set-939938a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/monitor-set-939938a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/monitor-set-939938a6.tar.gz)
- **loader-set-939938a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/loader-set-939938a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/loader-set-939938a6.tar.gz)
- **sct-runner-939938a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/sct-runner-939938a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/939938a6-56d0-4745-afc7-d9da64274390/20220909_102427/sct-runner-939938a6.tar.gz)

### Description

`disrupt_add_remove_dc` creates a keyspace shared between two datacenters, but doesn't delete it at the end of the nemesis, leading to consistency issues later down the line:
```
2022-09-08 15:28:55.149: (CassandraStressEvent Severity.ERROR) period_type=end event_id=29288213-9b2d-4c4c-8150-8ab11d7d101b duration=44s: node=Node longevity-200gb-48h-verify-limited--loader-node-939938a6-1 [63.33.59.139 | 10.4.10.113] (seed: False)
stress_cmd=cassandra-stress write n=400000 cl=QUORUM -mode native cql3 -schema 'replication(factor=4)' -log interval=5
errors:
Stress command completed with bad status 1: WARN  15:28:19,022 Error while computing token map for keyspace keyspace_new_dc with datacenter eu-w
<...>
< t:2022-09-08 16:06:56,340 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=D68X38PMH694WL2PJTR9; cassandra-stress write n=400000 cl=QUORUM -mode native cql3  user=cassandra password=cassandra -schema keyspace=drop_table_during_repair_ks_9 'replication(factor=4)' -log interval=5 -transport "truststore=/etc/scylla/ssl_conf/client/cacerts.jks truststore-password=cassandra" -node 10.4.11.251,10.4.9.10,10.4.8.142,10.4.8.173 -errors skip-unsupported-columns"; Exit status: 1
< t:2022-09-08 16:06:56,341 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-09-08T16:06:56+00:00 longevity-200gb-48h-verify-limited--db-node-939938a6-1     !INFO | scylla[7764]:  [shard  5] commitlog - Commitlog shutdown complete
< t:2022-09-08 16:06:56,341 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: WARN  16:06:29,632 Error while computing token map for keyspace keyspace_new_dc with datacenter eu-west_nemesis_dc: could not achieve replication factor 1 (found 0 replicas only), check your keyspace replication settings.

```

### Steps to Reproduce

1. Observe addremovedc nemesis
2. run `DESCRIBE SCHEMA` on one of the remaining nodes
3. See that `keyspace_new_dc` still exists even after nemesis ended.

**Comment by fruch** [comment]
Stress failing cause of a keyspace it's not using... this is quite weird...

**Comment by soyacz** [comment]
> Stress failing cause of a keyspace it's not using... this is quite weird...

@fruch I think because we don't switch back replication strategy after nemesis: https://github.com/scylladb/scylla-cluster-tests/issues/5236

I'll fix both issues promptly.

**Comment by soyacz** [comment]
Fix was merged, please reopen if issue persists.
