### ISSUE TITLE
Unable to find table feeds.table5000 error in 5000 tables test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5326]
When running 5000 table test we can see error:
```
2022-09-28 21:26:15.655: (CassandraStressEvent Severity.ERROR) period_type=end event_id=0611da87-380b-433c-b72a-8d287c03efe8 duration=19s: node=Node longevity-5000-tables-scale-te-loader-node-9432a26c-1 [3.248.230.89 | 10.4.0.156] (seed: False)
stress_cmd=cassandra-stress user profile=/tmp/templated_tables_mvxl6x90gb.yaml cl=QUORUM 'ops(insert=1, read1=5)' duration=55m -rate threads=2 -errors ignore -node 10.4.3.123,10.4.3.250,10.4.2.4,10.4.0.121,10.4.3.131,10.4.1.147
errors:
Stress command completed with bad status 1: java.lang.RuntimeException: Unable to find table feeds.table5000
at org.apache.cassandra.stress.Str
```

table5000 is never created as pre creating is 0 indexed: table0...table4999
So c-s should never run against this index.

Test details:

## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc1.0.20220902.a9bc6d191031.tar.gz
Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-scale-te-db-node-9432a26c-7 (176.34.94.226 | 10.4.1.154) (shards: -1)
- longevity-5000-tables-scale-te-db-node-9432a26c-6 (34.247.69.21 | 10.4.1.147) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-5 (52.48.210.162 | 10.4.3.131) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-4 (52.50.144.231 | 10.4.0.121) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-3 (54.154.228.197 | 10.4.2.4) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-2 (54.75.40.247 | 10.4.3.250) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-1 (52.51.92.89 | 10.4.3.123) (shards: 30)

OS / Image: `ami-0492fd8e302e5af45` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `9432a26c-4f6a-472e-82fc-12eda02a1916`
Test name: `enterprise-2022.2/scale/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f275e01e52e838da724c69e0416d2da8078b514/test-cases/scale/longevity-5000-tables.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9432a26c-4f6a-472e-82fc-12eda02a1916`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9432a26c-4f6a-472e-82fc-12eda02a1916)
- Show all stored logs command: `$ hydra investigate show-logs 9432a26c-4f6a-472e-82fc-12eda02a1916`

## Logs:
- **db-cluster-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz)
- **monitor-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz)
- **loader-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz)
- **sct-runner-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/scale/job/scale-5000-tables-test/5/)

**Comment by fruch** [comment]
This shouldn't be an issue, since c-s should be creating its own tables if not exist.

**Comment by roydahan** [comment]
Right.

**Comment by fruch** [comment]
> Somehow it didn't work, maybe table creation didn't propagate quickly enough to nodes. Anyway, this test precreates tables except this one and this looks like unintended exception. Shouldn't we fix that?

logs show it created the schema, and waited for 12sec
```
Created schema. Sleeping 6s for propagation.
Created extra schema. Sleeping 6s for propagation.
java.lang.RuntimeException: Unable to find table feeds.table5000
```

this "bug" in the test was there since it was first written, and this failure is a regression.
regardless the test by design is running few commands without precreate schemes, and those should work. (and was working in previous releases)

one more thing, all the stress commands in this test case were supposed to be mark as `stop_test_on_failure=False`, did the test stop on this failure ?

**Comment by soyacz** [comment]
> > Somehow it didn't work, maybe table creation didn't propagate quickly enough to nodes. Anyway, this test precreates tables except this one and this looks like unintended exception. Shouldn't we fix that?
> 
> logs show it created the schema, and waited for 12sec
> 
> ```
> Created schema. Sleeping 6s for propagation.
> Created extra schema. Sleeping 6s for propagation.
> java.lang.RuntimeException: Unable to find table feeds.table5000
> ```
> 
> this "bug" in the test was there since it was first written, and this failure is a regression. regardless the test by design is running few commands without precreate schemes, and those should work. (and was working in previous releases)

We cannot be sure if this is a regression - I executed this test twice for 2022.2-rc2 and during first time it didn't happen. So it could also not happen in the same way in previous versions.

> one more thing, all the stress commands in this test case were supposed to be mark as `stop_test_on_failure=False`, did the test stop on this failure ?

No it didn't stop the test.

@fruch what do we do with this SCT issue? Fix or close?

**Comment by fruch** [comment]
I think we need to check which nodes didn't create the schema for this table, and raise it as a scylla issue.

we can still fix the test, for clarity. since that specific table was intended to be unprepared.

**Comment by soyacz** [comment]
Thanks @fruch for your feedback. I examined this test deeply and found, that this table was precreated (but at later stage). This happened during one node being down and looks it was not propagated after startup. I created issue: https://github.com/scylladb/scylladb/issues/11675 I hope I did it well and added proper description.

This issue is not valid. Closing it.
