### ISSUE TITLE
TOLERABLE_REACTOR_STALL is not working

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5342]
When reactor stall exceeds TOLERABLE_REACTOR_STALL, event severity should be increased to ERROR (according to unit tests, which pass). It looks that this is not happening and these events are reported as warnings. 

Example test run:

## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.1.2-20220905.f1a246a8b` with build-id `aae082a8a9a1136b4d3f3751749267327a63014b`

Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-reproduc-db-node-8db6ab30-6 (3.250.220.62 | 10.0.1.209) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-5 (79.125.34.166 | 10.0.1.25) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-4 (34.255.6.152 | 10.0.0.230) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-3 (52.212.41.113 | 10.0.2.215) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-2 (54.75.69.167 | 10.0.0.63) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-1 (54.154.70.125 | 10.0.1.160) (shards: 30)

OS / Image: `ami-0ba5ceb867818a6ad` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `8db6ab30-2633-481c-8dd0-4a0c86d3a287`
Test name: `scylla-staging/lukasz/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/62dbcd4cfd040a9b79c3db0f42ca0a1f7db4a183/test-cases/scale/longevity-5000-tables.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8db6ab30-2633-481c-8dd0-4a0c86d3a287`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8db6ab30-2633-481c-8dd0-4a0c86d3a287)
- Show all stored logs command: `$ hydra investigate show-logs 8db6ab30-2633-481c-8dd0-4a0c86d3a287`

## Logs:
- **db-cluster-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/db-cluster-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/db-cluster-8db6ab30.tar.gz)
- **monitor-set-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/monitor-set-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/monitor-set-8db6ab30.tar.gz)
- **loader-set-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/loader-set-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/loader-set-8db6ab30.tar.gz)
- **sct-runner-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/sct-runner-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/sct-runner-8db6ab30.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scale-5000-tables-test/2/)

**Comment by fgelcer** [comment]
@soyacz , this will hopefully fix the problem --> #5343
