### ISSUE TITLE
Fix or skip add-remove-dc for multi-dc tests

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5369]
When running multidc scenario, add_remove_dc is failing causing even more issues in other nemesis (The add_dc configuration is wrong and then it started failing everything that is related to configuration), see comment in Argus:
https://argus.scylladb.com/test/47886b99-ea7a-4109-be02-0dd01f45ea18/runs?additionalRuns[]=93e3af19-ec5a-4ff8-816f-d9ff29ac174d

## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc2-20220919.75d087a2b75a` with build-id `463f1a57b82041a6c6b6441f0cbc26c8ad93091e`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc2.0.20220919.75d087a2b75a.tar.gz
Cluster size: 8 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-9 (54.159.140.96 | 10.12.4.176) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-8 (18.207.214.240 | 10.12.7.38) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-7 (3.90.4.74 | 10.12.7.51) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-6 (3.88.40.151 | 10.12.6.54) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-5 (3.92.208.67 | 10.12.4.69) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-4 (54.78.3.179 | 10.4.6.70) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-3 (18.203.68.41 | 10.4.6.107) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-2 (34.249.38.61 | 10.4.7.249) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-19 (54.216.235.235 | 10.4.4.243) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-18 (63.32.89.181 | 10.4.7.123) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-17 (34.243.241.23 | 10.4.6.83) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-16 (54.165.189.148 | 10.12.6.18) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-15 (44.204.160.90 | 10.12.7.121) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-14 (54.197.43.143 | 10.12.6.139) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-13 (54.166.3.166 | 10.12.7.224) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-12 (52.31.19.140 | 10.4.5.170) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-11 (176.34.207.154 | 10.4.7.12) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-10 (44.201.79.192 | 10.12.5.115) (shards: 14)
- longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-1 (3.252.209.42 | 10.4.7.121) (shards: 14)

OS / Image: `ami-00bd31f22bcf5ae1a ami-0b6ff8cdcbe0cb88a` (aws: eu-west-1)

Test: `longevity-cdc-8h-multi-dc-topology-changes-test`
Test id: `93e3af19-ec5a-4ff8-816f-d9ff29ac174d`
Test name: `enterprise-2022.2/longevity/longevity-cdc-8h-multi-dc-topology-changes-test`
Test config file(s):

- [longevity-cdc-100gb-8h-multi-dc-topology-changes.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a517ae8d5d433b425e07e61ca15248880971b5a1/test-cases/longevity/longevity-cdc-100gb-8h-multi-dc-topology-changes.yaml)

## Issue description

- Restore Monitor Stack command: `$ hydra investigate show-monitor 93e3af19-ec5a-4ff8-816f-d9ff29ac174d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=93e3af19-ec5a-4ff8-816f-d9ff29ac174d)
- Show all stored logs command: `$ hydra investigate show-logs 93e3af19-ec5a-4ff8-816f-d9ff29ac174d`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-cdc-8h-multi-dc-topology-changes-test/6/)

**Comment by fruch** [comment]
@soyacz 

I think some of this issue we should fix:
```
2022-10-11T21:02:57+00:00 longevity-cdc-100gb-8h-multi-dc-tpc-db-node-93e3af19-11      !ERR | scylla[7800]:  [shard  0] snitch_logger - double "dc_suffix" declaration in /etc/scylla/cassandra-rackdc.properties
```

and yes we can skip this nemesis, base on number of DCs available.
But we should be addressing/fixing for the long run

**Comment by fgelcer** [comment]
we should either send the workaround to skip the nemesis when we are already running with Multi-DC, or fix it... and we should get it done ASAP so we can re-run the failed tests for RC4.
@KnifeyMoloko @soyacz

**Comment by soyacz** [comment]
> we should either send the workaround to skip the nemesis when we are already running with Multi-DC, or fix it... and we should get it done ASAP so we can re-run the failed tests for RC4. @KnifeyMoloko @soyacz

Please review & merge: https://github.com/scylladb/scylla-cluster-tests/pull/5392
