### ISSUE TITLE
Two events with different event_id for same core dump

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5371]
When coredump happens we publish 2 events with different `event_id`: when coredump has been recognozed first time and when core dump has been uploaded. But we do not have 2 coredumps, it's the same event and we need to keep all info of first published event for second published event. Additional to problem of different id, that's wrong, we can miss another info, like `during_nemesis`, like in example:

```
2022-10-31 00:14:00.579: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=92206cab-4386-4f2d-aabb-1cbc6af9abc5 during_nemesis=GrowShrinkCluster node=Node longevity-10gb-3h-master-db-node-4e06109c-eastus-6 [172.174.48.182 | 10.0.0.10] (seed: False)
2022-10-31 00:17:58.244 <2022-10-31 00:12:46.000>: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=7ffc6cf5-aa03-4d84-8687-8fe6730a98fc node=Node longevity-10gb-3h-master-db-node-4e06109c-eastus-6 [172.174.48.182 | 10.0.0.10] (seed: False)
```

*Installation details*
Kernel version: `5.15.0-1022-azure`
Scylla version (or git commit hash): `5.2.0~dev-0.20221030.477e0c967a24 with build-id 372975eedadd13b192b103b64adcf0de546ee4a6`
Cluster size: 6 nodes (Standard_L8s_v3)
Scylla running with shards number (live nodes):
   longevity-10gb-3h-master-db-node-4e06109c-eastus-1 (20.169.170.178 | 10.0.0.5): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-2 (172.174.48.168 | 10.0.0.6): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-3 (172.174.48.174 | 10.0.0.7): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-5 (172.174.48.180 | 10.0.0.9): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-6 (172.174.48.182 | 10.0.0.10): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-7 (172.173.245.203 | 10.0.0.14): 7 shards
   longevity-10gb-3h-master-db-node-4e06109c-eastus-8 (172.173.128.49 | 10.0.0.8): 7 shards
Scylla running with shards number (terminated nodes):
   longevity-10gb-3h-master-db-node-4e06109c-eastus-4 (172.174.48.177 | 10.0.0.8): 7 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (azure: ['eu-west-1'])

Test: `longevity-10gb-3h-azure-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b33e6d73bb5f4a409c6935b175285aeacd0ab6fc/test-cases/longevity/longevity-10gb-3h.yaml)

Restore Monitor Stack command: `$ hydra investigate show-monitor 4e06109c-d0d3-455e-9416-5cc6514a0898`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=4e06109c-d0d3-455e-9416-5cc6514a0898)
Show all stored logs command: `$ hydra investigate show-logs 4e06109c-d0d3-455e-9416-5cc6514a0898`

Test id: `4e06109c-d0d3-455e-9416-5cc6514a0898`

Logs:

sct - [https://cloudius-jenkins-test.s3.amazonaws.com/4e06109c-d0d3-455e-9416-5cc6514a0898/20221031_024036/sct-runner-4e06109c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4e06109c-d0d3-455e-9416-5cc6514a0898/20221031_024036/sct-runner-4e06109c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/longevity/job/longevity-10gb-3h-azure-test/20/)

**Comment by fruch** [comment]
This is as designed, we have one event when funding the core and one when we read the content and uploaded it.

Them not having the same id doesn't warrant changing it now, since no code it counting on those IDs (at least for now)
