### ISSUE TITLE
Cassandra-stress may fail if one of the nodes provided in the command parameter is down

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#5380]
## Installation details

Kernel Version: 5.15.0-1021-aws
Scylla version (or git commit hash): `2022.2.0~rc3-20221009.994a5f0fbb4c` with build-id `ad2ce7ef5214afc9f921ccfa2ce00706376f77dc`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-aarch64-package-2022.2.0-rc3.0.20221009.994a5f0fbb4c.tar.gz
Cluster size: 6 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 (52.50.148.84 | 10.4.9.141) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-6 (54.171.57.223 | 10.4.11.178) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-5 (3.250.55.236 | 10.4.8.172) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-4 (34.245.194.44 | 10.4.8.136) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-3 (3.252.72.87 | 10.4.11.197) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-2 (52.30.62.224 | 10.4.11.38) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-9114821e-1 (3.249.40.180 | 10.4.9.97) (shards: 15)

OS / Image: `ami-0dcd7f54f9f910597` (aws: eu-west-1)

Test: `longevity-50gb-3days-arm-test`
Test id: `9114821e-a18b-413a-a3e3-6c3189f19b06`
Test name: `enterprise-2022.2/longevity/longevity-50gb-3days-arm-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1b668169316e7b75f2db649c8df5b8ef1f8f2805/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

**>>>>>>>**
When running NodetoolDecommission nemesis class, we use `nodetool decommission` to bring down a node and add a new node to the cluster. While doing this, our `cassandra-stress` process flagged issues with creating a connection to the added node:

```
2022-11-01 11:15:06.681: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=7018ee0b-ec83-4ca9-b31d-0b5d1b029bb9 duration=20s: node=Node longevity-tls-50gb-3d-2022-2-loader-node-9114821e-3 [63.34.9.128 | 10.4.10.133] (seed: False)
stress_cmd=cassandra-stress read cl=QUORUM duration=4320m -mode cql3 native  -rate threads=50 -pop seq=1..100000000 -log interval=5
errors:
Stress command completed with bad status 1: WARN  11:14:51,597 Error creating netty channel to /10.4.9.141:9042
```

Looking at the node in question, the connection problem happened in between finishing `Scylla Cloud Image Setup Service` and starting the Scylla Server. There is however a 1.5 minute window of no logs and possibly no action being taken. 

```
Nov 01 11:14:12 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[2100]: Created symlink /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
Nov 01 11:14:12 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[2133]: update-initramfs: Generating /boot/initrd.img-5.15.0-1021-aws
Nov 01 11:14:28 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[6681]: Unsupported platform on EFI system, doing nothing.
Nov 01 11:14:28 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[850]: Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
Nov 01 11:14:28 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[841]: Devices: ['/dev/nvme1n1']
Nov 01 11:14:30 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[6778]: Created symlink /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount → /etc/systemd/system/var-lib-systemd-coredump.mount.
Nov 01 11:14:30 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_image_setup[6817]: Removed /etc/systemd/system/timers.target.wants/fstrim.timer.
Nov 01 11:14:31 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 systemd[1]: Finished Scylla Cloud Image Setup service.
Nov 01 11:16:13 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 systemd[1]: Starting Scylla Server...
Nov 01 11:16:15 longevity-tls-50gb-3d-2022-2-db-node-9114821e-7 scylla_prepare[7727]: Saving the original irqbalance configuration is in /etc/default/irqbalance.scylla.orig
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9114821e-a18b-413a-a3e3-6c3189f19b06`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9114821e-a18b-413a-a3e3-6c3189f19b06)
- Show all stored logs command: `$ hydra investigate show-logs 9114821e-a18b-413a-a3e3-6c3189f19b06`

## Logs:
- **db-cluster-9114821e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/db-cluster-9114821e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/db-cluster-9114821e.tar.gz)
- **monitor-set-9114821e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/monitor-set-9114821e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/monitor-set-9114821e.tar.gz)
- **loader-set-9114821e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/loader-set-9114821e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/loader-set-9114821e.tar.gz)
- **sct-runner-9114821e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/sct-runner-9114821e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9114821e-a18b-413a-a3e3-6c3189f19b06/20221101_113210/sct-runner-9114821e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-50gb-3days-arm-test/5/)

**Comment by roydahan** [comment]
Moved the issue to SCT, but I don't understand what is the issue....

**Comment by fruch** [comment]
> Upon further investigation it looks like the issue is not with the time between ScyllaCloudImage service finishes and Scylla Server starts running. The cassandra-stress process failed here because the `NodetoolDecommission` nemesis created a new node in the cluster at the exact time our loaders finished running `preapre` commands and started running the main stress commands. In short: this is an SCT issue.
> @roydahan Are you able to transfer this issue to our SCT repo? Neither I nor Doron have that power.

Java-driver shouldn't be failing to connect if one node isn't available

If cassandra-stress is doing something funky at begining of the stress and assume all nodes are available, we should fix c-s.

**Comment by roydahan** [comment]
> > Upon further investigation it looks like the issue is not with the time between ScyllaCloudImage service finishes and Scylla Server starts running. The cassandra-stress process failed here because the `NodetoolDecommission` nemesis created a new node in the cluster at the exact time our loaders finished running `preapre` commands and started running the main stress commands. In short: this is an SCT issue.
> > @roydahan Are you able to transfer this issue to our SCT repo? Neither I nor Doron have that power.
> 
> Java-driver shouldn't be failing to connect if one node isn't available
> 
> If cassandra-stress is doing something funky at begining of the stress and assume all nodes are available, we should fix c-s.
If that's the issue, I think we already know that and that's why the PR from @ShlomiBalalis to do that is a mistake that should have been reverted.

**Comment by fruch** [comment]
This seems to be a bug in c-s code, I have a fix for it in:
https://github.com/scylladb/scylla-tools-java/pull/314

the sad part it's randomly select one of the host from the command-line, so this can happen any time, picking only one host in the commandline surface other issues for test cases we keep on start cassandra-stress command during the test while nemesis are running (why we included all nodes to the command line)

**Comment by mykaul** [comment]
> This seems to be a bug in c-s code, I have a fix for it in: [scylladb/scylla-tools-java#314](https://github.com/scylladb/scylla-tools-java/pull/314)

If you send a fix to c-s upstream, will they consider it, or is this a no-go?

**Comment by fruch** [comment]
> > This seems to be a bug in c-s code, I have a fix for it in: [scylladb/scylla-tools-java#314](https://github.com/scylladb/scylla-tools-java/pull/314)
> 
> If you send a fix to c-s upstream, will they consider it, or is this a no-go?

in most cases we opened issues and suggested PRs to C-S, we were mostly ignored.
https://github.com/apache/cassandra/pulls?q=is%3Apr+author%3Adkropachev+is%3Aclosed

I can suggest it also on upstream, but wouldn't get my hopes high for getting it merged quickly (or at all).

**Comment by avikivity** [comment]
They do merge fixes.

**Comment by fruch** [comment]
@mykaul @avikivity  

here's a PR for the upstream as well:
https://issues.apache.org/jira/browse/CASSANDRA-18025
https://github.com/apache/cassandra/pull/1989

let's see if they would want care or not.

**Comment by fruch** [comment]
The fix in c-s was merged in master, question do we want it backported or not.
