### ISSUE TITLE
NoCorruptRepair timed out after 32 seconds while attempting to preapre test tables

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#5390]
## Installation details

Kernel Version: 5.15.0-1021-aws
Scylla version (or git commit hash): `2022.2.0~rc3-20221009.994a5f0fbb4c` with build-id `ad2ce7ef5214afc9f921ccfa2ce00706376f77dc`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-aarch64-package-2022.2.0-rc3.0.20221009.994a5f0fbb4c.tar.gz
Cluster size: 6 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-4 (54.74.223.126 | 10.4.8.186) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-2 (34.244.91.86 | 10.4.11.8) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-8 (63.33.59.83 | 10.4.9.36) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-3 (34.244.34.161 | 10.4.11.184) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-5 (34.244.198.144 | 10.4.8.222) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-11 (34.246.185.229 | 10.4.8.69) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-7 (3.252.148.218 | 10.4.11.0) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-14 (54.78.166.116 | 10.4.11.241) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-13 (54.170.39.69 | 10.4.10.62) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-10 (54.74.187.127 | 10.4.9.87) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-17 (54.217.160.162 | 10.4.9.181) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-6 (54.194.155.233 | 10.4.8.125) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-16 (52.18.244.120 | 10.4.10.251) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-9 (54.74.252.233 | 10.4.10.212) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-18 (52.18.223.205 | 10.4.9.228) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-22 (52.17.24.151 | 10.4.9.33) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-12 (34.242.35.121 | 10.4.8.206) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-19 (34.244.170.40 | 10.4.9.23) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-20 (54.170.213.42 | 10.4.11.112) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-25 (54.216.162.126 | 10.4.9.20) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-15 (54.194.158.55 | 10.4.11.5) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-26 (3.249.36.220 | 10.4.11.208) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-1 (34.245.60.47 | 10.4.10.193) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-21 (63.35.178.122 | 10.4.10.136) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-23 (34.245.48.250 | 10.4.8.143) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-24 (34.255.122.210 | 10.4.9.61) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-27 (54.74.231.159 | 10.4.8.21) (shards: 15)
- longevity-tls-50gb-3d-2022-2-db-node-7f685b49-28 (54.77.180.124 | 10.4.11.209) (shards: 15)

OS / Image: `ami-0dcd7f54f9f910597` (aws: eu-west-1)

Test: `longevity-50gb-3days-arm-test`
Test id: `7f685b49-4c05-4d4d-987e-8287694d3a4e`
Test name: `enterprise-2022.2/longevity/longevity-50gb-3days-arm-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1b668169316e7b75f2db649c8df5b8ef1f8f2805/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

**>>>>>>>**
`NoCorruptRepair` nemesis failed due to a timeout after only 32 seconds. Possibly we might want to extend the timeout window or get more retries?:

```
< t:2022-11-06 16:54:29,664 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622332592) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,664 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:common.py       l:1481 c:cassandra.pool       p:DEBUG > Closing connection (139695622329040) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622329040) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:common.py       l:1481 c:cassandra.pool       p:DEBUG > Closing connection (139695622330096) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622330096) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:common.py       l:1481 c:cassandra.pool       p:DEBUG > Closing connection (139695622325584) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622325584) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:common.py       l:1481 c:cassandra.pool       p:DEBUG > Closing connection (139695622335712) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622335712) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,665 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,666 f:common.py       l:1481 c:cassandra.pool       p:DEBUG > Closing connection (139695622325728) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,666 f:libevreactor.py l:287  c:cassandra.io.libevreactor p:DEBUG > Closing connection (139695622325728) to 10.4.8.143:9042
< t:2022-11-06 16:54:29,666 f:libevreactor.py l:291  c:cassandra.io.libevreactor p:DEBUG > Closed socket to 10.4.8.143:9042
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_no_corrupt_repair at 0x7f0dae2ab7f0> < t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <function Nemesis.disrupt_no_corrupt_repair at 0x7f0dae2ab7f0>
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3693, in wrapper
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1418, in disrupt_no_corrupt_repair
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     self._prepare_test_table(ks=f'drop_table_during_repair_ks_{i}', table='standard1')
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1708, in _prepare_test_table
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     ks_cfs = self.cluster.get_non_system_ks_cf_list(db_node=self.target_node)
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3340, in get_non_system_ks_cf_list
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     return self.get_any_ks_cf_list(db_node, filter_out_table_with_counter=filter_out_table_with_counter,
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3402, in get_any_ks_cf_list
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     regular_table_names = execute_cmd(cql_session=session, entity_type="column")
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3366, in execute_cmd
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     fetcher = PageFetcher(execute_result).request_all()
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2256, in __init__
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     self.wait(seconds=30)
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2331, in wait
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR >     raise RuntimeError(error_message('Requested pages were not delivered before timeout'))
< t:2022-11-06 16:54:29,666 f:nemesis.py      l:3703 c:sdcm.nemesis         p:ERROR > RuntimeError: Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
```

```
2022-11-06 16:54:29.667: (DisruptionEvent Severity.ERROR) period_type=end event_id=90bb53e3-344e-4dbf-973c-14aecbc0bec7 duration=32s: nemesis_name=NoCorruptRepair target_node=Node longevity-tls-50gb-3d-2022-2-db-node-7f685b49-23 [34.245.48.250 | 10.4.8.143] (seed: False) errors=Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7f685b49-4c05-4d4d-987e-8287694d3a4e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7f685b49-4c05-4d4d-987e-8287694d3a4e)
- Show all stored logs command: `$ hydra investigate show-logs 7f685b49-4c05-4d4d-987e-8287694d3a4e`

## Logs:
- **db-cluster-7f685b49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/db-cluster-7f685b49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/db-cluster-7f685b49.tar.gz)
- **monitor-set-7f685b49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/monitor-set-7f685b49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/monitor-set-7f685b49.tar.gz)
- **loader-set-7f685b49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/loader-set-7f685b49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/loader-set-7f685b49.tar.gz)
- **normal-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/normal-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/normal-7f685b49.log.tar.gz)
- **summary-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/summary-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/summary-7f685b49.log.tar.gz)
- **events-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/events-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/events-7f685b49.log.tar.gz)
- **output-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/output-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/output-7f685b49.log.tar.gz)
- **debug-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/debug-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/debug-7f685b49.log.tar.gz)
- **sct-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/sct-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/sct-7f685b49.log.tar.gz)
- **error-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/error-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/error-7f685b49.log.tar.gz)
- **critical-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/critical-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/critical-7f685b49.log.tar.gz)
- **raw_events-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/raw_events-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/raw_events-7f685b49.log.tar.gz)
- **warning-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/warning-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/warning-7f685b49.log.tar.gz)
- **email_data-7f685b49.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/email_data-7f685b49.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/email_data-7f685b49.json.tar.gz)
- **argus-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/argus-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/argus-7f685b49.log.tar.gz)
- **left_processes-7f685b49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/left_processes-7f685b49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f685b49-4c05-4d4d-987e-8287694d3a4e/20221107_123159/left_processes-7f685b49.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-50gb-3days-arm-test/6/)

**Comment by fruch** [comment]
This is select from system table l, you are not supposed to have that many data in this table that is should be that slow.

What's that node cpu metrics say, it's that busy ? (Maybe the load is too heavy for that machines)

We rarely see this cal failing on timeouts, I don't think we should increase the timeouts blindly without understanding the reason.

**Comment by fgelcer** [comment]
seems like a dup of https://github.com/scylladb/scylladb/issues/11964

@KnifeyMoloko , please provide any information you may have in addition to what is already reported in there (and here)

**Comment by KnifeyMoloko** [comment]
Closing as dupe of https://github.com/scylladb/scylladb/issues/11964 (and as Yaron mentioned there, we don't see this crop up after RC4)
