### ISSUE TITLE
Retying of _add_and_init_new_cluster_node cause the problems during nemesis terminate_and_replace_nemesis

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5415]
Function`sdcm.nemesis.Nemesis._add_and_init_new_cluster_node` runs with retying decorator:
```
 @retrying(n=3, sleep_time=60, allowed_exceptions=(NodeSetupFailed, NodeSetupTimeout))
    def _add_and_init_new_cluster_node(self, old_node_ip=None, timeout=MAX_TIME_WAIT_FOR_NEW_NODE_UP, rack=0):
```

It may cause to the problem during nemesis `terminate_and_replace_nemesis`.
In the test below this nemesis was triggered 3 times. 
Every run new added node (_node1_) replaced the terminated node, but initialization took more then 6 hours (it's default timeout for a node up) and NodeSetup timeout is raised. When it happens, we remove this new node from our cluster object:
```
        except (NodeSetupFailed, NodeSetupTimeout):
            self.log.warning("TestConfig of the '%s' failed, removing it from list of nodes" % new_node)
            self.cluster.nodes.remove(new_node)
            self.log.warning("Node will not be terminated. Please terminate manually!!!")
            raise
```
But node initialization was completed  later (after 6 hours) and this node in appear in Scylla cluster. This is `nodetool status` output, where `10.4.1.114` is new added node:
```
< t:2022-11-12 11:13:44,612 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.4.0.64   1.04 TB    256          ?       62acdcac-49fb-4268-8abe-19fc912a8fc3  1a
UN  10.4.1.114  940.83 GB  256          ?       6c3dfcc3-4824-4d59-831f-d7bba9c622d3  1a
UN  10.4.2.34   1 TB       256          ?       ac5bbd2c-3c1c-4393-a652-410ddf0b0e41  1a
UN  10.4.0.93   1021.63 GB  256          ?       43c0f7df-8051-4dde-9ed8-21db0ebc2890  1a
```

But from SCT point of view new node setup failed and we start adding one more node (_node2_). _node2_ failed to startup because try to replace terminated node that already was replaced and not in the cluster. 
Due to _node2_ failure 3th node is adding (_node3_) and also fails with same error as _node2_.
As result we have 2 "zombie" nodes for each running of this nemesis.

Another problem that _node1_ does not report to prometheus and we have no statistics. On graphana dashboard we see less nodes then in the cluster
![Screenshot from 2022-11-14 17-46-31](https://user-images.githubusercontent.com/34435448/201704427-e55fa9e6-1161-408c-8c15-89951f7f3ac7.png)

Looks like the cluster has 1 node only but it's wrong.

**How we can solve the problem, few suggestions**:

1. Maybe we need to remove retrying and fail the test if "add and init node" fails with timeout.
If I remember correctly Bentsi added it because he wanted to keep nodes amount and continue to run the test

2. Another possibility - improve node setup/startup analyzing. I mean to recognize what happened there: 

- check if startup/bootstrap etc continue to run without errors and reached timeout (6h). In this case we can wait for Scylla initialization finish and report error with details - how long it took - and fail nemesis. In this case we get appropriate problem description, won't create surplus nodes and test will continue.
- find startup error and report about this. In this case we can create additional node to keep a cluster with correct number of nodes. And report about real error, not just "SetupFailure". In this case we won't need to search for the error manually.
- add to cluster health checker validation of nodes in the cluster against nodes in SCT cluster object. In the test described above nodes in the Scylla cluster != nodes in SCT cluster object

## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `2022.2.0~rc4-20221106.f5714e0db12f` with build-id `f4a927b8a00fbcd8d48640835192aeaa7968b1f2`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-9 (52.212.112.192 | 10.4.0.51) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-8 (3.251.79.14 | 10.4.2.113) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-7 (34.245.56.196 | 10.4.2.70) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-6 (18.202.219.69 | 10.4.1.114) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-5 (34.246.250.177 | 10.4.0.93) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-4 (3.252.162.201 | 10.4.0.64) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-3 (34.251.128.103 | 10.4.0.21) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-2 (52.19.215.161 | 10.4.3.148) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-14 (34.244.94.253 | 10.4.1.186) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-13 (52.215.53.82 | 10.4.3.200) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-12 (34.245.124.255 | 10.4.2.48) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-11 (34.246.193.25 | 10.4.0.111) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-10 (34.244.150.185 | 10.4.0.137) (shards: 14)
- longevity-tls-1tb-7d-2022-2-db-node-c159e20e-1 (54.74.4.53 | 10.4.2.34) (shards: 14)

OS / Image: `ami-00253925d2028dcef` (aws: eu-west-1)

Test: `ics-longevity-1tb-7days-test`
Test id: `c159e20e-0347-4563-9ad5-5113f5867513`
Test name: `enterprise-2022.2/SCT_Enterprise_Features/ICS/ics-longevity-1tb-7days-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/519e3909374cd87064c140c4badb2acc05805682/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor c159e20e-0347-4563-9ad5-5113f5867513`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c159e20e-0347-4563-9ad5-5113f5867513)
- Show all stored logs command: `$ hydra investigate show-logs c159e20e-0347-4563-9ad5-5113f5867513`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-1tb-7days-test/5/)

**Comment by juliayakovlev** [comment]
@fruch @fgelcer @roydahan for your decision

**Comment by fruch** [comment]
The retry is mainly for guarding us from cloud service related issues

Since it's now covering a big portion of other actions tucked into it, and include the waiting for node to become available, it's beating the idea a bit.

I think we should do two things:

1. refactor the code a bit that we can control the retries, and for this specific nemesis don't retry. (Cause of replace address, it probably won't ever work, of we got to scylla start once)

2. For a long run solution, we should split the add_node boot sequence into 2: creating/provision the resources, and the boot of scylla.
And then we could retry only the provisioning part

**Comment by fgelcer** [comment]
> I think we should do two things:
> 
> 1. refactor the code a bit that we can control the retries, and for this specific nemesis don't retry. (Cause of replace address, it probably won't ever work, of we got to scylla start once)

in addition to it, for now, until there is a decision if initialization taking more than 6 hours is ok, or not, we can increase this wait timeout (this is the biggest dataset we have, so probably 8 hours timeout would do it)

> 2. For a long run solution, we should split the add_node boot sequence into 2: creating/provision the resources, and the boot of scylla.
>    And then we could retry only the provisioning part

i think that was part of the plan, when we started working on the unified provision refactor, but we didn't get even close to start refactoring AWS backend...

**Comment by fruch** [comment]
> > I think we should do two things:
> > 
> > 1. refactor the code a bit that we can control the retries, and for this specific nemesis don't retry. (Cause of replace address, it probably won't ever work, of we got to scylla start once)
> 
> in addition to it, for now, until there is a decision if initialization taking more than 6 hours is ok, or not, we can increase this wait timeout (this is the biggest dataset we have, so probably 8 hours timeout would do it)
> 
> > 2. For a long run solution, we should split the add_node boot sequence into 2: creating/provision the resources, and the boot of scylla.
> >    And then we could retry only the provisioning part
> 
> i think that was part of the plan, when we started working on the unified provision refactor, but we didn't get even close to start refactoring AWS backend...

we do have provision code for AWS, but we never got to using that provision code instead of the old cluster based creation, code, i.e. the dynamic creation and provision code are separated.

**Comment by fruch** [comment]
> No refactor should be done here. We should just check if the replacement is still in progress instead of waiting without checking anything. If the replacement failed, we should retry, like a user would retry and this should work.

well in this case the replace is taking a long time, and we consider it as failed. but it's actually succeeded but reshaping is taking lots of time.
we don't expect the user to start doing a replacement (i.e. with the same address) while the process is running.

the refactoring I was talking about, is just the ability to passdown to this function if we want retries or not.
and in replace_address case, I just argue we don't want retries

**Comment by juliayakovlev** [comment]
> > No refactor should be done here. We should just check if the replacement is still in progress instead of waiting without checking anything. If the replacement failed, we should retry, like a user would retry and this should work.
> 
> well in this case the replace is taking a long time, and we consider it as failed. but it's actually succeeded but reshaping is taking lots of time. we don't expect the user to start doing a replacement (i.e. with the same address) while the process is running.

I described what happened during replacment here https://github.com/scylladb/scylladb/issues/11960.
Reshaping was long, yes, about 4h. But I see that after firmware update almost 1 hour nothing happens and just after 1 hour started reshaping:
```
Nov 12 05:23:00 longevity-tls-1tb-7d-2022-2-db-node-c159e20e-6 fwupdmgr[10075]: Successfully downloaded new metadata: 0 local devices supported
###### nothing happens here #############
Nov 12 06:21:18 longevity-tls-1tb-7d-2022-2-db-node-c159e20e-6 scylla[7825]:  [shard 10] compaction_manager - Starting off-strategy compaction for keyspace1.standard1, 704 candidates were found
```



> 
> the refactoring I was talking about, is just the ability to passdown to this function if we want retries or not. and in replace_address case, I just argue we don't want retries

**Comment by roydahan** [comment]
I think that instead of 1 big timeout, we should wait for replacement (with x timeout) and then wait for reshaping with y timeout).
If this is the actual behaviour that should happen.

**Comment by fruch** [comment]
> I think that instead of 1 big timeout, we should wait for replacement (with x timeout) and then wait for reshaping with y timeout). If this is the actual behaviour that should happen.

that quite a refactoring, since we just spin scylla up, and wait for CQL port to be open.
we don't have it waiting for log lines (like we do in dtest)

**Comment by fruch** [comment]
retry was removed from this action long time ago

it was removed in  f0012377951543de7e0d3ac3f739adda5da236b0

since it's inside nemesis, that nemesis would just fail, and would get triage and hopefully fixed
