### ISSUE TITLE
multi-keyspaces-60h: sct runner running out of disk space

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5428]
## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `5.1.0~rc4-20221106.0295d0c5c81d` with build-id `2e4327c4a7b39d7c4b64e75e8fdb23c73db11a1e`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/scylla-x86_64-package-5.1.0-rc4.0.20221106.0295d0c5c81d.tar.gz
Cluster size: 6 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-6 (3.222.215.135 | 10.12.3.238) (shards: 30)
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-5 (44.204.215.9 | 10.12.3.45) (shards: 30)
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-4 (3.80.11.205 | 10.12.0.20) (shards: 30)
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-3 (44.211.232.111 | 10.12.0.62) (shards: 30)
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-2 (18.234.98.77 | 10.12.2.179) (shards: 30)
- longevity-1000-keyspaces-5-1-enla-db-node-817eba41-1 (3.94.149.5 | 10.12.0.68) (shards: 30)

OS / Image: `ami-06d91ed374bbb1069` (aws: us-east-1)

Test: `longevity-multi-keyspaces-60h-test`
Test id: `817eba41-3b48-408f-a9bc-8335506bed7b`
Test name: `scylla-5.1/longevity/longevity-multi-keyspaces-60h-test`
Test config file(s):

- [longevity-multi-keyspaces.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/efeadfdfd5da2c129830dbb900c6f208d6862c9b/test-cases/longevity/longevity-multi-keyspaces.yaml)

## Issue description

clean resources step failed with:
```
Failed to write auth token to file "/home/ubuntu/.google_libcloud_auth.sct-project-1": [Errno 28] No space left on device
...
```

and collect resources as well:
```
[2022-11-16T00:07:06.379Z] Going to run './sct.py  send-email --test-status ABORTED --start-time 1668337247 --runner-ip 3.235.248.100 --email-recipients qa@scylladb.com'...

[2022-11-16T00:07:07.062Z] docker: Error response from daemon: mkdir /var/lib/docker/overlay2/cd8c5baaf55aa87d4c0e16b3aecf0209298555b75903d22fde74eaa56f1c3b3c-init: no space left on device.
```

since this test is only 60h, it under the heuristics of 3days we have to enlarge the root disk from default 80Gb to 120Gb

- Restore Monitor Stack command: `$ hydra investigate show-monitor 817eba41-3b48-408f-a9bc-8335506bed7b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=817eba41-3b48-408f-a9bc-8335506bed7b)
- Show all stored logs command: `$ hydra investigate show-logs 817eba41-3b48-408f-a9bc-8335506bed7b`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/longevity/job/longevity-multi-keyspaces-60h-test/4/)

**Comment by roydahan** [comment]
It brings us back to the old discussion of customizing the sct-runner per test, right?
Can we add the the parameter of the sct-runner root disk to be part of the pipeline?

**Comment by fruch** [comment]
> It brings us back to the old discussion of customizing the sct-runner per test, right?
> Can we add the the parameter of the sct-runner root disk to be part of the pipeline?

yes we can.

with a little bit more effort I think we can read it from test configuration.
