### ISSUE TITLE
Gemini is not started in upgrade test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5449]
In upgrade test on 2022.1 branch we can see error `'is_metric_has_data': failed with 'AssertionError('No results from Prometheus')'`
After investigation I found out that Gemini is not started at all.

Possibly issue was introduced in https://github.com/scylladb/scylla-cluster-tests/commit/e6ad89cea6ae2da3daa7dbeb23115f7658d5e04a
where `self.gemini_cmd.strip()` was replaced with `self.stress_cmd.strip()` making creation c-s stress instead of gemini (but I'm not sure).

test details:

## Installation details

Kernel Version: 5.15.0-1021-aws
Scylla version (or git commit hash): `5.0.5-20221009.5a97a1060` with build-id `5009658b834aaf68970135bfc84f964b66ea4dee`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-27ec68d5-4 (54.229.189.212 | 10.0.3.104) (shards: 8)
- rolling-upgrade--centos-db-node-27ec68d5-3 (54.170.179.167 | 10.0.3.153) (shards: 8)
- rolling-upgrade--centos-db-node-27ec68d5-2 (54.246.199.37 | 10.0.3.226) (shards: 8)
- rolling-upgrade--centos-db-node-27ec68d5-1 (34.244.208.152 | 10.0.3.231) (shards: 8)

OS / Image: `ami-0ba7328a376f6a3ef` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`
Test id: `27ec68d5-f6b1-40c4-8a0d-c57c6f003c85`
Test name: `enterprise-2022.1/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1c008a414b7159b03ef2969aa1208103ecead0ba/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 27ec68d5-f6b1-40c4-8a0d-c57c6f003c85`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=27ec68d5-f6b1-40c4-8a0d-c57c6f003c85)
- Show all stored logs command: `$ hydra investigate show-logs 27ec68d5-f6b1-40c4-8a0d-c57c6f003c85`

## Logs:
- **db-cluster-27ec68d5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/db-cluster-27ec68d5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/db-cluster-27ec68d5.tar.gz)
- **monitor-set-27ec68d5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/monitor-set-27ec68d5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/monitor-set-27ec68d5.tar.gz)
- **loader-set-27ec68d5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/loader-set-27ec68d5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/loader-set-27ec68d5.tar.gz)
- **sct-runner-27ec68d5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/sct-runner-27ec68d5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/27ec68d5-f6b1-40c4-8a0d-c57c6f003c85/20221119_071917/sct-runner-27ec68d5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/35/)

**Comment by soyacz** [comment]
@aleksbykov can you look if your commit could break it and prepare a fix?

**Comment by fruch** [comment]
> @aleksbykov can you look if your commit could break it and prepare a fix?

I tried fixing yesterday, but seem I didn't pushed it 

stress_cmd needs to be replaced with gemini_cmd

**Comment by fruch** [comment]
I think this would fix the issue:
https://github.com/scylladb/scylla-cluster-tests/commit/9425f567a231f303a120925a059bcafcb6572008

**Comment by fruch** [comment]
let's track:
https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/38/

and if it's passes this point, we can close this one

**Comment by fruch** [comment]
> let's track: https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/38/
> 
> and if it's passes this point, we can close this one

Looks like it wasn't enough:
```
2022-11-22 15:27:52.901: (GeminiStressEvent Severity.ERROR) period_type=end event_id=684e5f11-c3bf-4c1d-b5da-784074f92bbd duration=2s: node=Node rolling-upgrade--debian-buster-loader-node-60ab48b4-0-1 [34.148.45.137 | 10.142.0.77] (seed: False) gemini_cmd=gemini -d --duration 2h -c 10 -m write -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --table-options "cdc={'enabled': true}" --test-username cassandra --test-password cassandra --test-cluster=10.142.0.39,10.142.0.53,10.142.0.8,10.142.0.67 --outfile /home/scylla-test/gemini_result_5ac7fd7b-508d-422e-8c0a-15b7cf5faf3a.log --seed 66 --request-timeout 180s --connect-timeout 120s
result=Exit code: 127
errors=['Command error: bash: gemini: command not found\n\n']
```

**Comment by fruch** [comment]
I think we should revert

**Comment by fruch** [comment]
trying it again:
https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/40/

**Comment by aleksbykov** [comment]
@fruch i think problem is that gemini should be executed `./gemini` or `~/gemini

**Comment by fruch** [comment]
yeah few backport regarding gemini pulled some things from master they shouldn't have

looks like run 
https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/41/

is now working
