### ISSUE TITLE
[k8] MemoryStress nemesis fails to install stress-ng

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5455]
MemoryStress stress nemesis trying to install with snap that doesn't work on scylla docker

```
(DisruptionEvent Severity.ERROR) period_type=end event_id=75af9b75-7e3e-4a09-b1d6-1b888e764bbb duration=10s: nemesis_name=MemoryStress target_node=Node sct-cluster-2-us-east1-b-us-east1-2 [10.0.3.245 | 10.0.1.54] (seed: False) errors=Encountered a bad command exit code!

Command: 'snap install stress-ng'

Exit code: 1

Stdout:



Stderr:

error: cannot communicate with server: Post "http://localhost/v2/snaps/stress-ng": dial unix /run/snapd.socket: connect: no such file or directory
```

@vponomaryov have you seen this ?

maybe we should consider using some other means like
https://chaos-mesh.org/blog/how-to-efficiently-stress-test-pod-memory/

**Comment by vponomaryov** [comment]
> @vponomaryov have you seen this ?
No, I haven't.

And how should it be reproduced?

**Comment by fruch** [comment]
> > @vponomaryov have you seen this ?
> 
> No, I haven't.
> 
> And how should it be reproduced?

according to the dashboard:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/b997de2089a8bcea7889c78b9ac79123

running with any scylla image bigger then 5.0, it would break (I'm guessing the image changed a bit, and some stuff was removed)

**Comment by fruch** [comment]
we probably just need to replace it with using https://chaos-mesh.org/, it has the same capability, without messing around with the software of the image under test.
