### ISSUE TITLE
[ks8] multiteant show-monitor doesn't show corret name in the title

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5458]
we have 14 clusters in this one:
```
hydra investigate show-monitor abfc4334-0a6c-493f-94d9-48547e55af41
```

they all start up fine, but in all of them it say it's cluster 14 (i.e. the last one),

since it's a template, we might need to change it a bit for each one before uploading the dashboards

**Comment by juliayakovlev** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5612
