### ISSUE TITLE
Failure to fetch image from dockerhub

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5464]
getting this error:
```
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```

- [x] Need to think if we could put a retry on this specific `docker run` command
- [x] need to check why we didn't pull/cache it before (probably since it not set in the configuration)

## Installation details

Kernel Version: 5.15.0-1023-aws
Scylla version (or git commit hash): `5.2.0~dev-20221118.a396c27efccd` with build-id `74a707956a4aba54865b70d78b830b666f5f19f7`

Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-maste-oracle-db-node-327d8526-1 (3.250.107.231 | 10.4.1.191) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-327d8526-4 (34.246.134.27 | 10.4.3.165) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-327d8526-3 (18.203.221.38 | 10.4.2.33) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-327d8526-2 (54.77.43.53 | 10.4.3.123) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-327d8526-1 (34.250.197.116 | 10.4.2.117) (shards: 2)

OS / Image: `ami-053575527ef28ce64` (aws: eu-west-1)

Test: `gemini-3h-with-nemesis-test`
Test id: `327d8526-d993-481d-afa7-069a74e364de`
Test name: `scylla-master/gemini-/gemini-3h-with-nemesis-test`
Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f31573efeb1cbd00bb3c321995dbcc8c428df4f2/test-cases/gemini/gemini-3h-with-nemesis.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 327d8526-d993-481d-afa7-069a74e364de`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=327d8526-d993-481d-afa7-069a74e364de)
- Show all stored logs command: `$ hydra investigate show-logs 327d8526-d993-481d-afa7-069a74e364de`

## Logs:
- **db-cluster-327d8526.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/db-cluster-327d8526.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/db-cluster-327d8526.tar.gz)
- **monitor-set-327d8526.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/monitor-set-327d8526.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/monitor-set-327d8526.tar.gz)
- **loader-set-327d8526.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/loader-set-327d8526.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/loader-set-327d8526.tar.gz)
- **sct-runner-327d8526.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/sct-runner-327d8526.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/sct-runner-327d8526.tar.gz)
- **parallel-timelines-report-327d8526.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/parallel-timelines-report-327d8526.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327d8526-d993-481d-afa7-069a74e364de/20221120_081314/parallel-timelines-report-327d8526.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis-test/344/)

**Comment by roydahan** [comment]
Do we have retries there?

**Comment by mykaul** [comment]
We better also publish to quay.io and just try there. If for some reason you can't pull from docker.io, which can be due to number of reasons, you'll have a completely separate container registry that may be able to satisfy the requirement.

**Comment by mykaul** [comment]
Another alternative might be https://gallery.ecr.aws/

**Comment by mykaul** [comment]
> > Do we have retries there?
> 
> No we don't
> 
> > We better also publish to quay.io and just try there. If for some reason you can't pull from docker.io, which can be due to number of reasons, you'll have a completely separate container registry that may be able to satisfy the requirement.
> 
> we'll need scylla docker images upload there as well.
> 
> BTW we are pull lots of images for the k8s jobs, and k8s has it's own retrying, I don't remember having any issues with dockerhub

According to https://status.docker.com/ , they have 100% uptime... But they do and did have incidents of partial availability in the past.
