### ISSUE TITLE
spot termination during setUp, fails test from being reported

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5465]
Getting spot termination during setUp (it's longer cause of node perf tests), breaking reporting, since tearDown isn't being called

```
sdcm.sct_events.events_analyzer.TestFailure: Got critical event: (SpotTerminationEvent Severity.CRITICAL) period_type=one-time event_id=7a157497-1405-4850-bb6f-fb4a47516415: node=Node longevity-10gb-3h-master-db-node-060abe87-0-4 [34.75.146.77 | 10.142.0.69] (seed: False) message=Instance was preempted.
```

## Installation details

Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-060abe87-0-6 (35.231.8.221 | 10.142.0.78) (shards: -1)
- longevity-10gb-3h-master-db-node-060abe87-0-5 (34.148.94.4 | 10.142.0.77) (shards: -1)
- longevity-10gb-3h-master-db-node-060abe87-0-4 (34.75.146.77 | 10.142.0.69) (shards: -1)
- longevity-10gb-3h-master-db-node-060abe87-0-3 (34.23.71.50 | 10.142.0.66) (shards: -1)
- longevity-10gb-3h-master-db-node-060abe87-0-2 (34.148.239.150 | 10.142.0.65) (shards: -1)
- longevity-10gb-3h-master-db-node-060abe87-0-1 (34.75.220.230 | 10.142.0.64) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/1097659074127234974` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `060abe87-0f09-4b17-86cf-33caf5b18b8b`
Test name: `scylla-master/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/259bd1fded9fc617ccce00342bd5c9b8533727f5/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 060abe87-0f09-4b17-86cf-33caf5b18b8b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=060abe87-0f09-4b17-86cf-33caf5b18b8b)
- Show all stored logs command: `$ hydra investigate show-logs 060abe87-0f09-4b17-86cf-33caf5b18b8b`

## Logs:
- **db-cluster-060abe87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/db-cluster-060abe87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/db-cluster-060abe87.tar.gz)
- **monitor-set-060abe87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/monitor-set-060abe87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/monitor-set-060abe87.tar.gz)
- **loader-set-060abe87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/loader-set-060abe87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/loader-set-060abe87.tar.gz)
- **sct-runner-060abe87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/sct-runner-060abe87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/sct-runner-060abe87.tar.gz)
- **parallel-timelines-report-060abe87.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/parallel-timelines-report-060abe87.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/060abe87-0f09-4b17-86cf-33caf5b18b8b/20221121_093357/parallel-timelines-report-060abe87.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/284/)

**Comment by grzywin** [comment]
This error is randomly occuring while running for example some longevity-scylla-operator-3h-gke tests: 
https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke-test/33/consoleFull

**Comment by fruch** [comment]
> This error is randomly occuring while running for example some longevity-scylla-operator-3h-gke tests: 
> https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke-test/33/consoleFull

Why running those jobs with spots ?

**Comment by grzywin** [comment]
I was recently generating quite huge costs so to reduce it I was mixing my test runs with "spot" and "on-demand" instances.
So I shouldn't use spot for anything that runs for such a long time? Raya told me today that the rule of thumb is that "spots" are for runs which takes less than an hour, are they?

**Comment by fruch** [comment]
> I was recently generating quite huge costs so to reduce it I was mixing my test runs with "spot" and "on-demand" instances. So I shouldn't use spot for anything that runs for such a long time? Raya told me today that the rule of thumb is that "spots" are for runs which takes less than an hour, are they?

spot should be used if a job is short and getting triggered multiple times a day.
the job you referred to is something that was running once a week, in less something has changed, and in that case I won't recommend using spots.

regardless we don't have lots of mileage with spots + k8s setups, I'm not even sure what would be spot and what wouldn't be.
(i'm guess it's the monitor instance in your case)

**Comment by fruch** [comment]
@grzywin you cases the teardown is called, and every single information is reported to argus, it's not the same the the reported here.

anyhow what's reported here doesn't happen anymore.

the issue in this report isn't the sport termination.
