### ISSUE TITLE
gemini thread failing on timeout after test is done

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#5469]
## Installation details

Kernel Version: 5.15.0-1023-aws
Scylla version (or git commit hash): `2022.2.0~rc5-20221121.feb292600fc4` with build-id `172f9538efb0893c97c86cdf05622925159f4fa2`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2022-11-21T19:14:35Z/scylla-enterprise-x86_64-package.tar.gz
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-2022--oracle-db-node-a7a4b6fe-1 (44.204.243.217 | 10.12.0.129) (shards: 2)
- gemini-with-nemesis-3h-normal-2022--db-node-a7a4b6fe-4 (34.205.166.140 | 10.12.3.66) (shards: 2)
- gemini-with-nemesis-3h-normal-2022--db-node-a7a4b6fe-3 (3.235.151.15 | 10.12.2.199) (shards: 2)
- gemini-with-nemesis-3h-normal-2022--db-node-a7a4b6fe-2 (3.210.200.195 | 10.12.2.131) (shards: 2)
- gemini-with-nemesis-3h-normal-2022--db-node-a7a4b6fe-1 (44.204.100.57 | 10.12.0.147) (shards: 2)

OS / Image: `ami-09f28ba8061802c24` (aws: us-east-1)

Test: `gemini-3h-with-nemesis-test`
Test id: `a7a4b6fe-d151-402a-b67e-6ed933e57a7c`
Test name: `enterprise-2022.2/gemini-/gemini-3h-with-nemesis-test`
Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/40fc566526b3ae06c90d717a12c5b1f11708d103/test-cases/gemini/gemini-3h-with-nemesis.yaml)

## Issue description

**>>>>>>>**

```
2022-11-23 17:31:51.380: (InfoEvent Severity.NORMAL) period_type=not-set event_id=eed5764b-c631-4a70-9470-157ce1a5d838: message=TEST_END
2022-11-23 18:21:29.160: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=5ef0659a-7d0d-4ce3-abef-f3b8a862d6df, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 64, in test_load_random_with_nemesis
    self.gemini_results.update(self.verify_gemini_results(queue=gemini_thread))
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1958, in verify_gemini_results
    results = queue.get_gemini_results()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/gemini_thread.py", line 145, in get_gemini_results
    raw_results = self.get_results()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 344, in get_results
    for future in concurrent.futures.as_completed(self.results_futures, timeout=timeout):
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 241, in as_completed
    raise TimeoutError(
concurrent.futures._base.TimeoutError: 1 (of 1) futures unfinished
```

we can see that, the GeminiStress didn't end cleanly:
```
$ grep GeminiStressEvent events.log 
2022-11-23 13:19:56.962: (GeminiStressEvent Severity.NORMAL) period_type=begin event_id=664a88fe-eda3-42d5-bb07-9e5348ed886f: node=Node gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 [44.211.231.12 | 10.12.3.4] (seed: False) gemini_cmd=gemini -d --duration 3h --warmup 30m -c 50 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.12.0.147,10.12.2.131,10.12.2.199 --outfile /gemini/gemini_result_c92addd3-32de-498a-a468-97b2821f0690.log --seed 26 --request-timeout 180s --connect-timeout 120s --oracle-cluster=10.12.0.129
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a7a4b6fe-d151-402a-b67e-6ed933e57a7c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a7a4b6fe-d151-402a-b67e-6ed933e57a7c)
- Show all stored logs command: `$ hydra investigate show-logs a7a4b6fe-d151-402a-b67e-6ed933e57a7c`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/gemini-/job/gemini-3h-with-nemesis-test/12/)

**Comment by fgelcer** [comment]
i can see the stress took 3.5 hours (the timeout is defined to be 3h, and 30 min warm up):
```
{"L":"INFO","T":"2022-11-23T13:20:02.907Z","N":"generator","M":"starting partition key generation loop"}
{"L":"INFO","T":"2022-11-23T16:50:05.830Z","N":"pump","M":"Test run stopped. Exiting."}
{"L":"INFO","T":"2022-11-23T16:50:03.381Z","M":"Test run completed. Exiting."}
```

**Comment by fgelcer** [comment]
about the time the thread ended, i can see many messages related to metric reads, but i'm not sure where it is coming from:
```
Nov 23 16:51:45 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `memory' plugin took 11.007 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:51:45 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `disk' plugin took 10.575 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:02 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `df' plugin took 16.376 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:02 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `memory' plugin took 15.771 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:03 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `disk' plugin took 16.681 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:03 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: uc_update: Value too old: name = gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1/disk-nvme0n1p1/disk_time; value time = 1669222323.052; last cache update = 1669222323.052;
Nov 23 16:52:17 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `interface' plugin took 11.417 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:38 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `load' plugin took 12.477 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:39 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `processes' plugin took 13.555 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
Nov 23 16:52:39 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: plugin_read_thread: read-function of the `cpu' plugin took 13.557 seconds, which is above its read interval (10.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
```

what took my attention is:
```
Nov 23 16:52:03 gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1 collectd[4583]: uc_update: Value too old: name = gemini-with-nemesis-3h-normal-2022--loader-node-a7a4b6fe-1/disk-nvme0n1p1/disk_time; value time = 1669222323.052; last cache update = 1669222323.052;
```

**Comment by fruch** [comment]
seem like backup is still ongoing there

but seem like the process of gemini thread is stuck, and timeout.

I've seen this in the stdout:
```
Failed to close channel due to the following error:
```

seems like something failed the connection, and it's not clear what exactly

**Comment by fgelcer** [comment]
i think we are having something very similar for master (but the job is much longer, so perhaps the thread exited without error?):


## Installation details

Kernel Version: 5.15.0-1023-aws
Scylla version (or git commit hash): `5.2.0~dev-20221117.d85f73147821` with build-id `d9aaf343e7cbced97ce3bfd76b219cceff4d6cce`

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-6c29afba-1 (54.221.181.13 | 10.12.8.160) (shards: 62)
- gemini-1tb-10h-master-db-node-6c29afba-3 (54.91.217.61 | 10.12.11.148) (shards: 14)
- gemini-1tb-10h-master-db-node-6c29afba-2 (54.91.37.253 | 10.12.11.22) (shards: 14)
- gemini-1tb-10h-master-db-node-6c29afba-1 (54.196.10.163 | 10.12.11.86) (shards: 14)


OS / Image: `ami-04e57660a094884ef` (aws: us-east-1)

Test: `gemini-1tb-10h`
Test id: `6c29afba-574e-4726-83fb-0263f0d4b200`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f31573efeb1cbd00bb3c321995dbcc8c428df4f2/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

**>>>>>>>**

2022-11-18 07:46:19.841: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=e95371e6-3f4f-4bee-a297-afc8a6e4557c during_nemesis=MgmtBackup, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: []

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 6c29afba-574e-4726-83fb-0263f0d4b200`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6c29afba-574e-4726-83fb-0263f0d4b200)
- Show all stored logs command: `$ hydra investigate show-logs 6c29afba-574e-4726-83fb-0263f0d4b200`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/188/)

**Comment by fruch** [comment]
looks like in those case on master, we timeout on the connection to the loader, and then fail.
