### ISSUE TITLE
FullscanThread producing incorrect CQL commands

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5474]
Seem like since recent merge of refactoring of FullscanThread, 

it's keep generating broken CQL commands, like the following:
```
< t:2022-11-23 20:51:27,501 f:common.py       l:1474 c:utils                p:DEBUG > Executing CQL 'SELECT count(*) FROM keyspace1.standard1 300s BYPASS CACHE' ...
< t:2022-11-23 20:51:27,521 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-11-23 20:51:27.518: (FullScanAggregateEvent Severity.ERROR) period_type=end event_id=
0fec7694-0d94-4f20-adf9-1b2d5b834546 duration=0s node=longevity-10gb-3h-master-db-node-47a594ac-0-2select_from=keyspace1.standard1 message=<Error from server: code=2000 [Syntax error
in CQL query] message="line 1:41  : syntax error...
```

seem like it's adding the timeout straight like thay, without it's proper TIMEOUT keyword

*Installation details*
Kernel version: `5.15.0-1022-gcp`
Scylla version (or git commit hash): `5.2.0~dev-0.20221123.aec9faddb121 with build-id 8b8e9d0783d82c1ed54993071de2f8d13747d25e`
Cluster size: 6 nodes (n1-highmem-16)
Scylla running with shards number (live nodes):
   longevity-10gb-3h-master-db-node-47a594ac-0-1 (35.196.162.165 | 10.142.0.54): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-3 (35.196.22.244 | 10.142.0.64): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-4 (35.231.54.2 | 10.142.0.65): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-5 (35.231.49.10 | 10.142.0.66): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-7 (34.74.154.37 | 10.142.0.83): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-8 (34.23.27.5 | 10.142.0.92): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-10gb-3h-master-db-node-47a594ac-0-2 (35.227.73.253 | 10.142.0.55): 14 shards
   longevity-10gb-3h-master-db-node-47a594ac-0-6 (34.74.144.166 | 10.142.0.67): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: ['eu-west-1'])

Test: `longevity-10gb-3h-gce-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b3063064309a7a357170760e602a30c86629deae/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 47a594ac-0662-42a0-b242-7167df9a5265`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=47a594ac-0662-42a0-b242-7167df9a5265)
Show all stored logs command: `$ hydra investigate show-logs 47a594ac-0662-42a0-b242-7167df9a5265`

Test id: `47a594ac-0662-42a0-b242-7167df9a5265`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_190231/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_190343-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_190231/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_190343-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_190231/grafana-screenshot-overview-20221123_190231-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_190231/grafana-screenshot-overview-20221123_190231-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_192741/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_192816-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_192741/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_192816-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_192741/grafana-screenshot-overview-20221123_192741-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_192741/grafana-screenshot-overview-20221123_192741-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_193250/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_193324-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_193250/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_193324-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_193250/grafana-screenshot-overview-20221123_193250-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_193250/grafana-screenshot-overview-20221123_193250-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210359/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_210433-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210359/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_210433-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210359/grafana-screenshot-overview-20221123_210359-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210359/grafana-screenshot-overview-20221123_210359-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210911/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_210945-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210911/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_210945-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210911/grafana-screenshot-overview-20221123_210911-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_210911/grafana-screenshot-overview-20221123_210911-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_213524/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_213558-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_213524/grafana-screenshot-longevity-10gb-3h-gce-test-scylla-per-server-metrics-nemesis-20221123_213558-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_213524/grafana-screenshot-overview-20221123_213524-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_213524/grafana-screenshot-overview-20221123_213524-longevity-10gb-3h-master-monitor-node-47a594ac-0-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/db-cluster-47a594ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/db-cluster-47a594ac.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/loader-set-47a594ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/loader-set-47a594ac.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/monitor-set-47a594ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/monitor-set-47a594ac.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/sct-runner-47a594ac.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/47a594ac-0662-42a0-b242-7167df9a5265/20221123_214545/sct-runner-47a594ac.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/285/)

**Comment by KnifeyMoloko** [comment]
Looks like I've missed `USING TIMEOUT` in some cases. I'll look into it.

**Comment by fgelcer** [comment]
@KnifeyMoloko , let's get the PR merged ASAP
