### ISSUE TITLE
SCT doesn't detect endless broken mgmt backup process caused by the lack of free space on the backup storage

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5479]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: 339a3064-2982-47aa-97bc-0b6957be83aa
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-12h-multitenant-eks/8/consoleFull

### Description

Running K8S longevity multitenant setup with more than 1 nemesis thread we may face following situation like in the tracked here Ci job:

One tenant runs `mgmt_backup` nemesis which faces https://github.com/scylladb/scylla-manager/issues/3271 bug,
and falls into endless backup loop.
Another tenant runs any of `exclusive` nemesis's like `terminate_and_replace_node_kubernetes`.
The exclusive nemesis acquires lock, doesn't allow other nemesis to start and waits while existing ones finish.
But, existing running nemesis may be endless as in case of `tenant 1` and it's backup process.

So, as a result, it leads to the situation like in the referenced CI job: 
all the nemesis 's are blocked while the endless manager backup
process runs. The referenced CI job had running nemesis's for `1h` from `12h`. `11h` were spent for the buggy backup only.

### Steps to Reproduce

1. Deploy K8S cluster
2. Deploy operator
3. Deploy scylla-manager with `MinIO` backend which has too small disk size that won't fit a backup
4. Run K8S longevity multitenant setup with 2+ Scylla tenants running nemesis, one runs `mgmt_backup`, second any `exclusive`.
5. See that one tenant faces https://github.com/scylladb/scylla-manager/issues/3271 bug and blocks all other nemesis thread forever.

**Expected behavior:** 
- We should detect the referenced bug and mark as failed the backup nemesis right away stopping the non-sense backup process.
- We should mark all further manager backup nemesis for `skip` as known to be failed for sure
- We should have some time limit for the blocking exclusive nemesis. For example, make it wait only 1h, if it cannot wait for the end of the running nemesis than it must get skipped and release the lock.

**Actual behavior:** endless nemesis is not detected as well as the endless lock - both lead to the waste of time and money (11h from 12h were spent for nothing).

**Comment by fruch** [comment]
What are your suggestions for SCT ?

limit the nemesis in general ? 
limit for each nemesis on it's own ?

Keep in mind the time it would take is depended on the dataset type and size, we have one that takes can 12h, and we can't tell in advance how long they are gonna be.

One idea, since we keep score of nemesis in ES, is that we can cross reference the test/config with nemesis successful runs, and guesstimate a reasonable limit.

As for the lock, if we'll cache that limit from previous step, it can pick the longest limit of the ongoing nemesis as a timeout.

In other nemesis, we just set a hard limit of 8 hours for example, which I don't know if we did for backup nemesis.

**Comment by vponomaryov** [comment]
> What are your suggestions for SCT ?
> 
> limit the nemesis in general ? limit for each nemesis on it's own ?
> 
> Keep in mind the time it would take is depended on the dataset type and size, we have one that takes can 12h, and we can't tell in advance how long they are gonna be.
> 
> One idea, since we keep score of nemesis in ES, is that we can cross reference the test/config with nemesis successful runs, and guesstimate a reasonable limit.
> 
> As for the lock, if we'll cache that limit from previous step, it can pick the longest limit of the ongoing nemesis as a timeout.
> 
> In other nemesis, we just set a hard limit of 8 hours for example, which I don't know if we did for backup nemesis.

My proposal is simple: the bug gets detected by the reduced already backed up size. So, we just add detection of the reduced size. When it happens, we mark nemesis as "failed" and stop "backup" process in manager explicitly. Also, we mark "mgmt backup" nemesis for further skips.

**Comment by fruch** [comment]
> > What are your suggestions for SCT ?
> > limit the nemesis in general ? limit for each nemesis on it's own ?
> > Keep in mind the time it would take is depended on the dataset type and size, we have one that takes can 12h, and we can't tell in advance how long they are gonna be.
> > One idea, since we keep score of nemesis in ES, is that we can cross reference the test/config with nemesis successful runs, and guesstimate a reasonable limit.
> > As for the lock, if we'll cache that limit from previous step, it can pick the longest limit of the ongoing nemesis as a timeout.
> > In other nemesis, we just set a hard limit of 8 hours for example, which I don't know if we did for backup nemesis.
> 
> My proposal is simple: the bug gets detected by the reduce of the already backed up size. So, we just add detection of the reduced size. When it happens, we mark nemesis as "failed" and stop "backup" process in manager explicitly. Also, we mark "mgmt backup" nemesis for further skips. That's all.

this is a very specific solution to a specific nemesis, you might as well fix the root cause (enlarge minio size or switch to S3, and be done with it)

if we write a specific code for this issue, the next one that make a nemesis get "stuck" we didn't solved.

**Comment by vponomaryov** [comment]
> > > What are your suggestions for SCT ?
> > > limit the nemesis in general ? limit for each nemesis on it's own ?
> > > Keep in mind the time it would take is depended on the dataset type and size, we have one that takes can 12h, and we can't tell in advance how long they are gonna be.
> > > One idea, since we keep score of nemesis in ES, is that we can cross reference the test/config with nemesis successful runs, and guesstimate a reasonable limit.
> > > As for the lock, if we'll cache that limit from previous step, it can pick the longest limit of the ongoing nemesis as a timeout.
> > > In other nemesis, we just set a hard limit of 8 hours for example, which I don't know if we did for backup nemesis.
> > 
> > 
> > My proposal is simple: the bug gets detected by the reduce of the already backed up size. So, we just add detection of the reduced size. When it happens, we mark nemesis as "failed" and stop "backup" process in manager explicitly. Also, we mark "mgmt backup" nemesis for further skips. That's all.
> 
> this is a very specific solution to a specific nemesis, you might as well fix the root cause (enlarge minio size or switch to S3, and be done with it)
> 
> if we write a specific code for this issue, the next one that make a nemesis get "stuck" we didn't solved.

The "get stuck" problem is another solution for the lock mechanism - just need to set a time limit for waiting and skip an exclusive nemesis after it.

And the proposed solution for the mgmt doesn't exclude size change, it is complementary.

**Comment by fruch** [comment]
> > > > What are your suggestions for SCT ?
> > > > limit the nemesis in general ? limit for each nemesis on it's own ?
> > > > Keep in mind the time it would take is depended on the dataset type and size, we have one that takes can 12h, and we can't tell in advance how long they are gonna be.
> > > > One idea, since we keep score of nemesis in ES, is that we can cross reference the test/config with nemesis successful runs, and guesstimate a reasonable limit.
> > > > As for the lock, if we'll cache that limit from previous step, it can pick the longest limit of the ongoing nemesis as a timeout.
> > > > In other nemesis, we just set a hard limit of 8 hours for example, which I don't know if we did for backup nemesis.
> > > 
> > > 
> > > My proposal is simple: the bug gets detected by the reduce of the already backed up size. So, we just add detection of the reduced size. When it happens, we mark nemesis as "failed" and stop "backup" process in manager explicitly. Also, we mark "mgmt backup" nemesis for further skips. That's all.
> > 
> > 
> > this is a very specific solution to a specific nemesis, you might as well fix the root cause (enlarge minio size or switch to S3, and be done with it)
> > if we write a specific code for this issue, the next one that make a nemesis get "stuck" we didn't solved.
> 
> The "get stuck" problem is another solution for the lock mechanism - just need to set a time limit for waiting and skip an exclusive nemesis after it.

and how would you get the time limit from ? just hardcore for what exactly ?

> 
> And the proposed solution for the mgmt doesn't exclude size change, it is complementary.

**Comment by vponomaryov** [comment]
First cold mgmt backup takes much more time than further ones. So, 1h, I think, would cover the case.

**Comment by fruch** [comment]
> First cold mgmt backup takes much more time than further ones. So, 1h, I think, would cover the case.

as you can see:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/1475c3ecfff0826a706ccd8eb730d31c

![image](https://user-images.githubusercontent.com/340979/204518375-d3542356-b4d9-4eb6-bac3-5eef6a357d19.png)


on cases with bigger dataset it can be even 10h (and this is information, just from the last 3 months)

**Comment by vponomaryov** [comment]
I know that we have big datasets. This particular bug appears only in the `multitenant` case. So, it makes no sense to care about big datasets in current case. Only datasets in multitenant setup. We can make the time be configurable. But, personally, I don't see a need in it, at least, now.
