### ISSUE TITLE
Failures to get Coredump information on latest AMIs 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5489]
AMI: `ami-0a32d24be5d81ce05` (eu-west-1)
scylla version: `5.2.0~dev-0.20221117.2add9ba2925c with build-id fcf4dc562082746c569714d64fd2ad921daaa52e`

seem like we are failing to reading coredump listing in newer version of ubuntu (SMI images recently moved to ubuntu 22.04)

```
00:26:26  < t:2022-11-27 22:26:26,702 f:coredump.py     l:316  c:sdcm.cluster_aws     p:ERROR > Node longevity-10gb-3h-change-m-db-node-35fe2372-3 [54.246.12.208 | 10.4.2.25] (seed: False): CoredumpExportSystemdThread: PID pattern matched non-numerical value. Looks like coredumpctl changed it's output
```

this is systemd 249
```
scyllaadm@longevity-10gb-3h-change-m-db-node-35fe2372-4:~$ sudo coredumpctl --version
systemd 249 (249.11-0ubuntu3.6)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

output see to by a bit minimized, and our logic that was looking for 2 spaces isn't working anymore
```
scyllaadm@longevity-10gb-3h-change-m-db-node-35fe2372-4:~$ sudo coredumpctl list
TIME                          PID UID GID SIG     COREFILE EXE                           SIZE
Sun 2022-11-27 11:25:59 UTC 11218   0   0 SIGSEGV missing  /usr/bin/bash                  n/a
Sun 2022-11-27 21:48:10 UTC  6755 112 118 SIGABRT present  /opt/scylladb/libexec/scylla 57.5G
```

seems like since version 248 there a new flag `--json`, we should consider start using that, instead of parsing tables 
https://github.com/systemd/systemd/commit/0689cfdb83f573f70188003a366f20968267be7f

## Logs:

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity/job/longevity-10gb-3h/80/

**Comment by roydahan** [comment]
We need it ASAP
