### ISSUE TITLE
Fullscan thread isn't stopping on test failures

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5495]
Test failed cause of critical error:
```
16:55:45  < t:2022-11-28 14:55:45,363 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > sdcm.tester.CriticalTestFailure: Critical Error has failed the test
```

for 25min later the scan thread is still working (and printing like crazy info level logs)

looking at the code, seems like we now have two loops, the one in `run` and one inside `run_next_scan_operation`
`operation_queue` is filled up with (OPERATION_QUEUE_MAXSIZE = 10000) items to execute

and then execute all of them without a sleep in the middle, and without checking `nemesis_termination_event`

also nothing is filling `operation_queue` again, on on a longer test case it might finish it's work, and wouldn't do anything else.

```
    def run_next_scan_operation(self):
        try:
            while not self.operation_queue.empty():
                scan_op = self.operation_queue.queue.pop()
                self.log.info("Going to run fullscan operation %s", scan_op.__class__.__name__)
                scan_op.run_scan_operation()

            self.log.debug("Fullscan operations queue depleted.")

        except Exception as exc:  # pylint: disable=broad-except
            self.log.warning("Encountered exception while performing a fullscan operation:\n%s", exc)

    def run(self):
        end_time = time.time() + self.fullscan_params.duration
        self.wait_until_user_table_exists()

        while time.time() < end_time and not self.fullscan_params.db_cluster.nemesis_termination_event.is_set():
            self.fullscan_stats.read_pages = self.generator.choice([100, 1000, 0])
            self.run_next_scan_operation()
            time.sleep(self.fullscan_params.interval)
        self.log.info("Fullscan stats:\n%s", self.fullscan_stats.get_stats_pretty_table())
```

test_id: 14bd9a3c-5dfc-4f90-9bd6-8e3e1450cdd7
Job:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-large-partition-asymmetric-cluster-3h-test/12/

**Comment by fruch** [comment]
> we are seeing it again in the following tests id: `c125b61b-82a7-4b68-8009-1cbf938e3051` `b71d3e31-f4fc-45e5-bcd1-8349145ab76c`

it's not related to this issue, i.e. this issue was about the new implementation

I would suggestion opening a new one with more specific info  ( and not just test_id )

**Comment by KnifeyMoloko** [comment]
@fruch Do you happen to have the link to the job that failed? Looks like the test_id does not line up with the job link here and I can't find an email with that test_id anywhere. It's not super important, since we can progress without the logs, but would be helpful for @temichus investigation efforts.

**Comment by fruch** [comment]
> @fruch Do you happen to have the link to the job that failed? Looks like the test_id does not line up with the job link here and I can't find an email with that test_id anywhere. It's not super important, since we can progress without the logs, but would be helpful for @temichus investigation efforts.

yes the job link was incorrect, this is the job:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-large-partition-asymmetric-cluster-3h-test/12/

**Comment by fgelcer** [comment]
> > @fruch Do you happen to have the link to the job that failed? Looks like the test_id does not line up with the job link here and I can't find an email with that test_id anywhere. It's not super important, since we can progress without the logs, but would be helpful for @temichus investigation efforts.
> 
> yes the job link was incorrect, this is the job: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-large-partition-asymmetric-cluster-3h-test/12/

@temichus , let me know if you need help with finding the logs

**Comment by fgelcer** [comment]
about full partition scans, although we saw there was an issue with it, it seems to be AFAICT on the verification of it, hence less urgent for fixing.
moved this task/issue to waiting for review, and once merged, we shall create a task to confirm the full partition scans behavior is as expected, and if not, fix it.

**Comment by roydahan** [comment]
These changes are already part of 5.2 & 2023.1.
