### ISSUE TITLE
Azure: disrupt_rebuild_streaming_err timeouts looking for `Rebuild starts`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5506]
## Installation details

Kernel Version: 5.15.0-1023-azure
Scylla version (or git commit hash): `5.2.0~dev-20221129.8bc0af9e34fa` with build-id `64a68bc4306bd55bc726a81b066ae3350e79d108`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-8 (23.96.49.29 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-7 (52.152.233.218 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-6 (172.173.160.18 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-5 (20.231.122.14 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-4 (20.172.155.115 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-3 (4.246.181.200 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-2 (4.246.181.198 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-1 (20.172.155.182 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-11-29T13-26-23` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8224bdc2a2c0d512fbe00b7b4870591c5d3414a/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

Stress is failing with unclear reason 
```
2022-11-29 16:19:50.968: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=74718019-b5df-4f33-a186-b0647e4bdacd during_nemesis=NoCorruptRepair duration=3h10m0s: node=Node longevity-10gb-3h-master-loader-node-54aa0b5e-eastus-1 [20.172.155.136 | 10.0.0.11] (seed: False)
stress_cmd=cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
errors:
Stress command completed with bad status 1: WARN  13:09:52,113 Not using advanced port-based shard awareness with /10.0.0.8:9042 because we're m
```

Return code is 1, but the stress log seems like:
```
Results:
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Op rate                   :   64,583 op/s  [WRITE: 64,583 op/s]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Partition rate            :   64,583 pk/s  [WRITE: 64,583 pk/s]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Row rate                  :   64,583 row/s [WRITE: 64,583 row/s]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency mean              :   15.5 ms [WRITE: 15.5 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency median            :    9.7 ms [WRITE: 9.7 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency 95th percentile   :   47.4 ms [WRITE: 47.4 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency 99th percentile   :   87.2 ms [WRITE: 87.2 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency 99.9th percentile :  154.1 ms [WRITE: 154.1 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Latency max               : 41708.2 ms [WRITE: 41,708.2 ms]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total partitions          : 697,531,497 [WRITE: 697,531,497]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total errors              :          0 [WRITE: 0]
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total GC count            : 0
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total GC memory           : 0.000 KiB
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total GC time             :    0.0 seconds
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Avg GC time               :    NaN ms
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
StdDev GC time            :    0.0 ms
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
Total operation time      : 03:00:00
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response

com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
END
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.6:9042] Timed out waiting for server response
```

So  something broken with `10.0.0.6` that had `disrupt_rebuild_streaming_err` timing out on that node

- Restore Monitor Stack command: `$ hydra investigate show-monitor 54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=54aa0b5e-c3a5-4bcb-b657-6b83d804a11d)
- Show all stored logs command: `$ hydra investigate show-logs 54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`

## Logs:
- **db-cluster-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/db-cluster-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/db-cluster-54aa0b5e.tar.gz)
- **monitor-set-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/monitor-set-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/monitor-set-54aa0b5e.tar.gz)
- **loader-set-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/loader-set-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/loader-set-54aa0b5e.tar.gz)
- **sct-runner-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/sct-runner-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/sct-runner-54aa0b5e.tar.gz)
- **parallel-timelines-report-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/parallel-timelines-report-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/parallel-timelines-report-54aa0b5e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/131/)

**Comment by fruch** [comment]
Seems like there a race condition in `start_and_interrupt_rebuild_streaming` between the rebuild thread, and the thread searching the logs for `Rebuild starts`, if the rebuild starts before it's starts looking at the logs, it might never read the `Rebuild starts`

solution:
`self.target_node.follow_system_log` should happen before calling multiple threads, and passed down to `_call_disrupt_func_after_expression_logged`, and not created/started within the thread

**Comment by fruch** [comment]
the breakage of the stress command, seem like a different issue, not related to this specific nemesis

**Comment by fruch** [comment]
> the breakage of the stress command, seem like a different issue, not related to this specific nemesis

the cassnadra-stress is a different issue
https://github.com/scylladb/java-driver/issues/180

**Comment by fgelcer** [comment]
didn't make it this sprint, moving to sprint 72

**Comment by fgelcer** [comment]
didn't make in sprint 74, moving to sprint 75
