### ISSUE TITLE
Rolling-upgrade c-s commands before significantly slower after move to docker based loaders

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5526]
@fgelcer noticed this in https://github.com/scylladb/scylla-cluster-tests/pull/5524#issuecomment-1336502023
> @roydahan , true that, but in [this job](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu20.04-test/), until November 5th tests took 4.5 hours, and since, more than 5 hours (close to 6 hours, or more)

and @roydahan analysis:

> First, for ubuntu20 job that you gave as an example, we used scylla image as the base line, so the total time is shorter. (BTW!! we need to change now the base of ubuntu20 to be clean image and ubuntu22 to be based on image).
> 
> For ubuntu18, I see that in Nov 5th, it took 5h37m, so it's still much lower than what we have now. From a deep analysis I did [here](https://docs.google.com/spreadsheets/d/1abgVTEJlyN1yl8DkmoEj-NohM9jJ3m5nRlGsdkb1YBg/edit?usp=sharing), I can think of 3 options:
> 
> 1. Severe performance degredation in Scylla
> 2. Regression in c-s tool we use.
> 3. Slow instances.
> 
> The details that supports my analysis:
> 
> Failed test cassandra-stress results:
> 
> ```
> egrep -e 'Total operation time' -e 'Total partitions' -e 'Op rate' sct.log
> Op rate                   :    3,412 op/s  [insert: 3,423 op/s]
> Total partitions          :  5,000,000 [insert: 5,000,000]
> Total operation time      : 00:24:25
> Op rate                   :    7,814 op/s  [WRITE: 7,814 op/s]
> Total partitions          : 20,100,200 [WRITE: 20,100,200]
> Total operation time      : 00:42:52
> Op rate                   :    6,579 op/s  [WRITE: 6,579 op/s]
> Total partitions          : 10,100,200 [WRITE: 10,100,200]
> Total operation time      : 00:25:35
> Op rate                   :    9,548 op/s  [READ: 9,548 op/s]
> Total partitions          : 10,100,200 [READ: 10,100,200]
> Total operation time      : 00:17:37
> Op rate                   :    7,343 op/s  [READ: 7,343 op/s]
> Total partitions          :  4,415,382 [READ: 4,415,382]
> Total operation time      : 00:10:01
> Op rate                   :   15,580 op/s  [READ: 15,580 op/s]
> Total partitions          : 56,098,868 [READ: 56,098,868]
> Total operation time      : 01:00:00
> Op rate                   :   16,069 op/s  [READ: 16,069 op/s]
> Total partitions          : 20,100,200 [READ: 20,100,200]
> Total operation time      : 00:20:50
> ```
> 
> Passed test cassandra-stress results:
> 
> ```
> egrep -e 'Total operation time' -e 'Total partitions' -e 'Op rate' sct.log
> Op rate                   :    8,046 op/s  [insert: 8,072 op/s]
> Total partitions          :  5,000,000 [insert: 5,000,000]
> Total operation time      : 00:10:21
> Op rate                   :   17,795 op/s  [WRITE: 17,795 op/s]
> Total partitions          : 10,100,200 [WRITE: 10,100,200]
> Total operation time      : 00:09:27
> Op rate                   :   20,030 op/s  [READ: 20,030 op/s]
> Total partitions          : 10,100,200 [READ: 10,100,200]
> Total operation time      : 00:08:24
> Op rate                   :    9,083 op/s  [WRITE: 9,083 op/s]
> Total partitions          : 20,100,200 [WRITE: 20,100,200]
> Total operation time      : 00:36:52
> Op rate                   :   25,682 op/s  [READ: 25,682 op/s]
> Total partitions          : 15,427,625 [READ: 15,427,625]
> Total operation time      : 00:10:00
> Op rate                   :   29,562 op/s  [READ: 29,562 op/s]
> Total partitions          : 106,652,879 [READ: 106,652,879]
> Total operation time      : 01:00:07
> Op rate                   :   29,019 op/s  [READ: 29,019 op/s]
> Total partitions          : 20,100,200 [READ: 20,100,200]
> Total operation time      : 00:11:32
> Op rate                   :   11,078 op/s  [read1: 5,586 op/s, read3: 5,591 op/s]
> Total partitions          :  5,000,000 [read1: 2,498,747, read3: 2,501,253]
> Total operation time      : 00:07:31
> ```

**Comment by fruch** [comment]
I've tried a run with 4.6 scylla docker, and seems like it's still similarly slow:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test/2/

now trying a run with the VM fallback:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test/3/

**Comment by roydahan** [comment]
@fruch few comments on what you’ve wrote in the parallel PR:
1. The faster run is also running with docker based c-s (AFAICT).
2. This is a GCP test not AWS, so we can try to run the same command with/out docket from the same loader.
3. I ran another run last night, I’ll check it soon.

**Comment by fruch** [comment]
> @fruch few comments on what you’ve wrote in the parallel PR:
> 
> 1. The faster run is also running with docker based c-s (AFAICT). 

no, it has the revert in it

> 2. This is a GCP test not AWS, so we can try to run the same command with/out docket from the same loader.

we can't easily fallback to VMs in GCP, we need to create a prepared VM, which we don't have in GCP

> 3. I ran another run last night, I’ll check it soon.

**Comment by roydahan** [comment]
> > @fruch few comments on what you’ve wrote in the parallel PR:
> > 
> > 1. The faster run is also running with docker based c-s (AFAICT).
> 
> no, it has the revert in it

You're right, I just checked and all the "docker exec" are for other tools.
> 
> > 2. This is a GCP test not AWS, so we can try to run the same command with/out docket from the same loader.
> 
> we can't easily fallback to VMs in GCP, we need to create a prepared VM, which we don't have in GCP
> 
Are you running such test somewhere?

> > 3. I ran another run last night, I’ll check it soon.

**Comment by roydahan** [comment]
I think that I know why it happens.
We have many dockers running stress commands on the same loader in this test.
And maybe it's a slowdown caused by this.

**Comment by fruch** [comment]
> I think that I know why it happens. We have many dockers running stress commands on the same loader in this test. And maybe it's a slowdown caused by this.

I shouldn't be different then running multiple processes on the same runner in that regards.
we see a drop of %50 in throughput, it's more then this.

 
> > we can't easily fallback to VMs in GCP, we need to create a prepared VM, which we don't have in GCP
>  Are you running such test somewhere?

I'm trying it here:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test/4/

on more suspect I can think of, is that in c-s docker we are not using `--network=host` and this is also something I would like to try out.

**Comment by fruch** [comment]
run with `--network=host`:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test-host-network/2/

**Comment by vponomaryov** [comment]
The diff may also lay in the cpu context switch. 
Having one thread, as of now, we do not define the `--cpuset-cpus` docker option which must make a container get explicit dedicatation of a CPU core. 
Such a dedication means it will not have `expensive` CPU context-switch.
Which only gets worse having more heavy processes on a machine.
Note that setting that option will exclude overprovision of CPU cores.
But, in cases when you care about perf, it is even good that we get failures if we get undesired overprovisioning which leads to perf degradation.

**Comment by fruch** [comment]
> The diff may also lay in the cpu context switch. Having one thread, as of now, we do not define the `--cpuset-cpus` docker option which must make a container get explicit dedicatation of a CPU core. Such a dedication means it will not have `expensive` CPU context-switch. Which only gets worse having more heavy processes on a machine. Note that setting that option will exclude overprovision of CPU cores. But, in cases when you care about perf, it is even good that we get failures if we get undesired overprovisioning which leads to perf degradation.

how it's would be different then no using docker in this case ? i.e. we also never pinned the CPU in most of the cases

**Comment by vponomaryov** [comment]
> > The diff may also lay in the cpu context switch. Having one thread, as of now, we do not define the `--cpuset-cpus` docker option which must make a container get explicit dedicatation of a CPU core. Such a dedication means it will not have `expensive` CPU context-switch. Which only gets worse having more heavy processes on a machine. Note that setting that option will exclude overprovision of CPU cores. But, in cases when you care about perf, it is even good that we get failures if we get undesired overprovisioning which leads to perf degradation.
> 
> how it's would be different then no using docker in this case ? i.e. we also never pinned the CPU in most of the cases

Are we aware the perf diff setting and not setting it? We don't know how the docker's containerization efficiency comes out here.
It is expected to be 10% is general, but our goal is to reduce the unneeded perf penalties.

So, I just stated that pin of a CPU worth an attempt.

**Comment by fruch** [comment]
> > > The diff may also lay in the cpu context switch. Having one thread, as of now, we do not define the `--cpuset-cpus` docker option which must make a container get explicit dedicatation of a CPU core. Such a dedication means it will not have `expensive` CPU context-switch. Which only gets worse having more heavy processes on a machine. Note that setting that option will exclude overprovision of CPU cores. But, in cases when you care about perf, it is even good that we get failures if we get undesired overprovisioning which leads to perf degradation.
> > 
> > 
> > how it's would be different then no using docker in this case ? i.e. we also never pinned the CPU in most of the cases
> 
> Are we aware what is the perf diff setting and not setting it? We don't know how the docker's containerization "efficiency" comes out here. It is expected to be 10% is general, but our goal is to reduce the unneeded perf penalties as much as possible.
> 
> So, I just stated that pin of a CPU worth an attempt.

it's nice to say we need to set it, but we can't automatically select it correctly, current code doesn't hold any information to how many stress threads are going to use this loader

if I have 8 cpu on the loader, how many can I pin to a stress I'm starting now ? how can I tell how many stress are there going to be started at the same time ? 

we currently don't have enough information upstart to define those, setting it too high might break some of the use case, and setting it too low, might also break some of the cases....

**Comment by fruch** [comment]
based on https://github.com/moby/moby/issues/30801

I'm trying disabling the logging driver, and running with `--privileged` mode

**Comment by roydahan** [comment]
Maybe we can workaround it with more loaders and round_robin?

**Comment by fruch** [comment]
> Maybe we can workaround it with more loaders and round_robin?

if we are o.k. with the degregation, we can just extend the test duration, as you were going todo, and be done with it.

it's still weird, since in the performance test I did there wasn't such a big difference (and I wasn't doing those on GCP)

but in this test case we can it was ~40Kop/s and with docker it's drops to ~15Kop/s, i'm not sure we can just drop it (if it might affect other tests, that we didn't yet noticed)

**Comment by fruch** [comment]
I've change the test to work with stronger loader, throughput was much much better (maybe too good since the main load finished before all the upgrades too place):

![image](https://user-images.githubusercontent.com/340979/207031774-e457d2d8-cb21-4662-9408-b3e58cf1636a.png)
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test-host-network/13/

anyhow the test still took 6h:25m

with fallback to VMs and 2cpu loaders 
![image](https://user-images.githubusercontent.com/340979/207033028-4cd7504d-b71a-4903-afe0-b4f35386deed.png)

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test-host-network/12/
it took 5h:45m


@roydahan what do you think is better for those cases ?

**Comment by fruch** [comment]
> I think that for now it's better to use the VMs, because we know how the test behave and we don't need to start messing with timings. There is a task to refactor the entire rolling-upgrade test, there we should try to avoid hidden timings and possibly use the dockers.

o.k. please review https://github.com/scylladb/scylla-cluster-tests/pull/5553 that revert the needed code to fallback to VMs also in GCP

**Comment by fgelcer** [comment]
from the results here (https://github.com/scylladb/scylla-cluster-tests/pull/5524#issuecomment-1336588539), it seems that we have a very clear degradation, from c-s point of view...
should we run this test with VM instance loaders to be sure it is not related to the loaders?
IIRC this degradation was seen before the loaders moved to be docker containers... so, my guess is that we have a degradation in Scylla side
