### ISSUE TITLE
disrupt_rebuild_streaming_err fails with: list index out of range

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5538]
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3855, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3357, in disrupt_rebuild_streaming_err
    self.start_and_interrupt_rebuild_streaming()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3320, in start_and_interrupt_rebuild_streaming
    self._destroy_data_and_restart_scylla()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 243, in inner_func
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1003, in _destroy_data_and_restart_scylla
    file_for_destroy = self._choose_file_for_destroy(tables)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 940, in _choose_file_for_destroy
    ks_cf_for_destroy = random.choice(ks_cfs)  # expected value as: 'keyspace1.standard1'
  File "/usr/local/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221201.c5121cf27365` with build-id `d25d298da80af2e947d1728190d8f4f26978e44a`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-41fa60db-9 (34.227.61.71 | 10.12.8.50) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-8 (54.172.72.90 | 10.12.10.152) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-7 (54.227.114.85 | 10.12.9.165) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-6 (54.164.104.79 | 10.12.9.16) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-5 (3.85.198.112 | 10.12.11.109) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-4 (18.234.64.137 | 10.12.10.139) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-3 (18.208.221.98 | 10.12.8.86) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-2 (52.23.224.189 | 10.12.11.102) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-11 (50.17.90.79 | 10.12.10.164) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-10 (54.83.110.139 | 10.12.9.186) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-1 (34.229.220.114 | 10.12.10.44) (shards: 7)

OS / Image: `ami-058aaa3c56c451303` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f29e454d005db4f1d9a2d8f619d36dbe3919ee0/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=41fa60db-6de8-4a2f-8a9a-eba66cb9439a)
- Show all stored logs command: `$ hydra investigate show-logs 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`

## Logs:
- **db-cluster-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz)
- **monitor-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz)
- **loader-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz)
- **sct-runner-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/67/)

**Comment by fruch** [comment]
look for those prints;
```
self.log.warning(f'Failed to get rows from {table_name} table. Error: {exc}')
```

**Comment by roydahan** [comment]
But what is the root cause of this?

**Comment by fgelcer** [comment]
> But what is the root cause of this?

@yarongilor must confirm it, but IIUC this happened because we got a failed when querying system tables to find in which table to run the nemesis, and we got an empty error, because of an issue (https://github.com/scylladb/scylladb/issues/12268)

**Comment by fruch** [comment]
> > But what is the root cause of this?
> 
> @yarongilor must confirm it, but IIUC this happened because we got a failed when querying system tables to find in which table to run the nemesis, and we got an empty error, because of an issue (https://github.com/scylladb/scylladb/issues/12268)

It's not the root cause, it just found in the same log.

Seems like we have a new limit on number of tombstones in an unpaged query. We need to figure why our query doesn't consider paginated. (could be a bug in scylla or in SCT)

Or we can raise that limit for this test case.

**Comment by roydahan** [comment]
Avi said we should run all our queries with paging.
@yarongilor  is working on it to update our queries.

**Comment by fruch** [comment]
> Avi said we should run all our queries with paging. @yarongilor is working on it to update our queries.

the python-driver should be doing paged queries automatically, with `default_fetch_size = 5000` is that too big in this case ?

**Comment by roydahan** [comment]
IIRC the error is for 1000 tombstones, so probably 5K is too big.
who decided on the 5K as default?

**Comment by fruch** [comment]
> IIRC the error is for 1000 tombstones, so probably 5K is too big.
> who decided on the 5K as default?

Datastax, it's the default in the driver
