### ISSUE TITLE
subcontext event as causing some DbLogEvent to not be published

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5544]
## Issue description

look we have some unsafe code in the subcontext handling:
```
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > Traceback (most recent call last):
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_log_reader.py", line 148, in _read_and_publish_events
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >     cloned_event = event.clone().add_info(node=self._node_name, line_number=index, line=line)
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/base.py", line 467, in add_info
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >     self.add_subcontext()
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/base.py", line 231, in add_subcontext
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR >     if nemesis not in self.subcontext:
< t:2022-12-02 13:11:02,138 f:db_log_reader.py l:155  c:sdcm.db_log_reader   p:ERROR > TypeError: argument of type 'NoneType' is not iterable
```

## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221201.c5121cf27365` with build-id `d25d298da80af2e947d1728190d8f4f26978e44a`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-41fa60db-9 (34.227.61.71 | 10.12.8.50) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-8 (54.172.72.90 | 10.12.10.152) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-7 (54.227.114.85 | 10.12.9.165) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-6 (54.164.104.79 | 10.12.9.16) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-5 (3.85.198.112 | 10.12.11.109) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-4 (18.234.64.137 | 10.12.10.139) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-3 (18.208.221.98 | 10.12.8.86) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-2 (52.23.224.189 | 10.12.11.102) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-11 (50.17.90.79 | 10.12.10.164) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-10 (54.83.110.139 | 10.12.9.186) (shards: 7)
- longevity-twcs-48h-master-db-node-41fa60db-1 (34.229.220.114 | 10.12.10.44) (shards: 7)

OS / Image: `ami-058aaa3c56c451303` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f29e454d005db4f1d9a2d8f619d36dbe3919ee0/test-cases/longevity/longevity-twcs-48h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=41fa60db-6de8-4a2f-8a9a-eba66cb9439a)
- Show all stored logs command: `$ hydra investigate show-logs 41fa60db-6de8-4a2f-8a9a-eba66cb9439a`

## Logs:
- **db-cluster-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/db-cluster-41fa60db.tar.gz)
- **monitor-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/monitor-set-41fa60db.tar.gz)
- **loader-set-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/loader-set-41fa60db.tar.gz)
- **sct-runner-41fa60db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41fa60db-6de8-4a2f-8a9a-eba66cb9439a/20221204_051915/sct-runner-41fa60db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/67/)

**Comment by juliayakovlev** [comment]
To better understanding which type of event cause this failure I added print out with event content.
Also init the `self.subcontext` if it was not initialized (to prevent event failure)

**Comment by fruch** [comment]
> To better understanding which type of event cause this failure I added print out with event content. Also init the `self.subcontext` if it was not initialized (to prevent event failure)

please check the TWCS weekly run if you have the prints you need to understand what was going on.

**Comment by juliayakovlev** [comment]
> > To better understanding which type of event cause this failure I added print out with event content. Also init the `self.subcontext` if it was not initialized (to prevent event failure)
> 
> please check the TWCS weekly run if you have the prints you need to understand what was going on.

The job was not triggered after the PR merge. 
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/

I am checking other jobs that were started after merge

**Comment by fruch** [comment]
> > > To better understanding which type of event cause this failure I added print out with event content. Also init the `self.subcontext` if it was not initialized (to prevent event failure)
> > 
> > 
> > please check the TWCS weekly run if you have the prints you need to understand what was going on.
> 
> The job was not triggered after the PR merge. https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/
> 
> I am checking other jobs that were started after merge

I think there was a raft equivalent job that was running during the weekend

**Comment by juliayakovlev** [comment]
> > > > To better understanding which type of event cause this failure I added print out with event content. Also init the `self.subcontext` if it was not initialized (to prevent event failure)
> > > 
> > > 
> > > please check the TWCS weekly run if you have the prints you need to understand what was going on.
> > 
> > 
> > The job was not triggered after the PR merge. https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/
> > I am checking other jobs that were started after merge
> 
> I think there was a raft equivalent job that was running during the weekend

There is not:

https://argus.scylladb.com/workspace?state=WyI1NzRjZjZiMS02NTFhLTRkZTctOTQyMy05Y2EwMzk2YjJkNjQiLCIyMmU1ZjlkOS02Mjc5LTQ2ZTMtYTNjYy1jMWU1Y2RiYWEzNmIiLCIyOTA2MzVlYi05MjhjLTQ1NjctYmZlOS0wOGM2MDk1ZGU2NjAiLCIzYTk4YjNmMS01NTM0LTRlOTUtYTdhOS0yZjQxMDRmNGM4NTEiLCIzYWM0MGE1Mi1mOWJmLTQ4YWYtOWY1Ni02NTIxY2YzYjAzMDQiLCIzZDZmNTRkOS01Zjk3LTQwMzctOThhZS1mZWE3YmI5ZDUxYjIiLCJhZmMwMGQzYy0wMTExLTRlNWUtOTgzYy03YmEyYzlmMzQ3NDQiLCIwNDMxZTFhNy01MzVlLTRlOTAtYmE0OC0xOTY0YTk3ZWY5MTQiLCI0NjA0YmNmZi1jNGU3LTQ3YTEtOTc4YS01NTMzNDAyZjQ4NmYiLCI1MTAwM2U0OC1iMDk4LTQyY2MtYmZjZS1kMjQwYWFjODM5MzgiLCI1OTgxNjI1MS0zNTUxLTRiNGMtOWViNC0xOTg5NTllOWZmNWUiLCI4Y2RmN2QyYS01MGE4LTRmODctOWJlYS1kNTIzZTA5YjViMGMiLCJhMTUwZDhiNS04ZDFjLTQ3M2MtOWUxZS1jODg5YzY5ZjFhMWIiLCJhNGZlMzBiMC1mMzkwLTQ1MTUtODZlMC0yZTJhMGMwYjNmYjAiLCJiOGQ1NTEyMi1hMjc2LTQwZDUtYmEzZC1jZTMyOTdiOTQ0YzUiLCJiZDA0YzFiNS0xYjNiLTRkNjYtODE3My1kMWJiNTBiNzllZmYiLCJmMzJlOWM1OC03MDY5LTQ1YjctODI0Ni03MjExY2RhMmI3YWUiXQ

**Comment by juliayakovlev** [comment]
Found in https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-cdc-3d-400gb-test/2/

```
< t:2022-12-09 12:32:26,849 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-12-09T12:32:26+00:00 longevity-cdc-3d-400gb-master-db-node-43d44169-5      !ERR | scylla[5676]:  [shard  3] storage_ser
vice - Shutting down communications due to I/O errors until operator intervention: Disk error: std::system_error (error system:28, No space left on device)
< t:2022-12-09 12:32:26,849 f:base.py         l:227  c:sdcm.sct_events.base p:ERROR > 'self.subcontext' was not initialized. Event: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=9d3d257d-f486-4
e4b-8c0b-eae02d951242: type=NO_SPACE_ERROR regex=No space left on device line_number=213449 node=longevity-cdc-3d-400gb-master-db-node-43d44169-5
```

And published event with "[SCT internal warning]", but not explanation why:
```
< t:2022-12-09 12:33:00,425 f:base.py         l:318  c:sdcm.sct_events.base p:WARNING > [SCT internal warning] (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=9d3d257d-f486-4e4b-8c0b-eae02d951242: type=NO_SPACE_ERROR regex=No space left on device line_number=224710 node=longevity-cdc-3d-400gb-master-db-node-43d44169-5
```

**Comment by fruch** [comment]
@juliayakovlev

I think I've found the root cause, and the case causing it to be None, see #5550 with my findings
