### ISSUE TITLE
SCT doesn't detect overload state of Scylla members running in K8S multitenant setup

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5560]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 5.0.5

### Logs
* test_id: b349fb10-e9cc-4880-aa22-849012a1b3b3
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-12h-multitenant-eks/21

### Description

Running K8S multitenant setup with 14clients where we have 3 members using 1 core/shard we get following problem for sure:

After 7-8 hours of load one of the clusters goes into a constant 100% load on all the pods/members and SCT doesn't detect it anyhow
and doesn't create any events to notify about it.
The 100% load goes for about 2 hours. And in the end of second hour the latency gets increased a lot and finally we get C-S failures not having quorum answers.

Monitoring: 
![Screenshot from 2022-12-13 17-03-38](https://user-images.githubusercontent.com/3796058/207400213-50062860-fa3b-4ecc-a447-bb32a304314c.png)

Loader:
```
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
... lots lines ...
total,      78037359,    2500,    2500,    2500,     6.2,     6.0,     9.4,    11.3,    15.3,    22.1,31215.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78049861,    2500,    2500,    2500,     6.3,     5.9,     9.5,    13.5,    80.8,    84.2,31220.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78061335,    2295,    2295,    2295,    17.1,     7.1,    79.8,   177.7,   211.7,   326.6,31225.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78072050,    2143,    2143,    2143,    17.5,     7.1,    77.8,   185.1,   314.3,   318.8,31230.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78086913,    2973,    2973,    2973,    13.6,     7.3,    54.7,   112.2,   160.7,   190.4,31235.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78098370,    2291,    2291,    2291,    17.4,     9.8,    61.8,   116.8,   158.2,   165.4,31240.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78106457,    1617,    1617,    1617,    24.7,     7.0,    73.4,   308.8,  1715.5,  1928.3,31245.0,  0.00076,      0,      0,       0,       0,       0,       0
WARN  06:31:48,526 Error creating netty channel to /172.20.87.255:9042
com.datastax.shaded.netty.channel.ConnectTimeoutException: connection timed out: /172.20.87.255:9042
	at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:218) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
WARN  06:31:48,574 Error creating netty channel to sct-cluster-us-east1-b-us-east1-0.scylla.svc.cluster.local/172.20.139.186:9042
com.datastax.shaded.netty.channel.ConnectTimeoutException: connection timed out: sct-cluster-us-east1-b-us-east1-0.scylla.svc.cluster.local/172.20.139.186:9042
	at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:218) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
total,      78119874,    2683,    2683,    2683,    13.9,     7.1,    19.9,   164.5,   863.0,   944.8,31250.0,  0.00076,      0,      0,       0,       0,       0,       0
total,      78134156,    2856,    2856,    2856,    13.3,     7.2,    22.1,   145.2,   716.7,   910.7,31255.0,  0.00077,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
... 38 same messages ...
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
total,      78134267,      22,      22,      22,   464.2,    11.0,  1726.0,  1727.0,  1730.2,  1730.2,31260.0,  0.00078,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
... 277 same messages ...
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
... 51 same messages ...
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [4c4c324d363735363631]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x10 on key(s) [33314e4e333950313130]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

### Steps to Reproduce

1. Deploy K8S multitenant setup with 14 clients where each has 3 single-core members.
2. Run it for more than 8 hours where we run different nemesis's on 5 of them
3. See overload on one (can be more) of the clusters and see no events from SCT.

**Expected behavior:** SCT must detect overload of any multitenant cluster and shout about it.

**Actual behavior:** SCT is silent about overload, waits until loader fails to perform it's operations.

**Comment by vponomaryov** [comment]
@fruch except the SCT's problem, I guess we need to discuss the guaranteed 100% load of a Scylla cluster in this setup...

**Comment by fruch** [comment]
> @fruch except the SCT's problem, I guess we need to discuss the guaranteed 100% load of a Scylla cluster in this setup...

As for notification about overloadthis quite a common case that all 3 nodes are using all their CPU. and as long from user perspective they still behave as expected is o.k.
We could easily add an alert with error level, but we should be selective on which cases to put enable such alerts.

As for this specific case we need a bit more information, of what brings it to this situation, i.e if it's a specific nemesis that took place or just the size of data, since we don't change the actual load.

We are trying to learn what are the limitations of the free tier setup, and report our findings.

**Comment by vponomaryov** [comment]
> > @fruch except the SCT's problem, I guess we need to discuss the guaranteed 100% load of a Scylla cluster in this setup...
> 
> As for notification about overloadthis quite a common case that all 3 nodes are using all their CPU. and as long from user perspective they still behave as expected is o.k. We could easily add an alert with error level, but we should be selective on which cases to put enable such alerts.
> 
> As for this specific case we need a bit more information, of what brings it to this situation, i.e if it's a specific nemesis that took place or just the size of data, since we don't change the actual load.
> 
> We are trying to learn what are the limitations of the free tier setup, and report our findings.

There are no errors in DB logs, only info about compaction changes. Which are endless.
But all pods of the cluster are definitely tied in their 100% load. 
At first pod-2 goes to 100%, then pod-0 and last one is pod-1.
I also plan to run scylla 5.1 and see whether it happens there or not.

**Comment by fruch** [comment]
> > > @fruch except the SCT's problem, I guess we need to discuss the guaranteed 100% load of a Scylla cluster in this setup...
> > 
> > As for notification about overloadthis quite a common case that all 3 nodes are using all their CPU. and as long from user perspective they still behave as expected is o.k. We could easily add an alert with error level, but we should be selective on which cases to put enable such alerts.
> > 
> > As for this specific case we need a bit more information, of what brings it to this situation, i.e if it's a specific nemesis that took place or just the size of data, since we don't change the actual load.
> > 
> > We are trying to learn what are the limitations of the free tier setup, and report our findings.
> 
> There are no errors in DB logs, only info about compaction changes. Which are endless.
> But all pods of the cluster are definitely tied in their 100% load. 
> At first pod-2 goes to 100%, then pod-0 and last one is pod-1.
> I also plan to run scylla 5.1 and see whether it happens there or not.

Let's review the monitor data from such tenants, to see what the CPU is mostly busy with, could be with compaction. Could be with something else.

**Comment by fruch** [comment]
@vponomaryov share the test id, so I can download the data locally, 

this is not the dashboard we should be looking at, I think the advanced dashboard would be more helpful with how the CPU is being use by different scylla components

**Comment by vponomaryov** [comment]
> @vponomaryov share the test id, so I can download the data locally,
> 
> this is not the dashboard we should be looking at, I think the advanced dashboard would be more helpful with how the CPU is being use by different scylla components

It is in the bug description.
Alive monitor node is here: http://3.251.73.55:3000/d/bjO3rV5Vk/vp-longevity-scylla-operator-12h-multitenant-eks-sct-cluster-scylla-per-server-metrics-nemesis-master?orgId=1&from=1670907567267&to=1670908189207

**Comment by fruch** [comment]
here you can see that the compaction is getting a bit out of hand here:
![image](https://user-images.githubusercontent.com/340979/207420622-86d38802-41ec-44cf-96a5-b02bc487a882.png)

I'm guessing I'm looking on the first cluster

and seem like the issue is starting with this modify table nemesis:
(DisruptionEvent Severity.NORMAL) period_type=end event_id=1cb4d054-6ede-4f9f-af91-fe2c296bcd4c duration=2s: nemesis_name=ModifyTable target_node=Node sct-cluster-us-east1-b-us-east1-0 [10.4.0.187 | 10.4.0.165] (seed: False)
