### ISSUE TITLE
disrupt_no_corrupt_repair creates keyspaces with simple strategy in multidc cluster

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5564]
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221210.e47794ed9832` with build-id `a0d3f077099c66bf6c75707e386c6be3ba2c431f`

Cluster size: 9 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-9 (3.231.157.7 | 10.12.0.55) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-8 (54.236.61.76 | 10.12.2.89) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-7 (35.89.159.251 | 10.15.1.10) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-6 (34.220.120.124 | 10.15.0.20) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-5 (52.25.251.196 | 10.15.2.173) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-4 (34.252.129.224 | 10.4.1.211) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-3 (52.213.184.34 | 10.4.3.73) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-2 (3.250.26.135 | 10.4.0.234) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-10 (63.35.237.58 | 10.4.2.223) (shards: 30)
- lwt-longevity-multi-dc-24h-master-db-node-098c83c6-1 (34.245.33.124 | 10.4.2.36) (shards: 30)

OS / Image: `ami-01edd05a94c7ebf24 ami-062ec7921f7911f05 ami-0131a575da50af716` (aws: eu-west-1)

Test: `longevity-lwt-24h-multidc-test`
Test id: `098c83c6-71fd-4fa3-ac6c-0ea3f0329f85`
Test name: `scylla-master/raft/longevity-lwt-24h-multidc-test`
Test config file(s):

- [longevity-lwt-24h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d007cef368b29d19563df5b4933744ae44448cb5/test-cases/longevity/longevity-lwt-24h-multidc.yaml)

## Issue description

As in the title - this is not recommended configuration.
`self.tester.reliable_replication_factor` - should be resulting in replication strategy and factors instead of simple number.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 098c83c6-71fd-4fa3-ac6c-0ea3f0329f85`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=098c83c6-71fd-4fa3-ac6c-0ea3f0329f85)
- Show all stored logs command: `$ hydra investigate show-logs 098c83c6-71fd-4fa3-ac6c-0ea3f0329f85`

## Logs:
- **db-cluster-098c83c6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/db-cluster-098c83c6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/db-cluster-098c83c6.tar.gz)
- **monitor-set-098c83c6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/monitor-set-098c83c6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/monitor-set-098c83c6.tar.gz)
- **loader-set-098c83c6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/loader-set-098c83c6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/loader-set-098c83c6.tar.gz)
- **normal-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/normal-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/normal-098c83c6.log.tar.gz)
- **summary-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/summary-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/summary-098c83c6.log.tar.gz)
- **events-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/events-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/events-098c83c6.log.tar.gz)
- **output-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/output-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/output-098c83c6.log.tar.gz)
- **debug-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/debug-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/debug-098c83c6.log.tar.gz)
- **sct-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/sct-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/sct-098c83c6.log.tar.gz)
- **error-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/error-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/error-098c83c6.log.tar.gz)
- **critical-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/critical-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/critical-098c83c6.log.tar.gz)
- **raw_events-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/raw_events-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/raw_events-098c83c6.log.tar.gz)
- **warning-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/warning-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/warning-098c83c6.log.tar.gz)
- **email_data-098c83c6.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/email_data-098c83c6.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/email_data-098c83c6.json.tar.gz)
- **argus-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/argus-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/argus-098c83c6.log.tar.gz)
- **left_processes-098c83c6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/left_processes-098c83c6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/098c83c6-71fd-4fa3-ac6c-0ea3f0329f85/20221213_005420/left_processes-098c83c6.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-lwt-24h-multidc-test/2/)

**Comment by fruch** [comment]
this was introduce long ago, and even before that it was hardcode to 3
https://github.com/scylladb/scylla-cluster-tests/pull/2480

yes, using network strategy is more accurate and realistic
but question is, you didn't to mention what exactly happens if it uses simple strategy  ? it fails ? in which way ?

**Comment by soyacz** [comment]
When using simple startegy, warning is shown in scylla logs. I don't think this is critical, but using not recommended (and non realistic) scenarios should be fixed.
