### ISSUE TITLE
GKE clusters are not getting cleaned by clean-resources

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5566]
5/8 of last weekly runs of GKE job, didn't cleaned up their cluster

https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke/

```
20:47:45  Post behavior destroy for k8s_cluster. Clean resources
20:47:48  There are no instances to remove in AWS region eu-west-1

...

20:48:02  There are no ELBs to remove in AWS region us-west-2
20:48:05  There are no clusters to remove in GKE
20:48:09  Found following orphaned GKE disks: {}
20:48:25  There are no clusters to remove in EKS
20:48:30  There are no instances to remove in GCE
20:48:38  There are no instances to remove in GCE
20:48:49  ssh-agent started already:
20:48:49  		SSH_AUTH_SOCK=/tmp/ssh-C5zgjPV9rZSV/agent.88
20:48:49  		SSH_AGENT_PID=89
20:49:00  There are no resources to clean in Docker
20:49:00  Resources for {'TestId': 'ae47e6db-28d8-4d7a-b3f9-ce858e2c8d08'} have cleaned
20:49:00  Cleaning SSH agent
20:49:00  Agent pid 1070671 killed
20:49:00  + echo 'Finished cleaning resources.'
20:49:00  Finished cleaning resources.
```

manually doing the cleanup (from my laptop) base on the test_id worked

until we figure this out, I've disabled the weekly job

**Comment by vponomaryov** [comment]
Found the root cause, will work on the solution.

**Comment by fruch** [comment]
Damn, I've commented on the wrong issue

https://github.com/scylladb/scylla-cluster-tests/issues/5516#issuecomment-1374540448

I think we need to backport os.env context manager from python 3.11

**Comment by fruch** [comment]
I've confused it with chdir context manager the was introduced in 3.11


We can use something like this:

https://gist.github.com/igniteflow/7267431?permalink_comment_id=4314590#gistcomment-4314590

**Comment by vponomaryov** [comment]
2 solutions available as a fix for it:
Israel's: https://github.com/scylladb/scylla-cluster-tests/pull/5657
My: https://github.com/scylladb/scylla-cluster-tests/pull/5661
