### ISSUE TITLE
"cqlsh.py: error: no such option: --cloudconf" error running K8S functional tests

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5577]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: cb4de7ee-efa4-4c9c-b90a-87186bcc71a1
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-k8s-local-kind-aws/201

### Description

After merge of the https://github.com/scylladb/scylla-cluster-tests/pull/5494 we started getting following error running K8S functional tests:
```
E           Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspaces" --cloudconf /tmp/tmp4qia359p.yaml'
E                                                                                                 
E           Exit code: 2                                                                          
E                                                                                                 
E           Stdout:                                                                               
E                                                                                                 
E                                                                                                 
E                                                                                                 
E           Stderr:                                                                               
E                                                                                                 
E           Usage: cqlsh.py [options] [host [port]]                                               
E                                                                                                 
E           cqlsh.py: error: no such option: --cloudconf                                          
                                                                                                  
/usr/local/lib/python3.10/site-packages/invoke/runners.py:509: UnexpectedExit
```

Looks like that PR is missing the new cqlsh version installation that supports the serverless feature.

### Steps to Reproduce

1. Run K8S functional tests using latest SCT mater version
2. See error

**Expected behavior:** cqlsh must be used of the proper version that supports serverless feature.

**Actual behavior:** fails with unknown `--cloudconf` option.

**Comment by fruch** [comment]
This cqlsh option is available only in master

**Comment by vponomaryov** [comment]
> This cqlsh option is available only in master

Why then we enabled it by default in SCT?

**Comment by fruch** [comment]
> > This cqlsh option is available only in master
> 
> Why then we enabled it by default in SCT?

cause I want to weekly runs to run with the serverless options.

we can add a check for the cqlsh option, that would verify scylla version, before using it.
