### ISSUE TITLE
Fail to download scylla repo file from s3 due to SSL_ERROR_SYSCALL error

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5580]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

Sometimes fails the test at early stages - wasting test run and time for investigation

## How frequently does it reproduce?

This is the first time - among so many upgrade tests, I can say - very rarely.

## Installation details

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-8-db-node-062da4b3-0-4 (35.237.191.2 | 10.142.0.173) (shards: -1)
- rolling-upgrade--centos-8-db-node-062da4b3-0-3 (35.231.72.210 | 10.142.0.169) (shards: -1)
- rolling-upgrade--centos-8-db-node-062da4b3-0-2 (34.139.134.95 | 10.142.0.159) (shards: -1)
- rolling-upgrade--centos-8-db-node-062da4b3-0-1 (35.185.39.25 | 10.142.0.155) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-test`
Test id: `062da4b3-0721-4ab8-af97-0267e10889bb`
Test name: `enterprise-2022.1/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7d9fbadde7b6a3087117585b15b683ff2a4b6bb3/test-cases/upgrades/rolling-upgrade.yaml)

When doing scylla setup before upgrade test, error appeared when downloading repo file from s3:
```
Command: 'sudo curl -o /etc/yum.repos.d/scylla.repo -L https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-2021.1.repo'
Exit code: 35
Stdout:
Stderr:
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to s3.amazonaws.com:443
```
I see it for the first time, I don't think is critical or often but when reappears we need to think of solution to this issue (so it is not failing test, by e.g. retries)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 062da4b3-0721-4ab8-af97-0267e10889bb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=062da4b3-0721-4ab8-af97-0267e10889bb)
- Show all stored logs command: `$ hydra investigate show-logs 062da4b3-0721-4ab8-af97-0267e10889bb`

## Logs:
- **db-cluster-062da4b3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/db-cluster-062da4b3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/db-cluster-062da4b3.tar.gz)
- **monitor-set-062da4b3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/monitor-set-062da4b3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/monitor-set-062da4b3.tar.gz)
- **loader-set-062da4b3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/loader-set-062da4b3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/loader-set-062da4b3.tar.gz)
- **sct-runner-062da4b3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/sct-runner-062da4b3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/062da4b3-0721-4ab8-af97-0267e10889bb/20221217_061051/sct-runner-062da4b3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-centos8-test/38/)
</details>

**Comment by fruch** [comment]
Probably a networking issue.

We can put retry on those run calls, it should be harmless. (Not that it would completely solve any such issue)

**Comment by fruch** [comment]
> Probably a networking issue.
> 
> We can put retry on those run calls, it should be harmless. (Not that it would completely solve any such issue)
> 
> 

Also we can use curl own retries

**Comment by soyacz** [comment]
> > Probably a networking issue.
> > We can put retry on those run calls, it should be harmless. (Not that it would completely solve any such issue)
> 
> Also we can use curl own retries

Yes, I created quick PR for it: https://github.com/scylladb/scylla-cluster-tests/pull/5583

**Comment by fruch** [comment]
Seems like

https://github.com/scylladb/scylla-cluster-tests/issues/5580

Fixes this issue
