### ISSUE TITLE
kubectl errors when working with eks

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5607]
I tried to play around with EKS by running test from local machine. It failed with kubectl error after creating EKS cluster (unfortunately I lost log msg). When I tried to play around with it manually by:
```
>: ~/repos/scylla-cluster-tests$ aws eks --region eu-north-1 update-kubeconfig --name operator-many-clients-ls-268d8379
Added new context arn:aws:eks:eu-north-1:*:cluster/operator-many-clients-ls-268d8379 to /home/ls/.kube/config
>:~/repos/scylla-cluster-tests$ kubectl get pods
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

```

From investigation I found this might be related to outdated `awscli`. After upgrade it worked.

We should update `awscli`, which requires also upgrade in `boto3`.

**Comment by fruch** [comment]
Go for it

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5685
