### ISSUE TITLE
test_deploy_helm_with_default_values is failing on EKS, since we can't use EBS

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5641]
Since we move to K8S v1.24, we don't have EBS working, and functional test `test_deploy_helm_with_default_values` is
failing as waiting for pods to be up, but they can't since the default configuration is trying to use EBS:

```
>           raise UnexpectedExit(result)
E           invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
E
E           Command: 'kubectl --cache-dir=/home/ubuntu/sct-results/20230104-111022-805064/.kube/http-cache --namespace=t-default-values wait --timeout=1m --all --for=condition=Ready pod'
E
E           Exit code: 1
E
E           Stdout:
E
E
E
E           Stderr:
E
E           error: timed out waiting for the condition on pods/t-default-values-scylla-us-east-1-us-east-1a-0
/usr/local/lib/python3.10/site-packages/invoke/runners.py:509: UnexpectedExit
```

**Comment by fruch** [comment]
@vponomaryov what do you think, should we skip until then ? or maybe we could alter the configuration to use local disk as the rest of the functional test ?

**Comment by fruch** [comment]
> > @vponomaryov what do you think, should we skip until then ? or maybe we could alter the configuration to use local disk as the rest of the functional test ?
> 
> We must have some working default storage class. We will be able to use it in this test and minio too.

I'm not sure I understood your answer, current  situation is that the default storage isn't working for us in EKS (when using 1.23+), that's a given (under we'll figure how to address it), question is now, show we disable or bypass it to avoid confusion.

**Comment by vponomaryov** [comment]
> > > @vponomaryov what do you think, should we skip until then ? or maybe we could alter the configuration to use local disk as the rest of the functional test ?
> > 
> > 
> > We must have some working default storage class. We will be able to use it in this test and minio too.
> 
> I'm not sure I understood your answer, current situation is that the default storage isn't working for us in EKS (when using 1.23+), that's a given (under we'll figure how to address it), question is now, show we disable or bypass it to avoid confusion.

As fast solution I am ok to skip the test, but we should make the default storage class exist and work.
