### ISSUE TITLE
[Upgrade-test] enable `upgrade_sstables`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5705]
since commit https://github.com/scylladb/scylla-cluster-tests/commit/b11e26aa9922ff0ca80c0d6932711ae85f5e1138, the `upgrade_sstables` flag seems to be turned off

we should turn it back on by default, and test that it's still working

we should enable it only for the main rolling upgrade test, and not for all the others

**Comment by roydahan** [comment]
It's off only for generic_rolling_upgrade, not in the regular one.

**Comment by roydahan** [comment]
But it's set to true in the regular upgrade it doesn't even take it from the yaml config.

**Comment by fruch** [comment]
> But it's set to true in the regular upgrade it doesn't even take it from the yaml config.

so that's also bad, we have a flag that affect only some of the upgrade test and some not.

**Comment by fruch** [comment]
seems it's doesn't work as expected in regular case, but it's still confusing that this value didn't had a default.
