### ISSUE TITLE
ClusterHealthValidatorEvent raises false negative on K8S multitenant setups

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5745]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: d0497796-6633-4854-b671-1663a4886244
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-multitenant-eks/49/consoleFull

### Description

If we define `cluster_health_check` option with `true` value, setup K8S to be multitenant and run any of exclusive K8S nemesis which disrupt K8S nodes then we have a race to catch a false negative error like following:

```
13:41:52  < t:2023-01-31 11:41:51,855 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-01-31 11:41:51.853: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=09533440-7e7e-4a36-bfd5-7f0c233291aa during_nemesis=TerminateKubernetesHostThenReplaceScyllaNode: type=NodeStatus node=sct-cluster-2-us-east1-b-us-east1-0 error=Current node Node sct-cluster-2-us-east1-b-us-east1-0 [10.0.1.39 | 10.0.1.52] (seed: False). Node Node sct-cluster-2-us-east1-b-us-east1-2 [10.0.1.140 | 10.0.1.163] (seed: False) (not target node) status is DN
```

This health checker caught a failed pod from a neighbour Scylla cluster which was also `expectedly` disrupted.
And it caused a `critical SCT event`.

### Steps to Reproduce

1. Setup multitenant K8S cluster
2. Enable cluster health validation feature
3. Run exclusive K8S nemesis several times

**Expected behavior:** ClusterHealthValidatorEvent must understand K8S multitenant setup.

**Actual behavior:** ClusterHealthValidatorEvent generates false negative result.

**Comment by fruch** [comment]
@vponomaryov I'm not following how this would happen.

I thought we are blocking all other nemesis when doing exclusive ones ? are we not blocking the health checks as well ? 

If we don't have the healthcheck under the lock, we should fix it, and it should be under the lock as well

**Comment by fruch** [comment]
> > @vponomaryov I'm not following how this would happen.
> > I thought we are blocking all other nemesis when doing exclusive ones ? are we not blocking the health checks as well ?
> > If we don't have the healthcheck under the lock, we should fix it, and it should be under the lock as well
> 
> We have lock for nemesis logic only. Health-checks are separate.
> 
> And the problem with health check can and must be solved without regards to the lock used by nemesis. The health-checks logic must be smart enough to detect that really unexpected nodes are down. In current case it think that neighbour Scylla pods were `unexpected`, but it is not so because we use multitenancy.
> 
> So, the proper solution is to really run health checks during the nemesis, but it must support more than 1 Scylla pod/node as a target or `expected` to be disrupted.

again assuming the healthcheck would be under the lock, I don't understand why we need `expected` to be disrupted.

while under the lock, we have only one nemesis that disrupts a k8s node, once it's ends everything should be up and normal. and only then other nemesis are free to roam around.

I'm not sure I understand why the healthcheck need to be smarter, we are not running multiple nemesis threads in the same time with the one breaking the k8s node.

i.e. the lock is exactly for this reason, to prevent unexpected flows, I think we just need to fix it to include healthcheck.

**Comment by vponomaryov** [comment]
@fruch 

Ok, I see how exactly you do not get the real bug situation.
The bug described here is triggered by one single `exclusive` nemesis even when you use `noop monkey` for all other tenants.
So, since it is triggered even by one nemesis, it is unrelated to a lock mechanism, at all.

Health checker assumes that all the nodes are `UN` which are not `target` ones.
But the problem is that when we kill and K8S node in a multitenant setup we kill more than 1 Scylla pod.
And those all other pods which get killed as `neighbour` ones are considered by the health checker as unexpected breakage and generate `critical event`. But it is `totally expected` in our multitenant case.

**Comment by fruch** [comment]
Health checker run before and after a nemesis and should be checking it's own cluster only.

When we define exclusive I assume it hold a lock and no other nemesis or healthchecks are running, and when it would release it I expect all pods to be operational and ready for the next nemesis.

In case of noop I would expect it to be exactly the same

I agree we need to wait for the neighbors, but I think it should be part of the nemesis themselves and not part of the health checks.

**Comment by fruch** [comment]
@vponomaryov so we agreed we need the lock to cover the healthcheck as well ?

**Comment by vponomaryov** [comment]
> @vponomaryov so we agreed we need the lock to cover the healthcheck as well ?

Or lock or proper marking with `nemesis target` labels of all the affected pods.

**Comment by fruch** [comment]
> > @vponomaryov so we agreed we need the lock to cover the healthcheck as well ?
> 
> Or lock or proper marking with `nemesis target` labels of all the affected pods.

Let's go with the lock, which should be simpler option

**Comment by vponomaryov** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/5972

**Comment by vponomaryov** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5972 is merged
