### ISSUE TITLE
sct-runner loose network connectivity when too many event are generated

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5748]
## Issue description

In some error cases of scylla, SCT get millions of db log lines that generate too many events,
in turn it fill the sct-runner memory and the system OOM eventfully kills the sct-runner and 
make it unreachable,

## Impact

it makes make collection, and clean resources phases to fail.
and investigation of the core issue becomes very hard (since log collection need to be manual)  

## How frequently does it reproduce?

Seems like it's affect the 50gb 3days weekly run, for the last two runs 

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `5.3.0~dev-20230126.a0ff33e77774` with build-id `575b7a0891506801aeb1c05412a6eac011a0eda4`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-91f4614d-7 (3.95.18.168 | 10.12.9.13) (shards: -1)
- longevity-tls-50gb-3d-master-db-node-91f4614d-6 (52.55.169.59 | 10.12.8.241) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-91f4614d-5 (54.226.109.147 | 10.12.10.123) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-91f4614d-4 (54.196.151.77 | 10.12.9.157) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-91f4614d-3 (54.234.230.24 | 10.12.11.159) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-91f4614d-2 (54.167.109.174 | 10.12.8.179) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-91f4614d-1 (54.158.3.176 | 10.12.10.158) (shards: 14)

OS / Image: `ami-0a8fd7e11139b6ca1` (aws: us-east-1)

Test: `longevity-50gb-3days`
Test id: `91f4614d-70d0-4ae2-9c9b-b9aa15d603bd`
Test name: `scylla-master/longevity/longevity-50gb-3days`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ce782d42d1aea97b0366fb51c80b70d521fdb749/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 91f4614d-70d0-4ae2-9c9b-b9aa15d603bd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=91f4614d-70d0-4ae2-9c9b-b9aa15d603bd)
- Show all stored logs command: `$ hydra investigate show-logs 91f4614d-70d0-4ae2-9c9b-b9aa15d603bd`

## Logs:
- **monitor-set-91f4614d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230128_213155/monitor-set-91f4614d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230128_213155/monitor-set-91f4614d.tar.gz)
- **loader-set-91f4614d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230128_213155/loader-set-91f4614d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230128_213155/loader-set-91f4614d.tar.gz)
- **monitor-set-91f4614d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230129_164639/monitor-set-91f4614d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230129_164639/monitor-set-91f4614d.tar.gz)
- **loader-set-91f4614d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230129_164639/loader-set-91f4614d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/91f4614d-70d0-4ae2-9c9b-b9aa15d603bd/20230129_164639/loader-set-91f4614d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/178/)
</details>

**Comment by fruch** [comment]
I think we need some kind of rate limiting for similar enough events, this is a recurring pattern that some core changes starts printing lot of exceptions, and SCT can't handle it.

we implemented something for sending into grafana,  but we probably need it earlier at the pipeline of events creation

**Comment by juliayakovlev** [comment]
https://argus.scylladb.com/test/a2b90d5a-c79b-4f9d-a9a7-98974e88c866/runs?additionalRuns[]=91f4614d-70d0-4ae2-9c9b-b9aa15d603bd

**Comment by ilya-rarov** [comment]
@fruch I've managed to download `~/sct-results/latest` from the runner but the files are too big (even compressed) to attach here. Where should I put them?

**Comment by ilya-rarov** [comment]
> `S3`. Just run the SCT command for collecting logs the same way as it was expected to in the job.
Thanks you @vponomaryov! Updated my comment about failure with the links to the logs.

**Comment by roydahan** [comment]
Closing for now, we don't have the issue anymore.
