### ISSUE TITLE
Division by zero error in benchmark code when running on Azure/GCP

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5751]
```
< t:2023-01-30 06:56:43,791 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=division by zero
< t:2023-01-30 06:56:43,793 f:grafana.py      l:80   c:sdcm.sct_events.grafana p:DEBUG > GrafanaEventAggregator start a new time window (90 sec)
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 153, in wrapper
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 741, in setUp
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1720, in init_resources
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self.get_cluster_azure(loader_info=loader_info, db_info=db_info,
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1050, in get_cluster_azure
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self.db_cluster = ScyllaAzureCluster(image_id=azure_image,
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_azure.py", line 248, in __init__
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     super().__init__(
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3730, in __init__
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     super().__init__(*args, **kwargs)
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_azure.py", line 171, in __init__
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     super().__init__(cluster_uuid=cluster_uuid,
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3139, in __init__
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self.run_node_benchmarks()
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3592, in run_node_benchmarks
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self.node_benchmark_manager.run_benchmarks()
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 128, in run_benchmarks
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     self._compare_results()
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 187, in _compare_results
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     averages = self._get_average_results(es_docs=self._get_benchmark_results(instance_type))
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 247, in _get_average_results
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR >     return Averages(sysbench_eps=sum(eps) / len(eps),
< t:2023-01-30 06:56:43,789 f:tester.py       l:160  c:sdcm.tester          p:ERROR > ZeroDivisionError: division by zero

```

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-f94d1909-eastus-6 (172.173.133.78 | 10.0.0.10) (shards: -1)
- longevity-10gb-3h-master-db-node-f94d1909-eastus-5 (172.173.133.50 | 10.0.0.9) (shards: -1)
- longevity-10gb-3h-master-db-node-f94d1909-eastus-4 (172.173.133.27 | 10.0.0.8) (shards: -1)
- longevity-10gb-3h-master-db-node-f94d1909-eastus-3 (172.173.132.231 | 10.0.0.7) (shards: -1)
- longevity-10gb-3h-master-db-node-f94d1909-eastus-2 (172.173.132.219 | 10.0.0.6) (shards: -1)
- longevity-10gb-3h-master-db-node-f94d1909-eastus-1 (172.173.132.211 | 10.0.0.5) (shards: -1)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.3.0-dev-x86_64-2023-01-30T07-42-47` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `f94d1909-4968-4d3a-9d49-9df2a7abda6b`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5d63c03fb0d46bc3ded2b714ab203ef133926920/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f94d1909-4968-4d3a-9d49-9df2a7abda6b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f94d1909-4968-4d3a-9d49-9df2a7abda6b)
- Show all stored logs command: `$ hydra investigate show-logs f94d1909-4968-4d3a-9d49-9df2a7abda6b`

## Logs:
- **db-cluster-f94d1909.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/db-cluster-f94d1909.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/db-cluster-f94d1909.tar.gz)
- **sct-runner-f94d1909.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/sct-runner-f94d1909.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/sct-runner-f94d1909.tar.gz)
- **monitor-set-f94d1909.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/monitor-set-f94d1909.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/monitor-set-f94d1909.tar.gz)
- **loader-set-f94d1909.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/loader-set-f94d1909.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/loader-set-f94d1909.tar.gz)
- **parallel-timelines-report-f94d1909.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/parallel-timelines-report-f94d1909.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f94d1909-4968-4d3a-9d49-9df2a7abda6b/20230130_065718/parallel-timelines-report-f94d1909.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/155/)
</details>

**Comment by fgelcer** [comment]
same happens for GCE

**Comment by soyacz** [comment]
seems https://github.com/scylladb/scylla-cluster-tests/commit/cb3b570fe504b04c21b0522ec68766c7615f0472#diff-b549070b601e5c07aa6d688afada77a2d3411de78564f8bec3186a0e43b79614 broke it 
cc @aleksbykov

**Comment by soyacz** [comment]
@aleksbykov there are errors in sct.log related putting to ES:
```
< t:2023-01-30 06:56:42,724 f:es.py           l:35   c:sdcm.es              p:INFO  > BODY: {'test_id': 'f94d1909-4968-4d3a-9d49-9df2a7abda6b', 'node_instance_type': '', 'node_name': 'longevity-10gb-3h-master-db-node-f94d1909-eastus-4', 'sysbench_events_per_second': 12515.21, 'sysbench_latency_min': 0.34, 'sysbench_latency_max': 11.16, 'sysbench_latency_avg': 0.64, 'sysbench_latency_p95': 0.64, 'sysbench_thread_fairness_avg': 187729.125, 'sysbench_thread_fairness_stdev': 140.86, 'sysbench_thread_fairness_time_avg': 119.9715, 'sysbench_thread_fairness_time_stdev': 0.0}
< t:2023-01-30 06:56:42,728 f:base.py         l:274  c:elasticsearch        p:INFO  > PUT https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/node_benchmarks [status:400 request:0.004s]
< t:2023-01-30 06:56:42,728 f:base.py         l:277  c:elasticsearch        p:DEBUG > > None
< t:2023-01-30 06:56:42,728 f:base.py         l:278  c:elasticsearch        p:DEBUG > < {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [node_benchmarks/jewcpffpRu-WXLaaWL4C6g] already exists","index_uuid":"jewcpffpRu-WXLaaWL4C6g","index":"node_benchmarks"}],"type":"resource_already_exists_exception","reason":"index [node_benchmarks/jewcpffpRu-WXLaaWL4C6g] already exists","index_uuid":"jewcpffpRu-WXLaaWL4C6g","index":"node_benchmarks"},"status":400}
```
It looks later data is not properly retrieved and causing errors.
@aleksbykov I'm right? Any ideas how to quickly fix it?

**Comment by aleksbykov** [comment]
Yes, looks so. It seems that it attempts to create index, whlie it already exists. And it strange, there is no change in code for creating index:
```
    def _create_index(self, index):
        self.indices.create(index=index, ignore=400)  # pylint: disable=unexpected-keyword-arg
```

**Comment by fruch** [comment]
> Yes, looks so. It seems that it attempts to create index, whlie it already exists. And it strange, there is no change in code for creating index:
> 
> ```
>     def _create_index(self, index):
>         self.indices.create(index=index, ignore=400)  # pylint: disable=unexpected-keyword-arg
> ```

why the benchmark need to create an index ? should it already have an index, like all the time ?

**Comment by fruch** [comment]
seem like we try to create index, on every doc we create:  🤦🏼  
```
    def _create_index(self, index):
        self.indices.create(index=index, ignore=400)  # pylint: disable=unexpected-keyword-arg

    def create_doc(self, index, doc_type, doc_id, body):
        """
        Add document in json format
        """
        LOGGER.info('Create doc')
        LOGGER.info('INDEX: %s', index)
        LOGGER.info('DOC_TYPE: %s', doc_type)
        LOGGER.info('DOC_ID: %s', doc_id)
        LOGGER.info('BODY: %s', body)
        self._create_index(index)
        if self.exists(index=index, doc_type=doc_type, id=doc_id):
            self.update(index=index, doc_type=doc_type, id=doc_id, body={'doc': body})
        else:
            self.create(index=index, doc_type=doc_type, id=doc_id, body=body)
```

I think you are braking the wrong tree, it's probably happens on every run of the benchmark (i.e. failing to create the index, since it's already exists)

**Comment by fruch** [comment]
we need to change this ASAP...
```
Cloning from https://github.com/KnifeyMoloko/cassandra-fio.git...
```

**Comment by fruch** [comment]
I think I understand the reason of the failures, the benchmarks too more the 5min, so the cassandra-fio one was still running, while we are collecting results
 
```
    def run_benchmarks(self):
        try:
            parallel = ParallelObject(self._benchmark_runners, timeout=300)
            parallel.run(lambda x: x.run_benchmarks(), ignore_exceptions=True)
        except TimeoutError as exc:
            LOGGER.warning("Run into TimeoutError during running benchmarks. Exception:\n%s", exc)
        self._collect_benchmark_output()
        self._compare_results()
```


@soyacz first order of business here is to extend the timeout of the parallel, since this inclued the installation and the running of those tools, and it can take time, since it's compiled them from source

2nd thing, we should be taking the code of `casssandra-fio` from a private fork, it should be or official or scylla's fork (we should create a fork it not created)

**Comment by roydahan** [comment]
Did we contribute to that repo? if not, we don't need a fork and continue using cassandra's one.

**Comment by aleksbykov** [comment]
> I think I understand the reason of the failures, the benchmarks too more the 5min, so the cassandra-fio one was still running, while we are collecting results

But in sct log there is no log message with timeout exception

**Comment by soyacz** [comment]
> @soyacz first order of business here is to extend the timeout of the parallel, since this inclued the installation and the running of those tools, and it can take time, since it's compiled them from source

Yes, with high probability your'e right - I didn't catch it as I was looking for warning message which can't be thrown due to ignoring exceptions. I created quick fix, as I must be off for today and get back on Tuesday: https://github.com/scylladb/scylla-cluster-tests/pull/5763

**Comment by aleksbykov** [comment]
@fruch @soyacz could you review pr, it should fix DivisionByZero
