### ISSUE TITLE
chaos-mesh install fail on 14 tenants test [ValueError: filedescriptor out of range in select()]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5789]
## Issue description

- [x] This issue is a regression.

Running the 14 tenants use case is failing on chaos mesh installation with
```
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 154, in wrapper
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 745, in setUp
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     self.k8s_cluster.chaos_mesh.initialize()
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/k8s/chaos_mesh.py", line 74, in initialize
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     self._k8s_cluster.helm("repo add chaos-mesh https://charts.chaos-mesh.org")
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/k8s/__init__.py", line 562, in helm
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     res = self._helm_container.exec_run(["sh", "-c", cmd])
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 198, in exec_run
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     exec_output = self.client.api.exec_start(
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     return f(self, resource_id, *args, **kwargs)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/api/exec_api.py", line 169, in exec_start
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     return self._read_from_socket(res, stream, tty=tty, demux=demux)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 422, in _read_from_socket
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     return consume_socket_output(gen, demux=demux)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/socket.py", line 137, in consume_socket_output
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     return six.binary_type().join(frames)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 416, in <genexpr>
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     gen = (data for (_, data) in gen)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/socket.py", line 94, in frames_iter_no_tty
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     (stream, n) = next_frame_header(socket)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/socket.py", line 66, in next_frame_header
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     data = read_exactly(socket, 8)
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/socket.py", line 51, in read_exactly
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     next_data = read(socket, n - len(data))
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/utils/socket.py", line 31, in read
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR >     select.select([socket], [], [])
< t:2023-02-08 16:05:08,821 f:tester.py       l:161  c:sdcm.tester          p:ERROR > ValueError: filedescriptor out of range in select()
```
 
## Impact

we can't run the test case

## How frequently does it reproduce?

It's happens all the time

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-central-1)

Test: `longevity-scylla-operator-12h-multitenant-eks`
Test id: `5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9`
Test name: `scylla-staging/fruch/longevity-scylla-operator-12h-multitenant-eks`
Test config file(s):

- [longevity-scylla-operator-12h-multitenant-14-clients.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a77fec454b16de3eb27071a6f2f3ce6e92e88bf1/test-cases/scylla-operator/longevity-scylla-operator-12h-multitenant-14-clients.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9)
- Show all stored logs command: `$ hydra investigate show-logs 5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9`

## Logs:
- **db-cluster-5a9508fa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/db-cluster-5a9508fa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/db-cluster-5a9508fa.tar.gz)
- **sct-runner-5a9508fa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/sct-runner-5a9508fa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/sct-runner-5a9508fa.tar.gz)
- **monitor-set-5a9508fa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/monitor-set-5a9508fa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/monitor-set-5a9508fa.tar.gz)
- **kubernetes-5a9508fa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/kubernetes-5a9508fa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a9508fa-4e39-4cd7-9e1d-9c1c3d7742f9/20230208_160939/kubernetes-5a9508fa.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-12h-multitenant-eks/9/)
</details>

**Comment by fruch** [comment]
@vponomaryov have you ever seen something similar ?

@soyacz I might guess we don't have enough file descriptors in this case... but I'm not quite sure

**Comment by vponomaryov** [comment]
> @vponomaryov have you ever seen something similar ?
> 
> @soyacz I might guess we don't have enough file descriptors in this case... but I'm not quite sure

No. I guess last time I ran 14 clients was when chaos-mesh hadn't been merged yet into SCT.

**Comment by soyacz** [comment]
The problem looks deeper than just 'installation failure' - there's glibc `select()` a limit in linux hardcoded to 1024 and can't be fixed easily.
I need to dive deep why we use that high number - maybe we don't close somwhere resources properly?

Anyway I don't see a quick fix for it - better disable chaos-mesh for multitenant tests for the meantime.

**Comment by fruch** [comment]
> The problem looks deeper than just 'installation failure' - there's glibc `select()` a limit in linux hardcoded to 1024 and can't be fixed easily. Some discussion here: https://stackoverflow.com/questions/7976388/increasing-limit-of-fd-setsize-and-select
> I need to dive deep why we use that high number - maybe we don't close somwhere resources properly?
> 

It does seems we are using too many sockets in the call itself, I'm guessing it's some global resource, and we are "leaking" somewhere else, but it menifests here.

> Anyway I don't see a quick fix for it - better disable chaos-mesh for multitenant tests for the meantime.
> 

That's what I'm doing.

**Comment by soyacz** [comment]
This issue is related to update of fabric/invoke library ([already reverted](https://github.com/scylladb/scylla-cluster-tests/pull/5788)). I retried the test after revert and it passes now:
```
14:32:58  < t:2023-02-13 13:32:58,467 f:chaos_mesh.py   l:73   c:sdcm.utils.k8s.chaos_mesh p:INFO  > Installing chaos-mesh on sct-cluster k8s cluster...
14:33:31  < t:2023-02-13 13:33:29,998 f:chaos_mesh.py   l:102  c:sdcm.utils.k8s.chaos_mesh p:INFO  > chaos-mesh installed successfully on sct-cluster k8s cluster.
```
in build: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/multitenant-eks/3/
