### ISSUE TITLE
`get_nodes_status` generates too many requests to cloud api

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5812]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

ClusterHealthValidator started publishing error events like:
```
2023-02-14 21:25:11.262: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=948c165d-1824-41fa-acb5-5dda55483624: type=NodeStatus node=longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-3 error=Current node Node longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-3 [3.252.166.103 | 10.4.3.176] (seed: True). The node Node longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-1 [34.240.130.155 | 10.4.1.211] (seed: True) exists in the gossip but doesn't exist in the nodetool.status
```

The reason for it is that `get_nodes_status` we try to get `Node` object by finding it by ip 
`node := self.parent_cluster.find_node_by_ip(node_ip)`
And finding node by ip triggers `_refresh_instance_state` which does `ec2_instance_wait_public_ip` - making queries to AWS
When we run many jobs in parallel we deplete quota on these requests and cause these errors.

I think we could try first get node by ip without refreshing

## Impact

error events in logs. Possibly can lead to fail ClusterHealthValidation

## How frequently does it reproduce?

Often when running all nemesis tests at once. 

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `5.2.0~rc1-20230207.8ff4717fd010` with build-id `78fbb2c25e9244a62f57988313388a0260084528`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-3 (3.252.166.103 | 10.4.3.176) (shards: 2)
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-2 (34.245.61.44 | 10.4.1.56) (shards: 2)
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-249f30ed-1 (34.240.130.155 | 10.4.1.211) (shards: 2)

OS / Image: `ami-05e1d6aa4f71f3f25` (aws: eu-west-1)

Test: `longevity-5gb-1h-SoftRebootNodeMonkey-aws-test`
Test id: `249f30ed-7007-4b8e-a320-1207ebca5e5d`
Test name: `scylla-5.2/nemesis/longevity-5gb-1h-SoftRebootNodeMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-SoftRebootNodeMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b75ec6c71b99497afbe3bcc89818eadb8d60a9e8/test-cases/nemesis/longevity-5gb-1h-SoftRebootNodeMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 249f30ed-7007-4b8e-a320-1207ebca5e5d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=249f30ed-7007-4b8e-a320-1207ebca5e5d)
- Show all stored logs command: `$ hydra investigate show-logs 249f30ed-7007-4b8e-a320-1207ebca5e5d`

## Logs:
- **db-cluster-249f30ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/db-cluster-249f30ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/db-cluster-249f30ed.tar.gz)
- **sct-runner-249f30ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/sct-runner-249f30ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/sct-runner-249f30ed.tar.gz)
- **monitor-set-249f30ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/monitor-set-249f30ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/monitor-set-249f30ed.tar.gz)
- **loader-set-249f30ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/loader-set-249f30ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/loader-set-249f30ed.tar.gz)
- **parallel-timelines-report-249f30ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/parallel-timelines-report-249f30ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/249f30ed-7007-4b8e-a320-1207ebca5e5d/20230214_215652/parallel-timelines-report-249f30ed.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/nemesis/job/longevity-5gb-1h-SoftRebootNodeMonkey-aws-test/4/)
</details>

**Comment by fruch** [comment]
we need to change such a thing with great care, since the refresh there is introduced for the k8s sake.
so maybe limiting the refresh to k8s only

@vponomaryov what do you say maybe now with the ip tracker thread, we don't need those refreshes anymore ?

**Comment by soyacz** [comment]
`_refresh_instance_state` is different for each backend, K8s has own way.

`find_node_by_ip` is in a loop (for each ip address) which loops over all nodes, every time doing refresh of instance state.
First, there's no need to refresh ip address multiple times - so we could fix it on higher level - less risk.

**Comment by vponomaryov** [comment]
> we need to change such a thing with great care, since the refresh there is introduced for the k8s sake. so maybe limiting the refresh to k8s only
> 
> @vponomaryov what do you say maybe now with the ip tracker thread, we don't need those refreshes anymore ?

The presence of IP tracker thread reduces the need to use VM API.
So, it is more question to common VM case, what is needed there.

I think @soyacz is correct that the way of getting IP changes in VM case may be improved itself by removing redundancy.

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5869

**Comment by fruch** [comment]
Already merged
