### ISSUE TITLE
Issue when creating SCT runner for Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5819]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During create sct runner stage, runner is not created. Jenkins log shows:
```
05:01:55  Creating 'sct-runner-1.6-instance-75d9e3db' VM in resource group SCT-75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6-eastus-1...
05:01:55  Instance params: InstanceDefinition(name='sct-runner-1.6-instance-75d9e3db', image_id='/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCT_IMAGES-eastus/providers/Microsoft.Compute/galleries/SCT_IMAGES/images/sct-runner/versions/1.6.0', type='Standard_E2s_v3', user_name='ubuntu', tags={'RunByUser': 'timer', 'TestName': 'null', 'TestId': '75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6', 'version': 'scylla-master', 'CreatedBy': 'SCT', 'JenkinsJobTag': 'jenkins-scylla-master-rolling-upgrade-rolling-upgrade-azure-image-test-3', 'NodeType': 'sct-runner', 'keep': '16', 'keep_action': 'terminate', 'UserName': 'ubuntu', 'bastion': 'true', 'launch_time': 'February 11, 2023, 04:01:26'}, arch=<VmArch.X86: 'x86_64'>, root_disk_size=80, data_disks=None)
05:01:55  Error when sending create vm request for VM sct-runner-1.6-instance-75d9e3db: (InvalidReservedTagValue) The tag names 'TestName' have reserved tag values. The reserved tag values are: 'null, (null)'.
05:01:55  Code: InvalidReservedTagValue
05:01:55  Message: The tag names 'TestName' have reserved tag values. The reserved tag values are: 'null, (null)'.
05:01:55  Traceback (most recent call last):
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/./sct.py", line 1651, in <module>
05:01:55      cli.main(prog_name="hydra")
05:01:55    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
05:01:55      rv = self.invoke(ctx)
05:01:55    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
05:01:55      return _process_result(sub_ctx.command.invoke(sub_ctx))
05:01:55    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
05:01:55      return ctx.invoke(self.callback, **ctx.params)
05:01:55    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
05:01:55      return __callback(*args, **kwargs)
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/./sct.py", line 1510, in create_runner_instance
05:01:55      instance = sct_runner.create_instance(
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/sdcm/sct_runner.py", line 396, in create_instance
05:01:55      return self._create_instance(
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/sdcm/sct_runner.py", line 932, in _create_instance
05:01:55      self.instance = provisioner.get_or_create_instance(definition=vm_params,
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 103, in get_or_create_instance
05:01:55      return self.get_or_create_instances(definitions=[definition], pricing_model=pricing_model)[0]
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 128, in get_or_create_instances
05:01:55      v_ms = self._vm_provider.get_or_create(definitions=definitions_to_provision, nics_ids=[
05:01:55    File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test/scylla-cluster-tests/sdcm/provision/azure/virtual_machine_provider.py", line 116, in get_or_create
05:01:55      raise ProvisionError(error_to_raise)
05:01:55  sdcm.provision.provisioner.ProvisionError: (InvalidReservedTagValue) The tag names 'TestName' have reserved tag values. The reserved tag values are: 'null, (null)'.
05:01:55  Code: InvalidReservedTagValue
05:01:55  Message: The tag names 'TestName' have reserved tag values. The reserved tag values are: 'null, (null)'.
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-08-05T04-27-11Z` (azure: eastus)

Test: `rolling-upgrade-azure-image-test`
Test id: `75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/73dc21fe6b2fdd387986f9515bcdca9945002bc8/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6)
- Show all stored logs command: `$ hydra investigate show-logs 75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6`

## Logs:
- **db-cluster-75d9e3db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6/20230211_041424/db-cluster-75d9e3db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6/20230211_041424/db-cluster-75d9e3db.tar.gz)
- **sct-runner-75d9e3db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6/20230211_041424/sct-runner-75d9e3db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/75d9e3db-ae7b-45aa-a35e-d50dbb0db2f6/20230211_041424/sct-runner-75d9e3db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/3/)
</details>

**Comment by soyacz** [comment]
looks like jenkins passes word `null` to TestName value - which is forbidden.

**Comment by fruch** [comment]
> looks like jenkins passes word `null` to TestName value - which is forbidden.

rolling upgrade doesn't have test_name as param, so this is null:
```
def test_name = groovy.json.JsonOutput.toJson(params.test_name)
```

seems like e2d82f5b0efe0e38d81f0374d84ed25730e2156b isn't handle this case
we should default to empty string in case of `null`

**Comment by fruch** [comment]
> > looks like jenkins passes word `null` to TestName value - which is forbidden.
> 
> rolling upgrade doesn't have test_name as param, so this is null:
> 
> ```
> def test_name = groovy.json.JsonOutput.toJson(params.test_name)
> ```
> 
> seems like [e2d82f5](https://github.com/scylladb/scylla-cluster-tests/commit/e2d82f5b0efe0e38d81f0374d84ed25730e2156b) isn't handle this case we should default to empty string in case of `null`

or to some string, otherwise the command would fail

**Comment by soyacz** [comment]
PR fixes issue with null tags. Shall we fix this test_name too?

**Comment by fruch** [comment]
> PR fixes issue with null tags. Shall we fix this test_name too?

we should, should be easy fix

```groovy
def test_name = groovy.json.JsonOutput.toJson(params.get('test_name', ''))
```

**Comment by soyacz** [comment]
> > PR fixes issue with null tags. Shall we fix this test_name too?
> 
> we should, should be easy fix
> 
> ```groovy
> def test_name = groovy.json.JsonOutput.toJson(params.get('test_name', ''))
> ```

I added separate PR for it
