### ISSUE TITLE
add_node after decommission is broken 

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#582]
shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Trying to replace_address with auto_bootstrap disabled will not work, check your configuration)

The yaml of the newly added node contains the following line:
replace_address: 172.16.99.80

This shouldn't happen while adding a new node after decommission, only after remove and replace node.

**Comment by roydahan** [comment]
@amoskong this is probably caused by @bentsi but tomorrow is Friday and this is failing the the new longevity test.
Can you please take a look and try to push a fix to master and to my fork (PR) for new longevity?

**Comment by roydahan** [comment]
This is where the issue is:
    def _add_and_init_new_cluster_node(self, old_node_private_ip):
        self.log.info("Adding new node to cluster...")
        new_node = self.cluster.add_nodes(count=1, dc_idx=self.target_node.dc_idx)[0]
        new_node.replacement_node_ip = old_node_private_ip
        self.cluster.wait_for_init(node_list=[new_node], timeout=30)
        self.reconfigure_monitoring()
        return new_node

Indeed by @bentsi

**Comment by bentsi** [comment]
When removing node and adding new one, there is a chance that we get the same private IP address in the new node.  I've read the #583, is the issue here in not setting `auto_bootstrap` to true?
