### ISSUE TITLE
When provisioning instances in AWS we should use scylla-test key

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#584]
Current situation is that we create a new key pair when testing in AWS cluster and we don't delete it after the test finished. For example only in `us-east-1` we have **1713** keys!!
![image](https://user-images.githubusercontent.com/5269241/41548711-682d8f74-732c-11e8-98be-25d43bc45e6d.png)
@roydahan

**Comment by baiwfg2** [comment]
@bentsi Hi. When using this tool, do I have to use AWS ? I greatly hope I can run the test locally. Is that possible ?

**Comment by bentsi** [comment]
@baiwfg2 you can run it locally using docker backend

**Comment by fruch** [comment]
we removed the code that create keys in AWS. so I consider this fixed
