### ISSUE TITLE
SCT doesn't create a Critical event when connection to all the cluster nodes fails from a driver side causing deletion of resources marked as `keep-on-failure`

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5840]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: `branch-2023.1`
* **scylla**: `2023.1.0-rc1`

### Logs
* test_id: 8e27e0ef-f6ba-4d78-bf78-a565dbd705d6
* job log: https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/EncryptionAtRest/job/EaR-longevity-replicated-200gb-6h-test/4/

### Description

In case when a Scylla driver fails to establish stable network connection to all the newly created Scylla nodes,
SCT gives up in 1 minutes and generates only `ERROR` SCT events (no `Critical` one).
It leads to the following situation on the cleanup stage:

```
10:20:51  < t:2023-02-21 08:20:51,702 f:sct_config.py   l:1774 c:sdcm.sct_config      p:INFO  > post_behavior_db_nodes: keep-on-failure
10:20:51  < t:2023-02-21 08:20:51,702 f:sct_config.py   l:1774 c:sdcm.sct_config      p:INFO  > post_behavior_k8s_cluster: keep-on-failure
10:20:51  < t:2023-02-21 08:20:51,702 f:sct_config.py   l:1774 c:sdcm.sct_config      p:INFO  > post_behavior_loader_nodes: destroy
10:20:51  < t:2023-02-21 08:20:51,702 f:sct_config.py   l:1774 c:sdcm.sct_config      p:INFO  > post_behavior_monitor_nodes: keep-on-failure
...
11:03:32  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
11:03:32  
11:03:32  ----- LAST ERROR EVENT -------------------------------------------------------
11:03:32  2023-02-21 08:54:54.063: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=93db66f5-e7ff-4c51-a9ff-542df5d7570b, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
11:03:32  File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 93, in test_custom_time
11:03:32  self.run_pre_create_schema()
11:03:32  File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 69, in run_pre_create_schema
11:03:32  self._pre_create_schema(keyspace_num, scylla_encryption_options=self.params.get(
11:03:32  File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 371, in _pre_create_schema
11:03:32  self.create_table(name='standard1', keyspace_name=keyspace_name, key_type='blob', read_repair=0.0, compact_storage=True,
11:03:32  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2216, in create_table
11:03:32  session.execute(query)
11:03:32  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1643, in execute_verbose
11:03:32  return execute_orig(*args, **kwargs)
11:03:32  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
11:03:32  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
11:03:32  cassandra.OperationTimedOut: errors={'10.4.3.218:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.3.218:9042
...
11:03:32  ================================================================================
11:03:32  FAILED :(
...
11:14:15  Post behavior keep-on-failure for db_nodes. Test run Successful. Clean resources
...
11:14:17  Going to delete 'i-02a45b7d9556c2cf7' [name=longevity-encrypt-at-rest-200gb-6h--db-node-8e27e0ef-2] 
11:14:17  Going to delete 'i-06e3d63c65313ae7a' [name=longevity-encrypt-at-rest-200gb-6h--db-node-8e27e0ef-1] 
11:14:18  Going to delete 'i-0b54573224167c72c' [name=longevity-encrypt-at-rest-200gb-6h--db-node-8e27e0ef-4] 
11:14:18  Going to delete 'i-08f6e3456da071597' [name=longevity-encrypt-at-rest-200gb-6h--db-node-8e27e0ef-3] 
...
11:14:51  Post behavior keep-on-failure for monitor_nodes. Test run Successful. Clean resources
...
11:14:54  Going to delete 'i-06cfa15436be84615' [name=longevity-encrypt-at-rest-200gb-6h--monitor-node-8e27e0ef-1] 
...
11:15:26  Going to delete Docker container <b9713dcfe1 longevity-encrypt-at-rest-200gb-6h--monitor-node-8e27e0ef-1-10.4.1.73-autossh-web_driver> on `ip-10-4-2-194'
11:15:26  Post behavior destroy for loader_nodes. Clean resources
11:15:27  Going to delete 'i-0bfa8b4bfff55a941' [name=longevity-encrypt-at-rest-200gb-6h--loader-node-8e27e0ef-1] 
11:15:27  Going to delete 'i-0f2a006580375d3d2' [name=longevity-encrypt-at-rest-200gb-6h--loader-node-8e27e0ef-2] 
```

### Steps to Reproduce

1. Create a Scylla cluster with the `2023.1.0-rc1` Scylla version
2. Wait for the connectivity error
3. See no Critical event appearence and that all the resources get deleted even when we configured post behavior to be `keep-on-failure`.

**Expected behavior:** Critical event must be created

**Actual behavior:** Only error events were created making "post_behavior" think that the test run was `successful`.

**Comment by soyacz** [comment]
Shouldn't keep-on-failure consider any ERROR event as failure? Maybe we have wrong logic in that matter?

**Comment by vponomaryov** [comment]
> Shouldn't keep-on-failure consider any ERROR event as failure? Maybe we have wrong logic in that matter?

I would expect it too. So, this bug consists of several different small parts which we definitely need to solve.

**Comment by fgelcer** [comment]
> Shouldn't keep-on-failure consider any ERROR event as failure? Maybe we have wrong logic in that matter?

i don't remember exactly the algorithm for this matter (of keeping nodes on failure), and it could be that something got broken, but IIRC the error events were not keeping the instances alive on purpose... but i don't remember details on it... perhaps @fruch and @roydahan know

**Comment by roydahan** [comment]
For this issue, It's more of a decision case than a bug.
We should decide if we want to raise a critical event for it or not and when.
I think it's much easier to re-run the test and reproduce it quite immediately (since it's the first thing that happens in the cluster) instead of leaving the cluster alive for many hours, just waiting for someone to check if and why it's not connecting.
Convince me otherwise...

**Comment by vponomaryov** [comment]
> For this issue, It's more of a decision case than a bug. We should decide if we want to raise a critical event for it or not and when. I think it's much easier to re-run the test and reproduce it quite immediately (since it's the first thing that happens in the cluster) instead of leaving the cluster alive for many hours, just waiting for someone to check if and why it's not connecting. Convince me otherwise...

Your point is clear. If it was called `keep-on-critical` then there would be much more clarity.
Here we had `failure` and `keep-on-failure` didn't work. So, obviously we have this bugreport.

Feel free to close it.

**Comment by roydahan** [comment]
Yes, I agree, but it's old naming.
