### ISSUE TITLE
`stop_service` parameter doesn't work

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#586]
When we setup stop_service to `true` in sct configure, --stop-services parameters can't be add to userdata of ec2.

**Comment by roydahan** [comment]
Not sure I understand.
If we pass it manually to the AMI in userdata, does it work?

**Comment by amoskong** [comment]
It works, the scylla-server won't start.

**Comment by bentsi** [comment]
@amoskong please close the issue if it works :)

**Comment by amoskong** [comment]
Fixed by 7cfd760cb4172600a84b1f644409cd4b5b9c523b
