### ISSUE TITLE
Hydra failed to clean resources 

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylla-cluster-tests#5860]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: qa908-extend-longevity-coverage-for-azure
* **scylla**: 5.2

### Logs
* test_id: edc55fd8-b3c8-4555-a010-4a39a32dd999
* job log: https://jenkins.scylladb.com/job/scylla-staging/job/mark/job/SCT-Individual-nemesis-azure/job/longevity-5gb-1h-RefreshBigMonkey-azure.jenkinsfile/2/execution/node/213/log/

### Description
19:39:43  There are no SGs to remove in AWS region ap-northeast-2
19:39:48  There are no instances to remove in GCE
19:39:50  There are no instances to remove in GCE
19:39:52  There are no instances to remove in GCE
19:39:54  Traceback (most recent call last):
19:39:54    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1660, in <module>
19:39:54      cli.main(prog_name="hydra")
19:39:54    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
19:39:54      rv = self.invoke(ctx)
19:39:54    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
19:39:54      return _process_result(sub_ctx.command.invoke(sub_ctx))
19:39:54    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
19:39:54      return ctx.invoke(self.callback, **ctx.params)
19:39:54    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
19:39:54      return __callback(*args, **kwargs)
19:39:54    File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
19:39:54      return f(get_current_context(), *args, **kwargs)
19:39:54    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 302, in clean_resources
19:39:54      clean_func(param, dry_run=dry_run)
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2344, in clean_resources_according_post_behavior
19:39:54      clean_cloud_resources(params | {"NodeType": node_type}, dry_run=dry_run)
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 564, in clean_cloud_resources
19:39:54      clean_instances_azure(tags_dict, dry_run=dry_run)
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1332, in clean_instances_azure
19:39:54      provisioners = AzureProvisioner.discover_regions(tags_dict.get("TestId", ""))
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 96, in discover_regions
19:39:54      return [cls(*params) for params in provisioner_params]
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 96, in <listcomp>
19:39:54      return [cls(*params) for params in provisioner_params]
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 58, in __init__
19:39:54      self._cache[v_m.name] = self._vm_to_instance(v_m)
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 185, in _vm_to_instance
19:39:54      pub_address = self._ip_provider.get(v_m.name).ip_address
19:39:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/ip_provider.py", line 80, in get
19:39:54      return self._cache[ip_name]
19:39:54  KeyError: 'longevity-5gb-1h-refreshmonkey-qa90-db-node-eastus-2-ipv4'
19:39:54  Cleaning SSH agent
19:39:54  Agent pid 1652497 killed

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen].

Resources cleaned successfully

**Actual behavior:** [What actually happened]

Script failed

**Comment by fgelcer** [comment]
@Mark-Gurevich , it happend on Azure, and it might be related to Azure resources.. could you please add this information to the issue description?

@soyacz , have you seen such issue before, or can you try to look into it?

**Comment by soyacz** [comment]
I just saw today on master happens consistently since Feb 23. Need some time to investigate.

**Comment by fgelcer** [comment]
> I just saw today on master happens consistently since Feb 23. Need some time to investigate.

only for Azure, or for all different back ends?

**Comment by soyacz** [comment]
only Azure I suppose, something with ipv-4 deletion.

**Comment by fgelcer** [comment]
> only Azure I suppose, something with ipv-4 deletion.

can you add it to your tasks, and try to figure it out when you will have some time for that?
@fruch FYI

**Comment by soyacz** [comment]
Azure Traffic Manager and DNS is deleting network interfaces before test ends (or before cleanup resources) - this leads to this kind of errors.

**Comment by yaronkaikov** [comment]
@soyacz I am not sure if it's the same issue, but i am trying to chase this https://github.com/scylladb/scylla-pkg/issues/3021 , which sound similar, let me know if you manage to figure it out

**Comment by soyacz** [comment]
> @soyacz I am not sure if it's the same issue, but i am trying to chase this [scylladb/scylla-pkg#3021](https://github.com/scylladb/scylla-pkg/issues/3021) , which sound similar, let me know if you manage to figure it out

I don't think it is the same, in SCT we hit some cache issue, and we build it in this way:
```
    def __post_init__(self):
        """Discover existing ip addresses for resource group."""
        try:
            ips = self._azure_service.network.public_ip_addresses.list(self._resource_group_name)
            for ip in ips:
                ip = self._azure_service.network.public_ip_addresses.get(self._resource_group_name, ip.name)
                self._cache[ip.name] = ip
        except ResourceNotFoundError:
            pass
```
So weather list is not getting IP, or getting it returns `ResourceNotFoundError` - I'll add some warning message about this and try/catch cache issue.

**Comment by fgelcer** [comment]
@soyacz @yaronkaikov , could it be that, we are tearing down not in the correct order? so we are left in a stage where we are trying to tear down the IP address, but it already doesn't exist?

**Comment by fruch** [comment]
> @soyacz @yaronkaikov , could it be that, we are tearing down not in the correct order? so we are left in a stage where we are trying to tear down the IP address, but it already doesn't exist?

For the look it looks like that, since clean resources is called multi times, once for each type, and the logic collects all the resources per test id, again and again

**Comment by soyacz** [comment]
> For the look it looks like that, since clean resources is called multi times, once for each type, and the logic collects all the resources per test id, again and again

Yes, that's the reason - there's race condition when we list all instances (with IP's) while Azure already triggered VM deletion (and IP get's deleted quicker). My fix won't work. I need to find other solution.

**Comment by fruch** [comment]
@soyacz fixes need to be backported to 5.2/2023.1

**Comment by soyacz** [comment]
done by FF

**Comment by Mark-Gurevich** [comment]
Happened again in job:  https://jenkins.scylladb.com/view/enterprise-2023.1/job/enterprise-2023.1/job/nemesis/job/longevity-5gb-1h-DecommissionMonkey-azure-test/2/

```
19:43:20  Traceback (most recent call last):
19:43:20    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1678, in <module>
19:43:20      cli.main(prog_name="hydra")
19:43:20    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
19:43:20      rv = self.invoke(ctx)
19:43:20    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
19:43:20      return _process_result(sub_ctx.command.invoke(sub_ctx))
19:43:20    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
19:43:20      return ctx.invoke(self.callback, **ctx.params)
19:43:20    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
19:43:20      return __callback(*args, **kwargs)
19:43:20    File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
19:43:20      return f(get_current_context(), *args, **kwargs)
19:43:20    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 295, in clean_resources
19:43:20      clean_func(param, dry_run=dry_run)
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2344, in clean_resources_according_post_behavior
19:43:20      clean_cloud_resources(params | {"NodeType": node_type}, dry_run=dry_run)
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 565, in clean_cloud_resources
19:43:20      clean_instances_azure(tags_dict, dry_run=dry_run)
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1324, in clean_instances_azure
19:43:20      provisioners = AzureProvisioner.discover_regions(tags_dict.get("TestId", ""))
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 96, in discover_regions
19:43:20      return [cls(*params) for params in provisioner_params]
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 96, in <listcomp>
19:43:20      return [cls(*params) for params in provisioner_params]
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 58, in __init__
19:43:20      self._cache[v_m.name] = self._vm_to_instance(v_m)
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 185, in _vm_to_instance
19:43:20      pub_address = self._ip_provider.get(v_m.name).ip_address
19:43:20    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/ip_provider.py", line 80, in get
19:43:20      return self._cache[ip_name]
19:43:20  KeyError: 'longevity-5gb-1h-decommissionmonkey-loader-node-eastus-1-ipv4'
```
