### ISSUE TITLE
`RebuildStreamingErr` fails after rebuild has become a RBNO

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#5878]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In the Job, SCT started a `RebuildStreamingErr` nemesis
```
< t:2023-03-03 09:11:31,004 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-03-03 09:11:31.000: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=36779f97-2dac-4c2b-9121-2a5207b3eb79: nemesis_name=RebuildStreamingErr target_node=Node gemini-
1tb-10h-master-db-node-4467dd96-4 [52.206.185.201 | 10.12.9.3] (seed: False)
```
During this nemesis, the rebuild operation was triggered on the target node
```
< t:2023-03-03 09:14:03,353 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-03-03 09:14:03.351: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=5e58e787-db1e-4b47-aa79-da6f7e59f10c: nodetool_command=rebuild node=gemini-1tb-10h-master-db-node
-4467dd96-4
< t:2023-03-03 09:14:03,353 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
```
Then SCT is supposed to reboot the target node after it has found the message `Rebuild starts` in the node log.
But the message never appeared.

In the log of the target node (node-4) I found the following records instead at the moment when rebuild had started:
```
2023-03-03T09:14:04+00:00 gemini-1tb-10h-master-db-node-4467dd96-4     !INFO | scylla[5113]:  [shard  0] api - rebuild: source_dc=
2023-03-03T09:14:04+00:00 gemini-1tb-10h-master-db-node-4467dd96-4     !INFO | scylla[5113]:  [shard  0] storage_service - rebuild from dc: (any dc)
2023-03-03T09:14:04+00:00 gemini-1tb-10h-master-db-node-4467dd96-4     !INFO | scylla[5113]:  [shard  0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={decommission, bootstrap, rebuild, removenode, replace}
2023-03-03T09:14:04+00:00 gemini-1tb-10h-master-db-node-4467dd96-4     !INFO | scylla[5113]:  [shard  0] repair - rebuild_with_repair: started with keyspaces=system_tracessystem_authks1system_distributed_everywheresystem_distributed, source_dc=us-east, nr_ranges_total=11833, ignore_nodes=[]
2023-03-03T09:14:04+00:00 gemini-1tb-10h-master-db-node-4467dd96-4     !INFO | scylla[5113]:  [shard  0] repair - rebuild_with_repair: started with keyspace=system_traces, source_dc=us-east, nr_ranges=2605, ignore_nodes=[]
```
Here I noticed that rebuild is now part of the value passed to `allowed_repair_based_node_ops` parameter.
It looks like after merging this PR https://github.com/scylladb/scylladb/pull/12970 ScyllaDB has an extended list of RBNO by default including rebuild and this change affected the nemesis.

## Impact

The thread waiting for the log message eventually failed after reaching the timeout, and so did the nemesis
```
2023-03-03 09:21:43.980: (DisruptionEvent Severity.ERROR) period_type=end event_id=36779f97-2dac-4c2b-9121-2a5207b3eb79 duration=10m12s: nemesis_name=RebuildStreamingErr target_node=Node gemini-1tb-10h-master-db-node-4467dd96-4 [52.206.185.201 | 10.12.9.3] (seed: False) errors=when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_aws.AWSNode object at 0x7fa89036f250>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7fa8b43574f0>>, log_follower=<sdcm.utils.file.ReiterableGenerator object at 0x7fa8873eda80>, disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7fa8b43574f0>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_aws.AWSNode object at 0x7fa89036f250>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4108, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3450, in disrupt_rebuild_streaming_err
self.start_and_interrupt_rebuild_streaming()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3428, in start_and_interrupt_rebuild_streaming
ParallelObject(objects=[trigger, watcher], timeout=timeout + 60).call_objects()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 458, in call_objects
return self.run(lambda x: x(), ignore_exceptions=ignore_exceptions)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 434, in run
raise FuturesTimeoutError("when running on: %s" % [r.obj for r in results])
concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_aws.AWSNode object at 0x7fa89036f250>>, sub_cmd='rebuild', warning_event_on_exception=(<class 'Exception'>,), retry=0), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7fa8b43574f0>>, log_follower=<sdcm.utils.file.ReiterableGenerator object at 0x7fa8873eda80>, disrupt_func=<bound method Nemesis.reboot_node of <sdcm.nemesis.SisyphusMonkey object at 0x7fa8b43574f0>>, disrupt_func_kwargs={'target_node': <sdcm.cluster_aws.AWSNode object at 0x7fa89036f250>, 'hard': True, 'verify_ssh': True}, timeout=400, delay=1)]
```

## How frequently does it reproduce?

Got it for the first time, but I think it should reproduce every time.

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `5.3.0~dev-20230302.d85af3dca4c1` with build-id `005aa67dc6c490cd99a75575380594d998a92cb0`

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-4467dd96-1 (3.93.176.60 | 10.12.9.11) (shards: 14)
- gemini-1tb-10h-master-db-node-4467dd96-4 (52.206.185.201 | 10.12.9.3) (shards: 14)
- gemini-1tb-10h-master-db-node-4467dd96-3 (3.88.158.31 | 10.12.8.46) (shards: 14)
- gemini-1tb-10h-master-db-node-4467dd96-2 (54.196.142.237 | 10.12.8.156) (shards: 14)
- gemini-1tb-10h-master-db-node-4467dd96-1 (34.236.152.211 | 10.12.10.88) (shards: 14)

OS / Image: `ami-0483dd8065c50c839` (aws: us-east-1)

Test: `gemini-1tb-10h`
Test id: `4467dd96-1901-4d69-b32c-a7b469d1a1e8`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7d691c9db7946a26ee15cf27aab317dbfb95465e/test-cases/gemini/gemini-1tb-10h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4467dd96-1901-4d69-b32c-a7b469d1a1e8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4467dd96-1901-4d69-b32c-a7b469d1a1e8)
- Show all stored logs command: `$ hydra investigate show-logs 4467dd96-1901-4d69-b32c-a7b469d1a1e8`

## Logs:
- **db-cluster-4467dd96.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/db-cluster-4467dd96.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/db-cluster-4467dd96.tar.gz)
- **sct-runner-4467dd96.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/sct-runner-4467dd96.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/sct-runner-4467dd96.tar.gz)
- **monitor-set-4467dd96.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/monitor-set-4467dd96.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/monitor-set-4467dd96.tar.gz)
- **loader-set-4467dd96.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/loader-set-4467dd96.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4467dd96-1901-4d69-b32c-a7b469d1a1e8/20230303_150838/loader-set-4467dd96.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/202/)
</details>

**Comment by fgelcer** [comment]
perhaps we have a new or different message now?
because we are now using RBNO doesn't mean that the operations are not happening, but they are part of a chain of events, AFAIU...
what do you suggest? do you want to search the logs (and consult with @asias ) on how we could make this nemesis work after RBNO is default to all operations?
we will hit this issue not only for rebuild, but probably to all `*StreamingErr` nemeses...

**Comment by asias** [comment]
> Then SCT is supposed to reboot the target node after it has found the message Rebuild starts in the node log.
> But the message never appeared.

We need to modify SCT to check for better logs as starting of rebuild.

```
INFO  2023-03-06 10:18:34,792 [shard 0] storage_service - rebuild from dc: (any dc)                                                                                                                                                    
INFO  2023-03-06 10:18:34,792 [shard 0] storage_service - enable_repair_based_node_ops=false, allowed_repair_based_node_ops={decommission, bootstrap, rebuild, removenode, replace}                                                    
INFO  2023-03-06 10:18:34,834 [shard 0] range_streamer - Rebuild starts, nr_ranges_remaining=1786 
```

'Rebuild starts' comes from only the classic streaming.

We can use the `rebuild from dc' which is present on both rbno enabled and disabled.

**Comment by fgelcer** [comment]
> > Then SCT is supposed to reboot the target node after it has found the message Rebuild starts in the node log.
> > But the message never appeared.
> 
> We need to modify SCT to check for better logs as starting of rebuild.
> 
> ```
> INFO  2023-03-06 10:18:34,792 [shard 0] storage_service - rebuild from dc: (any dc)                                                                                                                                                    
> INFO  2023-03-06 10:18:34,792 [shard 0] storage_service - enable_repair_based_node_ops=false, allowed_repair_based_node_ops={decommission, bootstrap, rebuild, removenode, replace}                                                    
> INFO  2023-03-06 10:18:34,834 [shard 0] range_streamer - Rebuild starts, nr_ranges_remaining=1786 
> ```
> 
> 'Rebuild starts' comes from only the classic streaming.
> 
> We can use the `rebuild from dc' which is present on both rbno enabled and disabled.

@ilya-rarov , would you mind changing the `Rebuild starts` we look in the log, for `rebuild from dc:` and retry the test?

**Comment by ilya-rarov** [comment]
> @ilya-rarov , would you mind changing the `Rebuild starts` we look in the log, for `rebuild from dc:` and retry the test?

@fgelcer sure
