### ISSUE TITLE
Truncate with using timeout fails on operator

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5903]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

```
Command: 'cqlsh --no-color   --request-timeout=600 --connect-timeout=60  -e "TRUNCATE ks_truncate_large_partition.test_table USING TIMEOUT 600s" 10.0.1.136 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:SyntaxException: line 1:48  : syntax error...
```

## Installation details

Kernel Version: 5.10.167-147.601.amzn2.x86_64
Scylla version (or git commit hash): `2022.2.1-20230213.87d6af74da28` with build-id `8c7ea8efd50c58e81fe70a19bfd220917ec47174`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.1-50-g4cf4788
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-eks`
Test id: `2e218c3b-6de3-4d40-86b4-c3975480c7a7`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1b7bae52044936df4a3c94ecf54a737eb291e6db/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2e218c3b-6de3-4d40-86b4-c3975480c7a7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2e218c3b-6de3-4d40-86b4-c3975480c7a7)
- Show all stored logs command: `$ hydra investigate show-logs 2e218c3b-6de3-4d40-86b4-c3975480c7a7`

## Logs:
- **db-cluster-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/db-cluster-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/db-cluster-2e218c3b.tar.gz)
- **sct-runner-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/sct-runner-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/sct-runner-2e218c3b.tar.gz)
- **monitor-set-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/monitor-set-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/monitor-set-2e218c3b.tar.gz)
- **loader-set-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/loader-set-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/loader-set-2e218c3b.tar.gz)
- **kubernetes-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/kubernetes-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/kubernetes-2e218c3b.tar.gz)
- **parallel-timelines-report-2e218c3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/parallel-timelines-report-2e218c3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2e218c3b-6de3-4d40-86b4-c3975480c7a7/20230312_011820/parallel-timelines-report-2e218c3b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/57/)
</details>

**Comment by fgelcer** [comment]
it doesn't make sense... what would be the difference between the syntax on operator vs on Scylla?

**Comment by fgelcer** [comment]
will try to investigate it later

**Comment by fruch** [comment]
It's running 2022.2 where this feature isn't implemented

**Comment by fgelcer** [comment]
@soyacz , would you mind re-running your test using #5904 ?
