### ISSUE TITLE
Values in test-cases/longevity/longevity-large-partition-4days.yaml are too tough

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5940]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: 8ebaeac5-0f13-410b-823f-79380daf5ce7
* job log: https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-4days-arm-test/3/console

### Description

The config file `test-cases/longevity/longevity-large-partition-4days.yaml` which is used in following jenkins files:
- jenkins-pipelines/ics-longevity-large-partition-4days.jenkinsfile
- jenkins-pipelines/longevity-large-partition-4days-arm.jenkinsfile
- jenkins-pipelines/longevity-large-partition-4days.jenkinsfile
- jenkins-pipelines/raft/longevity-large-partition-4days.jenkinsfile

Always lead to the following situation:

```
Configuration
Mode:			 read
Workload:		 uniform
Timeout:		 3m0s
Max error number at row: 1000
Max error number:	 unlimited
Retries:		
  number:		 10
  min interval:		 80ms
  max interval:		 1s
  handler:		 sb
Consistency level:	 quorum
Partition count:	 60
Clustering rows:	 10000000
Clustering row size:	 Fixed(2048)
Rows per request:	 2000
Provide upper bound:	 false
IN queries:		 false
Order by:		 none
No lower bound:		 false
Page size:		 1000
Concurrency:		 700
Connections:		 500
Maximum rate:		 64000 op/s
Client compression:	 true
Hdr memory consumption:	 344254400 bytes

2023/03/20 10:52:04 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[7 437723] consistency=QUORUM] || retry: attempt №0, sleep for 48.372823ms
...
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[11 9489971] consistency=QUORUM] || retry: attempt №2, sleep for 179.314757ms
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[19 3789190] consistency=QUORUM] || retry: attempt №1, sleep for 90.914044ms
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[11 1582285] consistency=QUORUM] || retry: attempt №5, sleep for 1s
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[57 8693346] consistency=QUORUM] || retry: attempt №0, sleep for 58.973834ms
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[57 1949574] consistency=QUORUM] || retry: attempt №0, sleep for 39.646297ms
2023/03/20 11:40:35 [query statement="SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 2000 " values=[11 9131832] consistency=QUORUM] || retry: attempt №7, sleep for 1s
...
```

And then fail of one or more loaders with various errors.

According to logs of jobs where this config gets applied it is observable that DB nodes work and don't have errors, but queries get responded much longer than loaders expect.

Also, after looking at the history of this config, I see that it was not polished and/or optimized.

So, the current issue can be resolved by proper calculation of the `baseline` for this config file consisting of the following parts:
- Define DB and loader instance types before measurements
- Define number of DB and loader nodes
- Play with various query values to find a combination where we do not get query errors and still use large partitions.

### Steps to Reproduce

1. Run any existing CI job with the above mentioned config file.
2. See errors

**Expected behavior:** queries should not have errors in normal case, but large latencies are expected.

**Actual behavior:** Queries time out all the time and get retried too fast.

**Comment by fruch** [comment]
Seems like this one https://github.com/scylladb/scylla-cluster-tests/pull/4244, has introduce a very big change to the case s-b commands putting lots of pressure on the node, give it was before retries and all the timeouts were ignored.
retries ontop of this configuration is probably way off now.

**Comment by vponomaryov** [comment]
> Seems like this one #4244, has introduce a very big change to the case s-b commands putting lots of pressure on the node, give it was before retries and all the timeouts were ignored. retries ontop of this configuration is probably way off now.

Looked at the logs [1] of the job used to test these values. First 6 minutes of the run were mostly timing out:

```
Configuration
Mode:			 read
Workload:		 uniform
Timeout:		 3m0s
Consistency level:	 quorum
Partition count:	 60
Clustering rows:	 10000000
Clustering row size:	 Fixed(2048)
Rows per request:	 2000
Provide upper bound:	 false
IN queries:		 false
No lower bound:		 false
Page size:		 1000
Concurrency:		 10000
Connections:		 1000
Maximum rate:		 32000 op/s
Client compression:	 true

 time   ops/s  rows/s errors max    99.9th 99th   95th   90th   median mean   2021/12/26 18:36:08 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2021/12/26 18:36:08 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2021/12/26 18:36:08 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2021/12/26 18:36:08 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2021/12/26 18:36:08 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
...
2021/12/26 18:37:39 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
2021/12/26 18:37:39 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.

1m55.6s    5164 12682868   4839 1m43.1s 1m43.1s 1m42.6s 1m34s  1m29.7s 35.2s  39.3s  
3m17.8s   28815 2134031    365 1m38s  1m37.3s 59s    40.7s  15.9s  14ms   5.7s   2021/12/26 18:40:00 writev tcp 10.0.1.73:43988->10.0.0.243:9042: writev: broken pipe
2021/12/26 18:40:00 writev tcp 10.0.1.73:43988->10.0.0.243:9042: writev: broken pipe
2021/12/26 18:40:00 writev tcp 10.0.1.73:43988->10.0.0.243:9042: writev: broken pipe
2021/12/26 18:40:00 writev tcp 10.0.1.73:43988->10.0.0.243:9042: writev: broken pipe
...
2021/12/26 18:40:01 EOF
2021/12/26 18:40:01 EOF
2021/12/26 18:40:05 error: failed to connect to 10.0.3.170:9042 due to error: gocql: no response to connection startup within timeout
2021/12/26 18:40:22 error: failed to connect to 10.0.2.155:9042 due to error: gocql: no response to connection startup within timeout

6m21.3s   12380  177405      0 24.7s  19.8s  17.2s  6.9s   5.8s   2.5s   2.8s   
7m51.5s   10405  131066      0 2.1s   1.4s   700ms  118ms  35ms   1.2ms  29ms   
8m16.9s    9828  116501    172 33.2s  27.6s  16.8s  9.6s   6.7s   1.2s   2.6s   
```

And after those 6minutes started working kind of ok with small number of timeouts later.

So, looks like retries make the load to become too big during these first minutes.

[1] https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/longevity-large-partition-4days-test-better-load/4

**Comment by roydahan** [comment]
Ok, what is the suggestion here?

**Comment by fruch** [comment]
The suggestion is to fine-tune the case back into a working condition, it was enlarged to something too big to be handled correctly, and the timeout it was having was just ignored assuming it's a s-b issue, and it's not.

the case was moved from `-concurrency=7 to -concurrency=700` (as one example), we need to take it back a few steps

**Comment by roydahan** [comment]
I doubt we will find a "working condition".
The partitions are very very big, but let's try...

**Comment by fruch** [comment]
> I doubt we will find a "working condition". The partitions are very very big, but let's try...

where our definition of the sizes of the partitions are coming from ? from specific issues ? like what is the goal/target in this use case, it wasn't clear from the commit/PR the "enlarged" it as to what's the purpose was, it just state "it was for reverse queries"...

**Comment by roydahan** [comment]
Coming from a field case where we have 10GB partitions.

**Comment by fruch** [comment]
> Coming from a field case where we have 10GB partitions.

A reference to that issue would be helpful for whom gonna work on this one.

**Comment by roydahan** [comment]
It's not a specific issue.
I suggest we won't touch the partitions themselves, only change parallelism and load.

**Comment by roydahan** [comment]
I know noticed that this issue was filed for the arm case.
What's the status of the regular test? or i4i test?

**Comment by fruch** [comment]
@vponomaryov 

let's start fixing this case, starting with lowering the concurrency to a working condition (while keeping the sizes of the partitions, since this is the goal of those cases)

**Comment by fruch** [comment]
@vponomaryov 

let run one of the 5.2 jobs in reproducers with older version of s-b (without s-b retries), so we can pass the release job first
