### ISSUE TITLE
`ToggleTableGcMode` nemesis fails while trying to enable `repair` mode for system table

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#5963]
## Issue description

The nemesis `disrupt_toggle_table_gc_mode` was trying to enable the `repair` mode for Tombstone GC on the system table `audit.audit_log` and expectedly failed with the error
```
2023-03-14 23:52:28.614: (DisruptionEvent Severity.ERROR) period_type=end event_id=a29afd94-8768-45d3-8657-59403a9e1e30 duration=30s: nemesis_name=ToggleTableGcMode target_node=Node longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-10 [3.88.228.56 | 10.12.9.147] (seed: False) errors=Encountered a bad command exit code!
Command: 'cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "ALTER TABLE  audit.audit_log WITH tombstone_gc = {\'mode\': \'repair\'};" 10.12.9.147 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: tombstone_gc option with mode = repair not supported for table with RF one or local replication strategy
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4198, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2575, in disrupt_toggle_table_gc_mode
self.toggle_table_gc_mode()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2301, in toggle_table_gc_mode
self.target_node.run_cqlsh(cmd)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2782, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "ALTER TABLE  audit.audit_log WITH tombstone_gc = {\'mode\': \'repair\'};" 10.12.9.147 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: tombstone_gc option with mode = repair not supported for table with RF one or local replication strategy
```
## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `f8b55007dc790d0c224d5e2d4b422786ffeb918e`

Cluster size: 6 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-9 (23.20.39.29 | 10.12.10.64) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-8 (3.80.48.199 | 10.12.8.46) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-7 (54.242.159.137 | 10.12.8.148) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-6 (107.23.126.89 | 10.12.9.178) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-5 (184.73.12.125 | 10.12.11.209) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-4 (34.229.18.61 | 10.12.11.13) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-3 (52.23.165.219 | 10.12.10.2) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-2 (3.90.221.243 | 10.12.11.196) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-12 (54.234.184.16 | 10.12.10.222) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-11 (54.226.105.74 | 10.12.9.205) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-10 (3.88.228.56 | 10.12.9.147) (shards: 15)
- longevity-tls-50gb-3d-2023-1-db-node-1dfc319c-1 (34.224.97.71 | 10.12.11.235) (shards: 15)

OS / Image: `ami-0734389f2aed090ad` (aws: us-east-1)

Test: `longevity-50gb-3days-arm-test`
Test id: `1dfc319c-b33c-4b80-a705-e413ac1f0b1e`
Test name: `enterprise-2023.1/longevity/longevity-50gb-3days-arm-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ec1600f015410814cdbe6d94ce29af866d6ccda/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1dfc319c-b33c-4b80-a705-e413ac1f0b1e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1dfc319c-b33c-4b80-a705-e413ac1f0b1e)
- Show all stored logs command: `$ hydra investigate show-logs 1dfc319c-b33c-4b80-a705-e413ac1f0b1e`

## Logs:
- **db-cluster-1dfc319c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/db-cluster-1dfc319c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/db-cluster-1dfc319c.tar.gz)
- **email_data-1dfc319c.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/email_data-1dfc319c.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/email_data-1dfc319c.json.tar.gz)
- **output-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/output-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/output-1dfc319c.log.tar.gz)
- **debug-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/debug-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/debug-1dfc319c.log.tar.gz)
- **events-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/events-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/events-1dfc319c.log.tar.gz)
- **sct-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/sct-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/sct-1dfc319c.log.tar.gz)
- **normal-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/normal-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/normal-1dfc319c.log.tar.gz)
- **argus-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/argus-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/argus-1dfc319c.log.tar.gz)
- **raw_events-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/raw_events-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/raw_events-1dfc319c.log.tar.gz)
- **critical-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/critical-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/critical-1dfc319c.log.tar.gz)
- **warning-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/warning-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/warning-1dfc319c.log.tar.gz)
- **summary-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/summary-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/summary-1dfc319c.log.tar.gz)
- **left_processes-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/left_processes-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/left_processes-1dfc319c.log.tar.gz)
- **error-1dfc319c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/error-1dfc319c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/error-1dfc319c.log.tar.gz)
- **monitor-set-1dfc319c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/monitor-set-1dfc319c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/monitor-set-1dfc319c.tar.gz)
- **loader-set-1dfc319c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/loader-set-1dfc319c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1dfc319c-b33c-4b80-a705-e413ac1f0b1e/20230317_175824/loader-set-1dfc319c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-50gb-3days-arm-test/2/)
</details>

**Comment by ilya-rarov** [comment]
After a discussion with @roydahan I am assigning this to @yarongilor

**Comment by fruch** [comment]
I think the issue here is that audit should be considered a system table, and it's not.

This nemesis should be touching system tables.

**Comment by fruch** [comment]
Also this nemesis is failing on docker backend with one node, cause of the same reason. we should skip if it's a setup with less than 3 nodes.

**Comment by yarongilor** [comment]
@fruch , this bug is not related to `toggle_table_gc_mode`. it's a bug in `get_non_system_ks_cf_list`. So i can try get a fix for that.
The RF problem is a different issue, but perhaps it could be solved toghether if we add a parameter like `min_rf` to `get_non_system_ks_cf_list`

**Comment by fruch** [comment]
> @fruch , this bug is not related to `toggle_table_gc_mode`. it's a bug in `get_non_system_ks_cf_list`. So i can try get a fix for that. The RF problem is a different issue, but perhaps it could be solved toghether if we add a parameter like `min_rf` to `get_non_system_ks_cf_list`

`toggle_table_gc_mode` is the failing nemesis, so all those issues are related to it

**Comment by yarongilor** [comment]
The RF issue should be solved by filtering the keyspaces like:
```
cassandra@cqlsh> SELECT replication FROM system_schema.keyspaces WHERE keyspace_name = 'keyspace_lz4';

 replication
-------------------------------------------------------------------------------------
 {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}

(1 rows)
```

**Comment by fruch** [comment]
> The RF issue should be solved by filtering the keyspaces like:
> ```
> cassandra@cqlsh> SELECT replication FROM system_schema.keyspaces WHERE keyspace_name = 'keyspace_lz4';
> 
>  replication
> -------------------------------------------------------------------------------------
>  {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
> 
> (1 rows)
> ```

We shouldn't have any test table with RF=1, if we have it's a bug we need to address.
