### ISSUE TITLE
Automatic NetworkTopologyStrategy for c-s and CREATE commands

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5969]
In SCT we mostly use simpleStrategy for c-s workflows. While it's convenient it is not reflecting recommended production replication strategy which is network one. 
I propose to make c-s to automatically switch replication strategy from simple to network in the runtime (requires region knowledge).
benefits:
- more production like testing
- we could drop setting network replication strategies parameters in c-s commands so we can switch regions for the tests where we specify it

**Comment by soyacz** [comment]
Also should fix region names for cases we already hardcode regions when using NetworkTopology.

**Comment by soyacz** [comment]
Note: 
Currently we don't use Ec2MultiRegionSnitch and we apply some own way of naming datacenters in SCT.
Test how Ec2MultiRegionSnitch works and how it names dc's. Adapt SCT to use similar if needed.

**Comment by fgelcer** [comment]
any progress with this task?

**Comment by soyacz** [comment]
> any progress with this task?

not yet, it's planned.

**Comment by roydahan** [comment]
Do we still need it? (I think not, right?)

**Comment by soyacz** [comment]
Yes, it's fixed
