### ISSUE TITLE
CreateIndex nemesis: Timeout error while creating index test_v_nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5973]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

CreateIndex nemesis failed with a 2-hours timeout waiting for index to be created.
We have to check if it's something reasonable. perhaps we can also use a soft timeout to better understand how it performs.
```
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_create_index of <sdcm.nemesis.SisyphusMonkey object at 0x7fc08fe72f20>> < t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_create_index of <sdcm.nemesis.SisyphusMonkey object at 0x7fc08fe72f20>>
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4121, in disrupt_create_index
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     wait_for_index_to_be_built(self.target_node, ks, index_name, timeout=7200)
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 56, in wait_for_index_to_be_built
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     raise TimeoutError(f"Timeout error while creating index {index_name}. "
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > TimeoutError: Timeout error while creating index test_v_nemesis. stdout
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > : scylla_bench.test_v_nemesis_index has not finished building; node status is below.
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > Host         Info   
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 10.12.11.71  SUCCESS
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 10.12.11.160 SUCCESS
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 10.12.11.196 STARTED
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 10.12.8.178  SUCCESS
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > stderr
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > : 
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > During handling of the above exception, another exception occurred:
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > 
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4225, in wrapper
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4126, in disrupt_create_index
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     drop_index(session, ks, index_name)
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 87, in drop_index
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     session.execute(f'DROP INDEX {ks}.{index_name}')
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1649, in execute_verbose
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >     return execute_orig(*args, **kwargs)
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR >   File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
< t:2023-03-17 13:04:36,322 f:nemesis.py      l:4236 c:sdcm.nemesis         p:ERROR > cassandra.OperationTimedOut: errors={'10.12.11.160:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.11.160:9042
< t:2023-03-17 13:04:36,323 f:nemesis.py      l:4260 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: CreateIndex Node longevity-twcs-48h-master-db-node-c92a1ca7-5 [54.165.96.159 | 10.12.11.160] (seed: False) duration -> 7290 s
< t:2023-03-17 13:04:36,323 f:nemesis.py      l:294  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Update nemesis info with: {'start': 1679050985, 'end': 1679058276, 'duration': 7290, 'node': 'Node longevity-twcs-48h-master-db-node-c92a1ca7-5 [54.165.96.159 | 10.12.11.160] (seed: False)', 'subtype': 'end', 'error': "errors={'10.12.11.160:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.11.160:9042", 'full_traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4121, in disrupt_create_index\n    wait_for_index_to_be_built(self.target_node, ks, index_name, timeout=7200)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 56, in wait_for_index_to_be_built\n    raise TimeoutError(f"Timeout error while creating index {index_name}. "\nTimeoutError: Timeout error while creating index test_v_nemesis. stdout\n: scylla_bench.test_v_nemesis_index has not finished building; node status is below.\n\nHost         Info   \n10.12.11.71  SUCCESS\n10.12.11.160 SUCCESS\n10.12.11.196 STARTED\n10.12.8.178  SUCCESS\n\nstderr\n: \n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4225, in wrapper\n    result = method(*args[1:], **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4126, in disrupt_create_index\n    drop_index(session, ks, index_name)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 87, in drop_index\n    session.execute(f\'DROP INDEX {ks}.{index_name}\')\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1649, in execute_verbose\n    return execute_orig(*args, **kwargs)\n  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute\n  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result\ncassandra.OperationTimedOut: errors={\'10.12.11.160:9042\': \'Client request timeout. See Session.execute[_async](timeout)\'}, last_host=10.12.11.160:9042\n'}
< t:2023-03-17 13:04:36,360 f:nemesis.py      l:4275 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: log_info: {'start': 1679050985, 'end': 1679058276, 'duration': 7290, 'node': 'Node longevity-twcs-48h-master-db-node-c92a1ca7-5 [54.165.96.159 | 10.12.11.160] (seed: False)', 'subtype': 'end', 'error': "errors={'10.12.11.160:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.11.160:9042", 'full_traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4121, in disrupt_create_index\n    wait_for_index_to_be_built(self.target_node, ks, index_name, timeout=7200)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 56, in wait_for_index_to_be_built\n    raise TimeoutError(f"Timeout error while creating index {index_name}. "\nTimeoutError: Timeout error while creating index test_v_nemesis. stdout\n: scylla_bench.test_v_nemesis_index has not finished building; node status is below.\n\nHost         Info   \n10.12.11.71  SUCCESS\n10.12.11.160 SUCCESS\n10.12.11.196 STARTED\n10.12.8.178  SUCCESS\n\nstderr\n: \n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4225, in wrapper\n    result = method(*args[1:], **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4126, in disrupt_create_index\n    drop_index(session, ks, index_name)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 87, in drop_index\n    session.execute(f\'DROP INDEX {ks}.{index_name}\')\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1649, in execute_verbose\n    return execute_orig(*args, **kwargs)\n  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute\n  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result\ncassandra.OperationTimedOut: errors={\'10.12.11.160:9042\': \'Client request timeout. See Session.execute[_async](timeout)\'}, last_host=10.12.11.160:9042\n'}
< t:2023-03-17 13:06:07,590 f:nemesis.py      l:1738 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: <<<<<<<<<<<<<Finished random_disrupt_method create_index
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.2.0~dev-20230316.66219d769a0f` with build-id `8a87fca0693c65d17e56c7675808c611e9165773`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-c92a1ca7-9 (34.228.60.138 | 10.12.10.225) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-8 (54.205.189.73 | 10.12.10.11) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-7 (54.210.158.64 | 10.12.8.221) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-6 (54.165.43.250 | 10.12.8.178) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-5 (54.165.96.159 | 10.12.11.160) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-4 (18.234.45.237 | 10.12.11.196) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-3 (54.87.176.15 | 10.12.11.245) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-2 (54.234.148.64 | 10.12.10.191) (shards: 7)
- longevity-twcs-48h-master-db-node-c92a1ca7-10 (54.167.55.160 | 10.12.11.14) (shards: -1)
- longevity-twcs-48h-master-db-node-c92a1ca7-1 (54.237.235.219 | 10.12.11.71) (shards: 7)

OS / Image: `ami-015148d7136bade2e` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7`
Test name: `scylla-enterprise/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2294a254c75993b765f44dfa97994e307d75064e/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7)
- Show all stored logs command: `$ hydra investigate show-logs c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7`

## Logs:
- **db-cluster-c92a1ca7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/db-cluster-c92a1ca7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/db-cluster-c92a1ca7.tar.gz)
- **sct-runner-c92a1ca7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/sct-runner-c92a1ca7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/sct-runner-c92a1ca7.tar.gz)
- **monitor-set-c92a1ca7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/monitor-set-c92a1ca7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/monitor-set-c92a1ca7.tar.gz)
- **loader-set-c92a1ca7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/loader-set-c92a1ca7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c92a1ca7-fabf-4deb-88d0-2ab13c61f9d7/20230319_045335/loader-set-c92a1ca7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-twcs-48h-test/7/)
</details>

**Comment by nyh** [comment]
Something seems wrong about the scenario tested here - or I don't understand it: 
It seems like you're doing CREATE INDEX, which finishes almost immediately - and then waiting for the "view building" (the indexing of the pre-existing data) to finish. In parallel, you are doing DROP INDEX on this new index, which is allowed (the partially-build index will be deleted). So why are you suprised that the "waiting for view build" never finishes? Why should it ever finish if we asked to stop it? What am I missing?

Also, please take a look at the Scylla logs and report any interesting errors or non-errors you see. What I expect to see is that the view building should at some point realize that the view was deleted, potentially print some errors for a short time (as previously-written view updates get rejected) but then settle down. If something more serious happens we should know about it.

**Comment by soyacz** [comment]
> Something seems wrong about the scenario tested here - or I don't understand it: It seems like you're doing CREATE INDEX, which finishes almost immediately - and then waiting for the "view building" (the indexing of the pre-existing data) to finish. In parallel, you are doing DROP INDEX on this new index, which is allowed (the partially-build index will be deleted). So why are you suprised that the "waiting for view build" never finishes? Why should it ever finish if we asked to stop it? What am I missing?

@nyh 
Dropping index is after timeout of creating index (in 'finally` part of try-catch)

> 
> Also, please take a look at the Scylla logs and report any interesting errors or non-errors you see. What I expect to see is that the view building should at some point realize that the view was deleted, potentially print some errors for a short time (as previously-written view updates get rejected) but then settle down. If something more serious happens we should know about it.

Yes, that would be useful, possibly looking to monitoring also can provide some insight.
This is quite fresh Nemesis and maybe timeouts are not tuned properly to all the use cases. Need to investigate anyway as it looks only one node failed building index within 2h.

**Comment by soyacz** [comment]
we added soft timeout around that to see how long it really takes. no need for this issue anymore.
