### ISSUE TITLE
MultiDC test: provisioned instances for 2nd and 3th (in the region parameter list) region are ignored and new instances are created in "Run SCT Test"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5996]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Test with multi DC cluster. AWS. I did not check on GCE or Azure

Regions: eu-west-1, us-west-2, us-east-1

Instances were provisioned for every region.
But just for first region in the list provisioned instances were used. Region **eu-west-1**:
```
14:09:42  < t:2023-04-09 11:09:42,713 f:cluster_aws.py  l:351  c:sdcm.cluster         p:INFO  > Cluster lwt-longevity-multi-dc-24h-create-l-db-cluster-678b7602 (AMI: ['ami-0336a5a646b08dc25', 'ami-017ff4adbd0789b7d', 'ami-0bfa3b8209fe4bb00'] Type: i3.8xlarge): Found provisioned instances = [ec2.Instance(id='i-0092510240b9f0b51'), ec2.Instance(id='i-0849cac6e917e98c0'), ec2.Instance(id='i-0a110ffa7ef3849cf'), ec2.Instance(id='i-0060e05ba902345a6')]
14:09:43  < t:2023-04-09 11:09:43,365 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-1 [176.34.76.141 | 10.4.3.132] (seed: False): Detected Linux distribution: UBUNTU22
14:10:08  < t:2023-04-09 11:10:08,548 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-2 [54.228.89.246 | 10.4.0.119] (seed: False): Detected Linux distribution: UBUNTU22
14:10:33  < t:2023-04-09 11:10:33,664 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-3 [52.50.88.132 | 10.4.0.83] (seed: False): Detected Linux distribution: UBUNTU22
14:10:59  < t:2023-04-09 11:10:58,865 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-4 [34.243.179.64 | 10.4.2.42] (seed: False): Detected Linux distribution: UBUNTU22

```

For two other regiones the instances were created again.
Region **us-west-2**
```
14:11:24  < t:2023-04-09 11:11:23,330 f:cluster_aws.py  l:212  c:sdcm.cluster         p:INFO  > Cluster lwt-longevity-multi-dc-24h-create-l-db-cluster-678b7602 (AMI: ['ami-0336a5a646b08dc25', 'ami-017ff4adbd0789b7d', 'ami-0bfa3b8209fe4bb00'] Type: i3.8xlarge): Create on_demand instance(s)
14:12:36  < t:2023-04-09 11:12:33,755 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-5 [35.87.13.160 | 10.15.2.12] (seed: False): Detected Linux distribution: UBUNTU22
14:13:02  < t:2023-04-09 11:13:02,553 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-6 [34.209.50.250 | 10.15.1.97] (seed: False): Detected Linux distribution: UBUNTU22
14:13:31  < t:2023-04-09 11:13:31,072 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-7 [54.202.168.7 | 10.15.3.228] (seed: False): Detected Linux distribution: UBUNTU22
```

Region **us-east-1**:
```
14:13:57  < t:2023-04-09 11:13:57,096 f:cluster_aws.py  l:212  c:sdcm.cluster         p:INFO  > Cluster lwt-longevity-multi-dc-24h-create-l-db-cluster-678b7602 (AMI: ['ami-0336a5a646b08dc25', 'ami-017ff4adbd0789b7d', 'ami-0bfa3b8209fe4bb00'] Type: i3.8xlarge): Create on_demand instance(s)
14:15:23  < t:2023-04-09 11:15:10,547 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-8 [18.232.178.163 | 10.12.1.4] (seed: False): Detected Linux distribution: UBUNTU22
14:15:38  < t:2023-04-09 11:15:37,695 f:cluster.py      l:499  c:sdcm.cluster_aws     p:INFO  > Node lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-9 [3.208.90.148 | 10.12.3.169] (seed: False): Detected Linux distribution: UBUNTU22
```

Same for loaders.

As result in 2 regions we have duplicated instances. Example:
![Screenshot from 2023-04-09 17-58-32](https://user-images.githubusercontent.com/34435448/230780231-5fc07542-c6c8-48a0-9893-d86eb6faf76e.png)

Instances creation time:
![Screenshot from 2023-04-09 18-00-07](https://user-images.githubusercontent.com/34435448/230780310-a91bd305-8aa6-40a6-b469-4e05c13eabc8.png)

All instances (duplicated also) were terminated in the end of test

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 9 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-9 (3.208.90.148 | 10.12.3.169) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-8 (18.232.178.163 | 10.12.1.4) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-7 (54.202.168.7 | 10.15.3.228) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-6 (34.209.50.250 | 10.15.1.97) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-5 (35.87.13.160 | 10.15.2.12) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-4 (34.243.179.64 | 10.4.2.42) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-3 (52.50.88.132 | 10.4.0.83) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-2 (54.228.89.246 | 10.4.0.119) (shards: 30)
- lwt-longevity-multi-dc-24h-create-l-db-node-678b7602-1 (176.34.76.141 | 10.4.3.132) (shards: 30)

OS / Image: `ami-0336a5a646b08dc25 ami-017ff4adbd0789b7d ami-0bfa3b8209fe4bb00` (aws: eu-west-1)

Test: `longevity-lwt-24h-multidc-test`
Test id: `678b7602-8e39-4a13-b478-2e479f70eb6d`
Test name: `scylla-staging/yulia/longevity-lwt-24h-multidc-test`
Test config file(s):

- [longevity-lwt-24h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5981d966520e19e4c89eec420a56c16e75a83c3e/test-cases/longevity/longevity-lwt-24h-multidc.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 678b7602-8e39-4a13-b478-2e479f70eb6d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=678b7602-8e39-4a13-b478-2e479f70eb6d)
- Show all stored logs command: `$ hydra investigate show-logs 678b7602-8e39-4a13-b478-2e479f70eb6d`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-lwt-24h-multidc-test/4/)
</details>

**Comment by juliayakovlev** [comment]
Looks like the problem is here:
```
    def _create_or_find_instances(self, count, ec2_user_data, dc_idx):
        if self.nodes:
            return self._create_instances(count, ec2_user_data, dc_idx)

        if instances := self._get_instances(dc_idx):
            self.log.info('Found provisioned instances = %s', instances)
            return instances
 ```

This check  **if self.nodes:** does not take into account the DC and if nodes were added for the first DC, it creates the new instances again

**Comment by fruch** [comment]
> Looks like the problem is here:
> ```
>     def _create_or_find_instances(self, count, ec2_user_data, dc_idx):
>         if self.nodes:
>             return self._create_instances(count, ec2_user_data, dc_idx)
> 
>         if instances := self._get_instances(dc_idx):
>             self.log.info('Found provisioned instances = %s', instances)
>             return instances
>  ```
> 
> This check  **if self.nodes:** does not take into account the DC and if nodes were added for the first DC, it creates the new instances again
> 
> 

Sounds like an easy fix, of putting the create instances into an else clause.
