### ISSUE TITLE
failing to set /proc/sys/kernel/perf_event_paranoid in operator based test

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6018]
seems that recently we started getting this failure message when using master image
```
2023-04-16 03:51:42.072: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=33a7290d-37b2-4a13-8321-788770254ca8: type=BACKTRACE regex=backtrace line_number=167 node=sct-cluster-us-east1-b-us-east1-1
INFO  2023-04-16 03:49:53,281 [shard 0] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
```

two option to address:
1) ignore those in operator base runs 
2) find a way to enable /proc/sys/kernel/perf_event_paranoid on the hosts, so this feature would work

**Comment by fruch** [comment]
@vponomaryov what do you think is better option ?

**Comment by fgelcer** [comment]
seems like the message raised by OS changed, but we decided when introduced the option to enable it, to not do it for every test, but maybe this is now the time to enable it to all... there is already a flag to do it.
we must add `print_kernel_callstack: true` to `test_default.yaml`.

@roydahan , any objections?

**Comment by fgelcer** [comment]
> @vponomaryov what do you think is better option ?

and perhaps we must do tht 2 options... raise a `WARNING` event (and not `ERROR`), and maybe enable it to all tests

**Comment by fruch** [comment]
> seems like the message raised by OS changed, but we decided when introduced the option to enable it, to not do it for every test, but maybe this is now the time to enable it to all... there is already a flag to do it. we must add `print_kernel_callstack: true` to `test_default.yaml`.
> 
> @roydahan , any objections?

@fgelcer it's already true in test_default.yaml... 

also it's not a OS change, since it's k8s pod, the code we have to enable this kernel option is never being used.
this print from seastar is probably new, and just cause it has the word backtrace in it, we see it as error.

I think we should look into checking how to enable this kernel option on the k8s hosts, and check if it's working. (i.e. we need this debugging option also on k8s)

**Comment by vponomaryov** [comment]
We can do it on the SCT side, we already do tweaks on K8S Scylla nodes.
But I think it must be done on the scylla-operator side, because every user will face it.

**Comment by fruch** [comment]
> > We can do it on the SCT side, we already do tweaks on K8S Scylla nodes. But I think it must be done on the scylla-operator side, because every user will face it. So, it sounds to me as `need-to-file-scylla-operator-bug-and-temporary-workaround-in-sct` thing.
> 
> so we need an scylla-operator issue. Is there already?

I'm not sure scylla-operator should do it by default, i.e. maybe it should provide instruction on how to enabled it.
