### ISSUE TITLE
Job started with wrong number of loader nodes (7 instead of 4) 

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylla-cluster-tests#6041]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2023.1
* **scylla**: 2023.1.0-rc4

### Logs
* test_id: a90bf6ba-74a0-41e7-a283-27375d73dd9f
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/a90bf6ba-74a0-41e7-a283-27375d73dd9f/20230413_212706/sct-a90bf6ba.log.tar.gz
* loaders logs: https://cloudius-jenkins-test.s3.amazonaws.com/4ef11918-2f24-459d-a8e2-83e2cfaba5f1/20230417_101752/loader-set-4ef11918.tar.gz

### Description
The job started with 7 loader nodes instead of 4 while in the config file we have 4.
We can see that c-s ran on 4 nodes but 7 were started.

https://argus.scylladb.com/test/6865de3b-2605-4449-bc27-55bd19b1c4e2/runs?additionalRuns%5B%5D=8ace7e5f-6988-4f46-895b-6ee229dd35c5

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Job expected to start 4 loader nodes.
**Actual behavior:** [What actually happened]
Job started 7 loader nodes.

**Comment by soyacz** [comment]
error is in _create_or_find_instances logic: previously it was executed just once, after adding multi-az support it is executed more times and it is not detecting provisioned instances, it add new ones.
I try to find solution now.

**Comment by fruch** [comment]
> error is in _create_or_find_instances logic: previously it was executed just once, after adding multi-az support it is executed more times and it is not detecting provisioned instances, it add new ones. I try to find solution now.

it's exactly what Julia is trying to solve

**Comment by fruch** [comment]
> error is in _create_or_find_instances logic: previously it was executed just once, after adding multi-az support it is executed more times and it is not detecting provisioned instances, it add new ones. I try to find solution now.

it's happening all the time, or only on jobs using multiple AZ ?

**Comment by fruch** [comment]
@soyacz please look at https://github.com/scylladb/scylla-cluster-tests/pull/6002, I think it might be the exact issue.
we thought it would be happening only on multiple regions...

**Comment by soyacz** [comment]
I think I have the fix for issue introduced by multi-az and is **a bit** different than #6002 which looks like was existing before.
I'll create commit with fix for this issue introduced by multi-az, for #6002 let's think of more robust solution.
