### ISSUE TITLE
Do we set "system_auth_rf" correctly?

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#6084]
In https://github.com/scylladb/scylla-cluster-tests/blob/100adec8e9afdfbbf0adb0d11f12e2242fc62868/sdcm/tester.py#L867 we set it according to system_auth_rf param which by default is set to "3" (@aleksbykov why?).

In Scylla's documentation it needs to be set with the number of db_nodes:

> Set the system_auth keyspace replication factor to the number of nodes in the datacenter via cqlsh. It allows you to ensure that the user’s information is kept highly available for the cluster. If system_auth is not equal to the number of nodes and a node fails, the user whose information is on that node will be denied access.

(https://docs.scylladb.com/stable/operating-scylla/security/authentication.html)

Moreover, it seems that we only use "SimpleStrategy" but we need to use "NetworkTopology" and in some cases multi-dc.

**Comment by roydahan** [comment]
FYI @fgelcer @fruch

**Comment by roydahan** [comment]
@temichus I assigned to you and @aleksbykov who introduced this change few years ago.

**Comment by roydahan** [comment]
@fgelcer for the cases we have the authentication issue, please retest with a simple change of RF=n_db_nodes.
(assuming this is not a multi-dc / AZ scenario) till we have a complete fix for that).

**Comment by roydahan** [comment]
The tests that are failing with this issue - https://github.com/scylladb/scylladb/issues/13503
Need to be retested with the PR.

**Comment by vponomaryov** [comment]
> @roydahan , on a second thought the above documentation requirement doesn't fully make sense. What happens if the user want to extend it's cluster and add more nodes? does he have to change system_auth_rf dynamically? why would a value of '3' is not good enough for a cluster of 4 nodes?

We have configurations for much more than 4 nodes. Not counting scale tests we have `6`, `7`, `8` and `9` -node setups.
Then, the proposed solution to use RF equal to the starting num of DB nodes makes the diff be small enough in cases when `user want to extend it's cluster and add more nodes`.
In our case it gets returned to the original number all the time.

So, to me, the `system_auth_rf` equality to the starting node number sounds much better than keep an eye on the node numbers we configure in any old/new CI jb.

**Comment by soyacz** [comment]
I recommend using utilities from `sdcm/utils/replication_strategy_utils.py` to set RF factors.

**Comment by roydahan** [comment]
We should follow the exact instructions in the documentation, including scaling.

**Comment by aleksbykov** [comment]
I don't exactly remember why was choosen such behavior. To change according to documentation need answer on next questions:

1. Should we use only NetworkTopologyReplication? As @mykaul  mentioned, SimpleStrategy will be deprecated in near future.
With single DC we can use ` {'class' : 'NetworkTopologyStrategy', 'replication_factor': <num_of_nodes>}`
2. For multidc tests, we can use `Nemesis._switch_to_network_replication_strategy` to change for system_auth keyspace?
3. Should we always alter system_auth keyspaces with new rf when adding/remove nodes in nemesis?

**Comment by aleksbykov** [comment]
Possible solution: https://github.com/scylladb/scylla-cluster-tests/pull/6128

**Comment by roydahan** [comment]
This was backported to 2023.1 and 5.2.

@temichus & @aleksbykov please make sure you don't leave things in "Waiting for Backport"
