### ISSUE TITLE
After a node reboot, we need to wait for scylla service to be up (not for the ssh to be up as we do now) 

### ISSUE THREAD

**Issue by rayakurl** [scylladb/scylla-cluster-tests#6085]
We need to wait for scylla to be up after we reboot a node, not for ssh to be up as we do now.

Nemesis for example: disrupt_decommission_streaming_err

During DecommissionStreamingErr nemesis we interrupt the decommission process on a db node with a hard reboot. Than, if the decommission was interrupted successfully (i.e. it's still in the cluster), we run a nodetool rebuild command on it. In this case however the rebuild didn't start, since we failed to ssh to longevity-10gb-3h-5-2-db-node-98470f24-2 .

We failed to ssh since cloud-init restarted the sshd (twice):
`
2023-04-27T21:31:25+00:00 longevity-10gb-3h-5-2-db-node-98470f24-2     !INFO | cloud-init[736]: + systemctl restart sshd
2023-04-27T21:31:25+00:00 longevity-10gb-3h-5-2-db-node-98470f24-2     !INFO | cloud-init[736]: + systemctl restart sshd
2023-04-27T21:31:25+00:00 longevity-10gb-3h-5-2-db-node-98470f24-2     !INFO | cloud-init[736]: + systemctl start sshd
`

At the same time the test tried to run nodetool rebuild via ssh:
`
< t:2023-04-27 21:31:50,323 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
`
and failed:
`
< t:2023-04-27 21:32:07,152 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-27 21:32:07.144: (NodetoolEvent Severity.ERROR) period_type=end event_id=006652ef-ce66-4e89-aefa-d595bd6282b3 during_nemesis=DecommissionStreamingErr duration=16s: nodetool_command=rebuild node=longevity-10gb-3h-5-2-db-node-98470f24-2 errors=['Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n', 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\nsdcm.remote.libssh2_client.exceptions.OpenChannelTimeout: Failed to open channel in 15 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 591, in run\n    return self._complete_run(\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 649, in _complete_run\n    raise exception\nsdcm.remote.libssh2_client.exceptions.FailedToRunCommand: Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2585, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run\n    if self._run_on_retryable_exception(exc, new_session):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception\n    raise RetryableNetworkException(str(exc), original=exc)\nsdcm.remote.base.RetryableNetworkException: Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n\n']
`

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `5.2.0-20230427.429b696bbc1b` with build-id `9736db0414bad938b1d5d959bb25fbb4fb8558ce`

Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-2-db-node-98470f24-9 (44.214.1.240 | 10.12.3.115) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-8 (44.197.133.214 | 10.12.1.41) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-7 (44.204.201.164 | 10.12.0.132) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-6 (44.204.221.60 | 10.12.1.117) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-5 (44.193.28.39 | 10.12.2.145) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-4 (44.214.92.128 | 10.12.1.52) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-3 (44.193.82.82 | 10.12.2.122) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-2 (44.193.206.15 | 10.12.0.28) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-10 (3.239.69.35 | 10.12.3.69) (shards: 7)
- longevity-10gb-3h-5-2-db-node-98470f24-1 (3.219.29.100 | 10.12.0.136) (shards: 7)

OS / Image: `ami-01ef4ed35fc5245a1` (aws: us-east-1)

Test: `longevity-10gb-3h-test`
Test id: `98470f24-a816-4a97-be84-92e6d8d5e3ed`
Test name: `scylla-5.2/longevity/longevity-10gb-3h-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0fc27a30470bede5f583e2ae29f71e81c76c2b4c/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 98470f24-a816-4a97-be84-92e6d8d5e3ed`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=98470f24-a816-4a97-be84-92e6d8d5e3ed)
- Show all stored logs command: `$ hydra investigate show-logs 98470f24-a816-4a97-be84-92e6d8d5e3ed`

## Logs:
- **db-cluster-98470f24.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/db-cluster-98470f24.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/db-cluster-98470f24.tar.gz)
- **sct-runner-events-98470f24.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/sct-runner-events-98470f24.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/sct-runner-events-98470f24.tar.gz)
- **sct-98470f24.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/sct-98470f24.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/sct-98470f24.log.tar.gz)
- **monitor-set-98470f24.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/monitor-set-98470f24.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/monitor-set-98470f24.tar.gz)
- **loader-set-98470f24.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/loader-set-98470f24.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/loader-set-98470f24.tar.gz)
- **parallel-timelines-report-98470f24.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/parallel-timelines-report-98470f24.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98470f24-a816-4a97-be84-92e6d8d5e3ed/20230428_002731/parallel-timelines-report-98470f24.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-test/11/)
</details>

**Comment by rayakurl** [comment]
@fruch, @ShlomiBalalis , @fgelcer - FYI

**Comment by fgelcer** [comment]
> @fruch, @ShlomiBalalis , @fgelcer - FYI

AFAICT we need to:
```
wait_db_up()
wait_jmx_up()
```

does that make sense?

**Comment by fgelcer** [comment]
> > @fruch, @ShlomiBalalis , @fgelcer - FYI
> 
> AFAICT we need to:
> 
> ```
> wait_db_up()
> wait_jmx_up()
> ```
> 
> does that make sense?

and/or `wait_for_nodes_up_and_normal()`

**Comment by fruch** [comment]
> > > @fruch, @ShlomiBalalis , @fgelcer - FYI
> > 
> > AFAICT we need to:
> > 
> > ```
> > wait_db_up()
> > wait_jmx_up()
> > ```
> > 
> > does that make sense?
> 
> and/or `wait_for_nodes_up_and_normal()`

We need to wait just for one node and in some of the nemesis we use wait_db_up() and in some seem like it was forgotten, or the rebuild was added with considering it
