### ISSUE TITLE
Large partitions test has 50% probability to run wrong scylla-bench commands according to the clustering order configuration

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6098]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master, 2023.1, 2022.2, 5.2, 5.1
* **scylla**: 

### Logs
* context: https://github.com/scylladb/scylladb/issues/13740

### Description

See: https://github.com/scylladb/scylladb/issues/13740#issuecomment-1536266180

### Steps to Reproduce

1. Run the same `large partitions` test multiple times while you get different clustering order in different clusters - `ASC` and `DESC`.
2. See cache dashboard for each of them. In case of the `ASC` it is 5%, in case of the `DESC` it is `100%`. And total `op/s` differ a lot (5-6 times).

**Expected behavior:** SCT must use correct scylla-bench commands for each of the clustering orders.

**Actual behavior:** SCT uses the same scylla-bench commands for the different clustering orders.

**Comment by fruch** [comment]
@vponomaryov I see 2 option for fixing:
1) revert https://github.com/scylladb/scylla-cluster-tests/pull/4274, and stop randomizing
2) append the ordering commandline option to s-b based on the table options

I think I prefer option 1, since reversed should have their own use cases. and w shouldn't mixed it like that, making comparing the job a bit worthless

**Comment by fruch** [comment]
@vponomaryov 
After talking with @roydahan, let's revert https://github.com/scylladb/scylla-cluster-tests/pull/4274, and whom would re-introduce reverse queries into this job, would need to qualify this test case again

**Comment by roydahan** [comment]
FYI @yarongilor

**Comment by fruch** [comment]
fixed by https://github.com/scylladb/scylla-cluster-tests/pull/6110
