### ISSUE TITLE
Using monitor new images

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6121]
Requirements from images:
* We need a way to configure the image from user-data, while it support other users of user-data (like cloud-init), so mime multi-part should be defined
  * we need a way to pass in the nodes ip addresses 
  * we need a way to pass down commandline argument / env to `start.sh`
  * we need a way to pass in custom dashboards
* images should be able to start on their own once booted
* images should be sync into those regions: 
  `aws_supported_regions = ['eu-west-1', 'eu-west-2', 'us-west-2', 'us-east-1', 'eu-north-1', 'eu-central-1']`

**Comment by roydahan** [comment]
Dup of https://github.com/scylladb/qa-tasks/issues/993 ?

**Comment by fruch** [comment]
No, it's specific of the communication we had with Amnon,
https://github.com/scylladb/qa-tasks/issues/993 was about create/use images only,

this is how to use them via user-data

**Comment by fruch** [comment]
we did the first stage of using the images, but this part of executing via user-data isn't done yet.
