### ISSUE TITLE
disrupt_memory_stress failed: update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/boot /boot none bind,ro 0 0): permission denied

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6143]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

memoryStress nemesis stress-ng command failed.
Not sure if it's a real problem or has to be ignored or perhaps add a `sudo` or something to the command.
And why does 'boot' be involved in here?
the stderr output does show `successful run completed in 10.01s`
(no logs uploaded for this run)
error:
```
2023-05-12 06:43:16.990: (DisruptionEvent Severity.ERROR) period_type=end event_id=b994c182-885f-4941-b792-d810ff4f86a2 duration=29s: nemesis_name=MemoryStress target_node=Node longevity-large-partitions-2d-order-db-node-317fd90f-6 [34.254.228.235 | 10.4.3.140] (seed: False) errors=Encountered a bad command exit code!
Command: 'stress-ng --vm-bytes $(awk \'/MemAvailable/{printf "%d\\n", $2 * 1.2;}\' < /proc/meminfo)k --vm-keep -m 1 -t 100'
Exit code: 3
Stdout:
Stderr:
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/boot /boot none bind,ro 0 0): permission denied
stress-ng: info:  [11113] setting to a 100 second (1 min, 40.00 secs) run per stressor
stress-ng: info:  [11113] dispatching hogs: 1 vm
stress-ng: info:  [11146] vm: gave up trying to mmap, no available memory, skipping stressor
stress-ng: warn:  [11113] process [11145] (vm) aborted early, out of system resources
stress-ng: info:  [11113] passed: 0
stress-ng: info:  [11113] failed: 0
stress-ng: info:  [11113] skipped: 1: vm (1)
stress-ng: info:  [11113] successful run completed in 10.01s
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4427, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 256, in inner_func
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3838, in disrupt_memory_stress
self.target_node.remoter.run(
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'stress-ng --vm-bytes $(awk \'/MemAvailable/{printf "%d\\n", $2 * 1.2;}\' < /proc/meminfo)k --vm-keep -m 1 -t 100'
Exit code: 3
Stdout:
Stderr:
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/boot /boot none bind,ro 0 0): permission denied
stress-ng: info:  [11113] setting to a 100 second (1 min, 40.00 secs) run per stressor
stress-ng: info:  [11113] dispatching hogs: 1 vm
stress-ng: info:  [11146] vm: gave up trying to mmap, no available memory, skipping stressor
stress-ng: warn:  [11113] process [11145] (vm) aborted early, out of system resources
stress-ng: info:  [11113] passed: 0
stress-ng: info:  [11113] failed: 0
stress-ng: info:  [11113] skipped: 1: vm (1)
stress-ng: info:  [11113] successful run completed in 10.01s
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-2d-order-db-node-317fd90f-9 (52.208.240.115 | 10.4.3.68) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-8 (34.254.180.252 | 10.4.0.93) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-7 (63.35.202.225 | 10.4.3.175) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-6 (34.254.228.235 | 10.4.3.140) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-5 (34.252.186.239 | 10.4.2.24) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-4 (34.246.200.68 | 10.4.0.7) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-3 (63.33.196.101 | 10.4.0.58) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-2 (34.242.48.181 | 10.4.3.151) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-1 (34.253.210.75 | 10.4.1.78) (shards: 14)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-large-partition-2days-reversed-queries-test`
Test id: `317fd90f-934d-491b-8e04-ee44a177ec28`
Test name: `enterprise-2023.1/longevity/longevity-large-partition-2days-reversed-queries-test`
Test config file(s):

- [longevity-large-partition-2days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b39d0c385fc3f3b60a4852a5cb25c2034529580e/test-cases/longevity/longevity-large-partition-2days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 317fd90f-934d-491b-8e04-ee44a177ec28`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=317fd90f-934d-491b-8e04-ee44a177ec28)
- Show all stored logs command: `$ hydra investigate show-logs 317fd90f-934d-491b-8e04-ee44a177ec28`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-large-partition-2days-reversed-queries-test/3/)
</details>

**Comment by fruch** [comment]
seems like it's a snapd bug:
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1991691

even that I was fooled by this April 1st joke:
https://news.itsfoss.com/ubuntu-ditch-snap/
we should probably should install and use snaps

we should consider switching to a different tool for this nemesis, like:
https://chaos-mesh.org/docs/simulate-heavy-stress-in-physical-nodes/#simulating-memory-stress-using-the-command-line-mode

**Comment by yarongilor** [comment]
@fruch , couldn't we go for the option of aligning with k8s on using Chaos-mesh as it is already implemented by `class MemoryStressExperiment(ChaosMeshExperiment)` ?

**Comment by fruch** [comment]
> @fruch , couldn't we go for the option of aligning with k8s on using Chaos-mesh as it is already implemented by `class MemoryStressExperiment(ChaosMeshExperiment)` ?

that's kind of what I'm suggesting, beside we won't use k8s in VMs.
just the equivalent command tool from the same place

**Comment by roydahan** [comment]
Let's change this nemesis to not consume all the free memory but only 90%.
Also, let's verify that swap is configured correctly on scylla nodes.

**Comment by fruch** [comment]
> Let's change this nemesis to not consume all the free memory but only 90%. Also, let's verify that swap is configured correctly on scylla nodes.

it's doing both, not that I understand why:
```
        self.log.info('Try to allocate 120% available memory, the allocated memory will be swaped out')
        self.target_node.remoter.run(
            "stress-ng --vm-bytes $(awk '/MemAvailable/{printf \"%d\\n\", $2 * 1.2;}' < /proc/meminfo)k --vm-keep -m 1 -t 100")

        self.log.info('Try to allocate 90% total memory, the allocated memory will be swaped out')
        self.target_node.remoter.run(
            "stress-ng --vm-bytes $(awk '/MemTotal/{printf \"%d\\n\", $2 * 0.9;}' < /proc/meminfo)k --vm-keep -m 1 -t 100")
```

**Comment by roydahan** [comment]
So let's remove the part that it's consume 1.2 of memory size.

**Comment by fgelcer** [comment]
@yarongilor , not that this issue is fixed, is there anything else that requires to be fixed, before re-running the 2days reversed queries job?
