### ISSUE TITLE
collect_partitions_info: session.execute(count_pk_rows_cmd) timeouts with: Failed to collect partition info. Client request timeout

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6146]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

On currently running sct-runner the following file is empty:
sct-runner-1.6-instance-da817906 test-id: da817906-6710-4a13-b5d7-b4ee9ef7c87e
https://argus.scylladb.com/test/a388b58f-ff99-4bdb-b813-d07a2111d1d1/runs?additionalRuns[]=da817906-6710-4a13-b5d7-b4ee9ef7c87e

```
ubuntu@ip-10-4-2-240:~/sct-results/latest$ date
Wed May 17 15:36:46 UTC 2023
ubuntu@ip-10-4-2-240:~/sct-results/latest$ ll partitions_rows_before.log 
-rw-r--r-- 1 ubuntu ubuntu 0 May 15 16:59 partitions_rows_before.log
```
That happened because this query failure:
```
&lt; t:2023-05-15 16:59:25,941 f:longevity_test.py l:112  c:LargePartitionLongevityTest p:DEBUG &gt; Save partitions info before reads
&lt; t:2023-05-15 16:59:25,966 f:common.py       l:1656 c:utils                p:DEBUG &gt; Executing CQL 'select distinct pk from scylla_bench.test' ...
&lt; t:2023-05-15 16:59:25,966 f:common.py       l:1664 c:utils                p:DEBUG &gt; Executing CQL 'select distinct pk from scylla_bench.test' ...
&lt; t:2023-05-15 16:59:33,743 f:tester.py       l:2559 c:LargePartitionLongevityTest p:DEBUG &gt; Next PK: 19
&lt; t:2023-05-15 16:59:33,768 f:common.py       l:1656 c:utils                p:DEBUG &gt; Executing CQL 'select count(*) from scylla_bench.test where pk = 19 using timeout 5m' ...
&lt; t:2023-05-15 16:59:33,768 f:common.py       l:1664 c:utils                p:DEBUG &gt; Executing CQL 'select count(*) from scylla_bench.test where pk = 19 using timeout 5m' ...
&lt; t:2023-05-15 17:00:33,776 f:tester.py       l:2569 c:LargePartitionLongevityTest p:ERROR &gt; Failed to collect partition info. Error details: errors={'10.4.2.28:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.2.28:9042

```
perhaps it requires a paged query for this line:
https://github.com/scylladb/scylla-cluster-tests/blob/6d5d6c0b288144f36dbba51314096df2b919243f/sdcm/tester.py#L2571
( and why not also this line on the way https://github.com/scylladb/scylla-cluster-tests/blob/6d5d6c0b288144f36dbba51314096df2b919243f/sdcm/utils/common.py#L2930 )

Argus:
https://argus.scylladb.com/workspace?state=WyJhMzg4YjU4Zi1mZjk5LTRiZGItYjgxMy1kMDdhMjExMWQxZDEiXQ

https://argus.scylladb.com/test/da3835c5-80c5-4ba7-b882-ba4dae8db4f1/runs?additionalRuns[]=317fd90f-934d-491b-8e04-ee44a177ec28

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 4 nodes (i3en.3xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-4d-2023--db-node-da817906-8 (54.246.202.153 | 10.4.2.75) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-7 (3.252.123.16 | 10.4.1.81) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-6 (34.240.14.143 | 10.4.1.206) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-5 (3.252.189.146 | 10.4.2.59) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-4 (52.215.203.234 | 10.4.2.28) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-3 (52.17.133.79 | 10.4.3.170) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-2 (54.217.0.178 | 10.4.2.106) (shards: 10)
- longevity-large-partitions-4d-2023--db-node-da817906-1 (3.253.28.40 | 10.4.2.12) (shards: 10)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-large-partition-4days-test`
Test id: `da817906-6710-4a13-b5d7-b4ee9ef7c87e`
Test name: `enterprise-2023.1/longevity/longevity-large-partition-4days-test`
Test config file(s):

- [longevity-large-partition-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dafb96f428e2691c12e03508dc5024d85552043/test-cases/longevity/longevity-large-partition-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor da817906-6710-4a13-b5d7-b4ee9ef7c87e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=da817906-6710-4a13-b5d7-b4ee9ef7c87e)
- Show all stored logs command: `$ hydra investigate show-logs da817906-6710-4a13-b5d7-b4ee9ef7c87e`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-large-partition-4days-test/3/)
</details>

**Comment by fruch** [comment]
Can you give it a clearer title ?

I.e. not putting some line of code in the title.

But saying which part of SCT is failing and how

And yes if we read a whole partition in a large partition it might be big, and we might need bigger timeouts.

Didn't we test this code with large partitions ?

**Comment by fruch** [comment]
> > Can you give it a clearer title ?
> > I.e. not putting some line of code in the title.
> > But saying which part of SCT is failing and how
> > And yes if we read a whole partition in a large partition it might be big, and we might need bigger timeouts.
> > Didn't we test this code with large partitions ?
> 
> It is tested for long time now. the reason we didn't hit it is because of this line the 'skipped' the assertion:
> 
> https://github.com/scylladb/scylla-cluster-tests/blob/8e109359616ed1e50bba02dc060ecaacc2b2be2a/longevity_test.py#L158
> 
> should be fixed as well.

how many item would those things you are comparing should hold ? using assertEquals isn't very good if it has thousands  of rows
