### ISSUE TITLE
ModifyTable nemesis - `modify_table_twcs_window_size` generate unrecommended table configuration

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6153]
```
2023-05-16 02:08:51.356: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=dc481022-67de-4ec6-aee5-e6cfb298acc3: nemesis_name=ModifyTable target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-f7a
072d4-4 [34.249.51.228 | 10.4.2.134] (seed: False)
2023-05-16 02:08:53.036: (InfoEvent Severity.NORMAL) period_type=not-set event_id=a9cb4fdf-cf51-4d5a-af0b-b3950f0a9aee: message=ModifyTablePropertiesCompaction Node longevity-lwt-parallel-24h-2023-1-db-node-f7a0
72d4-4 [34.249.51.228 | 10.4.2.134] (seed: False)

< t:2023-05-16 02:12:13,604 f:nemesis.py      l:1921 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ModifyTableMonkey: _modify_table_property: ALTER TABLE cqlstress_lwt_example.blogposts WITH compaction = {'class
': 'TimeWindowCompactionStrategy'};


2023-05-16 02:12:16.562: (DisruptionEvent Severity.ERROR) period_type=end event_id=dc481022-67de-4ec6-aee5-e6cfb298acc3 duration=3m25s: nemesis_name=ModifyTable target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-4 [34.249.51.228 | 10.4.2.134] (seed: False) errors=<Error from server: code=2300 [Query invalid because of configuration issue] message="The setting of default_time_to_live=118079843 and compaction window=86400(s) can lead to 1366 windows, which is larger than the allowed number of windows specified by the twcs_max_window_count (50) parameter. Note that default_time_to_live=0 is also highly discouraged.">
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4370, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2604, in disrupt_modify_table
    disrupt_func()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2376, in modify_table_compaction
    self._modify_table_property(name="compaction", val=str(prop_val))
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1923, in _modify_table_property
    session.execute(cmd)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1657, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="The setting of default_time_to_live=118079843 and compaction window=86400(s) can lead to 1366 windows, which is larger than the allowed number of windows specified by the twcs_max_window_count (50) parameter. Note that default_time_to_live=0 is also highly discouraged.">
```
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-9 (3.250.109.85 | 10.4.1.49) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-8 (18.203.223.110 | 10.4.2.52) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-7 (34.244.199.69 | 10.4.2.204) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-6 (54.154.54.73 | 10.4.2.180) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-5 (34.255.6.153 | 10.4.1.2) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-4 (34.249.51.228 | 10.4.2.134) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-3 (18.202.235.51 | 10.4.2.207) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-2 (3.252.206.24 | 10.4.1.104) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-16 (52.48.130.233 | 10.4.2.21) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-15 (34.253.181.49 | 10.4.2.70) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-14 (34.241.112.227 | 10.4.0.168) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-13 (63.32.46.61 | 10.4.0.247) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-12 (3.250.11.52 | 10.4.3.162) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 (3.252.163.225 | 10.4.1.200) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-10 (3.250.50.18 | 10.4.0.86) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-1 (52.212.121.45 | 10.4.0.88) (shards: 7)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test id: `f7a072d4-311b-4f08-ac18-97c9a39b8378`
Test name: `enterprise-2023.1/longevity/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dafb96f428e2691c12e03508dc5024d85552043/test-cases/longevity/longevity-lwt-parallel-24h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f7a072d4-311b-4f08-ac18-97c9a39b8378`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f7a072d4-311b-4f08-ac18-97c9a39b8378)
- Show all stored logs command: `$ hydra investigate show-logs f7a072d4-311b-4f08-ac18-97c9a39b8378`

## Logs:
- **db-cluster-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz)
- **sct-runner-events-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz)
- **sct-f7a072d4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz)
- **monitor-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz)
- **loader-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test/4/)
</details>

**Comment by fruch** [comment]
this change in ModifyTable nemesis was introduced in:
https://github.com/scylladb/scylla-cluster-tests/pull/4655

**Comment by fruch** [comment]
@aleksbykov @temichus 

seems like `set_new_twcs_settings` is generating unrecommanded TWCS configurations.
I'm not sure I was able to warp my head around the logic there, lost of "magic" calculations/numbers I'm not sure where they are coming from.

**Comment by k0machi** [comment]
@fruch 
> set_new_twcs_settings 

That is not the case, the nemesis in that is actually `modify_table_compaction`, and the issue here is the entire function:
```
    def modify_table_compaction(self):
        """
            The compaction property defines the compaction strategy class for this table.
            default: compaction = {'class': 'SizeTieredCompactionStrategy'}
        """
        # TODO: Sub-properties for each of compaction strategies should also be tested
        strategies = ("SizeTieredCompactionStrategy",
                      "TimeWindowCompactionStrategy", "LeveledCompactionStrategy")
        prop_val = {"class": random.choice(strategies)}
        self._modify_table_property(name="compaction", val=str(prop_val))
```
Since it doesn't provide subproperties for each compaction strategy at all, Scylla takes previous dttl and gc values:
```
cassandra@cqlsh> SELECT default_time_to_live as dttl, gc_grace_seconds as gc, compaction from system_schema.tables WHERE keyspace_name='cqlstress_lwt_example' and table_name='blogposts';

 dttl      | gc     | compaction
-----------+--------+-------------------------------------------
 423595929 | 663654 | {'class': 'SizeTieredCompactionStrategy'}

(1 rows)
cassandra@cqlsh> ALTER TABLE cqlstress_lwt_example.blogposts WITH compaction = {'class': 'TimeWindowCompactionStrategy'};
ConfigurationException: The setting of default_time_to_live=423595929 and compaction window=86400(s) can lead to 4902 windows, which is larger than the allowed number of windows specified by the twcs_max_window_count (50) parameter. Note that default_time_to_live=0 is also highly discouraged.
```

And it fails. What should be done here? Should we remove TWCS as an option from here for now or introduce logic that will calculate correct values for TWCS here? (perhaps using `set_new_twcs_settings`)

cc @roydahan @temichus @aleksbykov
