### ISSUE TITLE
Allow hydra and other tests to use AMIs created in a new AWS releng account

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylla-cluster-tests#6163]
**Motivation:**

As part of AWS cost reduction and usage tracking, we are moving AMIs creation to separate AWS releng account `158855661827`.
New AMIs will be created under releng account and will be shared with other AWS accounts to allow use it.
In addition, the defined tags of the AMIs are created but they are not available for other accounts.

**Implementation:**
Follow this change need to make adjustments to allow hydra and other tests use these AMIs.

ref: https://github.com/scylladb/scylla-pkg/issues/3312

**Comment by fruch** [comment]
@Annamikhlin 

Seems like it's a simple change to add the new account into the code,

But, we still need the tags, seem like we can recreate the tags in the main AWS account for each image that is being created
without it we won't be able to search for images, like we are doing today (and on other clouds)

**Comment by fgelcer** [comment]
> @Annamikhlin
> 
> Seems like it's a simple change to add the new account into the code,
> 
> But, we still need the tags, seem like we can recreate the tags in the main AWS account for each image that is being created without it we won't be able to search for images, like we are doing today (and on other clouds)

and AFAICT we will need to support, for now, new and old accounts
