### ISSUE TITLE
"start_and_interrupt_decommission_streaming" waits static and too small amount of time

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6181]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 2023.1.0~rc5-20230429.a47bcb26e42e

### Logs
* test_id: da817906-6710-4a13-b5d7-b4ee9ef7c87e
* job log: [Argus](https://argus.scylladb.com/test/a388b58f-ff99-4bdb-b813-d07a2111d1d1/runs?additionalRuns[]=da817906-6710-4a13-b5d7-b4ee9ef7c87e), [CI job](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-large-partition-4days-test/3)

### Description

The `start_and_interrupt_decommission_streaming` method in the `nemesis.py` module picks up random stage of the decommission
process as trigger for the next step:

```
        terminate_patterns = self.target_node.raft.get_log_patterns_for_decommission_abort()            
        self.use_nemesis_seed()                                                                         
        terminate_pattern = random.choice(terminate_patterns)
```

Where the values available for random pick up are following:
```
        return ["DECOMMISSIONING: unbootstrap starts",                                                 
                "DECOMMISSIONING: unbootstrap done",                                                   
                "becoming a group 0 non-voter",                                                        
                "became a group 0 non-voter",                                                          
                "leaving token ring",                                                                  
                "left token ring",                                                                     
                "Finished token ring movement"]
```

Each of them will be awaited 1200 at max.
In current case was picked up following one:
```
< t:2023-05-19 11:44:02,356 f:nemesis.py      l:3442 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Reboot node after log message: 'left token ring'
```

Decommission start:
```
2023-05-19T11:44:03+00:00 longevity-large-partitions-4d-2023--db-node-da817906-8     !INFO | scylla[7273]:  [shard 0] storage_service - DECOMMISSIONING: starts
```

The expected message:
```
2023-05-19T12:22:46+00:00 longevity-large-partitions-4d-2023--db-node-da817906-8     !INFO | scylla[7273]:  [shard 0] storage_service - decommission[c3810463-df5c-471b-b42d-a81d93cad59d]: left token ring
```

We see that the time diff is about 39 minutes whereas the timeout is just 20 minutes.

So, at first the timeout is too small and , at second, the expected stages must have it's own timeout values.
For example, the start of the decommission process happens pretty fast and it must be error if we reach it, for example, after 1199 seconds.

### Steps to Reproduce

1. Run large partitions job and `disrupt_decommission_streaming_err` nemesis
2. Make sure that was picked up one of the latest decommission stages as an awaiting point.
3. See timeout

**Expected behavior:** wait time must be aligned with the target stage.

**Actual behavior:** wait time is fixed and small enough to reach wait timeouts.

**Comment by roydahan** [comment]
@aleksbykov can you please take a look?

**Comment by aleksbykov** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/6360

**Comment by aleksbykov** [comment]
Pr is updated. Stabilizing the jobs to get nemesis green. Once it will be done,

**Comment by aleksbykov** [comment]
Staging job 1 nemesis are passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/nemesis-clone/job/longevity-5gb-1h-DecommissionStreamingErrMonkey-aws-test/ latest three times

**Comment by aleksbykov** [comment]
Stablizing jobs for aws, azure, gce
On aws already got green results
waiting gce and azure

**Comment by aleksbykov** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/6360

**Comment by fruch** [comment]
@aleksbykov is this issue solved ?

**Comment by aleksbykov** [comment]
@fruch i checked several latest jobs , and DecommissionStreamErr passed during them.
@vponomaryov did you meet any failures with this nemesis in Operator tests last 2 weeks with sct master branch?

**Comment by vponomaryov** [comment]
@aleksbykov lately @fruch and @soyacz were running related jobs.
So, personally, I don't have info about the recent nemesis results for operator.

**Comment by fruch** [comment]
@aleksbykov in the last two weeks there wasn't any issues related to DecommissionStreamErr in operator tests

**Comment by aleksbykov** [comment]
@fruch , then i think we can conclude that issue was fixed for now
