### ISSUE TITLE
Row amount in partitions is not same before and after running of nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6183]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Ran the 2d large partitions reversed queries test.
It uses the validate-partitions that compares rows-per-partition after prepare and at the end of test after nemeses are done.
The validation failed with:
```
self.assertEqual(partitions_dict_before, partitions_dict_after,
AssertionError: {655: 50000, 111: 50000, 412: 50000, 332: [9443 chars]0000} != {990: 50000, 655: 50000, 937: 50000, 111: [11844 chars]0000}
Diff is 14938 characters long. Set self.maxDiff to None to see it. : Row amount in partitions is not same before and after running of nemesis
```

This validation can now be better re-tested following the fix of https://github.com/scylladb/scylla-cluster-tests/pull/6155
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-2d-order-db-node-317fd90f-9 (52.208.240.115 | 10.4.3.68) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-8 (34.254.180.252 | 10.4.0.93) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-7 (63.35.202.225 | 10.4.3.175) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-6 (34.254.228.235 | 10.4.3.140) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-5 (34.252.186.239 | 10.4.2.24) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-4 (34.246.200.68 | 10.4.0.7) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-3 (63.33.196.101 | 10.4.0.58) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-2 (34.242.48.181 | 10.4.3.151) (shards: 14)
- longevity-large-partitions-2d-order-db-node-317fd90f-1 (34.253.210.75 | 10.4.1.78) (shards: 14)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-large-partition-2days-reversed-queries-test`
Test id: `317fd90f-934d-491b-8e04-ee44a177ec28`
Test name: `enterprise-2023.1/longevity/longevity-large-partition-2days-reversed-queries-test`
Test config file(s):

- [longevity-large-partition-2days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b39d0c385fc3f3b60a4852a5cb25c2034529580e/test-cases/longevity/longevity-large-partition-2days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 317fd90f-934d-491b-8e04-ee44a177ec28`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=317fd90f-934d-491b-8e04-ee44a177ec28)
- Show all stored logs command: `$ hydra investigate show-logs 317fd90f-934d-491b-8e04-ee44a177ec28`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-large-partition-2days-reversed-queries-test/3/)
[Argus](https://argus.scylladb.com/test/da3835c5-80c5-4ba7-b882-ba4dae8db4f1/runs?additionalRuns[]=317fd90f-934d-491b-8e04-ee44a177ec28)
</details>

**Comment by fruch** [comment]
Which nemesis, any nemesis ?

What is the difference? data is lost, or data is added ?

If data is added, sounds reasonable since s-b continues to read while nemesis takes place.

**Comment by yarongilor** [comment]
@fruch any preference for the above options?

**Comment by fruch** [comment]
> @fruch any preference for the above options? 

Why not both ?

**Comment by yarongilor** [comment]
> > @fruch any preference for the above options?
> 
> Why not both ?

OK, a synthesis of both options might be possible as well:
Let's say `prepare` writes 100 partitions
and `partition_range_with_data_validation` = 0 - 50
Then `validate_partition` will take the minimum (intersection) like `min(prepare,partition_range_with_data_validation)`.
So only the first 50 partitions would be validated, in this example, while partitions 51 - 100 might be deleted by nemesis.

**Comment by roydahan** [comment]
> > > @fruch any preference for the above options?
> > 
> > 
> > Why not both ?
> 
> OK, a synthesis of both options might be possible as well: Let's say `prepare` writes 100 partitions and `partition_range_with_data_validation` = 0 - 50 Then `validate_partition` will take the minimum (intersection) like `min(prepare,partition_range_with_data_validation)`. So only the first 50 partitions would be validated, in this example, while partitions 51 - 100 might be deleted by nemesis.

It depends what the tests are doing.
First, we need to add a comment in each test yaml that relies on such logic to explain that.
Second, the validate_parition should run on:
1. range of partitions that isn't growing after the prepare (do we even have such a thing?)
2. range of partitions that isn't being deleted after the prepare.

so, I don't know if it's the intersection you mentioned above, please make sure of that and in each test, a comment in the test yaml should make it very clear.
