### ISSUE TITLE
[K8S] logging failure to stop thread

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6191]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During some `DrainKubernetesNodeThenDecommissionAndAddScyllaNode` the node  remote_logger is being stopped
but missing the stream object doesn't seem to have a fp opened yet.
```
2023-05-28 02:11:23.113: (DisruptionEvent Severity.ERROR) period_type=end event_id=cd203588-b5bd-4f0b-aad0-ef4e21ea69d0 duration=6m46s: nemesis_name=DrainKubernetesNodeThenDecommissionAndAddScyllaNode target_node=Node sct-cluster-2-us-east1-b-us-east1-1 [10.0.3.94 | 10.0.3.253] (seed: False) errors='NoneType' object has no attribute 'fileno'
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4424, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1415, in disrupt_drain_kubernetes_node_then_decommission_and_add_scylla_node
self._disrupt_kubernetes_then_decommission_and_add_scylla_node('drain_k8s_node')
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1438, in _disrupt_kubernetes_then_decommission_and_add_scylla_node
self.cluster.decommission(node, timeout=MAX_TIME_WAIT_FOR_DECOMMISSION)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 2810, in decommission
self.terminate_node(node, scylla_shards=scylla_shards)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 2791, in terminate_node
node.destroy()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1148, in destroy
self.stop_task_threads()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1098, in stop_task_threads
self._journal_thread.stop(timeout=5)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remote_logger.py", line 357, in stop
sock_obj = socket.fromfd(self._stream.fileno(), socket.AF_INET, socket.SOCK_STREAM)
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 716, in fileno
return self._fp.fileno()
File "/usr/local/lib/python3.10/http/client.py", line 711, in fileno
return self.fp.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.10.178-162.673.amzn2.x86_64
Scylla version (or git commit hash): `5.4.0~dev-20230527.e4d6ed7a7048` with build-id `6dc67925bbb00bf45be5af823788c65688817efb`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.4-14-gdb443d0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-multitenant-eks`
Test id: `af89b4c9-72dd-4119-b54f-94a37390fea0`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-multitenant-eks`
Test config file(s):

- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a6ae24d95c1e8854e24b1f4373dc7688a1f63279/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor af89b4c9-72dd-4119-b54f-94a37390fea0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=af89b4c9-72dd-4119-b54f-94a37390fea0)
- Show all stored logs command: `$ hydra investigate show-logs af89b4c9-72dd-4119-b54f-94a37390fea0`

## Logs:
- **db-cluster-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/db-cluster-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/db-cluster-af89b4c9.tar.gz)
- **sct-runner-events-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/sct-runner-events-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/sct-runner-events-af89b4c9.tar.gz)
- **sct-af89b4c9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/sct-af89b4c9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/sct-af89b4c9.log.tar.gz)
- **monitor-set-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/monitor-set-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/monitor-set-af89b4c9.tar.gz)
- **loader-set-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/loader-set-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/loader-set-af89b4c9.tar.gz)
- **kubernetes-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/kubernetes-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/kubernetes-af89b4c9.tar.gz)
- **parallel-timelines-report-af89b4c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/parallel-timelines-report-af89b4c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/af89b4c9-72dd-4119-b54f-94a37390fea0/20230528_031318/parallel-timelines-report-af89b4c9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks/48/)
[Argus](https://argus.scylladb.com/test/7774c24a-b749-4528-97a4-22785e7e5b6f/runs?additionalRuns[]=af89b4c9-72dd-4119-b54f-94a37390fea0)
</details>

**Comment by soyacz** [comment]
Happened again - quite the same situation:

## Installation details

Kernel Version: 5.15.0-1044-gke
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`


Operator Image: scylladb/scylla-operator:1.11
Operator Helm Version: 1.11.0-rc.2
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylladb:2023.1.1` (k8s-gke: undefined_region)

Test: `longevity-scylla-operator-3h-gke`
Test id: `c3c23190-2540-45aa-9a22-bedaff17eb4d`
Test name: `scylla-operator/operator-1.11/gke/longevity-scylla-operator-3h-gke`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/da34dfbaea6e21f713423f6ef6ab25b361c67821/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor c3c23190-2540-45aa-9a22-bedaff17eb4d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c3c23190-2540-45aa-9a22-bedaff17eb4d)
- Show all stored logs command: `$ hydra investigate show-logs c3c23190-2540-45aa-9a22-bedaff17eb4d`


## Logs:
- **kubernetes-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/kubernetes-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/kubernetes-c3c23190.tar.gz)
- **db-cluster-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/db-cluster-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/db-cluster-c3c23190.tar.gz)
- **sct-runner-events-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/sct-runner-events-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/sct-runner-events-c3c23190.tar.gz)
- **sct-c3c23190.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/sct-c3c23190.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/sct-c3c23190.log.tar.gz)
- **loader-set-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/loader-set-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/loader-set-c3c23190.tar.gz)
- **monitor-set-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/monitor-set-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/monitor-set-c3c23190.tar.gz)
- **parallel-timelines-report-c3c23190.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/parallel-timelines-report-c3c23190.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c3c23190-2540-45aa-9a22-bedaff17eb4d/20231016_093143/parallel-timelines-report-c3c23190.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.11/job/gke/job/longevity-scylla-operator-3h-gke/5/)
[Argus](https://argus.scylladb.com/test/3b523fd6-a2a2-49ed-86e1-53da1900be0f/runs?additionalRuns[]=c3c23190-2540-45aa-9a22-bedaff17eb4d)
</details>

**Comment by fruch** [comment]
Still happening 

## Installation details

Kernel Version: 5.15.0-1047-gke
Scylla version (or git commit hash): `5.5.0~dev-20240105.7e84e03f5231` with build-id `f21e4548b69223a75d01fd3bb9d4c9c2b1b71a6d`


Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-144-g60f7824
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylladb:5.5.0-dev-0.20240105.7e84e03f5231` (k8s-gke: undefined_region)

Test: `longevity-scylla-operator-3h-gke`
Test id: `f37bf383-7a0f-4f26-9f93-9a7987446305`
Test name: `scylla-operator/operator-master/gke/longevity-scylla-operator-3h-gke`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9c5b107ff97e06abf74f651d7650c481bc692548/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor f37bf383-7a0f-4f26-9f93-9a7987446305`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f37bf383-7a0f-4f26-9f93-9a7987446305)
- Show all stored logs command: `$ hydra investigate show-logs f37bf383-7a0f-4f26-9f93-9a7987446305`


## Logs:
- **kubernetes-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/kubernetes-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/kubernetes-f37bf383.tar.gz)
- **kubernetes-must-gather-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/kubernetes-must-gather-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/kubernetes-must-gather-f37bf383.tar.gz)
- **db-cluster-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/db-cluster-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/db-cluster-f37bf383.tar.gz)
- **sct-runner-events-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/sct-runner-events-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/sct-runner-events-f37bf383.tar.gz)
- **sct-f37bf383.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/sct-f37bf383.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/sct-f37bf383.log.tar.gz)
- **loader-set-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/loader-set-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/loader-set-f37bf383.tar.gz)
- **monitor-set-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/monitor-set-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/monitor-set-f37bf383.tar.gz)
- **parallel-timelines-report-f37bf383.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/parallel-timelines-report-f37bf383.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f37bf383-7a0f-4f26-9f93-9a7987446305/20240107_044036/parallel-timelines-report-f37bf383.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke/66/)
[Argus](https://argus.scylladb.com/test/b9f7805a-73c8-45a1-9846-5826da89bcb9/runs?additionalRuns[]=f37bf383-7a0f-4f26-9f93-9a7987446305)
</details>
