### ISSUE TITLE
cassandra-stress doesn't support passing `replication_factor` for NetworkTopologyStrategy

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6241]
cassandra-stress doesn't support passing `replication_factor` for NetworkTopologyStrategy

there are some check we'll need to remove from the code:
```
 ❯ grep -inr "is an option for SimpleStrategy, not NetworkTopologyStrategy" ./
./src/java/org/apache/cassandra/locator/NetworkTopologyStrategy.java:71:                    throw new ConfigurationException("replication_factor is an option for SimpleStrategy, not NetworkTopologyStrategy");
./src/java/org/apache/cassandra/locator/NetworkTopologyStrategy.java:227:                throw new ConfigurationException("replication_factor is an option for SimpleStrategy, not NetworkTopologyStrategy");
```

meanwhile we have an issue cause lots of code now changed with this option, and it won't working without precreating of schemas

## Installation details

Kernel Version: 5.15.0-1034-gke
Scylla version (or git commit hash): `2021.1.19-20230413.0c75931d2e` with build-id `e33e6faa25fc85927227e488480eaea3147f7ecb`

Operator Image: scylladb/scylla-operator:1.9.0-rc.0
Operator Helm Version: 1.9.0-rc.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 3 nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylladb:5.2.1` (k8s-gke: undefined_region)

Test: `upgrade-major-scylla-k8s-gke`
Test id: `a8804166-2463-4d72-86e9-8a6e738d2043`
Test name: `scylla-operator/operator-1.9/upgrade/upgrade-major-scylla-k8s-gke`
Test config file(s):

- [kubernetes-scylla-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f16a57385c2ee1cd38b99355bacc498760d1b1fa/test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a8804166-2463-4d72-86e9-8a6e738d2043`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a8804166-2463-4d72-86e9-8a6e738d2043)
- Show all stored logs command: `$ hydra investigate show-logs a8804166-2463-4d72-86e9-8a6e738d2043`

## Logs:
- **db-cluster-a8804166.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/db-cluster-a8804166.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/db-cluster-a8804166.tar.gz)
- **sct-runner-events-a8804166.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/sct-runner-events-a8804166.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/sct-runner-events-a8804166.tar.gz)
- **sct-a8804166.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/sct-a8804166.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/sct-a8804166.log.tar.gz)
- **monitor-set-a8804166.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/monitor-set-a8804166.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/monitor-set-a8804166.tar.gz)
- **loader-set-a8804166.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/loader-set-a8804166.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/loader-set-a8804166.tar.gz)
- **kubernetes-a8804166.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/kubernetes-a8804166.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8804166-2463-4d72-86e9-8a6e738d2043/20230611_214824/kubernetes-a8804166.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/upgrade/job/upgrade-major-scylla-k8s-gke/3/)
[Argus](https://argus.scylladb.com/test/3c0abddb-2b00-4dac-ac1d-df999ff8fcc8/runs?additionalRuns[]=a8804166-2463-4d72-86e9-8a6e738d2043)
</details>

**Comment by roydahan** [comment]
??? What?
Doesn't It mean that almost all of our tests are broken now??

**Comment by fruch** [comment]
> ??? What?
> Doesn't It mean that almost all of our tests are broken now??

1) No one is looking at master runs ?

2) we are using precreate much more than we think we do ?

If there would be more reports of it, I'll revert, regardless it should be a very easy fix to c-s

**Comment by roydahan** [comment]
For a test I'm working on it passed without any issue, so I don't know what exactly is broken.

**Comment by fruch** [comment]
> For a test I'm working on it passed without any issue, so I don't know what exactly is broken.

can you point to that test ? cause the c-s code is quite specific...

**Comment by fruch** [comment]
o.k. tested it with dtest

and seems like branch 2021.1 doesn't work and newer branch are working

this is upgrade test that started by mistake from 2021.1

**Comment by soyacz** [comment]
So, do we need to fix it in upgrade tests?

**Comment by fruch** [comment]
No, I think we could leave it alone, and if we'll need to use 2021.1 or we'll use it's branch or fix a specific case to not use NetworkTopology
