### ISSUE TITLE
collect also `scylla-manager-agent.yaml` on each node, if has manager

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#6243]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by fruch** [comment]
scylla-manager-agent.py ? what is this file ?

**Comment by fgelcer** [comment]
> scylla-manager-agent.py ? what is this file ?

meant to write `scylla-manager-agent.yaml`

@ShlomiBalalis can tell better, but earlier today, when checking with @ricardoborenstein about an issue on manager using IPv6, we saw that we don't have this configuration of the manager agent...
i'm not sure we do have many useful information in there, but in the issue afromentioned, the customer shared the `scylla-manager-agent.yaml` and we can just saved it in the collected logs of each node

**Comment by ShlomiBalalis** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/6310

**Comment by fruch** [comment]
> https://github.com/scylladb/scylla-cluster-tests/pull/6310

It's better if you mention this issue in the commit/PR you write this issue is fixed

**Comment by ShlomiBalalis** [comment]
> > #6310
> 
> It's better if you mention this issue in the commit/PR you write this issue is fixed

I did not notice it was an SCT ticket, I will edit the commit message
