### ISSUE TITLE
[K8S-GKE] recreation of a Scylla pod on a recreated K8S Scylla node fails due to presence of old PV

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6312]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 2022.2.6-20230423.b9a1478dba07

### Logs
* test_id: 283a201c-789c-4562-9294-1d949a7675ae
* job log: [Argus](https://argus.scylladb.com/test/5c32ee82-a403-40cf-aa96-8ab6b68626fa/runs?additionalRuns[]=283a201c-789c-4562-9294-1d949a7675ae), [CI](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/gke/job/longevity-scylla-operator-basic-12h-gke/2/consoleFull)

### Description

Running `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node` nemesis on the GKE backend using
the `static local volume provisioner` we get the following failure on the second run of the nemesis:

```
scylla    117s     Warning   FailedScheduling    pod/sct-cluster-us-east1-b-us-east1-2    default-scheduler  \
    0/8 nodes are available: 2 Insufficient cpu, 2 Insufficient memory, 2 node(s) didn't find available persistent volumes to bind, \
    4 node(s) didn't match Pod's node affinity/selector. preemption: 0/8 nodes are available: \
    2 No preemption victims found for incoming pod, 6 Preemption is not helpful for scheduling.   \
        9h           114     sct-cluster-us-east1-b-us-east1-2.1767b081e100369b
```

Pod list:
```
sct-cluster-us-east1-b-us-east1-0   2/2   Running   1 (12h ago)   12h   10.92.5.6    gke-longev-scylla-operat--scylla-pool-52dc42c3-pj75
sct-cluster-us-east1-b-us-east1-1   2/2   Running   0             10h   10.92.6.9    gke-longev-scylla-operat--scylla-pool-52dc42c3-w8kr
sct-cluster-us-east1-b-us-east1-2   0/2   Pending   0             9h    <none>       <none>
```

PV list:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                          STORAGECLASS       REASON   AGE   VOLUMEMODE
local-pv-4ae559ad                          1124Gi     RWO            Delete           Bound      scylla/data-sct-cluster-us-east1-b-us-east1-1                  local-raid-disks            12h   Filesystem
local-pv-d7c7df19                          1124Gi     RWO            Delete           Bound      scylla/data-sct-cluster-us-east1-b-us-east1-0                  local-raid-disks            12h   Filesystem
local-pv-dd431f1d                          1124Gi     RWO            Delete           Released   scylla/data-sct-cluster-us-east1-b-us-east1-2                  local-raid-disks            12h   Filesystem
local-pv-ebb52953                          1124Gi     RWO            Delete           Released   scylla/data-sct-cluster-us-east1-b-us-east1-2                  local-raid-disks            9h    Filesystem
pvc-7e14ef0e-a087-491e-a084-2bcc00ff4dd5   10Gi       RWO            Delete           Bound      scylla-manager/data-scylla-manager-manager-dc-manager-rack-0   standard-rwo                13h   Filesystem
pvc-8e7209cf-0489-4a5c-bb12-8c8824eba239   900Gi      RWO            Delete           Bound      minio/minio                                                    standard-rwo                13h   Filesystem
```

Volume provisioner:
```
I0611 18:43:40.759454       1 discovery.go:384] Found new volume at host path "/mnt/raid-disks/disk0/pv-01" with capacity 1206950502400, creating Local PV "local-pv-dd431f1d", required volumeMode "Filesystem"
E0611 18:43:40.771794       1 discovery.go:220] Failed to discover local volumes: 1 error(s) while discovering volumes: [error creating PV "local-pv-dd431f1d" for volume at "/mnt/raid-disks/disk0/pv-01": persistentvolumes "local-pv-dd431f1d" already exists]
...
<lots of the same messages>
```

One another volume provisioner:
```
I0611 19:11:16.789013       1 discovery.go:384] Found new volume at host path "/mnt/raid-disks/disk0/pv-01" with capacity 1206950502400, creating Local PV "local-pv-ebb52953", required volumeMode "Filesystem"
E0611 19:11:16.802146       1 discovery.go:220] Failed to discover local volumes: 1 error(s) while discovering volumes: [error creating PV "local-pv-ebb52953" for volume at "/mnt/raid-disks/disk0/pv-01": persistentvolumes "local-pv-ebb52953" already exists]
...
<lots of the same messages>
```

### Steps to Reproduce

1. Create a GKE cluster with 4 nodes dedicated for Scylla
2. Deploy scylla-operator on the GKE backend using the static local volume provisioner.
3. Deploy 3-member Scylla cluster
4. Run the `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node` nemesis twice
5. See scheduling error on the second nemesis run.

**Expected behavior:** Scylla pod must be created

**Actual behavior:** New PV doesn't get created, old doesn't get reused.

**Comment by fruch** [comment]
> So, probably we need to delete old PVs between `previous Scylla pod decommission end` and `scheduling of a new Scylla pod` operations.

Isn't that the operator's job to handle it ? or cause we don't have the provisioner in GKE ?

**Comment by vponomaryov** [comment]
> > So, probably we need to delete old PVs between `previous Scylla pod decommission end` and `scheduling of a new Scylla pod` operations.
> 
> Isn't that the operator's job to handle it ? or cause we don't have the provisioner in GKE ?

In GKE we `use` non-scylla-operator provisioning of PVs.
But I haven't tried the dynamic provisioner from the scylla-operator on GKE.
Probably need to try it out.

**Comment by vponomaryov** [comment]
Upd: I tried it out on top of the this PR: https://github.com/scylladb/scylla-cluster-tests/pull/6292
So, after merge of that PR I will upload the change with dynamic storage for GKE.

**Comment by vponomaryov** [comment]
Fixed here: https://github.com/scylladb/scylla-cluster-tests/pull/6292
