### ISSUE TITLE
SCT fails with `OSError: [Errno 98] Address already in use` 

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#6345]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The `artifacts-ubuntu2204-arm-test` job failed with the error:
```
14:36:24  < t:2023-07-09 11:36:24,227 f:test_config.py  l:296  c:sdcm.test_config     p:INFO  > Initializing Argus connection...
14:36:24  < t:2023-07-09 11:36:24,703 f:tester.py       l:390  c:ArtifactsTest        p:INFO  > test_id 707e495b-0757-47c6-966e-4a613fa62c4f already exists in Argus with status: created
14:36:25  < t:2023-07-09 11:36:24,849 f:tester.py       l:405  c:ArtifactsTest        p:INFO  > sct_runner info in Argus TestRun is updated
14:36:26  Process SyncManager-3:
14:36:26  Traceback (most recent call last):
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
14:36:26      self.run()
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
14:36:26      self._target(*self._args, **self._kwargs)
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/managers.py", line 591, in _run_server
14:36:26      server = cls._Server(registry, address, authkey, serializer)
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/managers.py", line 156, in __init__
14:36:26      self.listener = Listener(address=address, backlog=16)
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 453, in __init__
14:36:26      self._listener = SocketListener(address, family, backlog)
14:36:26    File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 596, in __init__
14:36:26      self._socket.bind(address)
14:36:26  OSError: [Errno 98] Address already in use
14:36:26  
14:36:26  Aborted!
```
The error happened at the very beginning of the execution of `Run SCT Test ()` stage of the pipeline, when `ClusterTester` was being initialized - the test didn't really start.

## How frequently does it reproduce?

It reproduced in many other artifacts jobs
`scylla-master`:
- [artifacts-rocky9-test](https://argus.scylladb.com/test/b6c1fc13-a7c0-4b05-ab4d-b1e9c54ac4d3/runs?additionalRuns[]=78f8afbf-7bed-4b44-b3b8-1c1fc2d37493)
- [artifacts-ubuntu2204-nonroot-test](https://argus.scylladb.com/test/0be0e4d6-2dc6-46a4-a938-ebece4b425b1/runs?additionalRuns[]=6d1cef6d-9c34-4e38-85ab-b83332b0f443)
- [artifacts-debian11-test](https://argus.scylladb.com/test/4caedf92-5700-4989-b981-ab2de693ce08/runs?additionalRuns[]=f936495c-79bd-4dfa-8eb7-625925cf91f2)
- [artifacts-ubuntu2204-arm-test](https://argus.scylladb.com/test/662308fc-5042-473f-963e-f337656df2b3/runs?additionalRuns[]=8300e26e-add4-41e5-b458-71db855d0134)
- [artifacts-debian11-nonroot-test](https://argus.scylladb.com/test/86eef0ae-3852-4d5d-ab79-65d25aa314d2/runs?additionalRuns[]=aec9c4f6-dc8d-4459-af9a-48edf5a7065c)
- [artifacts-rocky9-nonroot-test](https://argus.scylladb.com/test/f93cfada-a14d-420f-a7b5-8f40d9dfdaa7/runs?additionalRuns[]=f6e5a60c-6411-437a-a91f-2084c82e337f)

`scylla-enterprise`:
- [artifacts-ubuntu2204-test](https://argus.scylladb.com/test/8487999c-b90b-4f59-b216-c4145b983a50/runs?additionalRuns[]=0f73031d-7b24-443b-be17-d6414f60d718)
- [artifacts-rocky8-test](https://argus.scylladb.com/test/870b78f2-c087-46e3-8022-24f2c15f3802/runs?additionalRuns[]=f4ed822e-ce6c-4e10-8666-9ccb2d42448d)
- [artifacts-centos8-arm-test](https://argus.scylladb.com/test/e2f8b4c8-cccd-4a87-a86e-8af7f19e77fc/runs?additionalRuns[]=a0fbe522-7206-447f-9e3e-01a9843aca60)
- [artifacts-ubuntu2204-arm-test](https://argus.scylladb.com/test/f61ee749-cd0f-40a2-bd53-79d1cbf5ce95/runs?additionalRuns[]=3069da4c-ff85-47d8-b97c-6f5381c71e2e)

and more

## Installation details

Cluster size: 1 nodes (im4gn.xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `ami-022c8ce295ce9ac4c` (aws: undefined_region)

Test: `artifacts-ubuntu2204-arm-test`
Test id: `707e495b-0757-47c6-966e-4a613fa62c4f`
Test name: `scylla-master/artifacts/artifacts-ubuntu2204-arm-test`
Test config file(s):

- [ubuntu2204.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c34f91b1a83f9848be2ae1027d5cc64fe0b864fa/test-cases/artifacts/ubuntu2204.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 707e495b-0757-47c6-966e-4a613fa62c4f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=707e495b-0757-47c6-966e-4a613fa62c4f)
- Show all stored logs command: `$ hydra investigate show-logs 707e495b-0757-47c6-966e-4a613fa62c4f`

## Logs:
- **sct-runner-events-707e495b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/707e495b-0757-47c6-966e-4a613fa62c4f/20230709_113636/sct-runner-events-707e495b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/707e495b-0757-47c6-966e-4a613fa62c4f/20230709_113636/sct-runner-events-707e495b.tar.gz)
- **sct-707e495b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/707e495b-0757-47c6-966e-4a613fa62c4f/20230709_113636/sct-707e495b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/707e495b-0757-47c6-966e-4a613fa62c4f/20230709_113636/sct-707e495b.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-arm-test/189/)
[Argus](https://argus.scylladb.com/test/45b30fee-7ba3-42e3-92f7-f7cbf3a52364/runs?additionalRuns[]=707e495b-0757-47c6-966e-4a613fa62c4f)
</details>

**Comment by soyacz** [comment]
@aleksbykov isn't it related to manager you added recently in https://github.com/scylladb/scylla-cluster-tests/pull/6302?
Maybe we can postpone starting it when needed only?

**Comment by aleksbykov** [comment]
@soyacz , yes looks it is related to that code. It failed when try to initialize the new process event for counter. But it seems internal python errro, so event if it will be initialized lately, it will get same error, because addr will in used anyway. May be i am wrong.  As workaround, i can add try except on launching this event-process, so start of it doesn't fail the test? WDYT?

with perf and longevities i didn't catch such error.

**Comment by soyacz** [comment]
> @soyacz , yes looks it is related to that code. It failed when try to initialize the new process event for counter. But it seems internal python errro, so event if it will be initialized lately, it will get same error, because addr will in used anyway. May be i am wrong. As workaround, i can add try except on launching this event-process, so start of it doesn't fail the test? WDYT?

We don't count events in ArtifactTests, so this could be a workaround.

> 
> with perf and longevities i didn't catch such error.

Because we run only one test at a time in sct runners.

How about resigning from using manager at all and use Queue/Pipe as a bus for add/get/remove counter (or even don't get counters, just get_stats straight from `EventsCounter`) and make counters register internal to `EventsCounter`. WDYT?

**Comment by fruch** [comment]
one thing is for sure in artifacts we could get into a situation we would be running multiple jobs on the same builder as the same time.

so the failure of address is already in use, sounds related to two test running at the same time.

we shouldn't have such a limit, it cloud backfire in multiple places.

**Comment by fruch** [comment]
sounds like it's a bug in python 3.9 and 3.10
and we are pinning to `3.10.0-slim-bullseye`, we should move to use `3.10.12-slim-bullseye`
(and also start looking at moving to python 3.11)

**Comment by fruch** [comment]
I'm opening a PR with rebuild of the image, I think it would solve this one.
