### ISSUE TITLE
Collect more data on test failure

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-cluster-tests#6353]
When scylla times-out and gets aborted it's tempting to know more info about the system  other than logs  _before_ it gets killed (i.e. -- _before_ the coredump is produced), in particular

- the output of the `lsof` command to get the file descriptors scylla is holding
- the output of the `netstat -tanp` command to get the list of sockets and their states

refs: scylladb/scylladb#13100

**Comment by fruch** [comment]
it would be easy to collect those, and spit them in sct own log.

as separate files would also not going to be that hard.

@soyacz can you look at it ?


@xemul is it reproducible in one of those cases ? so we'll be able to test that it would work ?

**Comment by soyacz** [comment]
> 
> @soyacz can you look at it ?

@fruch I looked and I'm not sure if this is the right approach, but I was thinking about adding some command to `ExecStop` (e.g. if PID exists after some time, run above commands (and redirect output to some files). Possibly this could be done as part of `sdcm.cluster.BaseNode.fix_scylla_server_systemd_config`. WDYT?

**Comment by fruch** [comment]
> I was trying to add some code to/after 'stop_scylla_server' but looks that our timeout functionality does not work for that case - it should timeout after 300 seconds, while it returns right only after service stops (after SIGABRT, ~20 minutes).
> Need to investigate why this timeout does not work (I have some ideas), but I struggle to use `RemoteLibSSH2CmdRunner` alone for reproduction...
> I can take a look on Monday, unless @fruch you select someone else for this.

Don't worry, it will be waiting for you...
