### ISSUE TITLE
Rolling upgrade AMI tests do not search images in the releng AWS account

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla-cluster-tests#6362]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In the job `rolling-upgrade-ami-arm-test` SCT failed while performing `SetUp`.
At some point, `ec2_ami_get_root_device_name` was executed - it looked for the image `ami-024b197c962502cad`, but could not find it and created an empty Image object.
Later, while trying to get the value of the property `root_device_name` of this object the code failed with the error:
```
06:04:54  ERROR: test_rolling_upgrade (upgrade_test.UpgradeTest)
06:04:54  Upgrade half of nodes in the cluster, and start special read workload
06:04:54  ----------------------------------------------------------------------
06:04:54  Traceback (most recent call last):
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 164, in wrapper
06:04:54      return method(*args, **kwargs)
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
06:04:54      res = func(*args, **kwargs)
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 794, in setUp
06:04:54      self.init_resources()
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1818, in init_resources
06:04:54      self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1195, in get_cluster_aws
06:04:54      init_db_info_from_params(db_info, params=self.params, regions=regions)
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 250, in init_db_info_from_params
06:04:54      root_device = root_device if root_device else ec2_ami_get_root_device_name(
06:04:54    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 359, in ec2_ami_get_root_device_name
06:04:54      if image.root_device_name:
06:04:54    File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 386, in property_loader
06:04:54      return self.meta.data.get(name)
06:04:54  AttributeError: 'NoneType' object has no attribute 'get'. Did you mean: 'root_device_type'?
```
It turned out the image `ami-024b197c962502cad` is available only in the new releng AWS account, but this function does not use it for searching images.

Connected to https://github.com/scylladb/scylla-cluster-tests/issues/6163

## How frequently does it reproduce?

In job `rolling-upgrade-ami-arm-test` it reproduces each build with the image `ami-024b197c962502cad`
The same situation is in `rolling-upgrade-ami-test` with the image `ami-0eb5eae13f383b052`,  for example [this build](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=ec443641-1008-4014-933b-051c2d83bbdf)

## Installation details

Cluster size: 4 nodes (im4gn.2xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (aws: undefined_region)

Test: `rolling-upgrade-ami-arm-test`
Test id: `184da7e1-ae8e-4a04-886f-f33195021370`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-arm-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c34f91b1a83f9848be2ae1027d5cc64fe0b864fa/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 184da7e1-ae8e-4a04-886f-f33195021370`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=184da7e1-ae8e-4a04-886f-f33195021370)
- Show all stored logs command: `$ hydra investigate show-logs 184da7e1-ae8e-4a04-886f-f33195021370`

## Logs:
- **sct-runner-events-184da7e1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/184da7e1-ae8e-4a04-886f-f33195021370/20230708_030505/sct-runner-events-184da7e1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/184da7e1-ae8e-4a04-886f-f33195021370/20230708_030505/sct-runner-events-184da7e1.tar.gz)
- **sct-184da7e1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/184da7e1-ae8e-4a04-886f-f33195021370/20230708_030505/sct-184da7e1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/184da7e1-ae8e-4a04-886f-f33195021370/20230708_030505/sct-184da7e1.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-arm-test/54/)
[Argus](https://argus.scylladb.com/test/8e5f044d-57c2-43ad-8fe8-ac75a11a422d/runs?additionalRuns[]=184da7e1-ae8e-4a04-886f-f33195021370)
</details>

**Comment by ilya-rarov** [comment]
`sdcm.utils.common.wait_ami_available` may be also affected. It seems it may run a waiter in the wrong account

**Comment by fruch** [comment]
> `sdcm.utils.common.wait_ami_available` may be also affected. It seems it may run a waiter in the wrong account

should be a problem, since the image should be available also on the default account (and if it's not it's a bug)

**Comment by fruch** [comment]
FYI, @scylladb/releng

**Comment by fruch** [comment]
look like those are debug images, we shouldn't pick them up:
```
🟢 ❯ ./sct.py list-images -v 5.3
/home/fruch/.pyenv/versions/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243 using SSL with verify_certs=False is insecure.
  warnings.warn(
install-bash-completion current path: /home/fruch/projects/scylla-cluster-tests
New directory created: /home/fruch/sct-results/20230713-164910-300343-list-images
Found credentials in shared credentials file: ~/.aws/credentials
+-------------------------------------------------------------------------------------------------------------------------------------+
|                                          AWS Machine Images by Version in region eu-west-1                                          |
+---------+--------------------+-----------------------+--------------------------+---------------------------------------------------+
| Backend | Name               | ImageId               | CreationDate             | NameTag                                           |
+---------+--------------------+-----------------------+--------------------------+---------------------------------------------------+
| AWS     | ScyllaDB 5.3.0-dev | ami-0eb5eae13f383b052 | 2023-06-21T14:31:39.000Z | debug-scylla-5.4.0-dev-x86_64-2023-06-21T14-13-07 |
| AWS     | ScyllaDB 5.3.0-rc0 | ami-0895041392296aa54 | 2023-05-28T09:06:58.000Z | scylla-5.3.0-rc0-x86_64-2023-05-24T13-59-50       |
| AWS     | ScyllaDB 5.3.0-dev | ami-073aa7f2215f60ff5 | 2023-04-27T20:02:05.000Z | debug-scylla-5.3.0-dev-x86_64-2023-04-27T08-54-09 |
+---------+--------------------+-----------------------+--------------------------+---------------------------------------------------+
```

we should filter the image by name and if it has debug in it we should be using it.

**Comment by fgelcer** [comment]
> we should filter the image by name and if it has debug in it we should be using it.

we did have such a filter in place, but dunno why, it not always works
