### ISSUE TITLE
Disable 'implicit' tracing

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6368]
In various cases we've had a large tracing partition, for unknown reason. While it might be a red herring, it was found out tracing was enabled, though perhaps implicitly (no one expected it) @ https://github.com/scylladb/scylla-cluster-tests/blob/6e7fc4c302183583b22db0980a979eca1242dbfe/sdcm/scan_operation_thread.py#L454

Please remove it. If you wish to test tracing, that's great, let's do it explicitly.

**Comment by mykaul** [comment]
Example of a surprise - https://github.com/scylladb/scylla-enterprise/issues/3191#issuecomment-1637165290

**Comment by roydahan** [comment]
@temichus as we discussed please check if there is a metric in scylla that can validate that the parallel aggregation work (I don't know the name of it).

As a first step, please send a PR to trace=False and turn of the validation of aggregation if needed.

**Comment by temichus** [comment]
trace=False PR: https://github.com/scylladb/scylla-cluster-tests/pull/6419

**Comment by temichus** [comment]
@roydahan  I found some Prometheus metrics that might be related:


![Image](https://github.com/scylladb/scylla-cluster-tests/assets/1948660/ba62cd5e-dab1-4eb2-9847-53dfbfcd97ca)

But for now, I don't how to get data from these metrics and how to get access to them from SCT

Is anyone can help me with it?

**Comment by fgelcer** [comment]
> @roydahan I found some Prometheus metrics that might be related:
> 
> ![Image](https://user-images.githubusercontent.com/1948660/255847719-ba62cd5e-dab1-4eb2-9847-53dfbfcd97ca.png)
> 
> But for now, I don't how to get data from these metrics and how to get access to them from SCT
> 
> Is anyone can help me with it?

here is an example of usage of querying these metrics --> https://github.com/scylladb/scylla-cluster-tests/blob/31800d949edb135a69daad9707eed53c6d7a0740/admission_control_overload_test.py#L16

**Comment by fruch** [comment]
you can see more examples in db_stats.py all the `get_*` functions

**Comment by temichus** [comment]
pr with proper fix https://github.com/scylladb/scylla-cluster-tests/pull/6423
