### ISSUE TITLE
If "keyspace1" does not exists and nemesis_during_prepare is False, nemesis is not started during test_custom_time test.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#640]
If run just user profiles in longevity test, that does not create the "keyspace1"  keyspace and nemesis_during_prepare is False, the nemesis won't be started.

I think it happens because of `self.db_cluster.wait_total_space_used_per_node()` function receive the cfstats for "keyspace1" (hardcoded)

```
        if not prepare_write_cmd or self.params.get('nemesis_during_prepare', default='true').lower() == 'false':
            self.db_cluster.wait_total_space_used_per_node()
            self.db_cluster.start_nemesis(interval=self.params.get('nemesis_interval'))
```

**Comment by roydahan** [comment]
right, but if you set it to "0"?

**Comment by juliayakovlev** [comment]
I set it to "0", but nemesis didn't start
