### ISSUE TITLE
invalid CQL: Unknown property 'comment' in scylla 5.2

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6400]
https://github.com/scylladb/scylla-cluster-tests/pull/5944 introduced regression to 5.2: when running `"CREATE INDEX si_text ON scylla_bench.test(pk) with comment = 'TEST INDEX'"` error `cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="Unknown property 'comment'">`
More details in Argus: https://argus.scylladb.com/test/4d85e295-2ce4-4704-afa7-8ea748b17a88/runs?additionalRuns[]=b87f3cdd-5efb-4b17-98a7-9207698b7458

**Comment by fruch** [comment]
It was prematurely backported, 

It's failing on master as well, but people haven't reported it yet
