### ISSUE TITLE
disrupt_nodetool_enospc got: No space left on device

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6412]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.
error details:
```
2023-07-16 23:45:17.579 <2023-07-16 23:45:17.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=af334ddd-f38b-4ada-b806-18e4b4b5562e: type=NO_SPACE_ERROR regex=No space left on device line_number=17073 node=longevity-mv-si-4d-master-db-node-691e3684-2
2023-07-16T23:45:17+00:00 longevity-mv-si-4d-master-db-node-691e3684-2      !ERR | scylla[11144]:  [shard 11] compaction_manager - Compaction task 0x603008b0e410 for table sec_index.users compaction_group=0/1 [0x603008902860]: failed due to storage io error: Storage I/O error: 28: No space left on device: stopping
/libreloc/libc.so.6+0x8b12c /opt/scylladb/libreloc/libc.so.6+0x10cbbf
```
nemesis details:
```


disrupt_nodetool_enospc | longevity-mv-si-4d-master-db-node-691e3684-2 | Succeeded | 2023-07-16 23:44:51 | 2023-07-16 23:48:42
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_nodetool_enospcStatus: SucceededTarget InformationName: longevity-mv-si-4d-master-db-node-691e3684-2Public IP: 50.19.59.47Private IP: 10.12.11.146State: terminatedShards: 14

```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1039-aws
Scylla version (or git commit hash): `5.4.0~dev-20230715.a93fd2b162a8` with build-id `5ac70151955c5c56f337c369bc2deca9d4746c35`

Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-master-db-node-691e3684-6 (3.95.61.190 | 10.12.10.149) (shards: -1)
- longevity-mv-si-4d-master-db-node-691e3684-5 (107.23.158.93 | 10.12.10.73) (shards: 14)
- longevity-mv-si-4d-master-db-node-691e3684-4 (34.229.124.30 | 10.12.8.154) (shards: 14)
- longevity-mv-si-4d-master-db-node-691e3684-3 (54.144.124.121 | 10.12.11.53) (shards: 14)
- longevity-mv-si-4d-master-db-node-691e3684-2 (50.19.59.47 | 10.12.11.146) (shards: 14)
- longevity-mv-si-4d-master-db-node-691e3684-1 (54.160.180.96 | 10.12.10.204) (shards: 14)

OS / Image: `` (aws: undefined_region)

Test: `longevity-mv-si-4days-test`
Test id: `691e3684-96d6-4239-94c4-5409c9c77336`
Test name: `scylla-master/longevity/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a76ed862ad99c58012699546822eab08a94b2ea9/test-cases/longevity/longevity-mv-si-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 691e3684-96d6-4239-94c4-5409c9c77336`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=691e3684-96d6-4239-94c4-5409c9c77336)
- Show all stored logs command: `$ hydra investigate show-logs 691e3684-96d6-4239-94c4-5409c9c77336`

## Logs:
- **db-cluster-691e3684.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/db-cluster-691e3684.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/db-cluster-691e3684.tar.gz)
- **sct-runner-events-691e3684.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/sct-runner-events-691e3684.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/sct-runner-events-691e3684.tar.gz)
- **sct-691e3684.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/sct-691e3684.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/sct-691e3684.log.tar.gz)
- **loader-set-691e3684.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/loader-set-691e3684.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/loader-set-691e3684.tar.gz)
- **monitor-set-691e3684.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/monitor-set-691e3684.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/monitor-set-691e3684.tar.gz)
- **parallel-timelines-report-691e3684.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/parallel-timelines-report-691e3684.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/691e3684-96d6-4239-94c4-5409c9c77336/20230717_040619/parallel-timelines-report-691e3684.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-mv-si-4days-test/2/)
[Argus](https://argus.scylladb.com/test/b49dc529-c8e7-4117-a01d-2c6669c4dc05/runs?additionalRuns[]=691e3684-96d6-4239-94c4-5409c9c77336)
</details>

**Comment by temichus** [comment]
it can be a complex issue and not connected with disrupt_nodetool_enospc. same test longevity-mv-si-4days-test failed with "No space left on device" error after disrupt_truncate_large_partition

**Comment by fruch** [comment]
I don't think we see ENOSPC crashes like that for quite some time

closing for now
