### ISSUE TITLE
functional-eks test is failing on no `auxiliary-pool`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6438]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

```
2023-07-30 00:14:02.093: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=57d801d0-e473-479c-8675-b0c6906c060d, source=ScyllaOperatorFunctionalClusterTester.SetUp()
exception=Encountered a bad command exit code!
Command: 'kubectl --cache-dir=/home/ubuntu/sct-results/20230729-232411-373187/.kube/http-cache wait --timeout=8m -l eks.amazonaws.com/nodegroup=auxiliary-pool --for=condition=Ready node'
Exit code: 1
Stdout:
Stderr:
error: no matching resources found
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

happens for two week in a row

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `functional-eks`
Test id: `5fa9f9bb-59d3-43cf-8589-a32ea8c8207d`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6e3d34cd1b9fc6533a4e5a3874fd36ad401b9a81/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5fa9f9bb-59d3-43cf-8589-a32ea8c8207d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5fa9f9bb-59d3-43cf-8589-a32ea8c8207d)
- Show all stored logs command: `$ hydra investigate show-logs 5fa9f9bb-59d3-43cf-8589-a32ea8c8207d`

## Logs:
- **kubernetes-5fa9f9bb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/kubernetes-5fa9f9bb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/kubernetes-5fa9f9bb.tar.gz)
- **sct-runner-events-5fa9f9bb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/sct-runner-events-5fa9f9bb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/sct-runner-events-5fa9f9bb.tar.gz)
- **sct-5fa9f9bb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/sct-5fa9f9bb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/sct-5fa9f9bb.log.tar.gz)
- **parallel-timelines-report-5fa9f9bb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/parallel-timelines-report-5fa9f9bb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5fa9f9bb-59d3-43cf-8589-a32ea8c8207d/20230730_001514/parallel-timelines-report-5fa9f9bb.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/99/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=5fa9f9bb-59d3-43cf-8589-a32ea8c8207d)
</details>

**Comment by fruch** [comment]
@vponomaryov are you aware of this one ?

**Comment by vponomaryov** [comment]
> @vponomaryov are you aware of this one ?

In current case VMs of the `auxiliary` node pool were not created.
And no errors are observed in the logs that could describe the problem.
It looks like a temporary cloud platform problem.

So, I don't think we have problem on our side.
I would just rerun the test.

**Comment by fruch** [comment]
I'm running it again, to see if that the reason

**Comment by fruch** [comment]
It didn't reproduced
