### ISSUE TITLE
Load was stopped before nemesis finish and as result nemesis was marked as failed (scheduler runtime is 0)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6439]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Last nemesis fails after `TEST`END` event.
This nemesis `disrupt_sla_increase_shares_during_load` wait for load running and then measure scheduler runtime during load.
The problem here that in`sdcm.tester.ClusterTester.stop_resources` we first stop load and then waiting for nemesis finish.
```
    def stop_resources(self):  # pylint: disable=no-self-use
        self.log.debug('Stopping all resources')
        with silence(parent=self, name="Kill Stress Threads"):
            self.kill_stress_thread()

        # Stopping nemesis, using timeout of 30 minutes, since replace/decommission node can take time
        if self.db_cluster:
            self.get_nemesis_report(self.db_cluster)
            self.stop_nemesis(self.db_cluster)
            self.stop_resources_stop_tasks_threads(self.db_cluster)
            self.get_backtraces(self.db_cluster)
```

Due to load was stopped before nemesis finish, scheduler runtime is 0. And as result nemesis failed

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1038-aws
Scylla version (or git commit hash): `2023.1.0~rc7-20230621.b8e0eed13d19` with build-id `854ffecaf8918f0fe0cde4c200486b7b84fd7cb0`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-SlaIncreaseSharesD-db-node-b347237a-3 (16.16.63.4 | 10.0.3.253) (shards: 2)
- longevity-5gb-1h-SlaIncreaseSharesD-db-node-b347237a-2 (13.53.114.94 | 10.0.3.146) (shards: 2)
- longevity-5gb-1h-SlaIncreaseSharesD-db-node-b347237a-1 (16.170.238.113 | 10.0.1.176) (shards: 2)

OS / Image: `` (aws: undefined_region)

Test: `longevity-5gb-1h-SlaIncreaseSharesDuringLoad-aws`
Test id: `b347237a-2880-452d-9671-d76288737065`
Test name: `scylla-staging/yulia/longevity-5gb-1h-SlaIncreaseSharesDuringLoad-aws`
Test config file(s):

- [longevity-5gb-1h-SlaIncreaseSharesDuringLoad.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a619556b452e44c80d577fa133ce5f9b3f95736f/test-cases/nemesis/longevity-5gb-1h-SlaIncreaseSharesDuringLoad.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b347237a-2880-452d-9671-d76288737065`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b347237a-2880-452d-9671-d76288737065)
- Show all stored logs command: `$ hydra investigate show-logs b347237a-2880-452d-9671-d76288737065`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-5gb-1h-SlaIncreaseSharesDuringLoad-aws/3/)
[Argus](https://argus.scylladb.com/test/1b6ed6cc-80c5-454a-ab05-bfe75ea81252/runs?additionalRuns[]=b347237a-2880-452d-9671-d76288737065)
</details>

**Comment by fruch** [comment]
Is this the only nemesis we have which is dependent on the load ?

Until we have a different way to stop the nemesis thread, we can look at the termination_event before we raise error events...

**Comment by fruch** [comment]
@juliayakovlev 

I have a suggested fix, can you take it to the job that is failing for you ? to try it out ?
https://github.com/scylladb/scylla-cluster-tests/pull/6442

**Comment by juliayakovlev** [comment]
> @juliayakovlev
> 
> I have a suggested fix, can you take it to the job that is failing for you ? to try it out ? #6442

@fruch 
Running: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-5gb-1h-SlaReplaceUsingDetachDuringLoad-aws-test/3/

**Comment by fruch** [comment]
> > @juliayakovlev
> > I have a suggested fix, can you take it to the job that is failing for you ? to try it out ? #6442
> 
> @fruch [https://argus.scylladb.com/test/ebd06d8a-6452-4150-83ff-ccbdd29cc8d7/runs?additionalRuns[]=02f554f5-9955-495b-b3af-bf78a6e57f41](https://argus.scylladb.com/test/ebd06d8a-6452-4150-83ff-ccbdd29cc8d7/runs?additionalRuns%5B%5D=02f554f5-9955-495b-b3af-bf78a6e57f41)
> 
> Test failed with `sdcm.nemesis.KillNemesis` despite no nemesis was running at this point of time
> 
> ```
> 2023-07-31 09:20:30.824: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=0dab1ff4-1561-4782-b2e8-6ca783952439: nemesis_name=ReplaceServiceLevelUsingDetachDuringLoad target_node=Node longevity-5gb-1h-SlaReplaceUsingDet-db-node-02f554f5-1 [52.211.85.184 | 10.4.0.13] (seed: True)
> 2023-07-31 09:56:23.326: (DisruptionEvent Severity.NORMAL) period_type=end event_id=0dab1ff4-1561-4782-b2e8-6ca783952439 duration=35m52s: nemesis_name=ReplaceServiceLevelUsingDetachDuringLoad target_node=Node longevity-5gb-1h-SlaReplaceUsingDet-db-node-02f554f5-1 [52.211.85.184 | 10.4.0.13] (seed: True)
> 2023-07-31 10:12:00.251: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=7540220d-ec07-42d6-88ae-d84da278676d: nemesis_name=ReplaceServiceLevelUsingDetachDuringLoad target_node=Node longevity-5gb-1h-SlaReplaceUsingDet-db-node-02f554f5-2 [54.155.100.167 | 10.4.3.239] (seed: True)
> 2023-07-31 10:48:11.491: (DisruptionEvent Severity.NORMAL) period_type=end event_id=7540220d-ec07-42d6-88ae-d84da278676d duration=36m11s: nemesis_name=ReplaceServiceLevelUsingDetachDuringLoad target_node=Node longevity-5gb-1h-SlaReplaceUsingDet-db-node-02f554f5-2 [54.155.100.167 | 10.4.3.239] (seed: True)
> 2023-07-31 10:52:51.930: (InfoEvent Severity.NORMAL) period_type=not-set event_id=80ef9e13-389c-47e6-aa0b-5d2e6a4507c1: message=TEST_END
> ```

it's actually a good sign, that the mechanism works, but I need to handle it in some places to make sure it doesn't raise events
