### ISSUE TITLE
`create_index` and `wait_for_index_to_be_built` need to expect MV errors

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6469]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

When `disrupt_create_index` is used during parallel nemesis, it should expect 
errors like the following, since some node can be down during MV/Index creation:
```
< t:2023-08-07 02:16:00,108 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-08-07T02:16:00+00:00 longevity-parallel-topology-schema--db-node-f9c7a7e5-3  !WARNING | scylla[5398]:  [shard 6] view - Error executing build step for base keyspace1.standard1: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```

## Installation details

Kernel Version: 5.15.0-1040-aws
Scylla version (or git commit hash): `2023.1.0~rc8-20230731.b6f7c5a6910c` with build-id `f6e718548e76ccf3564ed2387b6582ba8d37793c`

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-f9c7a7e5-9 (54.75.126.66 | 10.4.1.97) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-8 (54.194.27.56 | 10.4.3.105) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-7 (63.33.208.200 | 10.4.1.200) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-6 (3.253.61.179 | 10.4.1.183) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-5 (3.248.218.96 | 10.4.3.90) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-4 (3.251.73.225 | 10.4.2.34) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-3 (34.249.188.75 | 10.4.0.186) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-21 (54.75.12.199 | 10.4.3.56) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-20 (54.171.208.78 | 10.4.1.129) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-2 (34.241.50.74 | 10.4.0.84) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-19 (34.248.132.128 | 10.4.2.23) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-18 (34.240.174.25 | 10.4.2.218) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-17 (54.217.43.84 | 10.4.2.17) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-16 (3.250.190.99 | 10.4.1.51) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-15 (63.32.47.34 | 10.4.2.6) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-14 (54.194.150.48 | 10.4.1.205) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-13 (34.245.120.56 | 10.4.1.161) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-12 (63.32.61.18 | 10.4.3.23) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-11 (34.240.65.63 | 10.4.3.80) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-10 (54.247.41.140 | 10.4.0.246) (shards: 7)
- longevity-parallel-topology-schema--db-node-f9c7a7e5-1 (34.240.226.156 | 10.4.2.30) (shards: 7)

OS / Image: `ami-0f995c2eaf941c262` (aws: eu-west-1)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `f9c7a7e5-ae10-4231-8cd4-fece4edc45cb`
Test name: `enterprise-2023.1/longevity/longevity-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5d4c4f28e9aeae884cd869a02e20c9ac56cd8fb7/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f9c7a7e5-ae10-4231-8cd4-fece4edc45cb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f9c7a7e5-ae10-4231-8cd4-fece4edc45cb)
- Show all stored logs command: `$ hydra investigate show-logs f9c7a7e5-ae10-4231-8cd4-fece4edc45cb`

## Logs:
- **db-cluster-f9c7a7e5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/db-cluster-f9c7a7e5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/db-cluster-f9c7a7e5.tar.gz)
- **sct-runner-events-f9c7a7e5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/sct-runner-events-f9c7a7e5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/sct-runner-events-f9c7a7e5.tar.gz)
- **sct-f9c7a7e5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/sct-f9c7a7e5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/sct-f9c7a7e5.log.tar.gz)
- **monitor-set-f9c7a7e5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/monitor-set-f9c7a7e5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/monitor-set-f9c7a7e5.tar.gz)
- **loader-set-f9c7a7e5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/loader-set-f9c7a7e5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9c7a7e5-ae10-4231-8cd4-fece4edc45cb/20230807_085318/loader-set-f9c7a7e5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-schema-topology-changes-12h-test/6/)
[Argus](https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=f9c7a7e5-ae10-4231-8cd4-fece4edc45cb)
</details>

**Comment by fruch** [comment]
@soyacz can you take a look at this one ?

**Comment by soyacz** [comment]
@fruch yes, I'll take a look today

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/6475
