### ISSUE TITLE
Change severity from error to warning for error message `Startup failed` for node bootstrapped again after  decommissioned node

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#6487]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
Kernel Version: 5.15.0-1042-azure
Scylla version (or git commit hash): `5.4.0~dev-20230730.14dee7a94602` with build-id `432eaee3090f86b6465505b3fe6ac145fddc5381`

### Logs
Test id: `930750bf-fa35-4ea4-b419-a2850215c142`
- **db-cluster-930750bf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/db-cluster-930750bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/db-cluster-930750bf.tar.gz)
- **sct-runner-events-930750bf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/sct-runner-events-930750bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/sct-runner-events-930750bf.tar.gz)
- **sct-930750bf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/sct-930750bf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/930750bf-fa35-4ea4-b419-a2850215c142/20230730_152528/sct-930750bf.log.tar.gz)

ARGUS: https://argus.scylladb.com/test/aa05fe67-89bd-4e30-88db-5e2b2e3d986d/runs?additionalRuns[]=930750bf-fa35-4ea4-b419-a2850215c142

### Description

Node after decommission was not started with error:
```
init - Startup failed: std::runtime_error (This node was decommissioned and will not rejoin the ring unless override_decommission=true has been set and consistent cluster management is not in use,or all existing data is removed and the node is bootstrapped again)
```

Need to add pattern to change severity, because issue is expected

**Comment by fruch** [comment]
happens quite often on azure short longevity:

## Installation details

Kernel Version: 5.15.0-1045-azure
Scylla version (or git commit hash): `2023.3.0~dev-20230907.596afc8d44fd` with build-id `8e5258e545248aa4e17e1b24c591d13d4eba14f3`





Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-9 (20.172.130.103 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-8 (172.190.34.212 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-7 (172.173.242.68 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-6 (20.121.215.253 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-5 (20.121.215.209 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-4 (20.121.215.148 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-3 (20.121.215.138 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-2 (20.121.215.75 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-5951cbbe-eastus-1 (20.121.214.210 | 10.0.0.5) (shards: 7)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-2023.3.0-dev-x86_64-2023-09-08T05-57-23` (azure: undefined_region)

Test: `longevity-10gb-3h-azure-test`
Test id: `5951cbbe-d343-41d4-8a3b-39882b44e265`
Test name: `scylla-enterprise/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4a1a93aa8438ca0c026f1b0e2809457f7864bd74/test-cases/longevity/longevity-10gb-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 5951cbbe-d343-41d4-8a3b-39882b44e265`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5951cbbe-d343-41d4-8a3b-39882b44e265)
- Show all stored logs command: `$ hydra investigate show-logs 5951cbbe-d343-41d4-8a3b-39882b44e265`


## Logs:
- **db-cluster-5951cbbe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/db-cluster-5951cbbe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/db-cluster-5951cbbe.tar.gz)
- **sct-runner-events-5951cbbe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/sct-runner-events-5951cbbe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/sct-runner-events-5951cbbe.tar.gz)
- **sct-5951cbbe.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/sct-5951cbbe.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/sct-5951cbbe.log.tar.gz)
- **loader-set-5951cbbe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/loader-set-5951cbbe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/loader-set-5951cbbe.tar.gz)
- **monitor-set-5951cbbe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/monitor-set-5951cbbe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/monitor-set-5951cbbe.tar.gz)
- **parallel-timelines-report-5951cbbe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/parallel-timelines-report-5951cbbe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5951cbbe-d343-41d4-8a3b-39882b44e265/20230908_082400/parallel-timelines-report-5951cbbe.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-10gb-3h-azure-test/91/)
[Argus](https://argus.scylladb.com/test/cdc07d5f-cef2-4aff-8ca7-ec364aa9b6e7/runs?additionalRuns[]=5951cbbe-d343-41d4-8a3b-39882b44e265)
</details>

**Comment by aleksbykov** [comment]
it is already fixed
