### ISSUE TITLE
artifacts-ami-arm-test: Failing due to wrong availability zone

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#6495]
`
13:29:22  < t:2023-08-14 10:29:17,499 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=Failed to get spot instances: {'SpotInstanceRequests': [{'AvailabilityZoneGroup': 'us-east-1a', 'CreateTime': datetime.datetime(2023, 8, 14, 10, 24, 13, tzinfo=tzlocal()), 'Fault': {'Code': 'bad-parameters', 'Message': 'Your Spot request failed due to bad parameters. Spot request cannot be fulfilled due to invalid availability zone.'}, 'LaunchSpecification': {'SecurityGroups': [{'GroupName': 'SCT-2-sg', 'GroupId': 'sg-0feef3370ee8305ac'}], 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {'DeleteOnTermination': True, 'VolumeSize': 50, 'VolumeType': 'gp2'}}], 'IamInstanceProfile': {'Name': 'qa-scylla-manager-backup-instance-profile'}, 'ImageId': 'ami-0d97abd22ab82abfa', 'InstanceType': 'im4gn.xlarge', 'KeyName': 'scylla-qa-ec2', 'NetworkInterfaces': [{'AssociatePublicIpAddress': True, 'DeviceIndex': 0, 'SubnetId': 'subnet-0a09ba4421ec6aaa8'}], 'Placement': {'AvailabilityZone': 'us-east-1a'}, 'Monitoring': {'Enabled': False}}, 'ProductDescription': 'Linux/UNIX', 'SpotInstanceRequestId': 'sir-p1d6pvyg', 'SpotPrice': '0.291032', 'State': 'failed', 'Status': {'Code': 'bad-parameters', 'Message': 'Your Spot request failed due to bad parameters. Spot request cannot be fulfilled due to invalid availability zone.', 'UpdateTime': datetime.datetime(2023, 8, 14, 10, 24, 13, tzinfo=tzlocal())}, 'Tags': [], 'Type': 'one-time', 'ValidUntil': datetime.datetime(2023, 8, 14, 10, 34, 13, tzinfo=tzlocal()), 'InstanceInterruptionBehavior': 'terminate'}], 'ResponseMetadata': {'RequestId': '7ee51a91-9a9b-459f-951c-95accd1254bc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '7ee51a91-9a9b-459f-951c-95accd1254bc', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'vary': 'accept-encoding', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '3060', 'date': 'Mon, 14 Aug 2023 10:29:17 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
`
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ami-arm-test/57/consoleFull

**Comment by soyacz** [comment]
@yaronkaikov I saw this job is executed with 'on_demand' and only spot was failing. 
Now it should be fixed and you can set this job back to run with spot.
