### ISSUE TITLE
`truncate_entries` info events are not being printed in the logs

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#6504]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

issue is that, searching in the logs for why the truncate failed, it is lacking the following event:
```
InfoEvent(message="Start truncate simple tables").publish()
```

it is inside `truncate_entries` decorator function, but not printed in the logs

in other hand, i see in the logs:
```
< t:2023-08-14 13:54:25,992 f:common.py       l:1726 c:utils                p:DEBUG > Executing CQL 'TRUNCATE TABLE truncate_table0' ...
```

## Impact

for some reason, truncate took too long, and the test proceeded to upgrade, so a truncate command failed, but part of the events are missing

## How frequently does it reproduce?

seeing that for the 1st time

## Installation details

Kernel Version: 4.18.0-500.el8.x86_64
Scylla version (or git commit hash): `5.2.6-20230730.58acf071bf28` with build-id `17961be569f8503b27ff284a8de1e00a9d83811e`
Target Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-8-db-node-146a9d47-0-4 (34.23.18.169 | 10.142.1.61) (shards: 7)
- rolling-upgrade--centos-8-db-node-146a9d47-0-3 (34.73.232.39 | 10.142.1.57) (shards: 7)
- rolling-upgrade--centos-8-db-node-146a9d47-0-2 (34.148.229.169 | 10.142.0.172) (shards: 7)
- rolling-upgrade--centos-8-db-node-146a9d47-0-1 (34.23.66.94 | 10.142.0.157) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-with-raft-test`
Test id: `146a9d47-b6f3-4b9b-90e5-a93a12fcb178`
Test name: `enterprise-2023.1/upgrade-with-raft/rolling-upgrade-centos8-with-raft-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/20354b24b545f7dc0fb7eb2da0b1caa027f7df0b/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 146a9d47-b6f3-4b9b-90e5-a93a12fcb178`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=146a9d47-b6f3-4b9b-90e5-a93a12fcb178)
- Show all stored logs command: `$ hydra investigate show-logs 146a9d47-b6f3-4b9b-90e5-a93a12fcb178`

## Logs:
- **db-cluster-146a9d47.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/db-cluster-146a9d47.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/db-cluster-146a9d47.tar.gz)
- **sct-runner-events-146a9d47.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/sct-runner-events-146a9d47.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/sct-runner-events-146a9d47.tar.gz)
- **sct-146a9d47.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/sct-146a9d47.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/sct-146a9d47.log.tar.gz)
- **monitor-set-146a9d47.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/monitor-set-146a9d47.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/monitor-set-146a9d47.tar.gz)
- **loader-set-146a9d47.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/loader-set-146a9d47.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/146a9d47-b6f3-4b9b-90e5-a93a12fcb178/20230814_141637/loader-set-146a9d47.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/upgrade-with-raft/job/rolling-upgrade-centos8-with-raft-test/7/)
[Argus](https://argus.scylladb.com/test/4b8fffbd-1e94-4dc3-ab1c-8140c947fb26/runs?additionalRuns[]=146a9d47-b6f3-4b9b-90e5-a93a12fcb178)
</details>

**Comment by fruch** [comment]
not seen since
