### ISSUE TITLE
cluster_aws: reboot node should query state after running

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#653]
reboot is an async operation, it doesn't block until the instance is rebooted.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.ServiceResource.reboot
That means that instance will highly likely not reboot when the reboot method returns.
Some implementation needed to query instance state

**Comment by amoskong** [comment]
We used soft & hard reboot() in two nemesises, we currently have self.target_node.wait_db_up() after reboot. If instance isn't rebooted successfully (become available), the wait_db_up() will be TIMEOUT, and raise exception.

Sometimes, we want to do something immediately after reboot (before the instance is available). So we can make the verify as optional.
