### ISSUE TITLE
`MemoryStress` failing to install stress-ng

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6555]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Seems like stress-ng isn't available as a snap package anymore:
```
2023-08-29 06:53:13.058: (DisruptionEvent Severity.ERROR) period_type=end event_id=2b7f4a62-5782-4f0b-8821-fddabca8a0a8 duration=18s: nemesis_name=MemoryStress target_node=Node longevity-10gb-3h-master-db-node-2c6bb844-0-4 [35.229.112.44 | 10.142.0.43] (seed: True) errors=Encountered a bad command exit code!
Command: 'sudo snap install stress-ng'
Exit code: 1
Stdout:
Stderr:
error: snap "stress-ng" not found
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4970, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 256, in inner_func
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4115, in disrupt_memory_stress
self.target_node.remoter.sudo('snap install stress-ng')
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
return self.run(cmd=cmd,
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo snap install stress-ng'
Exit code: 1
Stdout:
Stderr:
error: snap "stress-ng" not found
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1040-gcp
Scylla version (or git commit hash): `5.4.0~dev-20230829.83ceedb18bdc` with build-id `711ee9f13c2fe9969f6908550bdba2d098752f96`

Cluster size: 6 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-2c6bb844-0-8 (34.138.8.138 | 10.142.0.71) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-7 (34.139.56.121 | 10.142.0.69) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-6 (34.148.224.83 | 10.142.0.47) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-5 (34.73.133.190 | 10.142.0.46) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-4 (35.229.112.44 | 10.142.0.43) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-3 (34.23.40.57 | 10.142.0.42) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-2 (104.196.203.67 | 10.142.0.37) (shards: 14)
- longevity-10gb-3h-master-db-node-2c6bb844-0-1 (35.190.177.182 | 10.142.0.29) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/2228167545242831712` (gce: undefined_region)

Test: `longevity-10gb-3h-gce-test`
Test id: `2c6bb844-c36e-4eb9-849d-bac7c385f2f5`
Test name: `scylla-master/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3470ba06327705be9b14671a3c91dfedd8f5cb89/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2c6bb844-c36e-4eb9-849d-bac7c385f2f5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2c6bb844-c36e-4eb9-849d-bac7c385f2f5)
- Show all stored logs command: `$ hydra investigate show-logs 2c6bb844-c36e-4eb9-849d-bac7c385f2f5`

## Logs:
- **db-cluster-2c6bb844.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/db-cluster-2c6bb844.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/db-cluster-2c6bb844.tar.gz)
- **sct-runner-events-2c6bb844.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/sct-runner-events-2c6bb844.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/sct-runner-events-2c6bb844.tar.gz)
- **sct-2c6bb844.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/sct-2c6bb844.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/sct-2c6bb844.log.tar.gz)
- **loader-set-2c6bb844.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/loader-set-2c6bb844.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/loader-set-2c6bb844.tar.gz)
- **monitor-set-2c6bb844.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/monitor-set-2c6bb844.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/monitor-set-2c6bb844.tar.gz)
- **parallel-timelines-report-2c6bb844.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/parallel-timelines-report-2c6bb844.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2c6bb844-c36e-4eb9-849d-bac7c385f2f5/20230829_090340/parallel-timelines-report-2c6bb844.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/386/)
[Argus](https://argus.scylladb.com/test/6e39841d-5ed5-4f83-aa70-f51949559234/runs?additionalRuns[]=2c6bb844-c36e-4eb9-849d-bac7c385f2f5)
</details>

**Comment by fruch** [comment]
We should install it with apt-get, it should be available on all the release we are testing

**Comment by rayakurl** [comment]
Encountered the same issue on 5.1.16, during disrupt_memory_stress:
Build job: [scylla-5.1/longevity/longevity-10gb-3h-test](https://jenkins.scylladb.com/job/scylla-5.1/job/longevity/job/longevity-10gb-3h-test/61/)
`
Command: 'sudo snap install stress-ng'

Exit code: 1

Stdout:



Stderr:

error: snap "stress-ng" not found
`

**Comment by fruch** [comment]
> I think I'll do it, was there any particular reason to use a snap before this?

I think it wasn't yet package as part of debian/ubuntu at the time we started using it, or it was too old version.
I'm not sure what the the reason @amoskong used snap..
