### ISSUE TITLE
post-prepare-cql fails after disrupt_create_index: "Index si_text is a duplicate of existing index test_v_nemesis"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6565]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The create-index nemesis ran before post-prepare-cql:
```
< t:2023-08-31 09:09:04,530 f:nemesis.py      l:1736 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method create_index
< t:2023-08-31 09:09:45,955 f:common.py       l:1750 c:utils                p:DEBUG > Executing CQL 'CREATE INDEX test_v_nemesis ON scylla_bench.test("v")' ...
< t:2023-08-31 09:09:45,960 f:common.py       l:1758 c:utils                p:DEBUG > Executing CQL 'CREATE INDEX test_v_nemesis ON scylla_bench.test("v")' ...
```
then post-prepare-cql failed with: 
```
2023-08-31 09:15:37.584: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=53b45899-6b93-4012-9d33-e42316b7818d, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 106, in test_custom_time
self.run_prepare_write_cmd()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 209, in run_prepare_write_cmd
self.run_post_prepare_cql_cmds()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 152, in run_post_prepare_cql_cmds
self._run_cql_commands(post_prepare_cql_cmds)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 143, in _run_cql_commands
session.execute(cmd)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1751, in execute_verbose
return execute_orig(*args, **kwargs)
File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Index si_text is a duplicate of existing index test_v_nemesis"
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1040-aws
Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-3h-fix-l-db-node-a10402fd-5 (34.244.172.92 | 10.4.2.112) (shards: 6)
- longevity-large-partitions-3h-fix-l-db-node-a10402fd-4 (54.154.230.42 | 10.4.2.251) (shards: 4)
- longevity-large-partitions-3h-fix-l-db-node-a10402fd-3 (34.244.148.83 | 10.4.1.70) (shards: 5)
- longevity-large-partitions-3h-fix-l-db-node-a10402fd-2 (52.50.209.140 | 10.4.3.23) (shards: 7)
- longevity-large-partitions-3h-fix-l-db-node-a10402fd-1 (3.250.153.140 | 10.4.2.95) (shards: 7)

OS / Image: `ami-083eb64a6e3b43cc8` (aws: undefined_region)

Test: `longevity-10gb-3h-gce-test2`
Test id: `a10402fd-91dd-4b27-b855-cda850aaa613`
Test name: `scylla-staging/yarongilor/longevity-10gb-3h-gce-test2`
Test config file(s):

- [longevity-large-partition-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c754cc272621ac16ebed084b5987cf0cecf825a1/test-cases/longevity/longevity-large-partition-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a10402fd-91dd-4b27-b855-cda850aaa613`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a10402fd-91dd-4b27-b855-cda850aaa613)
- Show all stored logs command: `$ hydra investigate show-logs a10402fd-91dd-4b27-b855-cda850aaa613`

## Logs:
- **db-cluster-a10402fd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/db-cluster-a10402fd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/db-cluster-a10402fd.tar.gz)
- **sct-runner-events-a10402fd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/sct-runner-events-a10402fd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/sct-runner-events-a10402fd.tar.gz)
- **sct-a10402fd.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/sct-a10402fd.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/sct-a10402fd.log.tar.gz)
- **loader-set-a10402fd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/loader-set-a10402fd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/loader-set-a10402fd.tar.gz)
- **monitor-set-a10402fd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/monitor-set-a10402fd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/monitor-set-a10402fd.tar.gz)
- **parallel-timelines-report-a10402fd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/parallel-timelines-report-a10402fd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a10402fd-91dd-4b27-b855-cda850aaa613/20230831_092032/parallel-timelines-report-a10402fd.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-10gb-3h-gce-test2/24/)
[Argus](https://argus.scylladb.com/test/0c756c99-fe0d-49aa-84bc-9c719bcafff8/runs?additionalRuns[]=a10402fd-91dd-4b27-b855-cda850aaa613)
</details>

**Comment by yarongilor** [comment]
@juliayakovlev , @soyacz , any advise?
Can `nemesis_during_prepare: false` be a workaround?

**Comment by juliayakovlev** [comment]
The problem that scylla_bench.test table has so few columns.
Can we change and add few more columns to this table?

**Comment by juliayakovlev** [comment]
> @juliayakovlev , @soyacz , any advise? Can `nemesis_during_prepare: false` be a workaround?

It is definitely may be workaround.
Few ways to fix it:
1. not run nemesis during prepare
2. remove index creation from test yaml. But it was added by @k0machi as part of SI testing. So looks like it is not a good option.
3. change the nemesis: first check if there is column that "free" for index creation.
4. Add more columns into scylla_bench.test table. That means - chancg in scylla-bench. Not sounds good.

I think - option (3) is better

**Comment by fruch** [comment]
> > > @juliayakovlev , @soyacz , any advise? Can `nemesis_during_prepare: false` be a workaround?
> > 
> > It is definitely may be workaround. Few ways to fix it:
> > 
> > 1. not run nemesis during prepare
> > 2. remove index creation from test yaml. But it was added by @k0machi as part of SI testing. So looks like it is not a good option.
> > 3. change the nemesis: first check if there is column that "free" for index creation.
> > 4. Add more columns into scylla_bench.test table. That means - chancg in scylla-bench. Not sounds good.
> > 
> > I think - option (3) is better
> 
> After rethinking - not running nemesis during prepare will not help. Because the index that was created in post_prepare_cql_cmds exists during entire test.
> 
> I think we should change nemesis

I agree with 3, but we should also see if 4 can be done, like in c-s that we can control the back number of columns

**Comment by yarongilor** [comment]
@juliayakovlev , @fruch , i don't see how 3 will solve the problem (unless it is expected to parse the post-prepare-cql param)

**Comment by juliayakovlev** [comment]
> @juliayakovlev , @fruch , i don't see how 3 will solve the problem (unless it is expected to parse the post-prepare-cql param)

@yarongilor 
Create index if there is available column (that has no index only. If no "free" column - skip the nemesis

**Comment by yarongilor** [comment]
> > @juliayakovlev , @fruch , i don't see how 3 will solve the problem (unless it is expected to parse the post-prepare-cql param)
> 
> @yarongilor Create index if there is available column (that has no index only. If no "free" column - skip the nemesis

yes, that is exactly what happened in this case - the nemesis run before post-prepare-cql so there was no any index exist..

**Comment by juliayakovlev** [comment]
> > > @juliayakovlev , @fruch , i don't see how 3 will solve the problem (unless it is expected to parse the post-prepare-cql param)
> > 
> > 
> > @yarongilor Create index if there is available column (that has no index only. If no "free" column - skip the nemesis
> 
> yes, that is exactly what happened in this case - the nemesis run before post-prepare-cql so there was no any index exist..

@yarongilor 
to prevent this just need to change cql command to:
```
create index if not exists si_text ON scylla_bench.test(v)
```
It's is not perfect, but won't fail the test and won't happen every run (maximum we can change the nemesis seed).

But if the nemesis will happen later, after prepare, it will fail nemesis. And we can not use "if not exists" in the nemesis because the index must be created.

If it is possible to increase columns number in the scylla_bench.test table, it will be good

**Comment by mykaul** [comment]
@juliayakovlev , @fgelcer - what's the next step here? Can we take @yarongilor  's PR (https://github.com/scylladb/scylla-cluster-tests/pull/6578) and merge and fix this?

**Comment by mykaul** [comment]
So what is the next step here? What does https://github.com/scylladb/scylla-cluster-tests/pull/6578 solve?

**Comment by fruch** [comment]
> @juliayakovlev , @fgelcer - what's the next step here? Can we take @yarongilor 's PR (#6578) and merge and fix this?

https://github.com/scylladb/scylla-cluster-tests/pull/6578 isn't yet fixing the issue, just postponing it ot a later stage.
and not yet addressing all the issue (also not seem to be tested yet)

**Comment by fruch** [comment]
> > @juliayakovlev , @fgelcer - what's the next step here? Can we take @yarongilor 's PR (#6578) and merge and fix this?
> 
> https://github.com/scylladb/scylla-cluster-tests/pull/6578 isn't yet fixing the issue, just postponing it ot a later stage.
> and not yet addressing all the issue (also not seem to be tested yet)
> 
> 

There are two options to move forward

1) go backwards, and remove the MV from configuration

2) as suggest before, making sure we have more columns on the table (changing s-b), so there won't be a conflict, and adapt the nemesis code to select unused columns

**Comment by mykaul** [comment]
Saw it again @ https://argus.scylladb.com/test/fe83fd1d-d4be-4803-a484-001230ab46f5/runs?additionalRuns[]=7111138c-a788-4784-aaf3-e175ec8fde7c

**Comment by fruch** [comment]
> > > @juliayakovlev , @fgelcer - what's the next step here? Can we take @yarongilor 's PR (#6578) and merge and fix this?
> > 
> > https://github.com/scylladb/scylla-cluster-tests/pull/6578 isn't yet fixing the issue, just postponing it ot a later stage.
> > and not yet addressing all the issue (also not seem to be tested yet)
> > 
> > 
> 
> There are two options to move forward
> 
> 1) go backwards, and remove the MV from configuration
> 
> 2) as suggest before, making sure we have more columns on the table (changing s-b), so there won't be a conflict, and adapt the nemesis code to select unused columns 
> 
> 

@juliayakovlev Julia let's go on option one, remove the extra configuration for creating MV from all the large partition tests, until there's a proper handling for this case

**Comment by mykaul** [comment]
@juliayakovlev - any progress?

**Comment by juliayakovlev** [comment]
> > > > @juliayakovlev , @fgelcer - what's the next step here? Can we take @yarongilor 's PR (#6578) and merge and fix this?
> > > 
> > > 
> > > #6578 isn't yet fixing the issue, just postponing it ot a later stage.
> > > and not yet addressing all the issue (also not seem to be tested yet)
> > 
> > 
> > There are two options to move forward
> > 
> > 1. go backwards, and remove the MV from configuration
> > 2. as suggest before, making sure we have more columns on the table (changing s-b), so there won't be a conflict, and adapt the nemesis code to select unused columns
> 
> @juliayakovlev Julia let's go on option one, remove the extra configuration for creating MV from all the large partition tests, until there's a proper handling for this case

@fruch 
Israel, you ask to remove MV creating. But the problem here is index creation. Should I remove all MV anyway?
We can create MV on the same column as many as we need. 
Opposite it, it is impossible to create a few indexes on the same column.
