### ISSUE TITLE
disrupt_delete_by_rows_range deletes all partitions once, the try deleting all partitions again, fails to find partitions and raises UnsupportedNemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6576]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Run the following nemesis code:
```
    def disrupt_delete_by_rows_range(self):
        """
        Delete few partitions in the table with large partitions
        """
        self.verify_initial_inputs_for_delete_nemesis()

        ks_cf = 'scylla_bench.test'
        if random.random() > 0.5:
            partitions_for_exclude = self.delete_half_partition(ks_cf)
        else:
            partitions_for_exclude = self.delete_by_range_using_timestamp(ks_cf)

        self.delete_range_in_few_partitions(ks_cf, partitions_for_exclude)
```
In the "else" case, it runs `partitions_for_exclude = self.delete_by_range_using_timestamp(ks_cf)`.
Then it selects all partitions for deletion like:
```
partitions_for_delete = self.choose_partitions_for_delete(self.cluster.params.get('max_partitions_in_test_table'), ks_cf,
                                                                  with_clustering_key_data=False)
```
After (almost) all partitions are deleted, it tries deleting them again by next line of:
```
self.delete_range_in_few_partitions(ks_cf, partitions_for_exclude)
```
Then it runs this code, fails and raises `UnsupportedNemesis` (although nemesis already deleted partitions): 
```
        partitions_for_delete = self.choose_partitions_for_delete(self.cluster.params.get('max_partitions_in_test_table'), ks_cf,
                                                                  with_clustering_key_data=True,
                                                                  exclude_partitions=partitions_for_exclude)
        if not partitions_for_delete:
            raise UnsupportedNemesis('Not found partitions for delete. Nemesis can not be run')
```

The nemesis was tested during a staging-refactor-PR and reported:
```
disrupt_delete_by_rows_range | longevity-large-partitions-3h-fix-l-db-node-84abac2a-5 | Skipped | 2023-09-03 18:19:24 | 2023-09-03 18:26:33
-- | -- | -- | -- | --
Nemesis Information
Class: SisyphusName: disrupt_delete_by_rows_range
Status: Skipped
Skip reason Not found partitions for delete. Nemesis can not be run 
Target InformationName: longevity-large-partitions-3h-fix-l-db-node-84abac2a-5
Public IP: 52.210.82.82
Private IP: 10.4.2.19
State: terminated
Shards: 4
```

(caused by [this commit](https://github.com/scylladb/scylla-cluster-tests/commit/eba0d7e73831d920e85639531ba9f171d5680748#diff-5b39b3ae81128c1eb02e8af6c9165c8cefa8f13813740eaaa86d2292b7bcd3b3R2225))

The simple solution is to revert this commit change back to 10 (or `random.randint(10, self.cluster.params.get('max_partitions_in_test_table') // 5) partitions (instead of all):
```
partitions_for_delete = self.choose_partitions_for_delete(10, ks_cf, with_clustering_key_data=False)
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1040-aws
Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-3h-fix-l-db-node-84abac2a-5 (52.210.82.82 | 10.4.2.19) (shards: 4)
- longevity-large-partitions-3h-fix-l-db-node-84abac2a-4 (52.215.220.108 | 10.4.1.97) (shards: 7)
- longevity-large-partitions-3h-fix-l-db-node-84abac2a-3 (54.217.24.41 | 10.4.0.19) (shards: 6)
- longevity-large-partitions-3h-fix-l-db-node-84abac2a-2 (52.210.43.28 | 10.4.1.80) (shards: 6)
- longevity-large-partitions-3h-fix-l-db-node-84abac2a-1 (34.246.173.87 | 10.4.0.167) (shards: 7)

OS / Image: `ami-083eb64a6e3b43cc8` (aws: undefined_region)

Test: `longevity-10gb-3h-gce-test2`
Test id: `84abac2a-46f1-4039-b625-18754d0f30bf`
Test name: `scylla-staging/yarongilor/longevity-10gb-3h-gce-test2`
Test config file(s):

- [longevity-large-partition-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7a474ee5f503c25ec71d962ff8aa3baa0f4f348c/test-cases/longevity/longevity-large-partition-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 84abac2a-46f1-4039-b625-18754d0f30bf`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=84abac2a-46f1-4039-b625-18754d0f30bf)
- Show all stored logs command: `$ hydra investigate show-logs 84abac2a-46f1-4039-b625-18754d0f30bf`

## Logs:
- **db-cluster-84abac2a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/db-cluster-84abac2a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/db-cluster-84abac2a.tar.gz)
- **sct-runner-events-84abac2a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/sct-runner-events-84abac2a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/sct-runner-events-84abac2a.tar.gz)
- **sct-84abac2a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/sct-84abac2a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/sct-84abac2a.log.tar.gz)
- **loader-set-84abac2a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/loader-set-84abac2a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/loader-set-84abac2a.tar.gz)
- **monitor-set-84abac2a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/monitor-set-84abac2a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/monitor-set-84abac2a.tar.gz)
- **parallel-timelines-report-84abac2a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/parallel-timelines-report-84abac2a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84abac2a-46f1-4039-b625-18754d0f30bf/20230903_205957/parallel-timelines-report-84abac2a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-10gb-3h-gce-test2/26/)
[Argus](https://argus.scylladb.com/test/0c756c99-fe0d-49aa-84bc-9c719bcafff8/runs?additionalRuns[]=84abac2a-46f1-4039-b625-18754d0f30bf)
</details>

**Comment by yarongilor** [comment]
Should be fixed by this new PR [commit](https://github.com/scylladb/scylla-cluster-tests/pull/6185/commits/e1959e34f27c4e72fa1f4700468c8cc2030d1a16)

**Comment by mykaul** [comment]
From  https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-counters-3h-test/2/ :  
just saw this:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5077, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2333, in disrupt_delete_overlapping_row_ranges
    self.verify_initial_inputs_for_delete_nemesis()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2115, in verify_initial_inputs_for_delete_nemesis
    if not self.tester.partitions_attrs.max_partitions_in_test_table:
AttributeError: 'NoneType' object has no attribute 'max_partitions_in_test_table'
```

**Comment by fruch** [comment]
> From https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-counters-3h-test/2/ : just saw this:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5077, in wrapper
>     result = method(*args[1:], **kwargs)
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2333, in disrupt_delete_overlapping_row_ranges
>     self.verify_initial_inputs_for_delete_nemesis()
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2115, in verify_initial_inputs_for_delete_nemesis
>     if not self.tester.partitions_attrs.max_partitions_in_test_table:
> AttributeError: 'NoneType' object has no attribute 'max_partitions_in_test_table'
> ```

I think that would fix this issue:
https://github.com/scylladb/scylla-cluster-tests/pull/6758
