### ISSUE TITLE
Failed to copy connection bundle file to K8s node

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6592]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.
Error happened while running
```
E             File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2836, in _gen_cqlsh_cmd
E               self.remoter.send_files(str(connection_bundle_file), target_connection_bundle_file)
```
It happened to be that bundle file couldn't be overwritten:
```
E           Command: 'kubectl --cache-dir=/home/ubuntu/sct-results/20230909-232233-175823/.kube/http-cache cp /tmp/tmp5i8fvug3.yaml scylla/sct-cluster-us-east1-b-us-east1-0:/tmp/tmp5i8fvug3.yaml -c scylla'
E
E           Exit code: 2
E
E           Stdout:
E
E
E
E           Stderr:
E
E           tar: tmp5i8fvug3.yaml: Cannot open: File exists
E           tar: Exiting with failure status due to previous errors
```

## Impact

Failed test because of this error

## How frequently does it reproduce?

first time seen.
## Installation details

Kernel Version: 5.10.186-179.751.amzn2.x86_64
Scylla version (or git commit hash): `5.4.0~dev-20230907.cfc70810d335` with build-id `6dec2e4d10afbef8a279fc0d01018ac4bd74d6a6`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-58-g6b310ee
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `functional-eks`
Test id: `5a2141f4-96ea-448b-afaa-eb83b2a8891e`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4a1a93aa8438ca0c026f1b0e2809457f7864bd74/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5a2141f4-96ea-448b-afaa-eb83b2a8891e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5a2141f4-96ea-448b-afaa-eb83b2a8891e)
- Show all stored logs command: `$ hydra investigate show-logs 5a2141f4-96ea-448b-afaa-eb83b2a8891e`

## Logs:
- **kubernetes-5a2141f4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/kubernetes-5a2141f4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/kubernetes-5a2141f4.tar.gz)
- **db-cluster-5a2141f4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/db-cluster-5a2141f4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/db-cluster-5a2141f4.tar.gz)
- **sct-runner-events-5a2141f4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/sct-runner-events-5a2141f4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/sct-runner-events-5a2141f4.tar.gz)
- **sct-5a2141f4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/sct-5a2141f4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/sct-5a2141f4.log.tar.gz)
- **loader-set-5a2141f4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/loader-set-5a2141f4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/loader-set-5a2141f4.tar.gz)
- **parallel-timelines-report-5a2141f4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/parallel-timelines-report-5a2141f4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a2141f4-96ea-448b-afaa-eb83b2a8891e/20230910_013559/parallel-timelines-report-5a2141f4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/113/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=5a2141f4-96ea-448b-afaa-eb83b2a8891e)
</details>

**Comment by soyacz** [comment]
I found in sct logs that this file is copied multiple times. Maybe we can cache it, so it's not copied all over again?

**Comment by vponomaryov** [comment]
> I found in sct logs that this file is copied multiple times. Maybe we can cache it, so it's not copied all over again?

Cache is not suitable here, because custom copied file will be lost when pod gets recreated due to some temporary problem.
We see that it happens by the IP changes of pods.

So, here is the fix using lock mechanism: https://github.com/scylladb/scylla-cluster-tests/pull/6620

**Comment by vponomaryov** [comment]
This bug is fixed by the https://github.com/scylladb/scylla-cluster-tests/pull/6620
And the test itself becomes more stable with this PR: https://github.com/scylladb/scylla-cluster-tests/pull/6634
