### ISSUE TITLE
Sct runner on azure create one root disk size 80GB always and not depend on config sct parameter

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#6614]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id:  748610c3-17b8-4087-b552-065282f533bd
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-1tb-5days-azure-test/

### Description

azure sct runner always created with root disk size 80 GB. this disk size is small for Long run jobs and cause No space left on device error on sct-runner and no logs collected for jobs.

Requested instance with root disk 500GB
```
Instance params: InstanceDefinition(name='sct-runner-1.6-instance-1b6bbe2e', image_id='/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCT_IMAGES-eastus/providers/Microsoft.Compute/galleries/SCT_IMAGES/images/sct-runner/versions/1.6.0', type='Standard_E2s_v3', user_name='ubuntu', tags={'RunByUser': 'alex.bykov', 'TestName': 'longevity_test.LongevityTest.test_custom_time', 'TestId': '1b6bbe2e-fa9f-4ba6-a74a-d4ab2436221a', 'version': 'scylla-master', 'CreatedBy': 'SCT', 'JenkinsJobTag': 'jenkins-scylla-master-longevity-longevity-1tb-5days-azure-test-14', 'NodeType': 'sct-runner', 'keep': '39', 'keep_action': 'terminate', 'UserName': 'ubuntu', 'bastion': 'true', 'launch_time': 'September 19, 2023, 13:33:37'}, arch=<VmArch.X86: 'x86_64'>, root_disk_size=500, data_disks=None)
```
here is the result:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        78G  5.7G   72G   8% /
tmpfs           7.9G  208K  7.9G   1% /dev/shm
tmpfs           3.2G  1.2M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  5.3M  100M   5% /boot/efi
/dev/sdb1        32G   28K   30G   1% /mnt
tmpfs           1.6G  4.0K  1.6G   1% /run/user/1000

```
```
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0     7:0    0  63.2M  1 loop /snap/core20/1738
loop1     7:1    0   103M  1 loop /snap/lxd/23541
loop2     7:2    0  49.6M  1 loop /snap/snapd/17883
loop3     7:3    0  40.8M  1 loop /snap/snapd/20092
loop4     7:4    0  63.5M  1 loop /snap/core20/2015
loop5     7:5    0 111.9M  1 loop /snap/lxd/24322
sda       8:0    0    80G  0 disk 
├─sda1    8:1    0  79.9G  0 part /
├─sda14   8:14   0     4M  0 part 
└─sda15   8:15   0   106M  0 part /boot/efi
sdb       8:16   0    32G  0 disk 
└─sdb1    8:17   0    32G  0 part /mnt

```

The same picture and for job which created with rootdisksize 120GB

### Steps to Reproduce

1. Set sctrunner disk size more than 100GB
2. Create sct runner on azure
3. Check disk size

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by fruch** [comment]
we might need to follow this: https://learn.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks?tabs=ubuntu
sounds to me it's something todo with how we created the sct-runner disk.

@soyacz have you seen such a thing ?

**Comment by roydahan** [comment]
I don't understand the issue.
When we request disk size more than 80GB it doesn't work and we still get 80GB?

**Comment by fruch** [comment]
found the root cause of it.

and managed to create a running with 120Gb disk:
```
ubuntu@sct-runner-1-6:~/sct-results$ df -H
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       125G  2.7G  122G   3% /
tmpfs           4.2G     0  4.2G   0% /dev/shm
tmpfs           1.7G  1.1M  1.7G   1% /run
tmpfs           5.3M     0  5.3M   0% /run/lock
/dev/sda15      110M  5.5M  104M   5% /boot/efi
tmpfs           834M  4.1k  834M   1% /run/user/1000
```

Sending a PR soon...
