### ISSUE TITLE
[disrupt_mgmt_restore] during disrupt_mgmt_restore nemesis restore task was not disrupted

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#6635]
According to the log restore task was not disrupted. It looks like some issue in nemesis itself

disrupt_mgmt_restore failed with the following issue 

Failure reason
```
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 69, in wait_for
res = retry(func, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/init.py", line 404, in call
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/init.py", line 360, in iter
raise retry_exc.reraise()
File "/usr/local/lib/python3.10/site-packages/tenacity/init.py", line 194, in reraise
raise self
tenacity.RetryError: RetryError[<Future at 0x7fce2c4e13c0 state=finished returned bool>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 399, in wait_for_status
return wait.wait_for(func=self.is_status_in_list, step=step, throw_exc=True,
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 80, in wait_for
raise WaitForTimeoutError(err) from ex
sdcm.wait.WaitForTimeoutError: Wait for: Waiting until task: restore/ee5897e2-3bc3-40c5-9155-9fac4ed6c77e reaches status of: ['ERROR', 'ERROR (4/4)', 'STOPPED', 'DONE', 'ABORTED']: timeout - 120 seconds - expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5021, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2789, in disrupt_mgmt_restore
restore_task.wait_and_get_final_status(step=10, timeout=120)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 438, in wait_and_get_final_status
res = self.wait_for_status(list_status=list_final_status, timeout=timeout, step=step)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 403, in wait_for_status
raise WaitForTimeoutError(
sdcm.wait.WaitForTimeoutError: Failed on waiting until task: restore/ee5897e2-3bc3-40c5-9155-9fac4ed6c77e reaches status of ['ERROR', 'ERROR (4/4)', 'STOPPED', 'DONE', 'ABORTED']: current task status RUNNING: Wait for: Waiting until task: restore/ee5897e2-3bc3-40c5-9155-9fac4ed6c77e reaches status of: ['ERROR', 'ERROR (4/4)', 'STOPPED', 'DONE', 'ABORTED']: timeout - 120 seconds - expired
```

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `5.4.0~dev-20230921.a56a4b6226e6` with build-id `616f734e7c7fb5e3ee8898792b3c415d2574a132`

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-90530f5d-6 (3.250.118.99 | 10.4.9.89) (shards: 8)
- longevity-50gb-12h-master-db-node-90530f5d-5 (34.245.54.144 | 10.4.8.7) (shards: 13)
- longevity-50gb-12h-master-db-node-90530f5d-4 (54.154.138.88 | 10.4.10.168) (shards: 10)
- longevity-50gb-12h-master-db-node-90530f5d-3 (3.252.80.253 | 10.4.9.156) (shards: 13)
- longevity-50gb-12h-master-db-node-90530f5d-2 (52.212.212.195 | 10.4.9.212) (shards: 12)
- longevity-50gb-12h-master-db-node-90530f5d-1 (18.203.84.134 | 10.4.10.5) (shards: 10)

OS / Image: `ami-00f051bf1c684c01a` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `90530f5d-7e4a-461c-8259-c3fd208bc60f`
Test name: `scylla-master/longevity/longevity-150gb-asymmetric-cluster-12h-test`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/558925b49a60a15952f3cbb0f692a73e50e7e058/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 90530f5d-7e4a-461c-8259-c3fd208bc60f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=90530f5d-7e4a-461c-8259-c3fd208bc60f)
- Show all stored logs command: `$ hydra investigate show-logs 90530f5d-7e4a-461c-8259-c3fd208bc60f`

## Logs:
- **db-cluster-90530f5d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/db-cluster-90530f5d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/db-cluster-90530f5d.tar.gz)
- **sct-runner-events-90530f5d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/sct-runner-events-90530f5d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/sct-runner-events-90530f5d.tar.gz)
- **sct-90530f5d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/sct-90530f5d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/sct-90530f5d.log.tar.gz)
- **loader-set-90530f5d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/loader-set-90530f5d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/loader-set-90530f5d.tar.gz)
- **monitor-set-90530f5d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/monitor-set-90530f5d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/90530f5d-7e4a-461c-8259-c3fd208bc60f/20230926_115455/monitor-set-90530f5d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-150gb-asymmetric-cluster-12h-test/20/)
[Argus](https://argus.scylladb.com/test/6a3a708c-caa0-439f-84cd-736b40b517e3/runs?additionalRuns[]=90530f5d-7e4a-461c-8259-c3fd208bc60f)
</details>

**Comment by temichus** [comment]
@scylladb/qa-maintainers, Could you please take a look?

**Comment by fgelcer** [comment]
@ShlomiBalalis , please check... seems like restore is taking much longer than expected, and it may be related to the new manager 3.2.1

**Comment by fruch** [comment]
need to check if https://github.com/scylladb/scylla-manager/pull/3558, is in the manager that was used here

**Comment by ShlomiBalalis** [comment]
The restore test is a schema restoration, which, from my experience should take around 10~12 seconds. So the fact that it timed out is definitely not a test issue.
Looking at the logs, I see 
`Sep 26 04:20:11 longevity-50gb-12h-master-monitor-node-90530f5d-1 scylla-manager[31122]: {"L":"INFO","T":"2023-09-26T04:20:11.516Z","N":"scheduler.433a4644","M":"Run ended with ERROR","task":"restore/ee5897e2-3bc3-40c5-9155-9fac4ed6c77e","status":"ERROR","cause":"restore data: restore schema: giving up after 10 attempts: agent [HTTP 500] Failed to load new sstables: std::out_of_range (stoull)","duration":"3m43.855893453s","_trace_id":"rviVB6EcQt293BigtuxtoQ"}`
Which makes it a re-occurrence of https://github.com/scylladb/scylladb/issues/15226

> need to check if [scylladb/scylla-manager#3558](https://github.com/scylladb/scylla-manager/pull/3558), is in the manager that was used here

It is exactly that issue. The version is `3.2.0-0.20230815.9db309c5`, so no, it's not included.

> @ShlomiBalalis , please check... seems like restore is taking much longer than expected, and it may be related to the new manager 3.2.1

As seen above, this is still 3.2.0


All in all, It's an known issue that wouldn't happen next time since 3.2.1 has been promoted, and it includes the fix. Closing.

**Comment by fgelcer** [comment]
> The restore test is a schema restoration, which, from my experience should take around 10~12 seconds. So the fact that it timed out is definitely not a test issue. Looking at the logs, I see `Sep 26 04:20:11 longevity-50gb-12h-master-monitor-node-90530f5d-1 scylla-manager[31122]: {"L":"INFO","T":"2023-09-26T04:20:11.516Z","N":"scheduler.433a4644","M":"Run ended with ERROR","task":"restore/ee5897e2-3bc3-40c5-9155-9fac4ed6c77e","status":"ERROR","cause":"restore data: restore schema: giving up after 10 attempts: agent [HTTP 500] Failed to load new sstables: std::out_of_range (stoull)","duration":"3m43.855893453s","_trace_id":"rviVB6EcQt293BigtuxtoQ"}` Which makes it a re-occurrence of [scylladb/scylladb#15226](https://github.com/scylladb/scylladb/issues/15226)
> 
> > need to check if [scylladb/scylla-manager#3558](https://github.com/scylladb/scylla-manager/pull/3558), is in the manager that was used here
> 
> It is exactly that issue. The version is `3.2.0-0.20230815.9db309c5`, so no, it's not included.
> 
> > @ShlomiBalalis , please check... seems like restore is taking much longer than expected, and it may be related to the new manager 3.2.1
> 
> As seen above, this is still 3.2.0
> 
> All in all, It's an known issue that wouldn't happen next time since 3.2.1 has been promoted, and it includes the fix. Closing.

@temichus FYI
