### ISSUE TITLE
Remove unused parameters from table creation 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6645]
Recently scylla has introduced better validation of parameters when creating tables
And SCT now fails like this:
```
2023-10-03 04:25:46.154: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=6a75e537-a63c-4269-9cf5-09fe9cba9d3e, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 98, in test_custom_time
self.run_pre_create_schema()
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 74, in run_pre_create_schema
self._pre_create_schema(keyspace_num, scylla_encryption_options=self.params.get(
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 381, in _pre_create_schema
self.create_table(name='standard1', keyspace_name=keyspace_name, key_type='blob', read_repair=0.0, compact_storage=True,
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2321, in create_table
session.execute(query)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1767, in execute_verbose
return execute_orig(*args, **kwargs)
File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Invalid compaction strategy options {{sstable_size_in_mb, 100}} for chosen strategy type">
```

We should remove those as it was removed in dtest recently.

**Comment by fruch** [comment]
It's seems to be breaking all short longevity, so we need to get it fixed ASAP

**Comment by temichus** [comment]
@fruch I can take it today, but Could you please explain how the fix should look kike?

Do we need to remove the sstable_size_in_mb param at all?

**Comment by fruch** [comment]
> @fruch I can take it today, but Could you please explain how the fix should look kike?
> 
> Do we need to remove the sstable_size_in_mb param at all? 

No, we need to make sure it's used only in  the compaction strategy that supports it.

SCT code was abusing the fact scylla wasn't checking, and is passing some parameters regardless if they how supported

**Comment by fruch** [comment]
So the immediate thing to fix is create_table

But there might be more places, anything that uses different strategies, like ICS or ant compaction related code

**Comment by temichus** [comment]
could you please provide the test ID for the failed test to analyze logs?

**Comment by fruch** [comment]
- dfc46999-b125-40f6-b82f-b81aafabf762
- ab91e9e7-7ce9-494b-905d-0652e479072d
- b58df701-cd12-4199-8261-86d141637f77

**Comment by temichus** [comment]
found Scylla commit https://github.com/scylladb/scylladb/commit/0564d000c6ebcd32c5b24f317032176522e43ac5
sstable_size_in_mb - supports only in leveled_compaction_strategy

in all tests 
compaction={ 'class': 'SizeTieredCompactionStrategy', 'sstable_size_in_mb' : '100'}

I cant find in SCT where sstable_size_in_mb set 100. probably it is done by 

> random in  https://github.com/scylladb/scylla-cluster-tests/blob/32626541c1b7eb8612afcfac77a580e5737ed9e2/test_lib/compaction.py#L88C5-L88C44

I found only 1  usage of sstable_size_in_mb in CQL query : https://github.com/scylladb/scylla-cluster-tests/blob/32626541c1b7eb8612afcfac77a580e5737ed9e2/sdcm/tester.py#L2305

but there is indirect usage in https://github.com/scylladb/scylla-cluster-tests/blob/32626541c1b7eb8612afcfac77a580e5737ed9e2/sdcm/nemesis.py#L2423

**Comment by fruch** [comment]
@temichus 

I think the 100 is coming from:
https://github.com/scylladb/scylla-cluster-tests/blob/32626541c1b7eb8612afcfac77a580e5737ed9e2/test-cases/longevity/longevity-100gb-4h.yaml#L28

**Comment by temichus** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/6650

**Comment by roydahan** [comment]
I think we should remove this parameter at all and stop using it if we do.
