### ISSUE TITLE
Change disrupt_restart_then_repair_node nemesis to be able to run it when ip_ssh_connections="public"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#665]
If disrupt_restart_then_repair_node nemesis is run with ip_ssh_connections="public", 
replacement node procedure should be initiated.

**Comment by roydahan** [comment]
@aleksbykov I don't understand the issue here?

**Comment by bentsi** [comment]
as Israel mentioned it is super easy to fix, please fix this.

**Comment by roydahan** [comment]
@aleksbykov says it failed one of the multi-dc longevity.
@aleksbykov if this is the real issue, please send a quick fix and run when it's merged.

**Comment by aleksbykov** [comment]
Could be closed. Fixed by @juliayakovlev via https://github.com/scylladb/scylla-cluster-tests/commit/af897a04c2febe4691d06fbcd36b39f1373aff1c

**Comment by juliayakovlev** [comment]
> Could be closed. Fixed by @juliayakovlev via [af897a0](https://github.com/scylladb/scylla-cluster-tests/commit/af897a04c2febe4691d06fbcd36b39f1373aff1c)

@aleksbykov I didn't run multi-dc test. Please, let me know if you see it fails.

**Comment by aleksbykov** [comment]
@juliayakovlev it was failed with branch-4.2. Need a backport
