### ISSUE TITLE
AddRemoveMv error: Unknown column name detected in CREATE MATERIALIZED VIEW statement: column1

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6680]
Nemesis `AddRemoveMv` failed when run "CREATE MATERIALIZED VIEW" query with error:
`"Unknown column name detected in CREATE MATERIALIZED VIEW statement: column1"`

It was tried to create MV on `keyspace1.standard1` that does not have `column1` column.

```
< t:2023-10-11 11:17:22,766 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-10-11 11:17:22.762: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=7d9cc46e-0efc-44df-97fc-b75ef96fc9a3: nemesis_name=AddRemoveMv target_node=Node longevity-100gb-4h-2023-1-db-node-5562f9c5-2 [13.48.190.72 | 10.0.1.14] (seed: True)
< t:2023-10-11 11:18:49,963 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-10-11 11:18:49.962: (InfoEvent Severity.NORMAL) period_type=not-set event_id=756095b7-1774-41cf-9306-af191ce0bded
: message=Create a materialized-view for table keyspace1.standard1
< t:2023-10-11 11:19:57,463 f:nemesis.py      l:4613 c:sdcm.nemesis         p:ERROR > cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Unknown column name detected in CREATE MATERIALIZED VIEW statement: column1"
< t:2023-10-11 11:19:57,464 f:nemesis.py      l:316  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Update nemesis info with: {'start': 1697023042, 'end': 1697023197, 'duration': 154, 'node': 'Node longevity-100gb-4h-2023-1-db-node-5562f9c5-2 [13.48.190.72 | 10.0.1.14] (seed: True)', 'subtype': 'end', 'error': 'Error from server: code=2200 [Invalid query] message="Unknown column name detected in CREATE MATERIALIZED VIEW statement: column1"', 'full_traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4602, in wrapper\n    result = method(*args[1:], **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4373, in disrupt_add_remove_mv\n   self.tester.create_materialized_view(ks_name, base_table_name, view_name, [column],\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2319, in create_materialized_view\n    session.execute(query)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1727, in execute_verbose\n    return execute_orig(*args, **kwargs)\n  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute\n  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result\ncassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Unknown column name detected in CREATE MATERIALIZED VIEW statement: column1"\n'}
```

It's not clear where "column1" was found

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `2023.1.2-20231001.646df23cc4b3` with build-id `367fcf1672d44f5cbddc88f946cf272e2551b85a`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-2023-1-db-node-5562f9c5-9 (16.16.27.100 | 10.0.2.151) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-8 (16.171.65.126 | 10.0.1.255) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-7 (16.170.231.70 | 10.0.3.102) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-6 (16.170.158.14 | 10.0.3.236) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-5 (16.170.155.142 | 10.0.1.100) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-4 (16.16.28.194 | 10.0.3.250) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-3 (51.20.82.28 | 10.0.3.197) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-2 (13.48.190.72 | 10.0.1.14) (shards: 14)
- longevity-100gb-4h-2023-1-db-node-5562f9c5-1 (16.171.57.135 | 10.0.1.46) (shards: 14)

OS / Image: `ami-0928953b95c6b4f1e` (aws: eu-north-1)

Test: `longevity-100gb-4h-test`
Test id: `5562f9c5-d0fa-488d-ad61-ff3f93b8980f`
Test name: `enterprise-2023.1/longevity/longevity-100gb-4h-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c35a5e74b26a576b48cc5c6051b483c45e439454/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5562f9c5-d0fa-488d-ad61-ff3f93b8980f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5562f9c5-d0fa-488d-ad61-ff3f93b8980f)
- Show all stored logs command: `$ hydra investigate show-logs 5562f9c5-d0fa-488d-ad61-ff3f93b8980f`

## Logs:
- **db-cluster-5562f9c5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/db-cluster-5562f9c5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/db-cluster-5562f9c5.tar.gz)
- **sct-runner-events-5562f9c5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/sct-runner-events-5562f9c5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/sct-runner-events-5562f9c5.tar.gz)
- **sct-5562f9c5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/sct-5562f9c5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/sct-5562f9c5.log.tar.gz)
- **monitor-set-5562f9c5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/monitor-set-5562f9c5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/monitor-set-5562f9c5.tar.gz)
- **loader-set-5562f9c5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/loader-set-5562f9c5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/loader-set-5562f9c5.tar.gz)
- **parallel-timelines-report-5562f9c5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/parallel-timelines-report-5562f9c5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5562f9c5-d0fa-488d-ad61-ff3f93b8980f/20231011_155739/parallel-timelines-report-5562f9c5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-100gb-4h-test/16/)
[Argus](https://argus.scylladb.com/test/429a8a1c-e4f4-494c-af7f-8cad0ea2c755/runs?additionalRuns[]=5562f9c5-d0fa-488d-ad61-ff3f93b8980f)
</details>

**Comment by juliayakovlev** [comment]
I think it is Scylla issue:
```
cqlsh> desc keyspace1.standard1 

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob,
    "C5" blob,
    "C6" blob,
    "C7" blob,
    "C8" blob,
    "C9" blob
) WITH COMPACT STORAGE
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'test cf'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

```
cqlsh> SELECT * FROM system_schema.columns WHERE keyspace_name = 'keyspace1' AND table_name = 'standard1';

 keyspace_name | table_name | column_name | clustering_order | column_name_bytes | kind          | position | type
---------------+------------+-------------+------------------+-------------------+---------------+----------+------
     keyspace1 |  standard1 |          C0 |             NONE |            0x4330 |        static |       -1 | blob
     keyspace1 |  standard1 |          C1 |             NONE |            0x4331 |        static |       -1 | blob
     keyspace1 |  standard1 |          C2 |             NONE |            0x4332 |        static |       -1 | blob
     keyspace1 |  standard1 |          C3 |             NONE |            0x4333 |        static |       -1 | blob
     keyspace1 |  standard1 |          C4 |             NONE |            0x4334 |        static |       -1 | blob
     keyspace1 |  standard1 |          C5 |             NONE |            0x4335 |        static |       -1 | blob
     keyspace1 |  standard1 |          C6 |             NONE |            0x4336 |        static |       -1 | blob
     keyspace1 |  standard1 |          C7 |             NONE |            0x4337 |        static |       -1 | blob
     keyspace1 |  standard1 |          C8 |             NONE |            0x4338 |        static |       -1 | blob
     keyspace1 |  standard1 |          C9 |             NONE |            0x4339 |        static |       -1 | blob
     keyspace1 |  standard1 |     column1 |              ASC |  0x636f6c756d6e31 |    clustering |        0 | text
     keyspace1 |  standard1 |         key |             NONE |          0x6b6579 | partition_key |        0 | blob
     keyspace1 |  standard1 |       value |             NONE |      0x76616c7565 |       regular |       -1 | blob
```

**Comment by fruch** [comment]
looks like it like that for ages

**Comment by juliayakovlev** [comment]
`COMPACT STORAGE` causes to addid of 2 those columns:
```
cqlsh> CREATE TABLE keyspace1.standard5 ( key blob PRIMARY KEY,  "C0" blob, "C1" blob, "C2" blob, "C3" blob, "C4" blob, "C5" blob, "C6" blob, "C7" blob, "C8" blob, "C9" blob) WITH COMPACT STORAGE;
cqlsh> SELECT * FROM system_schema.columns WHERE keyspace_name = 'keyspace1' AND table_name = 'standard5';

 keyspace_name | table_name | column_name | clustering_order | column_name_bytes | kind          | position | type
---------------+------------+-------------+------------------+-------------------+---------------+----------+------
     keyspace1 |  standard5 |          C0 |             NONE |            0x4330 |        static |       -1 | blob
     keyspace1 |  standard5 |          C1 |             NONE |            0x4331 |        static |       -1 | blob
     keyspace1 |  standard5 |          C2 |             NONE |            0x4332 |        static |       -1 | blob
     keyspace1 |  standard5 |          C3 |             NONE |            0x4333 |        static |       -1 | blob
     keyspace1 |  standard5 |          C4 |             NONE |            0x4334 |        static |       -1 | blob
     keyspace1 |  standard5 |          C5 |             NONE |            0x4335 |        static |       -1 | blob
     keyspace1 |  standard5 |          C6 |             NONE |            0x4336 |        static |       -1 | blob
     keyspace1 |  standard5 |          C7 |             NONE |            0x4337 |        static |       -1 | blob
     keyspace1 |  standard5 |          C8 |             NONE |            0x4338 |        static |       -1 | blob
     keyspace1 |  standard5 |          C9 |             NONE |            0x4339 |        static |       -1 | blob
     keyspace1 |  standard5 |     column1 |              ASC |  0x636f6c756d6e31 |    clustering |        0 | text
     keyspace1 |  standard5 |         key |             NONE |          0x6b6579 | partition_key |        0 | blob
     keyspace1 |  standard5 |       value |             NONE |      0x76616c7565 |       regular |       -1 | blob

```

**Comment by fruch** [comment]
and the code in https://github.com/scylladb/scylla-cluster-tests/pull/6052, seem to be unaware of it

**Comment by juliayakovlev** [comment]
I do not know it it expected or not

**Comment by juliayakovlev** [comment]
This is the question of Yaniv:
`Why are we testing with COMPACT STORAGE? Didn't we deprecate it?`

**Comment by fruch** [comment]
> This is the question of Yaniv:
> `Why are we testing with COMPACT STORAGE? Didn't we deprecate it?`
> 
> @roydahan @fruch 
> Do you aware about it?

I don't remember it's deprecated, but I'm guessing cassandra-stress is defaulting to it, cause SCT code doesn't seem to do it (only on certain upgrade cases)

**Comment by roydahan** [comment]
It’s the default for c-s (or at least was).

**Comment by juliayakovlev** [comment]
@fruch @roydahan 

This nemesis was passed in another test (`longevity-10gb-3h-gce-test`) with same Scylla version and same `cassandra-stress write` load:

https://argus.scylladb.com/test/23a9f4cc-4d94-42d4-a427-6ece4fd9a487/runs?additionalRuns[]=3706dd96-5dd6-48bd-90f9-d8a655e224f4

This test is running now and I'll check the c-s table there

**Comment by fruch** [comment]
few things todo here:
1) file an issue to java-tools to change to not use COMPACT STORAGE, if it's really consider deprecated
2) SCT code should handle it till then, it would need to first check the table schema for it, and then filter those columns automatically created

**Comment by fruch** [comment]
> @fruch @avikivity and @denesb asked to open an inssue as it is not expected. Close SCT issue as it Scylla problem.
> 
> [scylladb/scylladb#16309](https://github.com/scylladb/scylladb/issues/16309)

I still think we should address it in SCT, disable COMPACT STORAGE everywhere, as a start.

**Comment by avikivity** [comment]
Agree we should test COMPACT STORAGE in system tests, only functional tests.

We should also deprecate it in new tables, and think about a migration path.

**Comment by juliayakovlev** [comment]
Re-open - disable COMPACT STORAGE everywhere in SCT

**Comment by fruch** [comment]
> @fruch we create tables with COMPACT STORAGE in sdcm/fill_db_data.py that used in upgrade test.
> Do we also want to remove it for there?

Yes, but on a separate commit, so we revert it if needed separately from other chsnges
