### ISSUE TITLE
offline-installer: Failed on arm based artifacts due to `InsufficientInstanceCapacity`

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#6684]
The following tests failed

https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2004-arm-test/243/consoleFull
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-debian10-arm-test/243/console
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-centos8-arm-test/246/console
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-arm-test/232/console

```
07:24:47  < t:2023-10-16 04:24:45,194 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-10-16 04:24:45.192: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=93489d5b-e7f3-40d3-ab46-7103424e6e90, source=ArtifactsTest.SetUp()
07:24:47  < t:2023-10-16 04:24:45,194 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (eu-west-1a). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-1b, eu-west-1c.
```

**Comment by yaronkaikov** [comment]
@soyacz Still facing this issue https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/408/consoleFull, can you please check?

**Comment by soyacz** [comment]
looks like jobs were not triggered today

**Comment by fgelcer** [comment]
> @soyacz Still facing this issue https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/408/consoleFull, can you please check?

@yaronkaikov , this job was triggered before the fix was merged... please try to re-run
