### ISSUE TITLE
Ability to select specific version when installing scylla for repo/list

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6722]
Right now we when installing scylla from a repo/list, we always select the latest version available in that repo/list
for testing master/enterprise versions it's enough, cause the repo/list would have only one version in it.

release repo/list has all of the branch releases and release candidates in them, and we'll alway take the latest one out of it.

we need a way to be able to pick a specific version out of a repo/list, for cases we want to reproduce with specific version (as we can do with SMI images)

**Comment by soyacz** [comment]
my proposal is to append specific version after a colon. E.g.:
scylla_repo: `https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-2021.1.list:2021.1.20`
then Scylla could be installed like this: `apt install scylla-enterprise=2021.1.20*`

In case version not provided, use latest
@fruch WDYT?
