### ISSUE TITLE
No capacity for loader machines in OSS perf tests

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6724]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

As in the title. From jenkins console we can see:
```
exception=An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient c4.2xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get c4.2xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f

```

## Impact

Failed perf tests, need to retry 

## How frequently does it reproduce?

Recent week, very often

## Installation details

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- perf-regression-latency-ubuntu-db-node-1e87d8af-3 (44.198.167.152 | 10.12.0.132) (shards: -1)
- perf-regression-latency-ubuntu-db-node-1e87d8af-2 (34.236.243.100 | 10.12.1.105) (shards: -1)
- perf-regression-latency-ubuntu-db-node-1e87d8af-1 (44.200.131.186 | 10.12.3.212) (shards: -1)

OS / Image: `ami-0243fc95a2d808e2d` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test id: `1e87d8af-72ee-4f38-86ed-73a20044a04b`
Test name: `scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test config file(s):

- [perf-regression-latency-1TB.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fd34adf1f50ead47aac26cfb4ff123e4b4e0d072/test-cases/performance/perf-regression-latency-1TB.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1e87d8af-72ee-4f38-86ed-73a20044a04b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1e87d8af-72ee-4f38-86ed-73a20044a04b)
- Show all stored logs command: `$ hydra investigate show-logs 1e87d8af-72ee-4f38-86ed-73a20044a04b`

## Logs:
- **db-cluster-1e87d8af.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/db-cluster-1e87d8af.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/db-cluster-1e87d8af.tar.gz)
- **sct-runner-1e87d8af.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/sct-runner-1e87d8af.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/sct-runner-1e87d8af.tar.gz)
- **monitor-set-1e87d8af.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/monitor-set-1e87d8af.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e87d8af-72ee-4f38-86ed-73a20044a04b/20231025_120226/monitor-set-1e87d8af.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-shard-aware-1TB-test/64/)
[Argus](https://argus.scylladb.com/test/623b19d1-a201-4ed0-94a2-b42347a4d2e5/runs?additionalRuns[]=1e87d8af-72ee-4f38-86ed-73a20044a04b)
</details>

**Comment by soyacz** [comment]
possibly switch to different AZ would help

**Comment by fruch** [comment]
switching to c6  mostly helped with
