### ISSUE TITLE
Perf-simple-query email results table overrides results

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6726]
When perf-simple-query test runs against previously tested Scylla build it overrides result instead of appending it to table.
We would like to have these values visible so we can compare stability across runs for the same build or at least link to ES to see them.

**Comment by fruch** [comment]
@soyacz you still think this is important to fix ?

**Comment by soyacz** [comment]
I don't think important. Maybe just preparing ES view and link would suffice keeping effort low.

**Comment by fruch** [comment]
So let revise, or close this one

**Comment by soyacz** [comment]
I revised - ES index is already done: https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/app/dashboards#/view/5f06de80-df8a-11ed-baf0-09544f843571?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d%2Fd,to:now))

As to test result verification logic - it's quite complicated without clue why it was done this way. 
I close this one as not important - until it is raised again we need to see these results.
