### ISSUE TITLE
k8s multitenatn test fails due to missing `partitions_attrs` attribute in tester object

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6727]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

SCT K8s multitenant test fails with error:
```
2023-10-22 01:17:58.265: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=267fd071-0ee8-4d5b-98e4-40344915fe32, source=LongevityOperatorMultiTenantTest.test_custom_time (longevity_operator_multi_tenant_test.LongevityOperatorMultiTenantTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/longevity_operator_multi_tenant_test.py", line 37, in test_custom_time
object_set.run(func=_run_test_on_one_tenant, unpack_objects=True, ignore_exceptions=False)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 459, in run
raise ParallelObjectException(results=results)
sdcm.utils.common.ParallelObjectException: [k8s-longevity-2-tenants--1]:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 443, in run
result = future.result(time_out)
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 419, in inner
return_val = fun(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/longevity_operator_multi_tenant_test.py", line 27, in _run_test_on_one_tenant
tenant.test_custom_time()
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 131, in test_custom_time
if self.partitions_attrs and self.partitions_attrs.validate_partitions:
AttributeError: 'TenantForLongevityTest-1' object has no attribute 'partitions_attrs'
[k8s-longevity-2-tenants--2]:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 443, in run
result = future.result(time_out)
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 419, in inner
return_val = fun(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/longevity_operator_multi_tenant_test.py", line 27, in _run_test_on_one_tenant
tenant.test_custom_time()
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 131, in test_custom_time
if self.partitions_attrs and self.partitions_attrs.validate_partitions:
AttributeError: 'TenantForLongevityTest-2' object has no attribute 'partitions_attrs'
```

## Impact

Multitenant tests don't work

## How frequently does it reproduce?

always

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `5.5.0~dev-20231019.7d5e22b43b64` with build-id `24849f2c8ab97292bd8df0296ccd5f09377a4899`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-13-g4bc44d9
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-3h-multitenant-eks`
Test id: `edb857ed-3a66-4d75-879a-181b74c52146`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-multitenant-eks`
Test config file(s):

- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60806e7b31f0e9351674ba718a5cdac8df07b86/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor edb857ed-3a66-4d75-879a-181b74c52146`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=edb857ed-3a66-4d75-879a-181b74c52146)
- Show all stored logs command: `$ hydra investigate show-logs edb857ed-3a66-4d75-879a-181b74c52146`

## Logs:
- **kubernetes-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/kubernetes-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/kubernetes-edb857ed.tar.gz)
- **db-cluster-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/db-cluster-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/db-cluster-edb857ed.tar.gz)
- **sct-runner-events-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/sct-runner-events-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/sct-runner-events-edb857ed.tar.gz)
- **sct-edb857ed.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/sct-edb857ed.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/sct-edb857ed.log.tar.gz)
- **loader-set-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/loader-set-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/loader-set-edb857ed.tar.gz)
- **monitor-set-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/monitor-set-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/monitor-set-edb857ed.tar.gz)
- **parallel-timelines-report-edb857ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/parallel-timelines-report-edb857ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/edb857ed-3a66-4d75-879a-181b74c52146/20231022_012249/parallel-timelines-report-edb857ed.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks/93/)
[Argus](https://argus.scylladb.com/test/7774c24a-b749-4528-97a4-22785e7e5b6f/runs?additionalRuns[]=edb857ed-3a66-4d75-879a-181b74c52146)
</details>

**Comment by fruch** [comment]
looks like somehting https://github.com/scylladb/scylla-cluster-tests/commit/48c2faa1b00cafdd2ff3e071d42bd773f8954867 introduced
