### ISSUE TITLE
Update scylla_repo_loader param default (change from .../scylla-4.6.repo' which is non-existent) 

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6738]
scylla_repo_loader: 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-4.6.repo'

**Comment by fruch** [comment]
that configuration option was already removed, at some point.

but it was revert, to support cases of rebuilding our loader images from scratch.

but it's not really being used for anything else, and it's default can be safely empty
