### ISSUE TITLE
Failing to delete placement groups

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6742]
Couldn't delete placement group in job: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-throughput-non-shard-aware-i4i-test/30/:
```
09:44:27  Going to delete placement group 'perf-regression-i4i-ubuntu-placement_group-2babbc08 in region us-east-1
09:44:28  Failed with: An error occurred (InvalidPlacementGroup.InUse) when calling the DeletePlacementGroup operation: The placement group 'perf-regression-i4i-ubuntu-placement_group-2babbc08' is in use and may not be deleted.
```

**Comment by fruch** [comment]
I've found one also in eu-west-1, from a different job

I'm guessing we are not waiting for instances deletion, and we might get to this part of code, when instances are not yet deleted/stopped

**Comment by fruch** [comment]
anyhow there seems to be a retry on top of it
```
@retrying(n=30, sleep_time=10, allowed_exceptions=(ClientError,))
```

maybe we should just squelch the errors from being printed

**Comment by fruch** [comment]
@soyacz still happening ?

**Comment by soyacz** [comment]
> @soyacz still happening ?

yes, I created quick PR with fix: https://github.com/scylladb/scylla-cluster-tests/pull/7400
