### ISSUE TITLE
Failure to run monitor container - can't find image 'mikefarah/yq:3' locally

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6743]
From https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-twcs-3h-test/3/ : 
```
Command: "sudo docker run --rm -v /home/ubuntu/sct-monitoring/scylla-monitoring-src/config:/workdir mikefarah/yq:3 yq w -i node_exporter_servers.yml '[0].targets[+]' ''[10.12.1.132]:9100''"
Exit code: 125
Stdout:
Stderr:
Unable to find image 'mikefarah/yq:3' locally
```

Additionally, we use v3 - but apparently v4 was released quite some time ago. Different than v3, so might require some changes. Upgrade guide - https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3

**Comment by mykaul** [comment]
I could not find the use of 'yq' in this repo, only the change to explicitly use v3 @ https://github.com/scylladb/scylla-cluster-tests/commit/a7b6a7b01fbedd7271b4362218ea9f560fae698e
@fruch  ?

**Comment by mykaul** [comment]
BTW, the issue may be a temporary hiccup in Dockerhub:
```
docker: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable.
```

(which is again why I suggest moving to Quay.IO!)

**Comment by mykaul** [comment]
https://www.dockerstatus.com/pages/incident/533c6539221ae15e3f000031/65400e537b554505b4c8c0df

**Comment by mykaul** [comment]
To complete the picture, this is how siren deploys yq - still unsure for which purpose: https://github.com/scylladb/siren/blob/8f648e513969f82648d338456dea054afb166c8a/cluster/setup/scripts/yq.sh

**Comment by fruch** [comment]
> w -i node_exporter_servers.yml '[0].targets[+]' ''[10.12.1.132]:9100''"

the usage is right here on the command:
```
yq w -i node_exporter_servers.yml '[0].targets[+]' ''[10.12.1.132]:9100''"
```

it's used to update the targets in the monitor yaml, since we didn't had yq available, and in some cases we just get monitor image as is, we used this, now we probably have better means to edit that file. (for example using the `remote_file` context manager)

**Comment by fruch** [comment]
I'll try to get rid of it in:
https://github.com/scylladb/scylla-cluster-tests/pull/6746
