### ISSUE TITLE
`NetworkRandomInterruptions` doesn't find `node_network_receive_bytes_total` metric:

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6757]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

`NetworkRandomInterruptions` doesn't find `node_network_receive_bytes_total` metric:
```
2023-11-05 02:26:00.445: (DisruptionEvent Severity.ERROR) period_type=end event_id=d46ff8ba-d504-4722-8890-7232328fa977 duration=0s: nemesis_name=NetworkRandomInterruptions target_node=Node sct-cluster-eu-north-1-rack-1-2 [10.0.3.54 | 10.0.3.87] (seed: False) errors=no results for node_network_receive_bytes_total metric in Prometheus
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5077, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3258, in disrupt_network_random_interruptions
self._disrupt_network_random_interruptions_k8s(list_of_timeout_options)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3216, in _disrupt_network_random_interruptions_k8s
rate_limit: Optional[str] = self.get_rate_limit_for_network_disruption()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3197, in get_rate_limit_for_network_disruption
assert results, "no results for node_network_receive_bytes_total metric in Prometheus "
AssertionError: no results for node_network_receive_bytes_total metric in Prometheus
```

this is clearly in the middle of the use case, and we should have ongoing stress command, it's not clear why we are not 
getting a metric for this one

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.10.197-186.748.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-56-ge771cb4
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-3h-eks`
Test id: `ad387c9a-51af-4c9c-9a5c-56e234322ff7`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/932d90acc6fe19dec3e1dc5eb58598919b9f4dae/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ad387c9a-51af-4c9c-9a5c-56e234322ff7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ad387c9a-51af-4c9c-9a5c-56e234322ff7)
- Show all stored logs command: `$ hydra investigate show-logs ad387c9a-51af-4c9c-9a5c-56e234322ff7`

## Logs:
- **kubernetes-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/kubernetes-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/kubernetes-ad387c9a.tar.gz)
- **db-cluster-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/db-cluster-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/db-cluster-ad387c9a.tar.gz)
- **sct-runner-events-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/sct-runner-events-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/sct-runner-events-ad387c9a.tar.gz)
- **sct-ad387c9a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/sct-ad387c9a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/sct-ad387c9a.log.tar.gz)
- **loader-set-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/loader-set-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/loader-set-ad387c9a.tar.gz)
- **monitor-set-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/monitor-set-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/monitor-set-ad387c9a.tar.gz)
- **parallel-timelines-report-ad387c9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/parallel-timelines-report-ad387c9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad387c9a-51af-4c9c-9a5c-56e234322ff7/20231105_035804/parallel-timelines-report-ad387c9a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/133/)
[Argus](https://argus.scylladb.com/test/028aa2df-5ce5-4883-a4a8-16bfbbe8dcc8/runs?additionalRuns[]=ad387c9a-51af-4c9c-9a5c-56e234322ff7)
</details>

                            

```[tasklist]
### Tasks
```

**Comment by fruch** [comment]
looks like ip address was changed right before:
![image](https://github.com/scylladb/scylla-cluster-tests/assets/340979/750722f3-bc72-420a-898e-6ea3392b22bb)

**Comment by soyacz** [comment]
It's not about changed ip address - monitoring switched from publishing data for pod ips to k8s node ip's.

@vponomaryov did something changed related to this intentionally, or it's some scylla/operator/monitoring issue?

**Comment by fruch** [comment]
> It's not about changed ip address - monitoring switched from publishing data for pod ips to k8s node ip's.
> 
> @vponomaryov did something changed related to this intentionally, or it's some scylla/operator/monitoring issue?

it's SCT that setup the monitoring upon changes

**Comment by fruch** [comment]
@soyacz where do you see anything switching ?, it was using 10.0.3.87:9180, all the time.

**Comment by soyacz** [comment]
> @soyacz where do you see anything switching ?, it was using 10.0.3.87:9180, all the time.

I verifed previous passing run - monitoring was showing IP's as they are visible in sct log (for db node), while the recent failing runs are showing IP's of k8s nodes

**Comment by soyacz** [comment]
I wonder if https://github.com/scylladb/scylla-cluster-tests/pull/6746 didn't break smthing

**Comment by soyacz** [comment]
```
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG > New content of `/home/ubuntu/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml':
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG > - targets:
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.1.127:9180
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.2.208:9180
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.3.87:9180
< t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - '[10.0.1.255]:9100'
```
Seems it is not updating correctly - there's only 1 target for node_exporter

**Comment by vponomaryov** [comment]
> It's not about changed ip address - monitoring switched from publishing data for pod ips to k8s node ip's.

Are you sure about the `K8S node IP`s ? 
K8S node IPs must not be used for the monitoring because we do not use `hostNetworking` setup.
It must use pod IPs only. Always.

> @vponomaryov did something changed related to this intentionally, or it's some scylla/operator/monitoring issue?

I didn't touch the monitoring part.

> I wonder if #6746 didn't break smthing

Sounds suspicious.

**Comment by fruch** [comment]
> ```
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG > New content of `/home/ubuntu/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml':
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG > - targets:
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.1.127:9180
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.2.208:9180
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - 10.0.3.87:9180
> < t:2023-11-05 02:00:55,518 f:remote_file.py  l:64   c:sdcm.remote.remote_file p:DEBUG >   - '[10.0.1.255]:9100'
> ```
> 
> Seems it is not updating correctly - there's only 1 target for node_exporter

as we should, 3 scylla node, one monitor node

**Comment by vponomaryov** [comment]
Having the [improvement(k8s): add support of the multiple kubeconfig files](https://github.com/scylladb/scylla-cluster-tests/commit/82b4e8a4c1610896244a14f494b2000e797cc4ba) as basis, my staging jobs didn't have this problem.
The next merged commit after it was the [fix(monitor-setup): stop using mikefarah/yq docker](https://github.com/scylladb/scylla-cluster-tests/commit/932d90acc6fe19dec3e1dc5eb58598919b9f4dae)
So,  my suspicion for it gets harder.

**Comment by vponomaryov** [comment]
Monitoring query:
```
2023-11-05 02:25:59,994 f:db_stats.py     l:263  c:sdcm.db_stats        p:DEBUG > Query to PrometheusDB: http://10.0.1.255:9090/api/v1/query_range?query=avg(node_network_receive_bytes_total{instance=~".*?10.0.3.87.*?", device       ="eth0"})&start=1699150559.9947512&end=1699151159.9947512&step=20
```

It used the `10.0.3.87` IP address which had gone at the `2023-11-05 02:06:18,278`.

```
2023-11-05 02:06:06,287 f:cluster.py      l:1186 c:sdcm.cluster         p:INFO  > Node sct-cluster-eu-north-1-rack-1-2 [10.0.3.54 | 10.0.3.87] (seed: False) destroyed
2023-11-05 02:06:13,198 f:nemesis.py      l:1202 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Adding new node to cluster...
2023-11-05 02:06:13,206 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-11-05 02:06:13.199: (InfoEvent Severity.NORMAL) period_type=not-set event_id=f0195d8e-7ad9-4c5f-a7e1-c0193d12c0b3: message=StartEvent - Adding new node to cluster
2023-11-05 02:06:18,278 f:__init__.py     l:929  c:sdcm.utils.k8s       p:INFO  > 'scylla/sct-cluster-eu-north-1-rack-1-2' node has changed it's pod IP address from '10.0.3.87' to '10.0.2.159'. All old IPs: 10.0.3.162, 10.0.3.87
```

**Comment by vponomaryov** [comment]
Hm, it got that IP back again later:
```
2023-11-05 02:18:00,260 f:__init__.py     l:929  c:sdcm.utils.k8s       p:INFO  > 'scylla/sct-cluster-eu-north-1-rack-1-2' node has changed it's pod IP address from '10.0.2.159' to '10.0.3.87'. All old IPs: 10.0.3.162, 10.0.3       .87, 10.0.2.159
2023-11-05 02:18:00,263 f:__init__.py     l:953  c:sdcm.utils.k8s       p:DEBUG > Calling 'refresh_scylla_pod_ip_address' callback (namespace=scylla, pod_name=sct-cluster-eu-north-1-rack-1-2)
2023-11-05 02:18:00,458 f:__init__.py     l:953  c:sdcm.utils.k8s       p:DEBUG > Calling 'reconfigure_scylla_monitoring' callback (namespace=scylla, pod_name=sct-cluster-eu-north-1-rack-1-2)
```

**Comment by fruch** [comment]
maybe it has something todo with the fact we are copying it, and using root.

**Comment by vponomaryov** [comment]
The problem has gone in my staging test run after reverting the `fix(monitor-setup): stop using 'mikefarah/yq' docker` commit.
Proof: https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks/80/

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/commit/8409417e7550a458c43dbf16d44f4aa981a8b6fa was reverted, can we close this one?

**Comment by fruch** [comment]
> https://github.com/scylladb/scylla-cluster-tests/commit/8409417e7550a458c43dbf16d44f4aa981a8b6fa was reverted, can we close this one?

Not yet

I'm testing a fix for it
