### ISSUE TITLE
SCT monitoring lacks the DC info making the dc filter be useless in grafana

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6779]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: any
* **scylla**: any

### Logs
* test_id: -
* job log: -

### Description

![Screenshot from 2023-11-09 14-24-37](https://github.com/scylladb/scylla-cluster-tests/assets/3796058/9ef88b40-e4e0-4607-9475-f73f2577c376)

### Steps to Reproduce

1. Run any SCT test with monitoring
2. Try to filter the nodes by their `dc`
3. See that filtering doesn't show the DCs at all to be applied

**Expected behavior:** I expect the `dc` filter to work in the monitoring.

**Actual behavior:** The `dc` filter is useless

**Comment by vponomaryov** [comment]
Related code is here:
- https://github.com/scylladb/scylla-cluster-tests/blob/2400d907/sdcm/cluster.py#L5561-L5590
- https://github.com/scylladb/scylla-monitoring/blob/master/genconfig.py

**Comment by fruch** [comment]
we need to handle this for monitoring 4.7 anyhow

**Comment by vponomaryov** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/7627
Found bug for the monitoring-4.7: https://github.com/scylladb/scylla-cluster-tests/issues/7626

**Comment by vponomaryov** [comment]
The https://github.com/scylladb/scylla-cluster-tests/pull/7627 has been merged.
