### ISSUE TITLE
left over from manager restore nemesis may not be a fit for other nemeses

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#6790]
## Issue description

we had a `disrupt_mgmt_restore` nemesis just before `disrupt_add_remove_dc`, and it ended up having a failure :
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5074, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4390, in disrupt_add_remove_dc
    self._switch_to_network_replication_strategy(self.cluster.get_test_keyspaces() + system_keyspaces)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4369, in _switch_to_network_replication_strategy
    replication_strategy = ReplicationStrategy.get(node, keyspace)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 24, in get
    create_ks_statement = node.run_cqlsh(f"describe {keyspace}").stdout.splitlines()[1]
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2856, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "describe "100gb_sizetiered_5_2"" 10.4.8.224 9042'

Exit code: 2

Stdout:



Stderr:


Warning: Using a password on the command line interface can be insecure.
Recommendation: use the credentials file to securely provide the password.

<stdin>:1:Improper describe command.
```

## Impact

`disrupt_add_remove_dc` fails, because of a keyspace created by restore nemesis, `100gb_sizetiered_5_2`

## How frequently does it reproduce?

not sure, but probably everytime we run `disrupt_add_remove_dc` after we had `disrupt_mgmt_restore`

## Installation details

Kernel Version: 5.15.0-1048-aws
Scylla version (or git commit hash): `5.4.0~rc1-20231029.24efacf90d0b` with build-id `878fe67520f7c3da9f2d36a90cd4a5612549d2ed`

Cluster size: 4 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-8 (54.74.205.1 | 10.4.9.114) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-7 (3.253.15.16 | 10.4.10.240) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-6 (34.254.178.226 | 10.4.8.82) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-5 (52.214.158.108 | 10.4.11.227) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-4 (52.215.78.203 | 10.4.11.10) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-3 (34.245.211.34 | 10.4.8.186) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-2 (3.252.148.57 | 10.4.8.178) (shards: 15)
- longevity-200gb-48h-verify-limited--db-node-bb19dae3-1 (54.195.215.97 | 10.4.8.224) (shards: 15)

OS / Image: `ami-0b21c9ee6a0c5cbdc` (aws: undefined_region)

Test: `longevity-200gb-48h-arm-test`
Test id: `bb19dae3-1e8a-4564-a78e-6911b4260c63`
Test name: `scylla-5.4/longevity/longevity-200gb-48h-arm-test`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/86e790b8fc04e31fae746e411198fe365b2766ae/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor bb19dae3-1e8a-4564-a78e-6911b4260c63`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bb19dae3-1e8a-4564-a78e-6911b4260c63)
- Show all stored logs command: `$ hydra investigate show-logs bb19dae3-1e8a-4564-a78e-6911b4260c63`

## Logs:
- **db-cluster-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/db-cluster-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/db-cluster-bb19dae3.tar.gz)
- **sct-runner-events-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-runner-events-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-runner-events-bb19dae3.tar.gz)
- **sct-bb19dae3.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-bb19dae3.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-bb19dae3.log.tar.gz)
- **loader-set-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/loader-set-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/loader-set-bb19dae3.tar.gz)
- **monitor-set-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/monitor-set-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/monitor-set-bb19dae3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-200gb-48h-arm-test/3/)
[Argus](https://argus.scylladb.com/test/d7570ae6-3f9d-4cf4-ab4e-389cd1be27b9/runs?additionalRuns[]=bb19dae3-1e8a-4564-a78e-6911b4260c63)
</details>

**Comment by fgelcer** [comment]
maybe the mgmt repair needs to remove every keyspace and tables created during it?

**Comment by fruch** [comment]
> maybe the mgmt repair needs to remove every keyspace and tables created during it?

There's two issues here

Yeah nemesis should clean after itself,

And the code calling describe isn't handling escaping correctly and should be fixed

**Comment by roydahan** [comment]
Reduced the priority, till we see it again if we see after Fabio's fix.

**Comment by mykaul** [comment]
Seen in [longevity-200gb-48h-arm-test#3](https://argus.scylladb.com/test/d7570ae6-3f9d-4cf4-ab4e-389cd1be27b9/runs?additionalRuns[]=bb19dae3-1e8a-4564-a78e-6911b4260c63)

**Comment by soyacz** [comment]
> Seen in [longevity-200gb-48h-arm-test#3](https://argus.scylladb.com/test/d7570ae6-3f9d-4cf4-ab4e-389cd1be27b9/runs?additionalRuns%5B%5D=bb19dae3-1e8a-4564-a78e-6911b4260c63)

This should be fixed already - mentioned job is from before fixes.
