### ISSUE TITLE
Add ability to add a node during a test which is a different instance type than the one defined in cluster.BaseNode

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#6796]
In some new test cases, e.g. (a [full cluster replacement](https://github.com/scylladb/qa-tasks/issues/1164) with a new instance type), there is a need to support add_node that has a different instance_type than the original nodes of the cluster.

E.g. we have a cluster of i4i.large and we would like to add a new node that is of a type i4i.2xlarge.

**Comment by fruch** [comment]
This PR https://github.com/scylladb/scylla-cluster-tests/pull/6797 is a draft for adding this support.

adding ontop of a configuration, or a hardcode test with the instances to use.
