### ISSUE TITLE
KMS encryption check is failing

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6825]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

all the places we have the check are failing like that:
```
2023-11-17 04:07:00.179: (AwsKmsEvent Severity.ERROR) period_type=one-time event_id=65ccf23b-1715-4a35-97f7-6d3fba4b188a: message=Failed to check the fact of encryption (KMS) for sstables
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4478, in _rotate_kms_key
assert all(encryption_result is True for encryption_result in encryption_results)
AssertionError
```

I some of the code making `scylla sstable` read encrypted was introduced and breaks the assumptions of this call

## Impact

validation of encryption isn't working, and we can't be  sure encryption was enabled

## How frequently does it reproduce?

it reproduce on enterprise builds and on 2024.1 builds, and 2023.1.2 and up

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `2023.1.2-20231001.646df23cc4b3` with build-id `367fcf1672d44f5cbddc88f946cf272e2551b85a`

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-encrypt-at-rest-200gb-6h--db-node-ed99c513-4 (54.242.142.57 | 10.12.10.61) (shards: 14)
- longevity-encrypt-at-rest-200gb-6h--db-node-ed99c513-3 (3.89.29.181 | 10.12.9.108) (shards: 14)
- longevity-encrypt-at-rest-200gb-6h--db-node-ed99c513-2 (3.80.183.203 | 10.12.10.196) (shards: 14)
- longevity-encrypt-at-rest-200gb-6h--db-node-ed99c513-1 (54.210.80.244 | 10.12.11.111) (shards: 14)

OS / Image: `ami-08d83ace0c0d35567` (aws: undefined_region)

Test: `EaR-longevity-kms-200gb-6h-test`
Test id: `ed99c513-0cd9-4e42-b890-ac7d53735965`
Test name: `scylla-staging/fruch/EaR-longevity-kms-200gb-6h-test`
Test config file(s):

- [longevity-encryption-at-rest-200GB-6h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ec511e13309e5caa6813efff2c1783d4436594fd/test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ed99c513-0cd9-4e42-b890-ac7d53735965`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ed99c513-0cd9-4e42-b890-ac7d53735965)
- Show all stored logs command: `$ hydra investigate show-logs ed99c513-0cd9-4e42-b890-ac7d53735965`

## Logs:
- **db-cluster-ed99c513.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/db-cluster-ed99c513.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/db-cluster-ed99c513.tar.gz)
- **sct-runner-events-ed99c513.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/sct-runner-events-ed99c513.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/sct-runner-events-ed99c513.tar.gz)
- **sct-ed99c513.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/sct-ed99c513.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/sct-ed99c513.log.tar.gz)
- **loader-set-ed99c513.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/loader-set-ed99c513.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/loader-set-ed99c513.tar.gz)
- **monitor-set-ed99c513.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/monitor-set-ed99c513.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed99c513-0cd9-4e42-b890-ac7d53735965/20231117_060554/monitor-set-ed99c513.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/EaR-longevity-kms-200gb-6h-test/19/)
[Argus](https://argus.scylladb.com/test/56e33bdb-f4fa-451f-b930-030150919046/runs?additionalRuns[]=ed99c513-0cd9-4e42-b890-ac7d53735965)
</details>

**Comment by mykaul** [comment]
@fruch - is this backported? Specifically, to 2024.1 and 2023.1.x?

**Comment by bhalevy** [comment]
I see it in branch-2024.1, 6b6a08ebe98ef2d3b1abaedf663c82dc62e0a570

**Comment by bhalevy** [comment]
However, [enterprise-2024.1/SCT_Enterprise_Features/LDAP/longevity-100gb-4h-ldap-authorization-authenticator-test#4](https://argus.scylladb.com/test/2f12c643-fe68-4dae-99da-c327cf7a0229/runs?additionalRuns[]=9c8c168f-4e8d-477b-b862-05d1cf77f574) failed with
```
2023-12-07 17:43:11.154: (AwsKmsEvent Severity.ERROR) period_type=one-time event_id=86c386ad-a3c0-470b-8b84-afd07ea3c8f2: message=Failed to check the fact of encryption (KMS) for sstables
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4340, in _rotate_kms_key
assert all(encryption_result is True for encryption_result in encryption_results)
AssertionError
```

Running SCT@a573c0639c0ef39a6081f4ddef52e6fadce6fd5f which is supposed to have this fix.

@fruch please look into it

**Comment by bhalevy** [comment]
Reopening the issue since it looks like https://github.com/scylladb/scylla-cluster-tests/commit/6b6a08ebe98ef2d3b1abaedf663c82dc62e0a570 does not solve the problem

**Comment by fruch** [comment]
> Reopening the issue since it looks like [6b6a08e](https://github.com/scylladb/scylla-cluster-tests/commit/6b6a08ebe98ef2d3b1abaedf663c82dc62e0a570) does not solve the problem

the PR solved it, but 2024.1 doesn't have all the needed core fixes yet, for it to work.

**Comment by bhalevy** [comment]
> > Reopening the issue since it looks like [6b6a08e](https://github.com/scylladb/scylla-cluster-tests/commit/6b6a08ebe98ef2d3b1abaedf663c82dc62e0a570) does not solve the problem
> 
> the PR solved it, but 2024.1 doesn't have all the needed core fixes yet, for it to work.

What other core fixes are needed?

**Comment by fruch** [comment]
@bhalevy in the one you refer the failure of running `scylla sstable`, is:
```
< t:2023-12-07 16:41:39,885 f:sstable_utils.py l:83   c:SstableUtils         p:DEBUG > error processing arguments: could not load schema via schema-tables: std::invalid_argument (Unknown option : kms_hosts)
```

i.e. it failed in reading the scylla.yaml, and part of the fixes @denesb or @elcallio did, I don't know the exact commit

the rest of the issue related to this encryption check are disscussed in https://github.com/scylladb/scylla-enterprise/issues/3684

**Comment by denesb** [comment]
I think this is another issue which could be solved by specifying `scylla.yaml`.

**Comment by fruch** [comment]
> I think this is another issue which could be solved by specifying `scylla.yaml`.

we already do:

```
< t:2023-12-18 11:32:32,241 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo /usr/bin/scylla sstable dump-scylla-metadata --scylla-yaml-file /etc/scylla/scylla.yaml  --logger-log-level scylla-sstable=debug --keyspace scylla_bench --table test --sstables /var/lib/scylla/data/scylla_bench/test-2cb40c809d9111eebc8043dccd9bf189/me-3gc0_0tze_4h6gw2h1yy429yrmo9-big-Data.db"...
```

**Comment by denesb** [comment]
Are schema tables also encrypted by any chance? Currently, config is not propagated to schema loading code.
Opened https://github.com/scylladb/scylladb/issues/16480.

**Comment by elcallio** [comment]
Only if the node is running with `system_info_encryption` active.

**Comment by fruch** [comment]
> Only if the node is running with `system_info_encryption` active.

It is

**Comment by denesb** [comment]
Ok, I'm working on a tentative fix for this.

**Comment by denesb** [comment]
I think this is https://github.com/scylladb/scylladb/issues/16480 and also possibly https://github.com/scylladb/scylladb/issues/16492.

**Comment by fruch** [comment]
> Ok, I'm working on a tentative fix for this.

I'm guessing that it's not that we can't read them at all, cause the command does work on some cases

**Comment by denesb** [comment]
@fruch do you use MV or index in the test? I found out, reading the schemas of those doesn't work at all.
