### ISSUE TITLE
Throughput in perf tests is reported incorrectly for i4i.4xlarge test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6841]
When verifying throughput performance in https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-throughput-non-shard-aware-i4i-4xlarge-test/9/
test_id: e2e2557c-be75-410f-a2a1-837b61a79f97
(i4i.4xlarge, non-shard aware) I noticed reported throughput doesn't match graphs:
![image](https://github.com/scylladb/scylla-cluster-tests/assets/18242288/79c1bd0c-20c9-4a0b-a361-29abab6a4891)

While `stats_total': {'op rate': 344408.0, 'Total errors': ''}` - and this value is taken to report.

From c-s results, value 344kops looks fine (12 processes with 28700 avg op rate).
stress cmd: `cassandra-stress write no-warmup cl=QUORUM duration=60m -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)'  -mode cql3 native -rate threads=150 -col 'size=FIXED(128) n=FIXED(8)' -pop seq=1..30000000`

The strange thing is also that it happens only for  i4i.4xlarge machines test - when running with i4i.2xlarge the same job shows correct values (or at least close to graphs). See e.g. https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-throughput-non-shard-aware-i4i-4x-test/7/consoleFull with test_id: aa71cdfa-cd7d-4027-9d1e-0cae83a47843
stress cmd: `stress_cmd_w: cassandra-stress write no-warmup cl=QUORUM duration=60m -mode cql3 native -rate threads=60 -col 'size=FIXED(128) n=FIXED(8)' -pop seq=1..650000000` with 6 loaders no process multiplier. Avg ops reported by loaders is 59086

**Comment by soyacz** [comment]
continuing investigation as could be that the previous run was rebased to branch-perf-v14 so I'm not sure yet of this, that's why I'm retrying with i4i.4xlarge and rebased to branch-perf-v14 (https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-throughput-non-shard-aware-i4i-4xlarge-test/14/)

**Comment by fruch** [comment]
I thought we might have difference on the c-s thread, but not of them seem relevant:
```bash
🟢 ❯ git log --oneline upstream/branch-perf-v14..upstream/master -- sdcm/stress_thread.py
f57ce405a test(custom_profile_d): Longevity with custom_d profile
155634898 fix(remote_logger): rework SSH-based remote loggers
92f2e247b refactor(naming): refactored naming around ip addresses
f531b304b fix(stress_thread): `stop_test_on_failure` affect log parsing
02ddb5b75 refactor(stress.base): convert stress killed to warning
0e40d8afe fix(c-s timeout): prolong timeout for c-s
ae8bcfb68 improvement(stress): add datacenter to c-s command for multi DC test
fb1f4a921 test(longevity): new longevity for MV running in synchronous mode
611b2395f fix(stress): fix c-s timeouts
```

**Comment by fruch** [comment]
@soyacz can we close it, now we know it was monitoring issue ?

**Comment by soyacz** [comment]
> @soyacz can we close it, now we know it was monitoring issue ?

yes, closing.
