### ISSUE TITLE
sctool restore failed: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_5_2.standard1: not found

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cluster-tests#6842]
I'm not sure if this is the right place to file this issue, please move it if it doesn't belong here.

In https://argus.scylladb.com/workspace?state=WyI5NjIwNzVjYi00MzQxLTQxZTUtODQ3OC0wZjNjMzBiZGNmZDYiXQ
we hit a `sctool restore` error:

```
2023-11-22 01:54:57.285: (DisruptionEvent Severity.ERROR) period_type=end event_id=76426d5b-d8c6-4441-99f6-556cce93a7e3 duration=13m17s: nemesis_name=MgmtRestore target_node=Node longevity-100gb-4h-5-4-db-node-dbdba817-10 [34.226.192.27 | 10.12.10.156] (seed: True) errors=Encounter
ed an error on sctool command: restore -c d6df5d09-c109-4062-815f-9ab10639ec82 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC: Encountered a bad command exit code!

Command: 'sudo sctool restore -c d6df5d09-c109-4062-815f-9ab10639ec82 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC'

Exit code: 1

Stdout:



Stderr:

Error: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_5_2.standard1: not found
Trace ID: g9weRzKuQfC-EmdX6H9V_Q (grep in scylla-manager logs)



Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1125, in run
    res = self.manager_node.remoter.sudo(f"sctool {cmd}")
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
    return self.run(cmd=cmd,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
```

But I can't find the scylla-manager logs for investigating `Trace ID: g9weRzKuQfC-EmdX6H9V_Q`

**Comment by fruch** [comment]
manager logs are collected, but it's inside the monitor node logs, where the manager runs.

splitting it into it's own file, probably gonna be clearer

**Comment by bhalevy** [comment]
Ok, thanks to @fruch I found monitor-set-dbdba817/longevity-100gb-4h-5-4-monitor-node-dbdba817-1/scylla_manager.log

**Comment by bhalevy** [comment]
monitor-set-dbdba817/longevity-100gb-4h-5-4-monitor-node-dbdba817-1/scylla_manager.log:
```
Nov 22 01:54:55 longevity-100gb-4h-5-4-monitor-node-dbdba817-1 scylla-manager[14156]: {"L":"INFO","T":"2023-11-22T01:54:55.089Z","N":"http","M":"POST /api/v1/cluster/d6df5d09-c109-4062-815f-9ab10639ec82/tasks","from":"127.0.0.1:35950","status":404,"bytes":189,"duration":"1066ms","error":"get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_5_2.standard1: not found","_trace_id":"g9weRzKuQfC-EmdX6H9V_Q"}
```

I'm not sure if this table was ever included in the snapshot.

@karol-kokoszka can you please look into this?

**Comment by karol-kokoszka** [comment]
@bhalevy @fruch 
```
"get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_5_2.standard1: not found"
```
This error is triggered when SM tries to check what is the value of tombstone_gc for given table, but the table is not found.
It's a simple CQL query that is executed
`select extensions from system_schema.tables where kesypace_name = ? and table_name = ?`.

Now, why it queries for this particular table.
It does it because the table is part of the snapshot that is being restores.

One of the [prerequisite](https://manager.docs.scylladb.com/stable/restore/restore-tables.html#prerequisites) to restore-tables with the scylla-manager is to have proper schema created already.
There is even a [command](https://manager.docs.scylladb.com/stable/sctool/restore.html#restore-schema) to do that, and it does it by restoring system_schema keyspace from the snapshot.

Taking a look on the SCT output from the logs, I see that the schema is restored some other (than sctool restore --restore-schema) way and most likely it restores different schema than is available in the snapshot.
```
< t:2023-11-21 23:22:20,218 f:nemesis.py      l:2812 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Restoring the keyspace 5gb_sizetiered_5_2
< t:2023-11-21 23:22:21,607 f:nemesis.py      l:2816 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Restoring the schema of the keyspace '5gb_sizetiered_5_2'
```

I didn't find any entry for `--restore-schema` query in the SCT logs. 

Whoever is maintaining this test, must make sure that it recreates exactly the same schema that is backed up in the snapshot that is used with the restore procedure.
The best way is to change the test the way that the schema is restored with sctool using the same snapshot that participates in `--restore-tables`.

Let me unassign myself from this issue.

**Comment by bhalevy** [comment]
@fruch reassigning to your team to follow-up on the SCT side.  Thanks @karol-kokoszka for your analysis

**Comment by roydahan** [comment]
@rayakurl as one who test manager, please check if there is a problem with how SCT restore the schema.
I would start by checking which manager version this branch uses and if it has/had that --schema feature that is mentioned above.

**Comment by rayakurl** [comment]
> Still hitting this. See below for 2024.1 What's the progress?
> 
> For example: [https://argus.scylladb.com/test/6af3624b-cded-4040-a656-e9246811b687/runs?additionalRuns[]=13c5e645-3ceb-4d1f-b2fa-60bd6b708ecf](https://argus.scylladb.com/test/6af3624b-cded-4040-a656-e9246811b687/runs?additionalRuns%5B%5D=13c5e645-3ceb-4d1f-b2fa-60bd6b708ecf)
> 
> ```
> Node longevity-fips-2024-1-db-node-13c5e645-5 [54.155.92.221 | 10.4.2.216] (seed: True)
> Nemesis: MgmtRestore
> 
> 2023-11-30 01:46:30.786: (DisruptionEvent Severity.ERROR) period_type=end event_id=79f995d4-e102-42b4-8e28-3781f97c2931 duration=12m25s: nemesis_name=MgmtRestore target_node=Node longevity-fips-2024-1-db-node-13c5e645-5 [54.155.92.221 | 10.4.2.216] (seed: True) errors=Encountered an error on sctool command: restore -c c6e77b96-32d7-4290-9af7-d95ca5f49dd6 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702201949UTC: Encountered a bad command exit code!
> Command: 'sudo sctool restore -c c6e77b96-32d7-4290-9af7-d95ca5f49dd6 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702201949UTC'
> Exit code: 1
> Stdout:
> Stderr:
> Error: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_2022_1.standard1: not found
> Trace ID: 21CAu1rHSGaLM-uAI7H-oA (grep in scylla-manager logs)
> Traceback (most recent call last):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1125, in run
> res = self.manager_node.remoter.sudo(f"sctool {cmd}")
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
> return self.run(cmd=cmd,
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
> result = _run()
> File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
> return func(*args, **kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
> return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
> result = connection.run(**command_kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
> return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
> raise UnexpectedExit(result)
> sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
> Command: 'sudo sctool restore -c c6e77b96-32d7-4290-9af7-d95ca5f49dd6 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702201949UTC'
> Exit code: 1
> Stdout:
> Stderr:
> Error: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_2022_1.standard1: not found
> Trace ID: 21CAu1rHSGaLM-uAI7H-oA (grep in scylla-manager logs)
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5094, in wrapper
> result = method(*args[1:], **kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2827, in disrupt_mgmt_restore
> restore_task = mgr_cluster.create_restore_task(restore_data=True,
> File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 544, in create_restore_task
> res = self.sctool.run(cmd=cmd, parse_table_res=False)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1128, in run
> raise ScyllaManagerError(f"Encountered an error on sctool command: {cmd}: {ex}") from ex
> sdcm.mgmt.common.ScyllaManagerError: Encountered an error on sctool command: restore -c c6e77b96-32d7-4290-9af7-d95ca5f49dd6 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702201949UTC: Encountered a bad command exit code!
> Command: 'sudo sctool restore -c c6e77b96-32d7-4290-9af7-d95ca5f49dd6 --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702201949UTC'
> Exit code: 1
> Stdout:
> Stderr:
> Error: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_2022_1.standard1: not found
> Trace ID: 21CAu1rHSGaLM-uAI7H-oA (grep in scylla-manager logs)
> ```

@bhalevy - my team just got ownership of Manager, we are still getting familiar with the tests. Currently we are in a middle of a sprint and can't take this task until other more urgent tasks are resolved. I am well aware of this issue and will plan fixing it in the next sprints. Please bear with us as the team is smaller than it should be and we are in a process of recruiting.

**Comment by bhalevy** [comment]
Hi @rayakurl what's the status of this issue?
It's really hampering SCT for 2024.1

**Comment by mykaul** [comment]
We have an issue with schema restore in 5.4 (with Raft enabled!) - unsure if it's the same or an entirely different issue.
If it's the flow of restoring Enterprise to OSS - this is not a supported flow (The other way around is, btw)

**Comment by roydahan** [comment]
I suggest that we will disable this nemesis until there is a fix for it.
Meanwhile, he team releasing manager should be aware that it's being less tested during regular longevities.

**Comment by rayakurl** [comment]
@roydahan what is the frequency if this issue? I've seen a passed run.

**Comment by fruch** [comment]
> @roydahan what is the frequency if this issue? I've seen a passed run.

https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/ace548b0-9f58-11ee-bf28-5927cc3d3ce3

~50% failure for this nemesis, across all current running releases

**Comment by dkropachev** [comment]
Update on findings:
`MgmtRestore` was run twice, it did restore schema in both cases, but second time table was not found by some reason: 
```
< t:2023-12-05 16:37:03,509 f:cli.py          l:1123 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool restore -c 93ba659b-e277-4685-adad-ab71bca84afd --restore-schema --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC'
< t:2023-12-05 16:49:55,418 f:cli.py          l:1123 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool restore -c 93ba659b-e277-4685-adad-ab71bca84afd --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC'
< t:2023-12-05 19:00:26,940 f:cli.py          l:1123 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool restore -c 93ba659b-e277-4685-adad-ab71bca84afd --restore-schema --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC'
< t:2023-12-05 19:13:15,834 f:cli.py          l:1123 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool restore -c 93ba659b-e277-4685-adad-ab71bca84afd --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC'
< t:2023-12-05 19:13:40,035 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo sctool restore -c 93ba659b-e277-4685-adad-ab71bca84afd --restore-tables --location s3:manager-backup-tests-permanent-snapshots-us-east-1  --snapshot-tag sm_20230702190638UTC"; Exit status: 1
< t:2023-12-05 19:13:40,035 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: Error: get resource: create restore target, units and views: init units: get tombstone_gc of 5gb_sizetiered_5_2.standard1: not found
< t:2023-12-05 19:13:40,035 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Trace ID: QYWs1GiDSHSVoQJXltp5ww (grep in scylla-manager logs)
< t:2023-12-05 19:13:40,035 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-12-05 19:13:40,035 f:base.py         l:325  c:sdcm.sct_events.base p:WARNING > [SCT internal warning] (InfoEvent Severity.WARNING) period_type=not-set event_id=54218104-46ee-45b9-bcc7-13b852133
```

So, there should be some reason on why cluster did not pick up table from the schema

**Comment by dkropachev** [comment]
Ok, so, it is expected behavior from scylla side, since `s-m` restoring schema via uploading schema `sstables`, what is effectively happening is that schema not getting restored on second restore since `DROP KEYSPACE` have higher timestamp than schema in sstables `s-m` upload to the nodes.

This is regresion after https://github.com/scylladb/scylla-cluster-tests/pull/6791, which should be reverted.

**Comment by fruch** [comment]
> Ok, so, it is expected behavior from scylla side, since `s-m` restoring schema via uploading schema `sstables`, what is effectively happening is that schema not getting restored on second restore since `DROP KEYSPACE` have higher timestamp than schema in sstables `s-m` upload to the nodes.
> 
> This is regresion after https://github.com/scylladb/scylla-cluster-tests/pull/6791, which should be reverted. 

So if I dropped the keyspace, and now I need the backup cause I've lost all data, restore won't work ?

**Comment by rayakurl** [comment]
> Ok, so, it is expected behavior from scylla side, since `s-m` restoring schema via uploading schema `sstables`, what is effectively happening is that schema not getting restored on second restore since `DROP KEYSPACE` have higher timestamp than schema in sstables `s-m` upload to the nodes.

@karol-kokoszka , @Michal-Leszczynski - can you please comment?

**Comment by dkropachev** [comment]
@fruch, It is `feature`, take a look at [docs](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html).
We have never supported restoring to an non-empty cluster.

But quality wise, I `100%` with you, we need to make it work, we need to make it work easy and without any hastels on cluster side.
Let's have [issue](https://github.com/scylladb/scylla-manager/issues/3677) on `s-m` side, when it is fixed, make test do it, while reverting test back to old behavior.

**Comment by fruch** [comment]
> @fruch, It is `feature`, take a look at [docs](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html).
> We have never supported restoring to an non-empty cluster.
> 

Those are not scylla manger docs, it's explains how to use CQL based schema.
And says nothing about drop or not the keyspace, and manger docs doesn't explain it either.


> But quality wise, I `100%` with you, we need to make it work, we need to make it work easy and without any hastels on cluster side.
> Let's have [issue](https://github.com/scylladb/scylla-manager/issues/3677) on `s-m` side, when it is fixed, make test do it, while reverting test back to old behavior for now.
> 

Once it's acknowledged and at least mentioned in docs, we'll update and backport

I can't guarantee that other nemesis might not change the table or keyspace in a duration of a longevity.

**Comment by roydahan** [comment]
@rayakurl / @tzach please handle this and get back to us.
We need to know if it's a known limitation that is documented somewhere for manager to not be able to restore a keyspace that was dropped (isn't it kind of defeating the purpose of restore?)

**Comment by rayakurl** [comment]
> @rayakurl / @tzach please handle this and get back to us. We need to know if it's a known limitation that is documented somewhere for manager to not be able to restore a keyspace that was dropped (isn't it kind of defeating the purpose of restore?)

@tzach we can discuss it during the Manager meeting on Thursday.

**Comment by Michal-Leszczynski** [comment]
> Once it's acknowledged and at least mentioned in docs, we'll update and backport

This is mentioned in SM [docs](https://manager.docs.scylladb.com/stable/restore/restore-schema.html#prerequisites) here:
```
It is strongly advised to restore schema only into an empty cluster with no schema change history of the keyspace that is going to be restored.
Otherwise, the restored schema might be overwritten by the already existing one and cause unexpected errors.
```

In case it's too confusing, we can change it to something more comprehensible.

The requirement of restoring schema into fresh cluster has been there from the beginning and currently there is no way around it. There is an effort to make `DESC SCHEMA` safe for restore purposes ([issue](https://github.com/scylladb/scylladb/issues/16482)), but even then I'm not sure if it's going to work correctly on a cluster with conflicting schema history - it might depend on the implementation itself.

**Comment by fruch** [comment]
> > Once it's acknowledged and at least mentioned in docs, we'll update and backport
> 
> This is mentioned in SM [docs](https://manager.docs.scylladb.com/stable/restore/restore-schema.html#prerequisites) here:
> 
> ```
> It is strongly advised to restore schema only into an empty cluster with no schema change history of the keyspace that is going to be restored.
> Otherwise, the restored schema might be overwritten by the already existing one and cause unexpected errors.
> ```
> 
> In case it's too confusing, we can change it to something more comprehensible.
> 
> The requirement of restoring schema into fresh cluster has been there from the beginning and currently there is no way around it. There is an effort to make `DESC SCHEMA` safe for restore purposes ([issue](https://github.com/scylladb/scylladb/issues/16482)), but even then I'm not sure if it's going to work correctly on a cluster with conflicting schema history - it might depend on the implementation itself.

so basically the restore should happen only once per keyspace inside a test ?

**Comment by Michal-Leszczynski** [comment]
> so basically the restore should happen only once per keyspace inside a test ?

Yes, that's how we test restore schema in SM repo without recreating the cluster for each test.

**Comment by roydahan** [comment]
I don't think the "fix" solves all the issues that were unified into this one.
