### ISSUE TITLE
Consider using capacity reservation

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#6852]
In order to overcome "Insufficient Capacity" in several places, espcially where we try to use placement groups, we can try using "capacity reservation" - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/capacity-reservations-using.html#capacity-reservations-create

**Comment by roydahan** [comment]
We should try to use it in 2 places:
1. pre-step for provision - try to have capacity reservation for db-instances, loaders and monitor.
if all succeed, we can use that AZ, if not, we can fallback to next AZ.


2. For performance test, the same with placement groups.

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/7289

**Comment by fruch** [comment]
we have some fallouts from this one, @soyacz is working on fixes

**Comment by soyacz** [comment]
I think this one can be closed
