### ISSUE TITLE
LargePartitionLongevityTest.SetUp fails with exception='NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cluster-tests#6893]
Seen in e.g. https://argus.scylladb.com/test/552a7c26-be98-44b6-b3bc-31abf53d9669/runs?additionalRuns[]=753fc3c1-5f32-4c4e-9b5f-91c732a7e987

sct-753fc3c1.log:
```
< t:2023-12-03 18:13:54,198 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-12-03 18:13:54.196: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=d32f5c15-6ec6-4340-81c5-643730037bdc, source=LargePartitionLongevityTest.SetUp()
< t:2023-12-03 18:13:54,198 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception='NoneType' object has no attribute 'get'
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 166, in wrapper
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 854, in setUp
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1763, in init_resources
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1253, in get_cluster_aws
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     init_db_info_from_params(db_info, params=self.params, regions=regions)
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 250, in init_db_info_from_params
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     root_device = root_device if root_device else ec2_ami_get_root_device_name(
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 359, in ec2_ami_get_root_device_name
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     if image.root_device_name:
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 386, in property_loader
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR >     return self.meta.data.get(name)
< t:2023-12-03 18:13:54,196 f:tester.py       l:173  c:sdcm.tester          p:ERROR > AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bhalevy** [comment]
Cc @roydahan @fruch @yarongilor

**Comment by fruch** [comment]
@yaronkaikov @Annamikhlin

the AMIs for 2024.1.0-rc1 are not exposed to other accounts, and we can't see some of their attributes, in compersented to 5.4 AMIs that we can.

**Comment by yaronkaikov** [comment]
@fruch i guess you meant @yarongilor

**Comment by fruch** [comment]
no I meant you

**Comment by fruch** [comment]
see this snippt
```
from sdcm.utils.common import get_scylla_ami_versions
from sdcm.utils.aws_utils import  ec2_ami_get_root_device_name

ami = get_scylla_ami_versions(region_name='eu-west-1', arch='x86_64', version='2024.1.0-rc1')
print(ami[0].id)
print(ami[0].name)
print(ami[0].root_device_name)
print(ec2_ami_get_root_device_name(ami[0].id, 'eu-west-1'))
```

and the output:
```
ami-0c523a19a0c19949c
ScyllaDB Enterprise 2024.1.0-rc1
/dev/sda1
Traceback (most recent call last):
  File "/home/fruch/projects/scylla-cluster-tests/ass.py", line 8, in <module>
    print(ec2_ami_get_root_device_name(ami[0].id, 'eu-west-1'))
  File "/home/fruch/projects/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 359, in ec2_ami_get_root_device_name
    if image.root_device_name:
  File "/home/fruch/.pyenv/versions/scylla-cluster-tests-3.10.5/lib/python3.10/site-packages/boto3/resources/factory.py", line 386, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by fruch** [comment]
@yaronkaikov something is broken with making this image public

**Comment by yaronkaikov** [comment]
@fruch nothing is wrong we don't make rc public

**Comment by yaronkaikov** [comment]
So if you looking for public images you will not find it

**Comment by fruch** [comment]
> > So if you looking for public images you will not find it
> 
> master images are, and 5.4 rc are... why this one is different ?

i.e. we tested with public images, so far, we never tested with private ones like, it wasn't part of the work done for https://github.com/scylladb/scylla-pkg/issues/3312

**Comment by roydahan** [comment]
We decided to make them public again.

**Comment by fruch** [comment]
So I guess we can close this issue, or we still want to support private ones in SCT ?

**Comment by bhalevy** [comment]
> So I guess we can close this issue, or we still want to support private ones in SCT ?

It would be best if we can support also private images.
These could potentially be private builds for certain customers

**Comment by roydahan** [comment]
> > So I guess we can close this issue, or we still want to support private ones in SCT ?
> 
> It would be best if we can support also private images. These could potentially be private builds for certain customers

It's not relevant for private builds, only to official builds that SCT can detect by official "scylla_version".
Any private build or any private AMI still works, but need to mention it by ami-id.

**Comment by fruch** [comment]
> > > So I guess we can close this issue, or we still want to support private ones in SCT ?
> > 
> > It would be best if we can support also private images. These could potentially be private builds for certain customers
> 
> It's not relevant for private builds, only to official builds that SCT can detect by official "scylla_version".
> Any private build or any private AMI still works, but need to mention it by ami-id.

If an AMI is not public, SCT would fail to run it, even if you specify it with its AMI id

If it were working, there wasn't an issue

The lookup code does know to work with the new images account, 

But we never talked about non public AMI, hence no one tested it.

**Comment by Annamikhlin** [comment]
> > > > So I guess we can close this issue, or we still want to support private ones in SCT ?
> > > 
> > > 
> > > It would be best if we can support also private images. These could potentially be private builds for certain customers
> > 
> > 
> > It's not relevant for private builds, only to official builds that SCT can detect by official "scylla_version".
> > Any private build or any private AMI still works, but need to mention it by ami-id.
> 
> If an AMI is not public, SCT would fail to run it, even if you specify it with its AMI id
> 
> If it were working, there wasn't an issue
> 
> The lookup code does know to work with the new images account,
> 
> But we never talked about non public AMI, hence no one tested it.

@fruch - according to the PR it was approved by Fabio
https://github.com/scylladb/scylla-pkg/pull/3387#issuecomment-1528961317

Let's bring him back to fix it ;)

**Comment by fruch** [comment]
> > > > > So I guess we can close this issue, or we still want to support private ones in SCT ?
> > > > 
> > > > 
> > > > It would be best if we can support also private images. These could potentially be private builds for certain customers
> > > 
> > > 
> > > It's not relevant for private builds, only to official builds that SCT can detect by official "scylla_version".
> > > Any private build or any private AMI still works, but need to mention it by ami-id.
> > 
> > If an AMI is not public, SCT would fail to run it, even if you specify it with its AMI id
> > 
> > If it were working, there wasn't an issue
> > 
> > The lookup code does know to work with the new images account,
> > 
> > But we never talked about non public AMI, hence no one tested it.
> 
> @fruch - according to the PR it was approved by Fabio
> https://github.com/scylladb/scylla-pkg/pull/3387#issuecomment-1528961317
> 
> Let's bring him back to fix it ;)

Anyone can handle/test these new requirements, if it's agreed those are the requirements.

All they need is one non public image
