### ISSUE TITLE
Endofquota nemesis fails to configure quota on non aws backends

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylla-cluster-tests#6915]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

@fruch Noticed that the endofquota nemesis fails on jobs which run on GCE and Azure back-ends.
Decided to skip the nemesis for the meantime.
Need to follow up with a task to test on a GCE live cluster with Jupiter.

```
2023-12-06 13:03:35.191: (DisruptionEvent Severity.ERROR) period_type=end event_id=0d6b5000-d2b4-42b4-a50a-5451d1192dd6 duration=3m25s: nemesis_name=EndOfQuotaNemesis target_node=Node longevity-large-partitions-200k-pks-db-node-a9240d39-0-4 [34.139.152.45 | 10.142.0.143] (seed: True) errors=Failed to configure quota on the cluster
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5048, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1714, in disrupt_end_of_quota_nemesis
raise QuotaConfigurationFailure("Failed to configure quota on the cluster")
sdcm.exceptions.QuotaConfigurationFailure: Failed to configure quota on the cluster
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1047-gcp
Scylla version (or git commit hash): `5.5.0~dev-20231205.4505a86f46df` with build-id `2355da584169ed4dedccb225347f30c5896efe06`

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-7 (35.229.27.248 | 10.142.0.72) (shards: -1)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-6 (34.139.9.181 | 10.142.0.7) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-5 (34.139.95.184 | 10.142.0.146) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-4 (34.139.152.45 | 10.142.0.143) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-3 (35.229.47.121 | 10.142.0.142) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-2 (34.75.112.71 | 10.142.0.141) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-a9240d39-0-1 (34.138.160.153 | 10.142.0.139) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-5-5-0-dev-x86-64-2023-12-05t09-16-23` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `a9240d39-6069-4a53-9e87-07f068c2afff`
Test name: `scylla-staging/fruch/longevity-large-partition-200k-pks-4days-gce-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/69b9893f1cba4b7180aab04e7f906a7fdc58b679/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a9240d39-6069-4a53-9e87-07f068c2afff`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a9240d39-6069-4a53-9e87-07f068c2afff)
- Show all stored logs command: `$ hydra investigate show-logs a9240d39-6069-4a53-9e87-07f068c2afff`

## Logs:
- **db-cluster-a9240d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/db-cluster-a9240d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/db-cluster-a9240d39.tar.gz)
- **sct-runner-events-a9240d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/sct-runner-events-a9240d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/sct-runner-events-a9240d39.tar.gz)
- **sct-a9240d39.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/sct-a9240d39.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/sct-a9240d39.log.tar.gz)
- **loader-set-a9240d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/loader-set-a9240d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/loader-set-a9240d39.tar.gz)
- **monitor-set-a9240d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/monitor-set-a9240d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a9240d39-6069-4a53-9e87-07f068c2afff/20231206_155954/monitor-set-a9240d39.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-large-partition-200k-pks-4days-gce-test/5/)
[Argus](https://argus.scylladb.com/test/7539b0e9-7dfd-4ad7-ab9d-a4cde2807077/runs?additionalRuns[]=a9240d39-6069-4a53-9e87-07f068c2afff)
</details>

**Comment by Mark-Gurevich** [comment]
Updated the description with a template from Argus.
I was under the impression that it was exclusively for Scylla issues and not for SCT.

**Comment by fruch** [comment]
@Mark-Gurevich 
I've put it on the QA board, please see you schedule it (with @bhalevy I'm guessing)

**Comment by roydahan** [comment]
I still don't understand how the quota configuration is related to the backend.

**Comment by fruch** [comment]
> I still don't understand how the quota configuration is related to the backend.
> 

I guess it might have an assumption on disk names, or something similar that was overseen (and wasn't tested)

**Comment by vponomaryov** [comment]
> I still don't understand how the quota configuration is related to the backend.

I think it is related to the implementation. Which must be different for each of the backends.
It works where it was developed and only on instance types with single SSD: https://github.com/scylladb/scylla-cluster-tests/issues/6936

**Comment by Mark-Gurevich** [comment]
> > I still don't understand how the quota configuration is related to the backend.
> 
> @roydahan I think it is related to the implementation. Which must be different for each of the backends. It works where it was developed and only on instance types with single SSD:
> 
> * [`end_of_quota_nemesis` nemesis fails incorrectly parsing the `mount` command #6936](https://github.com/scylladb/scylla-cluster-tests/issues/6936)

Exactly.
