### ISSUE TITLE
ScyllaBenchEvent was stopped due to tear down, but raised CRITICAL event, not WARNING

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6927]
ScyllaBenchEvent was stopped due to tear down, but raised CRITICAL event, not WARNING
```
&lt; t:2023-12-07 12:15:10,082 f:tester.py       l:2800 c:LongevityTest        p:INFO  &gt; TearDown is starting...
&lt; t:2023-12-07 12:15:31,963 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  &gt; 2023-12-07 12:15:31.960: (ScyllaBenchEvent Severity.CRITICAL) period_type=end event_id=3f3a89c7-f568-42f4-b170-10add3d726b0 during_nemesis=DecommissionStreamingErr,CreateIndex duration=2h46m15s: node=Node longevity-parallel-topology-schema--loader-node-b4619490-1 [34.201.28.197 | 10.12.1.229] (seed: False)
``` 

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1050-aws
Scylla version (or git commit hash): `2023.1.3-20231204.e79ea9835df7` with build-id `e210e1f13f58542da05a9f2aca55ee89de1d1d64`

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-b4619490-9 (35.172.234.59 | 10.12.2.211) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-8 (54.208.139.18 | 10.12.3.199) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-7 (3.218.151.58 | 10.12.2.241) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-6 (3.239.35.69 | 10.12.1.54) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-5 (44.205.14.165 | 10.12.1.222) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-4 (44.213.133.90 | 10.12.1.151) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-3 (18.204.44.185 | 10.12.2.162) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-2 (3.215.185.7 | 10.12.0.16) (shards: 7)
- longevity-parallel-topology-schema--db-node-b4619490-10 (44.198.61.225 | 10.12.1.134) (shards: -1)
- longevity-parallel-topology-schema--db-node-b4619490-1 (3.239.108.132 | 10.12.2.1) (shards: 7)

OS / Image: `ami-03d838f35dcf5a090` (aws: us-east-1)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `b4619490-d05a-4a2d-ba66-2fa62895e00a`
Test name: `enterprise-2023.1/longevity/longevity-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1eb9a52e9b702b8bfacb993d47d829ca579cdd64/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b4619490-d05a-4a2d-ba66-2fa62895e00a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b4619490-d05a-4a2d-ba66-2fa62895e00a)
- Show all stored logs command: `$ hydra investigate show-logs b4619490-d05a-4a2d-ba66-2fa62895e00a`

## Logs:
- **db-cluster-b4619490.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/db-cluster-b4619490.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/db-cluster-b4619490.tar.gz)
- **sct-runner-events-b4619490.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/sct-runner-events-b4619490.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/sct-runner-events-b4619490.tar.gz)
- **sct-b4619490.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/sct-b4619490.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/sct-b4619490.log.tar.gz)
- **monitor-set-b4619490.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/monitor-set-b4619490.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/monitor-set-b4619490.tar.gz)
- **loader-set-b4619490.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/loader-set-b4619490.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b4619490-d05a-4a2d-ba66-2fa62895e00a/20231207_130836/loader-set-b4619490.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-schema-topology-changes-12h-test/7/)
[Argus](https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=b4619490-d05a-4a2d-ba66-2fa62895e00a)
</details>

**Comment by fruch** [comment]
this is the fix for it on master:
https://github.com/scylladb/scylla-cluster-tests/pull/6442

we never backported it to 2023.1 (and we'll get once we'll refresh that branch)

**Comment by fruch** [comment]
branch-2023.1 got this fix
