### ISSUE TITLE
`install_package` method times out on dockerized Scylla

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6929]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

After the merge of the following commit:
- https://github.com/scylladb/scylla-cluster-tests/pull/6810/commits/eec63067c14016ac60d59f5ffdbdfded65da5262 (https://github.com/scylladb/scylla-cluster-tests/pull/6810/)

The K8S jobs started having a lot of the following errors in logs:

```
09:08:23  < t:2023-12-10 07:08:16,396 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:08:23  < t:2023-12-10 07:08:16,396 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c5874f190 state=finished returned bool>)
09:08:23  < t:2023-12-10 07:08:17,289 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (1/3) nodes ready, node Node sct-cluster-eu-north-1-rack-1-0 [10.0.2.240 | 10.0.2.42] (seed: False). Time elapsed: 61 s
09:09:24  < t:2023-12-10 07:09:17,568 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:09:24  < t:2023-12-10 07:09:17,569 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c5874eef0 state=finished returned bool>)
09:09:24  < t:2023-12-10 07:09:18,465 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (2/3) nodes ready, node Node sct-cluster-eu-north-1-rack-1-1 [10.0.3.172 | 10.0.2.107] (seed: False). Time elapsed: 61 s
09:10:22  < t:2023-12-10 07:10:18,723 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:10:22  < t:2023-12-10 07:10:18,724 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c6bddf400 state=finished returned bool>)
09:10:22  < t:2023-12-10 07:10:19,615 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (3/3) nodes ready, node Node sct-cluster-eu-north-1-rack-1-2 [10.0.0.24 | 10.0.0.233] (seed: False). Time elapsed: 61 s
09:11:31  < t:2023-12-10 07:11:24,166 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:11:31  < t:2023-12-10 07:11:24,166 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c406461d0 state=finished returned bool>)
09:11:31  < t:2023-12-10 07:11:25,070 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (1/3) nodes ready, node Node sct-cluster-eu-north-1-rack-1-0 [10.0.2.240 | 10.0.2.42] (seed: False). Time elapsed: 61 s
09:12:28  < t:2023-12-10 07:12:25,263 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:12:28  < t:2023-12-10 07:12:25,263 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c406a7e20 state=finished returned bool>)
09:12:28  < t:2023-12-10 07:12:26,183 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (2/3) nodes ready, node Node sct-cluster-eu-north-1-rack-1-1 [10.0.3.172 | 10.0.2.107] (seed: False). Time elapsed: 61 s
09:13:37  < t:2023-12-10 07:13:26,463 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: Checking if package manager is free: timeout - 60 seconds - expired
09:13:37  < t:2023-12-10 07:13:26,463 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7f0c40662fb0 state=finished returned bool>)
09:13:37  < t:2023-12-10 07:13:27,361 f:cluster.py      l:3688 c:sdcm.cluster         p:INFO  > EksScyllaPodCluster functional-master-db-cluster-8e282023 | Namespace: scylla: (3/3) 
```

It is caused by the fact that the `install_scylla_debuginfo` method started retrying failures instead of `try-and-go` approach.
The `install_scylla_debuginfo` method has always been failing on K8S due to the known restriction:
- https://github.com/scylladb/scylla-cluster-tests/issues/6214

## Impact

A lot of the time is wasted leading to the job timeouts.

## How frequently does it reproduce?

100%

## Installation details

Kernel Version: 5.10.199-190.747.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-144-g60f7824
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `functional-eks`
Test id: `8e282023-52e3-4237-ad65-e6307e23cc59`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3d32370733caa48cfe5af0014e1a1b1bb3a48a37/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8e282023-52e3-4237-ad65-e6307e23cc59`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8e282023-52e3-4237-ad65-e6307e23cc59)
- Show all stored logs command: `$ hydra investigate show-logs 8e282023-52e3-4237-ad65-e6307e23cc59`

## Logs:
- **kubernetes-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/kubernetes-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/kubernetes-8e282023.tar.gz)
- **kubernetes-must-gather-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/kubernetes-must-gather-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/kubernetes-must-gather-8e282023.tar.gz)
- **db-cluster-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/db-cluster-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/db-cluster-8e282023.tar.gz)
- **sct-runner-events-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/sct-runner-events-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/sct-runner-events-8e282023.tar.gz)
- **sct-8e282023.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/sct-8e282023.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/sct-8e282023.log.tar.gz)
- **loader-set-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/loader-set-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/loader-set-8e282023.tar.gz)
- **parallel-timelines-report-8e282023.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/parallel-timelines-report-8e282023.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8e282023-52e3-4237-ad65-e6307e23cc59/20231210_122714/parallel-timelines-report-8e282023.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/140/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=8e282023-52e3-4237-ad65-e6307e23cc59)
</details>

**Comment by mykaul** [comment]
Out of curiosity, what are we installing, in runtime, in our containers? We probably shouldn't be doing that in K8S.

**Comment by fruch** [comment]
> Out of curiosity, what are we installing, in runtime, in our containers? We probably shouldn't be doing that in K8S.

Trying to install the debug symbol, and failing
