### ISSUE TITLE
Update Oracle version

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6933]
Currently, it's a bit outdated - see https://github.com/search?q=repo%3Ascylladb%2Fscylla-cluster-tests+%22oracle_scylla_version%3A+%5C%22%22&type=code

Even Gemini itself is already using 5.2.2 in its CI.
Please update to latest 5.2.x

**Comment by fruch** [comment]
one more place, we need the information which release is valid and which not. and which isn't supported anymore.

**Comment by roydahan** [comment]
2021.1.15 is considered as good and very tested release.
We would like to keep comparing it for correctness and move it forward ONLY when we have correctness issues that were fixed and weren't backported to this release (which I'm not aware of such at the moment).

**Comment by bhalevy** [comment]
> 2021.1.15 is considered as good and very tested release. We would like to keep comparing it for correctness and move it forward ONLY when we have correctness issues that were fixed and weren't backported to this release (which I'm not aware of such at the moment).

https://github.com/scylladb/scylla-enterprise/commit/9ccb74c049669832b713a8dc8e0c1c9888ffbbd1 for example is only available since 2021.1.22 (in the 2021.1 linage)

**Comment by roydahan** [comment]
Please allow me to rephrase my previous comment.
We **should and will** progress on branch 2021.1 patch releases but not move to newer branches for now as the original comment is asking (branch-5.2).

Unless (again), we know of correctness issues that were not fixed in this enterprise release.
