### ISSUE TITLE
Add a Readme Page for test parameters used in test executions in Jenkins and description for the parameters in all pipelines

### ISSUE THREAD

**Issue by Mark-Gurevich** [scylladb/scylla-cluster-tests#6977]
Any new employee or engineer from Dev should be able easily run any test from the SCT repo.
We need to have a place to look for parameters format and links to places where you can take these parameters such as:
scylla_repo
scylla_version
scylla_ami_id
gce_image_db
azure_image_db
update_db_packages
availability_zone
and all others....

We need to see in Jenkins and in readme the correct format for the param or for multiple values.
In some cases you should enter the params using "," and others require to use the ["a","b"] format.
This should be easily understood from the Readme page and in the Jenkins description of the parameter without digging into the SCT code.
**It should be also clear which parameters are a must and which are optional.**

**Comment by roydahan** [comment]
We accept PRs, although we don't maintain Jenkins in SCT.
Each parameter has a description in Jenkins and in sct_config.
