### ISSUE TITLE
SCT grafana dashboard doesn't show per-instance load anymore

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#7014]
### Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

![Screenshot from 2023-12-26 16-34-22](https://github.com/scylladb/scylla-cluster-tests/assets/3796058/944f6321-4801-452b-bc14-edde7e3fb827)

#### Steps to Reproduce

1. Deploy SCT monitoring using `master` branch
2. Open SCT grafana dashboard
3. Try to look at the per-instance load
4. See that it is absent

**Expected behavior:** per-instance load must be shown

**Actual behavior:** per-instance load is not shown in the SCT grafana dashboard

### How frequently does it reproduce?

100%

### Installation details

SCT Version: master
Scylla version (or git commit hash): Any

### Logs
* test_id: `01fd8526-1ace-4bfd-9cc3-c8d46eed8244`
* job log: [Argus](https://argus.scylladb.com/test/e785a08d-eedf-4ec9-8c6a-eb6939e28759/runs?additionalRuns%5B%5D=01fd8526-1ace-4bfd-9cc3-c8d46eed8244), [CI](https://jenkins.scylladb.com/job/enterprise-2024.1/job/gemini-/job/gemini-8h-large-num-columns-test/2)

**Comment by fruch** [comment]
seems like a regression we didn't notices with monitor 4.6

I've addressed it in this PR:
https://github.com/scylladb/scylla-cluster-tests/pull/7007

and the rest of the dashboards are fixed in monitoring itself.

meanwhile you can manually edit the dashboard parameters, like in #7007:

from:
'Cluster,DC,Instance,Shard' to `Instance : instance,Cluster : cluster,DC : dc,Shard : instance\,shard`

**Comment by vponomaryov** [comment]
@fruch 
Need to change `"value_type": "cumulative"` to "value_type": "individual" in panes configuration where we expect per-instance info

**Comment by fruch** [comment]
> @fruch Need to change `"value_type": "cumulative"` to `"value_type": "individual"` in panels configuration where we expect per-instance info.

I don't think so, the query itself take care of that

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/7007 addressed it
