### ISSUE TITLE
After restore keyspace 100gb_sizetiered_5_2 become doubleqotted 

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#7031]
### Issue description

After `MgmtRestore` keyspace `100gb_sizetiered_5_2` become doublequotted:
```
< t:2023-11-09 00:57:48,835 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/cqlsh --no-color -u cassandra -p 'cassandra'  --request-timeout=120 --connect-timeout=60 --ssl -e "describe keyspaces" 10.4.8.224 9042"...
< t:2023-11-09 00:57:48,891 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Nov 09 00:57:48 longevity-200gb-48h-verify-limited--monitor-node-bb19dae3-1 scylla-manager[32565]: {"L":"INFO","T":"2023-11-09T00:57:48.573Z","N":"http","M":"GET /api/v1/version","from":"127.0.0.1:41982","status":200,"bytes":40,"duration":"0ms","_trace_id":"eGL1wejQRii4l_yIGjZVNw"}
< t:2023-11-09 00:57:48,892 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Nov 09 00:57:48 longevity-200gb-48h-verify-limited--monitor-node-bb19dae3-1 scylla-manager[32565]: {"L":"INFO","T":"2023-11-09T00:57:48.710Z","N":"http","M":"GET /api/v1/clusters","from":"127.0.0.1:41994","status":200,"bytes":209,"duration":"9ms","_trace_id":"CPtm6UIWS5a0EKYrFUhH-A"}
< t:2023-11-09 00:57:49,897 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-09 00:57:50,099 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-09 00:57:50,099 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Warning: Using a password on the command line interface can be insecure.
< t:2023-11-09 00:57:50,099 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > system_auth    system_distributed      ks_truncate                  
< t:2023-11-09 00:57:50,104 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Recommendation: use the credentials file to securely provide the password.
< t:2023-11-09 00:57:50,119 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > system_schema  system                  system_distributed_everywhere
< t:2023-11-09 00:57:50,125 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-09 00:57:50,125 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > keyspace1      system_traces         
< t:2023-11-09 00:57:50,125 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > lowload1       "100gb_sizetiered_5_2"
< t:2023-11-09 00:57:50,130 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-09 00:57:50,656 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: 
< t:2023-11-09 00:57:50,656 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > Warning: Using a password on the command line interface can be insecure.
< t:2023-11-09 00:57:50,656 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > Recommendation: use the credentials file to securely provide the password.
< t:2023-11-09 00:57:50,656 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-09 00:57:50,676 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/cqlsh --no-color -u cassandra -p 'cassandra'  --request-timeout=120 --connect-timeout=60 --ssl -e "describe keyspaces" 10.4.8.224 9042" finished with status 0
```

OS / Image: `ami-0b21c9ee6a0c5cbdc` (aws: undefined_region)

Test: `longevity-200gb-48h-arm-test`
Test id: `bb19dae3-1e8a-4564-a78e-6911b4260c63`
Test name: `scylla-5.4/longevity/longevity-200gb-48h-arm-test`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/86e790b8fc04e31fae746e411198fe365b2766ae/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor bb19dae3-1e8a-4564-a78e-6911b4260c63`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bb19dae3-1e8a-4564-a78e-6911b4260c63)
- Show all stored logs command: `$ hydra investigate show-logs bb19dae3-1e8a-4564-a78e-6911b4260c63`

## Logs:
- **db-cluster-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/db-cluster-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/db-cluster-bb19dae3.tar.gz)
- **sct-runner-events-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-runner-events-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-runner-events-bb19dae3.tar.gz)
- **sct-bb19dae3.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-bb19dae3.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/sct-bb19dae3.log.tar.gz)
- **loader-set-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/loader-set-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/loader-set-bb19dae3.tar.gz)
- **monitor-set-bb19dae3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/monitor-set-bb19dae3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bb19dae3-1e8a-4564-a78e-6911b4260c63/20231109_171230/monitor-set-bb19dae3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-200gb-48h-arm-test/3/)
[Argus](https://argus.scylladb.com/test/d7570ae6-3f9d-4cf4-ab4e-389cd1be27b9/runs?additionalRuns[]=bb19dae3-1e8a-4564-a78e-6911b4260c63)
</details>

**Comment by fruch** [comment]
It's by CQL spec

Cause it starts with a number, it's nothing to do with SCT

**Comment by fruch** [comment]
not a bug
