### ISSUE TITLE
hydra doesn't work with podman (Fedora 39) - [workaround? use Docker]

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#7037]
```
[ykaul@ykaul scylla-cluster-tests]$ docker/env/hydra.sh --help
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
There is scylladb/hydra:v1.53-cryptography-41.0.6-update in local cache, using it.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Going to run './sct.py --help '...
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] Using the Podman API service with TCP sockets is not recommended, please see `podman system service` manpage for details
Error: crun: chown `/dev/pts/1`: Operation not permitted: OCI permission denied
```

I think it'd be great if we could support Podman - I see no reason we'd need root for this - perhaps I'm missing the reason.

**Comment by fruch** [comment]
looks like podman doesn't like mounting the /dev/ folder into a rootless container
we need for some specific cases to run local k8s, and using loopback devices
we can make it work on docker

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/7038 might solve the issue
if someone would be able to take it, and give feedback (i.e. on my laptop it's working)

**Comment by mykaul** [comment]
I could not get it to work (podman on F40 beta). I ended up uninstalling podman, using docker (but then S3 creds did not work, as I had to sudo everything :-/ )
We need to get it to work. I'll re-install Podman, reproduce and open a new issue.
