### ISSUE TITLE
disrupt_end_of_quota_nemesis fails with message "Failed to configure quota on the cluster"

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#7062]
## Issue description

disrupt_end_of_quota_nemesis fails with error 
raise QuotaConfigurationFailure("Failed to configure quota on the cluster")
without any additional information,

looks like it is connected with the issue https://github.com/scylladb/scylladb/issues/15908 and PR https://github.com/scylladb/scylla-cluster-tests/pull/6616

## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `5.5.0~dev-20231227.331d9ce788e2` with build-id `5a3ba5068a1b94097fb0f3fab64cdb912cff2911`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-c08ea734-7 (3.255.97.32 | 10.4.9.206) (shards: -1)
- longevity-twcs-48h-master-db-node-c08ea734-6 (18.201.240.8 | 10.4.9.136) (shards: -1)
- longevity-twcs-48h-master-db-node-c08ea734-5 (3.249.43.20 | 10.4.10.177) (shards: -1)
- longevity-twcs-48h-master-db-node-c08ea734-4 (18.201.157.158 | 10.4.10.227) (shards: 7)
- longevity-twcs-48h-master-db-node-c08ea734-3 (18.203.255.93 | 10.4.9.249) (shards: 7)
- longevity-twcs-48h-master-db-node-c08ea734-2 (34.244.211.249 | 10.4.11.72) (shards: 7)
- longevity-twcs-48h-master-db-node-c08ea734-1 (54.217.175.245 | 10.4.11.163) (shards: 7)

OS / Image: `ami-0417c7525e0d98293` (aws: undefined_region)

Test: `longevity-twcs-48h-test`
Test id: `c08ea734-1c32-43b7-b1d5-fec05b22887d`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/53cd2d2662565307007e2de2ce4765a9bf30c831/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c08ea734-1c32-43b7-b1d5-fec05b22887d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c08ea734-1c32-43b7-b1d5-fec05b22887d)
- Show all stored logs command: `$ hydra investigate show-logs c08ea734-1c32-43b7-b1d5-fec05b22887d`

## Logs:
- **db-cluster-c08ea734.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/db-cluster-c08ea734.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/db-cluster-c08ea734.tar.gz)
- **sct-runner-events-c08ea734.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/sct-runner-events-c08ea734.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/sct-runner-events-c08ea734.tar.gz)
- **sct-c08ea734.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/sct-c08ea734.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/sct-c08ea734.log.tar.gz)
- **loader-set-c08ea734.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/loader-set-c08ea734.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/loader-set-c08ea734.tar.gz)
- **monitor-set-c08ea734.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/monitor-set-c08ea734.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c08ea734-1c32-43b7-b1d5-fec05b22887d/20231231_050721/monitor-set-c08ea734.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/101/)
[Argus](https://argus.scylladb.com/test/ca1ac895-78c0-4abd-80d5-0ba6dc7844bf/runs?additionalRuns[]=c08ea734-1c32-43b7-b1d5-fec05b22887d)
</details>

**Comment by fruch** [comment]
I think #6936 mentioned the exact reason for the failure

**Comment by temichus** [comment]
duplicate of https://github.com/scylladb/scylla-cluster-tests/issues/6936
