### ISSUE TITLE
Replace r5b.2xlarge with m7i.2xlarge (for loaders)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#7081]
Assuming memory is not our bottleneck, they are faster and cheaper:

![image](https://github.com/scylladb/scylla-cluster-tests/assets/4655593/724545ed-8caa-4ba3-bfbf-3bede2237554)

**Comment by roydahan** [comment]
We don't use r5b as loaders, we use c5.

**Comment by roydahan** [comment]
> We don't use r5b as loaders, we use c5.

Where did you see it?

**Comment by vponomaryov** [comment]
> > We don't use r5b as loaders, we use c5.
> 
> Where did you see it?

Are you sure you quoted correct message?
Or why are you referring to your own statement and ask question about?

**Comment by fruch** [comment]
we have it on configuration of 3 cases that uses EBS, no particular reason, and those are not being run (cause running ontop of EBS isn't stable), those can be changed if someone would insist.

**Comment by mykaul** [comment]
> we have it on configuration of 3 cases that uses EBS, no particular reason, and those are not being run (cause running ontop of EBS isn't stable), those can be changed if someone would insist.

For reference:
https://github.com/scylladb/scylla-cluster-tests/blob/2bf819cbccdc9f2b857c1117d670fc738d65e968/configurations/ebs/ebs-gp2-2v-4tb.yaml#L1
https://github.com/scylladb/scylla-cluster-tests/blob/2bf819cbccdc9f2b857c1117d670fc738d65e968/configurations/ebs/ebs-gp2-6v-1800gb.yaml#L1
https://github.com/scylladb/scylla-cluster-tests/blob/2bf819cbccdc9f2b857c1117d670fc738d65e968/configurations/ebs/ebs-gp3-2v-4tb-16k-iops.yaml#L1

**Comment by roydahan** [comment]
What @fruch meant is that these tests could be assume as deprecated.
They aren't being executed anymore (more than 1-2 years) since there sere severe issues with them (mostly timeouts killing the stress).
