### ISSUE TITLE
Extend scylla-bench workloads with tablet workloads.

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-cluster-tests#7116]
Tablets is an upcoming feature of ScyllaDB. Keyspaces created with tablets organize the data in a different fashion than regular ring-based keyspaces. Scylla-bench will be extended to be able to test such tables: https://github.com/scylladb/scylla-bench/issues/131 https://github.com/scylladb/scylla-bench/issues/132. We should extend (or add new jobs/workloads) existing scylla-bench workloads in SCT to also test keyspaces with tablets enabled.

**Comment by avelanarius** [comment]
@roydahan Please confirm that my team should work on this task (and the linked scylla-bench ones, which are trivial), so that we don't clash with any existing work planned for QA. I'll also appreciate your (and @fruch) input on what types of workloads we want to test.

**Comment by fruch** [comment]
@avelanarius 

since there a new option, that enable tablets on keyspaces/tables, without specifying anything in keyspace creation 
this might be unneeded. check it with @xemul if it's really needed

**Comment by roydahan** [comment]
No need to do it in any of the tools at the moment.
In any case, having this in one place is sufficient, closing this one and possibly the one in scylla-bench soon.
