### ISSUE TITLE
 Sending e-mail for failed tests doesn't happen (no failure mails for perf jobs)

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-cluster-tests#7136]
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/pavel/job/perf-regression-latency-650gb-grow-shrink/6/

Only "write" subtest succeeded and e-mail for it was sent and (!) was delivered. The "read" and "mixed" subtests failed, e-mail is claimed in logs to be sent, but there's no one in my inbox

Similar for same pipeline, job 5

**Comment by soyacz** [comment]
from what I see, in jenkins sending email failed for these 2 failed tests. This happens because there was `Results file not found` error - which can happen when c-s don't finish gracefully.

**Comment by fruch** [comment]
@xemul you still have issue with the email ?

**Comment by xemul** [comment]
Last time I tried (~beginning of Feb) I didn't get any e-mails, so likely I still do

**Comment by soyacz** [comment]
but what should be the solution? In case c-s failed, we cannot compare results to previous runs and email cannot be populated with data.
We can do only a fix to send email without any results - just logs and info about failure. Is that what you need?

**Comment by fruch** [comment]
@soyacz we should put failure email into email results file, if there's no other result

**Comment by soyacz** [comment]
> @soyacz we should put failure email into email results file, if there's no other result

Also should also send email results for the first run - currently it fails due to missing comparison data (all first runs of cloned jenkins job). In that case we should just send results without comparisons (N/A values)

**Comment by fruch** [comment]
> > @soyacz we should put failure email into email results file, if there's no other result
> 
> Also should also send email results for the first run - currently it fails due to missing comparison data (all first runs of cloned jenkins job). In that case we should just send results without comparisons (N/A values)

Let's track this on its issue. Since the changes are going to be in different places, it's not tied to on another

**Comment by soyacz** [comment]
> Let's track this on its issue. Since the changes are going to be in different places, it's not tied to on another

https://github.com/scylladb/scylla-cluster-tests/issues/7495

**Comment by fruch** [comment]
we now have email on failures, and when there no results we get emails as well.
(not to mention one can track it in argus now, with almost all of the information from the emails)
