### ISSUE TITLE
test continues to run after failure, doing nothing

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-cluster-tests#7157]
### Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

After https://github.com/scylladb/scylla-cluster-tests/issues/7156, the test doesn't make any progress. It doesn't terminate, but it also doesn't load the cluster.

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/avi/job/avi-regression-latency-650gb-grow-shrink/7/console

![image](https://github.com/scylladb/scylla-cluster-tests/assets/1017210/1e0b2c3a-df50-4050-b4fa-76f0fb039fba)

**Comment by fruch** [comment]
test failed in in 35min, (that what it taking for setup in that branch v14),
and was aborted during the log collection phase.

https://github.com/scylladb/scylla-cluster-tests/issues/7156 still need to be addressed,

but this one I'm closing, it's would be better in newer branch where we improved the setup time.
