### ISSUE TITLE
Low performance when installing from repo file (requires restart)

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7172]
When running running performance test (write) with Scylla installed from repo file, perf is much better if restarting Scylla before workload.
E.g. result without restart:
![no-restart](https://github.com/scylladb/scylla-cluster-tests/assets/18242288/c0354cc5-92be-4f97-b5a0-5bca343e8943)

the same test with putting `self.db_cluster.restart_scylla()` before running write workload:
![image](https://github.com/scylladb/scylla-cluster-tests/assets/18242288/73592ff7-2cdf-4cb6-b124-7cf5a7d7c91c)

Possibly, Scylla is not working at best perf in longevities (needs confirmation) when installed from repo file (and not restarted).

**Comment by fruch** [comment]
isn't that an issue with scylla ?, i.e. that installation of the box behave better after restart ?

**Comment by soyacz** [comment]
I don't know, I need to reexamine what happens when we install from repo file - if we do proper restarts after io-tune and if our procedure adhere from the official one.

**Comment by fruch** [comment]
> I don't know, I need to reexamine what happens when we install from repo file - if we do proper restarts after io-tune and if our procedure adhere from the official one.

io_properties was overridden in this run ? maybe I've introduced it in the wrong place ? after scylla started ?

**Comment by soyacz** [comment]
> > I don't know, I need to reexamine what happens when we install from repo file - if we do proper restarts after io-tune and if our procedure adhere from the official one.
> 
> io_properties was overridden in this run ? maybe I've introduced it in the wrong place ? after scylla started ?

when installing from repo we run scylla-setup and io-tune, need to examine, but I'm currently busy with other task - I'll get back to it soon as possible: I need to conclude Z3 tests and make results reproducible by jenkins job.

**Comment by fruch** [comment]
@soyacz 

do we have anything else todo with this one ?

**Comment by soyacz** [comment]
> @soyacz 
> 
> do we have anything else todo with this one ?

I think it can be closed
