### ISSUE TITLE
Replace i3.* with i4i.* instances (for example - i3.large -> i4i.large)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#7191]
The price is almost the same, the performance is substantially better. See https://instances.vantage.sh/?filter=i4i.large|i3.large&compare_on=true&selected=i4i.large,i3.large for comparison.

**Comment by mykaul** [comment]
Example - https://github.com/scylladb/scylla-cluster-tests/blob/ff98c60bfbcfda893971557bf1890432090dac15/unit_tests/test_config.py#L86

**Comment by mykaul** [comment]
Same for c5.* and c6i (or c6a) - see https://instances.vantage.sh/?filter=c5.large|c6i.large&compare_on=true&selected=c5.large,c6i.large and https://github.com/scylladb/scylla-cluster-tests/blob/ff98c60bfbcfda893971557bf1890432090dac15/test-cases/cdc/cdc-replication-longevity.yaml#L13

**Comment by fruch** [comment]
> Example - https://github.com/scylladb/scylla-cluster-tests/blob/ff98c60bfbcfda893971557bf1890432090dac15/unit_tests/test_config.py#L86

This a unittest, it not code that really provision a VM in AWS

We already did a sweep and replaced most of the i3, with exception of few tests that would need to be recalibrated for example SLA tests.

And we have very few performance tests that need to be calibrated with i4

**Comment by mykaul** [comment]
> > Example - https://github.com/scylladb/scylla-cluster-tests/blob/ff98c60bfbcfda893971557bf1890432090dac15/unit_tests/test_config.py#L86
> 
> This a unittest, it not code that really provision a VM in AWS

Yep, saw that - but want to ensure folks don't copy-paste from it.

> 
> We already did a sweep and replaced most of the i3, with exception of few tests that would need to be recalibrated for example SLA tests.
> 
> And we have very few performance tests that need to be calibrated with i4

Yes, I don't think we should touch them without calibration.

**Comment by fruch** [comment]
> > > Example - https://github.com/scylladb/scylla-cluster-tests/blob/ff98c60bfbcfda893971557bf1890432090dac15/unit_tests/test_config.py#L86
> > 
> > 
> > This a unittest, it not code that really provision a VM in AWS
> 
> Yep, saw that - but want to ensure folks don't copy-paste from it.
> 
> > We already did a sweep and replaced most of the i3, with exception of few tests that would need to be recalibrated for example SLA tests.
> > And we have very few performance tests that need to be calibrated with i4
> 
> Yes, I don't think we should touch them without calibration.

we are working on the performance ones, 

The SLA related ones should be handle by whom would work on https://github.com/scylladb/qa-tasks/issues/1593
But that's waiting for the relevant group to handle (i.e the one owning SLA)

**Comment by fruch** [comment]
> YAY - was it tested enough? did we communicate this change wide enough so folks pay extra attention in the coming days to change in test behavior/stability?

if there would be trouble with the nightly / tier1 we would know about it in the upcoming week.
so who are gonna be looking on tests is aware (i.e. me)

the rest of the cases, we'll find out next we'll try to run them.
