### ISSUE TITLE
rolling upgrades failed on step "Will check paged query before upgrading nodes" 

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#7232]
## Packages

Scylla version: `5.4.3-20240211.cf42ca0c2a65` with build-id `3b28ea7f1f552247f942244e28fe84917c997dcb`

Kernel Version: `5.10.0-28-cloud-amd64`

## Issue description

rolling upgrade tests failed with an error before the upgrade itself:
```
2024-02-24 05:35:12.049: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=23026c49-5e74-49eb-b04d-354d02dd01ab, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 660, in test_rolling_upgrade
self.paged_query()
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3389, in paged_query
full_res = self.rows_to_list(
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2419, in rows_to_list
return [list(row) for row in rows]
TypeError: 'NoneType' object is not iterable
```

 on step ```Will check paged query before upgrading nodes```

## Installation details

Cluster size: 4 nodes (n2-highmem-48)

Scylla Nodes used in this run:
- rolling-upgrade--debian-bullseye-db-node-cc3be31d-0-4 (35.237.87.235 | 10.142.0.217) (shards: 44)
- rolling-upgrade--debian-bullseye-db-node-cc3be31d-0-3 (35.237.104.100 | 10.142.0.214) (shards: 44)
- rolling-upgrade--debian-bullseye-db-node-cc3be31d-0-2 (34.139.253.94 | 10.142.0.203) (shards: 44)
- rolling-upgrade--debian-bullseye-db-node-cc3be31d-0-1 (34.23.120.123 | 10.142.0.94) (shards: 44)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-11` (gce: undefined_region)

Test: `rolling-upgrade-debian11-test`
Test id: `cc3be31d-e886-423a-a9fc-3f8d337648e8`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-debian11-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4103add70864490e724e9ddc608ef14835926677/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor cc3be31d-e886-423a-a9fc-3f8d337648e8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cc3be31d-e886-423a-a9fc-3f8d337648e8)
- Show all stored logs command: `$ hydra investigate show-logs cc3be31d-e886-423a-a9fc-3f8d337648e8`

## Logs:
- **db-cluster-cc3be31d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/db-cluster-cc3be31d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/db-cluster-cc3be31d.tar.gz)
- **sct-runner-events-cc3be31d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/sct-runner-events-cc3be31d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/sct-runner-events-cc3be31d.tar.gz)
- **sct-cc3be31d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/sct-cc3be31d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/sct-cc3be31d.log.tar.gz)
- **loader-set-cc3be31d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/loader-set-cc3be31d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/loader-set-cc3be31d.tar.gz)
- **monitor-set-cc3be31d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/monitor-set-cc3be31d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cc3be31d-e886-423a-a9fc-3f8d337648e8/20240224_064444/monitor-set-cc3be31d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian11-test/99/)
[Argus](https://argus.scylladb.com/test/79d2ac19-a1cc-4ab3-b3cb-8333e45e4812/runs?additionalRuns[]=cc3be31d-e886-423a-a9fc-3f8d337648e8)
</details>

**Comment by fruch** [comment]
seems like 25d82527a31adc821d3ae7695b9633f59b4c3463 is the cause, looks like `fetch_all_rows` breaks if timeout=None
I would produce a fix soon
