### ISSUE TITLE
SCYLLA_VERSION_IN_SCYLLA_MANAGER is 5.2.x, while the operator moved to 5.4.x (5.4.3 is the latest)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#7253]
https://github.com/scylladb/scylla-cluster-tests/blob/a8b8d7280d2365728faf2a8da0d4aa610a2f631d/sdcm/cluster_k8s/__init__.py#L132 is using an outdated version - I'm unsure why we need this version specifically instead of relying on the operator default, but the current version I see is older than the one used by the operator (see https://github.com/scylladb/scylla-operator/commit/94f685c354d61bc48a31600dbe60a76993c776bf )

**Comment by vponomaryov** [comment]
It is fixed as part of the following merged PR: https://github.com/scylladb/scylla-cluster-tests/pull/7259
