### ISSUE TITLE
`request_aborted` and `sleep_aborted` messages while bootstrap_streaming_error nemesis

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#7263]
Error during `disrupt_bootstrap_streaming_error`:
```
2024-03-11T18:23:13.144+00:00 longevity-10gb-3h-2023-1-db-node-eastus-10      !ERR | scylla[11250]:  [shard 0] init - Startup failed: raft::request_aborted (Request is aborted by a caller)
```
and 
```
2024-03-10T12:23:19.539+00:00 longevity-10gb-3h-2023-1-db-node-eastus-10      !ERR | scylla[11142]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

No impact, not failures.
I do not see any problems there.

@aleksbykov please, let your opinion. Runs #30 and #31
https://argus.scylladb.com/test/495648b9-1123-4547-a33b-eef73457c1db/runs?additionalRuns[]=c4ed6e5a-fc07-464b-b53c-c29b27a58802

## Packages

Scylla version: `2023.1.6-20240306.ee8c8089d9c4` with build-id `ba16490fa8be728988abec09fdc65e8f55710317`
Kernel Version: `5.15.0-1058-azure`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-9 (52.170.184.238 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-8 (23.96.45.245 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-7 (20.163.136.7 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-6 (20.185.237.197 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-5 (104.45.198.132 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-4 (172.171.202.180 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-3 (172.191.3.178 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-2 (172.191.1.146 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-10 (13.92.102.127 | 10.0.0.6) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-c4ed6e5a-eastus-1 (172.191.0.149 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-2023.1.6-x86_64-2024-03-07T23-42-10` (azure: undefined_region)

Test: `longevity-10gb-3h-azure-test`
Test id: `c4ed6e5a-fc07-464b-b53c-c29b27a58802`
Test name: `enterprise-2023.1/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/419768dacc27353c77df1e80500457a5cb4b697a/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c4ed6e5a-fc07-464b-b53c-c29b27a58802`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c4ed6e5a-fc07-464b-b53c-c29b27a58802)
- Show all stored logs command: `$ hydra investigate show-logs c4ed6e5a-fc07-464b-b53c-c29b27a58802`

## Logs:
- **db-cluster-c4ed6e5a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/db-cluster-c4ed6e5a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/db-cluster-c4ed6e5a.tar.gz)
- **sct-runner-events-c4ed6e5a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/sct-runner-events-c4ed6e5a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/sct-runner-events-c4ed6e5a.tar.gz)
- **sct-c4ed6e5a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/sct-c4ed6e5a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/sct-c4ed6e5a.log.tar.gz)
- **loader-set-c4ed6e5a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/loader-set-c4ed6e5a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/loader-set-c4ed6e5a.tar.gz)
- **monitor-set-c4ed6e5a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/monitor-set-c4ed6e5a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/monitor-set-c4ed6e5a.tar.gz)
- **parallel-timelines-report-c4ed6e5a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/parallel-timelines-report-c4ed6e5a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c4ed6e5a-fc07-464b-b53c-c29b27a58802/20240311_190910/parallel-timelines-report-c4ed6e5a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-10gb-3h-azure-test/31/)
[Argus](https://argus.scylladb.com/test/495648b9-1123-4547-a33b-eef73457c1db/runs?additionalRuns[]=c4ed6e5a-fc07-464b-b53c-c29b27a58802)
</details>

**Comment by temichus** [comment]
@aleksbykov, 1 common issue regarding disrupt_bootstrap_streaming_error should be created and all other closed

**Comment by aleksbykov** [comment]
I didn't find other errors. Need to update filters to correctly filter new errors

**Comment by aleksbykov** [comment]
Closed due to new issue: https://github.com/scylladb/scylla-cluster-tests/issues/7286
