### ISSUE TITLE
Oracle Enterprise Linux 8.1 artifacts test fail on non-supported instance type

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#7271]
The instance type change on https://github.com/scylladb/scylla-cluster-tests/pull/7198 cause OEL8 test to fail [0] as non-supported instance type

```
01:37:18  < t:2024-03-10 23:37:18,111 f:cluster_aws.py  l:274  c:sdcm.cluster         p:ERROR > Cluster artifacts-oel81-jenkins-db-cluster-932bf417 (AMI: ['ami-0e883e67243efea62'] Type: i4i.large): Cannot create spot_low_price instance(s): An error occurred (UnsupportedOperation) when calling the RequestSpotInstances operation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
```

Regardless, we should try changing the base-image from the Marketplace (paid image) to the community version

[0] https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-oel81-test/344/console

@fruch

**Comment by mykaul** [comment]
8.1 is irrelevant. Why are we using such an old release?

**Comment by fruch** [comment]
> 8.1 is irrelevant. Why are we using such an old release? 

We are selecting versions based on AMIs, so it's hardcoded, and since we introduced it wasn't changed.

When GCP images are used for example debian10, we always get the latest version of it, not sure there equivalent in AWS for every type of AMI (I know Ubuntu images does have)
