### ISSUE TITLE
Send test details report for failed perf tests

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7309]
When load fails in perf tests email report is not sent due missing result.json. Jenkins step fails with message `Results file not found`
But in that case we still should receive email with test details to first acknowledge the failure and ease investigation.
This was also raised by developers who were confused about missing email report after running perf tests that failed.

example run: https://jenkins.scylladb.com/job/scylla-enterprise/job/scylla-enterprise-perf-regression-latency-650gb-during-upgrade/39/

**Comment by fruch** [comment]
@soyacz this is still an issue we want to fix ?

**Comment by soyacz** [comment]
> @soyacz this is still an issue we want to fix ?

yes
