### ISSUE TITLE
"manifest unknown" is a bad error message

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylla-cluster-tests#7333]
If you mismatch SCT_SCYLLA_VERSION with SCT_DOCKER_IMAGE e.g. by using scylladb/scylladb but an enterprise version
```
export SCT_SCYLLA_VERSION="2024.1.2"
export SCT_DOCKER_IMAGE="scylladb/scylladb"
```
you will get a "manifest unknown" message which doesn't say anything about what you did wrong.

**Comment by fruch** [comment]
@kbr-scylla 

seems to be that the error you get from the docker daemon, now that I use the exact values you describe:

```
docker.errors.BuildError: pull access denied for scylladb/scylladb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

i.e. this is a non existing repo `scylladb/scylladb`

when it's existing repo, unexisting image you get:

```
docker.errors.BuildError: manifest for scylladb/scylla:2024.1.2 not found: manifest unknown: manifest unknown
```

I think those are reasonable errors to get, in both ends, you get them in ~10sec

**Comment by fruch** [comment]
error is identical to what you'll get on the `docker` command line.

I don't think we can provide better information then that...

**Comment by kbr-scylla** [comment]
> I don't think we can provide better information then that...

It would be enough to append to the error message something like "make sure that the provided SCT_SCYLLA_VERSION matches SCT_DOCKER_IMAGE, in particular you're not trying to combine open-source with enterprise". And that would make user experience 100x better
