### ISSUE TITLE
Download ssh keys should verify if keys are valid

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7335]
Few people had problems with ssh keys - somehow were wrong. 
Idea to verify sha of downloaded keys and re-download if is mismatched.
Also need to verify if keys permissions are valid (600)

**Comment by soyacz** [comment]
hmm, I'm not sure if it's not already fixed in `sdcm.keystore.KeyStore.sync`.
@fruch all this stuff is currently done automatically (including setting permissions). Closing?

**Comment by fruch** [comment]
> hmm, I'm not sure if it's not already fixed in `sdcm.keystore.KeyStore.sync`.
> @fruch all this stuff is currently done automatically (including setting permissions). Closing?

Need to verify if permission is checked and set if key didn't downloaded

Also this report is after that sync was in place

**Comment by fruch** [comment]
shouldn't be an issue, for anyone doing it for the first time.

but if we encounter it again, we can reopen the issue.
