### ISSUE TITLE
`remove_node_then_add_node` nemesis may leave a dead DB node if `nodetool removenode` op fails due to concurrent nemesis with index removal

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#7347]
## Packages

Scylla version: `5.5.0~dev-20240411.0be61e51d329` with build-id `54e018bb43eb2ae707aac127097747cd39532532`

Kernel Version: `5.15.0-1057-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In this scenario we were running 2 nemesis threads in parallel.
One thread was running `disrupt_remove_node_then_add_node` nemesis and another one `disrupt_create_index`.
When the first nemesis was running the `nodetool removenode` op the second one dropped index that it had created before the first nemesis.
It led to the abort of the `removenode` operation agreed by alive nodes:
```
2024-04-13 05:01:31,822 f:common.py       l:1823 c:utils                p:DEBUG > Executing CQL 'CREATE INDEX test_v_nemesis ON scylla_bench.test("v")' ...
...
2024-04-13 05:16:54,847 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  removenode e35af705-73fa-4dd1-8fbc-7ef886511ade "...
...
2024-04-13 05:20:37,095 f:common.py       l:1831 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="DROP INDEX scylla_bench.test_v_nemesis", consistency=Not Set>' ...
...
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: eu-west
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ===================
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > -- Address     Load     Tokens Owns Host ID                              Rack
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN 10.4.11.237 31.32 GB 256    ?    24ca87a5-b1af-4a30-81ed-65d33571caf8 1c  
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN 10.4.8.169  27.93 GB 256    ?    b3695113-7844-4d5d-86ff-d001329ea0d8 1c  
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN 10.4.8.224  28.41 GB 256    ?    45760ec2-0a80-4ec9-8b24-663b413ba961 1c  
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN 10.4.8.26   34.22 GB 256    ?    3185ce37-9ee7-4de5-8fde-3ec1ca5c701d 1c  
2024-04-13 05:20:53,338 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > DN 10.4.9.250  21.90 GB 256    ?    e35af705-73fa-4dd1-8fbc-7ef886511ade 1c
``` 

Nodes logs:
`<node-3>`:
```
Apr 13 05:20:51.964572 longevity-parallel-topology-schema--db-node-4bdf0ea1-3 scylla[7325]:  [shard 0:strm] storage_service - aborting node operation ops_uuid=e603c4dc-685c-435e-a343-f125e4581815
Apr 13 05:20:51.964731 longevity-parallel-topology-schema--db-node-4bdf0ea1-3 scylla[7325]:  [shard 0:strm] storage_service - removenode[e603c4dc-685c-435e-a343-f125e4581815]: Removed node=10.4.9.250 as leaving node, coordinator=10.4.8.26
Apr 13 05:20:51.990290 longevity-parallel-topology-schema--db-node-4bdf0ea1-3 scylla[7325]:  [shard 0:strm] node_ops - removenode[e603c4dc-685c-435e-a343-f125e4581815]: The removenode_abort command failed while handling a previous error, sync_nodes={10.4.8.224, 10.4.11.237, 10.4.8.169, 10.4.8.26}: std::runtime_error (The removenode_abort command failed for nodes={10.4.8.169}). Ignoring
```

`<node-4>`:
```
Apr 13 05:20:51.965141 longevity-parallel-topology-schema--db-node-4bdf0ea1-4 scylla[7336]:  [shard 0:strm] storage_service - aborting node operation ops_uuid=e603c4dc-685c-435e-a343-f125e4581815
Apr 13 05:20:51.965291 longevity-parallel-topology-schema--db-node-4bdf0ea1-4 scylla[7336]:  [shard 0:strm] storage_service - removenode[e603c4dc-685c-435e-a343-f125e4581815]: Removed node=10.4.9.250 as leaving node, coordinator=10.4.8.26
```

`<node-5>`:
```
2024-04-13T05:20:52.281+00:00 longevity-parallel-topology-schema--db-node-4bdf0ea1-5     !INFO | scylla[7374]:  [shard 0:strm] storage_service - aborting node operation ops_uuid=e603c4dc-685c-435e-a343-f125e4581815
2024-04-13T05:20:52.281+00:00 longevity-parallel-topology-schema--db-node-4bdf0ea1-5     !INFO | scylla[7374]:  [shard 0:strm] storage_service - removenode[e603c4dc-685c-435e-a343-f125e4581815]: Removed node=10.4.9.250 as leaving node, coordinator=10.4.8.26
```

`<node-7>`:
```
Apr 13 05:20:51.964691 longevity-parallel-topology-schema--db-node-4bdf0ea1-7 scylla[7304]:  [shard 0:strm] storage_service - aborting node operation ops_uuid=e603c4dc-685c-435e-a343-f125e4581815
Apr 13 05:20:51.964815 longevity-parallel-topology-schema--db-node-4bdf0ea1-7 scylla[7304]:  [shard 0:strm] storage_service - removenode[e603c4dc-685c-435e-a343-f125e4581815]: Removed node=10.4.9.250 as leaving node, coordinator=10.4.8.26
```

Then one of the following nemesis failed with the following error:
```
error executing POST request to http://localhost:10000/storage_service/decommission with parameters {}: remote replied with status code 500 Internal Server Error:
std::runtime_error (decommission[b7236c1a-106e-431e-bfe2-175e4b789ad9]: \
  Cannot start: nodes={10.4.9.250} needed for decommission operation are down. It is highly recommended to fix the down nodes and try again.)
```

The `10.4.9.250` is the dead node left by the `remove_node_then_add_node` nemesis.

## Impact

Spoils whole test run.

## How frequently does it reproduce?

First time observed

## Installation details

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-4bdf0ea1-8 (3.249.163.150 | 10.4.8.8) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-7 (54.170.247.145 | 10.4.8.169) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-6 (54.216.131.244 | 10.4.9.28) (shards: -1)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-5 (3.255.153.131 | 10.4.8.224) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-4 (34.255.216.239 | 10.4.11.237) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-3 (34.244.101.250 | 10.4.8.26) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-2 (18.201.146.10 | 10.4.9.250) (shards: 7)
- longevity-parallel-topology-schema--db-node-4bdf0ea1-1 (3.255.195.175 | 10.4.8.111) (shards: 7)

OS / Image: `ami-03a7123d7bfc23027` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `4bdf0ea1-8890-468e-9b6e-c89d5583acef`
Test name: `scylla-master/tier1/longevity-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ead2529c1f5f3816f04e3b23de737a359134c053/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4bdf0ea1-8890-468e-9b6e-c89d5583acef`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4bdf0ea1-8890-468e-9b6e-c89d5583acef)
- Show all stored logs command: `$ hydra investigate show-logs 4bdf0ea1-8890-468e-9b6e-c89d5583acef`

## Logs:
- **db-cluster-4bdf0ea1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/db-cluster-4bdf0ea1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/db-cluster-4bdf0ea1.tar.gz)
- **sct-runner-events-4bdf0ea1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/sct-runner-events-4bdf0ea1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/sct-runner-events-4bdf0ea1.tar.gz)
- **sct-4bdf0ea1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/sct-4bdf0ea1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/sct-4bdf0ea1.log.tar.gz)
- **loader-set-4bdf0ea1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/loader-set-4bdf0ea1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/loader-set-4bdf0ea1.tar.gz)
- **monitor-set-4bdf0ea1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/monitor-set-4bdf0ea1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4bdf0ea1-8890-468e-9b6e-c89d5583acef/20240413_062353/monitor-set-4bdf0ea1.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-schema-topology-changes-12h-test/9/)
[Argus](https://argus.scylladb.com/test/e17ff39a-f3f6-4ac6-a161-871267fd3955/runs?additionalRuns[]=4bdf0ea1-8890-468e-9b6e-c89d5583acef)
</details>

**Comment by fruch** [comment]
I'm not sure from this description why it's not a scylla core issue ? A deletion of MV shouldn't be affecting topology changes.

It's not a limitation of parallel nemesis in SCT, it actually sounds like elevating an actual issue

**Comment by vponomaryov** [comment]
> I'm not sure from this description why it's not a scylla core issue ? A deletion of MV shouldn't be affecting topology changes.
> 
> It's not a limitation of parallel nemesis in SCT, it actually sounds like elevating an actual issue

Created scylladb issue here: https://github.com/scylladb/scylladb/issues/18436
