### ISSUE TITLE
Grow-shrink cluster perf test is not using multi-az

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7384]
while we configure multi az in grow-shrink cluster perf test, nodetool status show we use anyway only one rack.

## Installation details

Cluster size: 3 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-6 (54.154.216.214 | 10.4.0.214) (shards: 7)
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-5 (3.253.65.77 | 10.4.0.31) (shards: 7)
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-4 (54.247.48.151 | 10.4.1.10) (shards: 7)
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-3 (3.254.164.240 | 10.4.1.169) (shards: 7)
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-2 (54.76.20.11 | 10.4.2.148) (shards: 7)
- perf-latency-grow-shrink-ubuntu-db-node-b2e47f7a-1 (3.253.62.202 | 10.4.2.207) (shards: 7)

OS / Image: `ami-044f45ee3df20f616` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-grow-shrink`
Test id: `b2e47f7a-3ac6-4e8c-817f-dfb1f518850e`
Test name: `scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink`
Test config file(s):

- [perf-regression-latency-650gb-grow-shrink.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cfc7e918c78d07caededb21f1d5e28754c3f40b7/test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b2e47f7a-3ac6-4e8c-817f-dfb1f518850e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b2e47f7a-3ac6-4e8c-817f-dfb1f518850e)
- Show all stored logs command: `$ hydra investigate show-logs b2e47f7a-3ac6-4e8c-817f-dfb1f518850e`

## Logs:
- **db-cluster-b2e47f7a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/db-cluster-b2e47f7a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/db-cluster-b2e47f7a.tar.gz)
- **sct-runner-b2e47f7a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/sct-runner-b2e47f7a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/sct-runner-b2e47f7a.tar.gz)
- **monitor-set-b2e47f7a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/monitor-set-b2e47f7a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/monitor-set-b2e47f7a.tar.gz)
- **loader-set-b2e47f7a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/loader-set-b2e47f7a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2e47f7a-3ac6-4e8c-817f-dfb1f518850e/20240428_145423/loader-set-b2e47f7a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-650gb-grow-shrink/38/)
[Argus](https://argus.scylladb.com/test/72a0f93b-6d0b-4f45-8462-e876a768cf54/runs?additionalRuns[]=b2e47f7a-3ac6-4e8c-817f-dfb1f518850e)
</details>

**Comment by soyacz** [comment]
root cause are missing backports to perf-v14: 

* https://github.com/scylladb/scylla-cluster-tests/pull/5934
* https://github.com/scylladb/scylla-cluster-tests/pull/6055/

Ideas:
1. test backports on side branch, if ok backport those two to it. Find also bugfixes patches for those - might be a few.
2. test grow-shrink perf test using master SCT branch
3. create branch-perf-v15

**Comment by fruch** [comment]
> root cause are missing backports to perf-v14:
> 
> * [feature(aws): add suport to multi az #5934](https://github.com/scylladb/scylla-cluster-tests/pull/5934)
> * [feature(multi-az): adapt provision step to multi-az #6055](https://github.com/scylladb/scylla-cluster-tests/pull/6055)
> 
> Ideas:
> 
> 1. test backports on side branch, if ok backport those two to it. Find also bugfixes patches for those - might be a few.
> 2. test grow-shrink perf test using master SCT branch
> 3. create branch-perf-v15

I think #3 since we want to do it anyhow, maybe first get the parallel cluster setup in ? anything else you think worth waiting for ?

**Comment by soyacz** [comment]
> I think #3 since we want to do it anyhow, maybe first get the parallel cluster setup in ? anything else you think worth waiting for ?

Just maybe the new throughput test I was working on.

**Comment by fruch** [comment]
> > I think #3 since we want to do it anyhow, maybe first get the parallel cluster setup in ? anything else you think worth waiting for ?
> 
> Just maybe the new throughput test I was working on.

and we can backport into it the new things (and fixes as needed)

**Comment by fruch** [comment]
let's raise it in the meeting, if it's important to fix and support multi-az

**Comment by fruch** [comment]
meanwhile let run on master, and see what's need adapting 
for example disable KMS

**Comment by soyacz** [comment]
master run (defaults, oss): https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-latency-650gb-grow-shrink-tablets/2/

**Comment by soyacz** [comment]
failed due: https://github.com/scylladb/scylla-cluster-tests/issues/7432

**Comment by juliayakovlev** [comment]
The https://github.com/scylladb/scylla-cluster-tests/pull/7677 should solve this.

Running the test:
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/Network/job/scylla-master-perf-regression-latency-650gb-grow-shrink/

For now I see that instances were provisioned in the different AZs

**Comment by juliayakovlev** [comment]
> The #7677 should solve this.
> 
> Running the test: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/Network/job/scylla-master-perf-regression-latency-650gb-grow-shrink/
> 
> For now I see that instances were provisioned in the different AZs


All  instances were provisioned in the different AZs:

https://argus.scylladb.com/test/a4084d48-6d92-4bd7-9a89-17af3a91f0b2/runs?additionalRuns[]=ceec3f53-1439-432f-b0ca-b44884b08688
https://argus.scylladb.com/test/a4084d48-6d92-4bd7-9a89-17af3a91f0b2/runs?additionalRuns[]=ea83547c-4b99-4924-bee6-10d3660ce196
https://argus.scylladb.com/test/a4084d48-6d92-4bd7-9a89-17af3a91f0b2/runs?additionalRuns[]=a585550a-26dc-4455-ad3b-53622c0cab84

**Comment by soyacz** [comment]
> The #7677 should solve this.
> 
> Running the test: https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/Network/job/scylla-master-perf-regression-latency-650gb-grow-shrink/
> 
> For now I see that instances were provisioned in the different AZs

Yes, the issue is related to perf-v14 branch, where we didn't backport multi AZ commits. Your work will hopefully fix issues that happen on master and it will work on perf-v15 (we soon plan to create).

**Comment by fruch** [comment]
reopening

since we didn't fully validate this case is working on master

**Comment by juliayakovlev** [comment]
@soyacz do you faced  in additional problem?

**Comment by soyacz** [comment]
> @soyacz do you faced in additional problem?

No, just reopened it to remember that perf tests we currently run are still not multi az (and this is not related to Your fix - just we didn't backport multi-az support to it. Possibly we'll close it after creating branch-perf-v15).

**Comment by fruch** [comment]
Using multi AZ, make this case really long

- https://argus.scylladb.com/workspace?state=WyJmZTFmMzJhNS05MDM3LTQxZDktODM4OS05NDYxNDVjZTA4NmQiLCI0YmRiNDY3OS0xM2MwLTQ1YjEtYWY0Yy0yNmFiMTc1ZmQxYjMiXQ

on enterprise it took 9h each (mixed 15h)
on oss, it took 10h, 11h, and mixed have passed the 24h now and didn't finish.

on v14, without multi-AZ, it took 7h,8h,8h in the last few runs.

**Comment by soyacz** [comment]
Worth to mention on perf meeting or raise an issue maybe?

**Comment by fruch** [comment]
we decided to not run multi az regullary, but it's operational if needed
