### ISSUE TITLE
Unfriendly error on missing QA keys

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#739]
I installed and ran Hydra without properly configuring AWS, apparently, and got
```
$ hydra ls                    
Docker version 1.13.1, build 1556cce-unsupported
scylladb/hydra                v0.28               edfe6e5bc96f        47 minutes ago      1.27 GB
Image up-to-date
Obtaining QA SSH keys...
QA private key '/home/nyh/.ssh/scylla-qa-ec2' doesn't exist. Retrieving...
fatal error: Unable to locate credentials
```

The "fatal error: Unable to locate credentials" message could be made friendlier. I should be told that I need to run "aws configure", and where I should get the parameters it asks me.
Come to think of it, if the README already contains all the parameters to "aws configure", why can't the script run it automatically?

CC: @eliransin

**Comment by nyh** [comment]
To clarify my latest understanding:

The README doesn't explain this that a user who wants to run this needs to get his own personal id and password, and run "aws configure" using these. Apparently the only way to get this personal id and password is to ask Shlomi @slivne . It doesn't help reading the README - they are not listed there, and they are different for every employee.

Would be nice if instead of "fatal error: Unable to locate credentials", or in addition to it, we'll get a message telling the user to run "aws configure" and a pointer to README.md which explains how, and the README.md section needs to be updated on where to get those personal id/password.

**Comment by bentsi** [comment]
- I disagree with you, It does help to read Readme :) 
- The Readme is NOT written for people that are completely new to AWS/GCP clouds
(Imagine that if one will read ScyllaDB Readme file he will ask to explain what is C++ and what is compiler. 
Any newbie tutorial to AWS that explains how to connect, during the first steps explains what are these keys. For example: https://cloudacademy.com/blog/how-to-use-aws-cli/)

Any way we will add the information that you expected to see there, this is the purpose of this issue.

**Comment by nyh** [comment]
Bentsi, I DID read the README. This is what it says on aws config:
```
Use following values when running ``aws configure``
 * ``region`` -> `us-east-1`
 * ``Default output format`` -> `None`
 * ``aws_access_key_id``, ``aws_secret_access_key``
```

First of all, this test is in the wrong place (not where you asked me to run aws configure).
But more importantly, it really made it seem like aws_access_key_id should be set to aws_secret_access_key. I had no idea what these things meant, or in fact that I was doing anything wrong or that the error message I'm seeing even has anything to do with the "aws config".

I don't understand the point about "not written for people new to AWS/GCP clouds". Don't you agree that the people who'll need to use this are mostly new employees? Many of them will be "completely new" to these, but more importantly, will have absolutely no idea that your script even needs them to get an id and from where (i.e., Shlomi). Please note that until yesterday, I was convinced that the entire QA team was running with the same credentials which everybody was sharing, and I didn't even know that I needed my own credentials to run SCT.

**Comment by bentsi** [comment]
As I said earlier, we will make the changes in the Readme file and improve the error message. anything else that I can help you with?
