### ISSUE TITLE
`alternator_enforce_authorization` need to support auth_v2

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7405]
see https://github.com/scylladb/scylladb/issues/17718#issuecomment-2096498242 for details

current code write directly to `system_auth`, 
~~while now on scylla master, it should be writing into `system_auth_v2`~~

we need to create a ROLE and retrieve its salted_hash

```python
            if self.params.get('alternator_enforce_authorization'):
                with self.db_cluster.cql_connection_patient(self.db_cluster.nodes[0]) as session:
                    session.execute(SimpleStatement("""
                        INSERT INTO system_auth.roles (role, salted_hash) VALUES (%s, %s)
                    """, consistency_level=ConsistencyLevel.ALL),
                                    (self.params.get('alternator_access_key_id'),
                                     self.params.get('alternator_secret_access_key')))
```

I suggest we keep writing into both for backward compatibility

**Comment by nuivall** [comment]
> I suggest we keep writing into both for backward compatibility

just use create role statement for 100% compatibility

**Comment by fruch** [comment]
> > I suggest we keep writing into both for backward compatibility
> 
> just use create role statement for 100% compatibility

So docs should show the exact command needed

**Comment by fruch** [comment]
@nuivall @nyh 

the process of using CREATE ROLE, should be documented, isn't less than trivial now. since you can set the salted_hash directly
you need to read it from the `SELECT * FROM system_auth_v2.roles` directly, and use it.

and it's not documented anywhere

**Comment by fruch** [comment]
here's a dtes example of how I got it working:

```diff
diff --git a/alternator_tests.py b/alternator_tests.py
index bfe2898a..6f283ae9 100644
--- a/alternator_tests.py
+++ b/alternator_tests.py
@@ -1327,6 +1327,33 @@ class TesterAlternator(BaseAlternator):
         items = self.get_table_items(table_name=TABLE_NAME, node=node1, consistent_read=False, num_of_items=num_of_items)
         assert [item for item in items if NUM_OF_ELEMENTS_IN_SET > len(item["Item"]["hello_set"]) > 0]

+    def test_alternator_enforce_authorization(self, request: pytest.FixtureRequest):
+        num_of_nodes = self._num_of_nodes_for_test(rf=3)
+        self.prepare_dynamodb_cluster(
+            num_of_nodes=num_of_nodes,
+            extra_config={
+                "alternator_enforce_authorization": True,
+                "authenticator": "org.apache.cassandra.auth.PasswordAuthenticator",
+                "authorizer": "org.apache.cassandra.auth.CassandraAuthorizer",
+            },
+        )
+        node1 = self.cluster.nodelist()[0]
+        num_of_items = 300
+
+        cql_session = self.patient_cql_connection(node1, user="cassandra", password="cassandra")
+        cql_session.execute("CREATE ROLE alternator WITH PASSWORD = 'password'")
+
+        salted_hash = list(cql_session.execute("SELECT salted_hash FROM system_auth_v2.roles WHERE role='alternator';"))
+        self.salted_hash = salted_hash[0].salted_hash
+        request.addfinalizer(lambda: setattr(self, "salted_hash", "None"))
+
+        self.alternator_urls = {}
+        self.alternator_apis = {}
+
+        items = self.create_items(num_of_items=num_of_items)
+        self.create_table(table_name=TABLE_NAME, node=node1)
+        self.batch_write_actions(table_name=TABLE_NAME, node=node1, new_items=items)
+

 class ConcurrencyLimitNotExceededError(Exception):
     pass

diff --git a/alternator_utils.py b/alternator_utils.py
index b4e80635..1044755d 100644
--- a/alternator_utils.py
+++ b/alternator_utils.py
@@ -159,6 +159,8 @@ class BaseAlternator(Tester):
     _table_primary_key = schemas.HASH_KEY_NAME
     _table_primary_key_format = "test{}"

+    salted_hash = "None"
+
     alternator_urls = {}
     alternator_apis = {}
     clear_resources_methods = []
@@ -171,7 +173,7 @@ class BaseAlternator(Tester):

     @property
     def dynamo_params(self):
-        p = dict(aws_access_key_id="None", aws_secret_access_key="None", region_name="None", verify=False, config=GLOBAL_CONFIG)
+        p = dict(aws_access_key_id="alternator", aws_secret_access_key=self.salted_hash, region_name="None", verify=False, config=GLOBAL_CONFIG)
         if self.is_encrypted:
             p["verify"] = self.cert_file
         return p
```

**Comment by nyh** [comment]
The long-standing explanation in docs/alternator/compatibility.md suggests (perhaps not clearly enough) that you should exactly what you ended up doing:
1. Create a user in whatever way you normally do it - CREATE ROLE, Scylla-Cloud UI, or whatever.
2. Now **read** from `system_auth_v2.roles` (this was updated recently) the "salted hash" - and this will be your Alternator secret access key ID. This key will look like random garbage you have no control over, but it will really be a salted hash of whatever was chosen as this role's password.

Indeed, Alternator's tests (test/alternator/run) didn't quite do this - instead it directly **wrote** the faux-salted-hash string "secret_pass" into the system table, without bothering to create a role, and the tests just assume the secret key "secret_pass" would work. This probably was never a great idea, and we never recommended that users will actually work this way.

**Comment by fruch** [comment]
> The long-standing explanation in docs/alternator/compatibility.md suggests (perhaps not clearly enough) that you should exactly what you ended up doing:
> 
> 1. Create a user in whatever way you normally do it - CREATE ROLE, Scylla-Cloud UI, or whatever.
> 2. Now **read** from `system_auth_v2.roles` (this was updated recently) the "salted hash" - and this will be your Alternator secret access key ID. This key will look like random garbage you have no control over, but it will really be a salted hash of whatever was chosen as this role's password.
> 
> Indeed, Alternator's tests (test/alternator/run) didn't quite do this - instead it directly **wrote** the faux-salted-hash string "secret_pass" into the system table, without bothering to create a role, and the tests just assume the secret key "secret_pass" would work. This probably was never a great idea, and we never recommended that users will actually work this way.

more than that, the unittest are not using `alternator_enforce_authorization` at all ... (nor do dtest), only SCT did...

**Comment by nyh** [comment]
> unit test only warns about, that one should use this flag, but no part of the test do that: https://github.com/scylladb/scylladb/blame/2ad13e5d7658d072cbc120b68d1eeef86a986ac7/test/alternator/test_authorization.py#L16

Moreover, the tests in test_authorization.py won't just "warn" you if you aren't running Alternator with enforce authorization - those test will fail if you aren't. The printouts are just to help you understand what might have failed, but you would have gotten actual failures if we forgot to enforce authentication.
