### ISSUE TITLE
Hydra: bad permissions when using ~/.ssh/config

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#741]
The SCT docker container mounts the users $HOME on /root in the container, I don't know why.
The problem is that if the user has in his $HOME/.ssh a "config" file, ssh refuses to run because it sees a config file owned (and writable) by another user, and this is considered a security risk.

One way to fix this is to tell ssh NOT to use /root/.ssh/config, with the "-F /dev/null" option. The following patch to `sdcm/remote.py` seems to make the "bad owner" errors from ssh go away:

```patch
diff --git a/sdcm/remote.py b/sdcm/remote.py
index 6d19090..6eab3c8 100644
--- a/sdcm/remote.py
+++ b/sdcm/remote.py
@@ -236,7 +236,7 @@ def _make_ssh_command(user="root", port=22, opts='', hosts_file='/dev/null',
     assert isinstance(connect_timeout, (int, long))
     base_command = path.find_command('ssh')
     base_command += " " + extra_ssh_options
-    base_command += (" -a -x %s -o StrictHostKeyChecking=no "
+    base_command += (" -F /dev/null -a -x %s -o StrictHostKeyChecking=no "
                      "-o UserKnownHostsFile=%s -o BatchMode=yes "
                      "-o ConnectTimeout=%d -o ServerAliveInterval=%d "
                      "-l %s -p %d")
```

An even cleaner solution would be, in my opinion, to not mount $HOME on /root at all. Why do we even need this there? We need to read the user's home directory perhaps to read the secret key file, but it doesn't need to be mounted on /root. It can be on /tmp/homedir - or any other mountpoint.

**Comment by bentsi** [comment]
Thanks for reporting this and suggesting the solution.
The main reason is that it was a quick solution to the following problems
- Hydra should work the same as you work without Hydra. That means that all your configurations of AWS, GCP (Google Cloud Platform), SSH that you currently have should be available inside the container
- Avocado logs are stored inside home directory and are needed be persisted after the test finished

These problems are solvable but need more dev time investment that we decided currently not improve since for most of the users it works (till now you are the only one that complained)

**Comment by nyh** [comment]
I'm the only one who complained because I guess I'm one of the few people who has a ~/.ssh/config. Only if you have this file (which you manually created to set ssh configuration) you'll see this problem.

I understand why you don't want a bigger fix, but maybe my "-F /dev/null" fix can be used? It seems simple enough.

**Comment by nyh** [comment]
Let's do something about this issue - without the "-F /dev/null", ssh does NOT WORK inside the container (i.e., hydra) for users who happen to have (for their own personal reasons, completely unrelated to SCT) a file `~/.ssh/config`.

 If there's a way to add this "-F /dev/null" only when running inside the container, then fine, but I don't know how to do it. But we have to do something, because otherwise hydra simply doesn't work for users like me who have this config file.

@roydahan what do you think?

**Comment by nyh** [comment]
BTW, fixing ssh is not enough, also need to fix scp:

```patch
diff --git a/sdcm/remote.py b/sdcm/remote.py
index 6d19090..5487bbb 100644
--- a/sdcm/remote.py
+++ b/sdcm/remote.py
@@ -236,7 +236,7 @@ def _make_ssh_command(user="root", port=22, opts='', hosts_file='/dev/null',
     assert isinstance(connect_timeout, (int, long))
     base_command = path.find_command('ssh')
     base_command += " " + extra_ssh_options
-    base_command += (" -a -x %s -o StrictHostKeyChecking=no "
+    base_command += (" -F /dev/null -a -x %s -o StrictHostKeyChecking=no "
                      "-o UserKnownHostsFile=%s -o BatchMode=yes "
                      "-o ConnectTimeout=%d -o ServerAliveInterval=%d "
                      "-l %s -p %d")
@@ -398,7 +398,7 @@ class BaseRemote(object):
         key_option = ''
         if self.key_file:
             key_option = '-i %s' % os.path.expanduser(self.key_file)
-        command = ("scp -r %s -o StrictHostKeyChecking=no -o BatchMode=yes "
+        command = ("scp -F /dev/null -r %s -o StrictHostKeyChecking=no -o BatchMode=yes "
                    "-o ConnectTimeout=%d -o ServerAliveInterval=%d "
                    "-o UserKnownHostsFile=%s -P %d %s %s '%s'")
         return command % (self.master_ssh_option, connect_timeout,
```

**Comment by fruch** [comment]
I don't think this is an issue anymore, since we are not mounting into /root anymore but using the user id:group when running docker
