### ISSUE TITLE
Reuse cluster doesn't support well nemesis with add_node

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#743]
When running test with reuse cluster on AWS the original user_data isn't pass to the new nodes that are being added during the test.
For example, when we have a nemesis like decommission or terminate_and_replace, in the stage of adding new node we try to add the new node with cluster_name that is different than the original.
Therefore, the node won't be added to the cluster.

```
Using user data:
--clustername longevity-tls-1tb-7d-3-0-rc4-db-cluster-82753976 --totalnodes 4 --stop-services --seeds 172.16.99.21  --bootstrap true

```

`ClusterName mismatch from 172.16.99.220 longevity-tls-1tb-7d-3-0-rc4-db-cluster-82753976!=longevity-tls-1tb-7d-3-0-rc4-db-cluster-40bf0c12`

**Comment by bentsi** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/746
