### ISSUE TITLE
cannot run cassandra-stress because it is not found

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7430]
nightly images stopped to ship scylla-tools package. This made our approach of using latest nightly docker image for c-s obsolete.

We need to find another way of shipping c-s to our loader nodes.

## Packages

Scylla version: `5.5.0~dev-20240513.2ce643d06bf0` with build-id `2e2c89cbb469c1231861753c4af823040a31579e`

Kernel Version: `5.15.0-1060-aws`

OS / Image: `ami-0de7228fdbd40d174` (aws: undefined_region)

Test: `longevity-100gb-4h-test`
Test id: `b2d93c9e-ebec-4409-8a4f-047a38c7daae`
Test name: `scylla-master/longevity/longevity-100gb-4h-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/29885d9894813da0cd9688cc95e09fb6cd0f1569/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b2d93c9e-ebec-4409-8a4f-047a38c7daae`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b2d93c9e-ebec-4409-8a4f-047a38c7daae)
- Show all stored logs command: `$ hydra investigate show-logs b2d93c9e-ebec-4409-8a4f-047a38c7daae`

## Logs:
- **db-cluster-b2d93c9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/db-cluster-b2d93c9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/db-cluster-b2d93c9e.tar.gz)
- **sct-runner-events-b2d93c9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/sct-runner-events-b2d93c9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/sct-runner-events-b2d93c9e.tar.gz)
- **sct-b2d93c9e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/sct-b2d93c9e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/sct-b2d93c9e.log.tar.gz)
- **loader-set-b2d93c9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/loader-set-b2d93c9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/loader-set-b2d93c9e.tar.gz)
- **monitor-set-b2d93c9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/monitor-set-b2d93c9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/monitor-set-b2d93c9e.tar.gz)
- **parallel-timelines-report-b2d93c9e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/parallel-timelines-report-b2d93c9e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2d93c9e-ebec-4409-8a4f-047a38c7daae/20240514_002840/parallel-timelines-report-b2d93c9e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/833/)
[Argus](https://argus.scylladb.com/test/f05fea04-eb74-4961-94fb-f71c67df52cb/runs?additionalRuns[]=b2d93c9e-ebec-4409-8a4f-047a38c7daae)
</details>

**Comment by roydahan** [comment]
@soyacz are you looking into where the issue is?
Why the docker image is picked incorrectly and why the fallback is to a newer/newest image?

**Comment by soyacz** [comment]
> @soyacz are you looking into where the issue is? Why the docker image is picked incorrectly and why the fallback is to a newer/newest image?

I think that was our decision to use the latest images to test latest java drivers (default if c-s version is set to empty).
Maybe instead of selecting the latest one, we should create another dependabot task to monitor java driver releases and update c-s image then - this way, older branches wouldn't take the latest one. 

Meantime we're still waiting for releng team to ship image with scylla java tools.

**Comment by roydahan** [comment]
According to the comment we have in SCT it shouldn't pick the latest, but the latest of each release (at least this is what I understand). Also, there is a clear definition there of the fallback.

**Comment by fruch** [comment]
we replace those to static images, and there is no more automatic selection of those images
