### ISSUE TITLE
Node benchmarks failed due error in cloning sysbench repo (RPC failed; curl 16 Error in the HTTP2 framing layer)

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7451]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During node benchmarks tools installation, error happened:
```
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Failed to clone from https://github.com/akopytov/sysbench.git. Failed with: Encountered a bad command exit code!
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Command: 'sudo git clone https://github.com/akopytov/sysbench.git '
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Exit code: 128
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Stdout:
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Stderr:
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > Cloning into 'sysbench'...
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > error: RPC failed; curl 16 Error in the HTTP2 framing layer
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > error: 5261 bytes of body are still expected
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > fetch-pack: unexpected disconnect while reading sideband packet
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > fatal: early EOF
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > fatal: fetch-pack: invalid index-pack output
< t:2024-05-19 06:08:33,920 f:git.py          l:42   c:sdcm.utils.git       p:WARNING > 

```
This error was practically ignored and despite that benchmark executed - failing with 
```
2024-05-19 06:13:22.672: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=7b7b8f38-6845-4dda-8002-a74265ebc4e2, source=PerformanceRegressionTest.SetUp()
exception=<sdcm.utils.benchmarks.ScyllaNodeBenchmarkRunner object at 0x7f458a849510>:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 420, in run
result = future.result(time_out)
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 396, in inner
return_val = fun(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 124, in <lambda>
parallel.run(lambda x: x.run_benchmarks(), ignore_exceptions=False)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 349, in run_benchmarks
self.run_sysbench()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 317, in run_sysbench
results_dict = asdict(ScyllaNodeBenchmarkSysbenchResult(sysbench_run_result.stdout))
File "<string>", line 4, in __init__
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/benchmarks.py", line 73, in __post_init__
self.sysbench_events_per_second = float(search_result.groupdict()["eps"])
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

We should ignore benchmark errors. Or examine if these benchmarks bring us any valuable info (in which I doubt) - in that case, I'd propose removing them - speeding up the tests.

## Impact

Test failure.

## How frequently does it reproduce?

First time seen

## Installation details

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- perf-regression-latency-ubuntu-db-node-7dc31ea7-3 (100.24.118.126 | 10.12.22.80) (shards: -1)
- perf-regression-latency-ubuntu-db-node-7dc31ea7-2 (18.206.74.215 | 10.12.20.153) (shards: -1)
- perf-regression-latency-ubuntu-db-node-7dc31ea7-1 (44.222.231.141 | 10.12.22.88) (shards: -1)

OS / Image: `ami-0659dc19fdd3cf714` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test id: `7dc31ea7-511c-4099-b11e-f032214deeec`
Test name: `scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test config file(s):

- [perf-regression-latency-1TB.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/721eabb00a5158ef777b3cc81f7c683a467efb36/test-cases/performance/perf-regression-latency-1TB.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7dc31ea7-511c-4099-b11e-f032214deeec`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7dc31ea7-511c-4099-b11e-f032214deeec)
- Show all stored logs command: `$ hydra investigate show-logs 7dc31ea7-511c-4099-b11e-f032214deeec`

## Logs:
- **db-cluster-7dc31ea7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/db-cluster-7dc31ea7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/db-cluster-7dc31ea7.tar.gz)
- **sct-runner-7dc31ea7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/sct-runner-7dc31ea7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/sct-runner-7dc31ea7.tar.gz)
- **monitor-set-7dc31ea7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/monitor-set-7dc31ea7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/monitor-set-7dc31ea7.tar.gz)
- **loader-set-7dc31ea7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/loader-set-7dc31ea7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dc31ea7-511c-4099-b11e-f032214deeec/20240519_061353/loader-set-7dc31ea7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-shard-aware-1TB-test/108/)
[Argus](https://argus.scylladb.com/test/623b19d1-a201-4ed0-94a2-b42347a4d2e5/runs?additionalRuns[]=7dc31ea7-511c-4099-b11e-f032214deeec)
</details>

**Comment by fruch** [comment]
We disabled those right in perf tests, I think we can close it

**Comment by soyacz** [comment]
> We disabled those right in perf tests, I think we can close it

Not precisely, some still use it (possibly wrong backport), I created a quick fix: https://github.com/scylladb/scylla-cluster-tests/pull/7921
