### ISSUE TITLE
`apt update` fails on debian10 node, monitoring prereqs steps

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#7453]
### Issue description

Repositories update step fails with `404 Not found` issue because of non available or outdated `http://cdn-aws.deb.debian.org/debian buster-backports` repositories.

```
Command: 'sudo apt update'
Exit code: 100
Stdout:
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian buster InRelease
Hit:3 http://cdn-aws.deb.debian.org/debian buster-updates InRelease
Ign:4 http://cdn-aws.deb.debian.org/debian buster-backports InRelease
Err:5 http://cdn-aws.deb.debian.org/debian buster-backports Release
404  Not Found [IP: 2600:9000:24f3:ae00:c:a756:bac0:93a1 80]
Get:6 https://download.docker.com/linux/debian buster InRelease [53.9 kB]
Get:7 https://download.docker.com/linux/debian buster/stable amd64 Packages [52.8 kB]
Reading package lists...
Stderr:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: The repository 'http://cdn-aws.deb.debian.org/debian buster-backports Release' does not have a Release file.
```
### Impact

All Manager executions with debian10 monitoring node fail.

### How frequently does it reproduce?

100% reproduciability.

### Logs
* Argus: https://argus.scylladb.com/workspace?state=WyI5ZGM2YTczMS0zZWUyLTQ3MDUtOTcwOC0zODZjMzRmM2JjZmUiXQ (run 3)

### Possible solution

As I temporary solution without image rebuilding I can suggest to replace non-working repositories in sources.list before executing `apt update`:
```
            node.remoter.sudo(
                cmd="sed -i 's|http://cdn-aws.deb.debian.org/debian buster-backports main|"
                    "http://archive.debian.org/debian buster-backports main|g' /etc/apt/sources.list"
            )
```
This approach was tested here (https://argus.scylladb.com/workspace?state=WyI5ZGM2YTczMS0zZWUyLTQ3MDUtOTcwOC0zODZjMzRmM2JjZmUiXQ run 4).

@scylladb/qa-maintainers 
If nobody from maintainers mind, I can issue the PR with this fix.

**Comment by soyacz** [comment]
old AMI used?

**Comment by mikliapko** [comment]
> old AMI used?

This one:
ami_id_monitor: 'ami-074f8bbb689b1c1a0'  # Debian buster image - debian-10-amd64-20230601-1398, region - us-east-1

**Comment by soyacz** [comment]
maybe try finding newer one and see if it helps?
20230601 - seems like 1y ago, maybe mirrors changed.

**Comment by mikliapko** [comment]
> maybe try finding newer one and see if it helps? 20230601 - seems like 1y ago, maybe mirrors changed.

Agree, there is a newer version from 2024-04-30, will give it a try, thanks
