### ISSUE TITLE
Decommissioning when RF = nodes-num failed with "Unable to find new replica for tablet "

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#7462]
## Packages

Scylla version: `5.5.0~dev-20240515.7b41bb601c53` with build-id `411dbd445918e9235d0bd963183ec77729d09e12`

Kernel Version: `5.15.0-1060-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

create some keyspaces with RF=6 in a 6-nodes cluster:
```
< t:2024-05-16 09:30:01,177 f:stress_thread.py l:334  c:sdcm.stress_thread   p:INFO  > cassandra-stress write no-warmup n=400000 cl=QUORUM -mode native cql3 -schema keyspace=ks_truncate 'replication(strategy=NetworkTopologyStrategy,replication_factor=6)' -log interval=5 -node 10.4.1.167,10.4.0.72,10.4.2.179,10.4.1.214,10.4.0.25,10.4.1.64 -errors skip-unsupported-columns
< t:2024-05-16 09:30:03,510 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.2.59>: Running command "sudo  docker exec 1b2fb3c9bc4f1f8de27bdb277e57a42404f46359b3d30ab6801c3dae3c824791 /bin/sh -c 'echo TAG: loader_idx:1-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=RWNLNZNXM8TIRKHIDMOK; cassandra-stress write no-warmup n=400000 cl=QUORUM -mode native cql3 -schema keyspace=ks_truncate '"'"'replication(strategy=NetworkTopologyStrategy,replication_factor=6)'"'"' -log interval=5 -node 10.4.1.167,10.4.0.72,10.4.2.179,10.4.1.214,10.4.0.25,10.4.1.64 -errors skip-unsupported-columns'"...
< t:2024-05-16 09:30:03,511 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write n=400000 cl=QUORUM -mode native cql3 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=6)' -log interval=5
< t:2024-05-16 09:30:04,438 f:base.py         l:230  c:RemoteLibSSH2CmdRunner p:DEBUG >   Replication Strategy Options: {replication_factor=6}
< t:2024-05-16 09:30:05,639 f:base.py         l:230  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  09:30:05,349 Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "ks_truncate" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '6'} AND durable_writes = true;' generated server side warning(s): Tables in this keyspace will be replicated using tablets, and will not support the CDC feature (issue #16317) and LWT may suffer from issue #5251 more often. If you want to use CDC or LWT, please drop this keyspace and re-create it without tablets, by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
< t:2024-05-16 09:30:30,178 f:base.py         l:141  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.2.59>: STDERR: WARN  09:30:05,349 Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "ks_truncate" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '6'} AND durable_writes = true;' generated server side warning(s): Tables in this keyspace will be replicated using tablets, and will not support the CDC feature (issue #16317) and LWT may suffer from issue #5251 more often. If you want to use CDC or LWT, please drop this keyspace and re-create it without tablets, by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
< t:2024-05-16 09:30:30,178 f:base.py         l:143  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.2.59>: Command "sudo  docker exec 1b2fb3c9bc4f1f8de27bdb277e57a42404f46359b3d30ab6801c3dae3c824791 /bin/sh -c 'echo TAG: loader_idx:1-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=RWNLNZNXM8TIRKHIDMOK; cassandra-stress write no-warmup n=400000 cl=QUORUM -mode native cql3 -schema keyspace=ks_truncate '"'"'replication(strategy=NetworkTopologyStrategy,replication_factor=6)'"'"' -log interval=5 -node 10.4.1.167,10.4.0.72,10.4.2.179,10.4.1.214,10.4.0.25,10.4.1.64 -errors skip-unsupported-columns'" finished with status 0
< t:2024-05-16 09:30:30,180 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write n=400000 cl=QUORUM -mode native cql3 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=6)' -log interval=5
```
Decommission failed with:
```
DatabaseLogEvent
ERROR
disrupt_nodetool_decommission
2024-05-16 10:15:22.143
Received: 2024-05-16 10:15:22.061


Nemesis Information
Class: Sisyphus
Name: disrupt_nodetool_decommission
Status: Failed
Failure reason
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1296, in disrupt_nodetool_decommission
    return self._nodetool_decommission(add_node=add_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1273, in _nodetool_decommission
    self.cluster.decommission(self.target_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4909, in decommission
    node.run_nodetool("decommission", timeout=timeout, retry=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2625, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 65, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  decommission '

Exit code: 4

Stdout:



Stderr:

error executing POST request to http://localhost:10000/storage_service/decommission with parameters {}: remote replied with status code 500 Internal Server Error:
std::runtime_error (Decommission failed. See earlier errors (Rolled back: Failed to drain tablets: std::runtime_error (Unable to find new replica for tablet e1f20020-1366-11ef-a53f-29d68ea048fc:1 on bd00624d-986c-40fa-907d-2a1a480dd13c:1 when draining {bd00624d-986c-40fa-907d-2a1a480dd13c})))


```
```
2024-05-16 10:15:22.143 <2024-05-16 10:15:22.061>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=34617cb3-2ff1-4720-9b8c-badd8b2707f6: type=RUNTIME_ERROR regex=std::runtime_error line_number=2757 node=longevity-harry-2h-master-db-node-cec289e4-2
2024-05-16T10:15:22.061+00:00 longevity-harry-2h-master-db-node-cec289e4-2      !ERR | scylla[6697]:  [shard 0:strm] raft_topology - tablets draining failed with std::runtime_error (Unable to find new replica for tablet e1f20020-1366-11ef-a53f-29d68ea048fc:1 on bd00624d-986c-40fa-907d-2a1a480dd13c:1 when draining {bd00624d-986c-40fa-907d-2a1a480dd13c}). Aborting the topology operation
```
```
2024-05-16 10:15:22.554 <2024-05-16 10:15:22.506>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=34617cb3-2ff1-4720-9b8c-badd8b2707f6: type=RUNTIME_ERROR regex=std::runtime_error line_number=2770 node=longevity-harry-2h-master-db-node-cec289e4-2
2024-05-16T10:15:22.506+00:00 longevity-harry-2h-master-db-node-cec289e4-2      !ERR | scylla[6697]:  [shard 0:strm] raft_topology - Decommission failed. See earlier errors (Rolled back: Failed to drain tablets: std::runtime_error (Unable to find new replica for tablet e1f20020-1366-11ef-a53f-29d68ea048fc:1 on bd00624d-986c-40fa-907d-2a1a480dd13c:1 when draining {bd00624d-986c-40fa-907d-2a1a480dd13c}))
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-harry-2h-master-db-node-cec289e4-9 (63.32.54.243 | 10.4.0.5) (shards: -1)
- longevity-harry-2h-master-db-node-cec289e4-8 (52.17.242.7 | 10.4.1.1) (shards: -1)
- longevity-harry-2h-master-db-node-cec289e4-7 (34.254.185.72 | 10.4.3.1) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-6 (3.252.205.250 | 10.4.1.64) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-5 (18.203.237.200 | 10.4.0.25) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-4 (54.217.63.108 | 10.4.1.214) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-3 (54.194.140.127 | 10.4.2.179) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-2 (34.249.108.155 | 10.4.0.72) (shards: 2)
- longevity-harry-2h-master-db-node-cec289e4-1 (34.246.177.168 | 10.4.1.167) (shards: 2)

OS / Image: `ami-03e1418be972f5f58` (aws: undefined_region)

Test: `longevity-harry-2h-test`
Test id: `cec289e4-665b-48f1-b68d-8082fb9a63af`
Test name: `scylla-master/tablets/longevity-harry-2h-test`
Test config file(s):

- [longevity-harry-2h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/819ad1e7275003f8ac9ce6af41985635c7718797/test-cases/longevity/longevity-harry-2h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor cec289e4-665b-48f1-b68d-8082fb9a63af`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cec289e4-665b-48f1-b68d-8082fb9a63af)
- Show all stored logs command: `$ hydra investigate show-logs cec289e4-665b-48f1-b68d-8082fb9a63af`

## Logs:
- **db-cluster-cec289e4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/db-cluster-cec289e4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/db-cluster-cec289e4.tar.gz)
- **sct-runner-events-cec289e4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/sct-runner-events-cec289e4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/sct-runner-events-cec289e4.tar.gz)
- **sct-cec289e4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/sct-cec289e4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/sct-cec289e4.log.tar.gz)
- **loader-set-cec289e4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/loader-set-cec289e4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/loader-set-cec289e4.tar.gz)
- **monitor-set-cec289e4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/monitor-set-cec289e4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/monitor-set-cec289e4.tar.gz)
- **parallel-timelines-report-cec289e4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/parallel-timelines-report-cec289e4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cec289e4-665b-48f1-b68d-8082fb9a63af/20240516_113601/parallel-timelines-report-cec289e4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/longevity-harry-2h-test/15/)
[Argus](https://argus.scylladb.com/test/469ce7c7-856a-4b59-8398-5f41ffc37602/runs?additionalRuns[]=cec289e4-665b-48f1-b68d-8082fb9a63af)
</details>

**Comment by yarongilor** [comment]
@bhalevy , @fruch , is this a known issue? anyone working on that?
IIUC, one possible solution, according to tablets design, would be to add node on first place, before decommissioning a node, in case tablets are used + number-of-nodes is not bigger than KS RF.

**Comment by yarongilor** [comment]
> > @bhalevy , @fruch , is this a known issue? anyone working on that? IIUC, one possible solution, according to tablets design, would be to add node on first place, before decommissioning a node, in case tablets are used + number-of-nodes is not bigger than KS RF.
> 
> Assuming there are 6 nodes and replication_factor is set to 6, as indicated above, then it's not an issue. The system behaves as designed (with tablets).

@bhalevy , that's right, so wouldn't we want to rewrite nodetool_decommission nemesis so not to issue an error in this case?

**Comment by fruch** [comment]
@yarongilor 

@ShlomiBalalis is working on exactly this in https://github.com/scylladb/scylla-cluster-tests/pull/7457
you might want to communicate to each other what's the status of testing related to tablets

**Comment by yarongilor** [comment]
@ShlomiBalalis , one note for https://github.com/scylladb/scylla-cluster-tests/pull/7457 - in this cs-harry longevity, nodetool_decommission would never be valid to run unless adding a new node in advance (prior to decommission)

**Comment by bhalevy** [comment]
> > > @bhalevy , @fruch , is this a known issue? anyone working on that? IIUC, one possible solution, according to tablets design, would be to add node on first place, before decommissioning a node, in case tablets are used + number-of-nodes is not bigger than KS RF.
> > 
> > 
> > Assuming there are 6 nodes and replication_factor is set to 6, as indicated above, then it's not an issue. The system behaves as designed (with tablets).
> 
> @bhalevy , that's right, so wouldn't we want to rewrite nodetool_decommission nemesis so not to issue an error in this case?

I think that the test should use a smaller RF to allow decommission.
We can test that decommission fails when there are not enough nodes remaining to satisfy RF, but testing it with a scylla unit test or with a dtest is sufficient.  We don't have to test that also with SCT.

**Comment by roydahan** [comment]
Closed as Dup.
