### ISSUE TITLE
using non-shard aware configuration makes loaders unreachable

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7465]
When using `configurations/perf-loaders-non-shard-aware-config.yaml` config, loaders become unreachable (SCT master branch):
```
2024-05-10 09:29:53.959: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=b8a0fea7-7c28-468b-ba6b-c47b35c0888c, source=PerformanceRegressionTestSplitRanges.SetUp()
exception=Wait for: perf-regression-i4i-4x-650gb-ubuntu-loader-node-1151c6de-1: Waiting for SSH to be up: timeout - 500 seconds - expired
```
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- perf-regression-i4i-4x-650gb-ubuntu-db-node-1151c6de-3 (34.200.214.130 | 10.12.0.133) (shards: -1)
- perf-regression-i4i-4x-650gb-ubuntu-db-node-1151c6de-2 (44.197.187.104 | 10.12.2.228) (shards: -1)
- perf-regression-i4i-4x-650gb-ubuntu-db-node-1151c6de-1 (3.219.56.129 | 10.12.1.140) (shards: -1)

OS / Image: `ami-0b2820e6979cea8ae` (aws: undefined_region)

Test: `perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb`
Test id: `1151c6de-ad17-49c5-9870-8c487b707521`
Test name: `scylla-staging/lukasz/perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb`
Test config file(s):

- [perf-regression-throughput-650gb.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c9721ea98e0b193f8fe290bdb464ca69c30bd529/test-cases/performance/perf-regression-throughput-650gb.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1151c6de-ad17-49c5-9870-8c487b707521`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1151c6de-ad17-49c5-9870-8c487b707521)
- Show all stored logs command: `$ hydra investigate show-logs 1151c6de-ad17-49c5-9870-8c487b707521`

## Logs:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                Log links for testrun with test id 1151c6de-ad17-49c5-9870-8c487b707521                                                |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                  |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------------+
| 20240510_093005 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/1151c6de-ad17-49c5-9870-8c487b707521/20240510_093005/db-cluster-1151c6de.tar.gz        |
| 20240510_093005 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/1151c6de-ad17-49c5-9870-8c487b707521/20240510_093005/loader-set-1151c6de.tar.gz        |
| 20240510_093005 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/1151c6de-ad17-49c5-9870-8c487b707521/20240510_093005/monitor-set-1151c6de.tar.gz       |
| 20240510_093005 | sct         | https://cloudius-jenkins-test.s3.amazonaws.com/1151c6de-ad17-49c5-9870-8c487b707521/20240510_093005/sct-1151c6de.log.tar.gz           |
| 20240510_093005 | event       | https://cloudius-jenkins-test.s3.amazonaws.com/1151c6de-ad17-49c5-9870-8c487b707521/20240510_093005/sct-runner-events-1151c6de.tar.gz |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------------+

```

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb/53/)
[Argus](https://argus.scylladb.com/test/38715366-8bed-41b7-8031-d1e4df2abb0f/runs?additionalRuns[]=1151c6de-ad17-49c5-9870-8c487b707521)
</details>

**Comment by fruch** [comment]
@soyacz is this one valid ? sound an issue with keys and such, which isn't related to `perf-loaders-non-shard-aware-config.yaml` directly 
also I'm guessing this was on v14, right  ?

**Comment by soyacz** [comment]
> @soyacz is this one valid ? sound an issue with keys and such, which isn't related to `perf-loaders-non-shard-aware-config.yaml` directly also I'm guessing this was on v14, right ?

I think it's not valid anymore. Closing.
