### ISSUE TITLE
Log collection stage can fail on collection of jepsen data, on test which aren't running jepsen

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7470]
```
13:59:30  Traceback (most recent call last):
13:59:30    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1797, in <module>
13:59:30      cli.main(prog_name="hydra")
13:59:30    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
13:59:30      rv = self.invoke(ctx)
13:59:30    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
13:59:30      return _process_result(sub_ctx.command.invoke(sub_ctx))
13:59:30    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
13:59:30      return ctx.invoke(self.callback, **ctx.params)
13:59:30    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
13:59:30      return __callback(*args, **kwargs)
13:59:30    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1211, in collect_logs
13:59:30      collected_logs = collector.run()
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1678, in run
13:59:30      if result := log_collector.collect_logs(local_search_path=local_dir_with_logs):
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1294, in collect_logs
13:59:30      if jepsen_archive := self.archive_log_remotely(jepsen_node, "./jepsen-scylla", "jepsen-data"):
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 686, in archive_log_remotely
13:59:30      if not node.remoter.run(f"tar czf '{archive_name}' -C '{archive_dir}' '{log_filename}'", ignore_status=True).ok:
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
13:59:30      result = _run()
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
13:59:30      return func(*args, **kwargs)
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 603, in _run
13:59:30      self._run_pre_run(cmd, timeout, ignore_status, verbose, new_session, log_file, retry, watchers)
13:59:30    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_cmd_runner.py", line 104, in _run_pre_run
13:59:30      raise SSHConnectTimeoutError(
13:59:30  sdcm.remote.base.SSHConnectTimeoutError: Unable to run "tar czf './jepsen-data.tar.gz' -C '.' 'jepsen-scylla'": failed connecting to "10.12.1.68" during 60s
```

Job: 
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/manager-ubuntu20-sanity-test/3/

**Comment by fruch** [comment]
we probably should use some part of the configurations to skip this part
and failures in collection should break the whole thing, we should keep on to the next collector

**Comment by dimakr** [comment]
Looks like the issue in this particular run is that test runner was not able to ssh to loader node to try to collect jepsen logs..
But it was able to connect to the loader node few minutes before, when was collecting the loader-set type of logs. So the connectivity was lost somewhere in between.

In normal conditions even if there are no Jepsen logs (or any other type of logs) the log_collector instance for this type of logs would return ` There are no logs collected for jepsen-data` kind of message.

**Comment by fruch** [comment]
> Looks like the issue in this particular run is that test runner was not able to ssh to loader node to try to collect jepsen logs.. But it was able to connect to the loader node few minutes before, when was collecting the loader-set type of logs. So the connectivity was lost somewhere in between.
> 
> In normal conditions even if there are no Jepsen logs (or any other type of logs) the log_collector instance for this type of logs would return ` There are no logs collected for jepsen-data` kind of message.

well, maybe there was connectivity issue, but the issue is that it's doing a step which isn't needed.
we need to find a way to pass the information if this step is needed or not, we should have the exact same parameter passed to the clean process, as the test itself, and it should have the data if it's a jepsen test or not.

we shouldn't waste time on such a step, and regardless it shouldn't failure the log collection, even if there's a connectivity error
