### ISSUE TITLE
Wait db down during kill scylla nemesis now flaky

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7480]
## Packages

Scylla version: `5.5.0~dev-20240521.a86fb293fe4a` with build-id `280ad7c68afafd4c378ff5987ce2f66f896a74f1`

Kernel Version: `5.15.0-1062-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

in kill scylla nemesis after sending -9 signal to scylla SCT waits for port not being used before checking back port is taken back (as Scylla is restarted by systemd).
In some rare cases kernel does not update immediately `/proc/net/tcp` (possibly due unclean Scylla termination) and verification the cql port has been released fails.
Possibly it happened due recent switch from `ss` to pure verification of `/proc/net/tcp` or Scylla startup is faster recently (in this situation it took 13 seconds from kill to serving message).

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-ScyllaKillMonkey-s-db-node-b7525d31-3 (54.216.11.115 | 10.4.3.1) (shards: 2)
- longevity-5gb-1h-ScyllaKillMonkey-s-db-node-b7525d31-2 (34.242.223.177 | 10.4.3.171) (shards: 2)
- longevity-5gb-1h-ScyllaKillMonkey-s-db-node-b7525d31-1 (54.246.9.107 | 10.4.0.30) (shards: 2)

OS / Image: `ami-0ab1b7f7a0258a8aa` (aws: undefined_region)

Test: `longevity-5gb-1h-ScyllaKillMonkey-aws-test`
Test id: `b7525d31-23b7-4ca3-965c-1b88eaa93ebd`
Test name: `scylla-staging/lukasz/longevity-5gb-1h-ScyllaKillMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2e071d872bc527b24efe3c15eb55c8cd2b22983b/configurations/nemesis/longevity-5gb-1h-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b7525d31-23b7-4ca3-965c-1b88eaa93ebd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b7525d31-23b7-4ca3-965c-1b88eaa93ebd)
- Show all stored logs command: `$ hydra investigate show-logs b7525d31-23b7-4ca3-965c-1b88eaa93ebd`

## Logs:
- **db-cluster-b7525d31.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/db-cluster-b7525d31.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/db-cluster-b7525d31.tar.gz)
- **sct-runner-events-b7525d31.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/sct-runner-events-b7525d31.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/sct-runner-events-b7525d31.tar.gz)
- **sct-b7525d31.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/sct-b7525d31.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/sct-b7525d31.log.tar.gz)
- **loader-set-b7525d31.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/loader-set-b7525d31.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/loader-set-b7525d31.tar.gz)
- **monitor-set-b7525d31.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/monitor-set-b7525d31.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/monitor-set-b7525d31.tar.gz)
- **parallel-timelines-report-b7525d31.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/parallel-timelines-report-b7525d31.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7525d31-23b7-4ca3-965c-1b88eaa93ebd/20240523_154436/parallel-timelines-report-b7525d31.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/longevity-5gb-1h-ScyllaKillMonkey-aws-test/12/)
[Argus](https://argus.scylladb.com/test/38256c5f-88a2-4356-b777-c655de35e9cb/runs?additionalRuns[]=b7525d31-23b7-4ca3-965c-1b88eaa93ebd)
</details>

**Comment by soyacz** [comment]
As a solution I propose to use `sdcm.utils.common.can_connect_to` function before `wait_db_down` so kernel refresh state of /proc/net/tcp (or just stop using wait_db_down).

**Comment by fruch** [comment]
@soyacz, we need this one addressed, I failed to notice it. but I don't think we can remove the `wait_db_down` calls, we need to be sure we stopped scylla

**Comment by soyacz** [comment]
WDYT of checking CQL port from sct-runner side, by trying to establish with example code:
```
def is_port_accepting_connections(host: str, port: int) ->bool
  with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
      result = s.connect_ex((host, port))
      return result == 0 
  return False
```
I didn't try it yet (and requires some error handling).

**Comment by fruch** [comment]
> WDYT of checking CQL port from sct-runner side, by trying to establish with example code:
> ```
> def is_port_accepting_connections(host: str, port: int) ->bool
>   with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
>       result = s.connect_ex((host, port))
>       return result == 0 
>   return False
> ```
> I didn't try it yet (and requires some error handling).

The downside is that it might generate errors in scylla log

**Comment by soyacz** [comment]
> > WDYT of checking CQL port from sct-runner side, by trying to establish with example code:
> > ```
> > def is_port_accepting_connections(host: str, port: int) ->bool
> >   with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
> >       result = s.connect_ex((host, port))
> >       return result == 0 
> >   return False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I didn't try it yet (and requires some error handling).
> 
> The downside is that it might generate errors in scylla log

ok, so maybe to use it to verify down only?

**Comment by fruch** [comment]
I think that for specific cases like this one that we know the down check isn't good enough, we can skip the down check.

I.e. one case at a time, I thought you want to stop the down check completely in all cases...

**Comment by fruch** [comment]
> I think for this case it was checking is down because it was causing false positive in waiting up (I believe with previous `ss` tool we would have the same issue).
> 
> We have 2 places where we use  `kill -9` and one `kill -3` in coredump generation code. For these, we might just need `sleep(30)` instead waiting db down (as anyway it is down due these signals)

I don't understand why sleep is needed ?

**Comment by fruch** [comment]
@soyacz can we try one of the options suggested here ?

**Comment by soyacz** [comment]
Ok, I'll try to create PR today
