### ISSUE TITLE
Send perf emails also for the first job run

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7495]
After creating a new job for perf test, the first successful run does not send email because there's no reference results (based on jenkins job path).
It's very inconvenient, as still there are valid results - just without comparison to previous run.

In that case, we should skip comparison and send email with `N/A` values instead of failing sending email.

**Comment by fruch** [comment]
@soyacz isn't the change I'm doing with pinning the jobs to compare with gonna help with this ? 

i.e. only left case is when it's the first run of a completely fresh case

**Comment by soyacz** [comment]
> @soyacz isn't the change I'm doing with pinning the jobs to compare with gonna help with this ?
> 
> i.e. only left case is when it's the first run of a completely fresh case

Yes, the change will help with this one (assuming we have a default one to compare)

**Comment by fruch** [comment]
We agreed we don't need, and we are o.k. with having at least two run to get results on new jobs
