### ISSUE TITLE
[DatabaseLogEvent] SCT catch INFO DB log as ERROR by regex=Failed to load schema version

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#7556]
## Packages

Scylla version: `6.0.0~rc2-20240602.cbf47319c1f7` with build-id `7d1275fde6e643dcd526b94b83688a6b636ba1f0`

Kernel Version: `5.15.0-1062-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

DatabaseLogEvent ERROR on disrupt_restart_then_repair_node
```
2024-06-03 04:06:55.176 <2024-06-03 04:06:55.103>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=b230cba5-85e1-49db-982c-affecf5d629d: type=SCHEMA_FAILURE regex=Failed to load schema version line_number=6071 node=alternator-3h-6-0-db-node-5a66ab34-4
2024-06-03T04:06:55.103+00:00 alternator-3h-6-0-db-node-5a66ab34-4     !INFO | scylla[3810]:  [shard 11:stmt] rpc - client 10.12.10.100:49305 msg_id 14:  exception "Failed to load schema version 899e3752-215c-11ef-8450-470041a9e27d" in no_wait handler ignored
```
## Impact

STC job failed

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-6-0-db-node-5a66ab34-8 (54.204.219.251 | 10.12.11.118) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-7 (54.167.45.150 | 10.12.8.149) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-6 (54.80.202.177 | 10.12.8.164) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-5 (54.242.198.248 | 10.12.10.100) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-4 (54.172.196.251 | 10.12.8.241) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-3 (3.94.119.25 | 10.12.9.210) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-2 (3.90.250.35 | 10.12.8.105) (shards: 14)
- alternator-3h-6-0-db-node-5a66ab34-1 (3.80.143.131 | 10.12.8.113) (shards: 14)

OS / Image: `ami-0c7e1bfe45f4c1655` (aws: undefined_region)

Test: `longevity-alternator-3h-test`
Test id: `5a66ab34-ef29-4bf6-96d5-61462c409be9`
Test name: `scylla-6.0/alternator/longevity-alternator-3h-test`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/95bd4ffdf448a32a7089c698a551b82ce62f927d/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5a66ab34-ef29-4bf6-96d5-61462c409be9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5a66ab34-ef29-4bf6-96d5-61462c409be9)
- Show all stored logs command: `$ hydra investigate show-logs 5a66ab34-ef29-4bf6-96d5-61462c409be9`

## Logs:
- **db-cluster-5a66ab34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/db-cluster-5a66ab34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/db-cluster-5a66ab34.tar.gz)
- **sct-runner-events-5a66ab34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/sct-runner-events-5a66ab34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/sct-runner-events-5a66ab34.tar.gz)
- **sct-5a66ab34.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/sct-5a66ab34.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/sct-5a66ab34.log.tar.gz)
- **loader-set-5a66ab34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/loader-set-5a66ab34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/loader-set-5a66ab34.tar.gz)
- **monitor-set-5a66ab34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/monitor-set-5a66ab34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/monitor-set-5a66ab34.tar.gz)
- **parallel-timelines-report-5a66ab34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/parallel-timelines-report-5a66ab34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5a66ab34-ef29-4bf6-96d5-61462c409be9/20240603_070900/parallel-timelines-report-5a66ab34.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.0/job/alternator/job/longevity-alternator-3h-test/8/)
[Argus](https://argus.scylladb.com/test/8cdbe81d-b64f-4086-8260-b57a46b32529/runs?additionalRuns[]=5a66ab34-ef29-4bf6-96d5-61462c409be9)
</details>

**Comment by temichus** [comment]
@kostja, Could you please confirm that this log message should not be considered as ERROR in SCT and should be ignored

**Comment by kbr-scylla** [comment]
Where did the idea come from that this is not an error? "Failed to load schema version" looks serious. Should probably be an issue in Scylla repo, not here.

**Comment by fruch** [comment]
just saying that context is king in those

we had plenty of scary looking error message, that ended up being acceptable in some conditions

but rule of thumb, first report it on scylla core, and only when there a clear agreement, waiver it on SCT, we can also use `SkipPerIssue` for things that were agree to defer a fix for them. (same as are using require in dtest)

**Comment by roydahan** [comment]
IIRC there was an issue about it and someone said to have an issue in SCT to ignore this error.
