### ISSUE TITLE
Logs and screenshots are not shown in Argus

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7583]
in case of failure during collect-log stage, logs and screenshots are not updated in Argus and we need to run collect-logs manually and paste to issues (which in turn doesn't look right or requires copy-paste procedure to download log)
We should update argus as soon as log is collected instead of waiting to the end.

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f417745e-0067-4479-95ee-24c9182267ce`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f417745e-0067-4479-95ee-24c9182267ce)
- Show all stored logs command: `$ hydra investigate show-logs f417745e-0067-4479-95ee-24c9182267ce`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scylla-master-perf-regression-latency-650gb-grow-shrink/24/)
[Argus](https://argus.scylladb.com/test/18619447-834b-4c2c-9a77-c87e54a099a8/runs?additionalRuns[]=f417745e-0067-4479-95ee-24c9182267ce)
</details>

**Comment by fruch** [comment]
@soyacz @k0machi 

from my POV:
https://github.com/scylladb/scylla-cluster-tests/pull/7568

is good enough to close this one

**Comment by fruch** [comment]
> > @soyacz @k0machi
> > from my POV: #7568
> > is good enough to close this one
> 
> from my POV it's not, I'd rather see an option to 'show-logs' `--update-argus` option

you'll have to elaborate more on this one...

**Comment by k0machi** [comment]
Maybe it would be better to have separate command to just update argus logs that would update argus logs by using `show-logs` internally? Just from POV of having an argument that would modify the behaviour of a command this much.

**Comment by fruch** [comment]
@k0machi please followup with this one
