### ISSUE TITLE
Create cleanup process for aliases 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7611]
Seems like from time to time, we reach to max KMS key aliases:
```
2024-06-09 19:45:35.002: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=6a64451e-8543-4759-b64a-1ed36f94b91e, source=LWTLongevityTest.SetUp()
exception=An error occurred (LimitExceededException) when calling the CreateAlias operation: Aliases per key quota for this account in this region is 50, current usage is 60.
```

not sure if it's cause we have 50 enterprise test running at the same time, or we have leftovers from test that are wasn't cleaned properly

to be on the safe side, first lets try to make a cleanup script for unused/old aliases into `clean_aws.py` 

and then see how we ask for bigger quote as needed

**Comment by vponomaryov** [comment]
@fruch 

SCT reuses existing KMS keys based on tags.
1 test run - 1 alias per region.

If limit for 50 aliases gets exceeded then it means there 50+ test runs running in parallel in the same region.

It can be mitigated by either increasing the alias limit (I don't see problem in it, it is just kind of label/tag) or run test runs in different regions.

I am leaning to the first option.

**Comment by fruch** [comment]
> @fruch
> 
> SCT reuses existing KMS keys based on tags. 1 test run - 1 alias per region.
> 
> If limit for 50 aliases gets exceeded then it means there are 50+ test runs running in parallel in the same region.
> 
> It can be mitigated by either increasing the alias limit (I don't see problem in it, it is just kind of label/tag) or run test runs in different regions.
> 
> I am leaning to the first option.

can you check if we have alias right now which are not part of an ongoing test ?, if yes, we need a cleanup process.

we can ask AWS to raise the limit, but it would take time, and we if we sometimes leak those for what ever reason, we'll hit it again.

**Comment by fruch** [comment]
seems like this is `Aliases per CMK` I've asked to raise it to 200

**Comment by vponomaryov** [comment]
no need to raise quota.

I know what to do. 

For now I cleaned up bigger part of garbage manually in the most affected region - `us-east-1`.

**Comment by vponomaryov** [comment]
PR:
- https://github.com/scylladb/scylla-cluster-tests/pull/7699
