### ISSUE TITLE
New monitoring 4.7 doesn't have loaders OS metrics which contain ":port" info in the target

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#7626]
### Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Recently was merged PR https://github.com/scylladb/scylla-cluster-tests/pull/7294 where we switch from using `monitoring-4.6` to `monitoring-4.7`.
And the new version has bug where OS metrics graphs don't show loaders nodes info (the ones with port suffix):

![Screenshot from 2024-06-10 17-49-29](https://github.com/scylladb/scylla-cluster-tests/assets/3796058/9e2d93e7-c44e-4087-815c-4d8c88d221fa)
![Screenshot from 2024-06-10 17-49-47](https://github.com/scylladb/scylla-cluster-tests/assets/3796058/1b5cc8c1-70fb-4fd3-8805-0587c047b3a8)

#### Steps to Reproduce

1. Run a longevity test using latest SCT
2. Wait while test starts meaning all nodes must report it's nodes info.
3. See that loader don't appear in OS metrics diagrams

**Expected behavior:** OS metrics should appear for all targets, not only for those which don't have port suffix.

**Actual behavior:** part of targets is absent in the OS metrics diagrams.

### Impact

Lack of monitoring info

### How frequently does it reproduce?

1/1

### Installation details

SCT Version: [branch or hash tag you are working on]
Scylla version (or git commit hash): [branch or commit hash]

### Logs
* test_id: c19f994e-13ed-4ae4-be98-47c24e7d4a2a
* job log: https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-10gb-simulated-multidc/17

**Comment by vponomaryov** [comment]
Alive yet monitoring: http://13.51.206.7:3000/d/OS-2024-1/os-metrics?orgId=1&var-cluster=&var-dc=All&var-node=All&var-by=instance&var-monitor_disk=All&var-monitor_network_interface=docker0&var-mount_point=%2Fvar%2Flib%2Fscylla&var-scylla_version=2024.1&var-monitoring_version=4.7.2&from=1718025062487&to=1718028039930

@fruch , @soyacz ^

**Comment by soyacz** [comment]
Aater reverting we won't see the tablets and other fixes
Issue is with `, job="node_exporter"` included in the filter. Switching it to this, make it visible :
`1-sum(rate(node_cpu_seconds_total{instance=~"[[node]]",cluster="$cluster", dc=~"$dc", mode="idle"}[3m])) by ([[by]])/count(node_cpu_seconds_total{instance=~"[[node]]",cluster="$cluster", dc=~"$dc", mode="idle"}) by ([[by]])`

**Comment by fruch** [comment]
@amnonh 

please advise, on how we can show target that has port configured ? or it's the square brackets which are the issue (we will have the when ipv6 would be used) ?

**Comment by amnonh** [comment]
The root cause is the job name, the dashboard limits the metrics for ```job="node_exporter"``` but this is a QA job, can you place those nodes under the node_exporter job?

**Comment by vponomaryov** [comment]
> The root cause is the job name, the dashboard limits the metrics for `job="node_exporter"` but this is a QA job, can you place those nodes under the node_exporter job?
> 
> The reason for the extra filter, a customer had issues with unrelated jobs using the same 3100 port. I can also make the filter more general (e.g. node_exporter.*) so node_exporter will be a prefix and not exact match

More general filter sounds more flexible. Would be good to have it this way.

**Comment by amnonh** [comment]
I've opened https://github.com/scylladb/scylla-monitoring/issues/2317

**Comment by vponomaryov** [comment]
> @vponomaryov we still have this issue ? (now we moved to monitor 4.8)

The 4.7 was successfully work-arounded as it is said here: https://github.com/scylladb/scylla-cluster-tests/pull/7627#issuecomment-2168775769
I didn't try out the `4.8` from this issue point of view.

**Comment by fruch** [comment]
> > @vponomaryov we still have this issue ? (now we moved to monitor 4.8)
> 
> The 4.7 was successfully work-arounded as it is said here: https://github.com/scylladb/scylla-cluster-tests/pull/7627#issuecomment-2168775769
> I didn't try out the `4.8` from this issue point of view.

So we can close this one ?

**Comment by vponomaryov** [comment]
> > > @vponomaryov we still have this issue ? (now we moved to monitor 4.8)
> > 
> > 
> > The 4.7 was successfully work-arounded as it is said here: [#7627 (comment)](https://github.com/scylladb/scylla-cluster-tests/pull/7627#issuecomment-2168775769)
> > I didn't try out the `4.8` from this issue point of view.
> 
> So we can close this one ?

Yes. We can reopen if it appears in 4.8
