### ISSUE TITLE
Provision step failure does not stop the test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7628]
In general, when provision step in jenkins fails we don't see it (marked as green) and test continues - later often failing anyway when SCT tries to provision resources.
This is wrong as pipeline could fail fast, skipping all the next steps.
Another problem is that this behavior hides problems with regressions in provision step.

Bonus points when fixing this issue:
When failing on provision, should gather more detailed logs so issues are easier to investigate.

**Comment by vponomaryov** [comment]
Commit that fixes this bug is one of 2 commits in the existing PR here:
- https://github.com/scylladb/scylla-cluster-tests/pull/7541

**Comment by vponomaryov** [comment]
Fixed here: https://github.com/scylladb/scylla-cluster-tests/pull/7541/commits/9dfea78f5b33f86805ae88bb4b6859995507a1fd
