### ISSUE TITLE
Overview screenshot is broken in Argus view

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7660]
![image](https://github.com/scylladb/scylla-cluster-tests/assets/18242288/cee3856f-c849-42da-9327-051b2e8aba8a)

But when looking into monitoring logs, screenshot there looks fine.

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-892914d3-8 (18.209.49.78 | 10.12.8.210) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-7 (3.90.239.80 | 10.12.9.133) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-6 (18.209.17.34 | 10.12.10.115) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-5 (34.235.139.229 | 10.12.8.166) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-4 (54.83.125.111 | 10.12.10.128) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-3 (18.234.196.137 | 10.12.10.253) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-2 (3.88.179.206 | 10.12.9.60) (shards: 14)
- longevity-100gb-4h-master-db-node-892914d3-1 (54.234.21.25 | 10.12.8.97) (shards: 14)

OS / Image: `ami-00ccec2077de86508` (aws: undefined_region)

Test: `longevity-100gb-4h-test`
Test id: `892914d3-44ab-414b-88a1-cc0235f31846`
Test name: `scylla-master/longevity/longevity-100gb-4h-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ef159f51300dcee27f8840519da803dabe1d54ef/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 892914d3-44ab-414b-88a1-cc0235f31846`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=892914d3-44ab-414b-88a1-cc0235f31846)
- Show all stored logs command: `$ hydra investigate show-logs 892914d3-44ab-414b-88a1-cc0235f31846`

## Logs:
- **db-cluster-892914d3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/db-cluster-892914d3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/db-cluster-892914d3.tar.gz)
- **sct-runner-events-892914d3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/sct-runner-events-892914d3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/sct-runner-events-892914d3.tar.gz)
- **sct-892914d3.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/sct-892914d3.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/sct-892914d3.log.tar.gz)
- **loader-set-892914d3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/loader-set-892914d3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/loader-set-892914d3.tar.gz)
- **monitor-set-892914d3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/monitor-set-892914d3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/monitor-set-892914d3.tar.gz)
- **parallel-timelines-report-892914d3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/parallel-timelines-report-892914d3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/892914d3-44ab-414b-88a1-cc0235f31846/20240615_040833/parallel-timelines-report-892914d3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/859/)
[Argus](https://argus.scylladb.com/test/f05fea04-eb74-4961-94fb-f71c67df52cb/runs?additionalRuns[]=892914d3-44ab-414b-88a1-cc0235f31846)
</details>

**Comment by fruch** [comment]
I just noticed that as well, it's not just in Argus.

I think monitoring stack 4.7 has broke something and we didn't noticed it

Anyhow we should try to bisect when it's started to break
Maybe setting back the dimensions for the snapshot, I used the automatic height, Aland it worked on 4.6

**Comment by fruch** [comment]
@k0machi can you give it a look, and first try to identify when it started to break

And then we can figure how to address it

**Comment by fruch** [comment]
And also SCT dashboard is cut, and doesn't show fully as it should

**Comment by k0machi** [comment]
I have taken a look at screenshots from recent runs and I've noticed that sometimes dashboards "work" but are empty and SOME screenshots contain a "failed to authenticate against an endpoint" toast in the top right. Has there been any updates to monitoring stack collecting in SCT recently? I'll see what's so different between monitoring stack logs collector and screenshot collector. My suspicion - since screenshot collection happens in teardown it may be missing something that was recently changed inside logs collector. Will check.

**Comment by fruch** [comment]
My bad I've mentioned the wrong issue to be closed

I've figured this one out and did a workaround 

https://github.com/scylladb/scylla-cluster-tests/pull/7704

We still need to see if monitoring 4.8 is fixing this issue
