### ISSUE TITLE
Performance tests with vnodes

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7706]
After switching tablets to default, we no longer test vnodes.
As agreed on perf meeting, we want to run it bi-weekly. 
New jobs/configurations/triggers must be prepared for it.

**Comment by fruch** [comment]
we switch all of the tests back to vnodes (i.e. no tablets),
and tablets cases would be introduced later (first elasticity case)

we have the cases with tablets, but no cadence was agreed
@roydahan, what do you suggest ?

**Comment by roydahan** [comment]
Every 3 weeks.

**Comment by fruch** [comment]
we start triggering the tablet case every 3 weeks, closing this one
