### ISSUE TITLE
Perf test latency with nemesis runs with simple replication strategy

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7707]
The reason why perf test with operations doesn't use tablets is that `test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml` forces simple replication strategy which is not supported by tablets.

We didn't backport https://github.com/scylladb/scylla-cluster-tests/commit/3bac923a7ce9849817badc5d644b0517cb50e52b to perf branch.

**Comment by fruch** [comment]
solved when we moved to v15
