### ISSUE TITLE
Stop testing the replace_address_first_boot/replace_address options

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-cluster-tests#7741]
Since https://github.com/scylladb/scylladb/commit/1577aa8098cac7bc2ef0b7f9523044383e14896e (5.2), the `replace_address` and `replace_address_first_boot` options are deprecated and their usage is discouraged, and warned about (when used).
Instead, the user should use the `replace_node_first_boot` which states the replaced node's host_id rather than its ip address.

**Comment by Lakshmipathi** [comment]
@bhalevy Should we completely remove this option or error (log.error) when its used? https://github.com/scylladb/scylla-cluster-tests/pull/7918

**Comment by vponomaryov** [comment]
It doesn't get tested with Scylla versions which support host-id replacement.
Code example from the SCT code:

```
@property
def is_replacement_by_host_id_supported(self):
    if self.is_enterprise:
        return ComparableScyllaVersion(self.scylla_version) > '2022.3.0~dev'
    return ComparableScyllaVersion(self.scylla_version) > '5.2.0~dev'

```
And it's usage:
```
        if verification_node.is_replacement_by_host_id_supported:
            new_node.replacement_host_id = host_id
        else:
            new_node.replacement_node_ip = old_node_ip
```

We still run/test old scylla versions.
So, this code should not be removed while we have customers running old Scylla.

**Comment by bhalevy** [comment]
> It doesn't get tested with Scylla versions which support host-id replacement.

That should be good enough for removing support for the legacy options in scylla.

**Comment by bhalevy** [comment]
So closing this issue based on the above.
