### ISSUE TITLE
Manager sanity for ubuntu20 fails `/tmp/ssl_conf/db.crt: no such file or directory` due to recent encryption changes

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#7755]
ubuntu20-sanity-test for Manager fails with the issue that has been already fixed [here](https://github.com/scylladb/scylla-cluster-tests/pull/7691) for ubuntu 22.

```
17:57:54  2024-06-25 15:57:44.902: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=fe786b70-edc6-462d-adc5-5116646921a3, source=MgmtCliTest.test_manager_sanity (mgmt_cli_test.MgmtCliTest) [Client Encryption]() message=Traceback (most recent call last):
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1131, in run
17:57:54  res = self.manager_node.remoter.sudo(f"sctool {cmd}")
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
17:57:54  return self.run(cmd=cmd,
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
17:57:54  result = _run()
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
17:57:54  return func(*args, **kwargs)
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
17:57:54  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
17:57:54  result = connection.run(**command_kwargs)
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
17:57:54  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
17:57:54  raise UnexpectedExit(result)
17:57:54  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
17:57:54  Command: 'sudo sctool cluster update -c 3b5061c2-8a6a-46e8-b086-0a349d869a75 --ssl-user-cert-file /tmp/ssl_conf/test.crt --ssl-user-key-file /tmp/ssl_conf/test.key  --force-non-ssl-session-port'
17:57:54  Exit code: 1
17:57:54  Stdout:
17:57:54  Stderr:
17:57:54  Error: open /tmp/ssl_conf/test.crt: no such file or directory
17:57:54  The above exception was the direct cause of the following exception:
17:57:54  Traceback (most recent call last):
17:57:54  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 364, in test_manager_sanity
17:57:54  self.test_client_encryption()
17:57:54  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 687, in test_client_encryption
17:57:54  mgr_cluster.update(
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 721, in update
17:57:54  self.sctool.run(cmd=cmd, is_verify_errorless_result=True)
17:57:54  File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1134, in run
17:57:54  raise ScyllaManagerError(f"Encountered an error on sctool command: {cmd}: {ex}") from ex
17:57:54  sdcm.mgmt.common.ScyllaManagerError: Encountered an error on sctool command: cluster update -c 3b5061c2-8a6a-46e8-b086-0a349d869a75 --ssl-user-cert-file /tmp/ssl_conf/test.crt --ssl-user-key-file /tmp/ssl_conf/test.key  --force-non-ssl-session-port: Encountered a bad command exit code!
17:57:54  Command: 'sudo sctool cluster update -c 3b5061c2-8a6a-46e8-b086-0a349d869a75 --ssl-user-cert-file /tmp/ssl_conf/test.crt --ssl-user-key-file /tmp/ssl_conf/test.key  --force-non-ssl-session-port'
17:57:54  Exit code: 1
17:57:54  Stdout:
17:57:54  Stderr:
17:57:54  Error: open /tmp/ssl_conf/test.crt: no such file or directory
```

Jenkins job - https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/ubuntu20-sanity-test/599/

It seems like there is a dependency on specific distro in this code.

### Issue description

- [x] This issue is a regression.

### Impact

Not high. Only ubuntu20-sanity-test is blocked.

### How frequently does it reproduce?

Every time.

### Installation details

SCT commit sha: 20d1ce0bb354bd3dc288431c2696e205d84c1231

**Comment by fruch** [comment]
seems like `enable_client_encrypt` and `disable_client_encrypt` are handling scylla only

while the code for copying the keys to nodes, looks the the configuration before it being changed by the test.

hence keys are not synced into node, and we should add the code for them to sync the key, if configuring client encryption

**Comment by fruch** [comment]
I think the `if self.params.get('use_prepared_loaders'):` should be remove, and if client encryption is enable, always to sync the keys, it was assuming db nodes get it in other way (which didn't happen in this case, cause of "live" reconfiguration)

**Comment by fruch** [comment]
still not clear to me how some tests do pass, I wouldn't expect anything different between distros for this one

**Comment by dimakr** [comment]
Turned out there is a small difference during runtime between ubuntu distros, particularly when doing this check - [remote.use_rsync() check](https://github.com/scylladb/scylla-cluster-tests/blob/60cddb41a438512ce1abab6006966b33bbaf2bd8/sdcm/remote/remote_base.py#L357:)
- on ubuntu22 the check returns false and the [remoter.send_file() call](https://github.com/scylladb/scylla-cluster-tests/blob/60cddb41a438512ce1abab6006966b33bbaf2bd8/sdcm/cluster.py#L2289) falls back to using scp approach to send files
- on ubuntu20 the check returns true and uses rsync approach

send_files works well if the src and dst directories names are the same (e.g. `ssl_conf`), so the directory with the same name is created on dst.
But after rework of how we create SSL/TLS certs in SCT, we now create certs on sct_runner in separate node-specific subdirs, e.g. `ssl_conf/x.x.x.x` (where x.x.x.x is node ip). Sending this src subdir content is done a bit differently - `ssl_conf` directory is created on dst and then inside it a `x.x.x.x` directory is created.
That's why test was not able to find `test.crt` in `/tmp/ssl_conf` on ubuntu20 config - it was in `tmp/ssl_conf/x.x.x.x` dir.

I'll add a fix in moment.

**Comment by dimakr** [comment]
The weird thing is that ubuntus 20 and 22 both have rsync preinstalled in them. The issue is somewhere in how `sdcm/remote/remote_base.py::RemoteCmdRunnerBase._use_rsync` class attribute is set when the class is instantiated  - in case of ubuntu22 a RemoteLibSSH2CmdRunner instance has this attribute value set to False, even though the instance itself was not updating the attribute anywhere.
I'll add this to my backlog to investigate later.

**Comment by vponomaryov** [comment]
> The weird thing is that ubuntus 20 and 22 both have rsync preinstalled in them. The issue is somewhere in how `sdcm/remote/remote_base.py::RemoteCmdRunnerBase._use_rsync` class attribute is set when the class is instantiated - in case of ubuntu22 a RemoteCmdRunnerBase instance has this attribute value set to False, even though the instance itself was not updating the attribute anywhere. I'll add this to my backlog to investigate later.

Probably the diff is in the python versions -> `3.8` in ubuntu20 and `3.10` in ubuntu22.

You can test different python versions using `tox` tool:
```tox -e py38 -- `pwd`/sct.py ...```
and
```tox -e py310 -- `pwd`/sct.py ...```

**Comment by fruch** [comment]
> > The weird thing is that ubuntus 20 and 22 both have rsync preinstalled in them. The issue is somewhere in how `sdcm/remote/remote_base.py::RemoteCmdRunnerBase._use_rsync` class attribute is set when the class is instantiated - in case of ubuntu22 a RemoteCmdRunnerBase instance has this attribute value set to False, even though the instance itself was not updating the attribute anywhere. I'll add this to my backlog to investigate later.
> 
> Probably the diff is in the python versions -> `3.8` in ubuntu20 and `3.10` in ubuntu22.
> 
> You can test different python versions using `tox` tool: `` tox -e py38 -- `pwd`/sct.py ... `` and `` tox -e py310 -- `pwd`/sct.py ... ``

I'm not sure we use the python on the host, during the process of copying files...

**Comment by dimakr** [comment]
PR to properly sync files to manager node: https://github.com/scylladb/scylla-cluster-tests/pull/7821
