### ISSUE TITLE
Scylla Enterprise upgrade with SLA runs with OSS base version and fails after rollback

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7777]
## Packages

Base Scylla version: `5.4.6-20240418.10f137e367e3` with build-id `c5211ffd45b36d1a7a10d0d43541e3ca1dae4d9f`
Target Scylla version (or git commit hash): `2024.1.5-20240606.842c1b55430b` with build-id `81ea194c3fbe195fe72806c38c0d8928beb75ead`

Kernel Version: `6.5.0-1020-gcp`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

rolling-upgrade-with-sla-test uses OSS as base version and still creates service levels. This is not failing and possibly has no effect as SLA is not supported by OSS. Problem starts when node gets upgraded to Enterprise and rolled back to OSS. In that case it freezes on boot with recurring db node log messages:
`service_level_controller - service level "sl_0" was updated to 1000 shares`

this causes test to fail on waiting for db up.
I believe this scenario of setting SLA on OSS and upgrading to Enterprise is not supported and we should not run this test at all.

## Impact

Failed test.

## How frequently does it reproduce?

Since upgrade from 5.4.6 to 2024.1.5. Previously was working.

## Installation details

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-sla--ubuntu-jammy-db-node-3eaa07f7-0-3 (35.196.5.98 | 10.142.0.219) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-3eaa07f7-0-2 (34.23.53.197 | 10.142.0.211) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-3eaa07f7-0-1 (34.148.156.61 | 10.142.0.204) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts` (gce: undefined_region)

Test: `rolling-upgrade-with-sla-test`
Test id: `3eaa07f7-cebb-4401-9afe-c78cf57f6da8`
Test name: `enterprise-2024.1/rolling-upgrade/rolling-upgrade-with-sla-test`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a7c6330ed17734d94113d0fae144a938f035064a/test-cases/upgrades/generic-rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3eaa07f7-cebb-4401-9afe-c78cf57f6da8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3eaa07f7-cebb-4401-9afe-c78cf57f6da8)
- Show all stored logs command: `$ hydra investigate show-logs 3eaa07f7-cebb-4401-9afe-c78cf57f6da8`

## Logs:
- **db-cluster-3eaa07f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/db-cluster-3eaa07f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/db-cluster-3eaa07f7.tar.gz)
- **sct-runner-events-3eaa07f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/sct-runner-events-3eaa07f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/sct-runner-events-3eaa07f7.tar.gz)
- **sct-3eaa07f7.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/sct-3eaa07f7.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/sct-3eaa07f7.log.tar.gz)
- **loader-set-3eaa07f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/loader-set-3eaa07f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/loader-set-3eaa07f7.tar.gz)
- **monitor-set-3eaa07f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/monitor-set-3eaa07f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3eaa07f7-cebb-4401-9afe-c78cf57f6da8/20240606_224409/monitor-set-3eaa07f7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.1/job/rolling-upgrade/job/rolling-upgrade-with-sla-test/14/)
[Argus](https://argus.scylladb.com/test/59a1bbb1-d21d-492b-a2f5-9294e04f5db7/runs?additionalRuns[]=3eaa07f7-cebb-4401-9afe-c78cf57f6da8)
</details>

**Comment by fruch** [comment]
@soyacz it's not defined anywhere that it's not supported, so until then it should be working.

on previous version it did work, this should be raise as core issue

**Comment by soyacz** [comment]
> @soyacz it's not defined anywhere that it's not supported, so until then it should be working.
> 
> on previous version it did work, this should be raise as core issue

Ok, raised, let's see what happens: https://github.com/scylladb/scylladb/issues/19568

**Comment by fruch** [comment]
not a SCT issue for sure
