### ISSUE TITLE
AuthenticationError caused by enabled logging is not filtered out when upgrading from 2022.2 to 2024.1

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylla-cluster-tests#7861]
There is a known issue of the error from cassandra-stress:
```
ERROR 05:52:00,907 Authentication error on host ip-10-4-0-166.eu-west-1.compute.internal/10.4.0.166:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0
```
that occurs on scenarios of rolling upgrades when audit is enabled, like here https://argus.scylladb.com/test/ec795529-c9e8-419b-9160-ad106aba85a6/runs?additionalRuns[]=74bd4cd5-dfc6-484a-a61c-fff05b646040.

By default audit is disabled in 2023.1 by https://github.com/scylladb/scylla-enterprise/pull/3094, but is not in 2022.2.

As per the https://github.com/scylladb/scylla-cluster-tests/pull/6590 and https://github.com/scylladb/scylla-cluster-tests/pull/7264 a filter was added to reduce severity of this error event, under SkipPerIssues condition. And skip tags `sct-2023.1-skip` and `sct-2024.1-skip` were added to the https://github.com/scylladb/scylla-enterprise/issues/3148 for that.

As the audit is not disabled in 2022.2 and skip tag is not added for this release the issue continues to periodically fire during rolling upgrades.
We need to tag the issue: https://github.com/scylladb/scylla-enterprise/issues/3148 with sct-2022.2-skip.
Or to find a way to apply filter also based on the initial version.

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

### Impact

2022.2 to 2024.1 rolling-upgrade scenarios are periodically failing.

### How frequently does it reproduce?

Periodically during upgrades from 2022.2 to 2024.1

## Installation details

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-74bd4cd5-4 (54.247.147.66 | 10.4.0.45) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-74bd4cd5-3 (54.216.73.210 | 10.4.0.166) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-74bd4cd5-2 (34.243.197.97 | 10.4.2.32) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-74bd4cd5-1 (3.251.86.13 | 10.4.2.22) (shards: 7)

OS / Image: `ami-07dcbdfe4d03fe54f` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `74bd4cd5-dfc6-484a-a61c-fff05b646040`
Test name: `enterprise-2024.1/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6171c64cdaed2a34ee55a922fac088764ebe7bf7/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 74bd4cd5-dfc6-484a-a61c-fff05b646040`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=74bd4cd5-dfc6-484a-a61c-fff05b646040)
- Show all stored logs command: `$ hydra investigate show-logs 74bd4cd5-dfc6-484a-a61c-fff05b646040`

## Logs:
- **db-cluster-74bd4cd5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/db-cluster-74bd4cd5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/db-cluster-74bd4cd5.tar.gz)
- **sct-runner-events-74bd4cd5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/sct-runner-events-74bd4cd5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/sct-runner-events-74bd4cd5.tar.gz)
- **sct-74bd4cd5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/sct-74bd4cd5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/sct-74bd4cd5.log.tar.gz)
- **loader-set-74bd4cd5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/loader-set-74bd4cd5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/loader-set-74bd4cd5.tar.gz)
- **monitor-set-74bd4cd5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/monitor-set-74bd4cd5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/74bd4cd5-dfc6-484a-a61c-fff05b646040/20240704_082924/monitor-set-74bd4cd5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.1/job/rolling-upgrade/job/rolling-upgrade-ami-test/18/)
[Argus](https://argus.scylladb.com/test/ec795529-c9e8-419b-9160-ad106aba85a6/runs?additionalRuns[]=74bd4cd5-dfc6-484a-a61c-fff05b646040)
</details>

**Comment by fruch** [comment]
@dimakr is this still happening ?

**Comment by fruch** [comment]
the label is in place, and test are o.k. since them

**Comment by dimakr** [comment]
For some reason, the enterprise issue https://github.com/scylladb/scylla-enterprise/issues/3148 for which we created and added `sct-2022.2-skip` label is not tagged anymore (as a result the issue describe here started appear again on upgrades from 2022.2).

**Comment by dimakr** [comment]
@fruch I see that you've added label to the enterprise issue on Sep 11 and that was the latest update there, no updates of who/when removed the label. And it seems like the label was just deleted as it doesn't appear in the list of available labels.
Maybe you know about this change (why the label was removed)?

**Comment by fruch** [comment]
> [@fruch](https://github.com/fruch) I see that you've added label to the enterprise issue on Sep 11 and that was the latest update there, no updates of who/when removed the label. And it seems like the label was just deleted as it doesn't appear in the list of available labels. Maybe you know about this change (why the label was removed)?

I guess someone was doing house cleaning

**Comment by dimakr** [comment]
> I guess someone was doing house cleaning

I see. I'll ask to re-create the label.
