### ISSUE TITLE
Replace argus-jenkins token

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#7881]
Currently Argus communicate with Jenkins by a token generated on @k0machi account,

I'm not familiar with jenkins solution for service-account or org-level tokens - but worth researching for such,
If we can't find such, we need to login into Jenkins with the github-promoted user (managed by @avikivity) and create a dedicated token for Argus

Ref https://github.com/scylladb/scylla-pkg/issues/4039#issuecomment-2180318100

**Comment by k0machi** [comment]
Got the token from Avi for `scylladb-promoter` user, provided it has same permissions as my jenkins account we are good to replace it @yaronkaikov

**Comment by yaronkaikov** [comment]
> Got the token from Avi for `scylladb-promoter` user, provided it has same permissions as my jenkins account we are good to replace it @yaronkaikov

Great, are you going to replace it?

**Comment by k0machi** [comment]
> > Got the token from Avi for `scylladb-promoter` user, provided it has same permissions as my jenkins account we are good to replace it [@yaronkaikov](https://github.com/yaronkaikov)
> 
> Great, are you going to replace it?

Replaced it just now, seems to be working (checked configuring a job, scan and a rebuild inside staging folder)

**Comment by yaronkaikov** [comment]
> > > Got the token from Avi for `scylladb-promoter` user, provided it has same permissions as my jenkins account we are good to replace it [@yaronkaikov](https://github.com/yaronkaikov)
> > 
> > 
> > Great, are you going to replace it?
> 
> Replaced it just now, seems to be working (checked configuring a job, scan and a rebuild inside staging folder)

Thanks @k0machi
