### ISSUE TITLE
Apply the default event filters again after upgrade to prevent ` Authentication error on host ` error

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#7907]
## Packages

Base Scylla version: `2022.2.19-20240328.7cba40ad90d8` with build-id `ba3d72e54a63aea9441129edfd889bdc79e422a4`
Target Scylla version (or git commit hash): `2023.1.10-20240706.21cffccc1ccd` with build-id `87fcdaf894b5dfb25d26f12d7d4aed71b84bfd44`

Kernel Version: `6.5.0-1023-gcp`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Audit was disabled by https://github.com/scylladb/scylla-enterprise/issues/3148.
But it was not disabled in `2022.2`
So every time after upgrade from this version the test suffers from ` Authentication error on host /10.142.0.200:9042: Cannot achieve consistency level for cl ONE. Requires 1, alive 0` error.
We need to apply the default event filters again after upgrade

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-sla--ubuntu-jammy-db-node-d318d953-0-3 (34.148.166.180 | 10.142.0.200) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-d318d953-0-2 (34.23.79.253 | 10.142.0.196) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-d318d953-0-1 (34.138.142.209 | 10.142.0.192) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts` (gce: undefined_region)

Test: `rolling-upgrade-with-sla-test`
Test id: `d318d953-d742-4d92-a8e6-4d29c59c5605`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-with-sla-test`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2d1cef1f9da0f3a751daa419b2d6c078676d446e/test-cases/upgrades/generic-rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d318d953-d742-4d92-a8e6-4d29c59c5605`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d318d953-d742-4d92-a8e6-4d29c59c5605)
- Show all stored logs command: `$ hydra investigate show-logs d318d953-d742-4d92-a8e6-4d29c59c5605`

## Logs:
- **db-cluster-d318d953.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/db-cluster-d318d953.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/db-cluster-d318d953.tar.gz)
- **sct-runner-events-d318d953.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/sct-runner-events-d318d953.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/sct-runner-events-d318d953.tar.gz)
- **sct-d318d953.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/sct-d318d953.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/sct-d318d953.log.tar.gz)
- **loader-set-d318d953.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/loader-set-d318d953.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/loader-set-d318d953.tar.gz)
- **monitor-set-d318d953.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/monitor-set-d318d953.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d318d953-d742-4d92-a8e6-4d29c59c5605/20240707_025953/monitor-set-d318d953.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-with-sla-test/46/)
[Argus](https://argus.scylladb.com/test/5f030eae-214c-44b1-a26f-2c2d44056182/runs?additionalRuns[]=d318d953-d742-4d92-a8e6-4d29c59c5605)
</details>

**Comment by fruch** [comment]
@juliayakovlev I think we can close this one
