### ISSUE TITLE
Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per region' 

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#7940]
This problem happens us from time to time
```
2024-06-09 20:51:07.754: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=42894415-42ed-4e3a-aee8-d459ef9f9491, source=LongevityTest.SetUp()
exception=409 POST https://compute.googleapis.com/compute/v1/projects/sct-project-1/zones/us-east1-d/instances: The resource 'projects/sct-project-1/zones/us-east1-d/instances/longevity-10gb-3h-2023-1-loader-node-d90f66a6-0-1' already exists
```

'_create_node_with_retries': failed with 
```
'Forbidden("GET https://compute.googleapis.com/compute/v1/projects/sct-project-1/zones/us-east1-d/instances/longevity-10gb-3h-2023-1-loader-node-d90f66a6-0-1: 
Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per region' of service 'compute.googleapis.com' for consumer 'project_number:1070746702980'.")', retrying [#0]
```

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-6 (34.148.146.24 | 10.142.0.89) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-5 (34.138.203.25 | 10.142.0.87) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-4 (35.243.202.194 | 10.142.0.80) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-3 (35.185.40.4 | 10.142.0.86) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-2 (34.148.140.224 | 10.142.0.84) (shards: -1)
- longevity-10gb-3h-2023-1-db-node-d90f66a6-0-1 (34.23.231.75 | 10.142.0.82) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/303472689904370913` (gce: undefined_region)

Test: `longevity-10gb-3h-gce-test`
Test id: `d90f66a6-f31d-4c59-99ee-d6e4e95541df`
Test name: `enterprise-2023.1/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/884b6de8a312e183df7b984aa3de681c9b1a6a21/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d90f66a6-f31d-4c59-99ee-d6e4e95541df`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d90f66a6-f31d-4c59-99ee-d6e4e95541df)
- Show all stored logs command: `$ hydra investigate show-logs d90f66a6-f31d-4c59-99ee-d6e4e95541df`

## Logs:
- **db-cluster-d90f66a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/db-cluster-d90f66a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/db-cluster-d90f66a6.tar.gz)
- **sct-runner-events-d90f66a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/sct-runner-events-d90f66a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/sct-runner-events-d90f66a6.tar.gz)
- **sct-d90f66a6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/sct-d90f66a6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/sct-d90f66a6.log.tar.gz)
- **loader-set-d90f66a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/loader-set-d90f66a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/loader-set-d90f66a6.tar.gz)
- **parallel-timelines-report-d90f66a6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/parallel-timelines-report-d90f66a6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d90f66a6-f31d-4c59-99ee-d6e4e95541df/20240609_205603/parallel-timelines-report-d90f66a6.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-10gb-3h-gce-test/27/)
[Argus](https://argus.scylladb.com/test/23a9f4cc-4d94-42d4-a427-6ece4fd9a487/runs?additionalRuns[]=d90f66a6-f31d-4c59-99ee-d6e4e95541df)
</details>

**Comment by fruch** [comment]
> Repeated again in a enterprise release test - [Argus link](https://argus.scylladb.com/test/e86009b6-9ee0-4615-b111-9ef255f2b518/runs?additionalRuns%5B%5D=f6ee7032-5785-4b37-9b0c-aaca3b2e3f62)
> 
> As per API quotas description on https://cloud.google.com/compute/api-quota the default limit for:
> 
> ```
> Quota group
> Description
> Read requests: Quota for regional and zonal get methods such as autoscalers.get, disks.get, instances.get, and machineTypes.get.
> 
> Metric name
> compute.googleapis.com/read_requests_per_region
> 
> Default quota
> Read requests per minute per region: 1500
> ```
> 
> We need to involve a person who has grants to access/edit the project Quotas/Limits (https://console.cloud.google.com/iam-admin/quotas?organizationId=273512867970), revise the quota and increase, if necessary.

I've asked the it to be enlarged to 2000

**Comment by fruch** [comment]
but still we should should have retries and exponential backoffs (i.e. after one minute we should be o.k.)

**Comment by fruch** [comment]
we do have retries, they were fixed, to delete instances after each failure.
