### ISSUE TITLE
artifact-tests: Don't fail test because of scylla-housekeeping

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#7970]
Recently due to multiple changes in Scylla our artifact tests keep failing due to Scylla-housekeeping version failure, based on @mykaul request, we shouldn't fail our artifacts for this.

**Comment by fruch** [comment]
i.e. we shouldn't test house-keeping anymore ?

**Comment by roydahan** [comment]
@mykaul please approve that we stop testing scylla housekeeping.

**Comment by mykaul** [comment]
I personally do not see the value in failing the whole pipeline over it. But what was not clear to me was what was failing. I was under the impression it was more than housekeeping itself that failed.

**Comment by yaronkaikov** [comment]
@mykaul @roydahan please decide what we should do with that.  removing or adding `|| true` so it will not fail is the same, we will not test it if we are ok with this, great. if not let's close this issue

**Comment by fruch** [comment]
Let's ask differently, does anyone is using the data from the house keeping database ?

**Comment by mykaul** [comment]
@tzach , @amnonh ? I feel with central monitoring that we have in Scylla cloud, there's a diminishing value with housekeeping. If we really wish to, we should aim higher (example - https://telemetry-public.ceph.com/ )

**Comment by roydahan** [comment]
Why are we focusing on the side track of things?
Did we check what is the actual issue and if we can fix it?

**Comment by mykaul** [comment]
> Why are we focusing on the side track of things? Did we check what is the actual issue and if we can fix it?

I'm surprised/annoyed we did not fix it yet. Should have taken an hour or so, takes 2 weeks.

**Comment by roydahan** [comment]
> > Why are we focusing on the side track of things? Did we check what is the actual issue and if we can fix it?
> 
> 
> 
> I'm surprised/annoyed we did not fix it yet. Should have taken an hour or so, takes 2 weeks.

You shouldn't, this issue doesn't refer to anything specific so we couldn't fix anything that you may refer to.
If you refer to the docker artifact test, it looks like a flaky issue and I asked @Annamikhlin to open an issue for that.

Let's stop opening issues as the above, instead of assuming and recommending, let's focus on the issue itself and let the people who fix it come up with the solution/recommendation.

**Comment by mykaul** [comment]
I don't think we should fail tests. I think the code in the setup should ignore housekeeping script errors.

**Comment by roydahan** [comment]
This is a code that specifically tests for housekeeping correctness.

**Comment by roydahan** [comment]
Bottom line IIUC: The setup doesn't fail, we do want the test to fail if it doesn't work.
