### ISSUE TITLE
wait_db_up in docker doesn't work properly sometimes

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#8031]
## Packages

Scylla version: `2024.2.0~rc1-20240715.9bbb8c1483d7` with build-id `963ed7f524fe09c74a07461967e282e2798783af`

Kernel Version: `5.15.0-1026-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Docker artifact tests are flaky. From my investigation I conclude that `wait_db_up` method is flaky for docker.
See, db node started to listen cql address at `2024-07-16 11:41:46,791`:
```
system.log|INFO  2024-07-16 11:41:46,791 [shard 0:sl:d] cql_server_controller - Starting listening for CQL clients on 172.17.0.2:9042 (unencrypted, non-shard-aware)
system.log|INFO  2024-07-16 11:41:46,791 [shard 0:sl:d] cql_server_controller - Starting listening for CQL clients on 172.17.0.2:19042 (unencrypted, shard-aware)
system.log|INFO  2024-07-16 11:41:46,792 [shard 0:main] init - serving
```
So, wait_db_up should wait till that time, but it wasn't:
```
< t:2024-07-16 11:41:41,708 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.17.0.2>: Running command "sudo sh -c "supervisorctl start scylla || supervisorctl start scylla-server""...
< t:2024-07-16 11:41:43,762 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.17.0.2>: scylla: started
< t:2024-07-16 11:41:44,262 f:base.py         l:143  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.17.0.2>: Command "sudo sh -c "supervisorctl start scylla || supervisorctl start scylla-server"" finished with status 0
[here verify_up code should run and take some time]
< t:2024-07-16 11:41:44,326 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.17.0.2>: Running command "sudo sh -c "supervisorctl start scylla-housekeeping || supervisorctl start scylla-housekeeping-server""...

```
this led to issue with running `nodetool status`:
```
< t:2024-07-16 11:41:47,296 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > error executing GET request to http://localhost:10000/gossiper/endpoint/live with parameters {}: remote replied with status code 404 Not Found:

```

## Impact

Failing artifact test for docker

## How frequently does it reproduce?

looks like 50% time on 2024.2 release

## Installation details

Cluster size: 1 nodes (docker)

Scylla Nodes used in this run:
- artifacts-docker-jenkins-db-node-533ff821-0 (172.17.0.2 | 172.17.0.2) (shards: 2)

OS / Image: `scylladb/scylla-enterprise-nightly` (docker: undefined_region)

Test: `artifacts-docker-test`
Test id: `533ff821-13af-4c8b-9c22-fdcc68246e1d`
Test name: `enterprise-2024.2/artifacts/artifacts-docker-test`
Test config file(s):

- [docker.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6c64059c72dfe0b891d44e6a120b7249c5dea01d/test-cases/artifacts/docker.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 533ff821-13af-4c8b-9c22-fdcc68246e1d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=533ff821-13af-4c8b-9c22-fdcc68246e1d)
- Show all stored logs command: `$ hydra investigate show-logs 533ff821-13af-4c8b-9c22-fdcc68246e1d`

## Logs:
- **db-cluster-533ff821.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/db-cluster-533ff821.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/db-cluster-533ff821.tar.gz)
- **sct-runner-events-533ff821.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/sct-runner-events-533ff821.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/sct-runner-events-533ff821.tar.gz)
- **sct-533ff821.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/sct-533ff821.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/sct-533ff821.log.tar.gz)
- **monitor-set-533ff821.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/monitor-set-533ff821.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/533ff821-13af-4c8b-9c22-fdcc68246e1d/20240716_114227/monitor-set-533ff821.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/artifacts/job/artifacts-docker-test/6/)
[Argus](https://argus.scylladb.com/test/92a7d93c-0efd-4da9-a4cf-36c868b3cc6d/runs?additionalRuns[]=533ff821-13af-4c8b-9c22-fdcc68246e1d)
</details>

**Comment by soyacz** [comment]
I examined wait_db_up and wait db down - retried couple times locally with more debugging to see if it works properly - and it is.
Because in this test scylla is not killed with -9 signal, it closes ports properly anyway and new method of checking it works.

Also there's no correlation to recent wait-db changes (in master this issue was visible recently only).

I don't think anyone will investigate this transient-few-seconds issue with nodetool that happen only occasionally in docker unless visible in k8s deployments.

My proposal is to introduce small wait (3s) before checking nodetool status in artifact test after restarting.
@fruch WDYT?

**Comment by fruch** [comment]
> I examined wait_db_up and wait db down - retried couple times locally with more debugging to see if it works properly - and it is. Because in this test scylla is not killed with -9 signal, it closes ports properly anyway and new method of checking it works.
> 
> Also there's no correlation to recent wait-db changes (in master this issue was visible recently only).
> 
> I don't think anyone will investigate this transient-few-seconds issue with nodetool that happen only occasionally in docker unless visible in k8s deployments.
> 
> My proposal is to introduce small wait (3s) before checking nodetool status in artifact test after restarting. @fruch WDYT?

I don't like it, and how can we tell it's enough ?

**Comment by soyacz** [comment]
> > I examined wait_db_up and wait db down - retried couple times locally with more debugging to see if it works properly - and it is. Because in this test scylla is not killed with -9 signal, it closes ports properly anyway and new method of checking it works.
> > Also there's no correlation to recent wait-db changes (in master this issue was visible recently only).
> > I don't think anyone will investigate this transient-few-seconds issue with nodetool that happen only occasionally in docker unless visible in k8s deployments.
> > My proposal is to introduce small wait (3s) before checking nodetool status in artifact test after restarting. @fruch WDYT?
> 
> I don't like it, and how can we tell it's enough ?

We can't - trial will tell us.
I don't like it either, but I have no other idea - except raising an issue in scylla to be fixed.

**Comment by fruch** [comment]
@soyacz 

I think we should add some prints there, to understand the problem, before we agree that sleep would be the workaround

**Comment by soyacz** [comment]
I investigated it further, and found fix for wait db down was working but still `is_port_used` was broken. Prepared a fix in above PR (to be tested).
