### ISSUE TITLE
Screenshots from perf jobs do not arrive to Argus and are not seen in Argus

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#8032]
Screenshots do not arrive to Argus and are not seen in Argus

[Argus](https://argus.scylladb.com/test/082baacc-7421-4083-ab0e-2f7322798074/runs?additionalRuns[]=139dd761-915d-4a08-a1be-157d289c0e4d)

**Comment by fruch** [comment]
I've checked and they do appear inside the monitoring log file.

so they are created in log collection phase, but probably not during the test itself.

not sure why.

**Comment by fruch** [comment]
so

`self.monitors.get_grafana_screenshot_and_snapshot` and `argus_collect_screenshots` are called as part of the `get_email_data` process, which explains why the perf test doesn't have it, they have their own mechanism for emails (cause it can create email multiple times during a test)

so we can do one of two things:
- add report of screenshots to log collection phase - @k0machi can argus identify duplicates ?
- add a dummy `get_email_data` for perf test that would do only those calls ? but won't send email ?

**Comment by soyacz** [comment]
> so
> 
> `self.monitors.get_grafana_screenshot_and_snapshot` and `argus_collect_screenshots` are called as part of the `get_email_data` process, which explains why the perf test doesn't have it, they have their own mechanism for emails (cause it can create email multiple times during a test)
> 
> so we can do one of two things:
> 
> * add report of screenshots to log collection phase - @k0machi can argus identify duplicates ?
> * add a dummy `get_email_data` for perf test that would do only those calls ? but won't send email ?

or refactor by extracting screenshot creation to separate step (with send to argus) and drop screenshot collection in collect logs phase (which duplicates it)

**Comment by fruch** [comment]
> > so
> > `self.monitors.get_grafana_screenshot_and_snapshot` and `argus_collect_screenshots` are called as part of the `get_email_data` process, which explains why the perf test doesn't have it, they have their own mechanism for emails (cause it can create email multiple times during a test)
> > so we can do one of two things:
> > 
> > * add report of screenshots to log collection phase - @k0machi can argus identify duplicates ?
> > * add a dummy `get_email_data` for perf test that would do only those calls ? but won't send email ?
> 
> or refactor by extracting screenshot creation to separate step (with send to argus) and drop screenshot collection in collect logs phase (which duplicates it)

Anyhow we still need it to happen before the email data is generated

I wouldn't drop the collection part that fast, it's good backup, if we don't get to the end of the test. (it happened so many times, like jenkins timeouts)

**Comment by soyacz** [comment]
> 
> Anyhow we still need it to happen before the email data is generated
> 
> I wouldn't drop the collection part that fast, it's good backup, if we don't get to the end of the test. (it happened so many times, like jenkins timeouts)

How about adding a step for screenshots dump&send to Argus with creating `screenshots.json` with details  which collect_logs (and other utilities like send email) read and act accordingly?
