### ISSUE TITLE
[K8S] Jenkins agent node may be picked up incorrectly causing further test run failure

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#8123]
### Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Latest set of weekly test runs for K8S has bunch of failures of the same following type:

```
02:17:22  Going to run './sct.py  create-runner-instance --cloud-provider aws --region null --availability-zone a --test-id ffa9b463-4ad0-4d5b-8d08-e632af6146af --duration 485 --test-name functional_tests/scylla_operator'...
02:17:27  logged in as arn:aws:iam::797456418907:user/qa
02:17:28  Usage: hydra create-runner-instance [OPTIONS]
02:17:28  Try 'hydra create-runner-instance --help' for help.
02:17:28  
02:17:28  Error: Invalid value for '-r' / '--region': invalid region: null. (choose from eu-north-1, ap-south-1, eu-west-3, eu-west-2, eu-west-1, ap-northeast-2, ap-northeast-1, sa-east-1, ca-central-1, ap-southeast-1, ap-southeast-2, eu-central-1, us-east-1, us-east-2, us-west-1, us-west-2)
```

Test runs that fail this way have following in common -> Label for jenkins agent doesn't get found leading to pick up of a random agent.

Output for ok case:
```
02:05:22  [Pipeline] echo
02:05:22  Finding builder for region: eu-north-1
02:05:22  [Pipeline] echo
02:05:22  Checking if we have a label for aws-eu-north-1
02:05:22  [Pipeline] echo
02:05:22  Found builder with label: aws-sct-builders-eu-north-1-v2-asg
02:05:23  [Pipeline] node
02:05:38  Still waiting to schedule task
02:05:38  All nodes of label ‘[aws-sct-builders-eu-north-1-v2-asg](https://jenkins.scylladb.com/label/aws-sct-builders-eu-north-1-v2-asg/)’ are offline
02:09:17  Running on [aws-eu-north-1-qa-builder-v2-1 i-07323c573e64e2d65](https://jenkins.scylladb.com/computer/i%2D07323c573e64e2d65/) in /tmp/jenkins/workspace/scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks-test
```

Output for the failed case:
```
02:20:13  Commit message: "fix(createTestJobPipeline): uncomment closing of an if"
02:20:13   > git rev-list --no-walk ae6806dd0e811439be21a90454c15d8c9c242b4f # timeout=10
02:20:14  [Pipeline] node
02:20:14  Running on [Dtest4CpuFleetASG-releng i-0800c90f9109d6e21](https://jenkins.scylladb.com/computer/i%2D0800c90f9109d6e21/) in /jenkins/workspace/scylla-operator/operator-master/gke/longevity-scylla-operator-3h-gke-test
```

Both main backends, EKS and GKE, fail this way.

Examples of the failed test runs with this issue:
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/46
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke-test/24
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks-test/47
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-multidc-12h-eks-test/24

#### Steps to Reproduce

1. Trigger bunch of K8S jobs in parallel?
2. [Second Step]
3. [and so on...]

**Expected behavior:** All jenkins agents must be picked up correctly based on the labels. If some are not found, then it must be scheduled and be awaited.

**Actual behavior:** Some random jenkins agents get picked up spoiling test runs.

### Installation details

SCT Version: master
Scylla version (or git commit hash): Unrelated

### Logs
* test_id: 6df93f4d-9a1b-4687-95ec-3a4bb813578e
* job log: https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/46

**Comment by vponomaryov** [comment]
@fruch , @yaronkaikov any ideas why any random agent gets picked up not waiting several minutes as before?

**Comment by fruch** [comment]
> @fruch , @yaronkaikov any ideas why any random agent gets picked up not waiting several minutes as before?

Last time I saw something like, all of the pipelines got their  parameters cleared, cause of an error I did. (Last week)

Have someone run the command to rebuild the job tree recently?

The issue was that with the parameters, there is no default value, hence no region, and we get empty marker, which leads to Jenkins picking whatever builder.

I thought I've fixed the pipeline to fail right away in those case, but looks like I didn't.

**Comment by vponomaryov** [comment]
> > @fruch , @yaronkaikov any ideas why any random agent gets picked up not waiting several minutes as before?
> 
> Last time I saw something like, all of the pipelines got their parameters cleared, cause of an error I did. (Last week)
> 
> Have someone run the command to rebuild the job tree recently?
> 
> The issue was that with the parameters, there is no default value, hence no region, and we get empty marker, which leads to Jenkins picking whatever builder.
> 
> I thought I've fixed the pipeline to fail right away in those case, but looks like I didn't.

It was latest weekly trigger. No rebuilds.

**Comment by fruch** [comment]
> > > @fruch , @yaronkaikov any ideas why any random agent gets picked up not waiting several minutes as before?
> > 
> > Last time I saw something like, all of the pipelines got their parameters cleared, cause of an error I did. (Last week)
> > 
> > Have someone run the command to rebuild the job tree recently?
> > 
> > The issue was that with the parameters, there is no default value, hence no region, and we get empty marker, which leads to Jenkins picking whatever builder.
> > 
> > I thought I've fixed the pipeline to fail right away in those case, but looks like I didn't.
> 
> It was latest weekly trigger. No rebuilds.

It's clearly run with parameters

See
https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/46/parameters/

**Comment by vponomaryov** [comment]
Parameters are also not visible in an OK test run:
- https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/47/parameters/

**Comment by fruch** [comment]
I've forgotten that the operator-master is part of the automatic job creation

https://github.com/scylladb/scylla-cluster-tests/blob/b3885befbc3992e7c93844388503a1d957ff26ff/vars/createTestJobPipeline.groovy#L84

So it's the same reason, next time everything would work.

The job reconfig was trying to merge things, it wasn't doing anything, I dropped the merging part which caused what you see here, parameters were gone.

I've added code that copy the parameters when we reconfig a job

**Comment by fruch** [comment]
> Parameters are also not visible in an OK test run:
> - https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/47/parameters/

There was one run before it, that loaded the parameters, it only needed a couple of seconds for doing that.

This job gets triggered twice in a row

**Comment by vponomaryov** [comment]
So, it needed changes in the jenkins directly? Or where did you do it?

**Comment by fruch** [comment]
> So, it needed changes in the jenkins directly? Or where did you do it?
> 

In SCT, so the next time it would reconfig, it should work

If you use the trigger now, it would work, cause all of them are now loaded with parameters.

It's the same as what we have with job number 1, that we immediately fail, so the next one would have the parameters.
