### ISSUE TITLE
Fail to get metadata from AWS using v1

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#8150]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

This test runs with use_dns_name
And branch-2023.1 has no new network config, like in master
so we receive the node dns_name using `curl http://169.254.169.254/latest/meta-data/local-hostname`
And this command return empty string
![Screenshot from 2024-07-25 22-14-26](https://github.com/user-attachments/assets/96c264c1-9e17-4e83-8031-cff53431c085)

Looks like we need to move to use v2 for that
https://docs.aws.amazon.com/cli/v1/userguide/install-linux.html#install-linux-awscli-upgrade

![Screenshot from 2024-07-25 22-28-19](https://github.com/user-attachments/assets/f9c45861-4883-453b-a88a-c0f4302ca1e0)

```
scyllaadm@longevity-tls-50gb-3d-use-dns--db-node-9c2d6c3d-1:~$ TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0  71519      0 --:--:-- --:--:-- --:--:-- 56000
scyllaadm@longevity-tls-50gb-3d-use-dns--db-node-9c2d6c3d-1:~$ echo $TOKEN
AQAEAC9xgkNn6PTejIh1CORsx4LDnBwRJxGY6cCu8rX3DQGitmwGxQ==
scyllaadm@longevity-tls-50gb-3d-use-dns--db-node-9c2d6c3d-1:~$ curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-hostname
ip-10-12-0-106.ec2.internalscyllaadm@longevity-tls-50gb-3d-use-dns--db-node-9c2d6c3d-1:~$ 
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-6 (3.88.187.147 | 10.12.9.163) (shards: 14)
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-5 (54.164.176.173 | 10.12.11.49) (shards: 14)
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-4 (54.196.187.54 | 10.12.9.186) (shards: 14)
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-3 (18.215.146.229 | 10.12.9.47) (shards: 14)
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-2 (3.80.67.58 | 10.12.9.160) (shards: 14)
- longevity-tls-50gb-3d-2023-1-db-node-fcb776fc-1 (3.93.184.34 | 10.12.9.244) (shards: 14)

OS / Image: `ami-0c6b306ef72314673` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `fcb776fc-052d-4452-9356-b56d8d6a7158`
Test name: `enterprise-2023.1/longevity/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9789547b75faf2a7d235ca7ad9ea79c3362fe92f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor fcb776fc-052d-4452-9356-b56d8d6a7158`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fcb776fc-052d-4452-9356-b56d8d6a7158)
- Show all stored logs command: `$ hydra investigate show-logs fcb776fc-052d-4452-9356-b56d8d6a7158`

## Logs:
- **db-cluster-fcb776fc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/db-cluster-fcb776fc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/db-cluster-fcb776fc.tar.gz)
- **sct-runner-events-fcb776fc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/sct-runner-events-fcb776fc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/sct-runner-events-fcb776fc.tar.gz)
- **sct-fcb776fc.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/sct-fcb776fc.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/sct-fcb776fc.log.tar.gz)
- **loader-set-fcb776fc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/loader-set-fcb776fc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/loader-set-fcb776fc.tar.gz)
- **monitor-set-fcb776fc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/monitor-set-fcb776fc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fcb776fc-052d-4452-9356-b56d8d6a7158/20240725_141024/monitor-set-fcb776fc.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-50gb-3days-test/16/)
[Argus](https://argus.scylladb.com/test/99eb9e9f-d620-4fac-add0-fe1920f028b6/runs?additionalRuns[]=fcb776fc-052d-4452-9356-b56d8d6a7158)
</details>

**Comment by soyacz** [comment]
it's not related to `new network config` - these instances somehow set `IMDSv2 Required` instead of optional like in other tests (where AWS complains it is recommended to be `required`...).
I'll try to fix it.

**Comment by fruch** [comment]
> it's not related to `new network config` - these instances somehow set `IMDSv2 Required` instead of optional like in other tests (where AWS complains it is recommended to be `required`...).
> I'll try to fix it.

The question is what got it started, the AMI we have now set it by default ? 

Or it's an account wide setting someone did, with telling everyone ?

Or AWS changed the default behavior ?

Regardless we should just use v2 across all the calls we do
