### ISSUE TITLE
scylla_forward_service_requests_dispatched_to_other_nodes renamed to scylla_mapreduce_service_requests_dispatched_to_other_nodes

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#8184]
### Issue description
Fullscan failed with 'forward_service_requests_dispatched_to_other_nodes' was not triggered
due to 
scylla_forward_service_requests_dispatched_to_other_nodes renamed to scylla_mapreduce_service_requests_dispatched_to_other_nodes

**Comment by roydahan** [comment]
I see these errors now in 2024.2.0 runs, but the blamed commit of scylla https://github.com/scylladb/scylladb/commit/3fc4e23a36aad7a418805797b08370a3f3ddae2b isn't part of this branch AFAICT.

**Comment by roydahan** [comment]
I see that these happened during Decommission nemesis.
It could be related.

**Comment by soyacz** [comment]
we didn't backport it to 2024.2 - which branched a week before this PR. Backporting.

**Comment by roydahan** [comment]
@soyacz 
Did you find the renaming commit as part of 2024.2?

Why would we need to backport this one if https://github.com/scylladb/scylla-enterprise/commit/3fc4e23a36aad7a418805797b08370a3f3ddae2b is not part of 2024.2 ?

**Comment by roydahan** [comment]
I wasn't sure yet when starting to comment on the issue.

**Comment by mykaul** [comment]
> I see it also in this run: https://argus.scylladb.com/tests/scylla-cluster-tests/b9dd8869-3644-49b4-bc4e-478f7282298a. Here it happened right after a decommission nemesis ended (FullScan started before).

@roydahan - this is (not surprising) also failing on 2024.2.x - do we have a separate bug for it? I could not find one.

**Comment by roydahan** [comment]
It's not the cause of this issue.
There is an attempt to fix/workaround this issue in this PR:

https://github.com/scylladb/scylla-cluster-tests/pull/9370

**Comment by mykaul** [comment]
2024.2.4 - https://argus.scylladb.com/test/76e76ae6-31d6-4c71-ad1a-d5694355c534/runs?additionalRuns[]=1f383d21-5aff-4606-ac4c-ef4155c7386a

**Comment by cezarmoise** [comment]
2024.2.6 - https://argus.scylladb.com/tests/scylla-cluster-tests/ebd1c3f1-79d8-4a7f-ae21-fa4193cb7e80
