### ISSUE TITLE
Test resources were not reported to Argus in 2024.1.8 release jobs

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylla-cluster-tests#8216]
### Issue description

A number of tests did not report test resources to Argus (`Resources` tab is empty) during 2024.1.8 release tests builds.
E.g. [enterprise-2024.1/longevity/longevity-150gb-asymmetric-cluster-12h-test#18](https://argus.scylladb.com/test/794fc3cc-6db5-4742-902e-48d831d2669c/runs?additionalRuns[]=fa980d10-0f3c-4d6e-878c-298efa4e042b) or [enterprise-2024.1/rolling-upgrade/rolling-upgrade-with-sla-no-shares-test#14](https://argus.scylladb.com/test/12c9fda2-ee51-4b50-ae01-9e8e93c288cb/runs?additionalRuns[]=d82fb4b0-c1b7-4fab-95b7-947d3e5361d3).

Repeated for both, passed and failed tests.

There are ArgusSCTClient errors in the build logs:
```
03:08:13  < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR > Encountered an unhandled exception while interacting with Argus < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR > Encountered an unhandled exception while interacting with Argus
03:08:13  < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR > Traceback (most recent call last):
03:08:13  < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 389, in _add_node_to_argus
03:08:13  < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR >     client.create_resource(
03:08:13  < t:2024-07-25 01:08:12,022 f:cluster.py      l:400  c:sdcm.cluster         p:ERROR > TypeError: ArgusSCTClient.create_resource() missing 2 required positional 
```

Argus image used in builds: `v1.60-argus-0.12.3-for-branch-5.4`

**Comment by soyacz** [comment]
update for Argus got in, while not the changes for it's required usage.
Missed backporting of https://github.com/scylladb/scylla-cluster-tests/pull/7433

we could fix it by backporting (which I don't know why was not backported) the above or fixing client not to require these arguments

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/8267 should close this
