### ISSUE TITLE
Wrong parameter used in spot_fleet_request

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#825]
21:39:32 Exception in init_resources. Will clean resources
21:39:32 Traceback (most recent call last):
21:39:32   File "/sct/sdcm/tester.py", line 131, in wrapper
21:39:32     return method(*args, **kwargs)
21:39:32   File "/sct/sdcm/tester.py", line 679, in init_resources
21:39:32     monitor_info=monitor_info)
21:39:32   File "/sct/sdcm/tester.py", line 507, in get_cluster_aws
21:39:32     self.db_cluster = create_cluster(db_type)
21:39:32   File "/sct/sdcm/tester.py", line 490, in create_cluster
21:39:32     **cl_params)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 531, in __init__
21:39:32     params=params)
21:39:32   File "/sct/sdcm/cluster.py", line 1775, in __init__
21:39:32     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 109, in __init__
21:39:32     region_names=self.region_names)
21:39:32   File "/sct/sdcm/cluster.py", line 1585, in __init__
21:39:32     self.add_nodes(num, dc_idx=dc_idx)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 560, in add_nodes
21:39:32     enable_auto_bootstrap=enable_auto_bootstrap)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 279, in add_nodes
21:39:32     instances = self._create_instances(count, ec2_user_data, dc_idx)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 214, in _create_instances
21:39:32     instances = self._create_spot_instances(count, interfaces, ec2_user_data, dc_idx, tags_list=tags_list)
21:39:32   File "/sct/sdcm/cluster_aws.py", line 183, in _create_spot_instances
21:39:32     instances_i = ec2.create_spot_fleet(**spot_params)
21:39:32   File "/sct/sdcm/ec2_client.py", line 302, in create_spot_fleet
21:39:32     user_data, count, block_device_mappings=block_device_mappings, tags_list=tags_list)
21:39:32   File "/sct/sdcm/ec2_client.py", line 124, in _request_spot_fleet
21:39:32     SpotFleetRequestConfig=fleet_config)
21:39:32   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
21:39:32     return self._make_api_call(operation_name, kwargs)
21:39:32   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
21:39:32     api_params, operation_model, context=request_context)
21:39:32   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 621, in _convert_to_request_dict
21:39:32     api_params, operation_model)
21:39:32   File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
21:39:32     raise ParamValidationError(report=report.generate_report())
21:39:32 ParamValidationError: Parameter validation failed:
21:39:32 Unknown parameter in SpotFleetRequestConfig: "TagSpecifications", must be one of: AllocationStrategy, ClientToken, ExcessCapacityTerminationPolicy, FulfilledCapacity, IamFleetRole, LaunchSpecifications, LaunchTemplateConfigs, SpotPrice, TargetCapacity, TerminateInstancesWithExpiration, Type, ValidFrom, ValidUntil, ReplaceUnhealthyInstances, InstanceInterruptionBehavior, LoadBalancersConfig

**Comment by bentsi** [comment]
`TagSpecifications` should be in `LaunchSpecifications`
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.request_spot_fleet

**Comment by roydahan** [comment]
ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Tag specification must have at least one tag

**Comment by fruch** [comment]
@roydahan find the root cause of this one, the fleet request failed, and the fallback ondemend call failed.
I've found more issues while looking into it, i.e. I think we could drop the bidding, AWS automatically gives you the lowest price possible, no point to limit on the minimum history prices. also the history was no on the right availability zones.
and final and not last, we need to ask AWS to extend the limit of spot instances on our account in eu-west-1, that's the reason fleet requests are failing (also cause of wrong price limits)

**Comment by fruch** [comment]
closed #826 and #853
