### ISSUE TITLE
Truncated log message in the event

### ISSUE THREAD

**Issue by xtrey** [scylladb/scylla-cluster-tests#8291]
SCT truncates the log messages, so the full message is not visible in the events.
Job example: https://argus.scylladb.com/test/4051b1c9-c265-4cdb-bf19-e24748ed3302/runs?additionalRuns[]=fdaae0bd-f82c-4726-a498-7edbd36aa7ef

Actual event message:
```
Stress command completed with bad status 1: com.datastax.driver.core.exceptions.InvalidQueryException: Cannot create CDC log for a table cdc_tes
```
But the full message from the cassandra-stress log is actualy reports the root cause of the problem: #16317 :
```
Stress command completed with bad status 1: com.datastax.driver.core.exceptions.InvalidQueryException: Cannot create CDC log for a table cdc_test.test_table, because keyspace uses tablets. See issue #16317.
```

so, we should print the full message instead of truncating it to speed up Agrus investigations

**Comment by temichus** [comment]
cc @roydahan

**Comment by fruch** [comment]
I don't think it's classified as tier1 issue.

It's a cosmetic issue

We can change to show two first lines (and not 100 characters or something like that, that is now)

Even that can really help when you have dozens of lines in stderr of the stress command.

And one would need to open the stress log to analyze the issue

**Comment by fruch** [comment]
This is the place to fix this one:
https://github.com/scylladb/scylla-cluster-tests/blob/23ccb24e43942ffb205a1563b7974790d5470da9/sdcm/stress/base.py#L154
