### ISSUE TITLE
Cloud cleanup scripts don't update Argus

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#8299]
Cloud cleanup scripts that terminate instances according to `keep` tag are not updating Argus.
So, later we end up with instances shown as `Running` while were terminated already.
This confuses Argus users and may cause additional actions taken by them to clean them.

Idea is to make `utils/cloud_cleanup` scripts to update status in Argus.

**Comment by fruch** [comment]
@soyacz 

let do that, doesn't sound too complicated from SCT end...

**Comment by soyacz** [comment]
ok, lets put it in the sprint

**Comment by fruch** [comment]
> ok, lets put it in the sprint

it's already there
