### ISSUE TITLE
Replace all places we use private/public IPs by default

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#833]
In continue to other issues me and @fruch found where using ip_address incorrectly.
We need to replace all places in the code that are specifically mentioning private_ip_address to ip_address that is decided in one place (public / private).

For example, longevity with multiDC fails during TerminateAndReplace nemesis because of this:
https://github.com/scylladb/scylla-cluster-tests/blob/b64989be567e7023e3861402de31a66158b0aeb0/sdcm/nemesis.py#L349

**Comment by roydahan** [comment]
@fruch already have some changes for this in PR #828

**Comment by fruch** [comment]
@roydahan, closing this one, since we seen the multi region use case is working.
We'll fix specific cases if we found ones
