### ISSUE TITLE
disrupt_grow_shrink_cluster nemesis is not updating end status in Argus

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#8341]
grow shrink cluster nemesis end time is not updated in Nemesis tab in Argus and shows as "Running".
See in [Argus](https://argus.scylladb.com/test/e17ff39a-f3f6-4ac6-a161-871267fd3955/runs?additionalRuns[]=6a95dc40-35e5-4903-8243-4e862df672ea)
</details>

**Comment by fruch** [comment]
@soyacz 

maybe it's really stuck ? 

keep in mind it's parallel nemesis case

**Comment by vponomaryov** [comment]
Bug exists since: https://github.com/scylladb/scylla-cluster-tests/pull/7702
Bug gets fixed here: https://github.com/scylladb/scylla-cluster-tests/pull/8380
