### ISSUE TITLE
deprecate `stress_multiplier` options completely 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#8370]
we found out this options is causing more harm than good
1) it's replicate the exact name commands, which for write or mixed, generate override we don't always intend
2) it was proven (in several) that in c-s increasing load with more thread works better
3) this option doesn't work correctly with docker loaders 

given all of those, I would suggest removing this option from SCT
and as follow up adjusting cases that was using with other options we have (number of threads) 

there is usage of it, only in 3 config files, 
2 in cases plan to deprecate, 
and on in alternator perf case, that isn't used for quite some time

**Comment by roydahan** [comment]
Once we deprecate the tests, It's fine to deprecate it.

**Comment by fruch** [comment]
I decide not to deprecate this option, it is used directly in more tests.
and might be useful in some situation which aren't performance tests
