### ISSUE TITLE
tests rolling-upgrade failed with issue " Counters are not yet supported with tablets"

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cluster-tests#8394]
## Issue description

test fail with error

```
2024-08-10 03:19:24.261: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=9152dff7-469f-49d7-a782-974b2735ad31, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 632, in test_rolling_upgrade
self.prepare_keyspaces_and_tables()
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3373, in prepare_keyspaces_and_tables
self.cql_create_tables(session)
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3132, in cql_create_tables
session.execute(create_table)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1313, in execute_verbose
return execute_orig(*args, **kwargs)
File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot use the 'counter' type for table keyspace_fill_db_data.counters_test: Counters are not yet supported with tablets"
```

recently in Argus, PR https://github.com/scylladb/scylla-cluster-tests/pull/8159 was mentioned as a fix, but looks like it does not help.

## How frequently does it reproduce?

every time 

## Installation details

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-dfd42869-4 (34.241.101.115 | 10.4.1.119) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-dfd42869-3 (3.252.164.42 | 10.4.3.15) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-dfd42869-2 (54.154.210.79 | 10.4.1.216) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-dfd42869-1 (54.75.66.15 | 10.4.2.27) (shards: 7)

OS / Image: `ami-0d4c8c23a6a9b7623` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `dfd42869-bdcd-427d-80ac-50b53850caab`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test method: `upgrade_test.UpgradeTest.test_rolling_upgrade`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/05b966987503dfe0602025e101fff695d0bf169c/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor dfd42869-bdcd-427d-80ac-50b53850caab`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=dfd42869-bdcd-427d-80ac-50b53850caab)
- Show all stored logs command: `$ hydra investigate show-logs dfd42869-bdcd-427d-80ac-50b53850caab`

## Logs:
- **db-cluster-dfd42869.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/db-cluster-dfd42869.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/db-cluster-dfd42869.tar.gz)
- **sct-runner-events-dfd42869.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/sct-runner-events-dfd42869.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/sct-runner-events-dfd42869.tar.gz)
- **sct-dfd42869.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/sct-dfd42869.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/sct-dfd42869.log.tar.gz)
- **loader-set-dfd42869.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/loader-set-dfd42869.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/loader-set-dfd42869.tar.gz)
- **monitor-set-dfd42869.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/monitor-set-dfd42869.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd42869-bdcd-427d-80ac-50b53850caab/20240810_032007/monitor-set-dfd42869.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/233/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=dfd42869-bdcd-427d-80ac-50b53850caab)
</details>

**Comment by aleksbykov** [comment]
Fixed by: https://github.com/scylladb/scylla-cluster-tests/pull/8372
