### ISSUE TITLE
The node that was created by `AddRemoveDc` nemesis and is been terminated, is set as target node by another nemesis

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#8401]
This issue may happens when 2 run nemeses: `AddRemoveDc` and any other run in parallel. And `AddRemoveDc` should start first.
```
< t:2024-08-17 22:18:01,085 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-08-17 22:18:01.072: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b6d96f8b-66a4-44ec-89f3-89b0c340
3294: nemesis_name=AddRemoveDc target_node=Node longevity-parallel-topology-schema--db-node-38b8ee85-50 [18.202.172.255 | 10.4.9.84]
< t:2024-08-17 22:24:13,983 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-08-17 22:24:13.974: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=2e58b84a-0e84-4034-bb46-5c117c17
2a94: nemesis_name=AddDropColumn target_node=Node longevity-parallel-topology-schema--db-node-38b8ee85-54 [54.228.128.54 | 10.4.8.54]
< t:2024-08-17 22:27:07,188 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-08-17 22:27:07.186: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b6d96f8b-66a4-44ec-89f3-89b0c34032
94 duration=9m6s: nemesis_name=AddRemoveDc target_node=Node longevity-parallel-topology-schema--db-node-38b8ee85-50 [18.202.172.255 | 10.4.9.84]
< t:2024-08-17 22:31:58,026 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-08-17 22:31:58.024: (DisruptionEvent Severity.ERROR) period_type=end event_id=2e58b84a-0e84-4034-bb46-5c117c172a94 duration=7m44s: nemesis_name=AddDropColumn target_node=Node longevity-parallel-topology-schema--db-node-38b8ee85-54 [54.228.128.54 | 10.4.8.54] errors=Failed to run a command due to exception!
```

We add new node during `AddRemoveDc` nemesis. When new node is ready, starts another nemesis and set this new node as target_node. And then - this node is decommissioned but original `AddRemoveDc` nemesis. As result - second nemesis fails.

Because new node is created in the new dc, we need to terminate this node, remove DC.
We can not choose any other node.
It may be few ways to fix:
1. mark this new node as not allowed to be target node
2. wait when new node became not "running nemesis"

## Packages

Scylla version: `6.2.0~dev-20240816.afee3924b3dc` with build-id `c01d2a55a9631178e3fbad3869c20ef3c8dcf293`

Kernel Version: `6.8.0-1013-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-38b8ee85-9 (34.243.172.21 | 10.4.10.40) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-8 (34.241.87.177 | 10.4.9.153) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-7 (3.248.146.218 | 10.4.11.3) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-65 (52.30.194.155 | 10.4.10.20) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-64 (54.75.203.188 | 10.4.10.126) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-63 (52.50.49.24 | 10.4.8.120) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-62 (18.203.32.147 | 10.4.9.93) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-61 (52.31.140.46 | 10.4.10.138) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-60 (54.73.163.60 | 10.4.11.187) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-6 (176.34.188.246 | 10.4.9.179) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-59 (63.33.142.5 | 10.4.11.147) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-58 (99.80.53.93 | 10.4.9.97) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-57 (54.246.102.229 | 10.4.11.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-56 (54.246.114.254 | 10.4.9.231) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-55 (54.228.229.218 | 10.4.11.135) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-54 (54.228.128.54 | 10.4.8.54) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-53 (54.220.76.170 | 10.4.8.112) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-52 (54.228.155.196 | 10.4.10.62) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-51 (54.155.42.214 | 10.4.10.130) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-50 (18.202.172.255 | 10.4.9.84) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-5 (54.194.167.67 | 10.4.9.98) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-49 (34.253.77.130 | 10.4.8.112) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-48 (52.50.119.131 | 10.4.10.10) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-47 (54.247.107.226 | 10.4.10.233) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-46 (63.34.140.249 | 10.4.10.89) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-45 (52.208.115.57 | 10.4.8.139) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-44 (108.129.36.151 | 10.4.9.85) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-43 (108.129.54.0 | 10.4.9.8) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-42 (46.51.181.179 | 10.4.11.99) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-41 (52.49.169.211 | 10.4.10.106) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-40 (52.51.11.85 | 10.4.8.32) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-4 (79.125.120.229 | 10.4.10.190) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-39 (54.73.81.149 | 10.4.10.154) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-38 (52.212.235.107 | 10.4.8.34) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-37 (54.78.206.207 | 10.4.10.23) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-36 (34.249.82.167 | 10.4.10.253) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-35 (54.74.152.7 | 10.4.9.250) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-34 (52.16.207.166 | 10.4.8.26) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-33 (108.128.171.193 | 10.4.8.255) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-32 (54.217.75.3 | 10.4.9.97) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-31 (52.51.9.38 | 10.4.10.234) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-30 (54.74.38.195 | 10.4.8.201) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-3 (176.34.236.69 | 10.4.11.232) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-29 (34.243.65.171 | 10.4.9.35) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-28 (18.200.83.15 | 10.4.8.114) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-27 (54.217.206.13 | 10.4.8.32) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-26 (54.194.3.157 | 10.4.9.254) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-25 (46.137.121.193 | 10.4.8.33) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-24 (63.34.81.137 | 10.4.10.200) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-23 (52.48.243.97 | 10.4.10.153) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-22 (79.125.122.56 | 10.4.8.30) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-21 (54.220.98.27 | 10.4.10.169) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-20 (52.19.173.79 | 10.4.10.146) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-2 (34.240.255.213 | 10.4.11.26) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-19 (34.240.190.131 | 10.4.9.22) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-18 (54.247.95.169 | 10.4.9.82) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-17 (34.251.173.31 | 10.4.9.17) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-16 (34.252.201.75 | 10.4.10.157) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-15 (52.211.65.141 | 10.4.9.175) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-14 (34.241.10.58 | 10.4.8.146) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-13 (52.30.1.91 | 10.4.11.144) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-12 (52.16.190.194 | 10.4.9.176) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-11 (52.211.210.182 | 10.4.11.78) (shards: -1)
- longevity-parallel-topology-schema--db-node-38b8ee85-10 (52.211.160.16 | 10.4.10.201) (shards: 7)
- longevity-parallel-topology-schema--db-node-38b8ee85-1 (46.137.180.83 | 10.4.9.26) (shards: 7)

OS / Image: `ami-0f440d7175113787f` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `38b8ee85-76c8-46ba-8f22-7964bec999fa`
Test name: `scylla-master/tier1/longevity-schema-topology-changes-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f99bd7dfef34caadf178a651aa0b6967284e598/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 38b8ee85-76c8-46ba-8f22-7964bec999fa`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=38b8ee85-76c8-46ba-8f22-7964bec999fa)
- Show all stored logs command: `$ hydra investigate show-logs 38b8ee85-76c8-46ba-8f22-7964bec999fa`

## Logs:
- **core.scylla-longevity-parallel-topology-schema--db-node-38b8ee85-57-2024-08-18_01-01-29.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.ff9e01ff74f843c8a0e1e92d112ebe05.6646.1723942560000000./core.scylla.106.ff9e01ff74f843c8a0e1e92d112ebe05.6646.1723942560000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.ff9e01ff74f843c8a0e1e92d112ebe05.6646.1723942560000000./core.scylla.106.ff9e01ff74f843c8a0e1e92d112ebe05.6646.1723942560000000.zst)
- **db-cluster-38b8ee85.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/db-cluster-38b8ee85.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/db-cluster-38b8ee85.tar.gz)
- **sct-runner-events-38b8ee85.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/sct-runner-events-38b8ee85.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/sct-runner-events-38b8ee85.tar.gz)
- **sct-38b8ee85.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/sct-38b8ee85.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/sct-38b8ee85.log.tar.gz)
- **loader-set-38b8ee85.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/loader-set-38b8ee85.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/loader-set-38b8ee85.tar.gz)
- **monitor-set-38b8ee85.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/monitor-set-38b8ee85.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/38b8ee85-76c8-46ba-8f22-7964bec999fa/20240818_033321/monitor-set-38b8ee85.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-schema-topology-changes-12h-test/30/)
[Argus](https://argus.scylladb.com/test/e17ff39a-f3f6-4ac6-a161-871267fd3955/runs?additionalRuns[]=38b8ee85-76c8-46ba-8f22-7964bec999fa)
</details>

**Comment by fruch** [comment]
we need to use `set_current_running_nemesis` and `unset_current_running_nemesis` calls on this node in AddRemoveDC
