### ISSUE TITLE
Argus is not setting `TEST-ERROR` for some tests

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#8614]
For some reason [this run](https://argus.scylladb.com/test/aa05fe67-89bd-4e30-88db-5e2b2e3d986d/runs?additionalRuns[]=b1611080-4440-472a-9c5a-9e61b1728d80) and [this run](https://argus.scylladb.com/test/f3e70652-634d-43ae-ba44-1ee974306fff/runs?additionalRuns%5B%5D=dd3d1632-6bc3-4140-9c09-4b86a29554dd)
Did not handle this event as `TEST-ERROR`
```
2024-09-06 00:01:56.534: (SpotTerminationEvent Severity.CRITICAL) period_type=one-time event_id=289e2787-9d81-4d8b-b098-f8258e954662: node=Node longevity-10gb-3h-master-db-node-b1611080-eastus-2 [None | 10.0.0.6] message=Got spot termination event for node: ['longevity-10gb-3h-master-db-node-eastus-2']. VM eviction time is Fri, 06 Sep 2024 00:02:05 GMT.
```

My primary suspicion is that SCT runner closed before it got to event collection and the new bit we added that uploads the events during log collection should probably trigger the same logic.

Another thing is that they're both run on Azure, and maybe we handle something differently here, althout the regex for plain Spot Termination Event is very simple and I don't see yet what could be stopping it from being matched.

**Comment by soyacz** [comment]
I think it's something on argus side, see argus.log shows:
```
< t:2024-09-10 02:22:38,581 f:base.py         l:65   c:argus.client.base    p:DEBUG > API Response: {'response': 'test_error', 'status': 'ok'}
< t:2024-09-10 02:22:38,944 f:base.py         l:65   c:argus.client.base    p:DEBUG > API Response: {'response': 'Finalized', 'status': 'ok'}

```

**Comment by k0machi** [comment]
> I think it's something on argus side, see argus.log shows:
> 
> ```
> < t:2024-09-10 02:22:38,581 f:base.py         l:65   c:argus.client.base    p:DEBUG > API Response: {'response': 'test_error', 'status': 'ok'}
> < t:2024-09-10 02:22:38,944 f:base.py         l:65   c:argus.client.base    p:DEBUG > API Response: {'response': 'Finalized', 'status': 'ok'}
> ```

We also have last stage on the pipeline that checks status and sets it as well, could be there as well.

**Comment by k0machi** [comment]
Here in fact:

https://github.com/scylladb/scylla-cluster-tests/blob/master/sct.py#L1786-L1791

I'm suprised we didn't see it earlier, will send a PR in a second.
