### ISSUE TITLE
nonroot tests should call native nodetool

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-cluster-tests#8799]
On nonroot tests, it defined to call $prefix/share/cassandra/bin/nodetool at:
https://github.com/scylladb/scylla-cluster-tests/blob/447dff1e56bebb0f37d42588a09d3f6e0b24a5f8/sdcm/cluster.py#L2423

Now it broken since we dropped scylla-jmx at https://github.com/scylladb/scylladb/commit/3cd2a6173668c5a13b6e674f912ff597f76422f5.
And also we will drop scylla-tools from unified installer soon:
https://github.com/scylladb/scylladb/issues/20739

We should call native nodetool which located at $prefix/bin/nodetool.

related with: scylladb/scylladb#20739

**Comment by fruch** [comment]
@syuu1228 

o.k. so change it to the proper calls, and once all of the artifacts test are passing calling `scylla nodetool`, we'll be able merge such a change.

**Comment by yaronkaikov** [comment]
@fruch can't we remove scylla-jmx completely from SCT?

**Comment by fruch** [comment]
> @fruch can't we remove scylla-jmx completely from SCT?

From artifact tests it can, but in general we still need to run versions with JMX, since we have releases with it

**Comment by fruch** [comment]
I've notice it few months ago, and raised it https://github.com/scylladb/scylladb/issues/19185.
I don't think anything change since then, i.e. that `scylla nodetool` might not work as expect across all the offline tests
