### ISSUE TITLE
SkipPerIssue class used but not imported

### ISSUE THREAD

**Issue by xtrey** [scylladb/scylla-cluster-tests#8838]
s## Packages

Scylla version: `6.0.4-20240919.7d421abec43d` with build-id `84cd4ae97ea9d9820a56ede82cc51ff18e019400`

Kernel Version: `5.15.0-1070-aws`

## Issue description
```
2024-09-19 21:50:03.515: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=98a291eb-e6fd-403a-aa88-8565fb22e013, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 130, in test_custom_time
self.pre_create_alternator_tables()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1110, in pre_create_alternator_tables
tablets_support_ttl = not SkipPerIssues(issues="scylladb/scylladb#16567", params=self.params)
NameError: name 'SkipPerIssues' is not defined
```

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-6-0-db-node-21397881-6 (54.172.153.104 | 10.12.11.109) (shards: 14)
- alternator-3h-6-0-db-node-21397881-5 (54.234.110.248 | 10.12.11.131) (shards: 14)
- alternator-3h-6-0-db-node-21397881-4 (54.197.120.0 | 10.12.8.169) (shards: 14)
- alternator-3h-6-0-db-node-21397881-3 (184.72.130.61 | 10.12.9.71) (shards: 14)
- alternator-3h-6-0-db-node-21397881-2 (18.206.174.13 | 10.12.10.208) (shards: 14)
- alternator-3h-6-0-db-node-21397881-1 (98.81.139.91 | 10.12.9.115) (shards: 14)

OS / Image: `ami-0c3bc135277a34630` (aws: undefined_region)

Test: `longevity-alternator-3h-test`
Test id: `21397881-c321-4ba2-8f17-a009d586d72b`
Test name: `scylla-6.0/alternator/longevity-alternator-3h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/80b1a5706b37425c522ec22d6739a1e73e56a5fe/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 21397881-c321-4ba2-8f17-a009d586d72b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=21397881-c321-4ba2-8f17-a009d586d72b)
- Show all stored logs command: `$ hydra investigate show-logs 21397881-c321-4ba2-8f17-a009d586d72b`

## Logs:
- **db-cluster-21397881.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/db-cluster-21397881.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/db-cluster-21397881.tar.gz)
- **sct-runner-events-21397881.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/sct-runner-events-21397881.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/sct-runner-events-21397881.tar.gz)
- **sct-21397881.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/sct-21397881.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/sct-21397881.log.tar.gz)
- **loader-set-21397881.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/loader-set-21397881.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/loader-set-21397881.tar.gz)
- **monitor-set-21397881.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/monitor-set-21397881.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/monitor-set-21397881.tar.gz)
- **parallel-timelines-report-21397881.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/parallel-timelines-report-21397881.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21397881-c321-4ba2-8f17-a009d586d72b/20240919_215156/parallel-timelines-report-21397881.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.0/job/alternator/job/longevity-alternator-3h-test/16/)
[Argus](https://argus.scylladb.com/test/8cdbe81d-b64f-4086-8260-b57a46b32529/runs?additionalRuns[]=21397881-c321-4ba2-8f17-a009d586d72b)
</details>

**Comment by vponomaryov** [comment]
Fixed here:
- https://github.com/scylladb/scylla-cluster-tests/pull/8864
