### ISSUE TITLE
Test that runs with `use_capacity_reservation: true` did not try to use another AZ

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#8839]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

This test runs with `use_capacity_reservation: true` (https://github.com/scylladb/scylla-cluster-tests/blob/0abca81bdcc589bb259b6d92e34277f615e4f414/test-cases/performance/perf-regression-latency-650gb-upgrade.yaml), but failed with error:
```
not have sufficient c6i.2xlarge capacity in the Availability Zone you requested (eu-west-1a)
```

It did not try to create instance in another AZ, not according to the test parameter

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-6 (3.250.103.193 | 10.4.3.101) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-5 (54.216.111.73 | 10.4.0.66) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-4 (34.244.110.95 | 10.4.0.222) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-3 (52.30.9.77 | 10.4.3.127) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-2 (108.129.147.115 | 10.4.0.255) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-753b0fe8-1 (34.244.27.21 | 10.4.0.185) (shards: -1)

OS / Image: `ami-0af227e94a100d678` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets`
Test id: `753b0fe8-5569-41a9-aade-30b5b0f6c404`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets`
Test method: `performance_regression_test.PerformanceRegressionUpgradeTest.test_latency_mixed_with_upgrade`
Test config file(s):

- [perf-regression-latency-650gb-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0abca81bdcc589bb259b6d92e34277f615e4f414/test-cases/performance/perf-regression-latency-650gb-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 753b0fe8-5569-41a9-aade-30b5b0f6c404`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=753b0fe8-5569-41a9-aade-30b5b0f6c404)
- Show all stored logs command: `$ hydra investigate show-logs 753b0fe8-5569-41a9-aade-30b5b0f6c404`

## Logs:
- **db-cluster-753b0fe8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/db-cluster-753b0fe8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/db-cluster-753b0fe8.tar.gz)
- **sct-runner-events-753b0fe8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/sct-runner-events-753b0fe8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/sct-runner-events-753b0fe8.tar.gz)
- **sct-753b0fe8.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/sct-753b0fe8.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/753b0fe8-5569-41a9-aade-30b5b0f6c404/20240925_103733/sct-753b0fe8.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets/4/)
[Argus](https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=753b0fe8-5569-41a9-aade-30b5b0f6c404)
</details>

**Comment by soyacz** [comment]
I saw it tried all supported AZ's:
```
14:55:25  Supported availability zones for instance types ['i3en.2xlarge', 'c6i.2xlarge']: ['eu-west-1c', 'eu-west-1a', 'eu-west-1b']
14:55:25  Creating capacity reservation in eu-west-1c
[...]
14:55:34  Failed to create capacity reservation in eu-west-1c
14:55:34  Capacity reservation cr-0c8860d65de2c8154 for i3en.2xlarge cancelled successfully.
14:55:34  waiting 30s before falling back to next AZ to release placement group
14:56:05  Falling back to next availability zone.
14:56:05  Creating capacity reservation in eu-west-1a
[...]
```

I think it's get problematic anyway if a test uses 'placement_groups' - maybe we don't need it for this test?

**Comment by juliayakovlev** [comment]
> I saw it tried all supported AZ's:
> 
> ```
> 14:55:25  Supported availability zones for instance types ['i3en.2xlarge', 'c6i.2xlarge']: ['eu-west-1c', 'eu-west-1a', 'eu-west-1b']
> 14:55:25  Creating capacity reservation in eu-west-1c
> [...]
> 14:55:34  Failed to create capacity reservation in eu-west-1c
> 14:55:34  Capacity reservation cr-0c8860d65de2c8154 for i3en.2xlarge cancelled successfully.
> 14:55:34  waiting 30s before falling back to next AZ to release placement group
> 14:56:05  Falling back to next availability zone.
> 14:56:05  Creating capacity reservation in eu-west-1a
> [...]
> ```
> 
> I think it's get problematic anyway if a test uses 'placement_groups' - maybe we don't need it for this test?

So the error message is not correct:
```
exception=An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient c6i.2xlarge capacity in the Availability Zone you requested (eu-west-1a). Our system will be working on provisioning additional capacity. You can currently get c6i.2xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-1b, eu-west-1c.
```

It suggest to try to create in other AZs. 
I should be like "tried a,b,c and failed to create in any zone"

**Comment by fruch** [comment]
@soyacz, not sure I see what problematic with placement groups here ? we are using combination for quite some time now, where do you see an issue?

**Comment by soyacz** [comment]
just using "placement_groups" makes for AWS harder to find right infrastructure - especially when we mix 6 db nodes with strong loaders.

**Comment by fruch** [comment]
> just using "placement_groups" makes for AWS harder to find right infrastructure - especially when we mix 6 db nodes with strong loaders.
> 

Well, not using it, we'll need to demo/proof it doesn't affect the thoughtput test we are trying to stabilize for quite some time.

It was introduced in order to try to stabilize the performance results.

**Comment by soyacz** [comment]
> > just using "placement_groups" makes for AWS harder to find right infrastructure - especially when we mix 6 db nodes with strong loaders.
> 
> Well, not using it, we'll need to demo/proof it doesn't affect the thoughtput test we are trying to stabilize for quite some time.
> 
> It was introduced in order to try to stabilize the performance results.

I think this one is crucial for 'pure latency' test, where we care about 1ms differences, here, I think we have bigger margins.
Still needs a proof.

**Comment by fruch** [comment]
> > > just using "placement_groups" makes for AWS harder to find right infrastructure - especially when we mix 6 db nodes with strong loaders.
> > 
> > Well, not using it, we'll need to demo/proof it doesn't affect the thoughtput test we are trying to stabilize for quite some time.
> > 
> > It was introduced in order to try to stabilize the performance results.
> 
> I think this one is crucial for 'pure latency' test, where we care about 1ms differences, here, I think we have bigger margins.
> Still needs a proof. 

Our issues were more with the thoughtput, and not latencies.

But anyway to do such a chance, we'll need to battle proof it

**Comment by juliayakovlev** [comment]
@fruch @soyacz 
Maybe it connected. Test failed with error:
```
exception=An error occurred (InvalidParameterCombination) when calling the RunInstances operation: Cluster placement groups are not supported by the 't3.small' instance type. Specify a supported instance type or change the placement group strategy, and try again.
```
Any idea?

## Packages










## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- perf-regression-predefined-steps-ub-db-node-d4492d0d-3 (18.206.86.116 | 10.12.2.130) (shards: -1)
- perf-regression-predefined-steps-ub-db-node-d4492d0d-2 (100.27.40.232 | 10.12.0.126) (shards: -1)
- perf-regression-predefined-steps-ub-db-node-d4492d0d-1 (3.239.19.160 | 10.12.0.180) (shards: -1)


OS / Image: `ami-0659bff0f4ab43da6` (aws: undefined_region)

Test: `scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes`
Test id: `d4492d0d-0f07-47a2-9b10-33cab2cc426a`
Test name: `scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes`
Test method: `performance_regression_gradual_grow_throughput.PerformanceRegressionPredefinedStepsTest.test_read_gradual_increase_load`
Test config file(s):

- [perf-regression-predefined-throughput-steps.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0abca81bdcc589bb259b6d92e34277f615e4f414/test-cases/performance/perf-regression-predefined-throughput-steps.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor d4492d0d-0f07-47a2-9b10-33cab2cc426a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d4492d0d-0f07-47a2-9b10-33cab2cc426a)
- Show all stored logs command: `$ hydra investigate show-logs d4492d0d-0f07-47a2-9b10-33cab2cc426a`


## Logs:
- **db-cluster-d4492d0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/db-cluster-d4492d0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/db-cluster-d4492d0d.tar.gz)
- **sct-runner-events-d4492d0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/sct-runner-events-d4492d0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/sct-runner-events-d4492d0d.tar.gz)
- **sct-d4492d0d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/sct-d4492d0d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/sct-d4492d0d.log.tar.gz)
- **loader-set-d4492d0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/loader-set-d4492d0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4492d0d-0f07-47a2-9b10-33cab2cc426a/20240926_085217/loader-set-d4492d0d.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/perf-regression/job/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes/2/)
[Argus](https://argus.scylladb.com/test/5c8777b4-9bf1-49bc-8b96-fa3426b05e86/runs?additionalRuns[]=d4492d0d-0f07-47a2-9b10-33cab2cc426a)
</details>

**Comment by soyacz** [comment]
That would mean we shouldn't use placement groups for monitoring nodes - this would require fixing some code I believe

**Comment by fruch** [comment]
> That would mean we shouldn't use placement groups for monitoring nodes - this would require fixing some code I believe

We should provision the monitor after we know the AZ selected 

But why does this case have any different configuration than other tests ?

**Comment by juliayakovlev** [comment]
> > That would mean we shouldn't use placement groups for monitoring nodes - this would require fixing some code I believe
> 
> We should provision the monitor after we know the AZ selected
> 
> But why does this case have any different configuration than other tests ?

What do you mean - different configuration?

**Comment by fruch** [comment]
> > > That would mean we shouldn't use placement groups for monitoring nodes - this would require fixing some code I believe
> > 
> > We should provision the monitor after we know the AZ selected
> > 
> > But why does this case have any different configuration than other tests ?
> 
> What do you mean - different configuration?

Never mind, I see all perf tests are using the same type of monitor.

@soyacz the mix here we failed provision, and during the test we are using CR, while this type is out of it...

If we put the monitor type in would the CRs ? Would that mean we need to pick a different instance for monitors ?

**Comment by soyacz** [comment]
Monitor is not part of the CR's, and should be provisioned during "provision" step - where actually is. From unknown reasons, later test stage tries to provision it again - and there we don't distinguish between instances types (as this situation is uncommon to add/remove monitor nodes). Investigating.

**Comment by soyacz** [comment]
Actually, one test failed on provision step (the one with t3.small provision issue):
```
10:44:39  Capacity reservations created in 'us-east-1a' az: {'a': {'i4i.4xlarge': 'cr-050f05f15bf30554d', 'c7i.8xlarge': 'cr-0b75117488af6ca9a'}} for duration: 560
10:44:41  [us-east-1] Creating {count} on-demand instances using AMI id 'ami-0659bff0f4ab43da6' with following parameters:
[...]
10:44:42  botocore.exceptions.ClientError: An error occurred (ReservationCapacityExceeded) when calling the RunInstances operation: The requested reservation does not have sufficient compatible and available capacity for this request.
```
I don't know why it proceeded to next steps, where it failed provisioning monitors. This scenario is not supported by CR's - provision step failure should be definitive.
Also I don't understand why it failed provision instances when it successfully created CR's...

**Comment by roydahan** [comment]
so what the issue here? Is it just bad error handling or a real issue?
Who should fix it?

**Comment by roydahan** [comment]
@fruch said to close.
