### ISSUE TITLE
[disrupt_decommission_streaming_err] nemises failed during clean_group0_garbage for target node

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#8930]
## Packages

Scylla version: `2024.2.0~rc3-20241004.89f8638e9e9b` with build-id `95fdcb05a2d968f52fbcfc46114ef612aaf56608`

Kernel Version: `5.15.0-1070-aws`

## Issue description

- [ ] This issue is a regression.

*Describe your issue in detail and steps it took to produce it.*
- Run **disrupt_restart_with_resharding** nemises
- Run **disrupt_decommission_streaming_err** nemises

Issue happens after the target node been terminated while **clean_group0_garbage** invoking (no any response from scylla received) 

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 12 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- parallel-topology-schema-changes-mu-db-node-d96e7c16-9 (18.175.180.24 | 2a05:d01c:0964:7d01:753d:7f82:63bd:7cc7) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-8 (18.175.135.35 | 2a05:d01c:0964:7d00:167d:4efc:ceeb:2ee8) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-7 (18.130.44.125 | 2a05:d01c:0964:7d00:036e:52b3:824f:3fd7) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-6 (3.255.143.11 | 2a05:d018:12e3:f002:16cf:1d41:df5e:4e49) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-5 (54.171.180.239 | 2a05:d018:12e3:f002:37ef:296f:d299:9b36) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-4 (34.244.83.45 | 2a05:d018:12e3:f001:4883:9ad8:e6c5:608a) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-3 (3.253.192.50 | 2a05:d018:12e3:f001:6cdf:9447:1510:fbd6) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-2 (54.75.62.62 | 2a05:d018:12e3:f000:9496:bab3:26b8:b8ab) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-18 (3.254.155.136 | 2a05:d018:12e3:f001:b4fc:dc28:d7d4:9d04) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-17 (18.201.250.249 | 2a05:d018:12e3:f001:8e84:86f1:21a3:90c5) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-16 (34.245.149.189 | 2a05:d018:12e3:f002:d6d4:d077:3f44:47fe) (shards: -1)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-15 (18.134.8.171 | 2a05:d01c:0964:7d02:d1b7:659f:0889:0560) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-14 (13.40.187.29 | 2a05:d01c:0964:7d01:c8a9:6e1a:c584:a35b) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-13 (18.130.56.103 | 2a05:d01c:0964:7d00:fa73:f461:7fad:540b) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-12 (18.130.220.74 | 2a05:d01c:0964:7d02:d18f:3d3a:54ed:78ee) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-11 (35.179.177.228 | 2a05:d01c:0964:7d02:7de3:f2a6:40e3:30da) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-10 (13.42.37.147 | 2a05:d01c:0964:7d01:1322:fa93:57b5:85ae) (shards: 7)
- parallel-topology-schema-changes-mu-db-node-d96e7c16-1 (34.242.18.246 | 2a05:d018:12e3:f000:4476:e97d:967a:0280) (shards: 7)

OS / Image: `ami-0ea8ad7f9305a3297 ami-0686dda0ba768267e` (aws: undefined_region)

Test: `longevity-multidc-schema-topology-changes-12h-test`
Test id: `d96e7c16-1105-4f5d-92bd-2b149705343f`
Test name: `enterprise-2024.2/tier1/longevity-multidc-schema-topology-changes-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-multidc-parallel-topology-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5c604c7363757dcd9084b9f267b4b1b90bee9776/test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d96e7c16-1105-4f5d-92bd-2b149705343f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d96e7c16-1105-4f5d-92bd-2b149705343f)
- Show all stored logs command: `$ hydra investigate show-logs d96e7c16-1105-4f5d-92bd-2b149705343f`

## Logs:
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-8-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-8-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-9-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-9-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-11-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-11-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-16** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-16-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-16-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-3-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-3-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-4-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-4-d96e7c16.tar.gz)
- **parallel-topology-schema-changes-mu-db-node-d96e7c16-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-15-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241006_131751/parallel-topology-schema-changes-mu-db-node-d96e7c16-15-d96e7c16.tar.gz)
- **db-cluster-d96e7c16.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/db-cluster-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/db-cluster-d96e7c16.tar.gz)
- **sct-runner-events-d96e7c16.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/sct-runner-events-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/sct-runner-events-d96e7c16.tar.gz)
- **sct-d96e7c16.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/sct-d96e7c16.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/sct-d96e7c16.log.tar.gz)
- **loader-set-d96e7c16.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/loader-set-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/loader-set-d96e7c16.tar.gz)
- **monitor-set-d96e7c16.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/monitor-set-d96e7c16.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d96e7c16-1105-4f5d-92bd-2b149705343f/20241007_000638/monitor-set-d96e7c16.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/tier1/job/longevity-multidc-schema-topology-changes-12h-test/7/)
[Argus](https://argus.scylladb.com/test/5cd4bfe3-231b-4f48-99bc-f21ebd1b5efe/runs?additionalRuns[]=d96e7c16-1105-4f5d-92bd-2b149705343f)
</details>

**Comment by soyacz** [comment]
@aleksbykov can you take a look?
