### ISSUE TITLE
Retire artifacts tests for amazon linux 2

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#8946]
@roydahan asked for the removal of those jobs in:
https://github.com/scylladb/scylladb/issues/18631#issuecomment-2383749588

- [ ] remove from master
- [x] remove the trigger  - https://github.com/scylladb/scylla-pkg/pull/4566
- [ ] delete in jenkins / argus 
- [ ] Update Scylla documentation

**Comment by roydahan** [comment]
@yaronkaikov Good opportunity to start practicing towards owning our support matrix.

**Comment by yaronkaikov** [comment]
> [@yaronkaikov](https://github.com/yaronkaikov) Good opportunity to start practicing towards owning our support matrix.

Let start with passing the knowledge before you start assigning us the QA related tasks :-)
