### ISSUE TITLE
Replace GCP instance types n1 with n2

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#8971]
This is what we recommend.

See https://github.com/search?q=repo%3Ascylladb%2Fscylla-cluster-tests%20%22gce_instance_type_db%3A%20%27n1%22&type=code

**Comment by mykaul** [comment]
Price comparison (https://gcpinstances.doit.com/?compare_on=true&selected=n1-highmem-8,n2-highmem-8 ):


Note that with n2, you can ask for IceLake (which is what Siren does) which is 30% faster or so in CPU compared to Cascade Lake (which you might get by default)

**Comment by roydahan** [comment]
@dimakr just blindly replace all n1 to n2.
