### ISSUE TITLE
Create test function for testing 90% storage utilization

### ISSUE THREAD

**Issue by pehala** [scylladb/scylla-cluster-tests#9130]
Add test function that allows testing cluster under 90% storage utilization

**Comment by mykaul** [comment]
@pehala , @Lakshmipathi  - can you update this? I assume it's being worked on already?

**Comment by pehala** [comment]
> [@pehala](https://github.com/pehala) , [@Lakshmipathi](https://github.com/Lakshmipathi) - can you update this? I assume it's being worked on already?

Resolved by migrating testcases to performance tests.
