### ISSUE TITLE
_rotate_kms_key: `SkipPerIssues` raises `AttributeError` as `self.params` object has no attribute 'scylla_version'

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#9134]
Here is a traceback of failure:
```
2024-11-04 17:38:44.815: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=91b83f10-bb92-45bc-a7db-6ff7f054ea0a: message='dict' object has no attribute 'scylla_version'
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4589, in _rotate_kms_key
if SkipPerIssues("https://github.com/scylladb/scylla-enterprise/issues/3896", self.params):
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/issues.py", line 171, in __bool__
return self.issues_opened() or self.issues_labeled()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/issues.py", line 162, in issues_labeled
if self.params.scylla_version:
AttributeError: 'dict' object has no attribute 'scylla_version'
```

Argus: https://argus.scylladb.com/tests/scylla-cluster-tests/439869f1-5f7a-4840-b6ef-ad1f83ec465e

The issue is in this particular [code](https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L4589):
```
                if SkipPerIssues("https://github.com/scylladb/scylla-enterprise/issues/3896", self.params):
                    self.log.warning("KMS encryption check is skipped due to the 'scylla-enterprise/issues/3896'")
                    continue
```
I suppose during the time the test waits to proceed with rotation the object `self.params` references to might have been changed somewhere else.

In general, this `if SkipPerIssues` clause can be completely removed since the issue it linked to is closed and doesn't have skip label.

@vponomaryov Please, let me know what do you think?
If you don't mind removing this `if` clause, I can remove it. Just decided to raise this question, since this `self.params` issue may exist somewhere else.

**Comment by vponomaryov** [comment]
> Here is a traceback of failure:
> 
> ```
> 2024-11-04 17:38:44.815: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=91b83f10-bb92-45bc-a7db-6ff7f054ea0a: message='dict' object has no attribute 'scylla_version'
> Traceback (most recent call last):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
> return func(*args, **kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4589, in _rotate_kms_key
> if SkipPerIssues("https://github.com/scylladb/scylla-enterprise/issues/3896", self.params):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/issues.py", line 171, in __bool__
> return self.issues_opened() or self.issues_labeled()
> File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/issues.py", line 162, in issues_labeled
> if self.params.scylla_version:
> AttributeError: 'dict' object has no attribute 'scylla_version'
> ```
> 
> Argus: https://argus.scylladb.com/tests/scylla-cluster-tests/439869f1-5f7a-4840-b6ef-ad1f83ec465e
> 
> The issue is in this particular [code](https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L4589):
> 
> ```
>                 if SkipPerIssues("https://github.com/scylladb/scylla-enterprise/issues/3896", self.params):
>                     self.log.warning("KMS encryption check is skipped due to the 'scylla-enterprise/issues/3896'")
>                     continue
> ```
> 
> I suppose during the time the test waits to proceed with rotation the object `self.params` references to might have been changed somewhere else.

I think it is related to this part of the logic: https://github.com/scylladb/scylla-cluster-tests/blame/24d72b4466b557fb7920b415208e1a1faa0d6074/sdcm/cluster.py#L4013
So, the question is why cluster gets initiated with dictionary and not with SCTConfiguration which has "scylla_version" attribute.

> In general, this `if SkipPerIssues` clause can be completely removed since the issue it linked to is closed and doesn't have skip label.
> 
> [@vponomaryov](https://github.com/vponomaryov) Please, let me know what do you think? If you don't mind removing this `if` clause, I can remove it. Just decided to raise this question, since this `self.params` issue may exist somewhere else.

Yes, if SKipPerIssue is not needed anymore, it can be removed.
It will solve your own case.

But SkipPerIssue still may get dictionary again in other cases.
So, bug really exists and must be fixed.

**Comment by fruch** [comment]
[#9160](https://github.com/scylladb/scylla-cluster-tests/pull/9160) fixes the issue, i.e. get it out of the way
