### ISSUE TITLE
Coredump event occurred while the simulation of total network block

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#9135]
## Packages

Scylla version: `6.3.0~dev-20241025.e7d6ab576bc7` with build-id `d6538cb390183d94e738de97f6d148fa1f6a0b98`

Kernel Version: `6.8.0-1017-aws`

## Issue description
New issue

Core dump event occurred while the simulation of total network block:

```
2024-10-26T09:59:01.745+00:00 longevity-tls-50gb-3d-master-db-node-5908342e-5     !INFO | kernel: systemd-network[608]: segfault at 7ffcd2d31ff8 ip 0000757ed01bb893 sp 00007ffcd2d32000 error 6 in libsystemd-shared-255.so[757ed006a000+247000] likely on CPU 12 (core 4, socket 0)
2024-10-26T09:59:01.745+00:00 longevity-tls-50gb-3d-master-db-node-5908342e-5     !INFO | kernel: Code: 00 e8 d1 ec 00 00 b8 f4 ff ff ff e9 45 ff ff ff 0f 1f 80 00 00 00 00 49 89 f2 48 85 ff 0f 84 54 04 00 00 55 49 89 f9 48 89 e5 <41> 55 41 54 53 48 83 ec 08 0f b6 4f 2f 89 c8 83 e0 03 3c 01 0f 84
2024-10-26T09:59:01.745+00:00 longevity-tls-50gb-3d-master-db-node-5908342e-5     !INFO | systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
2024-10-26T09:59:01.745+00:00 longevity-tls-50gb-3d-master-db-node-5908342e-5     !INFO | systemd[1]: Started systemd-coredump@0-18675-0.service - Process Core Dump (PID 18675/UID 0).
2024-10-26T09:59:01.745+00:00 longevity-tls-50gb-3d-master-db-node-5908342e-5     !CRIT | systemd-coredump[18676]: Process 608 (systemd-network) of user 998 dumped core.

Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2build1.1.amd64
Module libsystemd-shared-255.so from deb systemd-255.4-1ubuntu8.4.amd64
Module systemd-networkd from deb systemd-255.4-1ubuntu8.4.amd64
Stack trace of thread 608:
#0  0x0000757ed01bb893 n/a (libsystemd-shared-255.so + 0x1bb893)
#1  0x0000757ed01c412f _hashmap_iterate (libsystemd-shared-255.so + 0x1c412f)
#2  0x00005e21b88d6175 n/a (systemd-networkd + 0xe7175)
#3  0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#4  0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#5  0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#6  0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#7  0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#8  0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#9  0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#10 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#11 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#12 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#13 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#14 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#15 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#16 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#17 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#18 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#19 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#20 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#21 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#22 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#23 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#24 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#25 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#26 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#27 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#28 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#29 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#30 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#31 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#32 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#33 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#34 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#35 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#36 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#37 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#38 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#39 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#40 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#41 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#42 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#43 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#44 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#45 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#46 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#47 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#48 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#49 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#50 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#51 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#52 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#53 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#54 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#55 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#56 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#57 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#58 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#59 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#60 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#61 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
#62 0x00005e21b88d618d n/a (systemd-networkd + 0xe718d)
#63 0x00005e21b88d62ca n/a (systemd-networkd + 0xe72ca)
ELF object binary architecture: AMD x86-64
```

## Impact

No impact, the scylla is alive and nemesis finished with success status, but core dump event in systemd-networkd module occurred.

## How frequently does it reproduce?

Just once by this time 

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-5908342e-9 (63.33.86.87 | 10.4.23.75) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-8 (46.137.67.20 | 10.4.21.93) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-7 (99.80.165.71 | 10.4.21.95) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-6 (63.33.238.191 | 10.4.21.14) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-5 (34.253.62.67 | 10.4.21.204) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-4 (52.18.170.126 | 10.4.21.9) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-3 (54.78.226.251 | 10.4.22.68) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-2 (3.248.106.211 | 10.4.23.19) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-5908342e-1 (63.33.89.229 | 10.4.21.116) (shards: 14)

OS / Image: `ami-0ae43759689e5e8e8` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `5908342e-e432-451c-8291-9db27469783f`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6a3ca71c5eb4b39295ed924d684c138e139e4b9f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5908342e-e432-451c-8291-9db27469783f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5908342e-e432-451c-8291-9db27469783f)
- Show all stored logs command: `$ hydra investigate show-logs 5908342e-e432-451c-8291-9db27469783f`

## Logs:
- **longevity-tls-50gb-3d-master-db-node-5908342e-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-1-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-1-5908342e.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-5908342e-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-6-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-6-5908342e.tar.gz)
- **longevity-tls-50gb-3d-master-db-node-5908342e-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-8-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_031122/longevity-tls-50gb-3d-master-db-node-5908342e-8-5908342e.tar.gz)
- **core.scylla-longevity-tls-50gb-3d-master-db-node-5908342e-5-2024-10-26_09-59-37.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.systemd-network.998.475dcb6014de4d4e89417ce133bbd2e2.608.1729936741000000./core.systemd-network.998.475dcb6014de4d4e89417ce133bbd2e2.608.1729936741000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.systemd-network.998.475dcb6014de4d4e89417ce133bbd2e2.608.1729936741000000./core.systemd-network.998.475dcb6014de4d4e89417ce133bbd2e2.608.1729936741000000.zst)
- **db-cluster-5908342e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/db-cluster-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/db-cluster-5908342e.tar.gz)
- **sct-runner-events-5908342e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/sct-runner-events-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/sct-runner-events-5908342e.tar.gz)
- **sct-5908342e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/sct-5908342e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/sct-5908342e.log.tar.gz)
- **loader-set-5908342e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/loader-set-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/loader-set-5908342e.tar.gz)
- **monitor-set-5908342e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/monitor-set-5908342e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5908342e-e432-451c-8291-9db27469783f/20241026_173659/monitor-set-5908342e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/43/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=5908342e-e432-451c-8291-9db27469783f)
</details>

**Comment by fruch** [comment]
this run was ontop of `systemd 255 (255.4-1ubuntu8.4)`

sound like: https://github.com/systemd/systemd/issues/32247


and fixes exists from [v256-rc2](https://github.com/systemd/systemd/releases/tag/v256-rc2) and up

**Comment by fruch** [comment]
so we can ignore it for now

or skip the nemesis based on the systemd version... 

@scylladb/qa-maintainers WDYT ?

**Comment by roydahan** [comment]
If we carefully introduce skipPerIssue just for coredump event that are for systemd it would be the best.
If too complicated, we can try to ignore it and hope that v256 official will be released soon enough.

**Comment by fruch** [comment]
lets add information to the first coredump event, so we can filter based on the process name when needed
