### ISSUE TITLE
[disrupt_abort_repair] nemesis failed but operations that been initiated by it ended successfully

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#9177]
## Packages

Scylla version: `6.3.0~dev-20241108.aebb5329068e` with build-id `f25ba153fbf85f1e556539e48f980dd93e3ab285`

Kernel Version: `6.8.0-1018-aws`

## Issue description

New issue

there are few log entries that sign that repair been terminated from the test side but nemesis still failed
```
2024-11-09T16:31:45.334+00:00 longevity-50gb-12h-master-db-node-903af0db-1     !INFO | scylla[5461]:  [shard 2:strm] repair - repair[5f4e4854-2871-4b5b-97b2-a2e1169eca20]: stats: repair_reason=repair, keyspace=keyspace1, tables=["standard1"], ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=0, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=1, rpc_call_nr=20, tx_hashes_nr=234, rx_hashes_nr=104536, duration=1.5219303 seconds, tx_row_nr=226, rx_row_nr=234, tx_row_bytes=290184, rx_row_bytes=600210, row_from_disk_bytes={10.4.8.52: 67109544, 10.4.9.43: 67109544, 10.4.11.145: 67109544}, row_from_disk_nr={10.4.8.52: 52266, 10.4.9.43: 52266, 10.4.11.145: 52266}, row_from_disk_bytes_per_sec={10.4.8.52: 42.052284, 10.4.9.43: 42.052284, 10.4.11.145: 42.052284} MiB/s, row_from_disk_rows_per_sec={10.4.8.52: 34341.914, 10.4.9.43: 34341.914, 10.4.11.145: 34341.914} Rows/s, tx_row_nr_peer={10.4.8.52: 113, 10.4.11.145: 113}, rx_row_nr_peer={10.4.11.145: 234}
2024-11-09T16:31:45.334+00:00 longevity-50gb-12h-master-db-node-903af0db-1  !WARNING | scylla[5461]:  [shard 2:strm] repair - repair[5f4e4854-2871-4b5b-97b2-a2e1169eca20]: 1 out of 1 ranges failed, keyspace=keyspace1, tables=["standard1"], repair_reason=repair, nodes_down_during_repair={}, aborted_by_user=true, failed_because=N/A
2024-11-09T16:31:45.334+00:00 longevity-50gb-12h-master-db-node-903af0db-1  !WARNING | scylla[5461]:  [shard 2:strm] repair - repair[5f4e4854-2871-4b5b-97b2-a2e1169eca20]: Repair tablet for table=keyspace1.standard1 range=(-5188146770730811393,-4611686018427387905] status=failed: std::runtime_error (repair[5f4e4854-2871-4b5b-97b2-a2e1169eca20]: 1 out of 1 ranges failed, keyspace=keyspace1, tables=["standard1"], repair_reason=repair, nodes_down_during_repair={}, aborted_by_user=true, failed_because=N/A)
```
seems like test timeout need to be increased

*Describe your issue in detail and steps it took to produce it.*

## Impact

No visible impact on scylla

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-903af0db-7 (54.247.152.105 | 10.4.8.71) (shards: 8)
- longevity-50gb-12h-master-db-node-903af0db-6 (18.201.112.173 | 10.4.9.223) (shards: 9)
- longevity-50gb-12h-master-db-node-903af0db-5 (34.243.245.158 | 10.4.8.181) (shards: 12)
- longevity-50gb-12h-master-db-node-903af0db-4 (54.216.155.188 | 10.4.8.52) (shards: 10)
- longevity-50gb-12h-master-db-node-903af0db-3 (34.244.127.238 | 10.4.11.145) (shards: 11)
- longevity-50gb-12h-master-db-node-903af0db-2 (63.33.59.129 | 10.4.10.225) (shards: 9)
- longevity-50gb-12h-master-db-node-903af0db-1 (63.35.193.243 | 10.4.9.43) (shards: 8)

OS / Image: `ami-07f847bea92dccb9a` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `903af0db-f387-488e-b15d-886d1cb4c113`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/72a67ce96e506febf8f0e13bddc6d070c27cb3e4/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 903af0db-f387-488e-b15d-886d1cb4c113`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=903af0db-f387-488e-b15d-886d1cb4c113)
- Show all stored logs command: `$ hydra investigate show-logs 903af0db-f387-488e-b15d-886d1cb4c113`

## Logs:
- **longevity-50gb-12h-master-db-node-903af0db-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-5-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-5-903af0db.tar.gz)
- **longevity-50gb-12h-master-db-node-903af0db-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-6-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-6-903af0db.tar.gz)
- **longevity-50gb-12h-master-db-node-903af0db-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-2-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241109_040949/longevity-50gb-12h-master-db-node-903af0db-2-903af0db.tar.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-903af0db-1-2024-11-10_01-08-01.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.76f3d04b9e064af3873c01ddd42a3d72.31964.1731198289000000./core.scylla.106.76f3d04b9e064af3873c01ddd42a3d72.31964.1731198289000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.76f3d04b9e064af3873c01ddd42a3d72.31964.1731198289000000./core.scylla.106.76f3d04b9e064af3873c01ddd42a3d72.31964.1731198289000000.zst)
- **db-cluster-903af0db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/db-cluster-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/db-cluster-903af0db.tar.gz)
- **sct-runner-events-903af0db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/sct-runner-events-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/sct-runner-events-903af0db.tar.gz)
- **sct-903af0db.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/sct-903af0db.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/sct-903af0db.log.tar.gz)
- **loader-set-903af0db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/loader-set-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/loader-set-903af0db.tar.gz)
- **monitor-set-903af0db.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/monitor-set-903af0db.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/903af0db-f387-488e-b15d-886d1cb4c113/20241110_043042/monitor-set-903af0db.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/45/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=903af0db-f387-488e-b15d-886d1cb4c113)
</details>

**Comment by fruch** [comment]
in this nemeis is start reapir then uses API call to abort it

in:
https://github.com/scylladb/scylla-cluster-tests/issues/7226
it was no aborting all of the repairs (from nodetool command POV)

in this case, seem like stopping the repair on tablet really take a long time then it used to be abort repair
anyhow, this issue should go to scylla core

**Comment by bhalevy** [comment]
Cc @Deexie @denesb ☝

**Comment by Deexie** [comment]
Which API is used to abort repair in this nemesis?

**Comment by Deexie** [comment]
I opened https://github.com/scylladb/scylladb/issues/21612. It is relevant for this issue if the nemesis aborts repair using `/storage_service/force_terminate` or `/storage_service/force_terminate_repair`.

**Comment by temichus** [comment]
> Which API is used to abort repair in this nemesis?

self.target_node.remoter.run(
                    "curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json'"
                    " http://127.0.0.1:10000/storage_service/force_terminate_repair"
                )

**Comment by Deexie** [comment]
> > Which API is used to abort repair in this nemesis?
> 
> self.target_node.remoter.run( "curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json'" " http://127.0.0.1:10000/storage_service/force_terminate_repair" )
> 
> [@Deexie](https://github.com/Deexie) I thin we can close issue of SCT in this case, please confirm

Yes, I think so

**Comment by temichus** [comment]
bug in Core was opened https://github.com/scylladb/scylladb/issues/21612.
