### ISSUE TITLE
Fix failed nemesis to run only with data nodes

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#9277]
## Packages

Scylla version: `6.3.0~dev-20241115.5bc03da0c4c1` with build-id `616f46f4e7794bef8367877dfce801c0ddae5371`

Kernel Version: `6.8.0-1018-aws`

## Issue description

- [x] This issue is not a regression.
- [ ] It is unknown if this issue is a regression.

Need to fix nemesis to use only data nodes

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-9 (54.75.75.195 | 10.4.0.106) (shards: -1)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-8 (13.49.246.221 | 10.0.2.24) (shards: 2)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-7 (18.170.218.220 | 10.3.3.254) (shards: 2)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-6 (18.170.74.112 | 10.3.3.69) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-5 (3.8.173.78 | 10.3.3.79) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-4 (35.176.35.64 | 10.3.2.224) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-3 (34.245.5.52 | 10.4.2.8) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-2 (34.244.81.44 | 10.4.0.105) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-13 (34.252.27.143 | 10.4.1.185) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-12 (18.130.5.65 | 10.3.0.186) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-11 (3.250.169.219 | 10.4.2.87) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-10 (3.251.71.8 | 10.4.2.176) (shards: 14)
- multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-1 (108.129.183.102 | 10.4.1.221) (shards: 14)

OS / Image: `ami-01b1698557082262f ami-0dccc58abc9a782a1 ami-02f95ab5f9a3cf621` (aws: undefined_region)

Test: `longevity-multi-dc-rack-aware-zero-token-dc-test`
Test id: `86db9d07-0828-4e08-a96f-e3c2a82f9e35`
Test name: `scylla-master/tier1/longevity-multi-dc-rack-aware-zero-token-dc-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-multi-dc-rack-aware-with-znode-in-diff_dc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3c880d356e617d2de7b7ecaa53ab4d00c7061fd1/test-cases/longevity/longevity-multi-dc-rack-aware-with-znode-in-diff_dc.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 86db9d07-0828-4e08-a96f-e3c2a82f9e35`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=86db9d07-0828-4e08-a96f-e3c2a82f9e35)
- Show all stored logs command: `$ hydra investigate show-logs 86db9d07-0828-4e08-a96f-e3c2a82f9e35`

## Logs:
- **multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-9-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-9-86db9d07.tar.gz)
- **multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-1-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-1-86db9d07.tar.gz)
- **multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-10-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-10-86db9d07.tar.gz)
- **multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-11-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_080837/multi-dc-rackaware-with-znode-dc-ma-db-node-86db9d07-11-86db9d07.tar.gz)
- **db-cluster-86db9d07.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/db-cluster-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/db-cluster-86db9d07.tar.gz)
- **sct-runner-events-86db9d07.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/sct-runner-events-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/sct-runner-events-86db9d07.tar.gz)
- **sct-86db9d07.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/sct-86db9d07.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/sct-86db9d07.log.tar.gz)
- **loader-set-86db9d07.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/loader-set-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/loader-set-86db9d07.tar.gz)
- **monitor-set-86db9d07.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/monitor-set-86db9d07.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/86db9d07-0828-4e08-a96f-e3c2a82f9e35/20241116_204006/monitor-set-86db9d07.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-multi-dc-rack-aware-zero-token-dc-test/5/)
[Argus](https://argus.scylladb.com/test/7593a9ee-224a-49ec-af87-c2cdab1280d1/runs?additionalRuns[]=86db9d07-0828-4e08-a96f-e3c2a82f9e35)
</details>

**Comment by temichus** [comment]
2 PRs 

1. https://github.com/scylladb/scylla-cluster-tests/pull/9342
2. https://github.com/scylladb/scylla-cluster-tests/pull/9393
