### ISSUE TITLE
start_and_interrupt_decommission_streaming: log pattern no longer valid as a trigger

### ISSUE THREAD

**Issue by lersek** [scylladb/scylla-cluster-tests#9281]
(See the general description of the feature in #6181.)

As of commit d7ad4c87aa95, the log pattern `Finished token ring movement` in `ABORT_DECOMMISSION_LOG_PATTERNS` in `sdcm/utils/raft/__init__.py` is no longer valid. Scylla commit scylladb/scylladb@36520250623a ("storage_service: wire node_ops_ctl for node operations", 2023-03-09) changed `storage_service::decommission()` such that the function would not log the message any longer. (The log message had been introduced in scylla commit scylladb/scylladb@c3ed82e5fbaf, "service: storage_service: better error handling in `decommission`", 2023-01-17.)

As a consequence, if `start_and_interrupt_decommission_streaming -> target_node.raft.get_random_log_message` randomly chooses to pick this particular log message as a trigger, then watching the log for this message will time out inevitably.

I don't know if the message should be restored in scylla, or the log pattern should be removed from SCT.

@bhalevy @kbr-scylla @aleksbykov

**Comment by bhalevy** [comment]
I'd prefer to adjust the test if possible.

Also, in the future, please use `scylladb/scylladb@sha` for addressing a commit in a different repo
