### ISSUE TITLE
Testing "illegal" upgrades

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylla-cluster-tests#9330]
After digging into [enterprise-2024.2/rolling-upgrade/rolling-upgrade-ubuntu22.04-test#11](https://argus.scylladb.com/tests/scylla-cluster-tests/02f20a4d-63b9-42b5-9b95-2660dcf986f3)

This is upgrading from
```
Base scylla version: 6.0.4-20240919.7d421abec43d
```
to
```
Upgraded scylla version: 2024.2.0~rc2-20240904.4c26004e5311
```

However, 2024.2.0~rc2 is based on an older version of 6.0:

The last 6.0->2024.2 merge commit before this tag is scylladb/scylla-enterprise@aa9a8207a293405111966da9c0c160d9c3a09054
which is an ancestor of scylladb/scylladb@7d421abec43d == 6.0.4 (i.e. 6.0.4 is newer)

![Image](https://github.com/user-attachments/assets/a629f770-3c9d-4b14-b12f-962e821f33b1)

so it's like we're trying to "upgrade" from a newer version to an older version.

This is not something we can support I think, because e.g. the newer version could have some new RPC verbs, new cluster features and so on.

I don't know why the test was executed for this particular pair of versions, if it was by mistake or actual expectation, so creating this issue to figure it out

cc @mykaul @soyacz @fruch @avikivity

**Comment by kbr-scylla** [comment]
cc @timtimb0t

**Comment by roydahan** [comment]
For RC release it might be ok to have "illegal" path, however, if this is something that can happen in official 2024.2, it's a bug.
(Probably soon we may not have this issue anymore.)

**Comment by fruch** [comment]
1) this run is a retrigger, cause of issues we had with that pipeline, I was aiming on verifying it's now work, and didn't update the target version

2) those tests are designed to be triggered on every new build in a release, selecting targets manually can mismatch.

3) should we be more careful with introducing breaking changes (like introducing RPC verbs and such) across minor releases ? 

4) I wonder if we need to fix the race of syncing two products, maybe it would solve itself ?

**Comment by timtimb0t** [comment]
+ https://argus.scylladb.com/tests/scylla-cluster-tests/2a80fbea-0076-4e8b-b216-b7073e43ce1c

**Comment by roydahan** [comment]
@timtimb0t it should be opened as a scylla issue, not SCT issue.
There is no such thing illegal upgrade from 6.0 to 2024.2.0.

**Comment by mykaul** [comment]
> [@timtimb0t](https://github.com/timtimb0t) it should be opened as a scylla issue, not SCT issue. There is no such thing illegal upgrade from 6.0 to 2024.2.0.

Not if it was for an earlier RC of 2024.2.0. Does it work against the GA?

**Comment by timtimb0t** [comment]
@roydahan , @mykaul just want to clarify if scylla issue is required

**Comment by fruch** [comment]
> [@roydahan](https://github.com/roydahan) , [@mykaul](https://github.com/mykaul) just want to clarify if scylla issue is required

yes, what you are reporting is 6.0.4 GA -> 2024.2.0  GA, it's a scylla bug

not SCT,

closing this, since SCT isn't gonna introduce any guardrails about unsupported upgrades path.

**Comment by roydahan** [comment]
IIUC the replacement of this issue with a real issue is: https://github.com/scylladb/scylla-enterprise/issues/4740
