### ISSUE TITLE
Curl to download manager fails with option --retry-all-errors: is unknown on Azure

### ISSUE THREAD

**Issue by pehala** [scylladb/scylla-cluster-tests#9395]
LongevityTest.SetUp() and MonitorSetAzure throw:
```
Command: 'sudo curl -o /etc/apt/sources.list.d/scylla-manager.list -L https://downloads.scylladb.com/deb/debian/scylladb-manager-3.4.list --connect-timeout 10 --retry 5 --retry-all-errors --retry-max-time 100'
Exit code: 2
Stdout:
Stderr:
curl: option --retry-all-errors: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```
I see that this happened in two recent runs:
* https://argus.scylladb.com/tests/scylla-cluster-tests/8e8c53b6-8d6e-432f-802b-e80e81eaeb1d
* https://argus.scylladb.com/tests/scylla-cluster-tests/005503aa-d1c0-4763-ad14-23a40603a6d6

**Comment by fruch** [comment]
this flag was removed from code
