### ISSUE TITLE
Can't establish SSH connection to Scylla Cloud DB node via SCT

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#9427]
SCT fails to connect to DB node deployed in Scylla Cloud:
```
< t:2024-11-28 09:15:46,900 f:cluster.py      l:445  c:sdcm.cluster_baremetal p:DEBUG > Node longevity-small-set-1h-sct-inte-db-node-f6608939-1 [None | 172.29.96.179]: SSH access -> 'ssh -i ~/.ssh/scylla-cloud-cluster-7962 scyllaadm@172.29.96.179'
< t:2024-11-28 09:16:17,062 f:wait.py         l:52   c:sdcm.wait            p:DEBUG > wait_for: Retrying longevity-small-set-1h-sct-inte-db-node-f6608939-1: Waiting for SSH to be up: attempt 1 ended with: False
```

VPC and security groups are configured accordingly to allow ssh access from runner instance to the node.
And it works with the same key and credentials if to connect directly on runner instance (inside or outside a container):
![Image](https://github.com/user-attachments/assets/e8dd02fe-f05f-4a51-89cc-243932b6e12d)

According to @soyacz, the problem is that new Scylla server declines ssh-rsa signature algorithms - and this one is used by ssh2-python (used in SCT). Paramiko (which works well for the same case) uses rsa-sha2-256 or rsa-sha2-512 when authenticating with RSA keys.

Job - https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/siren-tests/job/siren-sct-integration/52/

**Comment by soyacz** [comment]
I tested it locally and found ssh2-python3 lib worked well (has updated libssh2 library, and should work with newer python versions) - this is a drop-in replacement.
@fruch we should consider moving to this one or create own fork (or both) - as anyway ssh2-python works with python 3.10 at max.

**Comment by fruch** [comment]
trying todo the switch in:
https://github.com/scylladb/scylla-cluster-tests/pull/9432

**Comment by mikliapko** [comment]
Fixed in https://github.com/scylladb/scylla-cluster-tests/pull/9432
