### ISSUE TITLE
name of nemesis to run is not logged

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla-cluster-tests#9520]
When choosing a new nemesis to run, the system logs the set of al nemesis that it will choose from, but not the actual nemesis that was picked.

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylla-cluster-tests/issues/6088 ?

**Comment by denesb** [comment]
Actually, it looks like I'm blind: https://github.com/scylladb/scylla-cluster-tests/issues/6088#issuecomment-2517977283.
