### ISSUE TITLE
Nemesis run() should check the termination event more often

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#958]
nemesis process can't be stop quickly enough, it's depended on duration of a nemesis run, and on the interval.
I think we should check the event multiple time, also before running the nemesis, and check it while we are waiting (maybe using wait_for with the interval as timeout)

```python
    def run(self, interval=30):
        interval *= 60
        self.log.info('Interval: %s s', interval)
        self.interval = interval
        while True:
            self._set_current_disruption(report=False)
            self.disrupt()
            if self.termination_event is not None:
                if self.termination_event.isSet():
                    self.termination_event = None
                    self.log.info('Asked to stop running nemesis')
                    break
            self.target_node.running_nemesis = None
            time.sleep(interval)
            self.set_target_node(is_running=True)
```

**Comment by bentsi** [comment]
The bottleneck is in `self.disrupt` call, I think moving the code before the `self.disrupt` can improve a bit the "sensitivity"  to the termination event but again the big issue is in `self.disrupt`. We will need to take this in consideration when redesigning Nemesis
