### ISSUE TITLE
SCT Events Annotation isn't working when using `reuse_cluster: true`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#977]
cause we are skipping the node_init we are not configuring the grafana url, and no annotation are sent to grafana
[ ] maybe the file of the annotation.json needs to be renamed to include date
[ ] check how `hydra investigate show-monitor` handle reuse_cluster` logging wise. @aleksbykov did you tried it ?

**Comment by aleksbykov** [comment]
@fruch No, this moment i don't tried. But if reuse-cluster is used, this means, that all nodes are configured already, and on teardown, sct collects all same logs and data. So i think there should be any issue with that. Will check

**Comment by fruch** [comment]
all of the data is overwritten, i.e. you'll loose the previous logs. i.e. you'll have only the last run information in s3, some of it might be a total of the info, like the prom snapshot, but db logs for example might be different (i.e. nodes that was decommissioned won't be there anymore for example, and you'll loose their logs)
